In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\\rheya_8e1lx53\\Projects\\Weather_Data.csv")
df

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
3267,6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
3268,6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
3269,6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [4]:
df=pd.read_excel("C:\\Users\\rheya_8e1lx53\\Projects\\Weather_Data.csv.xlsx")
df

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-01-02 00:00:00,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2008-02-02 00:00:00,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2008-03-02 00:00:00,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2008-04-02 00:00:00,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2008-05-02 00:00:00,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
3267,6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
3268,6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
3269,6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [5]:
df=pd.read_csv("C:\\Users\\rheya_8e1lx53\\Projects\\Weather_Data.csv")
data_list=df.to_dict(orient="list")
print(data_list)

{'Date': ['2/1/2008', '2/2/2008', '2/3/2008', '2/4/2008', '2/5/2008', '2/6/2008', '2/7/2008', '2/8/2008', '2/9/2008', '2/10/2008', '2/11/2008', '2/12/2008', '2/13/2008', '2/14/2008', '2/15/2008', '2/16/2008', '2/17/2008', '2/18/2008', '2/19/2008', '2/20/2008', '2/21/2008', '2/22/2008', '2/23/2008', '2/24/2008', '2/25/2008', '2/26/2008', '2/27/2008', '2/28/2008', '2/29/2008', '3/1/2008', '3/2/2008', '3/3/2008', '3/4/2008', '3/5/2008', '3/6/2008', '3/7/2008', '3/8/2008', '3/9/2008', '3/10/2008', '3/11/2008', '3/12/2008', '3/13/2008', '3/14/2008', '3/15/2008', '3/16/2008', '3/17/2008', '3/18/2008', '3/19/2008', '3/20/2008', '3/21/2008', '3/22/2008', '3/23/2008', '3/24/2008', '3/25/2008', '3/26/2008', '3/27/2008', '3/28/2008', '3/29/2008', '3/30/2008', '3/31/2008', '4/1/2008', '4/2/2008', '4/3/2008', '4/4/2008', '4/5/2008', '4/6/2008', '4/7/2008', '4/8/2008', '4/9/2008', '4/10/2008', '4/11/2008', '4/12/2008', '4/13/2008', '4/14/2008', '4/15/2008', '4/16/2008', '4/17/2008', '4/18/2008', '4/19/2008', '4/20/2008', '4/21/2008', '4/22/2008', '4/23/2008', '4/24/2008', '4/26/2008', '4/27/2008', '4/28/2008', '4/29/2008', '4/30/2008', '5/1/2008', '5/2/2008', '5/3/2008', '5/4/2008', '5/5/2008', '5/6/2008', '5/7/2008', '5/8/2008', '5/9/2008', '5/10/2008', '5/11/2008', '5/12/2008', '5/13/2008', '5/14/2008', '5/15/2008', '5/16/2008', '5/17/2008', '5/18/2008', '5/19/2008', '5/20/2008', '5/21/2008', '5/22/2008', '5/23/2008', '5/24/2008', '5/25/2008', '5/26/2008', '5/27/2008', '5/28/2008', '5/29/2008', '5/30/2008', '5/31/2008', '6/1/2008', '6/2/2008', '6/3/2008', '6/4/2008', '6/5/2008', '6/6/2008', '6/7/2008', '6/8/2008', '6/9/2008', '6/10/2008', '6/11/2008', '6/12/2008', '6/13/2008', '6/14/2008', '6/15/2008', '6/16/2008', '6/17/2008', '6/18/2008', '6/19/2008', '6/20/2008', '6/21/2008', '6/22/2008', '6/23/2008', '6/24/2008', '6/25/2008', '6/26/2008', '6/27/2008', '6/28/2008', '6/29/2008', '6/30/2008', '7/1/2008', '7/2/2008', '7/3/2008', '7/4/2008', '7/5/2008', '7/6/2008', '7/7/2008', '7/8/2008', '7/9/2008', '7/10/2008', '7/11/2008', '7/12/2008', '7/13/2008', '7/14/2008', '7/15/2008', '7/16/2008', '7/17/2008', '7/18/2008', '7/19/2008', '7/20/2008', '7/21/2008', '7/22/2008', '7/23/2008', '7/24/2008', '7/25/2008', '7/26/2008', '7/27/2008', '7/28/2008', '7/29/2008', '7/30/2008', '7/31/2008', '8/1/2008', '8/2/2008', '8/3/2008', '8/4/2008', '8/5/2008', '8/6/2008', '8/7/2008', '8/8/2008', '8/9/2008', '8/10/2008', '8/11/2008', '8/12/2008', '8/13/2008', '8/14/2008', '8/15/2008', '8/16/2008', '8/17/2008', '8/18/2008', '8/19/2008', '8/20/2008', '8/21/2008', '8/22/2008', '8/23/2008', '8/24/2008', '8/25/2008', '8/26/2008', '8/28/2008', '8/29/2008', '8/30/2008', '8/31/2008', '9/1/2008', '9/2/2008', '9/3/2008', '9/4/2008', '9/5/2008', '9/6/2008', '9/7/2008', '9/8/2008', '9/9/2008', '9/10/2008', '9/11/2008', '9/12/2008', '9/13/2008', '9/14/2008', '9/15/2008', '9/16/2008', '9/17/2008', '9/18/2008', '9/19/2008', '9/20/2008', '9/21/2008', '9/22/2008', '9/23/2008', '9/24/2008', '9/25/2008', '9/26/2008', '9/27/2008', '9/28/2008', '9/29/2008', '9/30/2008', '10/1/2008', '10/2/2008', '10/3/2008', '10/4/2008', '10/5/2008', '10/6/2008', '10/7/2008', '10/8/2008', '10/9/2008', '10/10/2008', '10/11/2008', '10/12/2008', '10/13/2008', '10/14/2008', '10/15/2008', '10/16/2008', '10/17/2008', '10/18/2008', '10/19/2008', '10/20/2008', '10/21/2008', '10/22/2008', '10/23/2008', '10/24/2008', '10/25/2008', '10/26/2008', '10/27/2008', '10/28/2008', '10/29/2008', '10/30/2008', '10/31/2008', '11/1/2008', '11/2/2008', '11/3/2008', '11/4/2008', '11/5/2008', '11/6/2008', '11/7/2008', '11/8/2008', '11/9/2008', '11/10/2008', '11/11/2008', '11/12/2008', '11/13/2008', '11/14/2008', '11/15/2008', '11/16/2008', '11/17/2008', '11/18/2008', '11/19/2008', '11/20/2008', '11/21/2008', '11/22/2008', '11/23/2008', '11/24/2008', '11/25/2008', '11/26/2008', '11/27/2008', '11/28/2008', '11/29/2008', '11/30/2008', '12/1/2008', '12/2/2008', '12/3/2008', '12/4/2008', '12/5/2008', '12/6/2008', '12/7/2008', '12/8/2008', '12/9/2008', '12/10/2008', '12/11/2008', '12/12/2008', '12/13/2008', '12/14/2008', '12/15/2008', '12/16/2008', '12/17/2008', '12/18/2008', '12/19/2008', '12/20/2008', '12/21/2008', '12/22/2008', '12/23/2008', '12/24/2008', '12/25/2008', '12/26/2008', '12/27/2008', '12/28/2008', '12/29/2008', '12/30/2008', '12/31/2008', '1/1/2009', '1/2/2009', '1/3/2009', '1/4/2009', '1/5/2009', '1/6/2009', '1/7/2009', '1/8/2009', '1/9/2009', '1/10/2009', '1/11/2009', '1/12/2009', '1/13/2009', '1/14/2009', '1/15/2009', '1/16/2009', '1/17/2009', '1/18/2009', '1/19/2009', '1/20/2009', '1/21/2009', '1/22/2009', '1/23/2009', '1/24/2009', '1/25/2009', '1/26/2009', '1/27/2009', '1/28/2009', '1/29/2009', '1/30/2009', '1/31/2009', '2/1/2009', '2/2/2009', '2/3/2009', '2/4/2009', '2/5/2009', '2/6/2009', '2/7/2009', '2/8/2009', '2/9/2009', '2/10/2009', '2/11/2009', '2/12/2009', '2/13/2009', '2/14/2009', '2/15/2009', '2/16/2009', '2/17/2009', '2/18/2009', '2/19/2009', '2/20/2009', '2/21/2009', '2/22/2009', '2/23/2009', '2/24/2009', '2/25/2009', '2/26/2009', '2/27/2009', '2/28/2009', '3/1/2009', '3/2/2009', '3/3/2009', '3/4/2009', '3/5/2009', '3/6/2009', '3/7/2009', '3/8/2009', '3/9/2009', '3/10/2009', '3/11/2009', '3/12/2009', '3/13/2009', '3/14/2009', '3/15/2009', '3/16/2009', '3/17/2009', '3/18/2009', '3/19/2009', '3/20/2009', '3/21/2009', '3/22/2009', '3/23/2009', '3/24/2009', '3/25/2009', '3/26/2009', '3/27/2009', '3/28/2009', '3/29/2009', '3/30/2009', '3/31/2009', '4/1/2009', '4/2/2009', '4/3/2009', '4/4/2009', '4/5/2009', '4/6/2009', '4/7/2009', '4/8/2009', '4/9/2009', '4/10/2009', '4/11/2009', '4/13/2009', '4/14/2009', '4/15/2009', '4/16/2009', '4/17/2009', '4/18/2009', '4/19/2009', '4/20/2009', '4/21/2009', '4/22/2009', '4/23/2009', '4/24/2009', '4/25/2009', '4/26/2009', '4/27/2009', '4/28/2009', '4/29/2009', '4/30/2009', '5/1/2009', '5/2/2009', '5/3/2009', '5/4/2009', '5/5/2009', '5/6/2009', '5/7/2009', '5/8/2009', '5/9/2009', '5/10/2009', '5/11/2009', '5/12/2009', '5/13/2009', '5/14/2009', '5/15/2009', '5/16/2009', '5/17/2009', '5/18/2009', '5/19/2009', '5/20/2009', '5/21/2009', '5/22/2009', '5/23/2009', '5/24/2009', '5/25/2009', '5/26/2009', '5/27/2009', '5/28/2009', '5/29/2009', '5/30/2009', '5/31/2009', '6/1/2009', '6/2/2009', '6/3/2009', '6/4/2009', '6/5/2009', '6/6/2009', '6/7/2009', '6/8/2009', '6/9/2009', '6/10/2009', '6/11/2009', '6/12/2009', '6/13/2009', '6/14/2009', '6/15/2009', '6/16/2009', '6/17/2009', '6/18/2009', '6/19/2009', '6/20/2009', '6/21/2009', '6/22/2009', '6/23/2009', '6/24/2009', '6/25/2009', '6/26/2009', '6/27/2009', '6/28/2009', '6/29/2009', '6/30/2009', '7/1/2009', '7/2/2009', '7/3/2009', '7/4/2009', '7/5/2009', '7/6/2009', '7/7/2009', '7/8/2009', '7/9/2009', '7/10/2009', '7/11/2009', '7/12/2009', '7/13/2009', '7/14/2009', '7/15/2009', '7/16/2009', '7/17/2009', '7/18/2009', '7/19/2009', '7/20/2009', '7/21/2009', '7/22/2009', '7/23/2009', '7/24/2009', '7/25/2009', '7/26/2009', '7/27/2009', '7/28/2009', '7/29/2009', '7/30/2009', '7/31/2009', '8/1/2009', '8/2/2009', '8/3/2009', '8/4/2009', '8/5/2009', '8/6/2009', '8/7/2009', '8/8/2009', '8/9/2009', '8/10/2009', '8/11/2009', '8/12/2009', '8/13/2009', '8/14/2009', '8/15/2009', '8/16/2009', '8/17/2009', '8/18/2009', '8/19/2009', '8/20/2009', '8/21/2009', '8/22/2009', '8/23/2009', '8/24/2009', '8/25/2009', '8/26/2009', '8/27/2009', '8/28/2009', '8/29/2009', '8/30/2009', '8/31/2009', '9/1/2009', '9/2/2009', '9/3/2009', '9/4/2009', '9/5/2009', '9/6/2009', '9/7/2009', '9/8/2009', '9/9/2009', '9/10/2009', '9/11/2009', '9/12/2009', '9/13/2009', '9/14/2009', '9/15/2009', '9/16/2009', '9/17/2009', '9/18/2009', '9/19/2009', '9/20/2009', '9/21/2009', '9/22/2009', '9/23/2009', '9/24/2009', '9/25/2009', '9/26/2009', '9/27/2009', '9/28/2009', '9/29/2009', '9/30/2009', '10/1/2009', '10/2/2009', '10/3/2009', '10/4/2009', '10/5/2009', '10/6/2009', '10/7/2009', '10/8/2009', '10/9/2009', '10/10/2009', '10/11/2009', '10/12/2009', '10/13/2009', '10/14/2009', '10/15/2009', '10/16/2009', '10/17/2009', '10/18/2009', '10/19/2009', '10/20/2009', '10/21/2009', '10/22/2009', '10/23/2009', '10/24/2009', '10/25/2009', '10/26/2009', '10/27/2009', '10/30/2009', '10/31/2009', '11/1/2009', '11/2/2009', '11/3/2009', '11/4/2009', '11/5/2009', '11/6/2009', '11/7/2009', '11/8/2009', '11/9/2009', '11/10/2009', '11/11/2009', '11/12/2009', '11/13/2009', '11/14/2009', '11/15/2009', '11/16/2009', '11/17/2009', '11/18/2009', '11/19/2009', '11/20/2009', '11/21/2009', '11/22/2009', '11/23/2009', '11/24/2009', '11/25/2009', '11/26/2009', '11/27/2009', '11/28/2009', '11/29/2009', '11/30/2009', '12/1/2009', '12/2/2009', '12/3/2009', '12/4/2009', '12/5/2009', '12/6/2009', '12/7/2009', '12/8/2009', '12/9/2009', '12/10/2009', '12/11/2009', '12/12/2009', '12/13/2009', '12/14/2009', '12/15/2009', '12/16/2009', '12/17/2009', '12/18/2009', '12/19/2009', '12/20/2009', '12/21/2009', '12/22/2009', '12/26/2009', '12/27/2009', '12/28/2009', '12/29/2009', '12/30/2009', '12/31/2009', '1/1/2010', '1/2/2010', '1/3/2010', '1/4/2010', '1/5/2010', '1/6/2010', '1/7/2010', '1/8/2010', '1/9/2010', '1/10/2010', '1/11/2010', '1/12/2010', '1/13/2010', '1/14/2010', '1/15/2010', '1/16/2010', '1/17/2010', '1/18/2010', '1/19/2010', '1/20/2010', '1/21/2010', '1/22/2010', '1/23/2010', '1/24/2010', '1/25/2010', '1/26/2010', '1/27/2010', '1/28/2010', '1/29/2010', '1/30/2010', '1/31/2010', '2/1/2010', '2/2/2010', '2/3/2010', '2/4/2010', '2/5/2010', '2/6/2010', '2/7/2010', '2/8/2010', '2/9/2010', '2/10/2010', '2/11/2010', '2/12/2010', '2/13/2010', '2/14/2010', '2/15/2010', '2/16/2010', '2/17/2010', '2/18/2010', '2/19/2010', '2/20/2010', '2/21/2010', '2/22/2010', '2/23/2010', '2/24/2010', '2/25/2010', '2/26/2010', '2/27/2010', '2/28/2010', '3/1/2010', '3/2/2010', '3/3/2010', '3/4/2010', '3/5/2010', '3/6/2010', '3/7/2010', '3/8/2010', '3/9/2010', '3/10/2010', '3/11/2010', '3/12/2010', '3/13/2010', '3/14/2010', '3/15/2010', '3/16/2010', '3/17/2010', '3/18/2010', '3/19/2010', '3/20/2010', '3/21/2010', '3/22/2010', '3/23/2010', '3/24/2010', '3/25/2010', '3/26/2010', '3/27/2010', '3/28/2010', '3/29/2010', '3/30/2010', '3/31/2010', '4/1/2010', '4/2/2010', '4/3/2010', '4/4/2010', '4/5/2010', '4/6/2010', '4/7/2010', '4/8/2010', '4/9/2010', '4/10/2010', '4/11/2010', '4/12/2010', '4/13/2010', '4/14/2010', '4/15/2010', '4/16/2010', '4/17/2010', '4/19/2010', '4/20/2010', '4/21/2010', '4/22/2010', '4/23/2010', '4/24/2010', '4/25/2010', '4/26/2010', '4/27/2010', '4/28/2010', '4/29/2010', '4/30/2010', '5/1/2010', '5/2/2010', '5/3/2010', '5/4/2010', '5/5/2010', '5/6/2010', '5/7/2010', '5/8/2010', '5/9/2010', '5/10/2010', '5/11/2010', '5/12/2010', '5/13/2010', '5/14/2010', '5/15/2010', '5/16/2010', '5/17/2010', '5/18/2010', '5/19/2010', '5/20/2010', '5/21/2010', '5/22/2010', '5/23/2010', '5/24/2010', '5/25/2010', '5/26/2010', '5/27/2010', '5/28/2010', '5/29/2010', '5/30/2010', '5/31/2010', '6/1/2010', '6/2/2010', '6/3/2010', '6/4/2010', '6/5/2010', '6/6/2010', '6/7/2010', '6/8/2010', '6/9/2010', '6/10/2010', '6/11/2010', '6/12/2010', '6/13/2010', '6/14/2010', '6/15/2010', '6/16/2010', '6/17/2010', '6/20/2010', '6/21/2010', '6/23/2010', '6/24/2010', '6/25/2010', '6/26/2010', '6/27/2010', '6/28/2010', '6/29/2010', '6/30/2010', '7/1/2010', '7/2/2010', '7/3/2010', '7/4/2010', '7/5/2010', '7/6/2010', '7/7/2010', '7/9/2010', '7/10/2010', '7/11/2010', '7/12/2010', '7/13/2010', '7/14/2010', '7/15/2010', '7/16/2010', '7/17/2010', '7/18/2010', '7/19/2010', '7/20/2010', '7/21/2010', '7/22/2010', '7/23/2010', '7/24/2010', '7/25/2010', '7/26/2010', '7/27/2010', '7/28/2010', '7/29/2010', '7/30/2010', '7/31/2010', '8/1/2010', '8/2/2010', '8/3/2010', '8/4/2010', '8/5/2010', '8/6/2010', '8/7/2010', '8/8/2010', '8/9/2010', '8/10/2010', '8/11/2010', '8/12/2010', '8/13/2010', '8/14/2010', '8/15/2010', '8/16/2010', '8/17/2010', '8/18/2010', '8/19/2010', '8/20/2010', '8/21/2010', '8/22/2010', '8/23/2010', '8/24/2010', '8/25/2010', '8/26/2010', '8/27/2010', '8/28/2010', '8/30/2010', '8/31/2010', '9/1/2010', '9/2/2010', '9/3/2010', '9/4/2010', '9/5/2010', '9/6/2010', '9/7/2010', '9/8/2010', '9/9/2010', '9/10/2010', '9/11/2010', '9/12/2010', '9/13/2010', '9/14/2010', '9/16/2010', '9/17/2010', '9/18/2010', '9/19/2010', '9/20/2010', '9/21/2010', '9/22/2010', '9/23/2010', '9/24/2010', '9/25/2010', '9/26/2010', '10/2/2010', '10/3/2010', '10/4/2010', '10/14/2010', '10/15/2010', '10/16/2010', '10/17/2010', '10/20/2010', '10/21/2010', '10/22/2010', '10/23/2010', '10/24/2010', '10/26/2010', '10/27/2010', '10/28/2010', '10/29/2010', '10/30/2010', '10/31/2010', '11/1/2010', '11/2/2010', '11/3/2010', '11/4/2010', '11/5/2010', '11/6/2010', '11/7/2010', '11/8/2010', '11/9/2010', '11/10/2010', '11/11/2010', '11/14/2010', '11/15/2010', '11/16/2010', '11/17/2010', '11/18/2010', '11/19/2010', '11/22/2010', '11/24/2010', '11/25/2010', '11/26/2010', '11/27/2010', '11/28/2010', '11/29/2010', '11/30/2010', '12/1/2010', '12/2/2010', '12/3/2010', '12/4/2010', '12/6/2010', '12/7/2010', '12/8/2010', '12/9/2010', '12/10/2010', '12/11/2010', '12/12/2010', '12/13/2010', '12/15/2010', '12/16/2010', '12/17/2010', '12/18/2010', '12/19/2010', '12/20/2010', '12/21/2010', '12/22/2010', '12/23/2010', '12/24/2010', '12/25/2010', '12/26/2010', '12/27/2010', '12/28/2010', '12/29/2010', '12/30/2010', '12/31/2010', '1/1/2011', '1/2/2011', '1/3/2011', '1/4/2011', '1/5/2011', '1/6/2011', '1/7/2011', '1/8/2011', '1/9/2011', '1/10/2011', '1/11/2011', '1/12/2011', '1/13/2011', '1/14/2011', '1/15/2011', '1/16/2011', '1/17/2011', '1/18/2011', '1/19/2011', '1/20/2011', '1/21/2011', '1/22/2011', '1/23/2011', '1/24/2011', '1/25/2011', '1/26/2011', '1/27/2011', '1/28/2011', '1/29/2011', '1/30/2011', '1/31/2011', '2/1/2011', '2/2/2011', '2/3/2011', '2/4/2011', '2/5/2011', '2/6/2011', '2/7/2011', '2/8/2011', '2/9/2011', '2/10/2011', '2/11/2011', '2/12/2011', '2/13/2011', '2/14/2011', '2/15/2011', '2/16/2011', '2/17/2011', '2/18/2011', '2/19/2011', '2/20/2011', '2/21/2011', '2/22/2011', '2/23/2011', '2/24/2011', '2/25/2011', '2/26/2011', '2/27/2011', '2/28/2011', '3/1/2011', '3/2/2011', '3/3/2011', '3/4/2011', '3/5/2011', '3/6/2011', '3/7/2011', '3/8/2011', '3/9/2011', '3/10/2011', '3/11/2011', '3/12/2011', '3/13/2011', '3/14/2011', '3/15/2011', '3/16/2011', '3/17/2011', '3/18/2011', '3/19/2011', '3/20/2011', '3/21/2011', '3/22/2011', '3/23/2011', '3/24/2011', '3/25/2011', '3/26/2011', '3/27/2011', '3/28/2011', '3/29/2011', '3/30/2011', '3/31/2011', '5/1/2011', '5/2/2011', '5/3/2011', '5/4/2011', '5/5/2011', '5/6/2011', '5/7/2011', '5/8/2011', '5/9/2011', '5/10/2011', '5/11/2011', '5/12/2011', '5/13/2011', '5/14/2011', '5/15/2011', '5/16/2011', '5/17/2011', '5/18/2011', '5/19/2011', '5/20/2011', '5/21/2011', '5/22/2011', '5/23/2011', '5/24/2011', '5/25/2011', '5/26/2011', '5/27/2011', '5/28/2011', '5/29/2011', '5/30/2011', '5/31/2011', '6/1/2011', '6/2/2011', '6/3/2011', '6/4/2011', '6/5/2011', '6/6/2011', '6/7/2011', '6/8/2011', '6/9/2011', '6/10/2011', '6/11/2011', '6/12/2011', '6/13/2011', '6/14/2011', '6/15/2011', '6/16/2011', '6/17/2011', '6/18/2011', '6/19/2011', '6/20/2011', '6/21/2011', '6/22/2011', '6/23/2011', '6/24/2011', '6/25/2011', '6/26/2011', '6/27/2011', '6/28/2011', '6/29/2011', '6/30/2011', '7/1/2011', '7/2/2011', '7/3/2011', '7/4/2011', '7/5/2011', '7/6/2011', '7/7/2011', '7/8/2011', '7/9/2011', '7/10/2011', '7/11/2011', '7/12/2011', '7/13/2011', '7/14/2011', '7/15/2011', '7/16/2011', '7/17/2011', '7/18/2011', '7/19/2011', '7/20/2011', '7/21/2011', '7/22/2011', '7/23/2011', '7/24/2011', '7/25/2011', '7/26/2011', '7/27/2011', '7/28/2011', '7/29/2011', '7/30/2011', '7/31/2011', '8/1/2011', '8/2/2011', '8/3/2011', '8/4/2011', '8/5/2011', '8/6/2011', '8/7/2011', '8/8/2011', '8/9/2011', '8/10/2011', '8/11/2011', '8/12/2011', '8/13/2011', '8/14/2011', '8/15/2011', '8/16/2011', '8/17/2011', '8/18/2011', '8/19/2011', '8/20/2011', '8/21/2011', '8/22/2011', '8/23/2011', '8/24/2011', '8/25/2011', '8/26/2011', '8/27/2011', '8/28/2011', '8/29/2011', '8/30/2011', '8/31/2011', '9/1/2011', '9/2/2011', '9/3/2011', '9/4/2011', '9/5/2011', '9/6/2011', '9/7/2011', '9/8/2011', '9/9/2011', '9/10/2011', '9/11/2011', '9/12/2011', '9/13/2011', '9/14/2011', '9/15/2011', '9/16/2011', '9/17/2011', '9/18/2011', '9/19/2011', '9/20/2011', '9/21/2011', '9/22/2011', '9/23/2011', '9/24/2011', '9/25/2011', '9/26/2011', '9/27/2011', '9/28/2011', '9/29/2011', '9/30/2011', '10/1/2011', '10/2/2011', '10/3/2011', '10/4/2011', '10/5/2011', '10/6/2011', '10/7/2011', '10/8/2011', '10/9/2011', '10/10/2011', '10/11/2011', '10/12/2011', '10/13/2011', '10/14/2011', '10/15/2011', '10/16/2011', '10/17/2011', '10/18/2011', '10/19/2011', '10/20/2011', '10/21/2011', '10/22/2011', '10/23/2011', '10/24/2011', '10/25/2011', '10/26/2011', '10/27/2011', '10/28/2011', '10/29/2011', '10/30/2011', '10/31/2011', '11/1/2011', '11/2/2011', '11/3/2011', '11/4/2011', '11/5/2011', '11/6/2011', '11/7/2011', '11/8/2011', '11/9/2011', '11/10/2011', '11/11/2011', '11/12/2011', '11/15/2011', '11/16/2011', '11/17/2011', '11/18/2011', '11/19/2011', '11/20/2011', '11/21/2011', '11/22/2011', '11/23/2011', '11/24/2011', '11/25/2011', '11/26/2011', '11/27/2011', '11/28/2011', '11/29/2011', '11/30/2011', '12/1/2011', '12/2/2011', '12/3/2011', '12/4/2011', '12/5/2011', '12/6/2011', '12/7/2011', '12/8/2011', '12/9/2011', '12/10/2011', '12/11/2011', '12/12/2011', '12/13/2011', '12/14/2011', '12/15/2011', '12/16/2011', '12/17/2011', '12/18/2011', '12/19/2011', '12/20/2011', '12/21/2011', '12/22/2011', '12/23/2011', '12/24/2011', '12/25/2011', '12/26/2011', '12/27/2011', '12/28/2011', '12/29/2011', '12/30/2011', '12/31/2011', '1/1/2012', '1/2/2012', '1/3/2012', '1/4/2012', '1/5/2012', '1/6/2012', '1/7/2012', '1/8/2012', '1/9/2012', '1/10/2012', '1/11/2012', '1/12/2012', '1/13/2012', '1/14/2012', '1/15/2012', '1/16/2012', '1/17/2012', '1/18/2012', '1/20/2012', '1/21/2012', '1/22/2012', '1/23/2012', '1/24/2012', '1/25/2012', '1/26/2012', '1/27/2012', '1/28/2012', '1/29/2012', '1/30/2012', '1/31/2012', '2/1/2012', '2/2/2012', '2/3/2012', '2/4/2012', '2/5/2012', '2/6/2012', '2/7/2012', '2/8/2012', '2/9/2012', '2/10/2012', '2/11/2012', '2/12/2012', '2/13/2012', '2/14/2012', '2/15/2012', '2/16/2012', '2/17/2012', '2/18/2012', '2/19/2012', '2/20/2012', '2/21/2012', '2/22/2012', '2/23/2012', '2/24/2012', '2/25/2012', '2/26/2012', '2/27/2012', '2/28/2012', '2/29/2012', '3/1/2012', '3/2/2012', '3/3/2012', '3/4/2012', '3/5/2012', '3/6/2012', '3/7/2012', '3/8/2012', '3/9/2012', '3/10/2012', '3/11/2012', '3/12/2012', '3/13/2012', '3/14/2012', '3/15/2012', '3/16/2012', '3/17/2012', '3/18/2012', '3/19/2012', '3/20/2012', '3/21/2012', '3/22/2012', '3/23/2012', '3/24/2012', '3/25/2012', '3/26/2012', '3/27/2012', '3/28/2012', '3/29/2012', '3/30/2012', '3/31/2012', '4/1/2012', '4/2/2012', '4/3/2012', '4/4/2012', '4/5/2012', '4/6/2012', '4/7/2012', '4/8/2012', '4/9/2012', '4/10/2012', '4/11/2012', '4/12/2012', '4/13/2012', '4/14/2012', '4/15/2012', '4/16/2012', '4/17/2012', '4/18/2012', '4/19/2012', '4/20/2012', '4/21/2012', '4/23/2012', '4/24/2012', '4/25/2012', '4/26/2012', '4/27/2012', '4/28/2012', '4/29/2012', '4/30/2012', '5/1/2012', '5/2/2012', '5/3/2012', '5/4/2012', '5/5/2012', '5/6/2012', '5/7/2012', '5/8/2012', '5/9/2012', '5/10/2012', '5/11/2012', '5/12/2012', '5/13/2012', '5/14/2012', '5/15/2012', '5/16/2012', '5/17/2012', '5/18/2012', '5/19/2012', '5/20/2012', '5/21/2012', '5/22/2012', '5/23/2012', '5/24/2012', '5/25/2012', '5/26/2012', '5/27/2012', '5/28/2012', '5/29/2012', '5/30/2012', '5/31/2012', '6/1/2012', '6/2/2012', '6/3/2012', '6/4/2012', '6/5/2012', '6/6/2012', '6/7/2012', '6/8/2012', '6/9/2012', '6/10/2012', '6/11/2012', '6/12/2012', '6/13/2012', '6/14/2012', '6/15/2012', '6/16/2012', '6/17/2012', '6/18/2012', '6/19/2012', '6/20/2012', '6/21/2012', '6/22/2012', '6/23/2012', '6/24/2012', '6/26/2012', '6/27/2012', '6/28/2012', '6/29/2012', '6/30/2012', '7/1/2012', '7/2/2012', '7/3/2012', '7/4/2012', '7/5/2012', '7/6/2012', '7/7/2012', '7/8/2012', '7/9/2012', '7/10/2

In [3]:
import pandas as pd
weather_dict={'Date': ['2/1/2008', '2/2/2008', '2/3/2008', '2/4/2008', '2/5/2008', '2/6/2008', '2/7/2008', '2/8/2008', '2/9/2008', '2/10/2008', '2/11/2008', '2/12/2008', '2/13/2008', '2/14/2008', '2/15/2008', '2/16/2008', '2/17/2008', '2/18/2008', '2/19/2008', '2/20/2008', '2/21/2008', '2/22/2008', '2/23/2008', '2/24/2008', '2/25/2008', '2/26/2008', '2/27/2008', '2/28/2008', '2/29/2008', '3/1/2008', '3/2/2008', '3/3/2008', '3/4/2008', '3/5/2008', '3/6/2008', '3/7/2008', '3/8/2008', '3/9/2008', '3/10/2008', '3/11/2008', '3/12/2008', '3/13/2008', '3/14/2008', '3/15/2008', '3/16/2008', '3/17/2008', '3/18/2008', '3/19/2008', '3/20/2008', '3/21/2008', '3/22/2008', '3/23/2008', '3/24/2008', '3/25/2008', '3/26/2008', '3/27/2008', '3/28/2008', '3/29/2008', '3/30/2008', '3/31/2008', '4/1/2008', '4/2/2008', '4/3/2008', '4/4/2008', '4/5/2008', '4/6/2008', '4/7/2008', '4/8/2008', '4/9/2008', '4/10/2008', '4/11/2008', '4/12/2008', '4/13/2008', '4/14/2008', '4/15/2008', '4/16/2008', '4/17/2008', '4/18/2008', '4/19/2008', '4/20/2008', '4/21/2008', '4/22/2008', '4/23/2008', '4/24/2008', '4/26/2008', '4/27/2008', '4/28/2008', '4/29/2008', '4/30/2008', '5/1/2008', '5/2/2008', '5/3/2008', '5/4/2008', '5/5/2008', '5/6/2008', '5/7/2008', '5/8/2008', '5/9/2008', '5/10/2008', '5/11/2008', '5/12/2008', '5/13/2008', '5/14/2008', '5/15/2008', '5/16/2008', '5/17/2008', '5/18/2008', '5/19/2008', '5/20/2008', '5/21/2008', '5/22/2008', '5/23/2008', '5/24/2008', '5/25/2008', '5/26/2008', '5/27/2008', '5/28/2008', '5/29/2008', '5/30/2008', '5/31/2008', '6/1/2008', '6/2/2008', '6/3/2008', '6/4/2008', '6/5/2008', '6/6/2008', '6/7/2008', '6/8/2008', '6/9/2008', '6/10/2008', '6/11/2008', '6/12/2008', '6/13/2008', '6/14/2008', '6/15/2008', '6/16/2008', '6/17/2008', '6/18/2008', '6/19/2008', '6/20/2008', '6/21/2008', '6/22/2008', '6/23/2008', '6/24/2008', '6/25/2008', '6/26/2008', '6/27/2008', '6/28/2008', '6/29/2008', '6/30/2008', '7/1/2008', '7/2/2008', '7/3/2008', '7/4/2008', '7/5/2008', '7/6/2008', '7/7/2008', '7/8/2008', '7/9/2008', '7/10/2008', '7/11/2008', '7/12/2008', '7/13/2008', '7/14/2008', '7/15/2008', '7/16/2008', '7/17/2008', '7/18/2008', '7/19/2008', '7/20/2008', '7/21/2008', '7/22/2008', '7/23/2008', '7/24/2008', '7/25/2008', '7/26/2008', '7/27/2008', '7/28/2008', '7/29/2008', '7/30/2008', '7/31/2008', '8/1/2008', '8/2/2008', '8/3/2008', '8/4/2008', '8/5/2008', '8/6/2008', '8/7/2008', '8/8/2008', '8/9/2008', '8/10/2008', '8/11/2008', '8/12/2008', '8/13/2008', '8/14/2008', '8/15/2008', '8/16/2008', '8/17/2008', '8/18/2008', '8/19/2008', '8/20/2008', '8/21/2008', '8/22/2008', '8/23/2008', '8/24/2008', '8/25/2008', '8/26/2008', '8/28/2008', '8/29/2008', '8/30/2008', '8/31/2008', '9/1/2008', '9/2/2008', '9/3/2008', '9/4/2008', '9/5/2008', '9/6/2008', '9/7/2008', '9/8/2008', '9/9/2008', '9/10/2008', '9/11/2008', '9/12/2008', '9/13/2008', '9/14/2008', '9/15/2008', '9/16/2008', '9/17/2008', '9/18/2008', '9/19/2008', '9/20/2008', '9/21/2008', '9/22/2008', '9/23/2008', '9/24/2008', '9/25/2008', '9/26/2008', '9/27/2008', '9/28/2008', '9/29/2008', '9/30/2008', '10/1/2008', '10/2/2008', '10/3/2008', '10/4/2008', '10/5/2008', '10/6/2008', '10/7/2008', '10/8/2008', '10/9/2008', '10/10/2008', '10/11/2008', '10/12/2008', '10/13/2008', '10/14/2008', '10/15/2008', '10/16/2008', '10/17/2008', '10/18/2008', '10/19/2008', '10/20/2008', '10/21/2008', '10/22/2008', '10/23/2008', '10/24/2008', '10/25/2008', '10/26/2008', '10/27/2008', '10/28/2008', '10/29/2008', '10/30/2008', '10/31/2008', '11/1/2008', '11/2/2008', '11/3/2008', '11/4/2008', '11/5/2008', '11/6/2008', '11/7/2008', '11/8/2008', '11/9/2008', '11/10/2008', '11/11/2008', '11/12/2008', '11/13/2008', '11/14/2008', '11/15/2008', '11/16/2008', '11/17/2008', '11/18/2008', '11/19/2008', '11/20/2008', '11/21/2008', '11/22/2008', '11/23/2008', '11/24/2008', '11/25/2008', '11/26/2008', '11/27/2008', '11/28/2008', '11/29/2008', '11/30/2008', '12/1/2008', '12/2/2008', '12/3/2008', '12/4/2008', '12/5/2008', '12/6/2008', '12/7/2008', '12/8/2008', '12/9/2008', '12/10/2008', '12/11/2008', '12/12/2008', '12/13/2008', '12/14/2008', '12/15/2008', '12/16/2008', '12/17/2008', '12/18/2008', '12/19/2008', '12/20/2008', '12/21/2008', '12/22/2008', '12/23/2008', '12/24/2008', '12/25/2008', '12/26/2008', '12/27/2008', '12/28/2008', '12/29/2008', '12/30/2008', '12/31/2008', '1/1/2009', '1/2/2009', '1/3/2009', '1/4/2009', '1/5/2009', '1/6/2009', '1/7/2009', '1/8/2009', '1/9/2009', '1/10/2009', '1/11/2009', '1/12/2009', '1/13/2009', '1/14/2009', '1/15/2009', '1/16/2009', '1/17/2009', '1/18/2009', '1/19/2009', '1/20/2009', '1/21/2009', '1/22/2009', '1/23/2009', '1/24/2009', '1/25/2009', '1/26/2009', '1/27/2009', '1/28/2009', '1/29/2009', '1/30/2009', '1/31/2009', '2/1/2009', '2/2/2009', '2/3/2009', '2/4/2009', '2/5/2009', '2/6/2009', '2/7/2009', '2/8/2009', '2/9/2009', '2/10/2009', '2/11/2009', '2/12/2009', '2/13/2009', '2/14/2009', '2/15/2009', '2/16/2009', '2/17/2009', '2/18/2009', '2/19/2009', '2/20/2009', '2/21/2009', '2/22/2009', '2/23/2009', '2/24/2009', '2/25/2009', '2/26/2009', '2/27/2009', '2/28/2009', '3/1/2009', '3/2/2009', '3/3/2009', '3/4/2009', '3/5/2009', '3/6/2009', '3/7/2009', '3/8/2009', '3/9/2009', '3/10/2009', '3/11/2009', '3/12/2009', '3/13/2009', '3/14/2009', '3/15/2009', '3/16/2009', '3/17/2009', '3/18/2009', '3/19/2009', '3/20/2009', '3/21/2009', '3/22/2009', '3/23/2009', '3/24/2009', '3/25/2009', '3/26/2009', '3/27/2009', '3/28/2009', '3/29/2009', '3/30/2009', '3/31/2009', '4/1/2009', '4/2/2009', '4/3/2009', '4/4/2009', '4/5/2009', '4/6/2009', '4/7/2009', '4/8/2009', '4/9/2009', '4/10/2009', '4/11/2009', '4/13/2009', '4/14/2009', '4/15/2009', '4/16/2009', '4/17/2009', '4/18/2009', '4/19/2009', '4/20/2009', '4/21/2009', '4/22/2009', '4/23/2009', '4/24/2009', '4/25/2009', '4/26/2009', '4/27/2009', '4/28/2009', '4/29/2009', '4/30/2009', '5/1/2009', '5/2/2009', '5/3/2009', '5/4/2009', '5/5/2009', '5/6/2009', '5/7/2009', '5/8/2009', '5/9/2009', '5/10/2009', '5/11/2009', '5/12/2009', '5/13/2009', '5/14/2009', '5/15/2009', '5/16/2009', '5/17/2009', '5/18/2009', '5/19/2009', '5/20/2009', '5/21/2009', '5/22/2009', '5/23/2009', '5/24/2009', '5/25/2009', '5/26/2009', '5/27/2009', '5/28/2009', '5/29/2009', '5/30/2009', '5/31/2009', '6/1/2009', '6/2/2009', '6/3/2009', '6/4/2009', '6/5/2009', '6/6/2009', '6/7/2009', '6/8/2009', '6/9/2009', '6/10/2009', '6/11/2009', '6/12/2009', '6/13/2009', '6/14/2009', '6/15/2009', '6/16/2009', '6/17/2009', '6/18/2009', '6/19/2009', '6/20/2009', '6/21/2009', '6/22/2009', '6/23/2009', '6/24/2009', '6/25/2009', '6/26/2009', '6/27/2009', '6/28/2009', '6/29/2009', '6/30/2009', '7/1/2009', '7/2/2009', '7/3/2009', '7/4/2009', '7/5/2009', '7/6/2009', '7/7/2009', '7/8/2009', '7/9/2009', '7/10/2009', '7/11/2009', '7/12/2009', '7/13/2009', '7/14/2009', '7/15/2009', '7/16/2009', '7/17/2009', '7/18/2009', '7/19/2009', '7/20/2009', '7/21/2009', '7/22/2009', '7/23/2009', '7/24/2009', '7/25/2009', '7/26/2009', '7/27/2009', '7/28/2009', '7/29/2009', '7/30/2009', '7/31/2009', '8/1/2009', '8/2/2009', '8/3/2009', '8/4/2009', '8/5/2009', '8/6/2009', '8/7/2009', '8/8/2009', '8/9/2009', '8/10/2009', '8/11/2009', '8/12/2009', '8/13/2009', '8/14/2009', '8/15/2009', '8/16/2009', '8/17/2009', '8/18/2009', '8/19/2009', '8/20/2009', '8/21/2009', '8/22/2009', '8/23/2009', '8/24/2009', '8/25/2009', '8/26/2009', '8/27/2009', '8/28/2009', '8/29/2009', '8/30/2009', '8/31/2009', '9/1/2009', '9/2/2009', '9/3/2009', '9/4/2009', '9/5/2009', '9/6/2009', '9/7/2009', '9/8/2009', '9/9/2009', '9/10/2009', '9/11/2009', '9/12/2009', '9/13/2009', '9/14/2009', '9/15/2009', '9/16/2009', '9/17/2009', '9/18/2009', '9/19/2009', '9/20/2009', '9/21/2009', '9/22/2009', '9/23/2009', '9/24/2009', '9/25/2009', '9/26/2009', '9/27/2009', '9/28/2009', '9/29/2009', '9/30/2009', '10/1/2009', '10/2/2009', '10/3/2009', '10/4/2009', '10/5/2009', '10/6/2009', '10/7/2009', '10/8/2009', '10/9/2009', '10/10/2009', '10/11/2009', '10/12/2009', '10/13/2009', '10/14/2009', '10/15/2009', '10/16/2009', '10/17/2009', '10/18/2009', '10/19/2009', '10/20/2009', '10/21/2009', '10/22/2009', '10/23/2009', '10/24/2009', '10/25/2009', '10/26/2009', '10/27/2009', '10/30/2009', '10/31/2009', '11/1/2009', '11/2/2009', '11/3/2009', '11/4/2009', '11/5/2009', '11/6/2009', '11/7/2009', '11/8/2009', '11/9/2009', '11/10/2009', '11/11/2009', '11/12/2009', '11/13/2009', '11/14/2009', '11/15/2009', '11/16/2009', '11/17/2009', '11/18/2009', '11/19/2009', '11/20/2009', '11/21/2009', '11/22/2009', '11/23/2009', '11/24/2009', '11/25/2009', '11/26/2009', '11/27/2009', '11/28/2009', '11/29/2009', '11/30/2009', '12/1/2009', '12/2/2009', '12/3/2009', '12/4/2009', '12/5/2009', '12/6/2009', '12/7/2009', '12/8/2009', '12/9/2009', '12/10/2009', '12/11/2009', '12/12/2009', '12/13/2009', '12/14/2009', '12/15/2009', '12/16/2009', '12/17/2009', '12/18/2009', '12/19/2009', '12/20/2009', '12/21/2009', '12/22/2009', '12/26/2009', '12/27/2009', '12/28/2009', '12/29/2009', '12/30/2009', '12/31/2009', '1/1/2010', '1/2/2010', '1/3/2010', '1/4/2010', '1/5/2010', '1/6/2010', '1/7/2010', '1/8/2010', '1/9/2010', '1/10/2010', '1/11/2010', '1/12/2010', '1/13/2010', '1/14/2010', '1/15/2010', '1/16/2010', '1/17/2010', '1/18/2010', '1/19/2010', '1/20/2010', '1/21/2010', '1/22/2010', '1/23/2010', '1/24/2010', '1/25/2010', '1/26/2010', '1/27/2010', '1/28/2010', '1/29/2010', '1/30/2010', '1/31/2010', '2/1/2010', '2/2/2010', '2/3/2010', '2/4/2010', '2/5/2010', '2/6/2010', '2/7/2010', '2/8/2010', '2/9/2010', '2/10/2010', '2/11/2010', '2/12/2010', '2/13/2010', '2/14/2010', '2/15/2010', '2/16/2010', '2/17/2010', '2/18/2010', '2/19/2010', '2/20/2010', '2/21/2010', '2/22/2010', '2/23/2010', '2/24/2010', '2/25/2010', '2/26/2010', '2/27/2010', '2/28/2010', '3/1/2010', '3/2/2010', '3/3/2010', '3/4/2010', '3/5/2010', '3/6/2010', '3/7/2010', '3/8/2010', '3/9/2010', '3/10/2010', '3/11/2010', '3/12/2010', '3/13/2010', '3/14/2010', '3/15/2010', '3/16/2010', '3/17/2010', '3/18/2010', '3/19/2010', '3/20/2010', '3/21/2010', '3/22/2010', '3/23/2010', '3/24/2010', '3/25/2010', '3/26/2010', '3/27/2010', '3/28/2010', '3/29/2010', '3/30/2010', '3/31/2010', '4/1/2010', '4/2/2010', '4/3/2010', '4/4/2010', '4/5/2010', '4/6/2010', '4/7/2010', '4/8/2010', '4/9/2010', '4/10/2010', '4/11/2010', '4/12/2010', '4/13/2010', '4/14/2010', '4/15/2010', '4/16/2010', '4/17/2010', '4/19/2010', '4/20/2010', '4/21/2010', '4/22/2010', '4/23/2010', '4/24/2010', '4/25/2010', '4/26/2010', '4/27/2010', '4/28/2010', '4/29/2010', '4/30/2010', '5/1/2010', '5/2/2010', '5/3/2010', '5/4/2010', '5/5/2010', '5/6/2010', '5/7/2010', '5/8/2010', '5/9/2010', '5/10/2010', '5/11/2010', '5/12/2010', '5/13/2010', '5/14/2010', '5/15/2010', '5/16/2010', '5/17/2010', '5/18/2010', '5/19/2010', '5/20/2010', '5/21/2010', '5/22/2010', '5/23/2010', '5/24/2010', '5/25/2010', '5/26/2010', '5/27/2010', '5/28/2010', '5/29/2010', '5/30/2010', '5/31/2010', '6/1/2010', '6/2/2010', '6/3/2010', '6/4/2010', '6/5/2010', '6/6/2010', '6/7/2010', '6/8/2010', '6/9/2010', '6/10/2010', '6/11/2010', '6/12/2010', '6/13/2010', '6/14/2010', '6/15/2010', '6/16/2010', '6/17/2010', '6/20/2010', '6/21/2010', '6/23/2010', '6/24/2010', '6/25/2010', '6/26/2010', '6/27/2010', '6/28/2010', '6/29/2010', '6/30/2010', '7/1/2010', '7/2/2010', '7/3/2010', '7/4/2010', '7/5/2010', '7/6/2010', '7/7/2010', '7/9/2010', '7/10/2010', '7/11/2010', '7/12/2010', '7/13/2010', '7/14/2010', '7/15/2010', '7/16/2010', '7/17/2010', '7/18/2010', '7/19/2010', '7/20/2010', '7/21/2010', '7/22/2010', '7/23/2010', '7/24/2010', '7/25/2010', '7/26/2010', '7/27/2010', '7/28/2010', '7/29/2010', '7/30/2010', '7/31/2010', '8/1/2010', '8/2/2010', '8/3/2010', '8/4/2010', '8/5/2010', '8/6/2010', '8/7/2010', '8/8/2010', '8/9/2010', '8/10/2010', '8/11/2010', '8/12/2010', '8/13/2010', '8/14/2010', '8/15/2010', '8/16/2010', '8/17/2010', '8/18/2010', '8/19/2010', '8/20/2010', '8/21/2010', '8/22/2010', '8/23/2010', '8/24/2010', '8/25/2010', '8/26/2010', '8/27/2010', '8/28/2010', '8/30/2010', '8/31/2010', '9/1/2010', '9/2/2010', '9/3/2010', '9/4/2010', '9/5/2010', '9/6/2010', '9/7/2010', '9/8/2010', '9/9/2010', '9/10/2010', '9/11/2010', '9/12/2010', '9/13/2010', '9/14/2010', '9/16/2010', '9/17/2010', '9/18/2010', '9/19/2010', '9/20/2010', '9/21/2010', '9/22/2010', '9/23/2010', '9/24/2010', '9/25/2010', '9/26/2010', '10/2/2010', '10/3/2010', '10/4/2010', '10/14/2010', '10/15/2010', '10/16/2010', '10/17/2010', '10/20/2010', '10/21/2010', '10/22/2010', '10/23/2010', '10/24/2010', '10/26/2010', '10/27/2010', '10/28/2010', '10/29/2010', '10/30/2010', '10/31/2010', '11/1/2010', '11/2/2010', '11/3/2010', '11/4/2010', '11/5/2010', '11/6/2010', '11/7/2010', '11/8/2010', '11/9/2010', '11/10/2010', '11/11/2010', '11/14/2010', '11/15/2010', '11/16/2010', '11/17/2010', '11/18/2010', '11/19/2010', '11/22/2010', '11/24/2010', '11/25/2010', '11/26/2010', '11/27/2010', '11/28/2010', '11/29/2010', '11/30/2010', '12/1/2010', '12/2/2010', '12/3/2010', '12/4/2010', '12/6/2010', '12/7/2010', '12/8/2010', '12/9/2010', '12/10/2010', '12/11/2010', '12/12/2010', '12/13/2010', '12/15/2010', '12/16/2010', '12/17/2010', '12/18/2010', '12/19/2010', '12/20/2010', '12/21/2010', '12/22/2010', '12/23/2010', '12/24/2010', '12/25/2010', '12/26/2010', '12/27/2010', '12/28/2010', '12/29/2010', '12/30/2010', '12/31/2010', '1/1/2011', '1/2/2011', '1/3/2011', '1/4/2011', '1/5/2011', '1/6/2011', '1/7/2011', '1/8/2011', '1/9/2011', '1/10/2011', '1/11/2011', '1/12/2011', '1/13/2011', '1/14/2011', '1/15/2011', '1/16/2011', '1/17/2011', '1/18/2011', '1/19/2011', '1/20/2011', '1/21/2011', '1/22/2011', '1/23/2011', '1/24/2011', '1/25/2011', '1/26/2011', '1/27/2011', '1/28/2011', '1/29/2011', '1/30/2011', '1/31/2011', '2/1/2011', '2/2/2011', '2/3/2011', '2/4/2011', '2/5/2011', '2/6/2011', '2/7/2011', '2/8/2011', '2/9/2011', '2/10/2011', '2/11/2011', '2/12/2011', '2/13/2011', '2/14/2011', '2/15/2011', '2/16/2011', '2/17/2011', '2/18/2011', '2/19/2011', '2/20/2011', '2/21/2011', '2/22/2011', '2/23/2011', '2/24/2011', '2/25/2011', '2/26/2011', '2/27/2011', '2/28/2011', '3/1/2011', '3/2/2011', '3/3/2011', '3/4/2011', '3/5/2011', '3/6/2011', '3/7/2011', '3/8/2011', '3/9/2011', '3/10/2011', '3/11/2011', '3/12/2011', '3/13/2011', '3/14/2011', '3/15/2011', '3/16/2011', '3/17/2011', '3/18/2011', '3/19/2011', '3/20/2011', '3/21/2011', '3/22/2011', '3/23/2011', '3/24/2011', '3/25/2011', '3/26/2011', '3/27/2011', '3/28/2011', '3/29/2011', '3/30/2011', '3/31/2011', '5/1/2011', '5/2/2011', '5/3/2011', '5/4/2011', '5/5/2011', '5/6/2011', '5/7/2011', '5/8/2011', '5/9/2011', '5/10/2011', '5/11/2011', '5/12/2011', '5/13/2011', '5/14/2011', '5/15/2011', '5/16/2011', '5/17/2011', '5/18/2011', '5/19/2011', '5/20/2011', '5/21/2011', '5/22/2011', '5/23/2011', '5/24/2011', '5/25/2011', '5/26/2011', '5/27/2011', '5/28/2011', '5/29/2011', '5/30/2011', '5/31/2011', '6/1/2011', '6/2/2011', '6/3/2011', '6/4/2011', '6/5/2011', '6/6/2011', '6/7/2011', '6/8/2011', '6/9/2011', '6/10/2011', '6/11/2011', '6/12/2011', '6/13/2011', '6/14/2011', '6/15/2011', '6/16/2011', '6/17/2011', '6/18/2011', '6/19/2011', '6/20/2011', '6/21/2011', '6/22/2011', '6/23/2011', '6/24/2011', '6/25/2011', '6/26/2011', '6/27/2011', '6/28/2011', '6/29/2011', '6/30/2011', '7/1/2011', '7/2/2011', '7/3/2011', '7/4/2011', '7/5/2011', '7/6/2011', '7/7/2011', '7/8/2011', '7/9/2011', '7/10/2011', '7/11/2011', '7/12/2011', '7/13/2011', '7/14/2011', '7/15/2011', '7/16/2011', '7/17/2011', '7/18/2011', '7/19/2011', '7/20/2011', '7/21/2011', '7/22/2011', '7/23/2011', '7/24/2011', '7/25/2011', '7/26/2011', '7/27/2011', '7/28/2011', '7/29/2011', '7/30/2011', '7/31/2011', '8/1/2011', '8/2/2011', '8/3/2011', '8/4/2011', '8/5/2011', '8/6/2011', '8/7/2011', '8/8/2011', '8/9/2011', '8/10/2011', '8/11/2011', '8/12/2011', '8/13/2011', '8/14/2011', '8/15/2011', '8/16/2011', '8/17/2011', '8/18/2011', '8/19/2011', '8/20/2011', '8/21/2011', '8/22/2011', '8/23/2011', '8/24/2011', '8/25/2011', '8/26/2011', '8/27/2011', '8/28/2011', '8/29/2011', '8/30/2011', '8/31/2011', '9/1/2011', '9/2/2011', '9/3/2011', '9/4/2011', '9/5/2011', '9/6/2011', '9/7/2011', '9/8/2011', '9/9/2011', '9/10/2011', '9/11/2011', '9/12/2011', '9/13/2011', '9/14/2011', '9/15/2011', '9/16/2011', '9/17/2011', '9/18/2011', '9/19/2011', '9/20/2011', '9/21/2011', '9/22/2011', '9/23/2011', '9/24/2011', '9/25/2011', '9/26/2011', '9/27/2011', '9/28/2011', '9/29/2011', '9/30/2011', '10/1/2011', '10/2/2011', '10/3/2011', '10/4/2011', '10/5/2011', '10/6/2011', '10/7/2011', '10/8/2011', '10/9/2011', '10/10/2011', '10/11/2011', '10/12/2011', '10/13/2011', '10/14/2011', '10/15/2011', '10/16/2011', '10/17/2011', '10/18/2011', '10/19/2011', '10/20/2011', '10/21/2011', '10/22/2011', '10/23/2011', '10/24/2011', '10/25/2011', '10/26/2011', '10/27/2011', '10/28/2011', '10/29/2011', '10/30/2011', '10/31/2011', '11/1/2011', '11/2/2011', '11/3/2011', '11/4/2011', '11/5/2011', '11/6/2011', '11/7/2011', '11/8/2011', '11/9/2011', '11/10/2011', '11/11/2011', '11/12/2011', '11/15/2011', '11/16/2011', '11/17/2011', '11/18/2011', '11/19/2011', '11/20/2011', '11/21/2011', '11/22/2011', '11/23/2011', '11/24/2011', '11/25/2011', '11/26/2011', '11/27/2011', '11/28/2011', '11/29/2011', '11/30/2011', '12/1/2011', '12/2/2011', '12/3/2011', '12/4/2011', '12/5/2011', '12/6/2011', '12/7/2011', '12/8/2011', '12/9/2011', '12/10/2011', '12/11/2011', '12/12/2011', '12/13/2011', '12/14/2011', '12/15/2011', '12/16/2011', '12/17/2011', '12/18/2011', '12/19/2011', '12/20/2011', '12/21/2011', '12/22/2011', '12/23/2011', '12/24/2011', '12/25/2011', '12/26/2011', '12/27/2011', '12/28/2011', '12/29/2011', '12/30/2011', '12/31/2011', '1/1/2012', '1/2/2012', '1/3/2012', '1/4/2012', '1/5/2012', '1/6/2012', '1/7/2012', '1/8/2012', '1/9/2012', '1/10/2012', '1/11/2012', '1/12/2012', '1/13/2012', '1/14/2012', '1/15/2012', '1/16/2012', '1/17/2012', '1/18/2012', '1/20/2012', '1/21/2012', '1/22/2012', '1/23/2012', '1/24/2012', '1/25/2012', '1/26/2012', '1/27/2012', '1/28/2012', '1/29/2012', '1/30/2012', '1/31/2012', '2/1/2012', '2/2/2012', '2/3/2012', '2/4/2012', '2/5/2012', '2/6/2012', '2/7/2012', '2/8/2012', '2/9/2012', '2/10/2012', '2/11/2012', '2/12/2012', '2/13/2012', '2/14/2012', '2/15/2012', '2/16/2012', '2/17/2012', '2/18/2012', '2/19/2012', '2/20/2012', '2/21/2012', '2/22/2012', '2/23/2012', '2/24/2012', '2/25/2012', '2/26/2012', '2/27/2012', '2/28/2012', '2/29/2012', '3/1/2012', '3/2/2012', '3/3/2012', '3/4/2012', '3/5/2012', '3/6/2012', '3/7/2012', '3/8/2012', '3/9/2012', '3/10/2012', '3/11/2012', '3/12/2012', '3/13/2012', '3/14/2012', '3/15/2012', '3/16/2012', '3/17/2012', '3/18/2012', '3/19/2012', '3/20/2012', '3/21/2012', '3/22/2012', '3/23/2012', '3/24/2012', '3/25/2012', '3/26/2012', '3/27/2012', '3/28/2012', '3/29/2012', '3/30/2012', '3/31/2012', '4/1/2012', '4/2/2012', '4/3/2012', '4/4/2012', '4/5/2012', '4/6/2012', '4/7/2012', '4/8/2012', '4/9/2012', '4/10/2012', '4/11/2012', '4/12/2012', '4/13/2012', '4/14/2012', '4/15/2012', '4/16/2012', '4/17/2012', '4/18/2012', '4/19/2012', '4/20/2012', '4/21/2012', '4/23/2012', '4/24/2012', '4/25/2012', '4/26/2012', '4/27/2012', '4/28/2012', '4/29/2012', '4/30/2012', '5/1/2012', '5/2/2012', '5/3/2012', '5/4/2012', '5/5/2012', '5/6/2012', '5/7/2012', '5/8/2012', '5/9/2012', '5/10/2012', '5/11/2012', '5/12/2012', '5/13/2012', '5/14/2012', '5/15/2012', '5/16/2012', '5/17/2012', '5/18/2012', '5/19/2012', '5/20/2012', '5/21/2012', '5/22/2012', '5/23/2012', '5/24/2012', '5/25/2012', '5/26/2012', '5/27/2012', '5/28/2012', '5/29/2012', '5/30/2012', '5/31/2012', '6/1/2012', '6/2/2012', '6/3/2012', '6/4/2012', '6/5/2012', '6/6/2012', '6/7/2012', '6/8/2012', '6/9/2012', '6/10/2012', '6/11/2012', '6/12/2012', '6/13/2012', '6/14/2012', '6/15/2012', '6/16/2012', '6/17/2012', '6/18/2012', '6/19/2012', '6/20/2012', '6/21/2012', '6/22/2012', '6/23/2012', '6/24/2012', '6/26/2012', '6/27/2012', '6/28/2012', '6/29/2012', '6/30/2012', '7/1/2012', '7/2/2012', '7/3/2012', '7/4/2012', '7/5/2012', '7/6/2012', '7/7/2012', '7/8/2012', '7/9/2012', '7/10/2012', '7/11/2012', '7/12/2012', '7/13/2012', '7/14/2012', '7/15/2012', '7/16/2012', '7/17/2012', '7/18/2012', '7/19/2012', '7/20/2012', '7/21/2012', '7/22/2012', '7/24/2012', '7/25/2012', '7/26/2012', '7/27/2012', '7/28/2012', '7/29/2012', '7/30/2012', '7/31/2012', '8/1/2012', '8/2/2012', '8/3/2012', '8/4/2012', '8/5/2012', '8/6/2012', '8/7/2012', '8/8/2012', '8/9/2012', '8/10/2012', '8/15/2012', '8/16/2012', '8/17/2012', '8/18/2012', '8/19/2012', '8/20/2012', '8/21/2012', '8/22/2012', '8/23/2012', '8/24/2012', '8/25/2012', '8/26/2012', '8/30/2012', '8/31/2012', '9/1/2012', '9/2/2012', '9/3/2012', '9/4/2012', '9/5/2012', '9/6/2012', '9/7/2012', '9/8/2012', '9/11/2012', '9/12/2012', '9/13/2012', '9/14/2012', '9/15/2012', '9/16/2012', '9/17/2012', '9/18/2012', '9/19/2012', '9/20/2012', '9/21/2012', '9/22/2012', '9/23/2012', '9/24/2012', '9/25/2012', '9/26/2012', '9/27/2012', '9/28/2012', '9/30/2012', '10/1/2012', '10/2/2012', '10/3/2012', '10/4/2012', '10/5/2012', '10/6/2012', '10/7/2012', '10/8/2012', '10/9/2012', '10/11/2012', '10/12/2012', '10/13/2012', '10/14/2012', '10/15/2012', '10/16/2012', '10/17/2012', '10/18/2012', '10/19/2012', '10/20/2012', '10/21/2012', '10/22/2012', '10/23/2012', '10/24/2012', '10/25/2012', '10/26/2012', '10/27/2012', '10/28/2012', '10/29/2012', '10/30/2012', '10/31/2012', '11/1/2012', '11/2/2012', '11/3/2012', '11/4/2012', '11/5/2012', '11/6/2012', '11/7/2012', '11/8/2012', '11/9/2012', '11/10/2012', '11/11/2012', '11/12/2012', '11/13/2012', '11/14/2012', '11/15/2012', '11/16/2012', '11/17/2012', '11/18/2012', '11/19/2012', '11/20/2012', '11/21/2012', '11/22/2012', '11/23/2012', '11/24/2012', '11/25/2012', '11/26/2012', '11/27/2012', '11/28/2012', '11/29/2012', '11/30/2012', '1/1/2013', '1/2/2013', '1/3/2013', '1/4/2013', '1/5/2013', '1/6/2013', '1/7/2013', '1/8/2013', '1/9/2013', '1/10/2013', '1/11/2013', '1/12/2013', '1/13/2013', '1/14/2013', '1/15/2013', '1/16/2013', '1/17/2013', '1/18/2013', '1/19/2013', '1/20/2013', '1/21/2013', '1/22/2013', '1/23/2013', '1/24/2013', '1/25/2013', '1/26/2013', '1/27/2013', '1/28/2013', '1/29/2013', '1/30/2013', '1/31/2013', '3/1/2013', '3/2/2013', '3/3/2013', '3/4/2013', '3/5/2013', '3/6/2013', '3/7/2013', '3/8/2013', '3/9/2013', '3/10/2013', '3/11/2013', '3/12/2013', '3/13/2013', '3/14/2013', '3/15/2013', '3/16/2013', '3/17/2013', '3/18/2013', '3/19/2013', '3/20/2013', '3/21/2013', '3/22/2013', '3/23/2013', '3/24/2013', '3/25/2013', '3/26/2013', '3/27/2013', '3/28/2013', '3/29/2013', '3/30/2013', '3/31/2013', '4/1/2013', '4/2/2013', '4/3/2013', '4/4/2013', '4/5/2013', '4/6/2013', '4/7/2013', '4/8/2013', '4/9/2013', '4/10/2013', '4/11/2013', '4/12/2013', '4/13/2013', '4/14/2013', '4/15/2013', '4/16/2013', '4/17/2013', '4/18/2013', '4/19/2013', '4/20/2013', '4/21/2013', '4/22/2013', '4/23/2013', '4/24/2013', '4/25/2013', '4/26/2013', '4/27/2013', '4/28/2013', '4/29/2013', '4/30/2013', '5/1/2013', '5/2/2013', '5/3/2013', '5/4/2013', '5/5/2013', '5/6/2013', '5/7/2013', '5/8/2013', '5/9/2013', '5/10/2013', '5/11/2013', '5/12/2013', '5/13/2013', '5/14/2013', '5/15/2013', '5/16/2013', '5/17/2013', '5/18/2013', '5/19/2013', '5/20/2013', '5/21/2013', '5/22/2013', '5/23/2013', '5/24/2013', '5/25/2013', '5/26/2013', '5/27/2013', '5/28/2013', '5/29/2013', '5/30/2013', '5/31/2013', '6/1/2013', '6/2/2013', '6/3/2013', '6/4/2013', '6/5/2013', '6/6/2013', '6/7/2013', '6/8/2013', '6/9/2013', '6/10/2013', '6/11/2013', '6/12/2013', '6/13/2013', '6/14/2013', '6/15/2013', '6/16/2013', '6/17/2013', '6/18/2013', '6/19/2013', '6/20/2013', '6/21/2013', '6/22/2013', '6/23/2013', '6/24/2013', '6/25/2013', '6/26/2013', '6/27/2013', '6/28/2013', '6/29/2013', '6/30/2013', '7/1/2013', '7/2/2013', '7/3/2013', '7/4/2013', '7/5/2013', '7/6/2013', '7/7/2013', '7/8/2013', '7/9/2013', '7/10/2013', '7/11/2013', '7/12/2013', '7/13/2013', '7/14/2013', '7/15/2013', '7/16/2013', '7/17/2013', '7/18/2013', '7/19/2013', '7/20/2013', '7/21/2013', '7/22/2013', '7/23/2013', '7/24/2013', '7/25/2013', '7/26/2013', '7/27/2013', '7/28/2013', '7/29/2013', '7/30/2013', '7/31/2013', '8/1/2013', '8/2/2013', '8/3/2013', '8/4/2013', '8/5/2013', '8/6/2013', '8/7/2013', '8/8/2013', '8/9/2013', '8/10/2013', '8/11/2013', '8/12/2013', '8/13/2013', '8/14/2013', '8/15/2013', '8/16/2013', '8/17/2013', '8/18/2013', '8/19/2013', '8/20/2013', '8/21/2013', '8/22/2013', '8/23/2013', '8/24/2013', '8/25/2013', '8/26/2013', '8/27/2013', '8/28/2013', '8/29/2013', '8/30/2013', '8/31/2013', '9/1/2013', '9/2/2013', '9/3/2013', '9/4/2013', '9/5/2013', '9/6/2013', '9/7/2013', '9/8/2013', '9/9/2013', '9/10/2013', '9/11/2013', '9/12/2013', '9/13/2013', '9/14/2013', '9/15/2013', '9/16/2013', '9/17/2013', '9/18/2013', '9/19/2013', '9/20/2013', '9/21/2013', '9/22/2013', '9/23/2013', '9/24/2013', '9/25/2013', '9/26/2013', '9/27/2013', '9/28/2013', '9/29/2013', '9/30/2013', '10/1/2013', '10/2/2013', '10/3/2013', '10/4/2013', '10/5/2013', '10/6/2013', '10/7/2013', '10/8/2013', '10/9/2013', '10/10/2013', '10/11/2013', '10/12/2013', '10/13/2013', '10/14/2013', '10/15/2013', '10/16/2013', '10/17/2013', '10/18/2013', '10/19/2013', '10/20/2013', '10/21/2013', '10/22/2013', '10/23/2013', '10/24/2013', '10/25/2013', '10/26/2013', '10/27/2013', '10/28/2013', '10/29/2013', '10/30/2013', '10/31/2013', '11/1/2013', '11/2/2013', '11/3/2013', '11/4/2013', '11/5/2013', '11/6/2013', '11/7/2013', '11/8/2013', '11/9/2013', '11/10/2013', '11/11/2013', '11/12/2013', '11/13/2013', '11/14/2013', '11/15/2013', '11/16/2013', '11/17/2013', '11/18/2013', '11/19/2013', '11/20/2013', '11/21/2013', '11/22/2013', '11/23/2013', '11/24/2013', '11/25/2013', '11/26/2013', '11/27/2013', '11/28/2013', '11/29/2013', '11/30/2013', '12/1/2013', '12/2/2013', '12/3/2013', '12/4/2013', '12/5/2013', '12/6/2013', '12/7/2013', '12/8/2013', '12/9/2013', '12/10/2013', '12/11/2013', '12/12/2013', '12/13/2013', '12/14/2013', '12/15/2013', '12/16/2013', '12/17/2013', '12/18/2013', '12/19/2013', '12/20/2013', '12/21/2013', '12/22/2013', '12/23/2013', '12/24/2013', '12/25/2013', '12/26/2013', '12/27/2013', '12/28/2013', '12/29/2013', '12/30/2013', '12/31/2013', '1/1/2014', '1/2/2014', '1/3/2014', '1/4/2014', '1/5/2014', '1/6/2014', '1/7/2014', '1/8/2014', '1/9/2014', '1/10/2014', '1/11/2014', '1/12/2014', '1/13/2014', '1/14/2014', '1/15/2014', '1/16/2014', '1/17/2014', '1/18/2014', '1/19/2014', '1/20/2014', '1/21/2014', '1/22/2014', '1/23/2014', '1/24/2014', '1/25/2014', '1/26/2014', '1/27/2014', '1/28/2014', '1/29/2014', '1/30/2014', '1/31/2014', '2/1/2014', '2/2/2014', '2/3/2014', '2/4/2014', '2/5/2014', '2/6/2014', '2/7/2014', '2/8/2014', '2/9/2014', '2/10/2014', '2/11/2014', '2/12/2014', '2/13/2014', '2/14/2014', '2/15/2014', '2/16/2014', '2/17/2014', '2/18/2014', '2/19/2014', '2/20/2014', '2/21/2014', '2/22/2014', '2/23/2014', '2/24/2014', '2/25/2014', '2/26/2014', '2/27/2014', '2/28/2014', '3/1/2014', '3/2/2014', '3/3/2014', '3/4/2014', '3/5/2014', '3/6/2014', '3/7/2014', '3/8/2014', '3/9/2014', '3/10/2014', '3/11/2014', '3/12/2014', '3/13/2014', '3/14/2014', '3/15/2014', '3/16/2014', '3/17/2014', '3/18/2014', '3/19/2014', '3/20/2014', '3/21/2014', '3/22/2014', '3/23/2014', '3/24/2014', '3/25/2014', '3/26/2014', '3/27/2014', '3/28/2014', '3/29/2014', '3/30/2014', '3/31/2014', '4/1/2014', '4/2/2014', '4/3/2014', '4/4/2014', '4/5/2014', '4/6/2014', '4/7/2014', '4/8/2014', '4/9/2014', '4/10/2014', '4/11/2014', '4/12/2014', '4/13/2014', '4/14/2014', '4/15/2014', '4/16/2014', '4/17/2014', '4/18/2014', '4/19/2014', '4/20/2014', '4/21/2014', '4/22/2014', '4/23/2014', '4/24/2014', '4/25/2014', '4/26/2014', '4/27/2014', '4/28/2014', '4/29/2014', '4/30/2014', '5/1/2014', '5/2/2014', '5/3/2014', '5/4/2014', '5/5/2014', '5/6/2014', '5/7/2014', '5/8/2014', '5/9/2014', '5/10/2014', '5/11/2014', '5/12/2014', '5/13/2014', '5/14/2014', '5/15/2014', '5/16/2014', '5/17/2014', '5/18/2014', '5/19/2014', '5/20/2014', '5/21/2014', '5/22/2014', '5/23/2014', '5/24/2014', '5/25/2014', '5/26/2014', '5/27/2014', '5/28/2014', '5/29/2014', '5/30/2014', '5/31/2014', '6/1/2014', '6/2/2014', '6/3/2014', '6/4/2014', '6/5/2014', '6/6/2014', '6/7/2014', '6/8/2014', '6/9/2014', '6/10/2014', '6/11/2014', '6/12/2014', '6/13/2014', '6/14/2014', '6/15/2014', '6/16/2014', '6/17/2014', '6/18/2014', '6/19/2014', '6/20/2014', '6/21/2014', '6/22/2014', '6/23/2014', '6/24/2014', '6/25/2014', '6/26/2014', '6/27/2014', '6/28/2014', '6/29/2014', '6/30/2014', '7/1/2014', '7/2/2014', '7/3/2014', '7/4/2014', '7/5/2014', '7/6/2014', '7/7/2014', '7/8/2014', '7/9/2014', '7/10/2014', '7/11/2014', '7/12/2014', '7/13/2014', '7/14/2014', '7/15/2014', '7/16/2014', '7/17/2014', '7/18/2014', '7/19/2014', '7/20/2014', '7/21/2014', '7/22/2014', '7/23/2014', '7/24/2014', '7/25/2014', '7/26/2014', '7/27/2014', '7/28/2014', '7/29/2014', '7/30/2014', '7/31/2014', '8/1/2014', '8/2/2014', '8/3/2014', '8/4/2014', '8/5/2014', '8/6/2014', '8/7/2014', '8/8/2014', '8/9/2014', '8/10/2014', '8/11/2014', '8/12/2014', '8/13/2014', '8/14/2014', '8/15/2014', '8/16/2014', '8/17/2014', '8/18/2014', '8/19/2014', '8/20/2014', '8/21/2014', '8/22/2014', '8/23/2014', '8/24/2014', '8/25/2014', '8/26/2014', '8/27/2014', '8/28/2014', '8/29/2014', '8/30/2014', '8/31/2014', '9/1/2014', '9/2/2014', '9/3/2014', '9/4/2014', '9/5/2014', '9/6/2014', '9/7/2014', '9/8/2014', '9/9/2014', '9/10/2014', '9/11/2014', '9/12/2014', '9/13/2014', '9/14/2014', '9/15/2014', '9/18/2014', '9/19/2014', '9/20/2014', '9/21/2014', '9/22/2014', '9/23/2014', '9/24/2014', '9/25/2014', '9/26/2014', '9/27/2014', '9/28/2014', '9/29/2014', '9/30/2014', '10/1/2014', '10/2/2014', '10/3/2014', '10/4/2014', '10/5/2014', '10/6/2014', '10/7/2014', '10/8/2014', '10/9/2014', '10/10/2014', '10/11/2014', '10/12/2014', '10/13/2014', '10/14/2014', '10/15/2014', '10/16/2014', '10/17/2014', '10/18/2014', '10/19/2014', '10/20/2014', '10/21/2014', '10/22/2014', '10/23/2014', '10/24/2014', '10/25/2014', '10/26/2014', '10/27/2014', '10/28/2014', '10/29/2014', '10/30/2014', '11/2/2014', '11/3/2014', '11/4/2014', '11/5/2014', '11/6/2014', '11/7/2014', '11/8/2014', '11/9/2014', '11/10/2014', '11/11/2014', '11/12/2014', '11/13/2014', '11/14/2014', '11/15/2014', '11/16/2014', '11/17/2014', '11/18/2014', '11/19/2014', '11/20/2014', '11/21/2014', '11/22/2014', '11/23/2014', '11/24/2014', '11/25/2014', '11/26/2014', '11/30/2014', '12/1/2014', '12/2/2014', '12/3/2014', '12/4/2014', '12/5/2014', '12/6/2014', '12/7/2014', '12/8/2014', '12/9/2014', '12/10/2014', '12/11/2014', '12/13/2014', '12/14/2014', '12/15/2014', '12/16/2014', '12/17/2014', '12/18/2014', '12/19/2014', '12/20/2014', '12/21/2014', '12/22/2014', '12/23/2014', '12/24/2014', '12/25/2014', '12/26/2014', '12/27/2014', '12/28/2014', '12/29/2014', '12/30/2014', '12/31/2014', '1/1/2015', '1/2/2015', '1/3/2015', '1/4/2015', '1/5/2015', '1/6/2015', '1/7/2015', '1/8/2015', '1/9/2015', '1/10/2015', '1/11/2015', '1/12/2015', '1/13/2015', '1/14/2015', '1/15/2015', '1/16/2015', '1/17/2015', '1/18/2015', '1/19/2015', '1/20/2015', '1/21/2015', '1/22/2015', '1/23/2015', '1/24/2015', '1/25/2015', '1/26/2015', '1/27/2015', '1/28/2015', '1/29/2015', '1/30/2015', '1/31/2015', '2/1/2015', '2/2/2015', '2/3/2015', '2/4/2015', '2/5/2015', '2/6/2015', '2/7/2015', '2/8/2015', '2/9/2015', '2/10/2015', '2/11/2015', '2/12/2015', '2/13/2015', '2/14/2015', '2/15/2015', '2/16/2015', '2/17/2015', '2/18/2015', '2/19/2015', '2/20/2015', '2/21/2015', '2/22/2015', '2/23/2015', '2/24/2015', '2/25/2015', '2/26/2015', '2/27/2015', '2/28/2015', '3/1/2015', '3/2/2015', '3/3/2015', '3/4/2015', '3/5/2015', '3/6/2015', '3/7/2015', '3/8/2015', '3/9/2015', '3/10/2015', '3/11/2015', '3/12/2015', '3/13/2015', '3/14/2015', '3/15/2015', '3/16/2015', '3/17/2015', '3/18/2015', '3/19/2015', '3/20/2015', '3/21/2015', '3/22/2015', '3/23/2015', '3/24/2015', '3/25/2015', '3/26/2015', '3/27/2015', '3/28/2015', '3/29/2015', '3/30/2015', '3/31/2015', '4/1/2015', '4/2/2015', '4/3/2015', '4/4/2015', '4/5/2015', '4/6/2015', '4/7/2015', '4/8/2015', '4/9/2015', '4/10/2015', '4/11/2015', '4/12/2015', '4/13/2015', '4/14/2015', '4/15/2015', '4/16/2015', '4/17/2015', '4/18/2015', '4/19/2015', '4/20/2015', '4/21/2015', '4/22/2015', '4/23/2015', '4/24/2015', '4/25/2015', '4/26/2015', '4/27/2015', '4/28/2015', '4/29/2015', '4/30/2015', '5/1/2015', '5/2/2015', '5/3/2015', '5/4/2015', '5/5/2015', '5/6/2015', '5/7/2015', '5/8/2015', '5/9/2015', '5/10/2015', '5/11/2015', '5/12/2015', '5/13/2015', '5/14/2015', '5/15/2015', '5/16/2015', '5/17/2015', '5/18/2015', '5/19/2015', '5/20/2015', '5/21/2015', '5/22/2015', '5/23/2015', '5/24/2015', '5/25/2015', '5/26/2015', '5/27/2015', '5/28/2015', '5/29/2015', '5/30/2015', '5/31/2015', '6/1/2015', '6/2/2015', '6/3/2015', '6/4/2015', '6/5/2015', '6/6/2015', '6/7/2015', '6/8/2015', '6/9/2015', '6/10/2015', '6/11/2015', '6/12/2015', '6/13/2015', '6/14/2015', '6/15/2015', '6/16/2015', '6/17/2015', '6/18/2015', '6/19/2015', '6/20/2015', '6/21/2015', '6/22/2015', '6/23/2015', '6/24/2015', '6/25/2015', '6/26/2015', '6/27/2015', '6/28/2015', '6/29/2015', '6/30/2015', '7/1/2015', '7/2/2015', '7/3/2015', '7/4/2015', '7/5/2015', '7/6/2015', '7/7/2015', '7/8/2015', '7/9/2015', '7/10/2015', '7/11/2015', '7/12/2015', '7/13/2015', '7/14/2015', '7/15/2015', '7/16/2015', '7/17/2015', '7/18/2015', '7/19/2015', '7/20/2015', '7/21/2015', '7/22/2015', '7/23/2015', '7/24/2015', '7/25/2015', '7/26/2015', '7/27/2015', '7/28/2015', '7/29/2015', '7/30/2015', '7/31/2015', '8/1/2015', '8/2/2015', '8/3/2015', '8/4/2015', '8/5/2015', '8/6/2015', '8/7/2015', '8/8/2015', '8/9/2015', '8/10/2015', '8/11/2015', '8/12/2015', '8/13/2015', '8/14/2015', '8/15/2015', '8/16/2015', '8/17/2015', '8/18/2015', '8/19/2015', '8/20/2015', '8/21/2015', '8/22/2015', '8/23/2015', '8/24/2015', '8/25/2015', '8/26/2015', '8/27/2015', '8/28/2015', '8/29/2015', '8/30/2015', '8/31/2015', '9/1/2015', '9/2/2015', '9/3/2015', '9/4/2015', '9/5/2015', '9/6/2015', '9/7/2015', '9/8/2015', '9/9/2015', '9/10/2015', '9/11/2015', '9/12/2015', '9/13/2015', '9/14/2015', '9/15/2015', '9/16/2015', '9/17/2015', '9/18/2015', '9/19/2015', '9/20/2015', '9/21/2015', '9/22/2015', '9/23/2015', '9/24/2015', '9/25/2015', '9/26/2015', '9/27/2015', '9/28/2015', '9/29/2015', '9/30/2015', '10/1/2015', '10/2/2015', '10/3/2015', '10/4/2015', '10/5/2015', '10/6/2015', '10/7/2015', '10/8/2015', '10/9/2015', '10/10/2015', '10/11/2015', '10/12/2015', '10/13/2015', '10/14/2015', '10/15/2015', '10/16/2015', '10/17/2015', '10/18/2015', '10/19/2015', '10/20/2015', '10/21/2015', '10/22/2015', '10/23/2015', '10/24/2015', '10/25/2015', '10/26/2015', '10/27/2015', '10/28/2015', '10/29/2015', '10/30/2015', '10/31/2015', '11/1/2015', '11/2/2015', '11/3/2015', '11/4/2015', '11/5/2015', '11/6/2015', '11/7/2015', '11/8/2015', '11/9/2015', '11/10/2015', '11/11/2015', '11/12/2015', '11/13/2015', '11/14/2015', '11/15/2015', '11/16/2015', '11/17/2015', '11/18/2015', '11/19/2015', '11/20/2015', '11/21/2015', '11/22/2015', '11/23/2015', '11/24/2015', '11/26/2015', '11/27/2015', '11/28/2015', '11/29/2015', '11/30/2015', '12/1/2015', '12/2/2015', '12/3/2015', '12/4/2015', '12/6/2015', '12/7/2015', '12/8/2015', '12/9/2015', '12/10/2015', '12/11/2015', '12/12/2015', '12/13/2015', '12/14/2015', '12/15/2015', '12/16/2015', '12/17/2015', '12/18/2015', '12/19/2015', '12/21/2015', '12/22/2015', '12/23/2015', '12/24/2015', '12/25/2015', '12/26/2015', '12/27/2015', '12/28/2015', '12/29/2015', '12/30/2015', '12/31/2015', '1/1/2016', '1/2/2016', '1/3/2016', '1/4/2016', '1/5/2016', '1/6/2016', '1/7/2016', '1/8/2016', '1/9/2016', '1/10/2016', '1/11/2016', '1/12/2016', '1/13/2016', '1/15/2016', '1/16/2016', '1/17/2016', '1/18/2016', '1/19/2016', '1/20/2016', '1/21/2016', '1/22/2016', '1/23/2016', '1/24/2016', '1/25/2016', '1/26/2016', '1/27/2016', '1/28/2016', '1/29/2016', '1/30/2016', '1/31/2016', '2/1/2016', '2/2/2016', '2/3/2016', '2/4/2016', '2/5/2016', '2/6/2016', '2/7/2016', '2/8/2016', '2/9/2016', '2/10/2016', '2/11/2016', '2/12/2016', '2/13/2016', '2/14/2016', '2/15/2016', '2/16/2016', '2/17/2016', '2/18/2016', '2/19/2016', '2/20/2016', '2/21/2016', '2/22/2016', '2/23/2016', '2/24/2016', '2/25/2016', '2/26/2016', '2/27/2016', '2/28/2016', '2/29/2016', '3/1/2016', '3/2/2016', '3/3/2016', '3/4/2016', '3/5/2016', '3/6/2016', '3/7/2016', '3/8/2016', '3/9/2016', '3/10/2016', '3/11/2016', '3/12/2016', '3/13/2016', '3/14/2016', '3/15/2016', '3/16/2016', '3/17/2016', '3/18/2016', '3/19/2016', '3/20/2016', '3/21/2016', '3/22/2016', '3/23/2016', '3/24/2016', '3/25/2016', '3/26/2016', '3/27/2016', '3/28/2016', '3/29/2016', '3/30/2016', '3/31/2016', '4/1/2016', '4/2/2016', '4/3/2016', '4/4/2016', '4/5/2016', '4/6/2016', '4/7/2016', '4/8/2016', '4/9/2016', '4/10/2016', '4/11/2016', '4/12/2016', '4/13/2016', '4/14/2016', '4/15/2016', '4/16/2016', '4/17/2016', '4/18/2016', '4/19/2016', '4/20/2016', '4/21/2016', '4/22/2016', '4/23/2016', '4/24/2016', '4/25/2016', '4/26/2016', '4/27/2016', '4/28/2016', '4/29/2016', '4/30/2016', '5/1/2016', '5/2/2016', '5/3/2016', '5/4/2016', '5/5/2016', '5/6/2016', '5/7/2016', '5/8/2016', '5/9/2016', '5/10/2016', '5/11/2016', '5/12/2016', '5/13/2016', '5/14/2016', '5/15/2016', '5/16/2016', '5/17/2016', '5/18/2016', '5/19/2016', '5/20/2016', '5/21/2016', '5/22/2016', '5/23/2016', '5/24/2016', '5/25/2016', '5/26/2016', '5/27/2016', '5/28/2016', '5/29/2016', '5/30/2016', '5/31/2016', '6/1/2016', '6/2/2016', '6/3/2016', '6/4/2016', '6/5/2016', '6/6/2016', '6/7/2016', '6/8/2016', '6/9/2016', '6/10/2016', '6/11/2016', '6/12/2016', '6/13/2016', '6/14/2016', '6/15/2016', '6/16/2016', '6/17/2016', '6/18/2016', '6/19/2016', '6/20/2016', '6/21/2016', '6/22/2016', '6/23/2016', '6/24/2016', '6/25/2016', '6/26/2016', '6/27/2016', '6/28/2016', '6/29/2016', '7/2/2016', '7/3/2016', '7/4/2016', '7/5/2016', '7/6/2016', '7/7/2016', '7/8/2016', '7/9/2016', '7/10/2016', '7/11/2016', '7/12/2016', '7/13/2016', '7/14/2016', '7/15/2016', '7/16/2016', '7/17/2016', '7/18/2016', '7/19/2016', '7/20/2016', '7/21/2016', '7/22/2016', '7/23/2016', '7/24/2016', '7/25/2016', '7/26/2016', '7/27/2016', '7/28/2016', '7/29/2016', '7/30/2016', '7/31/2016', '8/1/2016', '8/2/2016', '8/3/2016', '8/5/2016', '8/6/2016', '8/7/2016', '8/8/2016', '8/9/2016', '8/10/2016', '8/11/2016', '8/12/2016', '8/13/2016', '8/14/2016', '8/15/2016', '8/16/2016', '8/17/2016', '8/18/2016', '8/19/2016', '8/20/2016', '8/21/2016', '8/22/2016', '8/23/2016', '8/24/2016', '8/25/2016', '8/26/2016', '8/27/2016', '8/28/2016', '8/29/2016', '8/30/2016', '8/31/2016', '9/1/2016', '9/2/2016', '9/3/2016', '9/4/2016', '9/5/2016', '9/6/2016', '9/7/2016', '9/8/2016', '9/9/2016', '9/10/2016', '9/11/2016', '9/12/2016', '9/13/2016', '9/14/2016', '9/15/2016', '9/16/2016', '9/17/2016', '9/18/2016', '9/19/2016', '9/20/2016', '9/21/2016', '9/22/2016', '9/23/2016', '9/24/2016', '9/25/2016', '9/26/2016', '9/27/2016', '9/28/2016', '9/29/2016', '9/30/2016', '10/1/2016', '10/2/2016', '10/3/2016', '10/4/2016', '10/5/2016', '10/6/2016', '10/7/2016', '10/8/2016', '10/9/2016', '10/10/2016', '10/11/2016', '10/12/2016', '10/13/2016', '10/14/2016', '10/15/2016', '10/16/2016', '10/17/2016', '10/18/2016', '10/19/2016', '10/20/2016', '10/21/2016', '10/22/2016', '10/23/2016', '10/24/2016', '10/25/2016', '10/26/2016', '10/27/2016', '10/28/2016', '10/29/2016', '10/30/2016', '10/31/2016', '11/1/2016', '11/2/2016', '11/3/2016', '11/4/2016', '11/5/2016', '11/6/2016', '11/7/2016', '11/8/2016', '11/9/2016', '11/10/2016', '11/11/2016', '11/12/2016', '11/13/2016', '11/14/2016', '11/15/2016', '11/16/2016', '11/17/2016', '11/18/2016', '11/19/2016', '11/20/2016', '11/21/2016', '11/22/2016', '11/24/2016', '11/25/2016', '11/26/2016', '11/27/2016', '11/28/2016', '11/29/2016', '11/30/2016', '12/1/2016', '12/2/2016', '12/3/2016', '12/4/2016', '12/5/2016', '12/6/2016', '12/7/2016', '12/8/2016', '12/9/2016', '12/10/2016', '12/11/2016', '12/12/2016', '12/13/2016', '12/14/2016', '12/15/2016', '12/16/2016', '12/17/2016', '12/18/2016', '12/19/2016', '12/20/2016', '12/21/2016', '12/22/2016', '12/23/2016', '12/24/2016', '12/25/2016', '12/26/2016', '12/27/2016', '12/28/2016', '12/29/2016', '12/30/2016', '12/31/2016', '1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017', '1/7/2017', '1/8/2017', '1/9/2017', '1/10/2017', '1/11/2017', '1/12/2017', '1/13/2017', '1/14/2017', '1/15/2017', '1/16/2017', '1/17/2017', '1/18/2017', '1/19/2017', '1/20/2017', '1/21/2017', '1/22/2017', '1/23/2017', '1/24/2017', '1/25/2017', '1/26/2017', '1/27/2017', '1/28/2017', '1/29/2017', '1/30/2017', '1/31/2017', '2/1/2017', '2/2/2017', '2/3/2017', '2/4/2017', '2/5/2017', '2/6/2017', '2/7/2017', '2/8/2017', '2/9/2017', '2/10/2017', '2/11/2017', '2/12/2017', '2/13/2017', '2/14/2017', '2/15/2017', '2/16/2017', '2/17/2017', '2/18/2017', '2/19/2017', '2/20/2017', '2/21/2017', '2/22/2017', '2/23/2017', '2/24/2017', '2/25/2017', '2/26/2017', '2/27/2017', '2/28/2017', '3/1/2017', '3/2/2017', '3/3/2017', '3/4/2017', '3/5/2017', '3/6/2017', '3/7/2017', '3/8/2017', '3/9/2017', '3/10/2017', '3/11/2017', '3/12/2017', '3/13/2017', '3/14/2017', '3/15/2017', '3/16/2017', '3/17/2017', '3/18/2017', '3/19/2017', '3/20/2017', '3/21/2017', '3/22/2017', '3/23/2017', '3/24/2017', '3/25/2017', '3/26/2017', '3/27/2017', '3/28/2017', '3/29/2017', '3/30/2017', '3/31/2017', '4/1/2017', '4/2/2017', '4/3/2017', '4/4/2017', '4/5/2017', '4/6/2017', '4/7/2017', '4/8/2017', '4/9/2017', '4/10/2017', '4/11/2017', '4/12/2017', '4/13/2017', '4/14/2017', '4/15/2017', '4/16/2017', '4/17/2017', '4/18/2017', '4/19/2017', '4/20/2017', '4/21/2017', '4/22/2017', '4/23/2017', '4/24/2017', '4/25/2017', '4/27/2017', '4/28/2017', '4/29/2017', '4/30/2017', '5/1/2017', '5/2/2017', '5/3/2017', '5/4/2017', '5/5/2017', '5/6/2017', '5/7/2017', '5/8/2017', '5/9/2017', '5/10/2017', '5/11/2017', '5/12/2017', '5/13/2017', '5/14/2017', '5/15/2017', '5/16/2017', '5/17/2017', '5/18/2017', '5/19/2017', '5/20/2017', '5/21/2017', '5/22/2017', '5/23/2017', '5/24/2017', '5/25/2017', '5/26/2017', '5/27/2017', '5/28/2017', '5/29/2017', '5/30/2017', '5/31/2017', '6/1/2017', '6/2/2017', '6/3/2017', '6/4/2017', '6/5/2017', '6/6/2017', '6/7/2017', '6/8/2017', '6/9/2017', '6/10/2017', '6/11/2017', '6/12/2017', '6/13/2017', '6/14/2017', '6/15/2017', '6/16/2017', '6/17/2017', '6/18/2017', '6/19/2017', '6/20/2017', '6/21/2017', '6/22/2017', '6/23/2017', '6/24/2017', '6/25/2017'], 'MinTemp': [19.5, 19.5, 21.6, 20.2, 19.7, 20.2, 18.6, 17.2, 16.4, 14.6, 16.4, 18.9, 18.4, 16.9, 18.3, 16.7, 19.5, 18.6, 19.0, 18.3, 20.6, 19.1, 20.5, 16.5, 20.5, 19.3, 19.0, 17.9, 14.7, 12.8, 14.2, 15.0, 15.5, 18.7, 19.6, 19.9, 16.5, 16.4, 19.3, 18.6, 19.3, 19.2, 18.8, 19.3, 19.7, 19.5, 19.0, 19.9, 19.7, 17.7, 16.9, 16.3, 18.5, 19.8, 17.0, 15.0, 15.2, 14.4, 13.1, 13.5, 13.7, 14.1, 16.4, 11.2, 11.6, 13.1, 15.3, 14.6, 15.6, 13.8, 14.1, 14.0, 15.1, 13.2, 13.8, 13.8, 14.9, 15.3, 15.9, 15.2, 14.7, 14.4, 14.7, 14.7, 12.7, 15.6, 11.9, 8.6, 8.4, 11.6, 10.8, 10.9, 9.4, 9.4, 11.8, 13.0, 11.0, 11.0, 12.6, 14.0, 12.4, 13.2, 11.2, 12.0, 13.8, 15.2, 8.8, 10.7, 10.3, 11.1, 11.9, 11.0, 11.4, 8.8, 10.9, 11.5, 11.0, 11.0, 10.9, 10.8, 11.6, 14.3, 15.2, 15.5, 15.2, 14.7, 11.7, 12.7, 13.0, 12.4, 13.2, 13.7, 14.0, 9.6, 10.6, 13.3, 13.1, 13.6, 12.8, 13.8, 11.6, 9.7, 8.2, 9.2, 9.9, 10.2, 9.5, 7.9, 7.9, 9.2, 10.3, 10.8, 9.2, 8.2, 9.1, 8.3, 9.7, 10.5, 6.9, 7.2, 10.0, 5.7, 7.8, 10.1, 9.7, 8.9, 8.2, 8.2, 8.1, 10.8, 10.4, 7.2, 5.5, 6.9, 9.8, 6.2, 6.3, 7.0, 8.0, 6.0, 6.0, 7.9, 9.7, 9.4, 8.1, 6.6, 8.8, 8.3, 8.2, 6.9, 6.7, 7.0, 6.8, 8.4, 7.2, 9.4, 10.5, 6.9, 5.6, 5.3, 8.2, 9.4, 10.2, 7.3, 5.5, 8.2, 8.5, 8.8, 8.7, 8.1, 12.1, 10.4, 8.7, 9.7, 13.5, 13.1, 11.8, 9.5, 9.4, 8.4, 7.0, 7.1, 8.7, 14.8, 17.2, 16.9, 12.3, 10.7, 9.4, 14.6, 18.8, 15.8, 13.2, 15.6, 9.7, 10.3, 11.3, 14.0, 19.8, 13.5, 11.9, 12.6, 18.9, 22.5, 17.5, 14.6, 14.9, 9.7, 10.9, 10.5, 12.6, 14.6, 14.2, 16.1, 16.6, 15.1, 11.8, 12.9, 16.7, 16.5, 17.1, 14.5, 9.9, 7.9, 9.0, 12.3, 14.4, 19.8, 17.6, 16.8, 15.1, 16.9, 18.0, 17.5, 17.2, 15.5, 14.5, 15.2, 16.0, 18.4, 16.6, 17.4, 15.9, 16.4, 19.0, 19.2, 18.5, 17.2, 15.5, 16.2, 17.0, 17.3, 16.7, 17.9, 12.2, 13.6, 15.5, 16.4, 15.9, 19.5, 19.3, 15.0, 17.6, 16.6, 18.4, 18.4, 19.3, 20.8, 20.0, 18.2, 17.4, 19.5, 17.2, 17.4, 17.0, 19.2, 16.7, 15.0, 17.7, 19.3, 17.3, 15.7, 14.3, 15.9, 19.0, 18.7, 16.4, 19.1, 20.5, 19.7, 20.7, 18.2, 19.2, 18.4, 18.8, 17.0, 18.7, 19.5, 20.2, 20.7, 20.4, 17.2, 18.3, 17.4, 18.7, 19.6, 20.8, 23.0, 18.8, 17.7, 14.8, 16.4, 20.1, 21.3, 23.4, 25.0, 24.8, 20.5, 20.8, 20.2, 19.9, 21.2, 21.1, 21.8, 21.2, 22.9, 21.8, 21.6, 22.2, 21.9, 21.8, 21.4, 20.9, 17.9, 16.7, 17.5, 16.4, 17.0, 16.5, 18.6, 19.4, 19.4, 18.9, 20.3, 21.9, 20.3, 19.6, 19.9, 21.1, 19.6, 17.5, 17.5, 20.5, 21.8, 20.8, 22.5, 16.8, 14.4, 17.7, 20.2, 18.2, 19.1, 20.2, 18.2, 19.6, 19.9, 19.2, 16.1, 15.9, 17.1, 17.5, 19.9, 19.6, 17.6, 19.5, 20.5, 20.8, 20.5, 20.6, 16.4, 16.1, 18.6, 19.8, 18.4, 19.6, 20.1, 18.3, 17.1, 17.0, 16.3, 12.8, 15.1, 14.7, 17.4, 20.4, 17.6, 16.1, 14.9, 13.5, 14.2, 15.8, 15.9, 16.4, 16.0, 14.7, 13.1, 16.3, 16.7, 11.2, 11.8, 10.2, 11.0, 10.2, 10.9, 11.4, 12.1, 14.0, 12.9, 12.0, 12.3, 11.1, 13.0, 11.8, 9.6, 10.4, 11.1, 12.4, 14.2, 11.4, 10.5, 13.0, 14.5, 14.8, 15.6, 15.4, 17.4, 13.6, 12.8, 13.9, 12.0, 11.4, 9.9, 11.6, 13.1, 12.5, 13.7, 13.1, 13.1, 9.3, 10.7, 11.4, 10.0, 9.7, 6.1, 6.2, 7.8, 9.4, 8.2, 9.2, 10.5, 10.1, 9.2, 10.9, 11.7, 14.1, 10.1, 9.1, 8.7, 8.7, 9.4, 10.4, 9.6, 12.3, 15.7, 11.0, 11.1, 8.5, 10.1, 6.2, 7.5, 8.6, 9.1, 9.5, 9.1, 10.3, 11.6, 10.2, 6.7, 8.1, 9.2, 8.0, 8.0, 8.2, 8.8, 11.2, 11.4, 8.4, 7.6, 8.9, 8.3, 8.1, 9.5, 8.5, 9.2, 9.2, 7.9, 8.3, 10.0, 7.6, 8.0, 11.0, 7.8, 5.9, 6.8, 9.1, 8.9, 9.0, 10.8, 8.7, 9.4, 13.0, 9.0, 7.8, 9.9, 11.1, 14.5, 13.3, 17.0, 15.6, 12.0, 11.3, 10.6, 14.8, 13.7, 9.2, 11.1, 9.7, 12.0, 14.7, 14.7, 10.4, 13.5, 11.6, 10.3, 10.0, 9.5, 11.0, 17.3, 18.1, 15.4, 15.6, 14.7, 19.0, 13.1, 13.8, 15.7, 17.1, 17.0, 15.1, 13.5, 17.1, 10.1, 11.0, 11.4, 10.9, 14.9, 16.5, 13.6, 12.9, 13.1, 11.5, 10.6, 10.5, 9.6, 8.9, 11.8, 11.3, 17.0, 15.2, 13.8, 11.8, 11.6, 13.8, 12.4, 14.3, 15.6, 17.9, 17.5, 16.8, 17.9, 14.4, 14.7, 17.3, 18.7, 16.9, 18.8, 18.9, 19.4, 16.9, 16.7, 17.2, 19.1, 19.1, 15.9, 15.4, 16.6, 19.5, 15.0, 18.5, 18.7, 19.4, 17.8, 18.4, 21.0, 22.0, 21.2, 19.9, 18.1, 18.3, 21.3, 21.3, 21.1, 19.5, 18.1, 14.3, 13.5, 15.2, 17.3, 18.2, 18.7, 21.7, 20.1, 18.4, 19.2, 19.9, 16.9, 20.3, 20.0, 19.1, 21.7, 21.5, 20.2, 16.9, 19.6, 19.9, 19.7, 17.7, 17.7, 20.1, 19.8, 19.8, 20.1, 20.9, 23.3, 18.9, 18.2, 18.3, 21.8, 20.8, 20.9, 20.8, 24.1, 22.1, 23.0, 23.7, 19.5, 19.0, 21.7, 20.3, 16.7, 15.6, 17.4, 19.5, 22.6, 25.0, 18.4, 19.5, 22.3, 22.9, 22.2, 19.6, 20.5, 21.5, 22.6, 22.7, 21.4, 21.9, 23.1, 20.5, 20.2, 21.0, 22.8, 21.7, 21.4, 23.9, 21.4, 22.1, 20.2, 21.3, 18.5, 18.3, 20.2, 18.9, 20.7, 23.2, 26.0, 21.1, 20.5, 18.1, 18.4, 21.0, 19.2, 17.3, 18.2, 17.2, 20.5, 20.9, 22.3, 22.6, 20.8, 19.2, 18.2, 18.7, 17.4, 16.2, 18.0, 17.4, 15.6, 17.0, 18.2, 19.8, 21.7, 20.8, 18.7, 18.7, 19.5, 19.5, 22.4, 20.8, 22.4, 20.5, 18.9, 16.0, 17.2, 15.9, 15.4, 15.2, 17.0, 18.5, 19.0, 16.4, 17.2, 18.6, 14.9, 13.1, 12.3, 14.9, 16.9, 15.8, 17.2, 17.3, 16.7, 16.7, 16.6, 20.2, 17.2, 12.5, 11.7, 12.6, 13.4, 14.0, 14.3, 13.9, 14.8, 16.2, 15.4, 10.4, 11.3, 11.1, 12.3, 12.7, 12.8, 10.5, 9.0, 10.6, 10.5, 11.0, 12.7, 12.4, 11.7, 11.2, 11.7, 10.8, 9.5, 10.4, 12.1, 13.4, 13.5, 11.7, 12.9, 11.8, 12.6, 11.7, 11.2, 12.7, 15.2, 12.5, 9.5, 9.1, 9.1, 9.5, 10.3, 6.2, 9.0, 6.6, 6.9, 8.1, 9.1, 10.6, 9.5, 10.1, 12.6, 11.8, 12.2, 13.5, 6.7, 5.5, 4.7, 4.3, 6.4, 7.6, 7.7, 7.8, 8.8, 9.7, 9.6, 9.7, 8.6, 9.9, 10.1, 11.4, 13.9, 10.4, 7.2, 7.1, 7.3, 8.7, 8.0, 8.0, 6.0, 8.0, 9.6, 10.2, 9.2, 9.3, 11.2, 11.4, 12.0, 12.8, 9.6, 9.1, 10.3, 8.3, 7.1, 7.6, 6.8, 6.4, 7.2, 9.3, 12.2, 10.7, 9.9, 8.2, 12.8, 12.6, 7.6, 6.5, 9.3, 11.3, 8.8, 8.4, 11.2, 10.9, 11.5, 10.3, 10.3, 9.2, 10.5, 11.5, 14.9, 16.6, 13.7, 15.2, 16.4, 11.5, 10.4, 8.2, 9.7, 11.0, 11.1, 9.2, 13.3, 13.9, 10.4, 9.5, 9.6, 11.7, 11.1, 11.6, 13.0, 15.2, 13.7, 13.4, 13.1, 12.7, 15.0, 15.3, 17.8, 19.5, 11.7, 9.9, 12.9, 13.3, 15.3, 15.8, 14.1, 12.9, 14.8, 16.4, 14.5, 16.2, 19.3, 18.1, 11.8, 12.0, 14.4, 13.4, 13.6, 13.4, 16.1, 17.2, 18.2, 19.7, 20.5, 22.3, 17.4, 17.1, 16.8, 16.7, 16.5, 17.5, 18.5, 18.9, 18.2, 19.0, 16.8, 16.4, 17.2, 18.5, 19.8, 19.6, 20.4, 21.0, 20.8, 22.0, 22.8, 17.2, 17.8, 18.5, 20.0, 21.7, 18.0, 19.6, 18.5, 13.3, 15.4, 17.7, 19.1, 18.7, 16.0, 20.8, 18.4, 15.4, 17.3, 20.0, 21.4, 20.5, 20.7, 18.9, 17.3, 17.2, 19.5, 19.9, 21.3, 22.0, 21.5, 21.8, 22.3, 23.3, 21.8, 22.0, 22.1, 21.4, 20.0, 19.3, 21.5, 20.7, 20.5, 21.4, 21.0, 21.7, 22.9, 22.5, 22.5, 19.8, 17.8, 22.2, 22.7, 26.1, 25.1, 24.0, 24.2, 27.6, 18.0, 18.7, 18.1, 20.4, 21.0, 22.7, 19.5, 20.6, 18.3, 19.8, 20.9, 22.6, 22.4, 25.0, 20.0, 19.1, 17.3, 16.6, 18.0, 20.9, 20.3, 22.2, 22.7, 19.4, 17.4, 19.1, 18.1, 18.0, 17.0, 17.6, 20.7, 21.8, 22.0, 20.6, 21.8, 21.3, 17.5, 19.3, 20.6, 20.0, 19.4, 18.8, 19.4, 21.1, 19.9, 18.2, 17.7, 17.7, 16.1, 15.9, 17.1, 17.8, 20.1, 14.8, 12.9, 14.0, 13.0, 11.7, 10.1, 9.8, 9.6, 10.5, 10.1, 8.2, 7.9, 9.9, 10.8, 7.3, 7.3, 7.9, 8.5, 11.5, 11.3, 12.1, 12.4, 13.9, 12.1, 11.1, 10.7, 8.8, 8.5, 10.2, 11.2, 13.9, 16.1, 13.7, 10.6, 11.1, 10.5, 9.3, 7.0, 8.2, 7.5, 8.9, 9.9, 11.6, 12.8, 13.7, 14.1, 14.0, 8.2, 9.9, 8.3, 9.3, 11.8, 9.6, 9.8, 8.1, 7.7, 7.8, 7.5, 9.0, 10.7, 12.1, 10.8, 11.3, 8.6, 10.1, 12.2, 10.9, 11.1, 5.5, 6.4, 6.1, 9.2, 6.9, 9.5, 8.2, 5.6, 7.5, 10.4, 9.6, 7.4, 8.7, 11.1, 11.3, 8.7, 6.4, 8.3, 7.0, 8.1, 7.1, 7.3, 7.1, 7.4, 9.7, 9.9, 12.5, 12.0, 11.3, 12.7, 13.7, 9.4, 7.8, 7.8, 7.3, 10.3, 8.3, 10.3, 9.4, 10.6, 10.2, 10.9, 8.6, 8.9, 12.3, 12.7, 12.2, 10.4, 10.4, 10.8, 12.4, 11.3, 11.2, 13.6, 11.4, 13.4, 14.2, 10.1, 10.6, 14.2, 14.7, 11.6, 12.6, 12.2, 7.4, 10.2, 9.0, 8.2, 11.1, 15.2, 11.4, 14.3, 15.7, 14.6, 17.5, 11.9, 11.2, 12.7, 14.3, 13.1, 12.3, 10.7, 13.4, 15.5, 12.2, 10.8, 11.4, 10.3, 10.7, 10.0, 13.3, 14.4, 15.4, 13.2, 12.0, 12.2, 10.9, 14.9, 16.6, 17.1, 17.1, 13.2, 13.0, 12.3, 13.5, 15.9, 17.6, 19.0, 18.0, 18.7, 14.2, 13.9, 16.8, 17.6, 18.1, 14.4, 15.1, 14.3, 13.8, 13.9, 15.3, 17.7, 21.2, 19.4, 19.7, 24.2, 18.3, 19.3, 18.8, 19.1, 15.9, 17.1, 18.1, 19.6, 17.5, 17.8, 14.8, 15.3, 15.4, 18.1, 18.6, 17.0, 19.7, 20.7, 15.8, 14.1, 13.9, 15.6, 11.8, 12.6, 12.1, 16.2, 16.7, 17.7, 18.3, 17.5, 16.4, 15.2, 15.5, 14.7, 17.0, 15.8, 18.6, 18.4, 18.7, 19.2, 18.7, 19.7, 19.1, 20.0, 19.1, 18.3, 17.5, 17.1, 16.9, 16.0, 18.1, 20.6, 20.7, 20.0, 18.5, 15.1, 20.0, 20.8, 19.4, 19.7, 13.9, 14.7, 18.4, 17.3, 17.5, 18.7, 20.0, 20.7, 21.8, 19.7, 19.6, 20.5, 20.7, 20.8, 21.8, 21.6, 22.0, 21.7, 25.3, 18.4, 18.5, 16.7, 17.0, 18.2, 20.4, 19.4, 19.2, 18.9, 19.9, 19.6, 16.6, 18.6, 19.2, 19.1, 18.5, 19.0, 19.4, 19.9, 19.5, 19.6, 17.3, 18.2, 20.6, 18.9, 21.9, 21.9, 23.5, 20.2, 20.1, 18.6, 18.0, 18.9, 20.0, 19.5, 17.1, 15.0, 14.9, 17.0, 17.5, 19.9, 16.8, 18.1, 20.2, 20.1, 18.6, 17.1, 17.6, 18.9, 18.9, 18.3, 17.6, 13.9, 14.5, 16.2, 17.7, 19.4, 17.5, 16.7, 16.1, 16.2, 17.6, 16.8, 18.6, 19.0, 17.6, 18.2, 20.1, 14.1, 10.1, 10.4, 13.0, 12.4, 14.7, 17.0, 15.9, 17.3, 17.2, 17.5, 17.4, 18.2, 17.6, 15.6, 10.8, 13.5, 12.9, 13.8, 13.1, 10.9, 12.7, 12.4, 15.2, 11.5, 11.8, 10.8, 11.2, 10.8, 12.0, 14.1, 14.3, 13.8, 9.9, 9.1, 8.5, 9.8, 10.0, 10.5, 10.4, 10.4, 12.2, 9.8, 10.3, 9.6, 12.2, 10.4, 10.0, 9.1, 11.3, 10.4, 11.9, 11.6, 12.8, 14.0, 12.8, 9.0, 10.4, 9.1, 6.4, 6.6, 8.3, 9.9, 11.7, 10.7, 11.2, 11.4, 11.7, 10.1, 9.8, 8.6, 7.3, 8.4, 10.7, 8.0, 6.9, 8.6, 9.7, 9.0, 10.4, 10.1, 9.9, 7.5, 7.7, 7.2, 8.7, 9.6, 8.7, 9.1, 8.3, 8.4, 10.2, 11.6, 12.9, 11.1, 9.0, 9.4, 8.1, 9.3, 8.7, 5.8, 8.1, 9.7, 10.4, 8.7, 10.0, 8.7, 7.8, 8.4, 7.3, 7.5, 7.0, 6.5, 6.8, 7.2, 9.3, 11.6, 6.8, 5.6, 9.5, 7.6, 10.2, 11.7, 11.1, 9.6, 9.7, 7.5, 8.7, 10.6, 16.1, 12.4, 10.7, 8.3, 12.0, 9.7, 5.5, 7.2, 7.5, 9.7, 11.1, 18.4, 16.4, 11.3, 12.6, 11.0, 14.0, 7.9, 9.2, 10.5, 14.2, 12.4, 11.1, 12.1, 13.8, 12.4, 11.2, 13.5, 12.0, 14.6, 14.1, 18.9, 9.9, 9.8, 12.7, 11.2, 14.5, 20.0, 15.6, 12.7, 13.6, 12.1, 13.5, 8.5, 8.6, 12.4, 11.4, 15.4, 20.3, 16.6, 15.9, 16.6, 14.9, 15.1, 11.8, 11.7, 13.8, 16.9, 13.1, 15.3, 12.1, 14.1, 15.7, 16.8, 16.1, 13.7, 14.8, 17.0, 19.6, 19.8, 19.9, 18.5, 16.6, 13.1, 13.0, 16.9, 15.9, 16.2, 17.2, 15.1, 15.3, 12.8, 15.8, 13.4, 17.1, 15.7, 16.4, 18.5, 20.7, 19.8, 18.4, 19.9, 21.3, 20.2, 20.3, 18.4, 18.3, 20.9, 21.6, 21.4, 20.9, 21.1, 20.2, 21.2, 23.5, 20.7, 17.1, 16.8, 19.1, 21.4, 21.7, 21.5, 20.2, 20.7, 20.9, 20.7, 20.4, 21.6, 23.7, 20.1, 20.5, 19.3, 19.8, 21.0, 16.5, 17.9, 17.7, 19.5, 20.5, 20.2, 18.6, 20.3, 21.2, 19.6, 20.7, 20.4, 18.3, 20.8, 19.7, 20.1, 18.7, 13.9, 14.3, 16.1, 18.5, 21.1, 21.6, 20.6, 17.9, 20.6, 20.8, 21.5, 16.7, 14.8, 17.9, 17.4, 16.3, 17.0, 15.7, 15.6, 15.6, 14.2, 14.6, 15.6, 14.4, 15.2, 15.6, 15.7, 16.1, 17.4, 16.9, 14.2, 15.4, 13.3, 12.2, 10.9, 13.9, 12.7, 12.3, 12.5, 14.0, 14.0, 14.4, 15.9, 18.4, 16.9, 14.4, 11.1, 14.0, 12.7, 10.8, 11.7, 12.4, 12.1, 12.5, 13.0, 14.0, 13.7, 14.2, 9.2, 13.6, 12.2, 11.1, 9.8, 10.1, 10.1, 9.4, 10.6, 12.7, 10.6, 9.5, 10.6, 11.6, 11.3, 11.7, 11.8, 13.9, 14.4, 9.9, 10.3, 10.5, 11.7, 14.9, 13.5, 11.0, 10.5, 10.5, 10.4, 10.6, 11.7, 13.0, 9.7, 8.5, 8.0, 8.7, 8.7, 8.0, 7.7, 7.6, 9.6, 10.0, 10.5, 12.8, 12.9, 12.7, 11.3, 8.8, 8.8, 8.1, 8.5, 14.7, 7.8, 7.4, 7.4, 8.7, 8.9, 8.2, 8.3, 8.3, 8.9, 10.7, 14.4, 13.0, 13.3, 15.0, 14.5, 8.5, 8.7, 7.1, 10.1, 7.4, 7.9, 7.4, 8.3, 9.7, 11.1, 12.6, 8.1, 9.1, 10.4, 10.9, 9.5, 11.9, 10.8, 9.3, 7.0, 10.5, 9.0, 12.0, 9.6, 12.5, 10.5, 7.3, 10.7, 11.3, 13.6, 8.4, 7.6, 7.6, 11.8, 12.2, 9.9, 10.3, 11.5, 11.8, 11.4, 15.2, 14.9, 11.4, 12.2, 12.0, 12.2, 12.2, 16.0, 15.4, 17.0, 15.3, 20.1, 14.7, 12.1, 10.0, 14.1, 12.8, 14.6, 15.2, 15.2, 14.2, 11.4, 11.3, 11.0, 12.9, 17.5, 15.6, 16.2, 12.7, 11.7, 14.4, 12.4, 20.2, 13.0, 15.2, 9.7, 11.3, 14.1, 15.8, 14.3, 12.3, 17.6, 17.9, 14.3, 17.5, 13.1, 10.7, 12.7, 19.6, 13.7, 12.6, 15.5, 16.6, 19.5, 20.1, 16.4, 12.2, 14.0, 14.6, 15.6, 16.4, 13.2, 15.4, 17.3, 15.9, 18.7, 14.8, 15.0, 11.8, 15.0, 17.9, 22.3, 15.7, 15.1, 15.6, 15.1, 16.9, 15.9, 15.7, 14.8, 15.2, 16.4, 16.6, 20.1, 19.9, 18.1, 16.8, 16.4, 14.7, 13.7, 16.6, 19.5, 14.9, 14.0, 15.2, 15.2, 17.8, 19.0, 12.7, 13.6, 16.2, 19.3, 23.0, 18.1, 19.9, 18.9, 20.6, 19.1, 18.7, 18.7, 20.6, 18.9, 20.3, 21.5, 21.7, 22.4, 19.2, 18.7, 18.7, 17.9, 19.4, 20.0, 18.8, 17.5, 20.5, 22.3, 21.0, 20.1, 20.8, 19.6, 18.3, 16.2, 18.1, 19.0, 19.1, 21.1, 19.7, 18.3, 21.2, 21.1, 21.3, 19.3, 21.2, 21.7, 19.8, 19.8, 20.2, 19.7, 19.3, 17.2, 16.0, 19.6, 20.3, 21.7, 20.3, 21.7, 22.3, 21.3, 20.7, 17.5, 17.1, 15.5, 19.4, 20.6, 20.6, 20.1, 22.1, 21.5, 20.8, 20.9, 21.4, 18.4, 18.9, 20.5, 20.4, 18.0, 19.5, 19.6, 19.1, 19.5, 19.7, 20.3, 19.3, 18.2, 17.9, 18.8, 19.0, 18.1, 21.0, 19.3, 21.6, 19.6, 21.9, 19.6, 19.2, 18.5, 19.3, 19.5, 19.2, 15.1, 16.1, 19.6, 21.7, 20.4, 18.7, 20.3, 20.1, 17.1, 19.7, 20.6, 18.0, 18.7, 19.4, 17.5, 17.5, 18.1, 18.9, 19.9, 18.0, 17.2, 15.3, 17.2, 15.9, 17.8, 18.9, 17.9, 16.0, 13.5, 13.4, 14.3, 13.1, 13.5, 15.0, 13.2, 13.2, 12.4, 13.4, 14.1, 17.6, 15.5, 16.9, 15.0, 14.9, 18.2, 11.3, 13.3, 11.7, 10.8, 10.3, 10.7, 11.2, 11.1, 11.8, 12.0, 14.4, 12.6, 13.7, 12.6, 11.7, 12.0, 12.0, 13.0, 13.1, 14.4, 14.8, 13.1, 13.9, 15.7, 15.5, 14.1, 16.0, 17.1, 12.8, 14.5, 14.3, 14.8, 12.4, 10.5, 11.2, 13.6, 14.5, 10.1, 10.5, 8.6, 10.4, 10.4, 11.1, 10.7, 11.8, 10.3, 9.3, 10.0, 11.4, 10.6, 12.0, 10.5, 11.1, 10.0, 11.5, 11.1, 10.7, 10.4, 12.0, 10.0, 9.4, 8.9, 7.4, 6.7, 6.7, 8.2, 8.2, 8.3, 7.9, 6.6, 8.8, 9.0, 6.4, 6.5, 6.6, 9.2, 11.4, 9.5, 8.6, 8.5, 9.8, 8.9, 8.7, 8.9, 8.5, 9.6, 11.3, 9.4, 8.8, 11.8, 13.0, 13.9, 15.9, 7.2, 5.5, 6.4, 7.9, 6.5, 9.6, 9.1, 8.9, 9.9, 8.1, 6.3, 7.9, 6.4, 7.9, 8.7, 10.3, 11.0, 12.8, 9.5, 9.4, 11.2, 9.9, 11.1, 10.5, 11.6, 13.4, 12.3, 9.4, 12.0, 11.7, 10.7, 14.1, 8.9, 9.8, 8.8, 10.3, 11.2, 10.9, 12.2, 14.0, 12.1, 13.9, 12.9, 12.9, 13.1, 12.2, 9.2, 9.1, 10.9, 12.3, 10.9, 11.7, 17.4, 14.3, 13.0, 11.6, 16.5, 16.6, 15.6, 10.4, 12.8, 16.4, 14.0, 17.3, 19.7, 15.1, 14.4, 14.0, 14.4, 17.0, 17.9, 13.2, 10.6, 9.0, 12.2, 12.9, 12.4, 15.8, 15.0, 15.0, 14.5, 18.6, 18.5, 18.5, 19.4, 15.9, 16.6, 15.5, 13.7, 13.8, 16.1, 17.7, 15.5, 16.5, 14.4, 16.5, 18.7, 16.6, 16.4, 18.5, 17.7, 18.9, 18.1, 15.2, 18.6, 18.1, 18.8, 22.1, 19.1, 19.6, 21.1, 21.8, 19.3, 19.1, 19.6, 19.0, 21.6, 20.0, 19.6, 20.5, 18.7, 18.9, 21.1, 20.4, 20.7, 16.7, 15.3, 17.8, 20.0, 19.2, 18.3, 18.2, 18.0, 16.8, 20.5, 20.7, 21.0, 19.8, 19.9, 18.8, 18.9, 17.7, 19.4, 19.3, 21.4, 21.2, 22.0, 22.4, 20.5, 21.3, 22.8, 21.2, 21.8, 22.0, 20.6, 20.4, 18.9, 21.1, 22.0, 21.2, 20.7, 20.7, 20.9, 18.1, 19.7, 22.5, 22.4, 22.7, 21.6, 20.2, 18.9, 17.3, 14.6, 15.2, 17.0, 19.3, 18.0, 18.5, 17.3, 18.6, 17.6, 18.8, 18.9, 22.7, 21.5, 22.8, 21.0, 20.4, 20.4, 20.3, 22.1, 21.9, 22.2, 22.2, 21.7, 20.5, 20.7, 22.4, 22.2, 20.1, 19.9, 20.0, 20.1, 22.0, 18.2, 16.8, 21.5, 20.4, 16.2, 19.3, 19.6, 20.3, 21.1, 21.3, 20.0, 20.1, 15.8, 17.7, 16.3, 15.3, 19.7, 19.6, 20.0, 18.3, 18.6, 18.4, 20.6, 15.0, 16.9, 14.7, 14.7, 15.2, 17.3, 17.3, 17.8, 18.5, 17.9, 17.7, 15.5, 15.8, 15.1, 14.2, 15.3, 14.7, 15.6, 14.8, 14.8, 14.5, 15.0, 17.7, 19.9, 19.7, 18.0, 13.6, 14.5, 14.1, 14.3, 15.0, 14.4, 12.7, 12.5, 10.3, 10.6, 14.0, 14.1, 16.6, 18.9, 17.3, 14.7, 13.4, 11.5, 11.1, 11.4, 11.3, 15.4, 12.2, 13.2, 7.9, 10.2, 13.0, 11.1, 11.5, 13.8, 16.2, 14.5, 13.0, 10.2, 8.3, 9.4, 8.5, 10.4, 11.7, 13.6, 11.1, 11.5, 10.1, 6.1, 6.1, 7.4, 8.9, 10.1, 9.3, 10.8, 13.6, 12.8, 11.7, 12.6, 13.1, 9.5, 10.9, 12.9, 14.7, 11.4, 9.6, 8.3, 8.5, 8.0, 8.0, 10.2, 12.7, 10.1, 8.3, 7.4, 9.3, 9.0, 10.7, 7.0, 6.2, 5.8, 6.0, 6.0, 7.8, 7.9, 6.6, 7.3, 6.6, 7.1, 8.1, 8.6, 6.2, 8.3, 6.2, 6.6, 7.8, 7.8, 8.2, 9.9, 11.2, 11.6, 10.8, 11.0, 7.3, 6.4, 8.1, 8.2, 10.7, 9.4, 14.3, 8.4, 8.3, 5.0, 6.8, 6.7, 7.9, 6.2, 8.6, 9.8, 8.4, 9.4, 7.9, 8.2, 10.5, 9.3, 10.9, 9.0, 8.2, 9.4, 12.9, 15.4, 15.1, 12.5, 12.3, 11.6, 10.6, 9.0, 8.3, 9.6, 9.0, 8.0, 11.2, 12.5, 11.5, 12.7, 11.1, 10.0, 9.8, 11.3, 14.0, 10.9, 12.4, 15.3, 15.8, 12.4, 12.2, 13.6, 12.5, 12.5, 12.4, 14.6, 10.0, 8.3, 10.1, 11.1, 12.3, 10.9, 11.9, 16.7, 16.8, 16.5, 14.2, 19.8, 16.1, 20.3, 19.7, 17.0, 16.8, 15.7, 15.0, 16.5, 17.5, 16.9, 16.3, 17.3, 19.1, 18.8, 19.4, 18.7, 19.7, 18.6, 14.5, 12.9, 15.2, 17.5, 15.5, 13.4, 15.7, 14.1, 17.1, 17.5, 18.2, 18.6, 17.1, 16.0, 18.2, 18.4, 16.2, 13.7, 15.2, 18.9, 18.3, 18.0, 17.7, 14.9, 14.3, 14.4, 17.4, 18.8, 21.4, 20.3, 19.0, 17.1, 18.7, 22.4, 16.5, 19.1, 19.9, 18.2, 19.0, 19.2, 17.1, 14.6, 16.6, 18.8, 20.9, 21.3, 20.2, 21.2, 18.4, 18.2, 18.3, 20.6, 21.1, 16.6, 19.0, 20.3, 23.6, 17.7, 17.3, 16.9, 17.5, 18.8, 17.1, 15.3, 15.4, 15.0, 17.4, 17.9, 18.0, 20.2, 18.6, 17.8, 17.4, 16.5, 15.5, 18.5, 18.5, 20.5, 23.5, 21.3, 14.3, 14.3, 16.0, 16.7, 19.2, 21.9, 23.6, 22.8, 22.3, 20.8, 21.6, 21.6, 20.8, 21.4, 22.4, 19.5, 19.7, 21.8, 17.0, 19.3, 19.1, 19.6, 19.9, 19.1, 19.0, 21.0, 19.6, 20.7, 21.5, 20.7, 21.1, 22.3, 21.5, 19.5, 18.3, 20.5, 23.1, 21.4, 20.8, 21.8, 20.9, 21.9, 23.2, 22.5, 20.7, 20.5, 21.3, 20.3, 22.2, 22.8, 20.6, 20.8, 21.0, 22.4, 22.9, 22.0, 22.8, 21.8, 22.6, 21.8, 19.9, 19.7, 19.0, 19.6, 16.2, 17.4, 15.4, 14.3, 14.9, 16.5, 19.3, 17.1, 19.3, 19.4, 20.6, 19.0, 16.5, 16.6, 18.3, 19.5, 18.7, 18.6, 19.9, 19.9, 17.7, 16.0, 16.1, 16.1, 17.4, 15.5, 15.7, 16.5, 16.6, 19.1, 15.1, 16.9, 16.7, 17.3, 17.1, 16.2, 15.3, 13.1, 14.2, 15.3, 15.7, 16.0, 18.8, 18.1, 13.9, 12.8, 16.0, 13.5, 14.0, 12.4, 15.3, 18.0, 17.3, 12.6, 13.7, 13.9, 12.4, 13.2, 13.6, 16.3, 12.7, 11.9, 12.8, 13.6, 14.5, 15.2, 12.1, 10.4, 12.9, 12.8, 9.8, 9.2, 7.3, 8.7, 10.9, 11.1, 11.7, 13.3, 16.3, 13.7, 11.3, 10.9, 13.8, 13.1, 10.1, 7.9, 8.5, 9.9, 9.1, 10.2, 12.7, 14.7, 14.5, 15.0, 14.9, 12.8, 9.4, 12.7, 7.3, 5.6, 7.4, 7.7, 6.7, 8.2, 6.5, 6.4, 7.5, 9.5, 12.9, 12.4, 8.7, 10.5, 11.8, 14.8, 9.6, 6.7, 6.4, 6.9, 9.2, 11.0, 11.4, 16.5, 13.9, 13.1, 14.5, 7.8, 8.4, 10.2, 10.8, 8.8, 7.3, 8.7, 10.4, 10.9, 11.5, 10.7, 9.7, 9.2, 10.3, 8.7, 8.1, 10.9, 11.2, 7.1, 8.3, 9.5, 8.9, 9.8, 10.6, 11.6, 11.2, 11.0, 8.2, 9.5, 8.5, 11.8, 9.0, 7.3, 7.4, 8.4, 8.4, 10.7, 13.6, 12.1, 14.5, 15.4, 10.1, 10.0, 10.0, 12.2, 15.4, 14.7, 14.1, 13.0, 12.4, 16.0, 16.0, 14.1, 13.5, 10.7, 14.2, 13.1, 10.0, 14.0, 13.5, 15.2, 12.5, 13.6, 12.0, 10.9, 10.2, 14.2, 12.3, 12.4, 12.5, 18.4, 12.7, 11.7, 13.0, 16.0, 20.1, 13.8, 16.8, 12.3, 10.7, 11.8, 9.0, 11.1, 15.9, 21.7, 11.5, 16.2, 16.4, 15.3, 16.1, 10.2, 10.2, 11.4, 14.3, 18.4, 14.7, 15.3, 18.2, 16.1, 12.1, 13.0, 13.6, 15.3, 21.0, 15.7, 14.8, 21.2, 17.8, 16.9, 17.8, 18.4, 18.9, 17.4, 15.4, 14.3, 17.3, 16.4, 19.3, 19.1, 19.7, 21.0, 13.5, 14.7, 18.1, 19.6, 20.3, 19.3, 18.2, 18.1, 18.7, 21.0, 19.7, 22.1, 20.4, 18.6, 20.2, 18.1, 16.9, 20.0, 20.9, 20.7, 27.1, 17.4, 17.2, 18.5, 18.3, 17.7, 16.7, 18.6, 20.3, 20.8, 19.8, 19.1, 20.9, 21.8, 21.1, 22.6, 23.9, 24.1, 22.7, 21.2, 18.5, 20.1, 19.6, 19.9, 19.2, 19.7, 21.3, 22.6, 24.0, 22.3, 23.0, 24.6, 22.8, 21.7, 20.8, 25.1, 20.1, 19.0, 20.8, 20.4, 21.5, 24.5, 20.6, 20.7, 20.4, 20.4, 22.3, 23.1, 25.4, 20.3, 20.8, 22.3, 22.7, 25.8, 26.2, 22.1, 20.7, 22.5, 23.7, 23.9, 24.5, 17.8, 21.6, 18.0, 19.5, 22.6, 21.8, 18.6, 17.5, 16.9, 19.3, 21.6, 21.8, 18.6, 18.3, 18.7, 20.7, 20.6, 20.5, 20.7, 19.9, 20.1, 19.6, 18.8, 16.9, 17.9, 17.3, 16.9, 17.4, 22.2, 22.6, 19.8, 21.9, 20.0, 19.3, 21.6, 23.7, 23.3, 22.3, 20.7, 18.5, 19.2, 18.9, 19.2, 21.2, 21.4, 22.5, 15.3, 14.5, 17.0, 14.8, 14.9, 14.1, 13.2, 14.1, 14.9, 15.5, 11.7, 13.8, 15.0, 15.3, 13.9, 13.2, 15.2, 14.2, 16.0, 15.2, 16.2, 14.4, 17.7, 15.9, 15.7, 18.2, 12.1, 10.2, 10.8, 14.0, 13.2, 14.6, 14.9, 11.8, 12.7, 12.7, 14.6, 10.2, 10.7, 10.5, 10.9, 12.5, 14.0, 14.7, 13.1, 11.1, 9.8, 12.6, 14.8, 16.7, 13.8, 13.0, 14.7, 14.8, 11.6, 10.6, 12.6, 11.9, 11.4, 7.1, 9.7, 8.0, 8.5, 10.7, 10.5, 9.4, 9.1, 8.8, 12.4, 10.4, 12.5, 12.5, 11.3, 9.5, 11.1, 10.7, 11.9, 13.2, 11.3, 11.2, 11.3, 8.6, 9.3, 9.4, 10.1, 7.6], 'MaxTemp': [22.4, 25.6, 24.5, 22.8, 25.7, 27.2, 26.3, 22.3, 20.8, 24.2, 23.9, 27.3, 22.8, 24.3, 24.4, 24.1, 24.8, 25.3, 24.8, 26.4, 26.8, 25.4, 26.0, 28.3, 24.2, 26.2, 29.0, 21.4, 20.6, 22.0, 23.4, 23.1, 25.4, 25.8, 26.0, 24.9, 24.8, 24.3, 26.3, 26.1, 26.4, 26.1, 26.0, 26.1, 25.8, 25.7, 26.7, 26.9, 28.1, 19.6, 23.2, 24.8, 24.3, 27.5, 27.2, 23.6, 21.7, 22.9, 26.8, 25.6, 23.9, 28.7, 22.2, 22.2, 22.7, 22.7, 22.0, 22.1, 22.2, 22.7, 23.5, 23.8, 22.7, 18.9, 19.7, 20.9, 19.7, 20.0, 21.4, 19.1, 19.3, 20.3, 17.9, 20.0, 24.8, 26.1, 16.8, 18.4, 19.6, 18.2, 22.2, 19.6, 20.3, 22.3, 23.6, 23.0, 21.8, 21.9, 21.3, 19.4, 19.5, 19.7, 20.6, 21.4, 23.2, 21.8, 17.8, 20.5, 21.7, 18.9, 18.7, 18.4, 20.1, 18.3, 21.1, 22.4, 19.2, 18.6, 21.0, 20.1, 20.5, 17.6, 19.1, 18.3, 16.9, 17.4, 18.2, 17.7, 16.9, 19.9, 19.9, 22.1, 18.8, 14.6, 15.3, 16.8, 17.5, 19.4, 20.3, 17.9, 18.5, 17.3, 17.1, 19.2, 19.6, 20.2, 19.4, 18.7, 21.0, 22.1, 19.6, 19.2, 17.9, 15.0, 17.4, 18.4, 19.8, 17.2, 13.3, 15.8, 16.5, 15.9, 17.3, 23.1, 19.8, 18.0, 18.5, 18.7, 18.2, 17.6, 17.5, 15.1, 14.7, 15.9, 12.7, 17.0, 17.6, 13.6, 15.0, 17.0, 20.3, 20.8, 16.8, 18.8, 17.2, 16.3, 15.5, 16.5, 18.6, 17.3, 15.6, 15.9, 16.3, 17.4, 18.5, 18.8, 18.0, 16.4, 15.8, 17.6, 19.5, 20.2, 11.9, 14.8, 17.3, 16.4, 21.5, 16.9, 18.2, 16.0, 19.2, 21.0, 20.6, 17.9, 17.1, 15.7, 14.2, 19.0, 17.5, 16.4, 16.8, 17.7, 24.3, 30.6, 23.5, 27.9, 19.8, 16.3, 19.4, 25.8, 32.8, 21.6, 29.8, 17.0, 18.6, 18.6, 22.2, 25.4, 32.9, 21.8, 19.2, 24.7, 31.1, 34.8, 19.4, 19.1, 22.8, 20.6, 19.7, 19.9, 21.5, 22.3, 22.5, 29.2, 21.0, 18.9, 22.1, 24.9, 23.2, 26.8, 22.2, 19.2, 14.3, 15.7, 20.2, 24.0, 24.4, 33.6, 21.9, 17.3, 25.8, 35.0, 21.2, 23.1, 30.3, 19.0, 21.0, 30.3, 24.1, 25.2, 23.0, 23.3, 23.1, 24.6, 24.9, 27.0, 23.1, 22.4, 20.9, 23.4, 22.1, 27.6, 27.7, 20.6, 19.7, 22.3, 21.8, 21.8, 23.6, 24.6, 23.3, 24.9, 31.3, 23.8, 33.2, 21.8, 27.0, 34.8, 26.1, 22.3, 25.9, 23.4, 19.9, 24.5, 32.9, 25.4, 23.8, 24.1, 26.0, 27.4, 26.4, 20.4, 22.1, 24.1, 26.9, 20.7, 23.3, 26.0, 27.2, 28.3, 24.9, 27.6, 31.5, 34.7, 22.7, 23.0, 24.6, 27.9, 28.3, 33.1, 22.4, 22.6, 23.4, 24.6, 26.8, 26.2, 29.7, 33.4, 25.0, 22.6, 23.3, 25.1, 28.7, 31.1, 33.6, 31.7, 40.9, 25.9, 26.8, 23.9, 27.1, 28.3, 28.2, 29.1, 28.1, 28.3, 28.0, 27.3, 29.2, 29.5, 33.5, 28.6, 22.5, 19.4, 23.0, 22.0, 20.4, 21.2, 23.3, 25.0, 22.9, 26.6, 28.4, 26.1, 24.4, 24.9, 27.0, 30.5, 26.4, 24.6, 23.5, 25.4, 25.7, 25.5, 26.9, 25.1, 24.6, 23.6, 26.3, 25.3, 24.5, 24.5, 23.4, 25.3, 25.5, 27.2, 27.4, 26.8, 25.7, 24.5, 27.7, 26.1, 25.3, 26.7, 25.7, 26.1, 26.0, 26.6, 23.5, 23.5, 24.4, 26.2, 22.5, 24.7, 24.7, 25.1, 20.8, 22.8, 21.1, 21.3, 22.4, 23.2, 22.7, 23.8, 22.6, 26.9, 29.3, 24.1, 24.1, 22.8, 22.5, 21.4, 22.1, 22.7, 21.6, 24.7, 23.9, 20.2, 18.7, 21.9, 17.6, 17.4, 22.5, 22.0, 20.5, 23.3, 21.0, 22.9, 22.7, 20.9, 22.8, 20.1, 18.9, 20.1, 21.3, 21.5, 21.7, 21.7, 20.7, 20.9, 21.4, 21.2, 19.7, 19.6, 20.8, 21.3, 20.3, 23.4, 16.9, 19.2, 17.5, 16.5, 18.8, 16.8, 19.1, 18.5, 17.0, 18.5, 19.0, 19.8, 19.2, 16.2, 14.2, 15.8, 17.1, 18.5, 15.6, 19.8, 16.3, 15.6, 15.4, 18.0, 16.0, 19.1, 21.0, 19.6, 18.9, 16.9, 18.6, 15.8, 18.7, 20.7, 19.9, 21.2, 18.9, 16.2, 17.1, 18.1, 15.7, 15.1, 16.8, 17.6, 18.6, 16.4, 16.8, 17.4, 17.2, 17.3, 16.5, 15.8, 18.6, 19.9, 21.3, 23.4, 24.7, 18.3, 17.5, 18.6, 15.3, 18.9, 18.7, 19.5, 18.9, 19.7, 19.2, 19.2, 20.5, 19.8, 19.3, 19.5, 23.5, 16.8, 16.8, 16.3, 16.8, 19.8, 21.0, 21.0, 22.1, 25.7, 22.9, 18.9, 17.9, 21.1, 25.0, 20.8, 25.1, 23.9, 20.2, 21.6, 20.9, 24.8, 25.7, 19.5, 21.5, 22.0, 18.7, 21.1, 25.3, 21.2, 18.2, 19.9, 21.1, 20.8, 22.2, 22.4, 28.5, 32.2, 19.7, 20.4, 22.2, 32.1, 23.5, 20.8, 24.7, 25.8, 31.7, 21.8, 25.0, 25.4, 19.6, 17.2, 21.4, 21.0, 25.6, 33.1, 20.7, 15.2, 17.0, 20.2, 19.6, 19.3, 17.5, 17.1, 18.6, 19.3, 22.6, 24.5, 22.1, 23.0, 21.2, 21.2, 18.8, 20.8, 23.0, 34.6, 21.3, 22.9, 22.1, 20.9, 17.0, 18.8, 23.4, 22.8, 24.2, 26.0, 36.9, 19.9, 19.8, 21.3, 22.9, 21.9, 23.2, 23.9, 23.9, 26.7, 23.0, 24.3, 25.1, 27.6, 23.6, 23.8, 26.5, 33.2, 31.5, 40.4, 22.8, 21.5, 25.0, 26.6, 33.2, 29.3, 30.5, 23.1, 21.2, 22.6, 22.6, 24.4, 23.4, 25.6, 28.5, 27.6, 24.0, 28.8, 28.8, 27.1, 27.4, 24.3, 24.5, 26.5, 32.0, 21.4, 28.9, 22.5, 24.9, 29.4, 20.2, 22.9, 23.1, 26.1, 25.2, 24.8, 29.3, 30.7, 21.5, 23.9, 26.1, 27.6, 24.9, 25.6, 32.4, 30.0, 25.8, 30.3, 27.7, 22.9, 25.1, 25.9, 27.3, 25.7, 26.8, 28.9, 27.4, 32.6, 41.3, 23.0, 26.1, 29.0, 27.1, 26.6, 30.2, 27.3, 26.6, 27.7, 27.7, 27.3, 27.2, 26.5, 22.4, 25.0, 27.6, 27.6, 27.9, 28.2, 37.8, 25.5, 26.4, 30.0, 26.4, 25.6, 25.9, 25.5, 27.3, 29.8, 35.4, 28.6, 24.1, 24.6, 25.1, 27.0, 26.7, 19.7, 23.0, 24.4, 25.2, 25.1, 26.7, 26.4, 29.2, 30.0, 20.8, 24.2, 24.5, 24.7, 24.6, 25.2, 25.5, 26.0, 26.5, 27.4, 29.0, 30.9, 25.0, 27.0, 26.0, 25.5, 29.6, 26.9, 26.4, 27.5, 21.3, 23.1, 25.3, 24.6, 24.0, 22.4, 21.5, 23.3, 25.9, 28.7, 25.0, 27.9, 27.9, 24.5, 22.3, 25.0, 24.9, 22.3, 25.3, 24.9, 24.8, 24.2, 25.7, 30.7, 28.6, 22.8, 21.8, 20.4, 24.9, 24.6, 19.4, 21.7, 26.5, 23.1, 24.8, 21.1, 22.3, 23.1, 24.4, 24.6, 22.6, 27.0, 18.9, 21.9, 21.1, 21.7, 21.6, 17.9, 15.4, 20.0, 19.7, 19.5, 18.6, 14.7, 18.0, 16.9, 17.3, 18.7, 19.9, 17.1, 19.1, 20.0, 19.7, 20.1, 18.6, 17.7, 20.5, 18.5, 15.5, 18.5, 16.7, 17.2, 17.4, 16.7, 17.9, 18.3, 19.3, 18.9, 17.3, 20.2, 16.0, 15.6, 17.0, 18.4, 20.0, 14.9, 15.8, 14.4, 16.1, 17.1, 12.1, 16.3, 17.8, 13.5, 17.2, 16.0, 15.6, 17.6, 19.0, 16.9, 18.6, 18.1, 18.2, 18.2, 18.5, 19.4, 16.7, 16.5, 15.7, 14.7, 18.2, 18.3, 16.9, 17.0, 16.9, 15.2, 16.2, 21.1, 20.7, 20.9, 15.7, 17.3, 18.9, 16.9, 17.0, 16.1, 17.2, 17.1, 16.4, 18.0, 16.7, 18.3, 21.8, 20.1, 18.8, 17.6, 19.9, 24.6, 19.3, 16.7, 17.3, 15.0, 19.8, 18.1, 18.0, 19.2, 17.5, 17.6, 20.0, 25.9, 18.1, 17.6, 20.3, 21.3, 20.4, 16.8, 18.3, 18.4, 24.5, 19.9, 18.9, 23.9, 18.1, 21.2, 19.3, 23.3, 18.1, 20.1, 23.7, 20.1, 19.0, 21.1, 26.9, 22.0, 19.6, 19.7, 20.6, 28.9, 24.7, 16.1, 24.0, 20.3, 21.5, 23.0, 27.2, 15.7, 26.7, 23.8, 21.4, 22.1, 24.4, 24.7, 20.4, 17.9, 23.9, 18.1, 19.2, 18.8, 23.3, 26.3, 23.6, 24.5, 27.2, 30.4, 23.9, 23.5, 22.3, 23.4, 20.0, 24.0, 24.7, 26.0, 24.1, 25.8, 23.5, 21.5, 21.6, 20.1, 24.3, 24.4, 22.7, 25.7, 26.0, 26.3, 30.7, 29.6, 26.9, 30.8, 26.3, 25.6, 26.4, 26.4, 25.5, 27.3, 21.7, 27.8, 25.7, 27.0, 24.1, 26.3, 31.3, 19.9, 21.2, 24.7, 26.5, 27.2, 29.0, 28.0, 21.3, 22.6, 23.4, 26.8, 26.5, 26.7, 27.0, 26.2, 25.2, 27.9, 26.6, 27.9, 30.4, 28.1, 29.8, 26.1, 25.4, 27.3, 26.9, 28.4, 28.3, 35.4, 28.5, 31.4, 28.4, 24.3, 25.0, 28.2, 31.6, 33.5, 31.2, 37.5, 33.7, 41.5, 35.6, 23.0, 25.3, 24.5, 25.7, 29.2, 23.1, 22.8, 24.2, 25.0, 26.7, 28.7, 27.6, 30.1, 33.2, 24.9, 21.7, 26.6, 26.1, 28.0, 27.2, 30.3, 28.8, 33.6, 21.8, 31.7, 25.8, 23.2, 23.6, 24.4, 25.8, 30.8, 27.4, 26.7, 28.1, 27.7, 27.5, 24.5, 28.3, 26.8, 25.2, 24.0, 23.5, 24.8, 27.4, 30.8, 27.1, 26.7, 20.6, 20.5, 24.2, 24.8, 27.7, 21.3, 22.9, 18.4, 18.5, 21.8, 19.5, 19.6, 20.8, 22.0, 17.7, 18.0, 16.4, 16.7, 21.0, 17.9, 19.2, 19.6, 20.2, 20.8, 20.5, 21.2, 23.3, 21.6, 22.9, 18.8, 14.2, 19.6, 18.3, 17.4, 17.0, 17.9, 19.9, 21.0, 19.8, 20.4, 18.7, 17.7, 17.7, 15.0, 14.1, 16.4, 15.7, 15.7, 15.7, 16.7, 17.8, 18.4, 17.1, 18.3, 17.7, 18.4, 19.6, 20.7, 16.3, 20.5, 18.6, 19.6, 20.7, 20.0, 16.6, 18.0, 18.1, 16.6, 19.3, 20.7, 20.4, 17.1, 17.6, 17.6, 17.0, 17.0, 16.4, 17.9, 18.9, 12.3, 15.6, 13.2, 16.3, 16.1, 20.3, 14.7, 18.5, 13.3, 13.9, 15.6, 15.4, 19.1, 18.4, 17.3, 20.4, 20.0, 20.2, 21.4, 22.7, 22.1, 25.7, 23.5, 25.2, 24.0, 19.5, 18.3, 17.1, 18.5, 18.5, 17.3, 18.9, 16.5, 17.8, 17.9, 16.9, 18.9, 17.4, 19.5, 18.5, 18.2, 17.5, 18.9, 19.9, 20.4, 19.0, 21.6, 24.0, 18.7, 19.7, 19.5, 17.9, 19.1, 20.0, 22.5, 26.8, 20.1, 18.3, 14.8, 16.9, 20.4, 19.8, 22.6, 26.7, 19.3, 21.4, 25.4, 30.6, 26.0, 28.1, 22.7, 22.8, 32.5, 17.7, 17.3, 19.7, 20.8, 18.0, 22.0, 20.8, 20.0, 17.1, 18.4, 19.9, 20.1, 19.0, 21.0, 21.6, 23.6, 22.0, 21.1, 21.1, 20.1, 19.4, 24.6, 23.3, 20.5, 19.9, 21.4, 23.5, 30.1, 24.6, 24.8, 34.3, 19.5, 18.6, 19.6, 21.7, 28.2, 25.8, 22.7, 20.7, 24.0, 18.4, 21.5, 24.1, 28.9, 29.5, 28.9, 29.0, 30.4, 23.3, 24.7, 24.6, 22.1, 21.4, 23.7, 27.5, 28.0, 22.3, 21.9, 18.3, 18.3, 20.0, 26.8, 29.8, 26.9, 26.2, 31.6, 21.9, 21.1, 22.2, 21.1, 19.0, 19.1, 22.0, 22.3, 23.9, 23.5, 25.6, 19.3, 23.4, 22.2, 22.6, 21.6, 21.7, 23.2, 22.8, 24.3, 25.0, 22.9, 25.0, 26.2, 26.6, 26.8, 23.7, 24.4, 25.0, 25.1, 23.6, 25.3, 26.5, 26.8, 29.4, 24.8, 22.4, 24.8, 26.4, 27.5, 29.8, 27.6, 23.2, 25.0, 23.4, 22.9, 24.3, 26.1, 26.9, 25.7, 24.8, 26.6, 24.5, 23.7, 24.5, 26.9, 25.3, 26.6, 27.3, 33.2, 28.8, 21.9, 20.2, 21.0, 25.9, 26.8, 24.8, 24.0, 24.5, 25.8, 25.7, 25.3, 25.8, 25.4, 24.8, 25.3, 26.7, 27.4, 27.5, 27.1, 28.2, 25.7, 26.5, 26.9, 27.5, 26.6, 26.8, 28.0, 33.4, 22.0, 29.5, 20.9, 22.6, 27.3, 27.4, 24.7, 23.3, 21.2, 28.4, 26.5, 24.0, 24.0, 25.6, 25.2, 26.2, 28.0, 20.2, 23.0, 24.4, 24.7, 25.1, 20.0, 26.3, 25.2, 23.2, 23.0, 24.6, 22.5, 26.5, 24.8, 27.0, 25.4, 26.7, 26.5, 25.7, 25.6, 25.1, 28.3, 24.3, 24.8, 19.1, 20.2, 22.8, 24.7, 24.4, 25.4, 25.8, 21.4, 21.1, 23.8, 25.1, 24.9, 19.5, 25.3, 19.9, 21.5, 22.8, 24.2, 19.1, 20.2, 22.1, 22.3, 23.3, 22.4, 20.9, 21.3, 18.5, 23.3, 27.1, 29.1, 24.9, 20.7, 18.1, 18.6, 20.2, 21.1, 21.6, 23.1, 21.1, 16.4, 20.9, 20.9, 23.0, 17.1, 18.6, 17.5, 19.3, 18.9, 18.1, 18.5, 20.1, 18.8, 16.8, 15.3, 20.6, 16.1, 16.0, 17.7, 18.0, 18.3, 14.2, 16.1, 19.3, 15.4, 19.4, 20.9, 13.9, 18.5, 19.8, 19.2, 18.1, 18.7, 17.2, 17.0, 18.3, 13.7, 17.6, 18.5, 19.0, 20.0, 16.1, 16.8, 16.8, 16.2, 14.9, 16.0, 15.1, 18.0, 17.0, 18.0, 20.6, 17.3, 22.9, 20.2, 18.2, 20.3, 21.0, 20.7, 15.4, 17.3, 14.9, 16.9, 14.0, 19.6, 19.5, 17.4, 19.4, 16.2, 15.9, 16.1, 16.2, 17.4, 18.5, 20.8, 21.6, 19.4, 18.6, 22.5, 19.8, 14.9, 22.2, 20.6, 22.2, 18.1, 20.1, 17.8, 22.2, 24.7, 29.2, 19.3, 20.7, 20.9, 22.1, 18.4, 17.6, 20.7, 22.8, 24.4, 28.3, 27.9, 21.7, 21.0, 21.8, 21.3, 24.7, 18.5, 20.1, 21.0, 20.9, 20.6, 22.9, 20.5, 22.2, 22.7, 23.8, 24.4, 19.1, 20.7, 22.8, 33.2, 22.4, 19.9, 20.3, 27.8, 32.2, 34.2, 18.3, 20.6, 18.2, 19.6, 19.0, 16.0, 20.1, 19.5, 23.9, 34.1, 21.8, 21.5, 25.6, 33.8, 27.4, 18.7, 19.5, 23.0, 25.6, 21.2, 21.3, 19.8, 21.7, 23.1, 27.8, 33.3, 21.9, 18.5, 22.9, 25.1, 25.4, 24.2, 27.3, 27.1, 20.9, 21.4, 23.7, 23.9, 20.7, 24.7, 18.0, 21.3, 23.1, 21.1, 23.2, 24.5, 20.7, 22.0, 25.4, 31.0, 27.2, 24.1, 24.5, 27.0, 29.5, 26.2, 22.9, 24.8, 26.6, 28.3, 28.0, 27.5, 42.3, 25.0, 25.4, 29.6, 31.2, 23.8, 23.7, 24.9, 27.2, 29.0, 45.8, 24.8, 24.3, 26.6, 29.6, 25.7, 29.8, 29.2, 28.2, 22.7, 23.0, 26.2, 26.0, 27.8, 20.1, 23.1, 25.5, 26.1, 26.8, 27.3, 27.1, 26.8, 27.2, 28.0, 27.4, 26.4, 28.3, 24.3, 25.0, 28.7, 24.0, 23.8, 24.7, 24.8, 26.3, 31.8, 27.0, 28.4, 30.0, 26.9, 27.7, 33.5, 22.3, 23.6, 25.4, 24.3, 26.2, 18.6, 20.9, 23.6, 20.6, 22.7, 24.2, 22.0, 24.1, 25.3, 26.0, 25.4, 27.7, 27.9, 22.0, 23.6, 24.5, 20.2, 19.0, 22.2, 24.7, 25.3, 23.8, 23.2, 27.2, 26.3, 28.7, 26.5, 22.7, 25.0, 20.3, 22.9, 26.4, 20.1, 20.1, 21.5, 21.6, 23.2, 23.5, 22.1, 22.1, 22.8, 21.3, 20.6, 20.6, 19.6, 20.6, 20.2, 20.7, 22.5, 16.0, 17.4, 20.6, 21.3, 21.3, 20.2, 19.3, 21.1, 21.4, 24.9, 21.2, 15.8, 19.5, 21.1, 19.3, 20.1, 22.2, 19.2, 18.9, 21.5, 19.6, 16.0, 20.9, 20.1, 17.6, 19.1, 17.7, 19.2, 16.1, 16.6, 17.3, 13.5, 13.9, 13.8, 16.7, 19.8, 18.8, 16.1, 14.2, 17.1, 20.1, 19.9, 19.8, 23.4, 19.5, 17.4, 19.1, 19.2, 13.6, 15.9, 18.4, 20.2, 17.4, 18.4, 22.0, 21.6, 24.3, 22.6, 20.4, 20.4, 16.3, 17.2, 17.7, 17.0, 19.6, 20.3, 18.7, 18.8, 24.0, 21.5, 18.4, 19.6, 20.3, 19.6, 19.9, 21.0, 23.9, 17.9, 13.1, 17.4, 23.5, 21.8, 24.4, 22.8, 24.1, 18.7, 20.6, 24.4, 23.3, 20.9, 16.6, 18.1, 18.1, 18.6, 22.7, 23.6, 22.0, 21.9, 23.3, 21.8, 24.7, 24.5, 22.2, 22.0, 21.9, 21.1, 28.8, 23.3, 31.1, 21.2, 26.1, 31.6, 25.0, 23.6, 18.5, 22.9, 18.8, 17.7, 23.9, 25.3, 23.4, 21.6, 22.0, 25.2, 24.4, 28.4, 28.8, 31.8, 22.6, 29.3, 22.8, 27.4, 32.2, 26.6, 18.9, 20.4, 25.0, 29.8, 21.9, 21.9, 27.3, 37.3, 22.1, 24.7, 35.0, 20.7, 24.3, 28.3, 33.6, 22.1, 22.4, 24.4, 28.9, 27.0, 33.6, 25.9, 23.4, 23.9, 22.3, 22.3, 26.3, 22.2, 22.2, 21.7, 26.1, 34.2, 20.5, 21.4, 21.4, 26.2, 28.1, 33.3, 18.9, 18.4, 22.8, 27.6, 27.0, 23.3, 21.7, 18.0, 20.0, 25.4, 24.9, 24.6, 24.3, 25.0, 23.8, 23.3, 22.9, 23.9, 26.5, 20.9, 22.9, 22.7, 24.1, 24.6, 27.8, 26.3, 22.9, 25.0, 25.6, 29.8, 33.0, 28.0, 24.8, 26.3, 26.7, 24.6, 24.8, 26.0, 26.0, 26.4, 33.5, 27.8, 28.7, 36.0, 22.9, 21.5, 26.6, 24.8, 25.5, 24.6, 24.2, 26.2, 27.1, 36.5, 26.2, 27.5, 26.0, 32.0, 21.6, 22.3, 23.2, 25.7, 29.1, 28.8, 26.8, 27.5, 28.8, 28.1, 27.7, 28.7, 29.4, 25.9, 25.0, 22.8, 24.7, 26.3, 25.3, 22.3, 25.5, 26.5, 29.1, 27.9, 28.3, 28.7, 27.4, 27.1, 25.2, 24.5, 23.3, 25.4, 27.3, 27.6, 27.2, 27.7, 26.3, 27.0, 23.5, 24.9, 25.0, 26.4, 24.7, 29.1, 29.1, 27.0, 24.7, 26.5, 26.4, 26.7, 32.4, 22.0, 21.6, 22.7, 22.8, 26.3, 25.4, 27.5, 26.8, 26.9, 27.2, 27.1, 27.5, 27.8, 29.2, 27.0, 26.3, 26.6, 29.3, 28.0, 29.7, 27.9, 27.0, 26.8, 26.7, 27.0, 23.2, 25.2, 24.9, 22.2, 24.7, 25.7, 27.0, 25.0, 26.4, 26.0, 26.3, 22.3, 26.0, 21.7, 22.4, 23.2, 24.1, 24.7, 28.0, 21.0, 20.6, 21.0, 21.9, 23.3, 23.7, 26.5, 22.7, 22.9, 25.3, 25.8, 26.1, 29.9, 20.9, 23.1, 17.9, 20.6, 25.7, 25.3, 23.0, 22.2, 15.7, 20.5, 20.9, 23.4, 20.7, 21.0, 21.9, 24.8, 22.9, 23.0, 23.0, 23.2, 22.9, 25.3, 24.2, 24.8, 26.1, 25.5, 23.5, 27.1, 25.1, 25.2, 26.9, 23.6, 24.0, 24.1, 21.3, 21.4, 20.7, 20.7, 22.3, 20.3, 22.3, 19.8, 15.5, 19.4, 17.7, 18.4, 19.2, 19.6, 20.4, 20.9, 19.9, 17.2, 19.5, 19.8, 20.4, 21.5, 21.3, 21.9, 19.7, 16.6, 16.7, 18.1, 22.2, 21.2, 22.8, 16.4, 16.1, 19.1, 20.2, 18.3, 20.4, 18.0, 18.1, 19.5, 18.7, 21.3, 17.3, 18.5, 18.5, 16.3, 17.9, 15.6, 18.5, 19.9, 15.9, 14.9, 15.3, 18.3, 19.0, 18.9, 19.8, 18.8, 18.7, 21.0, 18.5, 23.3, 24.0, 25.0, 18.2, 16.1, 17.6, 17.2, 20.6, 22.4, 20.4, 18.1, 19.2, 23.2, 14.4, 15.4, 17.0, 19.3, 19.0, 16.8, 17.5, 15.7, 17.7, 17.1, 18.1, 19.6, 19.3, 19.4, 19.3, 15.6, 19.8, 19.7, 18.0, 16.1, 20.8, 23.6, 18.4, 16.7, 17.6, 18.2, 19.1, 19.0, 19.5, 23.1, 24.4, 25.8, 18.4, 17.6, 22.6, 20.1, 20.5, 22.2, 20.3, 20.9, 20.2, 21.2, 22.2, 24.6, 21.7, 22.8, 25.4, 32.9, 33.5, 22.1, 24.9, 21.1, 21.9, 33.8, 26.0, 27.9, 21.1, 21.2, 22.8, 26.8, 24.7, 26.2, 17.6, 16.0, 23.4, 20.8, 20.4, 23.9, 20.8, 18.7, 21.3, 28.0, 26.4, 29.9, 32.5, 31.6, 28.9, 24.6, 30.8, 23.5, 21.5, 21.8, 23.5, 23.2, 22.1, 23.1, 26.2, 23.6, 23.2, 22.2, 23.5, 32.2, 24.1, 28.5, 25.5, 26.7, 24.9, 31.1, 33.9, 26.3, 30.1, 30.2, 24.7, 23.3, 26.8, 26.8, 28.9, 29.3, 26.9, 27.2, 26.7, 27.2, 32.0, 23.8, 25.3, 22.0, 24.1, 24.4, 25.9, 25.0, 23.8, 25.3, 24.1, 23.1, 25.7, 26.4, 26.1, 24.3, 26.8, 30.4, 21.7, 24.2, 27.3, 28.1, 25.2, 28.4, 28.5, 28.8, 30.4, 26.3, 28.2, 29.3, 28.0, 29.9, 28.7, 22.9, 24.4, 28.8, 34.2, 29.0, 27.6, 35.7, 29.1, 22.7, 24.8, 28.0, 28.3, 29.1, 29.1, 34.4, 20.4, 20.4, 20.5, 24.3, 27.3, 26.1, 26.6, 25.0, 26.5, 25.6, 24.3, 25.6, 26.5, 32.1, 25.9, 28.2, 28.6, 28.8, 28.1, 27.2, 29.4, 28.0, 27.8, 27.6, 27.6, 26.8, 25.6, 27.4, 27.6, 25.6, 23.8, 25.8, 27.5, 27.0, 36.4, 24.6, 27.7, 27.9, 28.6, 30.9, 25.4, 27.6, 31.2, 24.5, 27.9, 28.7, 21.9, 24.5, 24.9, 23.6, 24.4, 29.9, 28.9, 31.4, 23.1, 24.4, 26.5, 27.6, 24.8, 28.7, 27.6, 24.5, 24.7, 23.9, 24.1, 25.3, 27.9, 19.0, 20.1, 25.9, 24.9, 23.0, 22.3, 22.2, 22.4, 22.7, 23.5, 22.2, 22.4, 24.2, 31.7, 23.7, 28.6, 22.5, 17.2, 17.7, 17.9, 23.8, 25.1, 25.9, 17.1, 20.9, 20.9, 18.9, 20.9, 21.7, 23.0, 20.9, 21.8, 27.5, 21.0, 20.3, 21.0, 21.0, 21.2, 21.9, 22.5, 17.3, 19.3, 20.0, 20.8, 20.5, 19.3, 21.5, 25.4, 21.8, 17.7, 19.0, 20.3, 19.5, 19.0, 21.6, 21.0, 19.2, 18.3, 15.0, 15.9, 16.6, 18.4, 19.0, 17.7, 21.0, 22.6, 22.9, 22.6, 14.6, 16.1, 19.4, 19.7, 19.9, 16.9, 17.9, 17.6, 17.4, 14.5, 16.6, 14.1, 19.2, 20.3, 21.3, 19.4, 19.2, 19.4, 19.6, 19.5, 19.1, 17.5, 16.4, 16.2, 16.1, 18.6, 17.3, 14.7, 16.5, 17.6, 16.9, 19.9, 15.1, 16.9, 17.6, 16.8, 13.4, 14.3, 14.6, 16.7, 17.9, 19.3, 16.9, 19.1, 20.0, 20.8, 20.2, 15.7, 17.3, 18.4, 20.5, 21.0, 22.3, 24.7, 19.4, 15.1, 14.2, 16.4, 18.5, 17.5, 17.6, 20.6, 21.0, 17.5, 19.8, 20.4, 18.1, 19.8, 20.5, 16.2, 17.0, 18.9, 21.0, 28.3, 18.5, 17.4, 19.9, 20.2, 20.5, 20.8, 20.3, 18.7, 19.7, 19.7, 18.8, 20.8, 19.5, 21.7, 17.5, 24.9, 20.0, 20.2, 19.6, 21.3, 25.4, 22.3, 23.6, 29.8, 21.1, 19.9, 20.0, 19.5, 18.6, 22.5, 19.5, 16.2, 16.3, 16.4, 20.1, 19.2, 20.8, 23.4, 21.4, 22.9, 23.0, 27.5, 33.8, 37.0, 32.3, 21.5, 21.1, 22.7, 24.3, 24.3, 29.5, 20.4, 23.3, 24.0, 27.5, 26.0, 23.2, 24.6, 26.8, 27.9, 20.5, 21.4, 22.3, 24.9, 29.4, 19.6, 21.2, 23.0, 23.1, 24.2, 26.8, 30.7, 20.0, 19.6, 23.4, 28.3, 24.6, 21.7, 23.3, 25.6, 23.9, 25.5, 28.8, 20.1, 20.9, 22.6, 25.1, 36.5, 31.2, 40.9, 22.1, 22.4, 26.5, 25.2, 37.8, 22.6, 23.8, 26.0, 26.3, 33.3, 22.8, 21.7, 23.6, 25.8, 25.5, 25.0, 33.3, 25.5, 35.3, 22.6, 24.4, 29.6, 26.9, 23.4, 26.1, 27.5, 29.0, 29.1, 21.8, 23.0, 24.6, 25.2, 26.1, 23.0, 22.6, 24.9, 25.6, 26.7, 25.6, 25.4, 24.6, 23.6, 20.3, 18.6, 24.4, 25.4, 25.5, 27.1, 31.6, 34.0, 31.0, 21.7, 23.8, 26.1, 27.0, 30.2, 37.5, 33.5, 29.2, 26.0, 25.0, 25.2, 27.8, 24.9, 27.6, 28.1, 28.7, 31.1, 26.5, 27.9, 28.3, 24.8, 26.1, 27.0, 27.4, 28.0, 27.7, 28.5, 28.4, 28.8, 28.9, 32.5, 29.3, 27.9, 26.0, 26.4, 29.4, 29.3, 27.0, 28.8, 29.7, 29.5, 32.8, 27.8, 27.5, 28.1, 27.7, 28.2, 28.8, 28.7, 28.3, 27.6, 27.9, 28.3, 28.1, 29.3, 30.6, 27.8, 28.7, 27.7, 30.7, 25.6, 26.2, 26.1, 28.2, 24.4, 22.0, 21.2, 23.8, 25.3, 27.4, 25.2, 26.0, 24.2, 26.0, 23.3, 28.7, 25.6, 25.6, 31.2, 25.2, 23.5, 26.2, 34.2, 20.5, 20.6, 25.0, 27.3, 26.5, 22.9, 24.2, 22.9, 24.6, 25.5, 23.2, 24.2, 23.9, 25.5, 24.5, 25.9, 20.2, 23.1, 22.8, 23.7, 23.7, 25.1, 24.2, 26.5, 26.1, 21.3, 26.4, 26.2, 22.4, 26.7, 22.9, 20.8, 22.2, 24.6, 23.1, 24.5, 25.9, 26.6, 24.4, 22.9, 28.2, 21.9, 23.2, 24.9, 21.5, 22.0, 26.8, 22.3, 21.2, 20.2, 18.6, 14.8, 19.3, 19.9, 17.5, 17.9, 19.1, 18.3, 21.1, 19.7, 18.4, 19.9, 20.7, 22.0, 21.4, 19.8, 18.1, 20.3, 21.2, 20.5, 22.2, 19.3, 21.1, 19.5, 20.4, 18.4, 19.7, 18.5, 16.3, 15.1, 15.3, 11.7, 17.3, 18.8, 18.2, 18.1, 15.6, 18.8, 17.7, 17.2, 15.6, 18.0, 17.9, 18.6, 20.2, 14.0, 17.0, 17.7, 18.9, 18.8, 24.2, 24.9, 16.9, 19.3, 25.7, 17.4, 14.3, 17.9, 17.9, 18.6, 19.4, 18.5, 19.8, 20.9, 18.4, 15.8, 14.6, 16.2, 15.5, 16.4, 19.7, 19.1, 25.2, 20.3, 19.4, 20.3, 20.0, 19.6, 20.3, 24.2, 22.9, 24.3, 17.9, 20.4, 13.8, 18.4, 14.7, 17.3, 17.3, 19.9, 20.5, 19.6, 19.9, 23.6, 22.5, 18.0, 20.5, 21.3, 21.2, 20.5, 22.0, 21.2, 22.7, 22.7, 21.0, 20.9, 20.2, 24.6, 22.1, 22.5, 22.4, 17.8, 21.4, 20.6, 21.2, 20.1, 22.0, 22.3, 22.1, 21.8, 23.2, 21.3, 22.8, 20.1, 22.1, 24.7, 25.6, 23.4, 23.7, 27.8, 31.0, 22.2, 25.5, 33.6, 21.3, 23.6, 18.3, 21.3, 23.9, 29.0, 22.4, 25.8, 24.5, 21.6, 25.2, 18.0, 19.8, 21.5, 23.3, 27.0, 21.7, 19.6, 24.3, 25.5, 23.3, 24.5, 24.1, 25.2, 30.6, 25.7, 26.0, 28.1, 28.3, 22.7, 24.6, 24.3, 32.5, 30.3, 24.4, 23.2, 25.2, 23.9, 31.4, 24.8, 25.1, 28.4, 31.0, 23.4, 25.5, 24.4, 23.5, 26.1, 25.3, 25.2, 28.5, 35.7, 26.8, 26.9, 29.9, 23.6, 25.1, 27.9, 27.8, 23.7, 26.3, 27.6, 37.8, 37.2, 19.1, 25.4, 33.7, 21.3, 22.9, 27.1, 26.7, 24.3, 24.4, 27.2, 27.4, 29.3, 29.6, 28.9, 36.6, 33.3, 30.0, 26.6, 26.3, 26.6, 25.9, 24.3, 26.5, 26.8, 28.5, 29.9, 31.3, 37.7, 28.4, 30.5, 32.5, 27.0, 27.2, 36.6, 38.1, 24.5, 29.2, 27.4, 26.5, 32.6, 37.0, 24.3, 25.5, 27.1, 29.7, 30.2, 34.3, 39.4, 23.6, 27.1, 26.4, 30.4, 34.9, 34.7, 24.9, 27.0, 30.9, 37.5, 36.2, 31.9, 27.3, 24.0, 26.1, 30.0, 29.9, 29.4, 26.1, 28.3, 27.6, 27.7, 28.1, 28.0, 20.8, 25.5, 26.6, 26.7, 27.2, 26.3, 24.8, 23.3, 23.0, 25.7, 23.2, 23.5, 25.1, 25.8, 26.1, 26.4, 27.4, 25.9, 25.9, 24.9, 22.7, 25.8, 26.2, 27.9, 27.1, 31.9, 23.3, 24.1, 24.5, 26.5, 27.0, 23.8, 28.8, 26.0, 22.6, 25.6, 22.0, 22.0, 22.8, 23.3, 23.4, 23.8, 24.9, 28.7, 17.9, 23.0, 22.7, 23.6, 24.7, 23.8, 26.9, 24.1, 24.3, 24.9, 24.0, 23.9, 24.1, 26.7, 23.9, 26.7, 20.0, 21.8, 22.7, 22.6, 25.6, 23.9, 18.4, 20.0, 21.6, 26.2, 22.2, 20.1, 21.0, 21.7, 22.1, 19.6, 21.3, 18.7, 20.8, 21.9, 20.2, 21.5, 20.4, 23.2, 23.5, 21.0, 22.6, 22.7, 21.4, 20.8, 20.6, 23.7, 18.3, 17.1, 16.3, 18.3, 18.1, 17.4, 19.7, 19.6, 17.9, 15.5, 18.1, 18.9, 18.1, 17.2, 20.4, 18.7, 17.8, 20.1, 17.3, 19.1, 18.0, 18.3, 20.0, 19.6, 19.2, 17.7, 19.3, 19.3], 'Rainfall': [15.6, 6.0, 6.6, 18.8, 77.4, 1.6, 6.2, 27.6, 12.6, 8.8, 0.0, 0.0, 14.4, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 22.2, 4.2, 33.0, 0.2, 5.4, 0.2, 0.0, 0.0, 0.0, 0.0, 17.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.2, 0.4, 17.0, 0.4, 19.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.0, 9.6, 22.8, 2.2, 0.0, 0.0, 0.0, 11.0, 2.8, 1.4, 4.6, 6.4, 5.0, 2.8, 21.8, 10.2, 12.6, 15.6, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 1.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 1.0, 0.2, 0.0, 0.2, 22.0, 4.0, 9.2, 46.4, 12.4, 0.0, 6.0, 3.6, 1.6, 0.0, 5.4, 0.0, 0.0, 0.0, 7.2, 3.4, 0.0, 0.0, 3.6, 2.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 1.2, 14.2, 0.0, 0.0, 0.2, 0.0, 1.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8, 0.0, 0.0, 7.0, 8.8, 16.2, 0.0, 3.8, 33.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 4.6, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 2.6, 20.8, 0.0, 0.0, 0.0, 2.4, 0.0, 0.0, 12.0, 0.2, 0.0, 0.0, 0.4, 1.6, 62.2, 21.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.6, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.6, 2.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 0.0, 0.0, 0.0, 9.6, 3.4, 1.8, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 9.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.8, 12.6, 11.4, 2.0, 0.0, 0.0, 0.0, 0.0, 6.2, 7.6, 0.2, 0.4, 0.8, 2.8, 0.2, 0.0, 0.0, 0.0, 0.2, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 6.6, 1.2, 0.0, 0.0, 6.2, 29.4, 0.2, 0.0, 0.2, 2.4, 0.0, 0.0, 0.0, 0.2, 10.8, 11.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.8, 1.8, 0.0, 3.4, 3.6, 28.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 7.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 1.2, 0.2, 0.0, 0.0, 1.8, 0.0, 0.0, 0.0, 0.0, 1.6, 1.0, 0.0, 0.0, 0.0, 0.0, 14.2, 4.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 3.4, 5.6, 0.6, 23.2, 19.6, 25.6, 16.4, 3.8, 24.6, 1.4, 0.0, 0.0, 2.2, 0.0, 0.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 36.8, 0.6, 0.0, 1.2, 0.0, 0.0, 17.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 1.4, 0.4, 0.0, 0.0, 0.0, 2.6, 46.0, 11.4, 5.0, 3.0, 0.0, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 48.0, 0.2, 0.0, 0.0, 0.0, 13.4, 9.0, 0.6, 6.8, 2.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 6.2, 5.6, 0.0, 13.0, 0.0, 1.2, 0.8, 0.0, 0.0, 0.0, 0.8, 1.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.6, 20.2, 27.2, 4.6, 17.6, 1.6, 0.0, 0.0, 0.0, 3.6, 0.0, 15.0, 10.6, 0.6, 0.0, 8.0, 10.4, 0.6, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.2, 0.6, 29.8, 7.8, 23.6, 0.2, 31.8, 12.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 13.8, 6.2, 8.8, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 7.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.6, 0.6, 0.0, 0.0, 12.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.6, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 5.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.6, 38.2, 3.4, 6.6, 7.0, 2.2, 0.0, 24.4, 2.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 73.2, 1.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.4, 4.2, 0.0, 0.8, 0.0, 0.0, 0.0, 4.0, 0.2, 0.0, 0.0, 1.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 1.0, 0.0, 0.0, 0.0, 4.4, 10.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.4, 8.0, 0.0, 0.0, 0.0, 12.0, 4.8, 16.0, 5.4, 0.0, 0.0, 0.4, 0.0, 8.6, 1.0, 0.2, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.2, 13.0, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.2, 0.4, 0.0, 0.0, 0.0, 2.6, 2.6, 0.0, 0.0, 0.6, 23.4, 3.4, 4.0, 31.2, 77.4, 3.4, 0.0, 0.4, 0.0, 0.0, 70.0, 10.0, 15.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 4.2, 9.0, 0.2, 0.0, 0.0, 14.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.2, 0.0, 5.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 14.0, 0.2, 0.0, 0.0, 6.8, 1.2, 0.8, 3.8, 3.0, 4.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.8, 0.4, 0.0, 0.0, 0.0, 0.0, 1.8, 0.0, 0.2, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 13.8, 47.8, 1.0, 0.0, 17.2, 14.2, 5.6, 0.8, 9.0, 33.6, 1.6, 3.0, 3.0, 12.8, 12.4, 0.0, 6.0, 26.4, 61.4, 0.4, 4.2, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.2, 4.0, 18.8, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 4.2, 2.6, 32.0, 4.6, 0.2, 0.2, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.6, 0.4, 0.2, 4.6, 0.0, 16.0, 2.4, 2.6, 24.2, 3.4, 6.6, 0.0, 0.4, 16.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8, 4.6, 0.2, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 2.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 3.2, 7.4, 0.6, 0.0, 0.0, 0.0, 0.0, 2.4, 0.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.8, 0.2, 0.0, 0.0, 0.0, 0.0, 14.2, 12.0, 2.0, 0.0, 0.8, 0.0, 0.2, 0.0, 0.0, 0.0, 30.6, 0.2, 0.0, 1.8, 0.2, 0.0, 0.0, 5.2, 32.6, 0.2, 0.4, 8.4, 26.0, 8.8, 0.0, 5.6, 0.0, 8.6, 0.0, 0.0, 21.0, 0.4, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.8, 5.6, 27.6, 21.0, 0.2, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.6, 0.0, 0.0, 4.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 17.0, 1.8, 0.0, 0.0, 0.0, 0.0, 0.0, 5.6, 3.0, 0.0, 0.0, 7.6, 6.6, 9.4, 5.4, 0.4, 1.6, 0.2, 0.2, 0.6, 0.2, 0.0, 0.0, 7.2, 0.2, 5.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.4, 0.0, 0.2, 1.4, 9.6, 0.4, 0.0, 2.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 1.8, 0.4, 0.0, 0.0, 0.0, 0.8, 0.6, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0, 0.2, 0.0, 0.0, 0.0, 1.0, 0.2, 0.0, 0.8, 0.0, 5.6, 0.0, 10.4, 99.4, 20.8, 27.8, 0.8, 0.2, 0.0, 0.0, 5.0, 5.8, 10.8, 0.0, 1.8, 3.6, 0.0, 0.6, 0.4, 0.2, 0.0, 0.0, 0.0, 0.0, 4.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.6, 0.0, 0.0, 0.0, 1.0, 0.0, 12.0, 9.4, 0.0, 0.0, 0.0, 36.0, 65.2, 4.6, 2.6, 0.0, 0.0, 1.4, 0.0, 0.0, 0.0, 0.0, 0.0, 7.8, 18.2, 23.4, 10.4, 13.8, 4.2, 4.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8, 0.4, 0.4, 2.6, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 9.0, 2.2, 1.4, 0.6, 76.8, 39.2, 88.2, 57.4, 2.0, 0.6, 0.6, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 4.4, 0.0, 0.0, 0.0, 13.0, 2.6, 1.0, 0.6, 0.0, 0.0, 5.6, 0.8, 20.2, 2.2, 0.0, 0.0, 1.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.4, 0.0, 4.4, 1.6, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 23.8, 30.0, 0.4, 0.0, 7.8, 0.8, 0.2, 9.8, 4.6, 0.2, 0.2, 0.0, 2.2, 2.0, 1.0, 0.2, 0.0, 0.0, 0.2, 0.0, 7.2, 0.2, 3.2, 0.2, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.8, 2.8, 2.2, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 11.4, 3.8, 0.2, 0.0, 0.0, 0.6, 19.8, 0.0, 0.4, 0.0, 0.0, 0.0, 12.8, 1.8, 0.0, 0.0, 2.4, 4.8, 38.8, 14.8, 7.6, 22.0, 6.8, 0.0, 0.0, 0.0, 1.4, 1.4, 0.0, 0.0, 4.8, 5.4, 2.2, 23.6, 0.6, 0.2, 0.0, 12.6, 4.2, 0.4, 0.2, 0.0, 0.0, 0.0, 0.0, 14.8, 0.0, 0.0, 5.2, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 0.0, 0.0, 31.6, 0.2, 0.0, 0.0, 0.0, 0.0, 29.0, 18.6, 6.0, 0.0, 0.0, 0.0, 12.0, 0.2, 0.0, 7.2, 29.6, 2.0, 0.2, 0.0, 1.4, 0.0, 8.8, 5.4, 49.8, 6.0, 0.2, 0.0, 2.2, 1.4, 0.2, 3.8, 2.2, 3.2, 1.8, 0.0, 0.6, 0.0, 0.0, 0.6, 0.0, 15.6, 6.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8, 27.6, 16.0, 16.8, 2.2, 14.8, 0.0, 0.0, 109.4, 18.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 41.8, 2.4, 12.0, 1.2, 0.0, 0.0, 0.4, 0.0, 0.0, 0.4, 0.4, 0.0, 6.2, 0.2, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.4, 0.0, 0.0, 7.2, 0.0, 0.0, 0.0, 0.0, 23.6, 48.8, 56.0, 0.8, 0.0, 0.0, 1.6, 3.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 13.8, 0.0, 0.2, 0.0, 21.4, 1.4, 0.0, 0.2, 0.2, 27.4, 11.2, 0.0, 19.2, 6.8, 0.0, 0.0, 2.4, 76.4, 49.4, 8.6, 13.8, 0.0, 0.4, 8.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.8, 9.4, 0.0, 1.6, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 19.0, 1.2, 0.2, 0.0, 0.0, 5.4, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 2.6, 6.8, 4.4, 0.0, 0.4, 0.0, 0.0, 0.0, 4.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 10.2, 0.0, 0.0, 0.0, 0.0, 0.4, 0.8, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.8, 0.0, 0.0, 0.0, 0.0, 3.6, 0.2, 0.0, 0.8, 0.0, 0.0, 0.2, 0.4, 0.2, 0.0, 0.0, 0.0, 0.6, 0.2, 0.0, 0.0, 0.0, 3.0, 0.2, 0.0, 9.8, 3.4, 4.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.6, 1.4, 0.2, 0.0, 0.0, 0.0, 9.2, 11.4, 0.2, 0.0, 0.0, 0.0, 0.2, 0.4, 10.4, 0.0, 0.0, 1.6, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 3.6, 10.2, 1.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.6, 0.2, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 16.8, 15.8, 95.2, 0.8, 0.0, 31.8, 15.2, 7.4, 4.4, 0.2, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.8, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 2.8, 0.0, 27.4, 61.4, 18.4, 2.4, 3.8, 2.0, 5.2, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.0, 0.0, 0.2, 0.4, 33.6, 32.8, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 27.2, 30.6, 20.0, 0.0, 3.4, 28.6, 0.2, 0.0, 0.0, 0.0, 14.8, 34.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 0.0, 8.4, 0.0, 0.0, 0.0, 0.0, 0.0, 15.6, 1.4, 0.0, 1.2, 56.2, 53.4, 5.0, 15.6, 0.8, 16.8, 41.0, 51.0, 9.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.6, 8.0, 0.0, 0.2, 0.0, 0.0, 0.2, 1.4, 4.8, 0.0, 0.0, 0.8, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 9.6, 4.2, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.2, 0.0, 1.2, 32.2, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.6, 0.0, 0.0, 0.0, 0.0, 28.2, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11.6, 39.6, 20.2, 7.4, 0.0, 0.0, 23.0, 40.8, 11.2, 17.6, 0.2, 0.0, 3.0, 7.4, 3.6, 0.0, 4.2, 0.0, 0.0, 0.2, 2.8, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.2, 2.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 21.0, 1.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 5.8, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 3.0, 0.2, 0.0, 2.4, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.2, 1.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.2, 3.4, 1.0, 1.0, 6.0, 21.8, 0.0, 0.0, 13.2, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 4.4, 2.4, 10.4, 6.6, 4.6, 1.4, 0.2, 1.6, 0.2, 0.0, 0.0, 0.2, 0.0, 0.0, 27.8, 0.2, 0.0, 5.4, 5.0, 0.2, 0.0, 0.0, 1.0, 0.0, 0.0, 0.4, 6.8, 0.6, 18.0, 7.4, 0.8, 0.2, 3.6, 0.0, 0.0, 0.0, 0.0, 5.6, 3.4, 16.0, 5.0, 0.0, 0.0, 5.6, 5.0, 3.8, 2.8, 4.2, 29.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.8, 9.2, 0.4, 20.2, 0.0, 3.4, 0.0, 0.0, 1.2, 3.8, 0.0, 0.0, 0.0, 0.0, 7.4, 0.4, 0.8, 0.0, 11.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.4, 11.2, 1.0, 0.0, 0.0, 8.6, 13.2, 6.8, 0.0, 2.2, 13.8, 5.6, 0.0, 0.0, 5.0, 0.2, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.2, 0.0, 0.0, 1.6, 1.8, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 8.2, 4.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 21.4, 19.4, 0.2, 0.0, 0.0, 28.6, 21.8, 38.4, 8.2, 10.8, 10.2, 3.2, 3.8, 0.0, 12.6, 13.2, 15.2, 2.0, 3.2, 3.0, 0.0, 0.2, 5.0, 0.2, 4.4, 11.0, 18.4, 1.0, 0.0, 5.0, 0.2, 0.2, 0.8, 0.4, 0.0, 0.0, 0.0, 0.0, 1.0, 0.2, 0.0, 0.0, 0.0, 2.0, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.4, 0.0, 0.2, 0.0, 0.0, 0.0, 9.4, 70.8, 0.2, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 2.4, 0.2, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.6, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 3.2, 8.2, 1.0, 23.8, 6.2, 1.8, 5.4, 15.8, 0.4, 0.0, 9.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.6, 0.0, 28.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 21.0, 9.6, 4.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.2, 18.0, 0.2, 0.0, 0.0, 1.0, 0.6, 33.0, 57.0, 14.0, 0.0, 0.0, 0.0, 3.4, 1.0, 1.2, 7.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 6.8, 4.4, 0.6, 0.0, 0.0, 0.0, 0.2, 0.0, 1.0, 1.2, 0.0, 0.2, 0.0, 4.2, 26.8, 0.2, 0.0, 11.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.6, 1.2, 0.0, 8.8, 0.0, 0.0, 0.2, 0.0, 2.0, 2.2, 1.4, 0.2, 22.4, 0.2, 0.0, 0.0, 0.0, 0.0, 14.2, 6.0, 0.0, 0.6, 24.0, 21.4, 0.0, 0.4, 5.8, 0.2, 0.4, 7.8, 0.2, 0.0, 0.0, 0.0, 0.6, 1.6, 0.4, 2.4, 13.2, 119.4, 105.8, 29.0, 0.0, 0.2, 13.0, 4.0, 0.2, 0.0, 10.2, 28.4, 8.6, 31.6, 0.4, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.2, 0.2, 0.8, 0.6, 0.0, 0.2, 0.4, 0.2, 11.2, 24.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 6.6, 0.4, 0.0, 0.0, 0.2, 2.6, 10.8, 2.2, 67.0, 7.2, 1.2, 3.0, 0.0, 0.0, 0.0, 6.2, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.6, 0.0, 0.0, 0.8, 2.2, 4.8, 0.6, 0.2, 0.2, 17.2, 9.0, 0.6, 0.0, 3.0, 0.0, 1.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.6, 0.0, 0.0, 0.0, 0.0, 0.0, 2.4, 4.2, 54.4, 5.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8, 20.4, 0.0, 0.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.2, 10.8, 0.4, 0.2, 0.2, 0.2, 3.2, 31.8, 3.4, 3.6, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.6, 1.6, 3.4, 0.0, 0.0, 0.0, 1.4, 0.2, 0.4, 1.0, 8.4, 14.8, 0.2, 0.0, 0.0, 7.6, 0.4, 0.0, 0.0, 0.0, 0.0, 26.0, 1.4, 3.8, 13.0, 11.6, 10.0, 0.4, 0.0, 0.0, 0.0, 2.4, 0.4, 18.2, 29.6, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 15.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.6, 9.8, 0.0, 0.0, 0.0, 29.8, 34.0, 1.0, 0.0, 0.6, 1.8, 2.6, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 15.0, 34.2, 51.4, 41.4, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 34.0, 5.4, 0.0, 0.0, 0.0, 0.0, 0.0, 30.6, 13.0, 0.0, 0.0, 0.0, 2.2, 0.4, 0.0, 9.0, 12.8, 0.2, 2.0, 0.0, 10.8, 3.6, 1.8, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 1.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 16.8, 23.0, 13.6, 3.4, 4.8, 0.2, 61.2, 25.4, 1.6, 0.0, 0.0, 0.0, 0.2, 34.8, 0.0, 7.0, 1.2, 0.0, 0.0, 0.0, 94.4, 6.4, 0.0, 0.2, 0.0, 0.4, 0.0, 0.0, 8.2, 0.6, 0.6, 1.0, 0.0, 0.0, 2.0, 15.0, 15.8, 0.0, 0.0, 6.6, 3.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0, 2.2, 0.2, 0.0, 29.4, 1.0, 0.2, 64.4, 93.8, 68.4, 0.0, 0.0, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 0.4, 38.8, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 2.4, 0.2, 0.0, 0.0, 0.0, 4.8, 0.2, 29.4, 22.4, 2.2, 1.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.8, 0.0, 0.2, 17.0, 20.4, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 24.8, 4.0, 1.8, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 1.8, 2.4, 52.8, 0.0, 1.4, 0.0, 0.0, 0.0, 0.0, 0.0, 14.4, 23.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.2, 0.0, 0.0, 0.0, 5.8, 0.0, 0.0, 0.0, 0.0, 13.4, 0.0, 0.0, 2.0, 0.6, 0.0, 3.4, 4.0, 0.0, 0.0, 1.4, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 3.8, 0.0, 4.4, 0.2, 0.0, 0.0, 0.0, 3.0, 0.2, 0.0, 0.0, 11.8, 0.6, 0.8, 0.0, 0.0, 0.0, 1.4, 3.2, 0.2, 1.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 10.2, 0.0, 9.0, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.4, 3.2, 7.8, 0.2, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 8.2, 32.6, 10.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 2.6, 1.2, 5.0, 8.8, 4.4, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.8, 0.0, 0.0, 0.0, 17.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.2, 4.4, 0.0, 0.0, 0.0, 0.0, 6.4, 85.0, 5.4, 0.0, 0.0, 0.0, 0.0, 0.0, 25.6, 0.0, 0.0, 8.0, 3.2, 0.6, 0.0, 0.0, 0.0, 0.0, 7.8, 28.6, 26.4, 2.6, 26.4, 3.2, 37.8, 27.6, 7.6, 2.4, 0.0, 5.0, 1.0, 0.6, 0.2, 0.0, 0.0, 0.4, 38.0, 2.6, 20.0, 45.8, 4.2, 0.2, 0.0, 25.6, 18.2, 10.2, 4.8, 0.0, 0.0, 0.0, 0.0, 2.4, 42.4, 0.0, 0.0, 33.8, 7.8, 0.4, 0.2, 0.0, 0.0, 0.0, 8.8, 0.0, 9.4, 19.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 1.4, 3.8, 0.4, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.4, 3.2, 0.0, 5.2, 0.0, 0.0, 0.0, 0.0, 14.6, 0.0, 0.0, 0.0, 0.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.4, 0.0, 0.0, 54.6, 61.0, 3.4, 38.8, 2.8, 1.2, 0.0, 2.6, 0.6, 0.0, 0.0, 1.8, 0.4, 4.4, 0.0, 0.0, 0.0, 0.0, 0.0], 'Evaporation': [6.2, 3.4, 2.4, 2.2, 4.8, 2.6, 5.2, 5.8, 4.8, 4.4, 6.4, 6.8, 7.0, 3.2, 6.2, 6.2, 7.6, 4.2, 5.2, 4.6, 6.8, 4.4, 6.6, 8.6, 8.6, 3.6, 8.2, 4.2, 7.0, 6.2, 6.4, 2.6, 6.8, 6.0, 5.0, 7.6, 6.0, 4.6, 4.6, 7.6, 7.0, 6.0, 5.4, 7.0, 5.6, 6.4, 8.0, 6.6, 6.0, 7.0, 2.2, 4.0, 2.6, 6.4, 2.4, 5.8, 2.6, 4.8, 4.6, 5.8, 6.6, 3.8, 10.6, 7.6, 4.2, 3.6, 3.2, 5.4, 5.4, 3.6, 3.2, 4.0, 1.8, 3.2, 2.8, 4.6, 1.4, 3.2, 4.8, 4.0, 7.5, 3.6, 4.0, 1.6, 2.6, 5.2, 7.6, 3.8, 3.6, 4.0, 2.4, 3.4, 3.6, 2.0, 3.4, 3.6, 3.2, 3.2, 3.0, 1.2, 1.6, 1.8, 2.0, 3.2, 2.2, 4.2, 4.2, 4.4, 3.0, 2.4, 4.0, 3.4, 2.4, 3.6, 0.4, 3.2, 1.6, 1.0, 1.4, 1.0, 2.2, 1.8, 0.4, 2.4, 2.4, 0.4, 2.2, 1.4, 1.2, 1.6, 1.8, 1.8, 3.4, 3.8, 2.8, 5.0, 0.8, 1.6, 2.0, 0.6, 1.8, 3.4, 3.4, 1.8, 2.8, 3.2, 4.4, 3.0, 0.8, 3.2, 3.8, 4.0, 3.2, 2.4, 1.6, 2.2, 2.2, 1.6, 2.8, 2.4, 4.8, 3.4, 2.6, 1.8, 1.8, 2.0, 1.4, 4.0, 3.4, 3.2, 1.6, 3.8, 4.0, 0.2, 2.4, 1.4, 2.0, 3.0, 1.4, 2.6, 3.4, 4.6, 4.6, 3.6, 3.0, 3.4, 3.4, 0.4, 1.4, 4.0, 3.0, 3.6, 3.0, 4.0, 4.0, 4.6, 4.0, 4.6, 3.4, 1.8, 3.8, 3.2, 3.4, 1.6, 3.0, 3.6, 2.6, 3.2, 4.2, 4.8, 4.8, 4.0, 3.0, 3.4, 4.6, 4.4, 4.8, 0.0, 3.4, 6.2, 4.0, 3.0, 3.6, 7.4, 9.6, 3.0, 10.6, 7.2, 3.6, 4.2, 7.6, 9.0, 4.4, 10.4, 2.4, 4.0, 6.2, 5.6, 6.6, 6.6, 6.4, 5.2, 6.6, 8.6, 10.4, 1.0, 2.0, 3.4, 4.8, 5.4, 6.0, 6.6, 3.6, 7.0, 9.2, 3.2, 4.2, 5.8, 7.4, 7.8, 8.0, 5.2, 6.0, 4.2, 2.4, 4.8, 8.0, 7.6, 11.4, 4.6, 1.2, 3.2, 10.2, 4.6, 3.4, 7.8, 7.8, 6.0, 8.4, 5.2, 4.4, 8.0, 5.2, 6.6, 8.0, 10.6, 9.4, 3.4, 6.8, 4.0, 7.8, 4.6, 7.0, 10.0, 9.8, 5.0, 5.6, 7.6, 5.0, 7.8, 2.6, 4.8, 7.6, 12.0, 8.0, 10.0, 4.8, 6.4, 7.6, 4.4, 5.4, 9.4, 4.6, 4.0, 4.8, 12.0, 9.8, 6.8, 9.2, 4.8, 10.2, 10.6, 5.2, 7.2, 10.8, 4.8, 0.8, 4.0, 7.2, 6.0, 8.0, 5.6, 7.4, 9.8, 11.0, 9.0, 5.4, 10.0, 10.0, 9.0, 9.8, 7.6, 7.6, 6.6, 8.8, 4.2, 10.2, 14.2, 10.2, 10.4, 5.6, 11.0, 9.0, 12.8, 8.0, 14.2, 10.6, 13.6, 6.8, 1.8, 1.8, 8.6, 10.2, 10.6, 9.2, 6.4, 10.8, 7.0, 6.6, 9.8, 10.4, 14.2, 9.0, 1.6, 2.2, 4.0, 5.4, 4.4, 2.4, 4.8, 7.4, 3.2, 3.6, 7.8, 6.4, 2.4, 4.6, 5.4, 7.0, 7.6, 6.0, 4.8, 6.8, 6.0, 6.8, 7.6, 5.0, 7.8, 4.8, 5.0, 2.0, 3.6, 6.2, 5.0, 6.4, 4.0, 8.4, 6.8, 6.1, 5.4, 6.0, 6.2, 6.2, 5.6, 8.0, 5.8, 7.0, 5.2, 5.8, 4.4, 6.6, 4.0, 6.0, 5.0, 3.8, 2.6, 4.2, 5.6, 3.4, 5.8, 5.6, 2.8, 4.0, 3.2, 3.6, 4.8, 5.0, 10.0, 4.8, 5.2, 3.4, 7.0, 5.4, 3.4, 4.2, 2.0, 5.4, 6.8, 7.2, 4.0, 4.6, 2.4, 3.0, 2.2, 3.6, 3.2, 1.8, 3.2, 4.0, 2.6, 4.4, 3.4, 3.4, 2.6, 1.6, 2.6, 6.2, 5.0, 4.8, 2.6, 2.4, 4.4, 1.8, 6.6, 5.0, 4.4, 3.6, 0.6, 3.0, 0.4, 2.4, 4.6, 1.2, 3.0, 1.2, 2.8, 0.0, 1.0, 2.2, 3.8, 3.2, 2.6, 4.4, 4.0, 3.0, 2.6, 3.4, 0.8, 3.0, 0.8, 1.0, 1.4, 3.8, 0.6, 1.8, 1.6, 1.4, 2.2, 1.8, 2.2, 2.2, 2.0, 1.4, 4.0, 4.8, 5.6, 3.8, 3.0, 3.0, 2.6, 2.6, 0.4, 1.8, 2.0, 1.4, 2.4, 3.2, 2.6, 2.0, 3.2, 3.0, 2.2, 2.6, 5.4, 4.8, 5.6, 2.2, 1.8, 5.8, 0.4, 3.6, 2.2, 4.0, 3.0, 3.8, 4.0, 4.0, 3.2, 2.8, 2.0, 4.8, 6.4, 2.6, 1.8, 1.2, 1.6, 5.4, 3.0, 3.2, 2.0, 8.0, 6.2, 4.2, 2.8, 4.0, 7.0, 3.6, 5.6, 5.0, 8.4, 6.0, 3.2, 9.2, 9.2, 6.0, 4.2, 3.8, 4.6, 1.8, 6.4, 3.8, 5.4, 3.6, 3.6, 5.0, 5.0, 6.0, 8.2, 7.4, 6.4, 3.4, 1.6, 10.4, 5.4, 5.8, 8.2, 3.4, 11.2, 7.6, 8.0, 11.2, 8.0, 8.2, 4.0, 5.4, 7.0, 10.2, 3.0, 2.4, 1.8, 2.6, 3.6, 6.8, 5.2, 3.4, 3.4, 4.8, 5.0, 11.2, 7.6, 7.4, 8.0, 5.8, 4.4, 5.8, 7.6, 9.4, 5.0, 7.0, 5.6, 4.8, 3.8, 4.0, 7.4, 8.0, 7.0, 6.2, 13.2, 2.2, 3.0, 4.2, 6.4, 2.6, 5.4, 10.2, 6.8, 8.8, 6.2, 8.8, 6.4, 8.8, 7.2, 8.0, 8.8, 12.4, 7.4, 13.4, 5.2, 3.0, 7.8, 7.8, 12.8, 10.6, 11.8, 6.4, 6.4, 6.8, 8.0, 9.8, 6.2, 8.2, 10.2, 8.2, 7.8, 7.0, 11.4, 8.4, 9.0, 4.8, 9.2, 10.4, 13.6, 3.8, 10.2, 4.4, 9.0, 2.8, 1.8, 2.6, 2.4, 8.6, 8.0, 2.8, 6.8, 7.0, 2.4, 4.6, 8.4, 8.0, 6.0, 5.4, 11.0, 8.6, 8.8, 9.2, 7.8, 3.8, 5.4, 6.6, 8.0, 10.0, 10.4, 9.0, 8.2, 13.4, 8.6, 3.6, 4.0, 6.2, 4.8, 3.4, 6.4, 5.4, 7.8, 8.0, 6.4, 6.0, 4.8, 5.0, 7.4, 1.8, 5.8, 5.8, 8.8, 9.0, 9.4, 2.0, 2.8, 7.6, 7.8, 8.0, 7.2, 6.4, 9.6, 9.4, 10.4, 9.2, 4.4, 6.0, 3.8, 8.0, 5.0, 3.8, 7.2, 4.4, 5.2, 3.4, 5.0, 6.4, 9.2, 8.0, 5.2, 9.0, 7.4, 5.6, 5.4, 5.8, 5.4, 6.6, 7.0, 6.2, 7.0, 8.4, 4.4, 7.6, 4.0, 5.6, 7.4, 5.4, 2.8, 4.8, 2.6, 3.6, 5.8, 6.6, 3.2, 4.4, 2.2, 2.8, 1.4, 5.0, 6.2, 3.8, 8.6, 5.6, 3.8, 6.0, 3.6, 2.4, 2.8, 4.4, 3.4, 5.4, 3.2, 7.2, 5.0, 3.0, 4.4, 2.4, 5.0, 5.0, 2.4, 1.2, 4.0, 2.8, 3.8, 4.4, 3.8, 4.0, 2.0, 4.4, 4.2, 8.0, 4.4, 4.4, 4.0, 4.4, 2.4, 1.0, 4.8, 2.8, 1.2, 2.8, 5.0, 0.2, 4.8, 2.2, 5.8, 1.4, 2.8, 1.4, 1.6, 2.6, 3.0, 2.4, 3.4, 1.0, 2.2, 3.4, 4.8, 2.2, 3.8, 3.2, 3.0, 3.8, 1.8, 2.0, 1.6, 4.0, 3.0, 3.4, 2.2, 0.6, 3.2, 1.4, 2.8, 2.0, 2.6, 3.0, 2.0, 2.0, 1.8, 3.2, 3.4, 0.4, 1.4, 0.0, 2.0, 1.2, 2.0, 0.6, 1.8, 5.2, 4.4, 2.6, 2.0, 3.6, 1.0, 3.2, 1.0, 2.0, 2.6, 1.0, 3.8, 1.6, 1.6, 1.4, 3.8, 0.2, 3.8, 4.0, 4.0, 4.0, 3.8, 2.4, 4.2, 3.0, 2.6, 2.4, 0.6, 6.6, 2.6, 4.2, 6.4, 4.0, 4.4, 4.2, 5.0, 6.2, 5.6, 4.6, 3.6, 2.2, 6.0, 6.4, 5.8, 4.0, 2.2, 3.2, 6.4, 3.8, 1.8, 2.8, 5.6, 8.0, 3.2, 4.0, 4.0, 2.0, 4.4, 3.8, 4.2, 5.4, 5.0, 6.4, 5.0, 4.0, 3.6, 3.0, 4.6, 5.0, 3.2, 5.4, 5.4, 2.6, 1.0, 4.0, 4.0, 7.8, 3.4, 6.6, 3.0, 6.6, 5.6, 8.0, 7.4, 3.8, 6.8, 5.4, 6.2, 3.2, 7.2, 6.6, 3.8, 4.0, 5.4, 8.4, 4.8, 3.6, 5.8, 11.2, 3.2, 7.2, 9.0, 10.4, 1.0, 6.6, 3.6, 8.0, 9.0, 11.0, 8.8, 11.6, 6.0, 10.8, 3.4, 1.8, 3.4, 1.8, 5.2, 7.4, 5.8, 8.0, 7.6, 10.4, 4.8, 6.8, 9.2, 10.2, 6.0, 7.6, 5.8, 7.8, 5.0, 9.2, 8.4, 9.2, 8.4, 8.0, 7.0, 8.0, 11.8, 5.4, 5.2, 8.6, 8.8, 10.0, 10.6, 7.2, 5.0, 5.4, 5.2, 6.4, 5.2, 4.6, 7.0, 6.6, 4.4, 10.6, 4.6, 11.4, 4.2, 8.8, 8.0, 5.6, 5.8, 8.2, 10.2, 11.0, 10.8, 10.6, 7.0, 7.2, 7.2, 7.8, 8.4, 9.2, 12.0, 12.8, 10.2, 5.2, 8.4, 16.6, 6.8, 4.8, 5.2, 7.2, 5.0, 8.6, 2.4, 4.0, 6.6, 3.6, 6.4, 5.0, 4.4, 7.2, 8.2, 9.0, 4.2, 5.0, 7.4, 7.6, 8.0, 5.0, 4.4, 9.2, 2.2, 8.0, 8.2, 8.2, 4.8, 6.8, 8.0, 6.2, 3.6, 3.2, 6.4, 8.0, 4.0, 3.2, 5.8, 5.4, 5.2, 4.8, 5.2, 1.6, 5.8, 8.6, 8.8, 5.2, 5.4, 1.6, 1.8, 6.6, 5.2, 0.8, 3.8, 2.4, 0.2, 4.6, 4.4, 4.6, 1.6, 3.8, 3.4, 3.8, 2.2, 4.0, 3.4, 4.8, 5.0, 2.2, 2.8, 1.8, 3.8, 1.0, 3.4, 3.4, 6.6, 1.4, 1.6, 2.4, 3.2, 0.6, 4.4, 4.8, 4.6, 3.2, 1.2, 2.8, 3.0, 2.0, 4.0, 1.8, 3.6, 4.8, 0.2, 4.8, 2.4, 3.4, 6.0, 3.6, 1.4, 3.6, 2.8, 3.4, 5.0, 4.6, 3.8, 3.4, 2.4, 1.8, 2.6, 2.6, 2.0, 1.6, 2.6, 1.4, 3.0, 4.4, 4.8, 5.6, 5.4, 4.0, 4.0, 3.8, 4.0, 3.2, 3.8, 2.8, 2.0, 1.4, 1.4, 1.0, 3.2, 4.8, 6.4, 4.8, 5.6, 2.8, 1.6, 0.4, 3.0, 1.8, 3.6, 2.8, 3.4, 2.4, 3.8, 2.8, 4.8, 5.4, 5.8, 5.0, 2.0, 3.8, 0.8, 4.8, 6.2, 1.2, 2.2, 1.6, 2.4, 2.0, 2.2, 4.2, 3.8, 6.0, 4.2, 2.8, 1.4, 4.0, 4.0, 3.4, 0.8, 3.6, 3.6, 2.4, 1.0, 4.0, 1.0, 3.4, 5.6, 3.2, 8.4, 5.8, 1.6, 2.3, 4.4, 6.0, 4.0, 5.2, 6.8, 4.8, 5.8, 6.8, 3.8, 8.0, 9.0, 5.2, 5.6, 8.2, 6.8, 4.0, 5.0, 7.2, 1.4, 7.0, 6.6, 6.4, 4.2, 6.0, 4.0, 3.0, 2.2, 4.0, 4.0, 4.4, 5.4, 5.4, 4.4, 4.6, 4.2, 3.4, 7.0, 8.0, 4.0, 8.0, 7.6, 8.8, 4.8, 4.8, 11.8, 4.0, 3.2, 4.6, 6.2, 5.6, 6.2, 5.4, 5.8, 4.6, 2.6, 6.4, 7.2, 8.2, 5.2, 10.8, 10.2, 6.2, 9.0, 8.6, 10.0, 2.4, 0.4, 6.2, 8.8, 4.8, 4.4, 7.4, 3.4, 2.4, 3.2, 7.4, 6.6, 9.4, 7.2, 9.0, 8.0, 6.8, 7.2, 7.6, 2.8, 4.0, 3.2, 3.4, 5.8, 3.8, 4.8, 2.0, 8.0, 7.8, 7.2, 5.4, 7.6, 7.0, 2.2, 6.8, 4.6, 3.0, 2.6, 7.2, 9.0, 6.8, 7.2, 7.0, 8.8, 7.0, 5.6, 10.2, 7.2, 13.4, 9.0, 6.6, 7.2, 8.8, 3.0, 9.0, 8.6, 13.2, 7.8, 9.4, 11.0, 3.4, 6.0, 7.2, 7.0, 4.8, 4.6, 9.8, 7.6, 2.4, 7.8, 2.8, 6.2, 6.6, 8.8, 11.2, 5.6, 2.8, 1.4, 0.2, 6.6, 8.8, 5.6, 4.0, 2.8, 5.8, 6.8, 4.8, 4.8, 4.0, 5.0, 7.4, 8.6, 6.4, 6.6, 12.6, 4.2, 7.0, 5.6, 7.6, 8.0, 7.6, 5.0, 7.4, 4.8, 1.6, 4.6, 2.8, 2.0, 5.8, 8.4, 6.6, 4.8, 1.2, 5.0, 6.4, 6.8, 4.0, 6.8, 4.6, 7.8, 7.4, 3.8, 6.0, 3.6, 5.6, 4.8, 1.4, 6.6, 7.8, 3.4, 5.6, 5.6, 3.4, 4.0, 3.4, 5.6, 3.8, 3.0, 6.0, 3.2, 6.6, 8.0, 8.0, 3.8, 7.0, 6.0, 2.8, 3.8, 4.8, 3.8, 4.8, 5.0, 3.2, 4.8, 1.0, 4.0, 1.6, 1.0, 4.0, 5.8, 3.4, 2.4, 3.0, 5.4, 2.4, 3.6, 3.0, 5.0, 3.0, 4.2, 3.0, 1.2, 3.0, 3.8, 4.0, 2.6, 5.4, 4.6, 3.2, 3.8, 2.0, 1.8, 3.8, 3.0, 0.4, 3.0, 4.0, 4.0, 1.0, 6.0, 3.4, 2.6, 3.0, 1.0, 3.2, 1.0, 0.6, 1.6, 0.2, 4.2, 2.6, 1.6, 2.6, 2.0, 0.2, 4.2, 2.4, 1.6, 1.2, 1.6, 1.8, 0.8, 3.4, 2.2, 4.4, 2.6, 5.0, 2.0, 3.2, 2.0, 2.0, 1.0, 2.4, 2.0, 3.0, 3.8, 2.8, 3.6, 2.6, 1.8, 2.4, 0.8, 1.2, 1.8, 3.4, 3.0, 0.4, 3.2, 5.0, 2.6, 3.6, 3.2, 3.6, 2.8, 2.0, 3.6, 2.4, 0.2, 3.8, 2.4, 4.0, 1.6, 4.0, 3.0, 2.4, 4.2, 3.6, 2.4, 1.6, 7.2, 3.2, 3.6, 3.4, 5.0, 4.6, 2.0, 5.8, 6.6, 6.0, 3.2, 2.6, 3.8, 6.4, 7.8, 6.4, 4.4, 5.0, 6.2, 5.0, 3.8, 3.4, 4.0, 5.2, 13.4, 10.8, 6.6, 5.4, 3.8, 5.6, 3.0, 5.2, 3.2, 5.4, 3.6, 3.8, 6.0, 4.4, 4.8, 4.4, 8.2, 3.2, 4.2, 6.8, 6.4, 8.4, 6.8, 5.0, 5.8, 7.2, 10.8, 7.6, 3.2, 7.8, 3.8, 6.8, 2.0, 4.0, 4.8, 6.4, 7.2, 11.4, 7.4, 6.6, 6.8, 5.0, 6.0, 2.0, 6.0, 8.2, 9.0, 5.4, 9.2, 3.6, 7.2, 7.0, 8.0, 10.8, 5.6, 2.6, 5.2, 9.0, 8.6, 3.8, 4.2, 7.4, 9.6, 6.0, 9.8, 8.0, 4.2, 5.0, 2.4, 6.0, 8.4, 7.0, 5.2, 9.0, 5.4, 5.2, 7.8, 9.4, 4.4, 3.2, 2.4, 7.0, 11.0, 7.4, 5.6, 9.0, 9.6, 11.6, 8.0, 9.8, 18.4, 8.4, 6.2, 9.6, 6.2, 2.0, 9.8, 6.6, 8.2, 9.0, 12.6, 5.0, 4.2, 7.4, 6.2, 7.2, 4.6, 11.4, 8.2, 2.2, 4.8, 5.6, 5.6, 6.8, 6.2, 4.8, 6.6, 6.0, 7.4, 7.4, 7.8, 6.8, 7.4, 7.8, 6.4, 5.4, 7.8, 2.6, 4.2, 6.8, 8.6, 6.4, 5.4, 6.6, 6.8, 8.4, 4.8, 7.0, 4.4, 5.4, 7.0, 8.0, 5.2, 5.0, 6.6, 3.8, 6.6, 5.0, 0.8, 3.6, 2.4, 3.4, 2.4, 2.2, 4.6, 4.4, 4.8, 5.4, 5.8, 3.2, 4.0, 2.6, 4.6, 4.8, 2.8, 2.6, 3.6, 3.6, 4.8, 3.4, 4.4, 4.6, 6.2, 2.8, 1.2, 5.6, 3.0, 4.4, 6.4, 3.4, 3.0, 3.4, 1.8, 3.6, 2.0, 3.6, 2.0, 2.4, 2.8, 5.4, 4.6, 3.8, 3.6, 4.0, 4.0, 2.2, 5.2, 2.4, 3.8, 1.8, 3.2, 1.2, 2.0, 2.6, 1.6, 4.0, 3.0, 4.6, 3.6, 3.4, 1.6, 2.0, 3.0, 7.0, 1.4, 0.2, 2.0, 0.6, 3.6, 4.0, 3.2, 3.8, 1.6, 3.2, 2.8, 2.0, 2.4, 0.4, 0.2, 2.4, 1.4, 3.4, 2.8, 3.2, 2.0, 0.8, 2.2, 2.2, 2.6, 4.0, 4.2, 4.0, 2.2, 3.0, 1.2, 1.2, 1.2, 3.0, 1.0, 3.6, 0.2, 1.8, 2.4, 3.2, 2.4, 6.4, 3.8, 3.2, 4.0, 3.0, 3.4, 1.8, 3.6, 2.6, 3.4, 2.6, 3.4, 2.2, 3.6, 4.2, 3.8, 5.6, 4.8, 3.8, 0.6, 4.0, 3.8, 3.8, 5.8, 4.2, 8.0, 3.6, 6.2, 6.6, 7.8, 6.2, 3.0, 5.6, 4.0, 4.0, 4.2, 3.6, 2.2, 3.0, 3.8, 5.2, 5.8, 4.8, 4.0, 4.2, 3.8, 5.8, 5.0, 3.2, 4.6, 2.2, 7.4, 11.6, 6.4, 5.6, 3.4, 4.0, 2.2, 4.8, 6.8, 7.6, 6.2, 7.0, 4.6, 5.4, 7.4, 6.4, 8.4, 12.2, 8.0, 9.8, 6.4, 8.6, 9.8, 10.0, 3.8, 5.2, 5.6, 9.8, 5.8, 5.0, 10.0, 13.2, 5.8, 6.6, 15.2, 5.8, 6.4, 11.2, 13.4, 6.8, 7.2, 6.2, 9.4, 2.8, 12.4, 10.8, 8.8, 6.0, 3.2, 4.8, 7.4, 5.4, 8.0, 5.6, 7.6, 11.2, 9.8, 4.6, 8.0, 9.4, 10.4, 9.6, 9.4, 1.8, 3.2, 9.6, 7.8, 4.8, 5.6, 4.0, 2.0, 6.8, 6.2, 9.8, 4.0, 5.0, 8.2, 7.4, 5.6, 8.0, 10.6, 3.4, 7.0, 5.0, 8.0, 8.8, 8.0, 10.0, 7.6, 7.2, 10.0, 8.0, 11.2, 10.4, 6.8, 8.8, 7.8, 7.0, 3.6, 10.0, 9.0, 10.0, 11.6, 8.0, 7.6, 6.6, 3.6, 1.2, 6.2, 5.6, 10.2, 11.4, 6.4, 7.4, 8.0, 5.6, 7.4, 8.2, 9.4, 11.4, 7.6, 3.8, 6.6, 7.2, 10.4, 7.6, 7.2, 10.0, 10.8, 10.4, 10.6, 10.8, 4.2, 5.0, 2.8, 4.4, 7.4, 5.6, 8.6, 3.6, 9.4, 12.0, 9.6, 12.6, 11.0, 7.2, 12.0, 12.0, 5.2, 7.2, 4.2, 9.2, 9.6, 10.4, 7.2, 6.0, 4.6, 8.8, 2.2, 2.4, 7.0, 2.4, 2.2, 4.2, 11.4, 5.8, 8.0, 6.4, 7.4, 9.8, 5.2, 3.2, 1.6, 2.4, 3.8, 2.6, 4.0, 7.0, 5.2, 5.6, 6.4, 6.8, 8.6, 8.2, 7.0, 4.0, 7.8, 5.8, 6.2, 7.2, 6.6, 6.2, 6.0, 6.0, 5.2, 6.2, 4.2, 2.8, 2.8, 1.0, 3.6, 3.6, 5.0, 3.2, 4.8, 3.0, 6.0, 9.2, 4.6, 4.2, 5.2, 0.4, 2.6, 1.6, 3.8, 1.4, 3.6, 3.4, 3.2, 5.2, 2.2, 3.8, 5.2, 4.0, 4.0, 4.2, 3.8, 4.6, 2.0, 2.2, 1.0, 3.0, 5.0, 5.2, 2.8, 5.6, 3.8, 5.4, 3.4, 3.2, 5.8, 3.0, 2.2, 2.0, 4.0, 4.8, 1.8, 4.0, 3.2, 4.0, 3.4, 2.4, 3.2, 3.6, 2.2, 4.0, 4.8, 3.4, 3.4, 2.6, 5.6, 5.4, 4.4, 1.0, 5.0, 2.0, 1.8, 3.6, 4.0, 7.2, 2.4, 3.6, 2.6, 2.0, 2.2, 1.0, 2.4, 2.4, 2.6, 0.8, 4.4, 1.8, 1.8, 4.6, 2.4, 3.4, 0.6, 6.2, 4.0, 4.8, 4.0, 5.0, 7.0, 3.8, 3.0, 3.8, 1.2, 2.4, 3.6, 4.0, 3.0, 3.8, 2.6, 5.8, 4.0, 3.4, 3.6, 3.2, 0.4, 1.2, 2.0, 4.0, 4.6, 4.0, 2.0, 1.4, 3.2, 0.6, 2.8, 2.0, 1.8, 3.2, 4.0, 6.2, 6.6, 8.4, 6.4, 3.8, 2.6, 1.6, 2.6, 4.6, 2.6, 1.8, 3.0, 3.4, 5.6, 3.6, 2.8, 3.4, 1.2, 4.8, 4.8, 4.4, 4.6, 2.0, 2.4, 3.2, 0.2, 3.2, 4.6, 3.2, 6.6, 3.8, 3.8, 1.0, 3.2, 5.2, 4.2, 3.0, 3.6, 3.2, 3.6, 2.4, 5.0, 6.8, 5.2, 6.8, 2.4, 2.8, 3.8, 7.0, 5.4, 4.2, 3.6, 4.8, 4.0, 5.4, 6.2, 3.0, 5.0, 5.4, 8.0, 8.0, 12.0, 7.2, 5.8, 3.0, 4.4, 8.8, 8.0, 4.6, 4.8, 4.8, 5.4, 7.8, 8.8, 5.8, 4.8, 4.0, 4.0, 7.6, 2.6, 10.6, 2.6, 5.0, 6.0, 5.8, 6.0, 5.0, 6.6, 7.8, 7.2, 5.8, 15.0, 7.8, 6.6, 6.0, 5.6, 6.2, 6.4, 6.8, 8.0, 4.2, 4.6, 6.8, 4.8, 12.8, 5.0, 7.0, 8.0, 8.0, 6.8, 8.4, 10.0, 6.0, 7.2, 6.6, 7.4, 8.0, 9.8, 8.6, 8.4, 8.0, 11.0, 5.6, 7.8, 8.6, 7.4, 5.0, 3.4, 8.4, 8.0, 8.0, 11.4, 7.6, 6.8, 6.6, 8.4, 7.0, 9.2, 8.2, 5.0, 5.8, 4.0, 10.6, 4.0, 5.4, 8.0, 9.6, 6.8, 9.2, 4.0, 10.2, 10.0, 4.0, 6.6, 9.2, 13.6, 7.4, 7.4, 4.8, 5.4, 6.2, 11.0, 8.2, 3.2, 10.2, 10.4, 3.4, 7.4, 8.4, 8.0, 9.2, 8.0, 10.6, 5.4, 7.2, 2.8, 8.8, 5.8, 9.4, 6.6, 8.6, 6.4, 7.2, 4.2, 5.4, 5.6, 8.0, 5.8, 5.8, 8.0, 7.8, 5.0, 5.6, 8.0, 8.4, 10.4, 9.6, 5.0, 2.8, 3.4, 6.6, 5.2, 6.6, 2.2, 4.6, 5.6, 6.0, 10.6, 5.0, 6.6, 4.8, 8.8, 8.0, 5.8, 4.0, 7.2, 1.2, 6.2, 6.2, 3.4, 5.6, 7.4, 4.8, 5.8, 3.0, 5.2, 7.6, 5.4, 3.4, 6.8, 3.4, 5.8, 7.0, 7.0, 5.0, 4.8, 3.0, 4.2, 4.2, 6.4, 5.4, 2.2, 4.0, 3.2, 5.6, 6.6, 5.2, 1.8, 2.0, 4.0, 4.2, 5.0, 3.2, 4.0, 2.0, 6.6, 3.2, 4.8, 4.8, 4.8, 2.2, 4.4, 4.0, 0.4, 5.6, 4.0, 3.8, 2.2, 2.6, 1.2, 1.8, 1.6, 6.4, 6.6, 5.2, 2.8, 4.8, 5.0, 6.6, 4.6, 4.0, 4.4, 2.8, 3.0, 2.0, 0.4, 1.4, 4.0, 3.4, 5.6, 2.8, 2.6, 2.0, 3.2, 1.4, 2.0, 2.4, 3.4, 0.4, 4.6, 3.2, 1.2, 4.0, 1.8, 2.2, 2.8, 4.0, 3.0, 0.6, 1.4, 2.4, 2.0, 4.0, 4.8, 0.6, 1.0, 4.8, 2.2, 2.2, 0.6, 2.0, 3.0, 2.4, 2.0, 1.8, 2.6, 1.0, 1.2, 0.6, 3.0, 4.0, 0.2, 1.6, 3.2, 3.2, 0.6, 2.0, 1.2, 1.4, 2.8, 4.8, 2.0, 3.4, 3.4, 0.0, 3.0, 2.0, 1.6, 0.8, 4.0, 0.8, 2.0, 2.6, 4.6, 5.0, 4.8, 4.8, 1.0, 4.8, 3.4, 5.4, 5.4, 3.8, 0.6, 3.8, 2.8, 2.6, 1.8, 2.6, 5.0, 3.8, 4.8, 4.0, 3.0, 3.0, 2.8, 4.4, 3.6, 2.6, 3.8, 4.2, 6.4, 1.8, 5.0, 2.8, 3.0, 2.8, 4.2, 3.6, 4.8, 3.2, 4.0, 5.6, 4.0, 2.8, 5.4, 0.6, 6.8, 5.0, 4.8, 4.0, 7.4, 3.8, 5.0, 6.4, 10.2, 4.2, 6.4, 5.4, 4.0, 1.6, 6.2, 8.8, 4.0, 2.8, 4.4, 3.8, 4.2, 5.8, 5.6, 5.6, 4.8, 7.2, 8.0, 11.0, 8.6, 13.2, 6.6, 5.4, 6.8, 5.6, 5.0, 7.8, 1.4, 7.0, 6.8, 9.8, 7.2, 4.2, 6.8, 7.6, 5.0, 2.8, 4.6, 7.4, 7.0, 7.8, 3.8, 5.4, 8.0, 8.0, 7.8, 6.6, 6.8, 1.4, 0.0, 3.2, 5.6, 7.2, 6.4, 6.0, 8.6, 4.8, 8.4, 9.0, 2.2, 4.4, 8.0, 11.0, 10.4, 8.8, 14.6, 6.2, 3.8, 8.0, 12.6, 14.6, 7.4, 6.4, 7.4, 8.0, 14.2, 9.2, 6.4, 9.0, 9.2, 7.6, 4.6, 10.0, 6.4, 12.2, 7.6, 8.0, 10.0, 5.4, 4.8, 13.6, 9.4, 14.0, 4.4, 3.6, 5.0, 7.0, 7.4, 8.8, 5.8, 7.4, 7.4, 8.0, 11.0, 6.8, 8.0, 6.4, 0.0, 8.0, 2.0, 6.6, 7.0, 8.0, 9.0, 10.6, 6.0, 12.2, 6.0, 5.6, 7.0, 8.0, 11.8, 11.6, 10.4, 3.4, 6.6, 4.6, 2.4, 9.8, 5.6, 5.0, 3.0, 5.8, 8.0, 5.0, 7.6, 7.6, 9.6, 8.8, 7.2, 4.6, 9.8, 7.6, 10.4, 6.4, 8.8, 9.6, 8.0, 7.0, 8.8, 8.0, 8.0, 9.4, 8.2, 3.8, 9.4, 11.0, 8.4, 12.2, 6.0, 8.0, 11.2, 4.2, 7.8, 8.2, 9.6, 9.2, 9.8, 8.0, 8.8, 9.2, 8.0, 5.8, 4.6, 9.0, 7.2, 7.0, 6.0, 5.2, 5.6, 5.4, 7.8, 5.8, 2.8, 4.2, 5.2, 6.8, 3.0, 4.0, 5.8, 4.0, 1.4, 6.8, 5.4, 6.8, 6.8, 3.4, 3.0, 6.8, 8.4, 4.0, 1.2, 3.8, 6.4, 5.6, 4.2, 3.4, 3.4, 5.0, 4.6, 3.0, 5.0, 3.4, 3.4, 4.0, 3.4, 2.6, 4.8, 2.8, 2.8, 5.2, 4.8, 3.4, 3.4, 4.8, 3.4, 8.0, 4.0, 3.4, 5.6, 1.4, 1.0, 4.4, 8.0, 6.0, 4.0, 7.2, 2.2, 3.2, 4.8, 6.6, 4.0, 4.0, 3.4, 2.0, 4.0, 7.6, 3.2, 4.6, 4.0, 5.6, 1.6, 2.6, 2.2, 0.6, 2.4, 2.4, 4.8, 4.8, 12.6, 5.2, 1.8, 4.8, 6.2, 3.2, 5.4, 1.0, 2.2, 3.4, 2.2, 3.6, 3.6, 0.8, 2.2, 6.0, 4.4, 5.0, 3.8, 5.4, 3.6, 2.2, 1.4, 4.0, 2.8, 3.6, 3.4, 0.6, 4.4, 6.4, 4.8, 0.6, 1.8, 3.2, 1.2, 8.0, 5.2, 3.0, 1.8, 1.8, 1.2, 3.2, 2.4, 1.8, 0.2, 7.6, 4.0, 4.0, 4.8, 5.4, 4.0, 4.0, 4.2, 2.8, 2.2, 1.0, 2.6, 3.2, 2.6, 0.6, 2.6, 2.0, 4.8, 6.2, 6.4, 3.2, 5.4, 3.2, 4.0, 3.8, 4.6, 4.8, 6.6, 5.2, 3.0, 0.6, 3.2, 5.2, 4.6, 2.8, 3.8, 4.0, 3.2, 4.8, 4.6, 6.2, 2.2, 5.6, 3.4, 5.0, 3.2, 3.8, 5.0, 7.4, 6.2, 4.2, 5.6, 1.8, 6.6, 6.8, 5.4, 6.6, 1.0, 6.4, 4.8, 4.0, 3.0, 4.8, 5.2, 4.2, 6.2, 7.2, 5.4, 7.2, 7.4, 8.0, 9.0, 10.2, 11.0, 7.6, 8.6, 10.0, 7.4, 8.4, 10.2, 6.6, 7.4, 8.2, 5.6, 10.0, 11.8, 3.0, 11.0, 8.0, 7.4, 8.4, 4.8, 5.8, 6.8, 7.8, 8.0, 4.6, 1.6, 7.0, 6.6, 10.6, 7.2, 7.4, 8.4, 13.4, 14.4, 7.6, 11.0, 5.2, 2.8, 7.0, 7.6, 8.0, 15.8, 5.8, 5.2, 7.4, 9.2, 8.6, 6.0, 7.4, 8.0, 6.6, 8.8, 8.0, 9.8, 6.0, 7.8, 6.4, 7.4, 6.0, 11.2, 8.0, 7.6, 7.0, 1.4, 8.0, 13.6, 9.0, 9.0, 10.6, 10.2, 13.4, 8.8, 1.0, 1.4, 10.0, 7.8, 7.0, 10.0, 9.2, 7.6, 9.4, 4.6, 11.2, 11.2, 7.8, 10.4, 9.2, 8.2, 6.8, 3.4, 6.2, 7.8, 6.0, 3.8, 6.6, 10.4, 9.6, 8.2, 7.4, 9.4, 8.6, 10.6, 8.0, 7.2, 10.4, 13.8, 12.6, 5.8, 6.2, 9.1, 9.6, 12.0, 10.2, 2.8, 4.2, 5.4, 11.4, 6.0, 11.8, 9.2, 0.0, 6.6, 4.4, 9.6, 11.8, 8.2, 3.4, 5.2, 10.0, 11.0, 10.4, 7.0, 9.0, 1.2, 8.0, 11.2, 5.4, 6.4, 8.0, 10.4, 7.0, 11.6, 10.6, 4.4, 5.8, 7.6, 5.6, 7.2, 3.6, 5.2, 4.0, 2.4, 4.0, 9.4, 8.8, 5.4, 5.4, 5.0, 7.2, 7.2, 7.6, 4.8, 7.6, 3.0, 2.8, 4.8, 8.4, 5.2, 6.0, 4.8, 7.8, 3.2, 3.0, 5.8, 7.4, 2.4, 7.4, 4.8, 4.8, 4.8, 4.2, 0.4, 5.4, 6.0, 3.4, 5.0, 7.0, 7.8, 3.6, 4.2, 2.4, 4.0, 5.2, 4.4, 3.0, 4.0, 4.6, 3.8, 4.0, 4.2, 3.6, 3.0, 4.4, 7.0, 5.0, 3.6, 3.0, 4.0, 5.0, 5.0, 3.8, 2.4, 4.0, 4.0, 4.8, 9.6, 3.4, 2.0, 2.6, 0.6, 4.0, 1.6, 3.0, 3.4, 3.6, 1.4, 1.0, 4.0, 1.0, 2.4, 3.4, 5.6, 1.8, 2.8, 2.4, 5.2, 3.4, 3.4, 4.8, 3.2, 3.4, 0.6, 2.8, 2.2, 2.6, 1.8, 1.6, 3.6, 1.6, 0.8, 2.2, 1.8, 1.2, 1.6, 1.0, 2.0, 2.2, 2.2, 2.0, 2.0, 2.4, 1.4, 3.4], 'Sunshine': [0.0, 2.7, 0.1, 0.0, 0.0, 8.6, 5.2, 2.1, 3.0, 10.1, 8.0, 6.7, 3.3, 8.7, 8.5, 8.8, 3.2, 4.5, 7.5, 11.1, 6.4, 9.4, 12.2, 12.0, 1.5, 8.4, 3.3, 0.0, 8.9, 11.3, 7.3, 11.2, 11.3, 8.7, 10.4, 4.5, 9.6, 10.2, 10.8, 11.3, 11.1, 10.6, 11.0, 11.3, 10.1, 10.0, 9.7, 6.3, 10.4, 0.0, 0.6, 6.1, 8.0, 2.5, 10.5, 11.0, 8.3, 9.3, 10.9, 10.4, 11.0, 10.5, 9.7, 10.6, 10.7, 6.4, 4.7, 5.1, 5.8, 10.6, 8.9, 7.8, 6.6, 5.2, 1.7, 2.2, 0.8, 0.3, 5.0, 1.3, 4.6, 2.0, 0.7, 2.5, 10.2, 7.6, 8.5, 10.5, 9.8, 2.7, 9.1, 10.5, 10.3, 10.0, 3.1, 9.4, 10.2, 10.1, 9.6, 2.1, 7.3, 4.2, 9.7, 8.7, 6.4, 6.9, 9.4, 9.9, 10.0, 6.1, 7.5, 5.4, 9.1, 6.5, 9.1, 8.7, 3.9, 4.6, 5.6, 9.4, 0.3, 0.1, 0.0, 0.0, 0.0, 1.8, 8.8, 0.5, 1.2, 3.9, 0.0, 6.9, 8.6, 3.4, 0.1, 2.4, 1.3, 4.1, 5.0, 0.6, 9.4, 9.3, 7.0, 9.2, 9.8, 9.7, 9.3, 8.8, 9.8, 9.8, 9.5, 9.7, 9.6, 0.4, 2.5, 7.8, 4.3, 5.5, 4.6, 4.9, 9.8, 8.3, 0.0, 6.1, 9.7, 9.6, 9.0, 8.7, 9.5, 0.0, 9.7, 10.0, 4.0, 1.7, 0.1, 8.6, 7.6, 3.6, 6.9, 9.7, 10.2, 1.8, 10.1, 10.0, 5.9, 8.5, 3.4, 6.0, 5.7, 9.6, 5.9, 10.7, 10.0, 10.5, 10.4, 10.7, 9.2, 10.4, 7.6, 10.8, 7.4, 1.1, 0.0, 5.9, 10.4, 7.1, 9.3, 8.5, 10.1, 6.3, 0.3, 11.3, 11.1, 6.2, 0.7, 0.0, 0.0, 9.4, 9.9, 10.9, 10.7, 10.3, 10.8, 10.6, 2.8, 11.0, 11.3, 4.6, 10.1, 10.4, 10.9, 10.9, 7.5, 3.0, 11.1, 10.9, 11.4, 11.4, 8.4, 7.1, 11.1, 10.6, 10.0, 9.8, 0.0, 0.0, 3.3, 11.7, 10.0, 11.7, 10.7, 7.2, 10.6, 9.2, 2.3, 5.0, 11.4, 11.7, 10.3, 10.8, 5.7, 8.4, 2.3, 5.0, 10.2, 11.5, 8.7, 11.8, 5.7, 0.0, 3.7, 5.0, 2.4, 0.2, 10.3, 6.2, 5.0, 10.3, 4.1, 0.2, 11.0, 8.1, 9.9, 10.7, 11.9, 9.1, 2.4, 4.0, 1.4, 8.3, 1.0, 7.5, 11.8, 9.8, 2.1, 10.5, 9.4, 0.1, 10.5, 0.7, 6.9, 12.3, 10.9, 12.9, 8.0, 2.2, 6.7, 9.8, 4.9, 6.3, 9.9, 5.2, 0.0, 0.0, 7.5, 12.7, 12.1, 13.0, 9.6, 8.4, 12.2, 4.6, 12.0, 12.1, 6.5, 0.0, 7.2, 10.0, 0.7, 12.1, 7.2, 10.9, 13.1, 12.9, 5.9, 0.5, 11.3, 12.2, 11.8, 9.3, 0.0, 5.9, 6.1, 8.7, 11.4, 11.1, 13.0, 9.4, 10.1, 6.5, 12.7, 12.7, 12.4, 7.4, 9.8, 11.9, 11.1, 6.8, 1.2, 1.7, 12.3, 12.5, 13.0, 11.5, 11.1, 9.8, 7.5, 7.1, 12.2, 10.8, 11.8, 12.2, 0.0, 0.0, 1.5, 1.1, 0.0, 0.0, 0.2, 6.4, 0.0, 7.1, 11.4, 9.6, 0.3, 6.3, 5.3, 10.7, 7.0, 6.8, 5.6, 5.6, 10.0, 9.0, 6.9, 0.5, 11.0, 9.8, 9.2, 4.1, 4.4, 6.7, 1.8, 9.8, 2.2, 6.4, 6.6, 10.8, 11.0, 10.1, 9.7, 8.6, 8.7, 8.4, 10.2, 10.8, 8.0, 7.6, 4.8, 10.8, 9.4, 6.7, 0.0, 2.3, 2.4, 7.9, 1.4, 8.0, 6.9, 7.7, 9.3, 8.4, 8.3, 0.8, 0.1, 7.8, 10.0, 9.8, 10.3, 7.9, 8.3, 2.9, 5.0, 7.7, 6.3, 9.0, 10.3, 9.2, 9.9, 10.5, 2.4, 2.7, 10.3, 9.4, 7.0, 10.0, 4.2, 9.7, 10.2, 9.5, 9.8, 3.4, 6.4, 5.5, 9.7, 10.1, 8.7, 7.8, 9.7, 5.2, 4.4, 3.0, 0.2, 0.0, 6.0, 7.4, 2.2, 8.4, 0.1, 7.7, 6.1, 4.0, 2.8, 0.0, 3.4, 0.1, 0.6, 3.5, 9.8, 6.6, 9.0, 6.0, 9.6, 9.8, 9.4, 4.6, 0.3, 8.6, 0.5, 3.3, 3.3, 7.2, 0.6, 1.9, 6.7, 9.5, 6.3, 6.5, 8.8, 0.2, 5.3, 9.8, 2.2, 8.6, 8.4, 9.4, 9.8, 9.8, 6.5, 3.9, 3.2, 4.4, 8.4, 3.6, 2.3, 2.8, 9.7, 6.9, 2.5, 4.5, 9.8, 9.4, 10.0, 10.0, 8.0, 8.1, 9.4, 9.9, 0.3, 9.0, 10.0, 9.1, 9.5, 8.5, 10.2, 10.1, 8.8, 5.1, 9.9, 9.2, 8.9, 9.9, 8.4, 4.1, 2.4, 9.7, 10.2, 9.9, 10.5, 10.2, 10.2, 10.4, 10.4, 4.9, 4.8, 6.3, 10.2, 3.5, 10.5, 10.9, 11.0, 10.2, 5.2, 10.9, 10.9, 10.7, 10.9, 4.7, 6.9, 10.2, 10.0, 2.1, 8.3, 11.2, 10.9, 10.7, 10.9, 10.9, 6.2, 6.9, 0.0, 7.6, 10.2, 9.7, 8.5, 8.1, 8.2, 8.0, 11.3, 11.2, 9.0, 10.8, 7.8, 11.1, 11.0, 10.8, 0.5, 0.0, 0.0, 2.2, 6.4, 8.8, 7.4, 4.7, 6.7, 6.7, 4.7, 11.2, 8.9, 10.0, 12.1, 12.2, 7.9, 12.2, 12.1, 11.6, 1.2, 11.1, 9.2, 1.1, 0.0, 0.0, 9.8, 10.3, 10.1, 6.9, 11.0, 0.0, 1.1, 0.8, 6.2, 0.7, 11.0, 12.8, 12.4, 11.2, 9.7, 12.6, 9.3, 10.3, 5.0, 6.6, 10.6, 7.6, 10.3, 6.0, 0.3, 2.1, 12.2, 8.4, 12.4, 9.5, 12.4, 3.9, 9.6, 11.2, 12.9, 12.5, 6.5, 10.5, 11.1, 8.8, 9.8, 1.2, 12.9, 13.0, 11.1, 0.0, 4.3, 10.6, 11.6, 0.0, 10.0, 0.0, 9.7, 12.0, 0.0, 0.0, 1.4, 11.9, 12.8, 2.0, 1.1, 4.8, 0.0, 2.8, 10.4, 9.5, 0.8, 7.7, 13.2, 12.7, 7.8, 9.4, 8.8, 0.2, 3.0, 4.8, 10.3, 13.0, 13.3, 13.0, 12.8, 9.6, 5.6, 0.1, 2.8, 8.6, 4.6, 1.8, 9.5, 7.0, 9.2, 7.9, 9.8, 7.3, 3.9, 3.0, 0.0, 0.2, 2.3, 9.9, 10.1, 6.9, 9.8, 0.3, 1.4, 9.9, 8.7, 12.8, 12.0, 8.0, 11.8, 11.6, 11.9, 7.4, 1.5, 9.3, 1.6, 11.8, 3.8, 0.0, 1.3, 7.5, 7.9, 1.0, 6.2, 5.0, 6.4, 11.7, 0.3, 9.0, 7.9, 7.1, 6.9, 5.9, 11.0, 11.3, 10.2, 11.2, 11.1, 9.0, 6.3, 10.9, 6.1, 8.7, 8.9, 7.2, 8.2, 0.1, 0.0, 3.1, 10.8, 9.4, 7.2, 6.6, 2.5, 3.6, 1.1, 9.4, 9.9, 7.4, 10.1, 10.6, 10.7, 10.7, 9.3, 1.5, 10.8, 9.6, 9.3, 10.3, 10.6, 10.6, 3.4, 3.8, 10.5, 2.2, 10.6, 10.7, 0.3, 4.6, 8.2, 6.5, 4.2, 5.9, 10.2, 10.1, 10.1, 10.2, 10.2, 9.7, 10.2, 9.4, 10.1, 9.0, 7.7, 0.2, 0.0, 6.1, 6.1, 6.4, 4.8, 0.4, 1.1, 0.1, 0.0, 3.3, 4.6, 0.0, 2.2, 3.9, 3.6, 7.0, 0.8, 0.0, 4.4, 6.5, 3.9, 9.0, 7.2, 7.2, 9.8, 9.6, 9.5, 9.5, 9.3, 9.6, 1.7, 9.8, 4.2, 0.2, 5.2, 2.8, 4.0, 6.8, 9.7, 9.9, 9.3, 8.6, 0.0, 9.8, 8.8, 0.1, 3.5, 2.9, 3.8, 4.8, 1.0, 2.1, 0.0, 8.0, 9.8, 9.4, 9.9, 10.0, 0.8, 8.5, 4.1, 5.0, 5.8, 3.9, 6.2, 3.2, 3.2, 0.8, 0.6, 5.8, 5.8, 10.3, 7.3, 6.6, 10.2, 8.3, 10.3, 10.2, 10.3, 8.9, 0.0, 6.0, 5.9, 10.6, 10.7, 7.3, 10.7, 10.4, 6.6, 10.8, 10.8, 10.9, 9.4, 1.0, 10.3, 10.4, 8.9, 8.4, 10.9, 8.2, 9.7, 3.3, 0.0, 0.0, 0.0, 11.3, 8.4, 10.3, 10.7, 2.4, 5.4, 10.9, 10.0, 6.9, 1.7, 9.6, 11.2, 11.0, 4.1, 9.1, 8.2, 9.5, 1.1, 10.7, 8.0, 10.8, 0.0, 1.2, 2.3, 10.8, 0.2, 9.3, 12.1, 10.9, 11.0, 11.0, 6.9, 0.0, 12.1, 9.6, 8.9, 1.8, 9.9, 5.5, 0.1, 1.7, 11.9, 2.8, 2.7, 2.5, 10.9, 7.9, 7.0, 6.0, 9.3, 10.2, 0.0, 7.9, 4.2, 8.8, 0.4, 11.4, 12.6, 12.1, 9.0, 10.8, 0.0, 0.0, 0.9, 0.0, 5.4, 8.7, 1.6, 11.4, 13.2, 12.2, 2.6, 4.3, 13.4, 13.3, 12.8, 10.7, 3.9, 3.8, 4.1, 5.0, 11.6, 13.5, 12.7, 7.5, 8.0, 12.5, 3.5, 0.3, 2.5, 12.7, 13.1, 11.7, 10.8, 8.6, 0.1, 1.9, 7.2, 12.3, 4.8, 10.3, 7.5, 6.6, 0.8, 5.6, 1.9, 9.8, 1.6, 7.9, 9.6, 7.3, 3.6, 12.3, 12.4, 11.7, 10.2, 7.5, 10.2, 9.3, 6.3, 4.3, 8.2, 12.8, 12.8, 12.3, 11.0, 5.7, 6.8, 12.4, 2.6, 0.0, 3.9, 6.0, 4.7, 8.0, 0.0, 0.0, 0.1, 3.0, 3.9, 8.3, 3.8, 7.8, 9.5, 4.3, 3.2, 7.3, 12.0, 7.6, 11.1, 1.4, 2.4, 1.9, 0.0, 10.5, 9.4, 0.6, 2.9, 10.1, 10.4, 2.3, 0.0, 1.8, 9.8, 10.7, 3.2, 3.4, 7.7, 5.9, 0.9, 0.9, 3.3, 2.6, 10.2, 11.0, 10.8, 8.0, 0.4, 2.5, 3.2, 8.3, 9.2, 0.5, 8.8, 0.5, 0.0, 9.1, 7.4, 8.7, 10.0, 10.1, 6.9, 9.1, 3.9, 10.2, 9.3, 10.0, 9.8, 10.2, 9.9, 9.3, 6.8, 9.4, 9.9, 7.3, 7.6, 3.9, 1.8, 4.1, 7.2, 3.1, 0.0, 0.0, 0.7, 0.7, 7.6, 8.8, 2.5, 9.2, 7.4, 7.3, 9.9, 9.9, 4.6, 6.1, 0.3, 0.0, 0.3, 0.2, 1.3, 9.5, 9.8, 9.7, 9.7, 6.8, 9.2, 9.4, 9.8, 9.5, 9.7, 9.6, 0.7, 2.6, 0.7, 1.9, 9.6, 8.1, 6.9, 9.8, 9.4, 10.0, 9.9, 10.0, 10.0, 10.0, 9.4, 0.0, 9.9, 0.6, 4.4, 0.7, 7.0, 5.1, 1.6, 0.0, 0.0, 2.7, 4.7, 6.0, 8.3, 8.7, 10.2, 10.4, 9.7, 8.7, 9.6, 9.8, 5.2, 10.2, 10.1, 7.7, 4.3, 9.1, 2.8, 9.8, 6.7, 2.7, 7.8, 0.8, 5.1, 8.2, 1.1, 9.7, 0.7, 9.7, 5.8, 6.9, 3.0, 10.3, 10.6, 10.4, 4.0, 8.2, 10.4, 8.4, 9.7, 7.9, 4.2, 9.7, 10.5, 6.1, 10.3, 10.4, 0.9, 1.1, 7.8, 10.2, 10.8, 10.9, 10.9, 9.1, 7.6, 9.6, 10.5, 9.8, 10.0, 11.0, 10.9, 9.5, 0.4, 0.0, 7.2, 9.3, 0.2, 5.1, 8.0, 5.2, 0.2, 7.2, 5.9, 2.9, 0.9, 6.3, 5.0, 6.0, 6.9, 10.3, 7.2, 3.1, 0.0, 7.6, 11.6, 8.9, 8.2, 12.0, 12.4, 12.2, 8.2, 9.5, 12.1, 0.3, 0.0, 4.3, 8.3, 5.1, 8.1, 12.0, 6.7, 11.4, 3.4, 9.3, 12.6, 8.3, 7.0, 7.4, 8.8, 5.0, 11.6, 8.1, 11.7, 1.1, 0.0, 9.6, 12.9, 7.0, 0.4, 0.2, 0.1, 0.0, 0.0, 5.5, 12.5, 12.9, 8.0, 2.2, 8.7, 8.2, 11.3, 3.9, 4.5, 0.5, 3.2, 0.2, 10.9, 3.1, 6.5, 0.0, 6.8, 10.5, 12.2, 6.8, 10.7, 3.1, 1.7, 6.6, 5.5, 2.1, 5.4, 10.9, 12.7, 4.7, 4.7, 12.5, 10.8, 11.7, 5.8, 13.1, 13.2, 12.6, 8.4, 3.9, 3.4, 12.7, 1.0, 12.5, 7.4, 10.9, 13.4, 11.3, 0.2, 1.2, 9.5, 12.3, 9.4, 7.2, 3.0, 8.7, 7.0, 0.2, 0.0, 3.3, 2.5, 3.5, 6.4, 9.4, 2.4, 0.0, 0.0, 0.0, 10.7, 13.0, 7.5, 0.6, 0.4, 8.0, 4.4, 7.9, 8.7, 9.1, 7.2, 10.8, 11.3, 7.6, 8.5, 9.6, 8.6, 9.8, 10.7, 12.2, 12.0, 11.3, 0.9, 6.1, 4.3, 0.0, 2.1, 0.0, 0.0, 7.0, 11.0, 9.4, 7.8, 2.3, 10.7, 10.8, 10.9, 2.3, 11.1, 7.5, 8.5, 10.3, 0.2, 7.2, 5.2, 5.6, 7.0, 0.0, 10.9, 11.1, 5.7, 9.7, 7.6, 0.4, 10.2, 7.2, 10.7, 8.1, 10.6, 8.6, 10.8, 10.4, 10.3, 9.2, 0.5, 10.7, 10.2, 6.1, 10.1, 11.0, 7.9, 4.6, 7.8, 0.0, 0.2, 3.3, 8.5, 5.6, 0.1, 7.6, 10.2, 6.6, 10.3, 5.2, 6.6, 3.5, 9.5, 9.0, 10.3, 10.3, 6.8, 10.3, 0.7, 10.2, 10.2, 10.2, 5.2, 6.8, 10.1, 10.1, 9.9, 9.5, 9.5, 9.7, 9.0, 0.4, 8.5, 10.0, 10.1, 2.4, 4.3, 7.8, 9.2, 9.3, 2.2, 6.6, 2.0, 1.2, 0.0, 0.0, 8.1, 4.0, 5.0, 9.1, 9.6, 9.5, 0.2, 0.0, 5.7, 1.5, 5.6, 3.5, 0.0, 9.7, 9.6, 9.7, 9.6, 1.4, 1.2, 9.6, 9.8, 0.0, 5.7, 4.6, 6.7, 7.3, 5.9, 9.6, 9.5, 6.4, 4.5, 5.8, 0.7, 8.1, 9.6, 2.4, 8.6, 0.2, 6.3, 9.5, 10.0, 9.9, 9.7, 7.9, 5.4, 9.8, 1.4, 6.8, 0.6, 6.5, 3.9, 10.0, 9.7, 7.1, 10.0, 6.3, 8.3, 9.6, 7.7, 10.2, 7.7, 10.2, 10.2, 10.6, 6.6, 3.8, 6.0, 9.2, 8.3, 10.4, 10.0, 10.7, 9.2, 9.1, 6.9, 11.0, 10.7, 10.0, 9.5, 7.6, 9.6, 11.2, 10.8, 9.9, 10.6, 10.7, 8.7, 10.8, 8.7, 10.2, 2.7, 11.3, 10.7, 10.3, 6.0, 7.7, 11.1, 9.4, 4.6, 10.9, 11.1, 11.2, 3.8, 8.3, 6.7, 6.0, 11.5, 9.8, 10.6, 11.3, 11.4, 10.3, 0.0, 11.2, 5.9, 9.0, 3.6, 4.3, 11.0, 8.8, 11.6, 9.6, 11.7, 8.2, 9.8, 11.8, 5.0, 6.6, 10.1, 11.6, 10.5, 3.3, 12.2, 5.3, 9.4, 9.8, 12.0, 5.2, 12.2, 0.0, 9.3, 10.0, 8.9, 0.0, 8.4, 9.8, 7.0, 12.7, 11.3, 9.9, 0.3, 7.2, 0.0, 7.0, 12.2, 6.9, 7.6, 10.6, 0.3, 5.2, 10.8, 12.7, 2.9, 1.0, 0.0, 8.3, 6.7, 10.9, 0.9, 12.4, 13.1, 12.7, 13.1, 9.0, 8.7, 6.1, 1.4, 10.0, 1.5, 0.0, 9.4, 10.8, 11.4, 12.1, 8.4, 2.3, 0.0, 5.3, 7.3, 2.3, 10.5, 12.8, 8.3, 0.0, 0.0, 4.5, 8.5, 12.2, 0.0, 0.1, 6.8, 9.6, 9.1, 7.6, 11.4, 6.1, 6.6, 9.8, 9.3, 7.9, 11.1, 1.3, 2.0, 10.7, 10.8, 10.2, 10.7, 9.9, 8.0, 4.4, 8.5, 10.5, 11.0, 4.3, 10.8, 7.3, 8.3, 10.6, 7.3, 5.8, 10.9, 0.0, 0.4, 4.3, 1.6, 7.0, 8.3, 3.6, 10.4, 10.8, 10.3, 10.7, 10.6, 5.7, 4.4, 7.7, 9.1, 10.5, 1.2, 9.7, 8.1, 10.4, 10.8, 10.1, 10.7, 9.5, 10.1, 9.3, 4.0, 7.4, 7.4, 10.2, 6.2, 9.1, 8.2, 8.8, 5.3, 10.2, 10.0, 4.3, 7.0, 1.8, 6.9, 9.8, 8.3, 10.1, 10.1, 9.1, 8.5, 9.1, 1.3, 0.7, 5.8, 9.4, 10.1, 7.1, 3.2, 4.9, 5.7, 9.1, 3.0, 1.8, 9.7, 9.3, 2.3, 2.3, 1.8, 1.5, 6.9, 3.9, 8.5, 1.0, 8.6, 7.0, 5.0, 9.5, 3.8, 8.0, 0.0, 7.2, 8.1, 0.0, 0.2, 0.1, 0.2, 4.3, 2.4, 0.0, 0.0, 2.2, 9.8, 9.8, 9.5, 9.8, 9.7, 9.8, 9.5, 9.1, 1.0, 2.7, 8.2, 8.4, 5.0, 8.5, 1.7, 3.4, 8.7, 3.9, 1.6, 8.9, 10.1, 9.9, 8.0, 4.8, 8.6, 9.3, 9.9, 6.8, 10.2, 3.4, 8.1, 10.1, 6.8, 10.0, 8.5, 10.0, 8.7, 8.3, 1.3, 6.7, 10.6, 10.4, 5.4, 10.8, 10.7, 10.7, 10.7, 10.5, 10.7, 9.9, 10.8, 10.3, 6.7, 2.5, 10.8, 10.7, 9.6, 9.4, 10.8, 6.7, 10.2, 8.2, 10.1, 11.0, 10.4, 10.1, 10.1, 8.5, 9.1, 1.7, 5.1, 9.7, 6.8, 10.2, 6.1, 8.4, 6.2, 0.0, 5.7, 10.7, 11.2, 10.3, 11.0, 10.5, 10.9, 5.3, 10.7, 11.4, 11.4, 11.5, 10.8, 10.6, 3.0, 11.2, 3.7, 10.6, 9.2, 11.2, 10.4, 11.2, 11.9, 10.0, 10.0, 11.2, 10.8, 6.7, 12.1, 11.7, 5.2, 11.2, 12.1, 10.9, 10.3, 0.6, 11.9, 12.5, 10.4, 11.6, 9.1, 5.7, 5.0, 12.0, 9.8, 7.7, 7.1, 7.4, 11.7, 4.3, 12.2, 11.9, 8.3, 9.5, 0.7, 0.0, 4.9, 13.0, 13.2, 8.0, 5.6, 0.0, 0.0, 10.3, 12.0, 9.8, 2.9, 9.3, 13.0, 10.3, 7.7, 12.6, 11.2, 0.0, 7.3, 7.5, 12.1, 13.3, 7.9, 8.4, 13.6, 12.6, 11.4, 4.1, 12.0, 13.2, 9.7, 13.0, 9.8, 2.0, 6.4, 11.9, 12.9, 12.9, 10.1, 9.9, 6.9, 4.0, 0.0, 0.0, 9.5, 10.5, 12.4, 11.7, 10.2, 10.6, 5.9, 3.5, 5.6, 11.2, 12.2, 12.8, 1.7, 0.4, 2.0, 9.3, 10.9, 10.3, 11.5, 12.0, 12.8, 13.1, 12.8, 13.1, 6.1, 2.8, 0.6, 0.0, 4.6, 1.5, 8.0, 2.3, 12.7, 13.0, 13.0, 13.0, 13.0, 10.6, 12.7, 11.6, 1.2, 3.1, 3.2, 12.3, 12.1, 12.9, 0.2, 4.0, 4.3, 7.5, 0.0, 0.0, 0.0, 8.3, 2.7, 1.8, 11.2, 11.9, 9.2, 10.7, 11.0, 11.8, 6.2, 0.2, 0.0, 0.0, 1.2, 3.8, 3.3, 7.7, 5.8, 7.5, 8.9, 11.1, 11.0, 10.8, 6.2, 6.2, 7.9, 5.8, 5.8, 11.2, 10.4, 10.1, 9.2, 5.2, 9.5, 7.2, 0.0, 6.5, 0.0, 0.0, 0.0, 5.6, 10.1, 10.2, 6.2, 10.9, 8.8, 0.0, 6.4, 1.1, 3.3, 1.2, 4.6, 0.0, 3.7, 0.7, 1.0, 3.3, 3.5, 9.0, 9.0, 10.8, 10.7, 10.4, 9.7, 7.9, 9.0, 9.1, 3.2, 1.2, 0.0, 2.8, 8.5, 7.1, 10.2, 7.3, 1.1, 8.5, 10.4, 8.2, 9.7, 6.2, 3.0, 5.2, 8.3, 8.8, 8.8, 9.5, 10.0, 9.9, 9.1, 2.8, 7.5, 4.7, 9.8, 9.4, 8.0, 7.4, 7.1, 9.4, 3.0, 9.6, 7.7, 5.2, 7.5, 0.4, 5.9, 9.9, 9.6, 0.4, 0.5, 7.8, 6.3, 5.1, 3.6, 5.6, 5.8, 3.3, 3.9, 1.2, 9.7, 9.1, 9.4, 8.5, 6.3, 9.5, 4.4, 1.8, 9.7, 9.7, 9.8, 8.1, 6.9, 9.6, 9.4, 9.3, 9.6, 9.6, 9.9, 9.6, 9.9, 9.2, 9.7, 9.4, 9.8, 9.9, 9.5, 9.6, 5.1, 0.0, 3.9, 9.4, 7.9, 3.2, 1.1, 7.5, 9.6, 6.7, 2.4, 2.6, 4.2, 10.2, 6.7, 5.1, 10.2, 10.1, 10.0, 10.0, 9.5, 10.1, 10.2, 10.1, 6.8, 4.0, 6.8, 3.5, 4.5, 3.9, 10.1, 10.3, 9.3, 0.3, 2.2, 0.0, 3.0, 5.0, 7.1, 10.1, 2.9, 7.3, 8.9, 0.0, 5.3, 8.8, 5.4, 2.7, 9.5, 8.7, 1.5, 7.7, 8.3, 8.7, 2.3, 6.9, 10.5, 10.3, 8.3, 10.9, 1.8, 3.8, 9.5, 10.1, 10.8, 9.7, 11.0, 8.0, 10.6, 10.9, 10.7, 1.2, 8.3, 11.1, 11.2, 10.6, 6.8, 11.3, 11.1, 6.3, 8.5, 10.6, 8.3, 7.7, 3.7, 8.5, 7.9, 11.1, 11.2, 5.0, 3.0, 0.1, 11.7, 8.8, 6.2, 12.0, 4.0, 0.0, 9.2, 10.7, 7.1, 8.4, 11.2, 8.9, 10.4, 11.4, 12.6, 12.9, 6.8, 8.8, 3.8, 9.5, 11.9, 12.3, 10.9, 3.2, 5.1, 6.1, 6.6, 11.2, 2.3, 7.3, 12.6, 11.7, 10.1, 10.6, 11.0, 9.3, 10.6, 6.4, 5.6, 7.3, 8.4, 8.0, 10.7, 7.6, 0.0, 6.9, 6.6, 8.9, 7.5, 2.1, 2.6, 0.7, 9.7, 10.8, 13.0, 8.7, 5.8, 5.6, 10.8, 9.5, 12.6, 8.8, 4.6, 3.3, 5.3, 8.9, 0.0, 2.0, 12.6, 12.7, 8.0, 11.0, 3.6, 12.0, 8.9, 3.4, 11.8, 12.4, 13.0, 8.7, 1.0, 0.0, 3.3, 7.5, 12.7, 11.7, 12.9, 13.4, 11.8, 0.1, 7.3, 10.5, 11.7, 10.5, 9.8, 11.2, 0.0, 0.0, 2.3, 12.2, 11.2, 11.7, 7.0, 8.7, 9.8, 6.6, 0.5, 7.8, 6.9, 12.2, 1.2, 7.7, 11.3, 10.0, 4.6, 6.7, 8.8, 11.1, 12.2, 12.2, 5.1, 1.8, 0.0, 10.7, 5.5, 6.2, 9.1, 4.7, 8.4, 6.0, 7.0, 3.3, 8.0, 7.4, 9.8, 11.3, 7.3, 6.7, 11.0, 0.9, 7.6, 9.8, 0.3, 8.9, 5.1, 6.1, 3.9, 7.8, 10.5, 8.0, 0.9, 1.6, 8.7, 2.2, 9.7, 10.4, 11.2, 10.9, 6.4, 2.7, 3.8, 9.9, 3.9, 0.0, 0.0, 9.7, 5.1, 9.8, 4.6, 6.1, 6.0, 4.6, 8.8, 10.2, 8.5, 8.7, 10.4, 0.0, 5.0, 6.6, 0.0, 0.0, 0.6, 8.6, 8.5, 8.1, 1.3, 10.5, 10.4, 0.9, 3.0, 1.0, 2.3, 0.4, 0.3, 9.8, 10.0, 10.3, 10.3, 10.3, 7.8, 10.2, 10.3, 7.7, 10.1, 7.8, 9.3, 3.0, 0.5, 1.8, 5.8, 5.8, 1.4, 8.6, 8.1, 6.0, 5.9, 8.3, 7.6, 0.6, 1.1, 0.0, 8.6, 9.1, 8.8, 9.0, 6.9, 6.1, 9.5, 8.1, 6.5, 0.0, 0.2, 0.7, 4.5, 8.3, 0.6, 0.3, 0.0, 0.8, 2.5, 8.6, 0.0, 7.7, 8.1, 6.5, 4.2, 7.2, 9.7, 9.5, 5.1, 4.3, 8.7, 8.1, 9.3, 6.8, 9.3, 9.5, 2.7, 6.3, 9.6, 3.2, 9.3, 4.0, 5.5, 8.3, 9.6, 2.6, 1.7, 4.3, 9.0, 4.2, 9.9, 0.9, 2.2, 3.7, 10.1, 9.3, 10.1, 9.6, 8.5, 7.6, 9.5, 9.2, 7.8, 10.1, 4.6, 4.8, 8.5, 10.1, 8.9, 9.5, 10.2, 10.5, 8.7, 10.5, 10.5, 7.3, 9.2, 10.4, 10.4, 6.6, 9.8, 9.4, 9.4, 0.2, 0.6, 4.4, 6.3, 4.3, 9.2, 10.8, 10.8, 10.9, 10.8, 10.4, 8.0, 5.7, 9.3, 1.0, 9.3, 11.0, 10.9, 6.5, 9.1, 10.4, 10.6, 10.7, 11.0, 10.2, 8.2, 7.7, 7.3, 3.4, 10.4, 9.2, 6.5, 6.1, 4.3, 7.7, 6.2, 11.0, 3.4, 6.4, 9.6, 10.5, 11.1, 8.2, 11.4, 11.4, 1.3, 2.2, 8.7, 9.5, 6.4, 9.6, 0.8, 8.3, 12.0, 11.9, 9.7, 3.8, 8.2, 7.7, 3.4, 0.7, 3.4, 12.0, 10.2, 5.2, 2.0, 8.2, 11.4, 9.3, 5.7, 9.0, 9.1, 0.0, 0.0, 0.7, 5.2, 5.3, 4.6, 12.3, 11.3, 0.0, 4.2, 7.4, 0.0, 0.8, 13.0, 12.6, 13.0, 12.5, 12.4, 0.3, 2.7, 11.5, 11.4, 9.6, 7.1, 0.3, 7.1, 11.1, 10.4, 5.3, 8.1, 9.3, 12.7, 7.9, 0.3, 8.6, 6.4, 8.8, 5.8, 6.5, 13.1, 5.7, 1.8, 12.0, 12.3, 13.2, 3.6, 0.0, 4.5, 9.5, 9.6, 6.1, 5.7, 4.8, 12.5, 13.1, 12.7, 12.3, 3.3, 0.0, 0.7, 0.0, 0.0, 7.6, 12.1, 8.6, 12.2, 12.1, 4.4, 11.0, 2.7, 7.2, 11.8, 13.5, 13.0, 10.0, 6.9, 1.4, 9.5, 0.6, 0.0, 8.7, 0.5, 6.7, 8.2, 3.0, 10.0, 7.4, 12.9, 10.7, 0.8, 6.8, 8.1, 10.1, 12.6, 10.3, 12.7, 9.6, 12.0, 12.1, 10.4, 6.9, 10.8, 10.4, 11.7, 11.1, 5.9, 4.8, 11.6, 12.4, 12.3, 12.2, 5.2, 10.0, 10.1, 5.7, 7.7, 10.7, 10.2, 10.1, 10.6, 10.5, 11.8, 10.8, 10.1, 6.5, 2.3, 10.7, 7.7, 4.9, 4.5, 7.6, 7.5, 4.4, 11.0, 3.4, 2.7, 6.9, 9.5, 9.3, 0.3, 10.2, 5.7, 4.1, 0.0, 7.5, 10.6, 10.2, 10.3, 6.7, 0.8, 10.4, 10.6, 0.0, 0.0, 9.5, 9.6, 9.4, 5.7, 8.3, 2.4, 9.9, 9.3, 3.2, 7.6, 6.9, 10.3, 10.5, 7.1, 1.3, 9.9, 10.4, 9.6, 10.7, 7.7, 4.6, 4.5, 4.7, 6.1, 10.4, 10.2, 10.1, 9.9, 8.7, 0.0, 0.0, 9.7, 7.5, 9.1, 10.0, 10.2, 5.2, 9.1, 8.9, 3.0, 9.9, 9.2, 4.4, 9.1, 9.2, 9.9, 8.7, 4.8, 9.9, 2.1, 9.8, 9.5, 1.7, 1.4, 8.7, 1.3, 0.0, 0.0, 2.2, 3.6, 9.3, 6.0, 9.1, 8.7, 8.3, 6.5, 9.6, 8.2, 9.6, 1.4, 3.4, 0.0, 3.5, 5.5, 9.0, 8.2, 6.5, 9.6, 5.2, 0.0, 8.9, 9.6, 9.5, 9.5, 7.5, 5.8, 4.8, 1.6, 0.0, 5.2, 7.3, 0.3, 7.8, 9.8, 9.6, 9.5, 4.7, 3.2, 8.9, 6.2, 0.0, 2.6, 7.4, 10.0, 5.4, 9.9, 9.9, 10.1, 10.1, 10.1, 10.0, 3.2, 0.7, 0.9, 0.2, 2.7, 2.2, 2.6, 10.8, 6.9, 9.2, 10.6, 8.6, 10.6, 10.5, 10.1, 10.5, 10.2, 10.5, 10.0, 10.7, 10.7, 0.2, 6.8, 0.0, 6.7, 7.8, 10.7, 10.7, 6.1, 4.4, 2.3, 9.2, 0.0, 9.1, 10.9, 11.1, 10.8, 8.2, 7.1, 8.9, 9.3, 8.7, 9.7, 1.5, 3.9, 8.1, 8.5, 8.8, 0.0, 10.1, 8.7, 2.9, 4.1, 8.2, 10.1, 2.1, 10.1, 9.7, 11.4, 4.2, 8.6, 10.4, 11.1, 8.3, 11.1, 11.0, 11.1, 9.3, 7.4, 8.4, 6.6, 11.4, 9.3, 7.9, 11.6, 12.2, 11.0, 2.4, 12.2, 11.1, 10.3, 8.4, 4.1, 10.4, 12.4, 12.3, 8.5, 6.2, 0.5, 7.9, 4.6, 12.9, 12.1, 12.8, 12.2, 12.8, 12.4, 12.3, 12.4, 4.1, 2.5, 10.7, 11.1, 9.1, 13.0, 7.0, 9.4, 12.7, 12.8, 12.1, 3.7, 8.5, 6.0, 9.7, 13.1, 13.1, 12.3, 1.7, 8.1, 7.0, 4.4, 8.1, 9.8, 9.7, 9.3, 2.9, 0.0, 9.3, 12.2, 13.4, 9.8, 11.4, 12.4, 11.4, 2.5, 0.0, 0.0, 12.7, 0.7, 7.1, 12.0, 10.4, 3.7, 7.9, 4.3, 12.8, 10.9, 6.0, 9.4, 4.8, 0.5, 4.8, 0.0, 3.5, 8.8, 5.6, 0.5, 4.8, 11.5, 11.7, 9.2, 8.8, 10.9, 7.2, 8.9, 7.1, 6.9, 12.1, 11.9, 11.1, 0.0, 2.6, 9.7, 10.7, 12.1, 2.6, 0.3, 0.4, 6.0, 12.2, 6.8, 12.0, 4.8, 0.0, 6.0, 0.1, 7.2, 7.0, 10.9, 1.3, 5.9, 11.8, 12.0, 11.4, 7.8, 12.8, 1.9, 10.1, 11.1, 6.6, 7.0, 7.9, 12.5, 11.7, 12.2, 11.5, 5.7, 0.0, 5.3, 7.5, 9.2, 2.2, 7.6, 1.4, 0.2, 0.0, 7.7, 3.6, 1.4, 2.7, 7.4, 10.7, 10.6, 6.2, 0.5, 5.5, 1.0, 1.3, 3.6, 5.5, 4.4, 1.5, 4.4, 0.2, 5.5, 4.9, 11.0, 11.0, 0.0, 8.4, 0.0, 9.9, 10.7, 5.8, 1.5, 6.4, 10.2, 8.7, 10.6, 9.8, 9.6, 6.1, 2.1, 2.8, 9.2, 10.8, 9.8, 8.1, 8.9, 9.3, 6.1, 9.9, 7.2, 3.5, 9.5, 10.0, 3.0, 8.2, 10.4, 10.5, 7.8, 9.5, 8.4, 3.4, 3.3, 8.5, 8.4, 10.0, 9.9, 7.5, 10.0, 8.5, 1.7, 7.3, 0.3, 5.5, 9.9, 9.5, 6.4, 0.5, 5.4, 9.2, 6.9, 8.8, 9.0, 9.6, 9.8, 7.0, 8.4, 9.4, 9.7, 7.8, 9.7, 4.8, 2.1, 6.8, 9.4, 7.2, 0.0, 1.3, 4.8, 0.2, 0.2, 7.5, 9.1, 2.9, 6.4, 0.2, 0.2, 6.3, 1.9, 5.8, 7.8, 9.2, 2.7, 9.3, 9.4], 'WindGustDir': ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NNW', 'NNW', 'WNW', 'W', 'ENE', 'ENE', 'NNE', 'NW', 'SSE', 'NE', 'SSE', 'ESE', 'ENE', 'NE', 'NE', 'SSE', 'WSW', 'SE', 'ESE', 'SE', 'ESE', 'NE', 'SW', 'SSE', 'N', 'E', 'NNE', 'SSE', 'ESE', 'SSE', 'NE', 'SSE', 'NE', 'NE', 'NE', 'NE', 'NNE', 'NNE', 'SSW', 'SSW', 'E', 'ENE', 'ENE', 'NE', 'ESE', 'ENE', 'NE', 'N', 'S', 'NE', 'SSW', 'SSW', 'NNE', 'SSE', 'NW', 'W', 'WSW', 'W', 'W', 'SE', 'SSE', 'SE', 'ENE', 'SSE', 'SSE', 'SSE', 'NE', 'E', 'NE', 'NE', 'S', 'SSW', 'SSE', 'S', 'S', 'ESE', 'ENE', 'E', 'E', 'ENE', 'NE', 'ENE', 'NNE', 'NNE', 'SSW', 'S', 'E', 'E', 'E', 'NE', 'ENE', 'NNE', 'SSW', 'S', 'SSE', 'S', 'SE', 'E', 'NNE', 'ENE', 'NNE', 'NE', 'SSW', 'ENE', 'NNW', 'SSE', 'S', 'ESE', 'E', 'NNE', 'SSW', 'S', 'SSE', 'SSE', 'ESE', 'NE', 'NNE', 'S', 'NNE', 'ESE', 'S', 'SSE', 'SSE', 'ENE', 'E', 'ENE', 'SSW', 'N', 'SSE', 'SSE', 'ESE', 'SSE', 'ESE', 'ESE', 'ENE', 'NNE', 'NW', 'SE', 'ESE', 'W', 'W', 'S', 'W', 'ESE', 'S', 'ESE', 'ESE', 'E', 'ENE', 'ENE', 'W', 'WNW', 'W', 'S', 'SSE', 'E', 'NE', 'WSW', 'SSE', 'SSW', 'W', 'S', 'W', 'SSW', 'SSE', 'W', 'SW', 'W', 'SSW', 'W', 'WSW', 'SW', 'WSW', 'WSW', 'W', 'W', 'W', 'N', 'WNW', 'W', 'NNE', 'NW', 'WNW', 'SW', 'SW', 'W', 'SSE', 'S', 'ESE', 'E', 'ESE', 'SE', 'W', 'SSW', 'W', 'WSW', 'W', 'W', 'W', 'SW', 'SE', 'S', 'SSE', 'SSE', 'ESE', 'ESE', 'W', 'W', 'W', 'NW', 'W', 'WSW', 'SW', 'W', 'W', 'W', 'W', 'SSE', 'ESE', 'SSE', 'SSE', 'W', 'N', 'NW', 'W', 'WNW', 'W', 'WSW', 'WSW', 'W', 'SW', 'WSW', 'WSW', 'SW', 'S', 'ENE', 'W', 'SW', 'W', 'S', 'WSW', 'S', 'SSW', 'W', 'NW', 'WSW', 'S', 'W', 'WNW', 'NNE', 'W', 'NNE', 'W', 'W', 'W', 'NNW', 'WSW', 'NW', 'W', 'WSW', 'WSW', 'W', 'SSW', 'W', 'S', 'W', 'ESE', 'NNE', 'NNW', 'SE', 'SSE', 'ESE', 'ESE', 'W', 'ENE', 'E', 'SSE', 'SSE', 'SSW', 'WSW', 'SSE', 'ESE', 'ESE', 'S', 'ENE', 'NNE', 'NNE', 'W', 'W', 'E', 'WSW', 'W', 'SW', 'SW', 'NW', 'S', 'SSE', 'W', 'SSW', 'S', 'NNE', 'W', 'W', 'NNE', 'SSE', 'SSE', 'ESE', 'ESE', 'ENE', 'NNE', 'W', 'W', 'SSW', 'SSE', 'S', 'SSE', 'WNW', 'NNE', 'E', 'ESE', 'WSW', 'E', 'WSW', 'ESE', 'E', 'ENE', 'ENE', 'SSW', 'S', 'E', 'NE', 'NNE', 'SSW', 'SSW', 'ENE', 'NW', 'SSE', 'SSE', 'ESE', 'ENE', 'NNE', 'S', 'SSE', 'S', 'S', 'SE', 'ESE', 'ENE', 'NE', 'E', 'W', 'NNE', 'SSE', 'ENE', 'NNE', 'NE', 'S', 'ESE', 'ENE', 'NNE', 'W', 'NE', 'SSE', 'SE', 'ESE', 'E', 'NE', 'WNW', 'NE', 'NE', 'SW', 'S', 'SSE', 'NNE', 'SSE', 'W', 'ESE', 'ESE', 'SSE', 'ENE', 'E', 'SSE', 'S', 'SSW', 'SE', 'ESE', 'SE', 'ESE', 'NE', 'NNE', 'SW', 'ESE', 'ENE', 'E', 'ENE', 'NE', 'S', 'SSE', 'SSE', 'SSE', 'ESE', 'ENE', 'ENE', 'NE', 'NE', 'S', 'SSE', 'SSW', 'ENE', 'NE', 'S', 'W', 'WSW', 'SW', 'ENE', 'ESE', 'ENE', 'E', 'ENE', 'ENE', 'E', 'SE', 'ESE', 'W', 'ESE', 'NNE', 'E', 'ESE', 'ENE', 'NE', 'NNE', 'SSE', 'SE', 'ESE', 'SSW', 'ESE', 'NE', 'S', 'ESE', 'ESE', 'ENE', 'NE', 'SSW', 'E', 'ENE', 'ESE', 'E', 'NE', 'ENE', 'ESE', 'NNE', 'SSE', 'SSE', 'SE', 'ENE', 'ENE', 'ENE', 'NNE', 'ENE', 'WNW', 'SE', 'SSW', 'SSW', 'ENE', 'NE', 'SSE', 'SSE', 'SSW', 'NW', 'WSW', 'ESE', 'ENE', 'ENE', 'NE', 'E', 'NNE', 'NNE', 'SSW', 'S', 'ESE', 'E', 'NE', 'S', 'W', 'W', 'SE', 'NE', 'N', 'E', 'ENE', 'W', 'E', 'WSW', 'W', 'W', 'ENE', 'ENE', 'ENE', 'SSE', 'W', 'SSE', 'SW', 'SSW', 'W', 'ENE', 'ENE', 'W', 'S', 'ESE', 'NE', 'ENE', 'W', 'SSW', 'NW', 'NW', 'W', 'W', 'W', 'N', 'S', 'W', 'ENE', 'W', 'WSW', 'W', 'SSW', 'W', 'SSW', 'W', 'W', 'W', 'W', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'NW', 'W', 'WNW', 'W', 'SW', 'SSW', 'SSW', 'W', 'ENE', 'NNE', 'SSW', 'SSE', 'W', 'SSE', 'S', 'WSW', 'W', 'W', 'SE', 'SE', 'SE', 'SW', 'WNW', 'N', 'W', 'W', 'WSW', 'WSW', 'W', 'N', 'NW', 'WSW', 'W', 'S', 'SSE', 'W', 'NNE', 'NNW', 'WSW', 'W', 'W', 'W', 'SSW', 'SSW', 'W', 'W', 'ENE', 'NE', 'W', 'NNW', 'N', 'NW', 'WSW', 'W', 'N', 'WSW', 'S', 'SSW', 'SSW', 'SE', 'W', 'N', 'NNW', 'W', 'WSW', 'S', 'SSW', 'SW', 'SSW', 'W', 'WNW', 'W', 'WSW', 'SSW', 'W', 'W', 'W', 'S', 'WNW', 'W', 'W', 'W', 'WSW', 'W', 'NNE', 'W', 'NW', 'W', 'W', 'W', 'NW', 'SSW', 'S', 'W', 'WNW', 'W', 'NNW', 'NW', 'W', 'W', 'S', 'NE', 'SSW', 'WSW', 'SSE', 'NNE', 'SSE', 'E', 'W', 'ENE', 'WSW', 'ESE', 'SSW', 'W', 'ESE', 'ENE', 'NNE', 'NNW', 'W', 'SSE', 'W', 'NNE', 'WNW', 'W', 'NE', 'SSW', 'SSE', 'S', 'WSW', 'SSW', 'SE', 'ESE', 'NNE', 'NNE', 'SSW', 'ENE', 'NE', 'SSE', 'S', 'SSE', 'SSE', 'NE', 'NE', 'S', 'SSE', 'SSE', 'ENE', 'NE', 'ENE', 'W', 'SSE', 'SE', 'NE', 'NNE', 'NE', 'NE', 'ESE', 'S', 'SSE', 'ESE', 'NE', 'S', 'E', 'ENE', 'SSW', 'SE', 'S', 'S', 'SSE', 'NNE', 'SSW', 'SSE', 'ENE', 'ENE', 'WSW', 'NE', 'E', 'NE', 'E', 'E', 'S', 'E', 'NNE', 'NE', 'E', 'NNE', 'NNW', 'SSE', 'ENE', 'NE', 'SSE', 'SSW', 'S', 'NE', 'E', 'ENE', 'S', 'SSE', 'SSE', 'ENE', 'S', 'S', 'SSW', 'ENE', 'NE', 'W', 'NE', 'E', 'ESE', 'NE', 'SSE', 'SSE', 'SE', 'ESE', 'ENE', 'ENE', 'NE', 'E', 'ENE', 'ENE', 'ENE', 'E', 'NE', 'SSW', 'SSW', 'E', 'SSW', 'SSW', 'ESE', 'NE', 'NNE', 'NW', 'ESE', 'E', 'S', 'ENE', 'NNE', 'W', 'SSE', 'NE', 'SSE', 'W', 'SW', 'S', 'SSW', 'W', 'NE', 'W', 'ESE', 'WNW', 'ENE', 'NE', 'ENE', 'NE', 'W', 'S', 'SSW', 'SSE', 'S', 'SW', 'SE', 'W', 'WSW', 'WSW', 'W', 'W', 'W', 'ENE', 'WNW', 'WNW', 'SSW', 'S', 'S', 'N', 'SSE', 'SSE', 'SSW', 'ESE', 'WNW', 'W', 'W', 'ENE', 'ENE', 'NNW', 'W', 'W', 'W', 'WSW', 'WSW', 'W', 'W', 'W', 'WNW', 'SSE', 'SE', 'W', 'W', 'SSW', 'ENE', 'W', 'E', 'W', 'NW', 'S', 'W', 'W', 'W', 'NNW', 'SSE', 'SSE', 'ENE', 'NNW', 'W', 'W', 'NW', 'W', 'WSW', 'W', 'S', 'S', 'S', 'SSW', 'W', 'SE', 'SSE', 'W', 'SSE', 'SSE', 'WNW', 'ESE', 'E', 'SE', 'W', 'W', 'W', 'NW', 'W', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'NNW', 'NW', 'NE', 'NNE', 'NNW', 'NNW', 'NW', 'WNW', 'WSW', 'SSW', 'WNW', 'WNW', 'W', 'NNE', 'NNW', 'SSW', 'S', 'W', 'W', 'NW', 'WSW', 'WNW', 'NNW', 'WSW', 'SSW', 'W', 'W', 'WSW', 'W', 'W', 'NNW', 'W', 'NE', 'WNW', 'WNW', 'W', 'WSW', 'W', 'W', 'WNW', 'W', 'SW', 'W', 'W', 'SSE', 'NNE', 'N', 'W', 'ENE', 'NE', 'ENE', 'NE', 'W', 'WNW', 'SSE', 'SSE', 'NNW', 'NNW', 'WNW', 'S', 'SSW', 'ENE', 'WSW', 'ENE', 'WNW', 'W', 'WNW', 'WSW', 'W', 'E', 'ENE', 'WSW', 'NNE', 'W', 'W', 'W', 'W', 'NNE', 'NW', 'NNW', 'WSW', 'WSW', 'E', 'SSW', 'SE', 'SSE', 'ENE', 'S', 'SSE', 'ENE', 'WNW', 'WSW', 'E', 'NE', 'NW', 'SW', 'ENE', 'NNE', 'NNE', 'SW', 'NW', 'W', 'E', 'WSW', 'ESE', 'ENE', 'S', 'W', 'W', 'W', 'W', 'W', 'W', 'ESE', 'ENE', 'NNE', 'W', 'SSE', 'SE', 'SE', 'ENE', 'ENE', 'ENE', 'ESE', 'SSE', 'SSE', 'S', 'S', 'E', 'ENE', 'NE', 'NE', 'SE', 'SSW', 'SSE', 'E', 'NNE', 'S', 'SW', 'ESE', 'ENE', 'ENE', 'NNE', 'W', 'WSW', 'NNE', 'NE', 'N', 'W', 'ENE', 'NE', 'ENE', 'SSE', 'ESE', 'ENE', 'NE', 'ENE', 'NNE', 'ENE', 'SSE', 'NNE', 'S', 'SSE', 'ENE', 'SW', 'ENE', 'NNE', 'SSE', 'ENE', 'ESE', 'W', 'WSW', 'ENE', 'S', 'NNE', 'W', 'SSE', 'SE', 'E', 'ENE', 'ENE', 'ESE', 'ESE', 'ENE', 'NE', 'ENE', 'NE', 'NE', 'SSE', 'S', 'E', 'SSE', 'E', 'NNE', 'SE', 'SSE', 'NE', 'NE', 'NE', 'NE', 'NE', 'SSE', 'NE', 'NE', 'SSE', 'SSE', 'E', 'ENE', 'NE', 'NE', 'SSE', 'SSE', 'ESE', 'ENE', 'ENE', 'NE', 'SSE', 'SSW', 'E', 'NNE', 'WSW', 'ESE', 'ESE', 'SE', 'ENE', 'NE', 'SSE', 'S', 'SE', 'NNE', 'ESE', 'ESE', 'ENE', 'S', 'SSW', 'NNE', 'ESE', 'E', 'ENE', 'NE', 'SE', 'S', 'NNE', 'WSW', 'W', 'NNE', 'NE', 'S', 'E', 'NE', 'SSW', 'NNW', 'W', 'ESE', 'NE', 'N', 'WSW', 'SSE', 'SE', 'W', 'NNE', 'E', 'SSW', 'S', 'SSW', 'SSW', 'SSE', 'W', 'ENE', 'W', 'NW', 'SSW', 'SSE', 'SSW', 'SSE', 'SW', 'SSE', 'WSW', 'SSE', 'WSW', 'W', 'W', 'W', 'SE', 'SSE', 'S', 'SSW', 'W', 'NNW', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'S', 'SSW', 'W', 'NW', 'SSE', 'SSE', 'W', 'ENE', 'WNW', 'W', 'NNE', 'W', 'WNW', 'W', 'W', 'W', 'W', 'WSW', 'W', 'NNE', 'N', 'NW', 'S', 'SSW', 'NNE', 'W', 'W', 'W', 'W', 'SSE', 'S', 'SSW', 'SSE', 'SSE', 'SSE', 'W', 'W', 'N', 'W', 'W', 'SW', 'WSW', 'W', 'W', 'WSW', 'W', 'W', 'N', 'WNW', 'W', 'WNW', 'N', 'W', 'NW', 'WSW', 'W', 'W', 'W', 'NW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'S', 'W', 'W', 'W', 'W', 'WSW', 'SW', 'SSW', 'W', 'W', 'W', 'N', 'W', 'W', 'W', 'WSW', 'NNW', 'NW', 'NNW', 'W', 'W', 'W', 'E', 'SSE', 'W', 'W', 'WNW', 'NE', 'SW', 'SSE', 'S', 'SSW', 'SSE', 'WNW', 'ESE', 'ESE', 'SSE', 'SSE', 'SW', 'SE', 'SSE', 'ESE', 'W', 'ESE', 'ESE', 'SSE', 'SSE', 'SSW', 'SSW', 'W', 'NE', 'W', 'SW', 'S', 'SSW', 'ESE', 'ESE', 'NE', 'NNE', 'W', 'SSW', 'S', 'E', 'SSE', 'ENE', 'WSW', 'ESE', 'S', 'ESE', 'E', 'NE', 'NNE', 'WSW', 'SSE', 'ESE', 'NNE', 'NNW', 'NW', 'WSW', 'WNW', 'ESE', 'ENE', 'SSW', 'NE', 'NW', 'SSW', 'ENE', 'NE', 'NNE', 'NNE', 'WNW', 'S', 'SW', 'ENE', 'SSE', 'ENE', 'NNE', 'SSE', 'ENE', 'NNE', 'E', 'NNE', 'SSE', 'S', 'WNW', 'W', 'ENE', 'E', 'W', 'ESE', 'ENE', 'NNE', 'SSW', 'E', 'ENE', 'S', 'ESE', 'ESE', 'ENE', 'NE', 'SSW', 'SE', 'W', 'E', 'SSE', 'ENE', 'ENE', 'SSE', 'SSE', 'SE', 'E', 'SW', 'ENE', 'NNE', 'NNE', 'SE', 'S', 'W', 'WNW', 'ENE', 'WNW', 'W', 'S', 'E', 'SSW', 'ESE', 'NNE', 'NE', 'NE', 'W', 'E', 'SSW', 'ENE', 'ENE', 'NE', 'NE', 'SSW', 'WSW', 'SSE', 'ENE', 'ENE', 'NNE', 'SSW', 'SSW', 'ENE', 'S', 'NE', 'SSW', 'S', 'E', 'NNE', 'W', 'NE', 'W', 'S', 'S', 'NNE', 'WSW', 'W', 'ENE', 'WNW', 'ESE', 'SE', 'ENE', 'E', 'ENE', 'NNE', 'NE', 'S', 'SSE', 'ESE', 'S', 'S', 'WSW', 'ESE', 'SE', 'SSE', 'SSE', 'SSE', 'ESE', 'ESE', 'ENE', 'E', 'S', 'ENE', 'ENE', 'ESE', 'ENE', 'ENE', 'NE', 'NE', 'NE', 'E', 'ENE', 'NE', 'ENE', 'E', 'ENE', 'SSE', 'SE', 'E', 'SE', 'NNE', 'SSE', 'SSE', 'ENE', 'SSW', 'SSE', 'WSW', 'ENE', 'SSE', 'ENE', 'SSW', 'WNW', 'SE', 'SSE', 'NE', 'SSE', 'SSE', 'N', 'SSE', 'SSW', 'SSE', 'SSE', 'ESE', 'NNE', 'SW', 'SSW', 'WSW', 'WSW', 'W', 'ENE', 'NW', 'ESE', 'NNE', 'S', 'S', 'ESE', 'W', 'N', 'NW', 'WSW', 'S', 'S', 'W', 'SSW', 'SSE', 'ENE', 'W', 'SSE', 'SSE', 'NW', 'S', 'SSE', 'SSE', 'S', 'SSE', 'W', 'SSE', 'SW', 'S', 'SSE', 'SSE', 'SSE', 'E', 'ESE', 'SSW', 'S', 'W', 'W', 'W', 'W', 'WNW', 'NW', 'WNW', 'W', 'W', 'W', 'S', 'S', 'W', 'W', 'NNW', 'NW', 'S', 'S', 'SSW', 'W', 'W', 'WNW', 'W', 'NNW', 'NW', 'W', 'W', 'WSW', 'WSW', 'W', 'W', 'W', 'W', 'NW', 'WNW', 'NNW', 'SSE', 'W', 'W', 'NNW', 'WSW', 'NE', 'WNW', 'NW', 'W', 'W', 'W', 'W', 'W', 'NNW', 'W', 'SSE', 'W', 'W', 'W', 'W', 'W', 'W', 'WSW', 'W', 'W', 'W', 'W', 'SSW', 'SSE', 'W', 'W', 'WNW', 'WNW', 'WSW', 'WSW', 'WNW', 'NW', 'SSW', 'SSW', 'W', 'W', 'NNE', 'N', 'W', 'NNW', 'NNW', 'NW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'WNW', 'WSW', 'WSW', 'W', 'WSW', 'WNW', 'SSW', 'W', 'NNE', 'W', 'NW', 'WSW', 'WSW', 'W', 'NW', 'WSW', 'SW', 'WNW', 'NE', 'NNE', 'NNW', 'NNW', 'E', 'NW', 'SSW', 'W', 'WSW', 'WSW', 'SSW', 'SSE', 'W', 'WNW', 'SW', 'S', 'ESE', 'ENE', 'W', 'W', 'W', 'SSW', 'NNE', 'ENE', 'NNE', 'NE', 'W', 'ESE', 'S', 'S', 'E', 'ENE', 'SSW', 'SSW', 'S', 'S', 'S', 'S', 'SW', 'W', 'NW', 'SSE', 'ENE', 'SSE', 'E', 'WSW', 'S', 'NNE', 'SSW', 'ENE', 'ENE', 'E', 'W', 'SSE', 'SSW', 'NE', 'NE', 'NNE', 'SSE', 'SSE', 'NE', 'W', 'NNE', 'S', 'SSW', 'ENE', 'NE', 'WSW', 'S', 'SSE', 'E', 'ENE', 'NE', 'NE', 'WSW', 'S', 'E', 'ENE', 'S', 'SSE', 'SSW', 'E', 'ENE', 'SSW', 'NNE', 'SSW', 'SSE', 'SSW', 'ESE', 'NNE', 'SSW', 'SSW', 'W', 'S', 'NNE', 'SSE', 'NE', 'W', 'ENE', 'ENE', 'ENE', 'S', 'S', 'SSE', 'ESE', 'E', 'ENE', 'E', 'NE', 'S', 'SSW', 'W', 'ESE', 'NE', 'ENE', 'ENE', 'SSE', 'E', 'NNE', 'NE', 'SSE', 'ESE', 'ESE', 'E', 'ENE', 'NE', 'S', 'SSW', 'SSE', 'ESE', 'W', 'E', 'ESE', 'SE', 'ESE', 'ESE', 'SE', 'W', 'W', 'ENE', 'ENE', 'E', 'S', 'NE', 'S', 'SE', 'SE', 'NNE', 'NNE', 'NNE', 'SW', 'NE', 'W', 'SSE', 'W', 'W', 'NE', 'NNE', 'NW', 'ESE', 'WNW', 'SSE', 'SE', 'SSE', 'S', 'SSE', 'SSE', 'ESE', 'E', 'SSE', 'NE', 'E', 'ENE', 'NNE', 'SSE', 'SW', 'SSE', 'SSE', 'E', 'ENE', 'S', 'E', 'ENE', 'NNE', 'NNE', 'NNE', 'S', 'ESE', 'E', 'ESE', 'ENE', 'NNE', 'NE', 'NE', 'NE', 'NE', 'ENE', 'ENE', 'NNE', 'SE', 'ENE', 'NE', 'ENE', 'SSW', 'SSW', 'ESE', 'W', 'SSW', 'W', 'S', 'S', 'S', 'W', 'ENE', 'S', 'ENE', 'ESE', 'SSW', 'SSW', 'WNW', 'SSE', 'NE', 'SSE', 'SSE', 'ENE', 'W', 'NE', 'SSE', 'ENE', 'ESE', 'W', 'WSW', 'S', 'ESE', 'ENE', 'NE', 'SSE', 'SSW', 'SSE', 'W', 'E', 'ENE', 'SSW', 'SSW', 'SSE', 'W', 'W', 'NE', 'E', 'NE', 'N', 'NNW', 'W', 'NW', 'NNW', 'W', 'W', 'W', 'WNW', 'NW', 'NW', 'W', 'W', 'WSW', 'W', 'W', 'ENE', 'WSW', 'WSW', 'W', 'W', 'W', 'NNE', 'WSW', 'W', 'W', 'NW', 'W', 'W', 'W', 'W', 'SE', 'W', 'W', 'WSW', 'ENE', 'ENE', 'W', 'WNW', 'WNW', 'NW', 'W', 'WSW', 'SW', 'W', 'W', 'WNW', 'NNW', 'NNW', 'SSW', 'NNE', 'NNW', 'NW', 'W', 'NNW', 'W', 'W', 'W', 'W', 'WSW', 'W', 'W', 'W', 'W', 'NW', 'W', 'S', 'W', 'SW', 'W', 'NW', 'NW', 'W', 'WSW', 'W', 'W', 'WNW', 'WNW', 'NW', 'SW', 'W', 'NNW', 'WNW', 'WSW', 'W', 'WNW', 'W', 'WSW', 'WSW', 'W', 'W', 'W', 'SE', 'S', 'SW', 'SSE', 'W', 'W', 'NNE', 'NW', 'W', 'NW', 'W', 'W', 'NE', 'ENE', 'ENE', 'N', 'NNE', 'WSW', 'W', 'W', 'SSE', 'S', 'W', 'W', 'W', 'W', 'W', 'NNE', 'NNW', 'NE', 'NE', 'WNW', 'WSW', 'ENE', 'E', 'NE', 'NE', 'NNE', 'NNE', 'W', 'W', 'SSW', 'NNW', 'W', 'W', 'NNE', 'WSW', 'W', 'WSW', 'N', 'WSW', 'SSW', 'W', 'WSW', 'WSW', 'WSW', 'W', 'NW', 'NNW', 'W', 'NE', 'WSW', 'W', 'SW', 'WSW', 'WNW', 'SSE', 'NE', 'W', 'WSW', 'WSW', 'SSW', 'W', 'NNE', 'NNE', 'W', 'W', 'W', 'NNE', 'NNE', 'WSW', 'SSW', 'ESE', 'ENE', 'ENE', 'SE', 'SSE', 'NE', 'NW', 'NNW', 'W', 'W', 'E', 'NE', 'W', 'W', 'NE', 'S', 'SSW', 'E', 'E', 'N', 'W', 'WSW', 'S', 'ESE', 'NNE', 'NNE', 'SSE', 'E', 'E', 'NE', 'SSE', 'ESE', 'NE', 'SE', 'NE', 'SE', 'NE', 'ENE', 'SSW', 'S', 'NE', 'SSW', 'S', 'SSW', 'NNE', 'W', 'E', 'E', 'NE', 'NNE', 'WSW', 'SSE', 'ESE', 'S', 'SSE', 'NE', 'SSW', 'S', 'ENE', 'ENE', 'NNW', 'NE', 'NE', 'NE', 'NNE', 'E', 'NNE', 'SE', 'E', 'S', 'SSE', 'ESE', 'ENE', 'E', 'NE', 'NE', 'ENE', 'E', 'SSE', 'E', 'SSW', 'ESE', 'ESE', 'NE', 'NNE', 'SSE', 'ENE', 'SSW', 'SSE', 'ENE', 'NE', 'SSW', 'SSE', 'SSE', 'S', 'NE', 'S', 'NNE', 'SSE', 'SSW', 'S', 'NNE', 'NNE', 'NW', 'S', 'W', 'ESE', 'NNE', 'SSE', 'SSW', 'SSE', 'SW', 'SSE', 'ENE', 'NNE', 'N', 'SE', 'S', 'WSW', 'NNE', 'NE', 'NNE', 'S', 'SSW', 'S', 'ESE', 'ESE', 'E', 'E', 'SE', 'SSE', 'SW', 'SSW', 'SSE', 'SE', 'SSE', 'SSE', 'SSE', 'NNE', 'E', 'E', 'E', 'ENE', 'S', 'SSE', 'ESE', 'NNE', 'NNE', 'WSW', 'SSW', 'S', 'ENE', 'ENE', 'NNE', 'SSW', 'E', 'SSW', 'SW', 'SSE', 'SSE', 'SSE', 'SE', 'ESE', 'ESE', 'ENE', 'ENE', 'WNW', 'W', 'SSW', 'SSW', 'SSE', 'W', 'W', 'WSW', 'W', 'ESE', 'SE', 'E', 'ENE', 'N', 'E', 'NNE', 'NW', 'S', 'SW', 'W', 'SSE', 'NNW', 'SSW', 'S', 'W', 'E', 'NNW', 'W', 'SSW', 'SSE', 'W', 'W', 'WNW', 'ENE', 'ESE', 'SSW', 'W', 'W', 'E', 'NNE', 'NE', 'W', 'W', 'ENE', 'WSW', 'WSW', 'W', 'W', 'NNW', 'W', 'WSW', 'SSW', 'WSW', 'SSW', 'S', 'W', 'W', 'WSW', 'SSW', 'SE', 'ESE', 'SSE', 'WNW', 'SSE', 'SSE', 'WNW', 'W', 'WNW', 'SSW', 'S', 'SSW', 'W', 'SSE', 'W', 'W', 'W', 'W'], 'WindGustSpeed': [41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 76, 85, 41, 37, 41, 41, 52, 48, 33, 54, 33, 31, 56, 50, 48, 54, 44, 48, 46, 37, 37, 74, 37, 52, 30, 50, 30, 35, 28, 35, 67, 44, 56, 44, 37, 63, 44, 56, 44, 43, 44, 43, 31, 28, 43, 63, 31, 46, 39, 46, 44, 43, 52, 41, 57, 65, 72, 52, 41, 59, 44, 43, 76, 57, 39, 48, 30, 46, 39, 52, 50, 35, 26, 41, 33, 31, 44, 48, 44, 54, 44, 54, 37, 30, 52, 31, 44, 39, 41, 31, 50, 69, 50, 46, 43, 41, 39, 43, 33, 37, 35, 70, 43, 56, 67, 35, 30, 33, 41, 39, 52, 54, 41, 31, 28, 31, 43, 44, 28, 65, 50, 33, 35, 30, 41, 37, 46, 54, 43, 33, 46, 43, 35, 33, 48, 24, 24, 22, 41, 41, 59, 28, 33, 31, 39, 46, 59, 57, 24, 39, 57, 46, 56, 41, 33, 43, 41, 43, 28, 31, 41, 41, 50, 33, 35, 31, 41, 44, 56, 43, 41, 52, 41, 30, 30, 28, 26, 20, 22, 26, 52, 39, 69, 39, 31, 37, 31, 94, 70, 54, 37, 28, 26, 39, 48, 39, 67, 54, 56, 54, 57, 50, 67, 69, 54, 70, 54, 30, 35, 78, 54, 50, 26, 26, 22, 33, 43, 43, 30, 33, 24, 39, 50, 65, 52, 70, 50, 52, 80, 46, 48, 48, 44, 39, 26, 17, 39, 56, 70, 56, 46, 41, 33, 33, 35, 39, 28, 22, 24, 28, 26, 24, 26, 41, 33, 37, 35, 33, 33, 39, 33, 41, 28, 24, 26, 24, 52, 50, 78, 56, 46, 44, 41, 28, 30, 30, 28, 35, 31, 31, 24, 30, 37, 37, 39, 37, 56, 43, 24, 46, 57, 50, 46, 35, 59, 37, 41, 31, 59, 56, 78, 41, 44, 70, 39, 61, 44, 41, 31, 72, 63, 48, 67, 50, 35, 24, 22, 24, 31, 54, 30, 56, 41, 33, 35, 39, 37, 43, 28, 35, 48, 33, 31, 30, 44, 59, 41, 39, 43, 35, 59, 48, 28, 43, 39, 30, 43, 31, 28, 63, 43, 52, 39, 35, 46, 65, 22, 30, 48, 74, 31, 41, 48, 43, 52, 59, 54, 46, 65, 54, 57, 52, 39, 63, 41, 30, 35, 22, 28, 24, 37, 46, 48, 46, 31, 30, 26, 44, 46, 37, 33, 20, 31, 33, 52, 59, 50, 50, 43, 37, 28, 41, 43, 44, 67, 44, 56, 43, 43, 41, 35, 70, 43, 43, 39, 56, 39, 35, 33, 28, 31, 44, 41, 35, 35, 26, 46, 31, 50, 56, 44, 48, 39, 35, 24, 41, 59, 39, 30, 43, 46, 46, 31, 31, 31, 28, 41, 39, 31, 39, 33, 57, 33, 31, 33, 43, 44, 37, 31, 52, 67, 65, 48, 41, 39, 44, 54, 54, 48, 43, 30, 43, 37, 39, 44, 43, 50, 57, 43, 31, 37, 63, 57, 44, 28, 37, 33, 31, 26, 22, 22, 39, 20, 24, 31, 28, 33, 57, 44, 61, 65, 54, 41, 28, 30, 22, 35, 56, 54, 31, 41, 26, 33, 74, 65, 37, 22, 24, 56, 30, 31, 31, 26, 31, 48, 37, 30, 30, 22, 28, 28, 54, 70, 43, 35, 31, 26, 22, 30, 30, 26, 33, 24, 37, 59, 61, 41, 41, 30, 26, 28, 24, 24, 24, 35, 76, 72, 39, 31, 31, 30, 41, 50, 30, 22, 24, 26, 50, 30, 54, 26, 35, 61, 43, 37, 37, 28, 26, 24, 30, 44, 52, 41, 41, 44, 44, 31, 26, 24, 44, 31, 31, 39, 39, 46, 43, 35, 31, 50, 35, 52, 48, 26, 30, 31, 41, 44, 39, 54, 44, 43, 44, 31, 35, 44, 46, 33, 30, 63, 93, 30, 35, 76, 61, 37, 24, 31, 41, 91, 67, 41, 33, 54, 59, 61, 31, 28, 28, 57, 54, 72, 59, 39, 43, 63, 37, 37, 41, 39, 37, 35, 30, 37, 33, 39, 48, 33, 44, 46, 65, 48, 30, 26, 31, 37, 57, 48, 57, 35, 33, 50, 74, 35, 28, 46, 43, 39, 41, 31, 56, 46, 80, 41, 46, 30, 56, 41, 30, 44, 43, 33, 52, 54, 31, 41, 52, 57, 35, 35, 50, 50, 31, 54, 57, 31, 35, 41, 33, 70, 50, 44, 50, 72, 30, 39, 26, 41, 44, 26, 43, 44, 30, 52, 30, 52, 52, 33, 46, 69, 50, 37, 43, 56, 56, 59, 41, 31, 41, 78, 50, 28, 37, 52, 56, 33, 44, 57, 50, 69, 70, 28, 54, 63, 57, 56, 39, 35, 39, 39, 31, 39, 35, 35, 30, 46, 43, 43, 31, 65, 41, 28, 37, 54, 59, 30, 28, 30, 39, 48, 37, 44, 35, 44, 26, 39, 48, 31, 24, 31, 22, 26, 24, 30, 26, 31, 35, 24, 37, 41, 30, 41, 65, 65, 33, 41, 43, 35, 33, 41, 26, 28, 26, 35, 37, 46, 31, 56, 37, 35, 31, 22, 24, 26, 31, 28, 28, 41, 46, 50, 57, 41, 39, 44, 54, 31, 48, 48, 41, 30, 41, 30, 20, 24, 41, 52, 81, 41, 41, 26, 26, 41, 43, 26, 28, 30, 41, 48, 46, 43, 41, 44, 43, 52, 39, 31, 39, 41, 39, 41, 52, 26, 41, 28, 37, 26, 33, 26, 43, 65, 37, 35, 33, 30, 24, 30, 30, 26, 24, 33, 26, 22, 30, 57, 48, 54, 54, 44, 48, 33, 22, 28, 26, 37, 48, 43, 30, 31, 37, 44, 50, 52, 35, 57, 35, 31, 31, 94, 35, 39, 57, 41, 57, 39, 59, 56, 50, 50, 56, 35, 35, 33, 24, 39, 56, 39, 30, 26, 28, 31, 41, 28, 24, 39, 41, 33, 74, 43, 74, 41, 54, 33, 80, 57, 48, 63, 69, 37, 28, 24, 39, 43, 41, 46, 76, 41, 35, 85, 48, 65, 39, 28, 33, 52, 44, 30, 74, 61, 31, 80, 44, 33, 48, 80, 41, 37, 48, 37, 50, 63, 70, 35, 44, 37, 61, 93, 41, 41, 41, 41, 41, 41, 33, 43, 48, 63, 48, 50, 54, 28, 37, 33, 69, 50, 50, 59, 39, 33, 52, 69, 31, 41, 61, 41, 30, 46, 59, 44, 35, 37, 48, 54, 78, 59, 30, 46, 56, 54, 31, 46, 46, 50, 30, 35, 44, 33, 56, 43, 57, 52, 57, 41, 35, 43, 31, 54, 78, 43, 37, 41, 52, 37, 57, 59, 43, 44, 35, 33, 41, 35, 39, 33, 44, 56, 41, 52, 52, 37, 37, 33, 43, 31, 52, 56, 31, 44, 57, 44, 52, 44, 37, 43, 56, 61, 41, 26, 41, 44, 48, 59, 31, 33, 39, 28, 26, 54, 31, 26, 35, 33, 41, 33, 37, 33, 50, 43, 44, 44, 26, 41, 37, 22, 50, 46, 31, 39, 31, 37, 35, 37, 44, 43, 91, 57, 35, 31, 48, 33, 39, 37, 41, 54, 35, 37, 35, 26, 41, 35, 26, 31, 26, 31, 43, 50, 48, 39, 22, 22, 17, 37, 54, 52, 41, 50, 43, 41, 35, 41, 28, 35, 20, 24, 41, 39, 30, 35, 20, 31, 44, 31, 46, 57, 54, 39, 39, 43, 46, 26, 35, 41, 37, 26, 28, 24, 28, 26, 20, 24, 24, 26, 24, 22, 35, 26, 30, 48, 48, 35, 33, 31, 46, 30, 39, 33, 30, 48, 39, 46, 46, 31, 24, 30, 28, 31, 54, 44, 43, 35, 24, 28, 30, 26, 37, 81, 76, 41, 30, 96, 69, 50, 33, 37, 28, 30, 48, 43, 43, 33, 67, 61, 35, 44, 46, 35, 22, 41, 56, 63, 70, 54, 31, 24, 22, 20, 52, 43, 31, 46, 44, 41, 61, 72, 46, 28, 26, 33, 35, 41, 24, 26, 31, 48, 44, 37, 30, 28, 26, 46, 63, 78, 44, 43, 28, 31, 22, 44, 52, 56, 48, 50, 52, 37, 31, 59, 76, 61, 52, 43, 31, 35, 41, 59, 50, 41, 28, 35, 30, 44, 31, 41, 30, 26, 37, 37, 61, 41, 35, 50, 37, 52, 61, 30, 31, 39, 63, 46, 61, 35, 37, 35, 41, 52, 57, 76, 78, 30, 50, 26, 41, 69, 31, 46, 28, 48, 39, 44, 70, 43, 37, 28, 56, 37, 46, 67, 50, 30, 41, 54, 37, 35, 33, 39, 72, 39, 74, 35, 43, 41, 41, 63, 37, 44, 33, 52, 41, 44, 46, 61, 59, 61, 52, 30, 50, 70, 31, 33, 65, 44, 39, 41, 65, 41, 31, 56, 31, 46, 57, 41, 54, 59, 57, 31, 30, 46, 54, 46, 43, 37, 48, 52, 35, 26, 44, 41, 48, 41, 33, 56, 43, 54, 35, 33, 39, 39, 44, 48, 59, 37, 52, 43, 59, 35, 37, 43, 57, 48, 26, 37, 61, 43, 43, 46, 31, 35, 26, 46, 33, 41, 37, 31, 39, 37, 46, 48, 41, 39, 43, 37, 31, 31, 61, 44, 20, 28, 43, 91, 48, 33, 26, 59, 44, 43, 35, 31, 35, 52, 41, 44, 31, 70, 37, 31, 28, 35, 72, 44, 44, 41, 31, 37, 41, 52, 37, 31, 28, 31, 39, 48, 48, 52, 31, 35, 70, 63, 54, 35, 22, 44, 35, 24, 46, 41, 20, 54, 61, 83, 87, 72, 26, 19, 57, 48, 35, 39, 37, 33, 41, 52, 50, 28, 41, 46, 56, 35, 35, 52, 70, 52, 59, 46, 48, 41, 24, 20, 28, 31, 41, 72, 44, 35, 26, 30, 26, 24, 26, 28, 30, 63, 50, 35, 33, 33, 28, 24, 52, 30, 31, 24, 24, 33, 24, 39, 24, 30, 39, 41, 41, 33, 22, 26, 24, 37, 26, 26, 28, 22, 28, 33, 65, 44, 31, 30, 37, 43, 31, 24, 43, 61, 57, 76, 44, 24, 43, 57, 48, 33, 26, 33, 28, 28, 33, 31, 59, 63, 41, 41, 41, 41, 61, 43, 57, 33, 48, 37, 33, 33, 30, 33, 30, 74, 48, 30, 30, 28, 46, 39, 24, 31, 31, 33, 22, 59, 56, 28, 52, 48, 30, 39, 35, 31, 31, 52, 48, 37, 24, 54, 52, 41, 37, 39, 24, 30, 43, 41, 37, 43, 52, 33, 37, 35, 59, 69, 65, 54, 43, 46, 28, 50, 33, 33, 33, 22, 46, 20, 43, 67, 35, 43, 24, 41, 43, 37, 37, 44, 43, 31, 35, 39, 35, 31, 61, 41, 39, 43, 69, 54, 31, 31, 39, 48, 44, 46, 35, 56, 50, 33, 46, 46, 30, 30, 31, 43, 48, 33, 46, 31, 44, 57, 28, 54, 54, 33, 52, 52, 74, 37, 37, 43, 48, 63, 61, 31, 28, 35, 39, 43, 61, 44, 59, 39, 48, 28, 43, 80, 37, 46, 52, 50, 44, 31, 37, 35, 39, 59, 44, 35, 26, 41, 35, 28, 44, 46, 54, 48, 41, 41, 31, 41, 28, 52, 37, 54, 43, 33, 35, 41, 39, 61, 30, 41, 31, 41, 41, 48, 39, 65, 70, 48, 43, 33, 43, 59, 56, 37, 30, 24, 39, 43, 26, 33, 46, 48, 31, 48, 39, 30, 35, 52, 37, 39, 43, 46, 44, 63, 33, 28, 31, 33, 50, 46, 39, 41, 46, 44, 33, 43, 31, 37, 43, 30, 41, 44, 39, 41, 52, 44, 52, 43, 50, 33, 31, 24, 28, 41, 26, 37, 30, 39, 37, 35, 35, 33, 41, 43, 43, 31, 26, 41, 31, 35, 28, 33, 33, 28, 43, 37, 24, 22, 30, 44, 52, 43, 20, 22, 35, 24, 26, 33, 44, 41, 33, 26, 28, 41, 24, 22, 43, 72, 43, 46, 30, 28, 30, 28, 31, 39, 37, 41, 24, 24, 61, 44, 33, 48, 61, 39, 37, 39, 35, 24, 41, 28, 89, 96, 59, 44, 31, 59, 35, 54, 33, 30, 41, 26, 30, 30, 31, 52, 52, 59, 50, 35, 69, 54, 39, 46, 46, 31, 37, 24, 22, 46, 61, 50, 28, 30, 30, 69, 54, 72, 50, 31, 28, 24, 30, 20, 35, 31, 52, 69, 46, 44, 39, 63, 48, 50, 33, 24, 22, 54, 63, 35, 31, 33, 28, 28, 44, 46, 41, 41, 28, 30, 24, 24, 31, 48, 59, 39, 35, 37, 43, 48, 43, 33, 33, 22, 31, 54, 28, 31, 65, 39, 26, 24, 30, 41, 52, 57, 33, 28, 30, 37, 41, 43, 37, 30, 59, 28, 31, 56, 61, 30, 41, 41, 61, 35, 56, 67, 41, 41, 72, 70, 57, 48, 37, 54, 52, 41, 61, 39, 57, 30, 50, 56, 41, 48, 50, 44, 46, 57, 59, 37, 37, 26, 41, 30, 41, 50, 52, 33, 39, 37, 35, 76, 57, 44, 54, 37, 28, 33, 48, 72, 56, 39, 39, 43, 37, 44, 33, 35, 46, 52, 37, 46, 35, 37, 44, 50, 37, 57, 41, 39, 59, 33, 37, 56, 72, 39, 41, 52, 44, 57, 46, 30, 70, 57, 44, 48, 52, 35, 48, 44, 48, 52, 43, 61, 28, 30, 37, 24, 56, 48, 31, 30, 35, 43, 54, 31, 31, 63, 31, 52, 35, 33, 52, 50, 59, 41, 65, 48, 39, 56, 69, 35, 31, 31, 48, 31, 56, 57, 33, 50, 24, 35, 41, 48, 41, 46, 54, 44, 63, 59, 37, 44, 37, 54, 70, 41, 48, 63, 33, 48, 46, 31, 44, 48, 44, 48, 43, 26, 63, 54, 56, 65, 54, 46, 43, 44, 31, 46, 56, 44, 54, 56, 59, 65, 57, 39, 30, 63, 41, 41, 26, 28, 41, 54, 30, 69, 54, 35, 50, 50, 41, 37, 24, 28, 37, 67, 54, 54, 43, 31, 26, 26, 39, 24, 24, 30, 30, 26, 19, 22, 24, 39, 46, 44, 31, 28, 30, 39, 43, 24, 26, 43, 50, 33, 31, 37, 30, 26, 28, 26, 43, 33, 28, 33, 43, 35, 30, 22, 24, 54, 33, 30, 24, 48, 56, 39, 52, 43, 41, 41, 28, 28, 59, 56, 44, 52, 50, 20, 26, 37, 24, 22, 26, 26, 52, 37, 26, 37, 30, 24, 43, 35], 'WindDir9am': ['S', 'W', 'ESE', 'NNE', 'NNE', 'W', 'W', 'S', 'SSW', 'W', 'WNW', 'N', 'S', 'SSW', 'SW', 'WNW', 'SE', 'SSE', 'WNW', 'W', 'WNW', 'WNW', 'WSW', 'WNW', 'E', 'WSW', 'W', 'S', 'SW', 'W', 'W', 'W', 'WNW', 'S', 'N', 'SSW', 'WNW', 'W', 'WNW', 'ENE', 'W', 'WNW', 'W', 'NW', 'W', 'WNW', 'N', 'SSE', 'NNE', 'S', 'ESE', 'WNW', 'NNW', 'NE', 'W', 'W', 'SSW', 'W', 'W', 'WNW', 'W', 'W', 'SW', 'W', 'WNW', 'W', 'SSW', 'SE', 'W', 'W', 'W', 'W', 'W', 'SSW', 'SW', 'SSW', 'SSW', 'W', 'SE', 'ESE', 'SSW', 'SSE', 'SW', 'S', 'W', 'NNW', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'NNW', 'W', 'W', 'W', 'WNW', 'SSW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'SE', 'SSW', 'WSW', 'W', 'WNW', 'W', 'W', 'NNW', 'W', 'NW', 'W', 'SSW', 'SSW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'NNW', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'N', 'NW', 'W', 'W', 'W', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NW', 'W', 'W', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'E', 'W', 'W', 'SSW', 'W', 'W', 'WNW', 'W', 'WNW', 'W', 'NNE', 'W', 'W', 'SSE', 'SE', 'ESE', 'S', 'W', 'W', 'WSW', 'W', 'WNW', 'W', 'E', 'N', 'N', 'W', 'S', 'W', 'W', 'N', 'E', 'W', 'SSW', 'WNW', 'W', 'ESE', 'S', 'WNW', 'SW', 'W', 'WNW', 'NE', 'WNW', 'ESE', 'SSW', 'SSW', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'SSW', 'SSE', 'W', 'W', 'S', 'W', 'SSW', 'SSW', 'WSW', 'SW', 'WNW', 'W', 'ESE', 'E', 'S', 'ESE', 'W', 'N', 'S', 'W', 'WNW', 'S', 'W', 'W', 'WNW', 'NNW', 'W', 'E', 'W', 'NNW', 'ENE', 'ENE', 'SSE', 'S', 'E', 'NNE', 'NNE', 'WNW', 'WSW', 'WNW', 'WNW', 'SSW', 'SSW', 'E', 'NNE', 'NW', 'S', 'SSW', 'ENE', 'W', 'W', 'ESE', 'N', 'W', 'W', 'E', 'W', 'S', 'ESE', 'ENE', 'N', 'W', 'S', 'NNW', 'WNW', 'WNW', 'WNW', 'S', 'NNW', 'NNE', 'E', 'S', 'E', 'ESE', 'E', 'W', 'SSE', 'W', 'W', 'W', 'E', 'ESE', 'NNE', 'ESE', 'SSW', 'SSW', 'SSE', 'SSE', 'ENE', 'NE', 'E', 'ESE', 'E', 'ESE', 'S', 'SSE', 'WNW', 'N', 'E', 'W', 'NNW', 'ESE', 'NW', 'SE', 'S', 'S', 'N', 'E', 'E', 'ENE', 'E', 'ESE', 'W', 'S', 'E', 'E', 'E', 'E', 'S', 'SSW', 'SSW', 'SSW', 'SE', 'ESE', 'SSE', 'SE', 'SE', 'W', 'NNW', 'W', 'W', 'SSE', 'W', 'W', 'S', 'S', 'W', 'N', 'E', 'W', 'ENE', 'E', 'W', 'W', 'SW', 'SSW', 'SW', 'ENE', 'ESE', 'W', 'W', 'NE', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'NE', 'NNE', 'NNE', 'NE', 'SSE', 'WNW', 'WNW', 'ESE', 'SE', 'ESE', 'ESE', 'W', 'S', 'W', 'S', 'S', 'W', 'WNW', 'W', 'W', 'SE', 'W', 'W', 'W', 'WNW', 'WSW', 'SSW', 'SSE', 'ESE', 'SW', 'WNW', 'NNW', 'NW', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'SSW', 'W', 'W', 'W', 'NW', 'W', 'W', 'W', 'W', 'W', 'E', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'E', 'W', 'WNW', 'SE', 'W', 'W', 'W', 'NW', 'NNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'SW', 'W', 'W', 'ENE', 'W', 'W', 'WNW', 'W', 'NNW', 'WNW', 'W', 'WNW', 'W', 'W', 'NNW', 'W', 'NNW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NW', 'NNW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'NNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'NNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'WNW', 'W', 'N', 'SSW', 'W', 'W', 'W', 'WNW', 'E', 'W', 'NNW', 'W', 'WNW', 'W', 'WNW', 'W', 'W', 'WSW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'WNW', 'NNW', 'S', 'W', 'SW', 'SE', 'SW', 'W', 'WNW', 'S', 'NW', 'W', 'W', 'N', 'W', 'W', 'W', 'W', 'W', 'NW', 'W', 'SSW', 'E', 'W', 'W', 'W', 'SW', 'WSW', 'W', 'W', 'E', 'W', 'NW', 'WNW', 'W', 'WNW', 'ENE', 'W', 'W', 'WNW', 'ESE', 'NNW', 'SSE', 'E', 'SE', 'ESE', 'E', 'ENE', 'NNE', 'SSW', 'ESE', 'SE', 'SE', 'ESE', 'E', 'ESE', 'ENE', 'NNE', 'W', 'NNW', 'S', 'WSW', 'S', 'W', 'SSE', 'E', 'E', 'NW', 'WSW', 'ENE', 'SSE', 'SSE', 'W', 'NE', 'WNW', 'E', 'WNW', 'SSW', 'S', 'SSW', 'WNW', 'S', 'ENE', 'ENE', 'E', 'WNW', 'S', 'NNW', 'WSW', 'NNW', 'S', 'ESE', 'NE', 'NE', 'E', 'NE', 'W', 'SE', 'NE', 'SSW', 'SSW', 'SSW', 'SE', 'S', 'S', 'W', 'E', 'W', 'W', 'E', 'ENE', 'S', 'S', 'E', 'WSW', 'N', 'E', 'N', 'SSE', 'S', 'SSW', 'NE', 'W', 'W', 'WSW', 'WNW', 'W', 'W', 'NW', 'SSW', 'WNW', 'NE', 'S', 'W', 'WNW', 'S', 'E', 'E', 'ESE', 'E', 'E', 'NE', 'S', 'SSW', 'ESE', 'W', 'NE', 'E', 'W', 'S', 'W', 'W', 'W', 'SW', 'SE', 'ESE', 'W', 'W', 'W', 'S', 'ESE', 'E', 'W', 'W', 'WSW', 'SSW', 'SE', 'SE', 'W', 'NE', 'NNW', 'ENE', 'ENE', 'WNW', 'S', 'S', 'SE', 'SSE', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'ESE', 'WNW', 'W', 'W', 'W', 'SSW', 'W', 'W', 'SSW', 'S', 'W', 'W', 'WNW', 'W', 'WNW', 'W', 'NNE', 'W', 'WNW', 'W', 'NNW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'NW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'NNE', 'W', 'W', 'W', 'W', 'W', 'W', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'WNW', 'W', 'SE', 'W', 'N', 'WNW', 'SSW', 'W', 'W', 'SSW', 'E', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'NNW', 'W', 'W', 'SSE', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'N', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'N', 'NW', 'W', 'W', 'N', 'W', 'W', 'W', 'NNW', 'W', 'W', 'W', 'W', 'WSW', 'NW', 'W', 'W', 'N', 'NNW', 'W', 'W', 'W', 'NNW', 'WNW', 'WNW', 'W', 'NW', 'W', 'SW', 'NW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'ESE', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'SE', 'NNW', 'W', 'W', 'E', 'ENE', 'E', 'NNW', 'NE', 'W', 'W', 'W', 'W', 'W', 'W', 'SSE', 'W', 'SSE', 'SE', 'WNW', 'N', 'NE', 'S', 'W', 'W', 'S', 'SE', 'SSW', 'WNW', 'E', 'SSE', 'WNW', 'ESE', 'ENE', 'SW', 'S', 'S', 'N', 'S', 'WNW', 'NNE', 'E', 'E', 'E', 'NE', 'SSW', 'S', 'ENE', 'ENE', 'NNE', 'NNW', 'ESE', 'E', 'NE', 'NE', 'WSW', 'W', 'W', 'SSW', 'E', 'ENE', 'SSW', 'NW', 'N', 'W', 'WNW', 'SE', 'W', 'ESE', 'W', 'W', 'SSW', 'SSE', 'WSW', 'E', 'ESE', 'E', 'SE', 'S', 'SSW', 'WNW', 'S', 'SSE', 'ENE', 'ENE', 'ENE', 'E', 'ENE', 'NE', 'NNE', 'N', 'S', 'E', 'S', 'S', 'E', 'ESE', 'NE', 'NNE', 'NNE', 'WSW', 'ESE', 'S', 'SSE', 'ENE', 'NNW', 'ENE', 'W', 'SSE', 'SSE', 'N', 'NW', 'W', 'WSW', 'WNW', 'SSW', 'W', 'NNE', 'S', 'SSW', 'SE', 'WNW', 'WNW', 'NNW', 'S', 'NNE', 'E', 'SSE', 'SSE', 'W', 'W', 'WNW', 'WNW', 'W', 'NE', 'W', 'ESE', 'W', 'W', 'SSE', 'SSE', 'ESE', 'W', 'W', 'W', 'S', 'N', 'N', 'WNW', 'WNW', 'W', 'S', 'SSW', 'ESE', 'ESE', 'E', 'WNW', 'W', 'NW', 'W', 'SSW', 'WNW', 'W', 'WNW', 'WNW', 'SSE', 'WNW', 'W', 'W', 'W', 'SW', 'W', 'W', 'W', 'SSW', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'NW', 'WNW', 'SSW', 'W', 'W', 'W', 'W', 'SSE', 'ESE', 'SE', 'S', 'WNW', 'WNW', 'W', 'NW', 'W', 'WNW', 'WNW', 'W', 'SSW', 'SSE', 'SSW', 'SE', 'SSE', 'SSE', 'WNW', 'W', 'W', 'WSW', 'N', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'SSE', 'S', 'WNW', 'W', 'WNW', 'NNW', 'WNW', 'NW', 'W', 'WNW', 'WNW', 'W', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'SSW', 'SW', 'SE', 'W', 'W', 'WNW', 'WNW', 'WNW', 'W', 'WNW', 'W', 'WNW', 'W', 'WNW', 'W', 'WNW', 'W', 'W', 'NNW', 'W', 'W', 'WNW', 'W', 'SW', 'W', 'W', 'WNW', 'W', 'W', 'NW', 'W', 'SSE', 'SE', 'SE', 'W', 'WNW', 'W', 'SSE', 'W', 'W', 'NW', 'S', 'WNW', 'WNW', 'SSW', 'W', 'N', 'SE', 'N', 'W', 'S', 'W', 'WSW', 'WSW', 'W', 'WNW', 'SE', 'SSE', 'WNW', 'SSE', 'ESE', 'ENE', 'N', 'WSW', 'WNW', 'W', 'ESE', 'SE', 'SE', 'W', 'N', 'NNW', 'WNW', 'SSW', 'SSW', 'WSW', 'W', 'W', 'W', 'WNW', 'WNW', 'W', 'WNW', 'WSW', 'W', 'W', 'ENE', 'NE', 'S', 'SSE', 'SW', 'W', 'W', 'WNW', 'N', 'SSW', 'ESE', 'SSE', 'SSE', 'ESE', 'NE', 'SE', 'S', 'SW', 'SSE', 'WNW', 'E', 'WNW', 'NNW', 'ESE', 'WNW', 'W', 'W', 'WNW', 'E', 'NNE', 'E', 'SSW', 'E', 'E', 'E', 'ENE', 'ENE', 'W', 'SSE', 'SE', 'E', 'NNE', 'WNW', 'N', 'NE', 'NNE', 'S', 'SSW', 'W', 'SSW', 'S', 'SSW', 'WNW', 'SE', 'W', 'NNE', 'ENE', 'SSE', 'SSW', 'SSW', 'SSE', 'ESE', 'ESE', 'W', 'NNW', 'SSW', 'SSW', 'SE', 'ESE', 'E', 'NE', 'NNE', 'S', 'SSW', 'SSW', 'W', 'W', 'NNW', 'NNE', 'NE', 'E', 'S', 'S', 'W', 'W', 'SSW', 'W', 'WNW', 'WSW', 'WNW', 'SE', 'ESE', 'NNW', 'ENE', 'SSW', 'SSE', 'E', 'ESE', 'ESE', 'W', 'NNE', 'SSE', 'ESE', 'ESE', 'NNE', 'NE', 'SW', 'SE', 'SE', 'W', 'WNW', 'W', 'S', 'SSW', 'SE', 'E', 'N', 'WNW', 'WNW', 'W', 'S', 'E', 'N', 'ENE', 'SSW', 'WNW', 'W', 'SSW', 'WSW', 'W', 'WNW', 'ESE', 'NE', 'NE', 'E', 'SSW', 'NNW', 'SSE', 'E', 'N', 'SW', 'S', 'SSW', 'W', 'W', 'W', 'W', 'ESE', 'W', 'W', 'ENE', 'ESE', 'SSW', 'SW', 'SE', 'SSW', 'NNW', 'SSW', 'WNW', 'W', 'WNW', 'SSW', 'WNW', 'E', 'WNW', 'W', 'WNW', 'WNW', 'W', 'WNW', 'NE', 'SSE', 'W', 'WSW', 'NE', 'WSW', 'SSW', 'SSW', 'W', 'WNW', 'W', 'WNW', 'WNW', 'SSE', 'WSW', 'ENE', 'W', 'SSW', 'NW', 'W', 'WNW', 'W', 'W', 'W', 'SSW', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WSW', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'WNW', 'NNW', 'WNW', 'W', 'W', 'NW', 'W', 'W', 'WNW', 'WNW', 'WNW', 'W', 'WNW', 'SSW', 'W', 'W', 'W', 'W', 'W', 'SE', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'WNW', 'NW', 'NNW', 'W', 'WNW', 'S', 'SSW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'SW', 'W', 'W', 'WNW', 'W', 'WNW', 'W', 'NW', 'W', 'WNW', 'W', 'WNW', 'W', 'W', 'W', 'SSW', 'W', 'W', 'W', 'N', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'N', 'W', 'W', 'WNW', 'W', 'WNW', 'W', 'N', 'NW', 'W', 'W', 'WNW', 'WNW', 'WNW', 'WNW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NNW', 'WNW', 'WNW', 'W', 'WNW', 'W', 'N', 'W', 'W', 'N', 'S', 'W', 'WNW', 'W', 'NNE', 'WNW', 'SSW', 'WSW', 'W', 'S', 'NNE', 'ENE', 'WSW', 'WNW', 'S', 'W', 'W', 'W', 'ESE', 'SW', 'NNW', 'SSE', 'SE', 'W', 'W', 'WNW', 'W', 'ESE', 'SE', 'ENE', 'WNW', 'WNW', 'W', 'SSE', 'SE', 'W', 'W', 'ESE', 'SSW', 'ESE', 'WNW', 'WSW', 'WNW', 'WNW', 'S', 'WSW', 'WNW', 'ESE', 'E', 'NE', 'ENE', 'W', 'SSE', 'ESE', 'W', 'S', 'E', 'NE', 'SSW', 'ESE', 'W', 'W', 'SSE', 'W', 'SSE', 'E', 'ESE', 'W', 'S', 'ESE', 'SE', 'ESE', 'W', 'ESE', 'SE', 'ESE', 'NE', 'NE', 'ENE', 'S', 'SSE', 'S', 'ENE', 'NE', 'W', 'ESE', 'S', 'NW', 'WNW', 'NW', 'E', 'S', 'SE', 'ESE', 'NNE', 'SSW', 'SSW', 'N', 'ENE', 'E', 'NE', 'WNW', 'SE', 'N', 'SE', 'SE', 'SE', 'E', 'E', 'NNW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'SSE', 'SSW', 'N', 'SSW', 'W', 'W', 'WNW', 'NNE', 'NNW', 'ESE', 'WNW', 'WNW', 'WNW', 'W', 'E', 'SW', 'W', 'WSW', 'WSW', 'W', 'S', 'SE', 'WNW', 'W', 'W', 'W', 'WNW', 'WNW', 'WNW', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'WNW', 'WSW', 'S', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'SSW', 'WNW', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NNW', 'WSW', 'W', 'W', 'W', 'W', 'WNW', 'WSW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'WNW', 'W', 'N', 'W', 'W', 'W', 'WNW', 'W', 'NNW', 'W', 'W', 'W', 'W', 'WNW', 'WNW', 'NNW', 'WSW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'SE', 'W', 'W', 'SSE', 'W', 'W', 'W', 'WNW', 'NNW', 'NW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NW', 'W', 'W', 'W', 'NE', 'N', 'NW', 'WNW', 'W', 'WSW', 'W', 'WNW', 'W', 'WNW', 'N', 'W', 'SSW', 'WNW', 'W', 'W', 'NW', 'WNW', 'NW', 'W', 'W', 'W', 'W', 'WNW', 'N', 'NNW', 'NNW', 'WSW', 'WNW', 'NNE', 'NW', 'N', 'WSW', 'W', 'N', 'NW', 'WSW', 'WNW', 'WNW', 'W', 'W', 'WNW', 'N', 'WNW', 'WNW', 'W', 'WNW', 'W', 'W', 'SSW', 'W', 'SSE', 'N', 'NW', 'W', 'W', 'SW', 'W', 'S', 'S', 'N', 'NW', 'W', 'NNW', 'W', 'WNW', 'W', 'E', 'W', 'NW', 'W', 'W', 'W', 'W', 'NNW', 'NNW', 'WSW', 'WNW', 'W', 'WNW', 'SSW', 'WNW', 'W', 'NW', 'SSE', 'WNW', 'WNW', 'SSW', 'WNW', 'NNE', 'N', 'W', 'WNW', 'W', 'W', 'SSW', 'NNW', 'WSW', 'WSW', 'WSW', 'NW', 'ENE', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'SSW', 'SSE', 'N', 'W', 'WNW', 'NNW', 'SSE', 'SSW', 'S', 'SSW', 'W', 'NNE', 'NE', 'WNW', 'SSE', 'SW', 'WSW', 'WNW', 'NNE', 'SSE', 'S', 'WNW', 'E', 'N', 'ENE', 'SSW', 'W', 'W', 'E', 'ESE', 'WNW', 'WSW', 'E', 'ESE', 'S', 'NE', 'NE', 'NNE', 'ENE', 'NE', 'E', 'SSW', 'NE', 'ESE', 'SSE', 'W', 'SSW', 'W', 'ENE', 'SSE', 'E', 'W', 'NNE', 'ESE', 'ENE', 'SSW', 'NNE', 'WSW', 'SSE', 'SE', 'ENE', 'ESE', 'W', 'ENE', 'SW', 'W', 'ESE', 'ENE', 'NNE', 'ENE', 'SE', 'SSE', 'E', 'SE', 'E', 'NNE', 'S', 'SSW', 'W', 'NNE', 'NNE', 'E', 'NE', 'SSW', 'NE', 'NNE', 'ESE', 'SSE', 'WSW', 'W', 'SE', 'ENE', 'SSW', 'S', 'ESE', 'NE', 'NNE', 'E', 'S', 'SSW', 'NW', 'N', 'SW', 'W', 'SE', 'SSE', 'WNW', 'NNW', 'ESE', 'S', 'SSE', 'WNW', 'SSW', 'WNW', 'WNW', 'WNW', 'SSW', 'WNW', 'NNE', 'W', 'NNE', 'W', 'WNW', 'SW', 'NNW', 'NNW', 'WNW', 'W', 'W', 'SSW', 'W', 'NNE', 'ESE', 'SE', 'SSW', 'W', 'WNW', 'NNE', 'WNW', 'W', 'WNW', 'WNW', 'WNW', 'WNW', 'WNW', 'SSW', 'WNW', 'SW', 'WSW', 'WNW', 'WNW', 'W', 'NW', 'SW', 'SW', 'W', 'W', 'W', 'W', 'WNW', 'SSW', 'W', 'W', 'WNW', 'W', 'WNW', 'S', 'N', 'SSE', 'W', 'NNW', 'WSW', 'W', 'W', 'NW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'NNE', 'NW', 'W', 'W', 'WNW', 'NW', 'W', 'WSW', 'W', 'W', 'SSW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'NW', 'W', 'W', 'W', 'WNW', 'N', 'WNW', 'WNW', 'NNW', 'NW', 'W', 'WNW', 'NW', 'N', 'NW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NNW', 'WNW', 'WNW', 'WNW', 'W', 'W', 'W', 'ENE', 'NW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'WNW', 'NW', 'WNW', 'W', 'W', 'WNW', 'WNW', 'NNW', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'E', 'SSE', 'S', 'W', 'WNW', 'W', 'NW', 'WNW', 'W', 'SSW', 'S', 'SSE', 'W', 'SW', 'W', 'WNW', 'W', 'SW', 'SSW', 'W', 'NW', 'W', 'WNW', 'NNW', 'W', 'WNW', 'SSW', 'WNW', 'WNW', 'WNW', 'WSW', 'W', 'WNW', 'WNW', 'WNW', 'W', 'WNW', 'W', 'SSW', 'SSW', 'NNW', 'N', 'SE', 'W', 'W', 'W', 'NE', 'W', 'WNW', 'WSW', 'SSE', 'WNW', 'NNW', 'WNW', 'W', 'ESE', 'W', 'SW', 'W', 'SSE', 'W', 'W', 'S', 'ESE', 'NNW', 'W', 'NNW', 'WNW', 'W', 'NNE', 'W', 'SSW', 'W', 'W', 'WNW', 'NNE', 'ESE', 'SSW', 'E', 'E', 'S', 'S', 'ESE', 'WNW', 'ENE', 'SSW', 'S', 'NW', 'W', 'W', 'ENE', 'NE', 'SSE', 'SE', 'E', 'SSW', 'SSW', 'ENE', 'ENE', 'E', 'WNW', 'E', 'ENE', 'N', 'NE', 'ENE', 'ESE', 'ESE', 'E', 'W', 'SE', 'WNW', 'ENE', 'NNE', 'SSE', 'WNW', 'SSE', 'ESE', 'W', 'ENE', 'NW', 'S', 'N', 'WSW', 'ESE', 'S', 'NNW', 'S', 'E', 'NE', 'S', 'E', 'E', 'SSW', 'SSE', 'E', 'N', 'E', 'ESE', 'ESE', 'SSE', 'WSW', 'WNW', 'WSW', 'WSW', 'W', 'SSW', 'SSE', 'ENE', 'SSE', 'ESE', 'NE', 'E', 'W', 'SSE', 'ESE', 'SSE', 'SSW', 'WSW', 'WNW', 'SSW', 'SSW', 'SW', 'W', 'ESE', 'W', 'WNW', 'W', 'S', 'WNW', 'ENE', 'SE', 'WNW', 'W', 'N', 'NE', 'NNE', 'NE', 'ENE', 'W', 'SSE', 'ESE', 'NNE', 'NNW', 'WSW', 'WNW', 'S', 'ENE', 'E', 'SSW', 'WNW', 'S', 'SW', 'WNW', 'E', 'WNW', 'WNW', 'SSW', 'WNW', 'SSE', 'SSE', 'WNW', 'SSW', 'WNW', 'WNW', 'NNE', 'W', 'W', 'SE', 'E', 'N', 'SW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'N', 'SSE', 'ESE', 'W', 'WNW', 'WNW', 'WSW', 'WSW', 'SSW', 'W', 'WNW', 'SW', 'WNW', 'W', 'WNW', 'E', 'N', 'WSW', 'S', 'SSE', 'SSW', 'WNW', 'WNW', 'W', 'W', 'W', 'WNW', 'WNW', 'SSE', 'SSW', 'ESE', 'SSW', 'W', 'NNW', 'W', 'W', 'W', 'W', 'N', 'WNW', 'NW', 'W', 'W', 'W', 'SW', 'W', 'W', 'NNE', 'NW', 'W', 'S', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'WNW', 'WNW', 'WSW', 'WSW', 'W', 'WNW', 'WSW', 'W', 'W', 'WNW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'N', 'N', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'W', 'WNW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'SSW', 'W', 'WNW', 'W', 'W', 'WNW', 'SE', 'W', 'W', 'NNW', 'N', 'W', 'WNW', 'W', 'W', 'N', 'NW', 'WNW', 'WNW', 'W', 'WNW', 'WNW', 'W', 'WNW', 'W', 'W', 'W', 'W', 'WSW', 'W', 'WNW', 'W', 'W', 'WSW', 'W', 'WNW', 'WNW', 'N', 'N', 'S', 'WNW', 'SSE', 'W', 'W', 'W', 'WNW', 'WSW', 'W', 'W', 'WNW', 'SSW', 'WNW', 'NNE', 'W', 'WSW', 'W', 'WNW', 'WNW', 'W', 'WNW', 'NNE', 'NNE', 'W', 'WNW', 'S', 'W', 'W', 'W', 'SW', 'SSW', 'SSW', 'S', 'W', 'SW', 'W', 'N', 'SSE', 'W', 'NNW', 'W', 'W', 'WNW', 'WNW', 'SSE', 'ESE', 'N', 'SE', 'WNW', 'WSW', 'S', 'W', 'NNE', 'ESE', 'SSE', 'SE', 'N', 'SE', 'WNW', 'S', 'SSW', 'WNW', 'E', 'ESE', 'S', 'W', 'WNW', 'W', 'NE', 'E', 'NW', 'SSE', 'ESE', 'NE', 'W', 'ESE', 'SSW', 'W', 'S', 'S', 'NNE', 'W', 'S', 'SSE', 'SSE', 'W', 'W', 'W', 'SW', 'SE', 'E', 'WNW', 'ENE', 'NNW', 'SE', 'ENE', 'NNE', 'WSW', 'ESE', 'S', 'ESE', 'WNW', 'SE', 'ESE', 'NE', 'NNE', 'S', 'W', 'E', 'NE', 'WNW', 'ENE', 'NE', 'WNW', 'E', 'ESE', 'ENE', 'SSW', 'SE', 'ESE', 'ENE', 'N', 'SSE', 'SW', 'SE', 'NW', 'WNW', 'SSW', 'W', 'SSE', 'ESE', 'SE', 'SE', 'SSW', 'NW', 'N', 'W', 'ESE', 'W', 'NNE', 'W', 'SSE', 'SSE', 'WNW', 'N', 'ESE', 'SW', 'SSW', 'S', 'SSW', 'E', 'E', 'NE', 'N', 'NNE', 'W', 'W', 'NNW', 'WNW', 'W', 'SSW', 'S', 'SE', 'WNW', 'WNW', 'SSE', 'W', 'WSW', 'W', 'N', 'NE', 'W', 'SSW', 'SSW', 'SSW', 'NW', 'SSW', 'S', 'W', 'N', 'NNE', 'NE', 'SSW', 'ESE', 'W', 'W', 'E', 'NNE', 'NNE', 'N', 'NNE', 'N', 'E', 'NE', 'N', 'SSE', 'ENE', 'WNW', 'NE', 'WNW', 'SW', 'S', 'NW', 'NNE', 'WSW', 'SSW', 'WSW', 'W', 'W', 'W', 'WNW', 'WNW', 'S', 'S', 'SSW', 'W', 'W', 'W', 'W', 'SSW', 'SE', 'NNE', 'ESE', 'SSE', 'W', 'WNW', 'WNW', 'WNW', 'SE', 'WNW', 'S', 'W', 'W', 'SSW', 'W', 'W', 'W', 'W', 'WNW', 'SSW', 'ESE', 'WNW', 'WNW', 'WNW', 'W', 'W', 'NE', 'N', 'NW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'NNE', 'NW', 'WSW', 'NNW', 'WNW', 'WNW', 'W', 'W', 'WNW', 'W', 'WNW', 'WSW', 'W', 'W', 'NW', 'W', 'W', 'NNW', 'W', 'NNW', 'W', 'W', 'W', 'W', 'W', 'WNW', 'NNE', 'NE', 'W', 'NNW', 'WNW', 'NNW', 'WNW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'NNW', 'E', 'W', 'NNW', 'NW', 'NW', 'NNW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'W', 'WNW', 'S', 'W', 'WNW', 'WNW', 'N', 'WNW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'S', 'W', 'NNW', 'WNW', 'W', 'NNW', 'N', 'NW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'SE', 'W', 'W', 'W', 'WNW', 'W', 'NNW', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'WNW', 'SSE', 'SW', 'W', 'W', 'W', 'W', 'W', 'N', 'W', 'SSE', 'WNW', 'WNW', 'W', 'WNW', 'WNW', 'N', 'ENE', 'NNW', 'WSW', 'W', 'SSW', 'NNW', 'NW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W', 'WSW', 'WNW', 'W', 'WSW', 'N', 'WNW', 'NNE', 'NNW', 'WNW', 'NW', 'NNE', 'NW', 'W', 'W', 'W', 'S', 'W', 'NE', 'WSW', 'W', 'SSW', 'WNW', 'W', 'N', 'WNW', 'NNW', 'WSW', 'ENE', 'NNW', 'SE', 'W', 'W', 'W', 'W', 'SSE', 'W', 'W', 'NE', 'SSW', 'W', 'WSW', 'WNW', 'W', 'SW', 'WSW', 'W', 'SE', 'S', 'W', 'SSW', 'NNW', 'NNW', 'W', 'S', 'WNW', 'ESE', 'W', 'SSE', 'E', 'E', 'E', 'WSW', 'W', 'ENE', 'SE', 'NE', 'S', 'ESE', 'W', 'WNW', 'SSE', 'E', 'NE', 'W', 'SE', 'NNE', 'W', 'SSE', 'NE', 'NE', 'ESE', 'NW', 'SE', 'SSE', 'NW', 'SE', 'ENE', 'E', 'S', 'E', 'NE', 'WNW', 'ESE', 'E', 'S', 'E', 'W', 'W', 'SSE', 'E', 'SSW', 'S', 'ESE', 'NNE', 'ESE', 'S', 'N', 'ESE', 'W', 'W', 'SSE', 'N', 'NNW', 'E', 'NNE', 'ESE', 'WNW', 'ESE', 'NNE', 'SSE', 'NE', 'NNW', 'NW', 'S', 'SSW', 'SSW', 'NE', 'SSW', 'E', 'ESE', 'SSW', 'S', 'NNE', 'ESE', 'E', 'S', 'S', 'ESE', 'NNW', 'NW', 'W', 'S', 'SSW', 'E', 'WSW', 'W', 'NE', 'S', 'W', 'W', 'WNW', 'NNE', 'N', 'SE', 'S', 'SSE', 'SE', 'ESE', 'SE', 'WNW', 'S', 'SE', 'W', 'WSW', 'SW', 'ESE', 'SE', 'W', 'WNW', 'NNE', 'NNE', 'ESE', 'E', 'ENE', 'SSW', 'SE', 'E', 'NE', 'NNE', 'SE', 'SSW', 'W', 'WNW', 'WNW', 'W', 'SSW', 'E', 'NNE', 'W', 'W', 'SSW', 'W', 'WNW', 'W', 'W', 'WNW', 'WNW', 'NW', 'WNW', 'W', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'W', 'W', 'WNW', 'WNW', 'NNE', 'WNW', 'W', 'E', 'W', 'W', 'W', 'WNW', 'W', 'W', 'S', 'WNW', 'WNW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'WNW', 'SW', 'W', 'W', 'W', 'WNW', 'NE', 'NW', 'W', 'W', 'WNW', 'NNW', 'W', 'W', 'W', 'W', 'SW', 'W', 'SSW', 'W', 'W', 'W', 'W', 'W', 'W', 'SSW', 'W', 'W', 'SE', 'W', 'WNW', 'W', 'WNW', 'W', 'W', 'WNW', 'SW', 'W', 'W', 'W', 'W', 'WNW', 'W', 'W'], 'WindDir3pm': ['SSW', 'E', 'ESE', 'E', 'W', 'ENE', 'S', 'SE', 'W', 'SSE', 'E', 'NE', 'S', 'SSE', 'SSE', 'SSE', 'ESE', 'ENE', 'E', 'E', 'SE', 'E', 'ESE', 'ESE', 'E', 'E', 'NNE', 'ESE', 'S', 'SSE', 'SE', 'ENE', 'E', 'ESE', 'ENE', 'SSE', 'E', 'E', 'NE', 'E', 'NE', 'ESE', 'ENE', 'ENE', 'E', 'E', 'ENE', 'E', 'NE', 'SSW', 'E', 'ESE', 'ENE', 'NNW', 'NW', 'ESE', 'SE', 'E', 'WNW', 'WNW', 'ESE', 'N', 'WSW', 'E', 'E', 'ESE', 'SSE', 'SE', 'E', 'E', 'E', 'E', 'ESE', 'S', 'S', 'SSW', 'S', 'SSE', 'SE', 'S', 'S', 'SE', 'SSE', 'S', 'E', 'N', 'WSW', 'SSE', 'E', 'W', 'WSW', 'SSE', 'SE', 'NW', 'WNW', 'SSE', 'S', 'SE', 'E', 'SSE', 'E', 'E', 'ENE', 'E', 'NE', 'NNW', 'W', 'WNW', 'W', 'S', 'SSE', 'SSE', 'NW', 'ENE', 'ENE', 'E', 'NE', 'S', 'E', 'SSE', 'SE', 'W', 'E', 'ESE', 'S', 'SSW', 'S', 'ESE', 'ESE', 'N', 'N', 'ENE', 'WSW', 'SW', 'SSW', 'SSW', 'SSW', 'NE', 'ESE', 'W', 'WSW', 'SSW', 'WSW', 'WNW', 'WNW', 'W', 'WSW', 'SSE', 'NNW', 'NW', 'W', 'W', 'WNW', 'S', 'NE', 'SSE', 'N', 'SE', 'WSW', 'NW', 'WSW', 'NE', 'N', 'E', 'ESE', 'SSE', 'N', 'W', 'W', 'NE', 'W', 'SSW', 'SSW', 'ESE', 'S', 'SSE', 'ESE', 'SW', 'SSW', 'ESE', 'E', 'WNW', 'W', 'W', 'E', 'SSE', 'SSW', 'NW', 'SW', 'WNW', 'WNW', 'W', 'W', 'ESE', 'WSW', 'W', 'SE', 'SSE', 'SSW', 'ENE', 'W', 'ENE', 'SSW', 'S', 'SSE', 'NE', 'E', 'S', 'SSE', 'ENE', 'N', 'E', 'ESE', 'SSE', 'ESE', 'ESE', 'S', 'ESE', 'SSE', 'SE', 'ESE', 'ENE', 'NE', 'NE', 'NW', 'NW', 'WSW', 'SE', 'NE', 'NE', 'W', 'NE', 'NW', 'SSE', 'E', 'E', 'NE', 'E', 'SSE', 'SE', 'NE', 'NE', 'NE', 'W', 'NE', 'S', 'ENE', 'E', 'E', 'ESE', 'E', 'E', 'E', 'NE', 'E', 'SE', 'E', 'ENE', 'E', 'NE', 'SE', 'SSE', 'S', 'S', 'E', 'E', 'NNE', 'NE', 'SSE', 'SE', 'NE', 'WNW', 'SSE', 'NE', 'W', 'SSE', 'NE', 'ENE', 'E', 'WSW', 'E', 'E', 'E', 'ENE', 'E', 'NE', 'SE', 'SE', 'NE', 'NE', 'E', 'N', 'E', 'E', 'SSW', 'SSE', 'SSE', 'E', 'NE', 'N', 'S', 'E', 'WNW', 'E', 'W', 'E', 'E', 'SSE', 'SE', 'E', 'NE', 'SSE', 'ESE', 'ENE', 'W', 'WSW', 'SE', 'NE', 'E', 'E', 'SE', 'SSE', 'E', 'NE', 'ENE', 'SSE', 'E', 'NE', 'NE', 'E', 'SE', 'E', 'E', 'NNW', 'ESE', 'ENE', 'NE', 'ENE', 'E', 'E', 'SSE', 'ESE', 'E', 'ENE', 'ESE', 'NE', 'NNE', 'NE', 'E', 'SSE', 'E', 'NE', 'NE', 'ENE', 'NNW', 'E', 'W', 'ESE', 'S', 'SSE', 'NE', 'NE', 'NE', 'NE', 'ESE', 'NE', 'SE', 'E', 'NE', 'ENE', 'NNE', 'ENE', 'S', 'SSW', 'S', 'SSE', 'SE', 'ESE', 'SE', 'SE', 'SE', 'S', 'E', 'E', 'E', 'E', 'ENE', 'SE', 'ESE', 'S', 'E', 'E', 'E', 'E', 'ENE', 'SW', 'SE', 'ESE', 'ESE', 'S', 'E', 'E', 'E', 'E', 'NW', 'ENE', 'E', 'E', 'SE', 'ENE', 'E', 'E', 'E', 'NE', 'NE', 'NE', 'E', 'ENE', 'SSE', 'E', 'E', 'SE', 'E', 'ESE', 'ESE', 'ENE', 'SSE', 'NE', 'SSE', 'SE', 'SE', 'E', 'E', 'ENE', 'S', 'E', 'NW', 'E', 'S', 'S', 'S', 'S', 'S', 'S', 'ENE', 'E', 'W', 'WNW', 'WNW', 'W', 'S', 'WSW', 'E', 'S', 'SE', 'E', 'S', 'ENE', 'SSE', 'S', 'E', 'SSE', 'SW', 'S', 'WNW', 'W', 'W', 'WSW', 'SE', 'ESE', 'E', 'ESE', 'E', 'E', 'E', 'E', 'E', 'E', 'W', 'S', 'S', 'SSW', 'E', 'E', 'ENE', 'E', 'ENE', 'W', 'WNW', 'WNW', 'W', 'WNW', 'WSW', 'W', 'W', 'WNW', 'NNE', 'SSW', 'S', 'WSW', 'E', 'E', 'NNE', 'NE', 'NE', 'E', 'E', 'WNW', 'ENE', 'N', 'WNW', 'W', 'NNW', 'W', 'W', 'W', 'W', 'S', 'WSW', 'SSW', 'ESE', 'ESE', 'SSE', 'ENE', 'N', 'N', 'WNW', 'NW', 'SW', 'SSW', 'WNW', 'WNW', 'N', 'E', 'NNW', 'SSW', 'E', 'ENE', 'W', 'WSW', 'WSW', 'WSW', 'W', 'W', 'WNW', 'E', 'W', 'W', 'ESE', 'NE', 'WNW', 'S', 'E', 'E', 'N', 'WNW', 'WSW', 'E', 'WNW', 'NE', 'SW', 'E', 'NE', 'E', 'NNE', 'ENE', 'ENE', 'NW', 'WNW', 'WNW', 'NE', 'NE', 'NE', 'W', 'W', 'ESE', 'E', 'W', 'WNW', 'ESE', 'ENE', 'NE', 'ENE', 'WSW', 'E', 'E', 'NE', 'E', 'SSE', 'NE', 'SSE', 'NNW', 'SE', 'E', 'NE', 'E', 'NNW', 'W', 'WNW', 'NE', 'W', 'W', 'S', 'E', 'ENE', 'E', 'SE', 'S', 'E', 'E', 'E', 'WSW', 'SSW', 'S', 'S', 'NNE', 'E', 'WNW', 'WNW', 'WNW', 'W', 'SE', 'ESE', 'E', 'ENE', 'E', 'E', 'E', 'E', 'WNW', 'SE', 'E', 'ENE', 'E', 'NE', 'ESE', 'WNW', 'E', 'ESE', 'E', 'E', 'E', 'E', 'ENE', 'E', 'NNE', 'SSE', 'ENE', 'SE', 'E', 'SSE', 'ENE', 'ENE', 'E', 'SE', 'N', 'SSE', 'SSE', 'E', 'NE', 'E', 'NE', 'W', 'S', 'S', 'SE', 'ENE', 'SSE', 'E', 'ENE', 'E', 'E', 'ESE', 'NE', 'ESE', 'ENE', 'SE', 'ESE', 'ENE', 'NE', 'NNE', 'SSE', 'SSE', 'E', 'NE', 'ENE', 'SSW', 'SSE', 'S', 'SE', 'SSE', 'ENE', 'E', 'E', 'E', 'ENE', 'ENE', 'SE', 'SE', 'E', 'NE', 'SSE', 'NE', 'ENE', 'SSE', 'S', 'ESE', 'ENE', 'SSE', 'W', 'E', 'E', 'E', 'E', 'SSE', 'ESE', 'E', 'ENE', 'SSE', 'ENE', 'SE', 'SE', 'E', 'E', 'SE', 'E', 'E', 'NNE', 'S', 'SE', 'E', 'E', 'ENE', 'ENE', 'WNW', 'E', 'E', 'ENE', 'S', 'SE', 'SE', 'E', 'NE', 'E', 'E', 'SE', 'E', 'ESE', 'ESE', 'NE', 'ESE', 'SE', 'SE', 'ESE', 'E', 'ENE', 'NE', 'ENE', 'NE', 'W', 'SSE', 'SSE', 'SE', 'SE', 'ESE', 'E', 'E', 'E', 'ENE', 'ENE', 'E', 'E', 'ESE', 'ENE', 'ESE', 'NE', 'ENE', 'S', 'NE', 'W', 'SSW', 'S', 'S', 'S', 'SE', 'SSE', 'SE', 'E', 'NNW', 'SSE', 'SE', 'E', 'WNW', 'WSW', 'SSE', 'ENE', 'ESE', 'SSE', 'ESE', 'E', 'E', 'ENE', 'E', 'NE', 'NNW', 'S', 'SE', 'W', 'W', 'WNW', 'S', 'ENE', 'SW', 'ESE', 'NE', 'W', 'WSW', 'WSW', 'E', 'E', 'NE', 'W', 'S', 'S', 'SW', 'S', 'SSE', 'WNW', 'SW', 'SSE', 'ESE', 'SSE', 'SSW', 'W', 'E', 'WNW', 'ESE', 'S', 'E', 'NE', 'W', 'S', 'S', 'SSW', 'ESE', 'SSE', 'SSW', 'SW', 'SSW', 'NE', 'WNW', 'SSW', 'W', 'S', 'S', 'ENE', 'ENE', 'ENE', 'N', 'ESE', 'S', 'S', 'E', 'N', 'WSW', 'SSW', 'W', 'WSW', 'WNW', 'W', 'W', 'SSW', 'S', 'W', 'SSW', 'S', 'S', 'ENE', 'NW', 'WNW', 'NNE', 'WNW', 'WSW', 'S', 'E', 'ESE', 'SSW', 'SSW', 'SSW', 'SSW', 'S', 'SE', 'SE', 'SE', 'E', 'NNE', 'N', 'NNE', 'W', 'NW', 'WSW', 'E', 'W', 'W', 'S', 'S', 'E', 'E', 'NNE', 'WNW', 'W', 'S', 'N', 'WNW', 'W', 'E', 'NE', 'WNW', 'WNW', 'W', 'E', 'NE', 'WNW', 'WNW', 'W', 'WNW', 'S', 'E', 'NE', 'E', 'E', 'E', 'E', 'E', 'E', 'S', 'ESE', 'NW', 'W', 'E', 'NE', 'W', 'ESE', 'WNW', 'ENE', 'ESE', 'ENE', 'E', 'SSE', 'E', 'E', 'NE', 'ESE', 'E', 'ENE', 'E', 'E', 'E', 'NE', 'W', 'SSE', 'E', 'ENE', 'ENE', 'WSW', 'S', 'ENE', 'SE', 'ESE', 'ENE', 'NE', 'NE', 'SSE', 'SSE', 'ESE', 'SE', 'SSE', 'SSE', 'E', 'NNE', 'E', 'ENE', 'E', 'NNE', 'SE', 'SSE', 'E', 'NE', 'SSE', 'E', 'NE', 'NE', 'E', 'NE', 'NE', 'S', 'SSE', 'E', 'ENE', 'E', 'E', 'ESE', 'ENE', 'NE', 'SSE', 'E', 'ENE', 'ENE', 'ESE', 'E', 'NNW', 'ESE', 'NW', 'N', 'W', 'WNW', 'SSE', 'E', 'ESE', 'NE', 'WNW', 'SSE', 'ESE', 'NE', 'E', 'ENE', 'ENE', 'SSE', 'SSE', 'SE', 'E', 'S', 'E', 'E', 'E', 'E', 'NE', 'NE', 'ENE', 'NE', 'ENE', 'ESE', 'SSE', 'ESE', 'ENE', 'ENE', 'ENE', 'E', 'NE', 'NW', 'ENE', 'E', 'E', 'SSE', 'ENE', 'ENE', 'ENE', 'NE', 'E', 'SSW', 'ENE', 'NNW', 'S', 'SE', 'ESE', 'ENE', 'E', 'ENE', 'S', 'S', 'SE', 'ESE', 'E', 'E', 'SE', 'NE', 'SE', 'SE', 'SSE', 'SSE', 'E', 'NNE', 'E', 'WNW', 'ENE', 'WNW', 'E', 'SE', 'E', 'ESE', 'E', 'E', 'NE', 'NW', 'ENE', 'ESE', 'E', 'NE', 'S', 'SE', 'SE', 'SE', 'SSE', 'ESE', 'ESE', 'E', 'ENE', 'W', 'WNW', 'S', 'S', 'SSW', 'E', 'NE', 'E', 'SE', 'S', 'WNW', 'SSW', 'S', 'SSW', 'S', 'ESE', 'WSW', 'SSW', 'S', 'W', 'WSW', 'W', 'WSW', 'W', 'ENE', 'S', 'E', 'ENE', 'E', 'E', 'NE', 'NW', 'SSE', 'SSW', 'S', 'S', 'S', 'SSW', 'SSE', 'ESE', 'ESE', 'SE', 'WNW', 'W', 'W', 'SSE', 'W', 'W', 'W', 'SW', 'SSW', 'SSE', 'SE', 'SSE', 'SE', 'SSW', 'WSW', 'W', 'WNW', 'WNW', 'WSW', 'WSW', 'WSW', 'NE', 'E', 'W', 'SSE', 'S', 'S', 'SSE', 'SSW', 'E', 'N', 'NW', 'W', 'NW', 'WSW', 'W', 'WSW', 'NW', 'W', 'WNW', 'W', 'S', 'S', 'E', 'ESE', 'WNW', 'W', 'SSW', 'SW', 'WSW', 'SSW', 'W', 'SSE', 'SW', 'S', 'N', 'ENE', 'SE', 'S', 'E', 'NE', 'ENE', 'NE', 'NNW', 'NNE', 'N', 'W', 'W', 'WNW', 'S', 'SSW', 'E', 'E', 'ESE', 'ENE', 'N', 'W', 'SSE', 'SE', 'SSE', 'SE', 'ENE', 'ENE', 'NE', 'E', 'E', 'ENE', 'S', 'ESE', 'E', 'ESE', 'S', 'NE', 'NE', 'NE', 'NNE', 'ESE', 'E', 'S', 'WSW', 'SW', 'ESE', 'E', 'WNW', 'E', 'ENE', 'E', 'SSE', 'NE', 'WNW', 'E', 'ENE', 'W', 'ESE', 'ESE', 'ESE', 'NE', 'ENE', 'WNW', 'W', 'SE', 'SSE', 'S', 'SSE', 'E', 'NE', 'E', 'SSE', 'SW', 'E', 'ESE', 'ESE', 'E', 'ENE', 'ENE', 'SE', 'SE', 'E', 'ENE', 'ENE', 'ENE', 'E', 'ENE', 'NNW', 'SSE', 'SE', 'E', 'ENE', 'ESE', 'E', 'SE', 'ESE', 'SE', 'ESE', 'ESE', 'NE', 'NNE', 'E', 'NNE', 'E', 'SW', 'E', 'E', 'E', 'SSW', 'ESE', 'E', 'NNE', 'E', 'NE', 'SSE', 'SSE', 'ESE', 'ESE', 'ENE', 'WSW', 'NE', 'NE', 'NW', 'SSE', 'S', 'E', 'SSE', 'SSW', 'SE', 'ESE', 'E', 'E', 'E', 'NNE', 'SSE', 'SSE', 'S', 'ESE', 'SE', 'E', 'NE', 'NNE', 'SE', 'ESE', 'ENE', 'E', 'E', 'NE', 'ENE', 'S', 'S', 'SSE', 'ESE', 'E', 'ENE', 'ENE', 'NE', 'E', 'E', 'SSE', 'ENE', 'NNE', 'ESE', 'E', 'W', 'SE', 'E', 'E', 'ESE', 'E', 'E', 'E', 'E', 'NNE', 'SE', 'ESE', 'SSE', 'E', 'E', 'ESE', 'E', 'NE', 'NNW', 'SE', 'ESE', 'SE', 'WSW', 'ESE', 'E', 'SSW', 'ESE', 'ESE', 'E', 'NE', 'W', 'E', 'ESE', 'ESE', 'ENE', 'NE', 'ENE', 'SSE', 'E', 'SE', 'S', 'SE', 'ENE', 'E', 'ENE', 'NE', 'ENE', 'ESE', 'SSW', 'ENE', 'SE', 'NNE', 'NE', 'SE', 'SSE', 'S', 'WSW', 'W', 'SE', 'E', 'ENE', 'E', 'E', 'NE', 'ENE', 'S', 'SSW', 'SE', 'E', 'NE', 'SSW', 'WNW', 'S', 'SE', 'ENE', 'E', 'ENE', 'E', 'ESE', 'E', 'E', 'ESE', 'NE', 'NE', 'E', 'ENE', 'SSE', 'NE', 'W', 'SSW', 'SSW', 'SE', 'ENE', 'ENE', 'ENE', 'SSE', 'SE', 'ENE', 'E', 'ENE', 'SSE', 'N', 'W', 'W', 'SSE', 'ESE', 'NE', 'SSE', 'ENE', 'NE', 'ENE', 'ESE', 'ESE', 'S', 'NE', 'SW', 'WNW', 'E', 'ESE', 'E', 'WSW', 'W', 'SSW', 'SSE', 'SSE', 'E', 'E', 'WNW', 'SSW', 'NNE', 'WNW', 'N', 'W', 'NNW', 'W', 'S', 'S', 'S', 'SSE', 'SSE', 'ESE', 'ESE', 'SSE', 'WNW', 'W', 'SSE', 'SSE', 'ENE', 'NNW', 'WSW', 'SW', 'S', 'W', 'E', 'NNE', 'NNE', 'W', 'W', 'WSW', 'NE', 'NNE', 'WNW', 'WSW', 'WSW', 'S', 'SE', 'ESE', 'ENE', 'NW', 'W', 'WSW', 'S', 'SSW', 'SSW', 'S', 'SW', 'E', 'NE', 'NNE', 'NW', 'NNE', 'N', 'WNW', 'WSW', 'ENE', 'N', 'SW', 'SSW', 'SSW', 'SSW', 'S', 'SSW', 'ENE', 'NE', 'W', 'S', 'S', 'SSW', 'SSW', 'S', 'SE', 'NW', 'NW', 'W', 'SW', 'WNW', 'W', 'WSW', 'SSW', 'N', 'E', 'WNW', 'W', 'E', 'E', 'ENE', 'ENE', 'NW', 'WNW', 'WNW', 'E', 'WNW', 'W', 'S', 'ENE', 'E', 'E', 'NNW', 'WNW', 'WNW', 'WSW', 'SSE', 'NE', 'S', 'ESE', 'SE', 'NE', 'SSE', 'E', 'ESE', 'E', 'ENE', 'SE', 'NNE', 'E', 'ESE', 'ENE', 'NE', 'NW', 'ESE', 'E', 'E', 'E', 'WNW', 'SSE', 'NE', 'SSE', 'ESE', 'ESE', 'E', 'SSW', 'SE', 'ESE', 'NE', 'E', 'ESE', 'NE', 'E', 'S', 'WNW', 'S', 'ESE', 'NE', 'E', 'E', 'SE', 'E', 'E', 'ENE', 'ESE', 'E', 'SSE', 'ESE', 'ENE', 'NE', 'NE', 'ENE', 'E', 'ENE', 'SSE', 'ESE', 'NE', 'SSE', 'E', 'ENE', 'SSE', 'E', 'NE', 'SSW', 'SE', 'NE', 'SE', 'ESE', 'E', 'E', 'ESE', 'SE', 'ESE', 'NE', 'ENE', 'E', 'SE', 'E', 'ENE', 'ENE', 'E', 'E', 'NW', 'SSE', 'ENE', 'ENE', 'S', 'SSE', 'SSE', 'E', 'E', 'E', 'E', 'SSE', 'ESE', 'NE', 'NE', 'S', 'ESE', 'E', 'NE', 'NNE', 'ENE', 'SSE', 'ESE', 'NE', 'SSE', 'SSE', 'ESE', 'ESE', 'ENE', 'ENE', 'NE', 'E', 'ENE', 'ENE', 'E', 'E', 'NE', 'SSW', 'SSW', 'E', 'SSW', 'ESE', 'ESE', 'E', 'NE', 'NNW', 'E', 'E', 'S', 'ENE', 'ENE', 'E', 'SSE', 'ENE', 'S', 'E', 'ESE', 'S', 'SE', 'ENE', 'SE', 'E', 'ESE', 'ESE', 'ENE', 'ENE', 'ENE', 'NE', 'ENE', 'E', 'S', 'SSE', 'SSE', 'SSW', 'SSE', 'ESE', 'W', 'ESE', 'ESE', 'ESE', 'SW', 'ENE', 'WNW', 'ESE', 'SSE', 'SE', 'S', 'ENE', 'SSE', 'S', 'S', 'SSE', 'E', 'ENE', 'SE', 'ENE', 'ENE', 'NNE', 'SE', 'WNW', 'W', 'WSW', 'W', 'W', 'WSW', 'SW', 'SSW', 'SE', 'SSE', 'SSE', 'NE', 'SSE', 'E', 'ENE', 'ENE', 'NNE', 'N', 'SW', 'SSE', 'S', 'ENE', 'NNE', 'SSW', 'SE', 'ENE', 'WNW', 'WNW', 'W', 'WNW', 'WSW', 'SSW', 'S', 'SW', 'S', 'SSW', 'SSW', 'SSW', 'SSW', 'SSW', 'WNW', 'W', 'SE', 'ESE', 'ENE', 'SSE', 'SSW', 'E', 'WNW', 'NNE', 'NNW', 'W', 'WNW', 'WSW', 'SSE', 'SSW', 'SSE', 'E', 'WNW', 'E', 'NE', 'NNW', 'NE', 'E', 'NE', 'N', 'NW', 'WNW', 'W', 'WSW', 'SSW', 'E', 'WNW', 'E', 'E', 'N', 'ENE', 'S', 'ESE', 'W', 'W', 'WSW', 'WNW', 'WNW', 'ESE', 'SSW', 'NW', 'NW', 'E', 'W', 'WNW', 'WNW', 'S', 'ENE', 'W', 'NNW', 'WNW', 'WSW', 'W', 'WNW', 'WNW', 'ESE', 'E', 'WNW', 'ESE', 'SSE', 'NE', 'ENE', 'SE', 'E', 'NE', 'ENE', 'NE', 'WNW', 'E', 'ENE', 'ESE', 'NE', 'WNW', 'WSW', 'SW', 'ENE', 'S', 'ENE', 'ENE', 'NNW', 'W', 'WNW', 'SW', 'ESE', 'ENE', 'E', 'ENE', 'NE', 'WNW', 'E', 'W', 'E', 'NE', 'WNW', 'ENE', 'S', 'ESE', 'E', 'E', 'SSE', 'SSE', 'NE', 'WNW', 'ENE', 'ENE', 'WNW', 'ESE', 'NE', 'ENE', 'WNW', 'E', 'E', 'ENE', 'ESE', 'ESE', 'W', 'WSW', 'E', 'ESE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'ESE', 'E', 'ENE', 'NNE', 'SE', 'SE', 'SSE', 'E', 'E', 'E', 'SE', 'SSE', 'SSE', 'SSE', 'SSE', 'E', 'NE', 'NNE', 'NE', 'SE', 'S', 'SSE', 'E', 'NE', 'S', 'SE', 'E', 'ENE', 'NE', 'E', 'W', 'ESE', 'E', 'NE', 'NE', 'ESE', 'E', 'ENE', 'ENE', 'SSE', 'E', 'ENE', 'ENE', 'ENE', 'NE', 'E', 'SSE', 'E', 'ESE', 'SSE', 'NE', 'ESE', 'ENE', 'NE', 'SSE', 'ENE', 'ESE', 'NE', 'WSW', 'ENE', 'E', 'NE', 'SE', 'SE', 'SE', 'ENE', 'ENE', 'NE', 'ESE', 'ESE', 'E', 'NE', 'ENE', 'NE', 'ENE', 'SE', 'ESE', 'E', 'SSE', 'E', 'NE', 'SSE', 'E', 'ENE', 'NE', 'NE', 'NE', 'NE', 'ESE', 'NE', 'NE', 'S', 'SSE', 'ESE', 'ENE', 'NE', 'NE', 'S', 'SE', 'ESE', 'E', 'ENE', 'ENE', 'SSE', 'ESE', 'E', 'W', 'ESE', 'SE', 'ESE', 'SE', 'E', 'NE', 'ENE', 'SSE', 'SSE', 'ENE', 'S', 'SE', 'E', 'NE', 'S', 'E', 'ESE', 'E', 'E', 'NE', 'E', 'SE', 'ENE', 'NE', 'WNW', 'ENE', 'NE', 'SSE', 'E', 'ENE', 'ENE', 'ENE', 'W', 'ESE', 'E', 'N', 'WSW', 'SSE', 'ESE', 'ESE', 'ENE', 'E', 'E', 'S', 'SSE', 'SW', 'SSE', 'E', 'E', 'E', 'SW', 'SSW', 'S', 'S', 'S', 'S', 'SSE', 'WNW', 'SSE', 'ENE', 'ESE', 'W', 'ESE', 'WNW', 'ENE', 'WNW', 'S', 'NNE', 'NE', 'SSW', 'ESE', 'W', 'W', 'W', 'NW', 'ENE', 'S', 'SSE', 'E', 'N', 'SSW', 'S', 'E', 'NE', 'E', 'ENE', 'ENE', 'W', 'WNW', 'WNW', 'ESE', 'W', 'WNW', 'SSW', 'ESE', 'ENE', 'NNE', 'WNW', 'S', 'S', 'ENE', 'W', 'WNW', 'WNW', 'SSE', 'SSW', 'SSW', 'SSW', 'SSW', 'SE', 'SE', 'SSE', 'NNE', 'N', 'W', 'WSW', 'WNW', 'SSW', 'ESE', 'NE', 'W', 'W', 'NNE', 'N', 'WNW', 'W', 'WNW', 'NNE', 'NW', 'NW', 'WSW', 'W', 'SSE', 'ENE', 'ESE', 'WNW', 'WSW', 'WSW', 'E', 'NNE', 'W', 'W', 'WSW', 'S', 'SSW', 'E', 'W', 'WNW', 'WSW', 'SSW', 'S', 'SSE', 'SE', 'ESE', 'N', 'N', 'WNW', 'ESE', 'WNW', 'NNE', 'WNW', 'NW', 'W', 'S', 'ESE', 'E', 'SSE', 'NE', 'SE', 'ESE', 'NE', 'WNW', 'S', 'SW', 'SSE', 'SE', 'ESE', 'ESE', 'WNW', 'SSW', 'SW', 'S', 'S', 'SSE', 'E', 'E', 'ESE', 'SSW', 'SE', 'SSE', 'SSW', 'SW', 'ESE', 'ENE', 'S', 'SSW', 'SSW', 'S', 'SE', 'SE', 'NE', 'NE', 'WSW', 'E', 'SE', 'E', 'E', 'ENE', 'SE', 'E', 'SSE', 'ESE', 'E', 'NE', 'NE', 'SSE', 'SE', 'SE', 'NE', 'WNW', 'NW', 'SE', 'NE', 'E', 'NE', 'E', 'ENE', 'ESE', 'ESE', 'ENE', 'ENE', 'E', 'NE', 'ENE', 'WSW', 'SSW', 'E', 'S', 'E', 'NE', 'S', 'E', 'NE', 'E', 'ENE', 'SSE', 'SSE', 'W', 'W', 'E', 'ENE', 'ESE', 'ESE', 'ENE', 'NE', 'SE', 'E', 'NE', 'SSE', 'SE', 'SE', 'E', 'ENE', 'ESE', 'SSE', 'W', 'E', 'SSE', 'E', 'ENE', 'E', 'E', 'E', 'E', 'ESE', 'ENE', 'NE', 'NE', 'NNE', 'ENE', 'ENE', 'NE', 'E', 'E', 'WSW', 'ESE', 'E', 'SSW', 'ESE', 'ENE', 'ENE', 'NE', 'SE', 'E', 'SE', 'E', 'E', 'NE', 'NNE', 'S', 'NE', 'SE', 'ESE', 'E', 'NE', 'E', 'E', 'NE', 'ESE', 'NE', 'NE', 'ESE', 'E', 'NE', 'NE', 'ENE', 'ENE', 'S', 'S', 'ENE', 'WNW', 'ESE', 'E', 'E', 'ESE', 'SE', 'NE', 'E', 'E', 'NE', 'NE', 'E', 'S', 'E', 'SSW', 'S', 'WSW', 'ESE', 'ESE', 'S', 'SE', 'SSE', 'ESE', 'ESE', 'ENE', 'E', 'SE', 'E', 'E', 'ESE', 'ESE', 'NE', 'ENE', 'NE', 'ENE', 'E', 'E', 'E', 'ESE', 'E', 'E', 'S', 'SSE', 'E', 'ESE', 'NE', 'E', 'SE', 'E', 'E', 'SSE', 'W', 'ENE', 'SSE', 'E', 'E', 'E', 'SE', 'S', 'E', 'S', 'E', 'NE', 'ESE', 'ESE', 'S', 'SE', 'E', 'NE', 'SE', 'SSE', 'WNW', 'W', 'ESE', 'ENE', 'ENE', 'E', 'ENE', 'E', 'SSW', 'SE', 'ESE', 'NW', 'WNW', 'WSW', 'S', 'S', 'E', 'SSE', 'SSE', 'ENE', 'ENE', 'ENE', 'E', 'N', 'SSE', 'SSE', 'S', 'SSW', 'SE', 'E', 'ENE', 'SW', 'SSE', 'S', 'SE', 'SE', 'ESE', 'NE', 'S', 'SSE', 'NNW', 'WSW', 'WSW', 'WNW', 'NW', 'WNW', 'WSW', 'W', 'SW', 'W', 'SSW', 'S', 'ESE', 'SE', 'NE', 'ENE', 'S', 'S', 'S', 'ESE', 'NNW', 'SSE', 'WNW', 'ENE', 'WNW', 'WNW', 'NW', 'SW', 'S', 'SSW', 'ENE', 'SSW', 'W', 'N', 'WNW', 'WSW', 'SSW', 'N', 'NNW', 'NNW', 'E', 'W', 'NNE', 'W', 'SSW', 'SSW', 'SSW', 'SSW', 'NNE', 'NNE', 'ESE', 'SSE', 'NNE', 'W', 'ESE', 'E', 'ENE', 'NW', 'WSW', 'SSE', 'WNW', 'ESE', 'W', 'SSW', 'SSE', 'E', 'WNW', 'NNW', 'WNW', 'WSW', 'W', 'ENE', 'W', 'SW', 'SSW', 'S', 'SE', 'NE', 'NNW', 'ESE', 'E', 'WNW', 'WNW', 'WSW', 'S', 'ESE', 'E', 'WNW', 'NW', 'NW', 'WSW', 'SSE', 'WNW', 'S', 'SSE', 'SSE', 'E', 'E', 'WNW', 'WNW', 'SW', 'E', 'SSE', 'NE', 'NW', 'SSE', 'E', 'NE', 'NE', 'N', 'NNW', 'SSE', 'W', 'S', 'NW', 'S', 'WNW', 'S', 'SSE', 'ESE', 'ENE', 'WSW', 'S', 'SE', 'ENE', 'W', 'W', 'SSE', 'SSE', 'NE', 'E', 'E', 'NE', 'NNW', 'ESE', 'SE', 'S', 'ESE', 'E', 'NE', 'S', 'SSW', 'SSW', 'SSE', 'SSE', 'S', 'ESE', 'NE', 'ESE', 'E', 'ENE', 'E', 'W', 'E', 'ENE', 'SE', 'E', 'NE', 'E', 'ENE', 'NE', 'ESE', 'NE', 'ENE', 'E', 'ESE', 'E', 'ENE', 'ENE', 'W', 'SSW', 'SSW', 'ENE', 'NE', 'WSW', 'SSE', 'E', 'E', 'NE', 'NE', 'NE', 'E', 'SE', 'E', 'NE', 'NE', 'ESE', 'SSE', 'E', 'ENE', 'ESE', 'ENE', 'NE', 'ESE', 'S', 'ESE', 'NE', 'W', 'E', 'WNW', 'SE', 'ENE', 'SE', 'NE', 'W', 'ESE', 'NE', 'NE', 'E', 'NE', 'S', 'ESE', 'E', 'ENE', 'E', 'ENE', 'ENE', 'E', 'WNW', 'ESE', 'NE', 'E', 'ENE', 'N', 'E', 'ENE', 'NE', 'S', 'NE', 'ESE', 'ESE', 'E', 'NE', 'S', 'SSE', 'ESE', 'E', 'E', 'E', 'ESE', 'SE', 'ESE', 'SE', 'SSE', 'SSW', 'E', 'E', 'ENE', 'E', 'SSE', 'E', 'S', 'SSE', 'ESE', 'E', 'ENE', 'E', 'ENE', 'E', 'S', 'ESE', 'E', 'ENE', 'NE', 'ENE', 'ESE', 'ESE', 'WNW', 'SE', 'ESE', 'E', 'S', 'SSE', 'ESE', 'ESE', 'ESE', 'SE', 'ENE', 'E', 'E', 'NE', 'SSE', 'ESE', 'SE', 'ESE', 'ESE', 'ENE', 'S', 'ESE', 'ENE', 'ENE', 'ENE', 'E', 'SE', 'ESE', 'E', 'SE', 'ENE', 'ENE', 'NE', 'NE', 'NE', 'NE', 'NE', 'ENE', 'NE', 'SSE', 'ENE', 'E', 'ENE', 'SE', 'S', 'SSW', 'E', 'NNE', 'SE', 'S', 'SSW', 'S', 'ESE', 'E', 'WNW', 'ENE', 'E', 'ESE', 'SSW', 'NW', 'SSE', 'ENE', 'SW', 'ESE', 'ESE', 'NNE', 'NNE', 'SSE', 'E', 'SE', 'E', 'SE', 'SSE', 'ESE', 'NE', 'NE', 'ENE', 'SSE', 'SSE', 'ESE', 'E', 'NE', 'S', 'SSW', 'ESE', 'ESE', 'E', 'NE', 'E', 'NE', 'WNW', 'N', 'NE', 'WNW', 'E', 'E', 'ESE', 'ENE', 'E', 'NNE', 'WNW', 'WSW', 'WNW', 'WNW', 'ENE', 'N', 'NE', 'WNW', 'N', 'WNW', 'SE', 'E', 'E', 'SSW', 'WSW', 'E', 'NW', 'W', 'W', 'W', 'WSW', 'SE', 'ENE', 'SSE', 'S', 'NE', 'ENE', 'WSW', 'WNW', 'WNW', 'WNW', 'WNW', 'W', 'S', 'E', 'WNW', 'E', 'N', 'N', 'ESE', 'ESE', 'NW', 'WNW', 'W', 'NNW', 'W', 'S', 'W', 'SW', 'SSW', 'N', 'W', 'ENE', 'SE', 'NW', 'WSW', 'WSW', 'SSW', 'S', 'E', 'N', 'NW', 'WSW', 'W', 'E', 'SSE', 'ESE', 'WNW', 'NE', 'WSW', 'NW', 'NW', 'W', 'NW', 'WNW', 'E', 'WSW', 'WNW', 'WNW', 'ESE', 'WNW', 'W', 'S', 'SSE', 'SSW', 'SE', 'ESE', 'E', 'NE', 'NNW', 'WSW', 'E', 'WSW', 'SE', 'NE', 'ENE', 'ENE', 'ENE', 'NNW', 'WSW', 'WNW', 'W', 'SSW', 'ESE', 'S', 'S', 'ENE', 'ESE', 'W', 'ENE', 'NNW', 'NE', 'SSE', 'WNW', 'ESE', 'ENE', 'ENE', 'E', 'NE', 'NE', 'W', 'ESE', 'E', 'S', 'N', 'WNW', 'W', 'NE', 'W', 'W', 'NE', 'NE', 'W', 'SSW', 'ESE', 'SE', 'E', 'WSW', 'E', 'N', 'NW', 'W', 'ENE', 'WNW', 'W', 'WSW', 'WSW', 'W', 'SSE', 'NE', 'WSW', 'SE', 'E', 'S', 'E', 'NE', 'NE', 'NNW', 'WNW', 'NW', 'NE', 'NE', 'S', 'S', 'SSE', 'NE', 'E', 'SSE', 'ESE', 'NE', 'ENE', 'E', 'E', 'E', 'ENE', 'NE', 'WSW', 'ESE', 'NE', 'SSE', 'SSE', 'E', 'ESE', 'E', 'W', 'SSE', 'ESE', 'ESE', 'E', 'NE', 'SE', 'E', 'ENE', 'ENE', 'SE', 'ESE', 'NE', 'ESE', 'E', 'SE', 'E', 'ENE', 'ESE', 'ESE', 'E', 'E', 'NE', 'E', 'NE', 'WSW', 'ENE', 'E', 'ENE', 'NE', 'WSW', 'SSE', 'ESE', 'WNW', 'SE', 'NE', 'ESE', 'ESE', 'ENE', 'NE', 'ENE', 'NE', 'NE', 'ESE', 'NNE', 'ENE', 'ENE', 'SE', 'E', 'SSE', 'SSE', 'ESE', 'E', 'E', 'NE', 'ENE', 'E', 'E', 'ESE', 'E', 'NE', 'ESE', 'E', 'NE', 'ENE', 'SSE', 'ENE', 'NNW', 'SE', 'E', 'NE', 'W', 'S', 'SSE', 'ESE', 'ENE', 'SSE', 'NE', 'SSE', 'SSE', 'SE', 'NE', 'E', 'ENE', 'SE', 'S', 'E', 'NE', 'ENE', 'E', 'SSE', 'ESE', 'SSE', 'E', 'ENE', 'NE', 'ESE', 'ESE', 'WNW', 'ESE', 'NE', 'ENE', 'ESE', 'SSW', 'SSW', 'SE', 'E', 'ESE', 'E', 'SE', 'S', 'SW', 'SSW', 'SSW', 'SE', 'SSE', 'S', 'ESE', 'ENE', 'E', 'ENE', 'E', 'NE', 'S', 'ESE', 'ENE', 'NE', 'E', 'E', 'SSW', 'SSW', 'NE', 'E', 'NE', 'S', 'E', 'SSW', 'S', 'ESE', 'SSE', 'ESE', 'SSE', 'ESE', 'ENE', 'E', 'NE', 'NNE', 'W', 'SSW', 'SSW', 'SSE', 'SE', 'ESE', 'WSW', 'ESE', 'E', 'SE', 'ENE', 'E', 'ENE', 'ESE', 'E', 'NW', 'S', 'S', 'ESE', 'SE', 'N', 'SSW', 'SSE', 'ESE', 'ENE', 'N', 'ESE', 'SE', 'S', 'SE', 'SSE', 'ESE', 'NE', 'SE', 'SSW', 'SSE', 'E', 'E', 'NNE', 'WNW', 'ESE', 'E', 'ENE', 'WSW', 'E', 'S', 'ENE', 'NW', 'WSW', 'WNW', 'SSW', 'SSW', 'SSW', 'S', 'SSE', 'WSW', 'S', 'S', 'S', 'SSE', 'SSE', 'W', 'SSE', 'SSE', 'ENE', 'ENE', 'WSW', 'SSW', 'SSW', 'S', 'SSW', 'SSE', 'ESE', 'N', 'W', 'W'], 'WindSpeed9am': [17, 9, 17, 22, 11, 9, 15, 7, 19, 11, 9, 7, 24, 15, 19, 11, 13, 13, 7, 13, 4, 11, 20, 11, 15, 2, 0, 20, 24, 19, 13, 15, 9, 19, 11, 13, 9, 9, 9, 2, 7, 6, 9, 2, 7, 4, 11, 7, 6, 26, 24, 9, 7, 4, 0, 20, 13, 15, 22, 9, 20, 6, 26, 24, 13, 13, 11, 20, 13, 15, 15, 11, 11, 19, 20, 15, 17, 4, 22, 15, 9, 9, 6, 19, 15, 20, 20, 24, 15, 11, 19, 19, 22, 15, 9, 22, 24, 17, 11, 13, 11, 11, 20, 13, 15, 20, 19, 22, 24, 19, 20, 17, 13, 17, 20, 15, 26, 19, 19, 17, 19, 9, 17, 19, 24, 15, 19, 17, 13, 13, 6, 11, 20, 30, 24, 19, 11, 13, 13, 19, 15, 22, 13, 19, 17, 28, 24, 20, 13, 19, 0, 26, 17, 20, 11, 15, 9, 11, 15, 11, 24, 17, 4, 0, 20, 13, 15, 13, 4, 6, 26, 19, 22, 19, 15, 24, 11, 20, 22, 19, 19, 17, 28, 20, 13, 22, 15, 20, 17, 19, 19, 33, 19, 22, 22, 22, 22, 17, 20, 22, 2, 7, 15, 24, 24, 15, 19, 13, 19, 13, 15, 7, 19, 22, 20, 28, 22, 15, 15, 13, 17, 15, 11, 4, 15, 28, 39, 15, 6, 0, 6, 9, 6, 17, 11, 6, 4, 7, 17, 19, 6, 9, 4, 15, 13, 11, 15, 22, 19, 17, 11, 6, 11, 6, 20, 20, 7, 7, 4, 6, 20, 26, 19, 24, 15, 17, 6, 6, 11, 11, 9, 17, 19, 11, 22, 22, 4, 9, 15, 24, 13, 2, 0, 6, 13, 13, 17, 20, 4, 22, 9, 15, 19, 31, 19, 19, 15, 7, 17, 24, 13, 13, 2, 6, 13, 20, 15, 13, 11, 19, 7, 35, 15, 13, 24, 33, 24, 13, 6, 13, 7, 26, 2, 22, 11, 17, 7, 4, 9, 4, 28, 9, 19, 11, 11, 13, 13, 6, 11, 6, 24, 22, 17, 19, 7, 7, 7, 7, 4, 26, 11, 15, 9, 11, 15, 9, 11, 15, 9, 9, 4, 4, 4, 7, 13, 4, 0, 6, 6, 6, 9, 9, 20, 6, 26, 19, 24, 30, 19, 19, 9, 19, 19, 2, 0, 13, 0, 11, 4, 11, 13, 7, 9, 0, 19, 4, 30, 15, 11, 11, 6, 17, 17, 4, 7, 2, 6, 17, 20, 11, 13, 0, 6, 11, 7, 6, 4, 2, 17, 9, 9, 7, 20, 28, 22, 0, 24, 9, 30, 11, 11, 9, 15, 0, 15, 19, 11, 15, 13, 11, 20, 26, 33, 9, 15, 9, 11, 20, 28, 19, 20, 17, 17, 22, 7, 19, 13, 11, 20, 20, 19, 11, 15, 19, 22, 17, 15, 24, 15, 19, 15, 33, 15, 15, 15, 15, 15, 15, 15, 17, 20, 19, 24, 17, 13, 6, 15, 17, 17, 13, 13, 17, 35, 26, 22, 9, 6, 15, 17, 19, 11, 11, 15, 4, 9, 13, 7, 13, 15, 7, 11, 17, 28, 7, 13, 44, 15, 20, 19, 19, 15, 13, 13, 13, 9, 9, 15, 17, 24, 20, 15, 9, 15, 15, 15, 4, 20, 15, 4, 19, 11, 17, 22, 9, 20, 20, 13, 11, 17, 13, 22, 22, 17, 11, 13, 19, 9, 20, 13, 6, 22, 19, 13, 13, 13, 7, 13, 26, 31, 13, 4, 2, 20, 30, 20, 13, 11, 11, 11, 19, 13, 17, 7, 20, 20, 15, 11, 20, 30, 9, 9, 4, 17, 9, 9, 13, 24, 30, 31, 17, 15, 39, 30, 17, 9, 15, 15, 22, 6, 13, 22, 20, 26, 15, 15, 15, 4, 26, 20, 11, 33, 15, 4, 7, 9, 15, 9, 7, 17, 7, 31, 22, 11, 17, 19, 17, 9, 11, 13, 24, 20, 9, 19, 4, 15, 17, 26, 6, 17, 6, 20, 4, 9, 9, 4, 11, 28, 13, 4, 15, 17, 7, 13, 19, 22, 17, 2, 26, 2, 11, 11, 9, 17, 4, 11, 7, 15, 11, 15, 13, 13, 11, 15, 15, 17, 2, 17, 20, 13, 17, 20, 2, 2, 15, 15, 7, 13, 15, 13, 13, 2, 2, 11, 6, 19, 22, 9, 11, 0, 15, 15, 7, 6, 7, 26, 7, 2, 6, 19, 0, 7, 26, 19, 13, 19, 26, 28, 11, 31, 19, 7, 4, 9, 4, 2, 17, 9, 11, 22, 9, 19, 19, 13, 4, 7, 24, 9, 15, 7, 2, 4, 19, 17, 11, 0, 20, 2, 19, 11, 11, 20, 24, 19, 22, 13, 11, 15, 13, 9, 6, 15, 9, 9, 13, 17, 7, 9, 17, 6, 7, 4, 24, 24, 13, 17, 13, 9, 0, 15, 17, 15, 9, 15, 30, 17, 15, 15, 9, 11, 6, 13, 15, 11, 13, 11, 20, 24, 19, 15, 24, 20, 13, 19, 15, 2, 7, 24, 20, 20, 15, 13, 11, 28, 24, 19, 20, 17, 19, 22, 20, 19, 13, 22, 19, 15, 11, 17, 15, 15, 11, 15, 22, 15, 19, 19, 26, 22, 28, 24, 22, 6, 26, 19, 20, 22, 22, 17, 11, 11, 19, 15, 17, 15, 13, 20, 20, 22, 13, 11, 20, 15, 24, 22, 20, 7, 22, 19, 17, 13, 19, 7, 20, 24, 24, 26, 20, 15, 19, 19, 28, 20, 22, 11, 15, 13, 4, 6, 22, 7, 11, 24, 15, 15, 17, 19, 26, 20, 15, 2, 19, 35, 26, 11, 22, 24, 26, 13, 22, 11, 20, 22, 6, 17, 17, 19, 20, 20, 4, 9, 15, 15, 15, 15, 15, 15, 15, 15, 2, 9, 20, 15, 13, 28, 24, 20, 17, 11, 13, 15, 11, 13, 13, 9, 6, 13, 19, 7, 22, 13, 46, 24, 11, 11, 6, 7, 22, 13, 13, 17, 11, 9, 19, 22, 31, 13, 15, 17, 7, 13, 7, 22, 6, 7, 13, 9, 13, 17, 7, 26, 4, 17, 17, 13, 6, 9, 30, 11, 30, 17, 17, 6, 7, 19, 15, 13, 17, 13, 6, 15, 11, 4, 6, 24, 15, 41, 26, 19, 9, 19, 0, 20, 15, 11, 4, 7, 7, 13, 9, 17, 20, 6, 20, 9, 11, 22, 20, 20, 13, 15, 19, 9, 11, 13, 13, 17, 20, 4, 13, 20, 11, 4, 11, 9, 20, 11, 15, 2, 7, 13, 11, 7, 24, 2, 13, 11, 13, 7, 7, 30, 11, 20, 9, 15, 11, 20, 15, 6, 17, 22, 13, 17, 7, 4, 17, 13, 9, 19, 20, 9, 22, 17, 9, 7, 6, 6, 7, 4, 9, 11, 13, 11, 17, 19, 24, 22, 26, 9, 19, 28, 28, 28, 17, 15, 4, 13, 22, 19, 20, 15, 24, 24, 19, 22, 20, 22, 26, 9, 26, 13, 28, 24, 17, 22, 19, 15, 15, 17, 13, 15, 7, 33, 20, 22, 22, 20, 30, 39, 22, 11, 20, 13, 20, 7, 13, 22, 22, 19, 20, 28, 17, 22, 37, 31, 9, 17, 19, 11, 20, 19, 9, 20, 19, 13, 28, 20, 17, 7, 19, 11, 17, 28, 28, 20, 44, 19, 24, 26, 22, 19, 20, 19, 26, 13, 11, 22, 22, 24, 22, 19, 22, 22, 13, 19, 19, 22, 17, 17, 15, 15, 19, 13, 15, 6, 0, 9, 17, 19, 9, 15, 22, 20, 7, 17, 13, 17, 28, 28, 24, 26, 20, 17, 17, 9, 19, 11, 20, 4, 15, 15, 6, 17, 15, 13, 4, 20, 28, 2, 15, 31, 28, 19, 11, 6, 19, 13, 9, 6, 11, 22, 17, 11, 15, 15, 31, 24, 9, 9, 19, 28, 2, 30, 17, 19, 20, 7, 9, 9, 11, 13, 28, 17, 2, 20, 2, 15, 24, 4, 13, 6, 11, 2, 2, 7, 26, 11, 19, 11, 4, 6, 19, 15, 15, 19, 7, 11, 6, 9, 9, 9, 11, 15, 20, 11, 13, 9, 4, 15, 9, 9, 7, 19, 19, 24, 28, 26, 13, 9, 17, 22, 22, 13, 20, 24, 15, 11, 4, 9, 2, 2, 20, 19, 20, 13, 15, 15, 11, 9, 20, 9, 9, 9, 15, 15, 17, 24, 20, 15, 13, 13, 17, 15, 15, 15, 11, 24, 11, 7, 22, 17, 15, 22, 15, 11, 28, 13, 20, 2, 19, 13, 31, 30, 6, 7, 13, 30, 19, 20, 17, 19, 26, 17, 15, 13, 11, 24, 13, 17, 17, 17, 7, 15, 9, 6, 15, 13, 7, 13, 6, 9, 20, 13, 11, 11, 2, 11, 6, 6, 20, 17, 17, 26, 11, 17, 17, 33, 30, 13, 11, 13, 4, 13, 7, 13, 6, 24, 15, 19, 6, 13, 17, 11, 22, 13, 2, 9, 9, 15, 19, 13, 9, 9, 13, 11, 2, 6, 15, 17, 28, 31, 24, 17, 17, 4, 19, 11, 20, 9, 2, 9, 19, 20, 13, 24, 22, 19, 15, 17, 20, 9, 15, 15, 20, 20, 24, 13, 22, 15, 22, 9, 17, 31, 20, 24, 22, 19, 17, 24, 19, 20, 20, 11, 7, 24, 26, 22, 20, 9, 19, 20, 15, 13, 11, 13, 15, 28, 24, 20, 24, 15, 20, 22, 13, 15, 11, 13, 15, 19, 13, 13, 2, 19, 17, 17, 11, 7, 19, 13, 19, 15, 28, 20, 28, 17, 17, 24, 19, 15, 9, 11, 9, 15, 13, 9, 24, 13, 20, 26, 22, 17, 20, 17, 17, 13, 15, 22, 17, 24, 26, 22, 26, 9, 22, 17, 2, 22, 17, 9, 31, 19, 26, 19, 30, 20, 19, 13, 9, 17, 31, 15, 19, 9, 26, 24, 20, 17, 19, 15, 28, 20, 30, 17, 11, 20, 20, 19, 19, 19, 9, 11, 13, 4, 11, 2, 26, 13, 4, 6, 22, 31, 11, 11, 13, 9, 22, 9, 17, 7, 7, 4, 35, 26, 13, 9, 6, 22, 15, 11, 22, 13, 30, 19, 11, 9, 6, 7, 13, 9, 2, 11, 9, 28, 6, 6, 9, 15, 2, 4, 9, 28, 13, 13, 19, 15, 19, 11, 13, 6, 17, 28, 9, 22, 13, 9, 7, 7, 6, 9, 6, 15, 9, 17, 7, 17, 9, 13, 9, 4, 24, 17, 4, 13, 13, 17, 6, 7, 2, 13, 19, 13, 2, 17, 20, 20, 11, 17, 6, 7, 11, 11, 19, 26, 30, 30, 22, 20, 6, 11, 9, 13, 7, 9, 13, 7, 7, 24, 11, 24, 20, 17, 13, 7, 20, 4, 9, 19, 9, 0, 2, 22, 13, 13, 13, 19, 22, 17, 9, 11, 9, 15, 15, 13, 13, 13, 17, 17, 9, 17, 13, 15, 20, 17, 15, 13, 15, 20, 20, 17, 17, 7, 13, 15, 15, 13, 19, 19, 15, 13, 13, 13, 17, 20, 22, 13, 9, 20, 15, 22, 24, 17, 20, 19, 22, 17, 11, 28, 22, 20, 22, 11, 15, 15, 9, 11, 20, 24, 24, 7, 15, 20, 19, 13, 13, 17, 13, 15, 17, 24, 24, 26, 26, 24, 26, 19, 26, 7, 17, 17, 31, 15, 9, 9, 11, 20, 20, 19, 17, 20, 13, 19, 19, 19, 17, 20, 17, 15, 11, 4, 9, 9, 7, 15, 17, 24, 17, 17, 17, 20, 15, 22, 7, 22, 13, 20, 24, 15, 7, 9, 11, 20, 17, 24, 20, 11, 13, 9, 13, 24, 24, 17, 20, 15, 7, 26, 20, 19, 20, 26, 17, 20, 15, 20, 17, 22, 22, 17, 19, 11, 13, 13, 13, 13, 13, 9, 33, 28, 15, 20, 17, 6, 6, 22, 20, 9, 13, 22, 11, 7, 2, 9, 17, 19, 13, 13, 6, 35, 17, 30, 15, 15, 9, 26, 9, 13, 15, 24, 13, 11, 28, 15, 9, 31, 15, 13, 4, 11, 20, 28, 20, 20, 28, 17, 15, 15, 0, 0, 0, 0, 0, 0, 0, 11, 11, 4, 9, 15, 31, 4, 20, 15, 2, 19, 22, 30, 17, 11, 15, 28, 9, 7, 6, 13, 13, 9, 13, 22, 6, 11, 11, 13, 4, 26, 13, 9, 6, 24, 13, 15, 9, 30, 2, 9, 9, 15, 17, 6, 28, 9, 11, 24, 6, 13, 9, 19, 39, 9, 9, 13, 6, 13, 17, 9, 17, 26, 11, 17, 4, 6, 9, 7, 7, 2, 9, 6, 7, 6, 11, 20, 15, 20, 20, 20, 7, 13, 17, 6, 13, 17, 17, 22, 26, 17, 26, 11, 11, 2, 9, 20, 4, 19, 11, 6, 2, 6, 13, 4, 11, 7, 20, 9, 24, 9, 6, 7, 24, 20, 2, 11, 11, 7, 4, 20, 13, 13, 6, 11, 9, 7, 15, 7, 7, 9, 15, 19, 13, 0, 6, 6, 6, 24, 11, 11, 2, 13, 15, 11, 15, 13, 11, 13, 11, 13, 9, 13, 13, 13, 11, 22, 26, 20, 20, 22, 20, 19, 15, 17, 17, 20, 17, 20, 15, 7, 7, 19, 11, 13, 15, 19, 17, 13, 20, 22, 26, 20, 19, 9, 13, 15, 17, 20, 13, 15, 19, 11, 15, 19, 17, 13, 13, 11, 13, 19, 13, 11, 22, 20, 19, 15, 7, 11, 9, 24, 19, 22, 26, 17, 22, 20, 19, 15, 15, 17, 13, 15, 20, 22, 15, 6, 22, 15, 15, 28, 31, 17, 11, 28, 28, 24, 20, 28, 19, 9, 17, 17, 17, 20, 11, 15, 17, 11, 28, 17, 13, 4, 20, 28, 26, 20, 22, 22, 17, 11, 9, 22, 20, 15, 22, 13, 24, 22, 28, 20, 17, 17, 20, 28, 17, 13, 9, 15, 17, 19, 20, 17, 13, 28, 31, 28, 22, 19, 17, 4, 17, 13, 2, 19, 20, 17, 20, 20, 13, 7, 28, 24, 17, 7, 15, 17, 17, 9, 13, 13, 9, 11, 11, 28, 19, 13, 15, 6, 11, 6, 6, 22, 15, 19, 17, 2, 28, 11, 6, 19, 11, 9, 28, 20, 7, 13, 13, 9, 11, 26, 28, 11, 20, 15, 9, 33, 19, 4, 6, 13, 19, 11, 13, 17, 7, 13, 28, 11, 13, 15, 24, 9, 9, 22, 13, 7, 6, 15, 2, 7, 22, 15, 20, 11, 6, 7, 9, 4, 6, 13, 17, 11, 6, 15, 4, 9, 9, 17, 11, 2, 19, 17, 19, 19, 7, 6, 13, 33, 11, 31, 9, 6, 15, 11, 17, 9, 19, 11, 2, 13, 13, 17, 15, 17, 15, 11, 9, 11, 17, 6, 13, 2, 19, 22, 6, 6, 11, 6, 7, 13, 28, 20, 2, 9, 11, 15, 6, 20, 20, 17, 17, 20, 9, 9, 19, 17, 15, 20, 9, 9, 9, 20, 6, 17, 4, 7, 7, 4, 19, 19, 9, 11, 6, 6, 4, 15, 4, 6, 15, 11, 9, 6, 20, 9, 7, 15, 15, 2, 11, 11, 17, 11, 22, 22, 9, 26, 13, 11, 9, 20, 13, 22, 24, 9, 2, 19, 19, 15, 24, 11, 19, 6, 13, 7, 13, 33, 13, 7, 15, 30, 13, 13, 13, 17, 13, 13, 15, 4, 17, 19, 22, 24, 54, 20, 13, 11, 17, 19, 19, 20, 20, 17, 17, 20, 15, 17, 20, 28, 19, 22, 19, 20, 17, 11, 33, 28, 22, 19, 17, 15, 2, 17, 20, 31, 26, 19, 11, 24, 15, 11, 9, 11, 11, 28, 31, 22, 17, 19, 20, 17, 15, 13, 11, 9, 13, 17, 19, 13, 9, 9, 17, 24, 15, 20, 13, 13, 11, 19, 19, 15, 20, 19, 22, 19, 22, 26, 13, 20, 17, 24, 22, 19, 13, 20, 22, 15, 13, 9, 13, 26, 19, 17, 20, 17, 2, 24, 13, 11, 9, 20, 24, 20, 11, 6, 15, 9, 20, 19, 20, 22, 26, 19, 20, 13, 17, 19, 28, 15, 20, 13, 13, 20, 17, 11, 13, 19, 7, 17, 22, 13, 9, 22, 13, 20, 15, 17, 11, 20, 19, 17, 11, 9, 30, 20, 13, 11, 11, 11, 17, 9, 19, 9, 20, 17, 11, 15, 24, 31, 22, 13, 22, 20, 15, 15, 17, 6, 4, 13, 4, 11, 15, 39, 13, 15, 2, 9, 11, 20, 6, 13, 6, 17, 17, 11, 6, 2, 11, 19, 13, 7, 9, 19, 9, 7, 7, 19, 15, 13, 19, 24, 30, 9, 9, 17, 11, 2, 13, 17, 7, 15, 24, 17, 6, 11, 9, 2, 13, 17, 11, 13, 28, 4, 20, 17, 7, 9, 22, 11, 6, 7, 9, 11, 7, 7, 17, 15, 19, 9, 11, 22, 9, 15, 9, 7, 19, 13, 20, 4, 17, 22, 20, 20, 6, 9, 2, 0, 20, 6, 26, 19, 22, 4, 2, 9, 7, 2, 4, 19, 20, 13, 6, 6, 4, 4, 7, 17, 11, 13, 11, 17, 17, 11, 17, 15, 2, 17, 4, 24, 31, 20, 9, 11, 26, 11, 6, 7, 9, 2, 15, 17, 22, 11, 9, 24, 9, 11, 9, 11, 7, 28, 17, 11, 9, 4, 13, 4, 20, 11, 4, 7, 7, 13, 2, 6, 9, 11, 9, 11, 9, 4, 11, 20, 15, 19, 20, 20, 11, 11, 17, 9, 15, 13, 17, 20, 15, 19, 17, 6, 9, 7, 26, 13, 17, 19, 15, 7, 11, 6, 2, 7, 15, 17, 13, 15, 9, 13, 22, 22, 13, 13, 15, 11, 13, 4, 19, 7, 11, 17, 13, 19, 13, 11, 11, 20, 9, 15, 13, 19, 20, 17, 7, 17, 9, 19, 13, 13, 9, 17, 22, 22, 17, 9, 17, 24, 17, 15, 19, 11, 13, 31, 28, 20, 15, 31, 15, 24, 22, 20, 15, 17, 13, 20, 6, 13, 9, 22, 17, 7, 13, 28, 20, 26, 31, 22, 24, 17, 13, 11, 22, 19, 17, 20, 13, 20, 15, 37, 30, 22, 19, 13, 9, 0, 9, 15, 30, 44, 22, 19, 6, 19, 19, 24, 26, 15, 6, 15, 31, 20, 17, 15, 22, 17, 17, 17, 20, 24, 20, 17, 13, 15, 15, 11, 19, 24, 15, 19, 11, 22, 20, 24, 22, 17, 17, 20, 11, 6, 33, 11, 20, 13, 13, 9, 6, 26, 17, 20, 15, 6, 41, 19, 6, 17, 30, 17, 9, 20, 17, 13, 15, 20, 20, 17, 11, 28, 35, 7, 15, 17, 30, 7, 9, 28, 11, 9, 35, 26, 26, 17, 11, 22, 28, 19, 24, 19, 20, 15, 22, 15, 13, 11, 20, 19, 13, 9, 28, 17, 20, 11, 11, 20, 22, 13, 6, 13, 7, 9, 15, 4, 33, 13, 13, 4, 13, 30, 13, 11, 15, 22, 20, 7, 19, 15, 22, 6, 9, 13, 11, 6, 13, 15, 15, 9, 44, 11, 13, 15, 9, 24, 17, 17, 2, 15, 13, 4, 15, 17, 20, 9, 4, 13, 17, 15, 15, 9, 17, 9, 26, 19, 22, 7, 15, 2, 11, 9, 9, 9, 7, 15, 2, 20, 22, 6, 20, 20, 22, 22, 4, 17, 11, 13, 11, 13, 2, 13, 13, 7, 6, 30, 11, 4, 4, 19, 24, 37, 17, 7, 9, 2, 19, 17, 7, 6, 9, 17, 17, 35, 17, 15, 17, 7, 19, 15, 19, 19, 9, 13, 6, 19, 20, 19, 13, 17, 15, 17, 17, 9, 7, 20, 30, 26, 26, 24, 28, 11, 11, 4, 19, 13, 11, 13, 11, 19, 2, 19, 20, 17, 15, 19, 15, 9, 17, 11, 13, 7, 26, 22, 19, 17, 11, 13, 13, 15, 15, 17, 9, 15, 2, 11, 15, 4, 22, 22, 24, 15, 11, 17, 17, 13, 15, 11, 22, 22, 19, 20, 24, 19, 11, 7, 20, 19, 17, 15, 11, 11, 22, 17, 11, 7, 22, 19, 19, 13, 15, 17, 20, 28, 24, 20, 20, 20, 19, 24, 17, 19, 17, 15, 15, 20, 13, 13, 19, 9, 13, 17, 19, 22, 20, 15, 17, 13], 'WindSpeed3pm': [20, 13, 2, 20, 6, 22, 15, 15, 9, 20, 26, 24, 30, 19, 22, 26, 24, 24, 17, 22, 15, 28, 24, 24, 20, 28, 15, 9, 28, 31, 17, 19, 19, 22, 19, 24, 22, 19, 24, 20, 22, 20, 24, 20, 24, 19, 20, 13, 17, 22, 30, 13, 26, 17, 6, 19, 17, 15, 15, 17, 15, 22, 20, 15, 17, 20, 15, 17, 20, 15, 15, 9, 4, 30, 22, 20, 13, 15, 24, 6, 19, 20, 22, 20, 6, 22, 24, 9, 17, 7, 17, 11, 11, 7, 9, 13, 15, 11, 11, 15, 15, 9, 19, 9, 15, 17, 31, 7, 7, 22, 19, 13, 2, 11, 13, 13, 2, 4, 7, 17, 17, 7, 22, 26, 24, 24, 24, 17, 2, 9, 4, 7, 26, 24, 26, 20, 13, 2, 13, 19, 17, 22, 13, 9, 6, 28, 15, 9, 6, 28, 41, 31, 7, 9, 15, 4, 11, 7, 20, 26, 20, 13, 17, 7, 11, 11, 17, 39, 6, 4, 31, 22, 19, 22, 17, 13, 6, 31, 20, 11, 11, 26, 24, 7, 13, 13, 13, 19, 19, 15, 24, 20, 30, 15, 26, 31, 15, 15, 19, 15, 4, 11, 17, 28, 22, 19, 15, 20, 20, 17, 22, 19, 17, 30, 26, 20, 30, 15, 24, 20, 19, 20, 20, 7, 7, 39, 19, 11, 22, 20, 26, 19, 37, 24, 19, 19, 11, 9, 28, 24, 15, 22, 19, 11, 9, 11, 22, 24, 15, 22, 20, 22, 28, 24, 20, 17, 19, 20, 24, 9, 20, 35, 24, 26, 17, 19, 19, 20, 22, 13, 20, 26, 24, 17, 24, 31, 20, 17, 13, 17, 20, 20, 19, 22, 19, 22, 19, 28, 15, 24, 20, 13, 31, 19, 26, 20, 24, 19, 26, 17, 24, 19, 24, 26, 19, 22, 24, 20, 20, 31, 17, 30, 26, 30, 37, 44, 20, 20, 17, 17, 30, 15, 20, 26, 9, 6, 19, 22, 13, 20, 15, 26, 20, 17, 33, 15, 31, 13, 20, 15, 31, 19, 20, 31, 15, 26, 24, 19, 24, 28, 22, 26, 22, 22, 26, 19, 26, 17, 15, 7, 22, 26, 24, 19, 17, 24, 19, 17, 22, 11, 31, 17, 17, 19, 20, 31, 24, 19, 22, 24, 17, 15, 20, 19, 11, 13, 15, 15, 20, 20, 11, 20, 19, 17, 20, 13, 20, 19, 19, 19, 13, 20, 24, 22, 2, 20, 15, 22, 19, 17, 13, 17, 17, 19, 17, 19, 17, 17, 26, 17, 19, 22, 26, 30, 17, 24, 28, 20, 26, 24, 22, 19, 9, 9, 7, 20, 20, 15, 19, 28, 17, 24, 15, 17, 7, 11, 22, 28, 24, 26, 22, 4, 11, 22, 6, 15, 19, 17, 17, 24, 9, 17, 2, 11, 11, 35, 30, 30, 15, 17, 20, 31, 19, 19, 19, 19, 19, 11, 6, 22, 26, 13, 24, 2, 15, 19, 2, 15, 7, 19, 22, 22, 31, 22, 4, 7, 2, 7, 19, 6, 9, 19, 11, 11, 4, 11, 7, 13, 11, 9, 7, 7, 24, 28, 33, 37, 30, 11, 7, 19, 4, 30, 20, 13, 26, 7, 28, 7, 22, 22, 6, 11, 13, 11, 24, 19, 9, 17, 9, 17, 20, 9, 15, 22, 11, 13, 22, 13, 15, 15, 24, 17, 15, 15, 13, 11, 19, 17, 9, 19, 13, 15, 20, 13, 20, 17, 17, 19, 22, 24, 17, 17, 15, 30, 13, 19, 19, 11, 13, 17, 26, 28, 11, 26, 24, 20, 9, 13, 20, 17, 11, 31, 30, 20, 15, 17, 31, 37, 17, 24, 33, 35, 9, 19, 20, 19, 15, 19, 19, 11, 17, 22, 39, 17, 19, 11, 6, 35, 30, 24, 26, 20, 17, 19, 22, 19, 17, 22, 19, 7, 26, 13, 22, 30, 26, 19, 30, 17, 24, 19, 19, 15, 19, 26, 19, 20, 26, 26, 20, 19, 28, 26, 13, 4, 13, 26, 30, 13, 30, 20, 24, 22, 28, 33, 24, 22, 30, 30, 20, 30, 20, 26, 24, 20, 24, 28, 31, 19, 22, 28, 37, 20, 26, 11, 26, 19, 20, 13, 22, 17, 20, 11, 19, 19, 19, 19, 20, 17, 15, 24, 13, 20, 24, 26, 35, 17, 17, 22, 26, 28, 22, 24, 24, 15, 6, 11, 19, 19, 20, 17, 20, 13, 24, 24, 30, 26, 28, 19, 24, 15, 22, 24, 20, 26, 15, 11, 11, 17, 35, 20, 20, 13, 24, 15, 20, 28, 13, 22, 7, 19, 13, 17, 17, 19, 26, 15, 15, 33, 17, 22, 24, 24, 28, 19, 17, 15, 19, 19, 17, 17, 15, 19, 19, 22, 20, 20, 9, 19, 19, 11, 9, 30, 19, 24, 15, 19, 7, 17, 22, 17, 20, 17, 20, 20, 19, 17, 19, 15, 15, 13, 15, 20, 19, 11, 20, 20, 15, 11, 9, 17, 13, 13, 2, 6, 17, 28, 7, 6, 11, 17, 19, 30, 26, 17, 22, 24, 13, 4, 17, 9, 11, 20, 24, 11, 4, 7, 50, 11, 7, 4, 2, 28, 19, 13, 24, 30, 15, 22, 20, 6, 30, 13, 22, 22, 13, 2, 7, 15, 22, 7, 17, 6, 19, 17, 17, 22, 9, 6, 4, 7, 11, 24, 17, 11, 17, 20, 9, 11, 7, 6, 7, 22, 17, 19, 9, 7, 7, 19, 13, 20, 20, 13, 15, 7, 9, 11, 9, 9, 28, 26, 28, 19, 9, 20, 19, 20, 15, 20, 13, 20, 22, 31, 6, 17, 24, 15, 19, 31, 19, 30, 13, 7, 22, 26, 33, 28, 19, 15, 22, 19, 19, 19, 19, 19, 19, 24, 15, 6, 39, 15, 17, 24, 28, 19, 19, 20, 13, 20, 24, 22, 15, 13, 15, 24, 20, 24, 24, 17, 31, 48, 4, 26, 28, 19, 4, 20, 24, 26, 19, 15, 22, 28, 28, 24, 24, 20, 30, 15, 26, 28, 11, 30, 24, 28, 7, 20, 15, 20, 33, 26, 26, 20, 19, 28, 13, 28, 17, 19, 22, 24, 19, 19, 24, 28, 9, 28, 22, 28, 24, 24, 6, 6, 26, 33, 41, 20, 26, 19, 19, 19, 15, 28, 19, 28, 20, 28, 20, 26, 20, 19, 20, 17, 17, 20, 20, 26, 20, 28, 28, 28, 7, 15, 24, 20, 20, 24, 28, 26, 28, 26, 20, 15, 17, 24, 24, 24, 17, 17, 20, 24, 28, 33, 41, 19, 17, 11, 24, 13, 26, 26, 19, 20, 19, 15, 13, 28, 13, 20, 26, 20, 22, 20, 26, 6, 26, 17, 11, 28, 24, 28, 19, 20, 30, 17, 9, 19, 20, 22, 31, 15, 20, 17, 20, 24, 39, 19, 20, 13, 35, 13, 20, 19, 15, 24, 17, 20, 13, 13, 20, 20, 26, 17, 9, 11, 31, 22, 28, 24, 20, 20, 11, 13, 17, 9, 17, 11, 11, 11, 26, 19, 31, 17, 13, 19, 17, 17, 31, 37, 19, 6, 6, 9, 20, 24, 30, 28, 31, 26, 35, 20, 35, 28, 22, 39, 39, 9, 22, 39, 30, 9, 9, 7, 6, 17, 13, 6, 15, 20, 2, 20, 26, 39, 20, 30, 17, 22, 31, 13, 11, 22, 22, 13, 17, 2, 4, 26, 24, 30, 19, 22, 13, 4, 15, 20, 15, 11, 6, 2, 15, 4, 15, 17, 20, 11, 17, 13, 15, 15, 13, 15, 17, 11, 15, 11, 17, 30, 39, 26, 28, 19, 11, 17, 17, 15, 6, 17, 6, 17, 17, 19, 19, 26, 20, 13, 15, 19, 17, 13, 31, 19, 19, 19, 24, 20, 17, 19, 31, 26, 43, 17, 20, 17, 19, 20, 17, 22, 11, 31, 33, 17, 31, 28, 20, 15, 15, 19, 20, 20, 22, 19, 22, 24, 22, 15, 24, 20, 17, 24, 22, 9, 19, 19, 28, 33, 20, 19, 30, 11, 22, 26, 17, 26, 11, 17, 26, 17, 11, 24, 13, 20, 24, 17, 24, 22, 11, 22, 17, 9, 17, 22, 24, 24, 15, 30, 26, 24, 22, 22, 22, 30, 24, 28, 17, 17, 24, 11, 17, 13, 13, 19, 31, 22, 20, 17, 20, 24, 24, 22, 24, 13, 20, 19, 31, 9, 24, 17, 24, 20, 19, 26, 24, 24, 9, 17, 28, 28, 20, 24, 30, 39, 24, 26, 13, 24, 26, 20, 22, 19, 2, 24, 20, 7, 13, 15, 28, 19, 28, 24, 28, 28, 17, 9, 17, 28, 37, 28, 19, 26, 24, 11, 19, 20, 19, 19, 26, 22, 22, 24, 19, 35, 22, 22, 22, 28, 19, 22, 20, 15, 17, 20, 17, 24, 26, 28, 22, 15, 24, 26, 20, 26, 19, 24, 22, 15, 22, 28, 22, 19, 20, 13, 20, 15, 15, 22, 15, 6, 22, 13, 15, 17, 15, 17, 17, 20, 20, 31, 15, 19, 33, 31, 15, 20, 17, 11, 20, 9, 35, 13, 9, 19, 15, 41, 35, 22, 17, 11, 28, 11, 20, 20, 17, 19, 26, 13, 7, 7, 9, 19, 7, 6, 39, 22, 20, 13, 17, 11, 9, 13, 13, 13, 17, 7, 24, 31, 19, 26, 17, 13, 15, 6, 6, 15, 9, 33, 28, 17, 6, 4, 6, 15, 24, 11, 0, 13, 9, 30, 17, 28, 4, 17, 20, 15, 19, 15, 15, 9, 13, 13, 28, 24, 19, 26, 24, 22, 11, 11, 13, 22, 15, 9, 26, 19, 17, 11, 17, 13, 31, 19, 22, 20, 11, 20, 7, 20, 11, 20, 28, 24, 22, 9, 11, 6, 15, 17, 6, 9, 31, 26, 11, 19, 37, 33, 17, 17, 19, 19, 41, 33, 6, 15, 30, 24, 31, 19, 15, 17, 31, 22, 39, 28, 17, 20, 33, 17, 19, 24, 26, 20, 17, 22, 13, 17, 17, 17, 26, 33, 19, 22, 26, 20, 17, 7, 11, 28, 11, 28, 19, 19, 9, 22, 20, 20, 19, 22, 24, 22, 19, 33, 20, 39, 20, 24, 19, 19, 24, 15, 30, 24, 20, 20, 26, 17, 26, 20, 30, 19, 20, 17, 26, 19, 31, 28, 20, 17, 9, 15, 35, 26, 22, 24, 22, 17, 28, 15, 20, 13, 13, 20, 24, 19, 24, 19, 26, 17, 20, 20, 28, 28, 24, 15, 26, 19, 28, 17, 24, 26, 15, 20, 15, 17, 17, 26, 20, 26, 30, 9, 24, 24, 20, 24, 26, 31, 30, 22, 28, 24, 24, 20, 24, 20, 26, 19, 26, 11, 26, 20, 31, 24, 19, 20, 26, 20, 24, 17, 13, 24, 22, 11, 20, 24, 28, 17, 19, 20, 9, 7, 6, 15, 17, 6, 20, 17, 19, 22, 13, 11, 20, 17, 26, 35, 30, 15, 11, 15, 13, 17, 13, 19, 15, 13, 19, 17, 20, 19, 37, 7, 17, 19, 9, 13, 13, 22, 13, 11, 13, 28, 31, 28, 22, 20, 22, 20, 20, 22, 24, 15, 4, 24, 15, 15, 7, 13, 17, 24, 13, 9, 13, 6, 15, 11, 15, 17, 9, 19, 20, 22, 11, 15, 17, 17, 26, 20, 15, 17, 19, 11, 9, 20, 19, 15, 9, 9, 7, 4, 13, 22, 33, 19, 11, 17, 17, 13, 9, 6, 2, 15, 13, 13, 9, 13, 17, 26, 31, 26, 19, 20, 9, 7, 15, 17, 11, 6, 22, 15, 19, 4, 24, 15, 17, 15, 24, 9, 11, 11, 48, 9, 17, 19, 26, 26, 20, 39, 22, 20, 24, 28, 19, 17, 11, 15, 24, 17, 6, 11, 20, 17, 20, 20, 11, 15, 15, 13, 11, 31, 15, 6, 24, 24, 17, 35, 28, 28, 46, 24, 19, 20, 13, 9, 20, 35, 19, 39, 22, 17, 41, 15, 24, 15, 13, 17, 33, 22, 15, 22, 19, 24, 46, 24, 20, 35, 43, 22, 28, 19, 15, 7, 31, 31, 26, 26, 20, 19, 0, 0, 0, 0, 0, 0, 0, 20, 30, 22, 28, 20, 22, 28, 6, 24, 20, 26, 33, 17, 24, 17, 22, 24, 39, 7, 20, 35, 22, 20, 19, 19, 20, 17, 22, 30, 15, 48, 24, 22, 26, 6, 13, 24, 28, 30, 31, 19, 24, 30, 26, 28, 9, 37, 9, 9, 17, 13, 24, 22, 28, 28, 24, 24, 24, 33, 26, 22, 22, 26, 13, 15, 20, 26, 17, 19, 17, 30, 22, 28, 26, 22, 20, 24, 15, 24, 20, 28, 37, 19, 26, 28, 20, 30, 26, 17, 26, 33, 31, 26, 17, 30, 26, 22, 17, 13, 22, 28, 17, 17, 24, 20, 13, 13, 17, 28, 24, 20, 19, 30, 17, 26, 20, 11, 17, 11, 11, 15, 22, 20, 22, 20, 26, 20, 11, 15, 30, 17, 13, 26, 19, 26, 22, 19, 20, 19, 31, 9, 9, 7, 11, 24, 22, 15, 17, 20, 24, 19, 24, 7, 9, 13, 17, 7, 9, 22, 15, 15, 28, 22, 22, 13, 22, 17, 15, 11, 13, 6, 15, 6, 15, 11, 15, 20, 15, 19, 35, 31, 7, 6, 20, 19, 13, 13, 20, 20, 9, 17, 13, 13, 13, 7, 7, 7, 13, 6, 13, 15, 17, 17, 26, 26, 22, 17, 17, 26, 9, 17, 13, 11, 17, 19, 24, 17, 19, 9, 9, 15, 19, 22, 11, 19, 11, 13, 6, 11, 4, 22, 33, 39, 15, 9, 20, 28, 22, 7, 13, 13, 7, 28, 24, 19, 6, 22, 37, 19, 26, 24, 19, 2, 20, 26, 39, 24, 22, 17, 11, 13, 9, 15, 24, 15, 15, 20, 22, 35, 28, 28, 15, 20, 17, 11, 13, 15, 15, 9, 24, 11, 20, 22, 17, 13, 22, 28, 26, 22, 22, 17, 20, 11, 19, 9, 28, 26, 24, 22, 15, 13, 22, 30, 31, 26, 24, 17, 24, 22, 28, 17, 15, 17, 17, 22, 24, 26, 22, 15, 17, 20, 17, 17, 19, 20, 24, 15, 26, 24, 13, 17, 24, 17, 19, 20, 19, 22, 22, 19, 26, 13, 20, 26, 24, 31, 17, 19, 22, 19, 28, 20, 30, 19, 24, 41, 22, 26, 17, 22, 26, 31, 30, 28, 22, 22, 24, 20, 20, 20, 22, 13, 24, 44, 24, 24, 28, 24, 22, 19, 22, 28, 24, 26, 26, 20, 20, 17, 22, 17, 17, 22, 17, 22, 22, 26, 28, 24, 24, 39, 22, 20, 22, 20, 31, 33, 13, 28, 22, 37, 15, 13, 24, 17, 24, 24, 17, 22, 15, 15, 17, 22, 31, 31, 13, 13, 30, 20, 28, 24, 22, 24, 20, 24, 26, 20, 19, 30, 24, 19, 17, 13, 6, 35, 17, 19, 19, 35, 24, 30, 13, 15, 22, 22, 20, 19, 28, 26, 19, 17, 20, 28, 31, 28, 17, 9, 15, 20, 17, 33, 30, 17, 17, 22, 20, 15, 28, 13, 35, 24, 24, 22, 24, 20, 26, 22, 17, 19, 33, 13, 17, 17, 19, 39, 22, 22, 22, 9, 20, 17, 22, 20, 20, 19, 13, 17, 11, 13, 26, 19, 15, 22, 30, 31, 20, 13, 28, 19, 17, 19, 15, 13, 26, 35, 46, 46, 22, 7, 13, 19, 19, 17, 22, 17, 17, 15, 17, 22, 7, 26, 26, 30, 11, 19, 26, 39, 30, 13, 20, 24, 20, 17, 2, 7, 19, 19, 30, 22, 6, 7, 9, 9, 4, 7, 9, 13, 26, 20, 11, 9, 7, 4, 15, 19, 19, 9, 4, 4, 11, 6, 9, 7, 7, 13, 20, 13, 11, 7, 9, 6, 20, 2, 11, 9, 9, 7, 9, 33, 15, 11, 4, 22, 11, 17, 7, 13, 17, 33, 39, 17, 13, 13, 26, 28, 17, 15, 15, 17, 9, 9, 15, 35, 26, 19, 11, 19, 9, 28, 20, 17, 2, 19, 11, 17, 24, 13, 20, 9, 28, 17, 19, 19, 15, 13, 19, 13, 20, 15, 11, 7, 9, 20, 13, 17, 20, 15, 22, 22, 13, 19, 24, 20, 24, 6, 15, 24, 17, 15, 24, 19, 20, 24, 35, 26, 28, 26, 24, 13, 15, 37, 35, 28, 26, 24, 20, 17, 17, 20, 24, 24, 11, 28, 11, 17, 26, 20, 24, 17, 11, 19, 20, 20, 30, 20, 15, 15, 24, 15, 9, 31, 17, 26, 19, 13, 30, 20, 22, 24, 28, 17, 15, 17, 31, 26, 13, 28, 26, 17, 19, 11, 17, 6, 19, 19, 20, 22, 22, 17, 28, 24, 17, 30, 28, 35, 22, 17, 22, 22, 31, 35, 20, 19, 24, 22, 17, 17, 19, 30, 28, 30, 19, 22, 13, 24, 30, 20, 22, 2, 22, 20, 20, 17, 28, 24, 22, 19, 24, 28, 19, 22, 7, 26, 20, 24, 19, 22, 26, 15, 24, 28, 22, 20, 22, 20, 13, 9, 20, 13, 33, 15, 13, 19, 15, 15, 6, 17, 26, 15, 24, 26, 33, 39, 20, 17, 17, 19, 22, 20, 22, 24, 4, 20, 31, 22, 19, 20, 26, 13, 24, 22, 26, 17, 22, 22, 17, 20, 26, 30, 26, 24, 24, 20, 26, 20, 24, 24, 19, 24, 20, 20, 26, 20, 15, 13, 22, 20, 24, 19, 15, 24, 9, 17, 20, 20, 19, 7, 20, 28, 9, 19, 17, 24, 26, 19, 2, 15, 19, 19, 22, 19, 15, 19, 11, 17, 17, 17, 13, 13, 24, 17, 20, 15, 13, 19, 20, 11, 9, 20, 9, 20, 15, 20, 13, 13, 9, 17, 35, 17, 22, 11, 15, 9, 15, 15, 11, 17, 17, 9, 9, 22, 19, 6, 24, 37, 13, 15, 9, 6, 7, 15, 11, 30, 57, 28, 20, 15, 17, 7, 19, 7, 9, 6, 9, 11, 17, 4, 20, 22, 28, 28, 24, 43, 17, 7, 9, 13, 4, 17, 13, 6, 17, 31, 22, 7, 13, 15, 39, 33, 37, 20, 4, 15, 2, 15, 6, 13, 2, 30, 43, 15, 24, 9, 26, 11, 11, 9, 7, 6, 24, 24, 17, 7, 7, 11, 11, 24, 22, 13, 19, 13, 17, 19, 11, 19, 24, 22, 9, 24, 20, 9, 15, 20, 15, 17, 9, 15, 39, 15, 9, 30, 15, 19, 19, 17, 24, 22, 31, 17, 19, 9, 19, 35, 28, 19, 6, 28, 17, 15, 24, 24, 17, 15, 19, 26, 17, 22, 39, 39, 20, 31, 43, 26, 30, 22, 30, 24, 28, 9, 24, 24, 19, 26, 28, 15, 26, 6, 26, 26, 22, 28, 22, 22, 20, 26, 7, 20, 11, 20, 20, 20, 26, 20, 28, 26, 24, 24, 19, 19, 20, 22, 41, 28, 19, 22, 28, 11, 20, 26, 17, 24, 26, 22, 24, 22, 28, 20, 31, 19, 17, 19, 26, 17, 7, 24, 26, 31, 26, 28, 19, 15, 33, 15, 4, 19, 22, 24, 20, 28, 20, 28, 20, 26, 30, 19, 24, 22, 20, 24, 19, 28, 19, 22, 20, 22, 28, 20, 20, 17, 20, 20, 30, 22, 22, 28, 11, 31, 19, 28, 20, 22, 20, 20, 11, 13, 15, 17, 19, 17, 33, 9, 22, 17, 17, 6, 19, 19, 19, 20, 17, 19, 33, 22, 24, 17, 24, 9, 20, 19, 19, 19, 22, 22, 15, 19, 24, 24, 17, 22, 15, 17, 20, 24, 33, 30, 20, 31, 24, 20, 28, 19, 24, 31, 24, 35, 22, 24, 20, 17, 19, 20, 20, 13, 19, 22, 11, 22, 28, 28, 17, 22, 24, 20, 22, 15, 13, 20, 20, 26, 26, 17, 20, 15, 17, 9, 13, 17, 15, 20, 17, 15, 17, 17, 22, 24, 13, 13, 13, 19, 15, 15, 13, 20, 13, 13, 20, 13, 13, 19, 17, 17, 9, 20, 11, 17, 22, 17, 9, 17, 11, 17, 22, 11, 13, 15, 24, 19, 17, 28, 26, 20, 22, 17, 7, 15, 17, 15, 28, 15, 6, 15, 22, 9, 15, 7, 13, 28, 19, 9, 20, 7, 13, 19, 13], 'Humidity9am': [92, 83, 88, 83, 88, 69, 75, 77, 92, 80, 78, 68, 87, 81, 80, 77, 63, 70, 79, 80, 86, 77, 38, 48, 58, 73, 82, 77, 65, 55, 93, 78, 77, 72, 67, 83, 88, 82, 76, 72, 77, 84, 84, 80, 81, 82, 73, 70, 70, 87, 81, 82, 95, 81, 76, 52, 71, 85, 61, 57, 55, 75, 42, 47, 71, 71, 83, 86, 96, 77, 83, 79, 81, 82, 85, 78, 91, 94, 51, 79, 91, 90, 90, 93, 81, 51, 46, 54, 68, 74, 65, 62, 64, 71, 74, 57, 63, 75, 86, 84, 88, 88, 82, 90, 78, 52, 57, 58, 64, 74, 63, 76, 71, 78, 81, 82, 80, 86, 87, 90, 91, 97, 98, 87, 82, 81, 76, 97, 96, 98, 74, 97, 67, 49, 75, 86, 88, 90, 91, 81, 66, 61, 74, 72, 69, 47, 57, 68, 84, 47, 45, 55, 63, 84, 78, 84, 87, 80, 57, 58, 46, 67, 67, 80, 81, 81, 84, 73, 53, 41, 56, 52, 67, 95, 93, 79, 71, 79, 86, 65, 71, 40, 48, 52, 62, 67, 89, 74, 58, 56, 62, 46, 50, 49, 51, 49, 48, 45, 59, 65, 58, 58, 90, 65, 63, 76, 78, 85, 70, 82, 91, 54, 56, 67, 55, 76, 92, 69, 68, 49, 66, 72, 53, 40, 82, 58, 30, 60, 63, 67, 46, 73, 64, 88, 60, 67, 56, 67, 35, 42, 61, 70, 44, 41, 89, 93, 85, 51, 53, 56, 76, 82, 76, 72, 89, 63, 64, 71, 77, 64, 76, 68, 87, 71, 66, 66, 58, 55, 67, 93, 92, 53, 73, 72, 62, 59, 59, 58, 61, 62, 46, 63, 66, 69, 61, 65, 92, 75, 60, 60, 91, 70, 34, 49, 50, 47, 62, 55, 58, 71, 92, 64, 29, 65, 67, 59, 78, 57, 81, 74, 81, 71, 90, 85, 82, 42, 39, 58, 68, 65, 67, 57, 60, 56, 60, 77, 73, 75, 79, 72, 72, 81, 37, 73, 62, 58, 59, 66, 77, 72, 78, 54, 54, 58, 71, 74, 67, 61, 69, 52, 62, 55, 61, 66, 52, 59, 55, 57, 80, 95, 78, 73, 72, 76, 71, 79, 63, 84, 73, 75, 68, 69, 84, 94, 77, 76, 86, 66, 88, 82, 70, 93, 74, 78, 85, 70, 78, 82, 83, 74, 78, 70, 70, 71, 61, 73, 39, 67, 77, 80, 94, 66, 59, 87, 85, 82, 81, 42, 47, 72, 76, 80, 83, 82, 66, 67, 69, 72, 69, 85, 77, 66, 86, 93, 87, 92, 84, 72, 69, 67, 66, 72, 81, 80, 79, 89, 70, 43, 56, 66, 91, 60, 59, 85, 87, 75, 52, 47, 43, 54, 59, 92, 76, 61, 85, 84, 86, 92, 67, 71, 74, 86, 74, 78, 80, 50, 58, 49, 64, 74, 91, 68, 53, 59, 66, 52, 82, 89, 88, 92, 65, 82, 86, 83, 91, 89, 97, 93, 71, 80, 63, 62, 37, 48, 67, 70, 74, 79, 81, 92, 95, 95, 95, 93, 96, 91, 86, 69, 76, 84, 86, 67, 66, 61, 55, 50, 59, 54, 74, 81, 96, 96, 97, 94, 80, 67, 68, 79, 78, 80, 84, 66, 72, 68, 54, 62, 62, 81, 83, 72, 63, 61, 65, 66, 60, 63, 58, 70, 69, 73, 47, 46, 70, 77, 81, 77, 63, 61, 77, 66, 37, 48, 70, 74, 47, 51, 64, 47, 29, 32, 44, 44, 51, 34, 40, 49, 60, 80, 81, 36, 53, 74, 56, 47, 45, 50, 49, 24, 70, 77, 80, 68, 43, 63, 49, 69, 45, 40, 36, 36, 24, 30, 39, 42, 57, 21, 72, 91, 88, 91, 77, 51, 49, 65, 84, 91, 61, 38, 36, 46, 42, 53, 80, 71, 71, 44, 67, 66, 63, 72, 91, 58, 78, 80, 62, 82, 73, 71, 75, 66, 69, 75, 77, 61, 74, 70, 66, 66, 74, 72, 61, 72, 70, 71, 56, 75, 62, 84, 82, 80, 50, 63, 28, 55, 58, 69, 58, 69, 59, 61, 67, 68, 76, 75, 30, 57, 68, 72, 59, 74, 71, 87, 70, 62, 65, 58, 91, 92, 97, 69, 66, 92, 84, 70, 80, 64, 64, 83, 66, 66, 76, 65, 64, 77, 64, 90, 83, 72, 64, 55, 39, 41, 74, 77, 28, 92, 80, 83, 78, 80, 81, 82, 75, 73, 61, 90, 83, 79, 95, 95, 76, 83, 72, 71, 71, 92, 91, 95, 65, 64, 52, 60, 76, 75, 61, 54, 55, 45, 73, 79, 83, 68, 52, 53, 73, 72, 90, 71, 72, 46, 85, 63, 55, 68, 87, 78, 82, 80, 77, 82, 64, 64, 64, 74, 79, 75, 80, 80, 82, 78, 92, 68, 68, 74, 72, 84, 76, 74, 90, 77, 68, 78, 58, 33, 52, 71, 77, 77, 82, 82, 87, 95, 81, 68, 57, 77, 56, 65, 64, 44, 79, 89, 90, 75, 80, 59, 48, 62, 65, 68, 78, 64, 40, 53, 60, 62, 71, 85, 94, 91, 82, 83, 92, 91, 86, 89, 96, 82, 92, 88, 78, 87, 80, 81, 91, 85, 80, 64, 60, 78, 71, 48, 64, 63, 66, 75, 86, 89, 67, 71, 95, 83, 96, 83, 78, 72, 68, 63, 70, 70, 74, 68, 68, 76, 95, 83, 96, 95, 61, 87, 83, 56, 50, 63, 71, 81, 67, 71, 73, 64, 75, 81, 83, 90, 86, 96, 93, 97, 96, 62, 49, 75, 75, 57, 56, 58, 73, 83, 93, 59, 55, 54, 69, 53, 44, 44, 69, 57, 45, 44, 58, 77, 53, 36, 48, 47, 52, 70, 71, 53, 77, 80, 90, 44, 45, 54, 58, 77, 82, 46, 64, 64, 70, 42, 41, 48, 56, 66, 82, 75, 69, 67, 58, 57, 70, 93, 83, 63, 66, 34, 44, 70, 75, 70, 59, 92, 73, 76, 65, 82, 70, 81, 78, 77, 65, 83, 67, 93, 77, 64, 80, 87, 77, 70, 70, 82, 80, 65, 71, 82, 60, 67, 62, 77, 73, 85, 94, 94, 91, 70, 84, 74, 73, 67, 80, 74, 46, 47, 62, 71, 72, 75, 57, 69, 42, 36, 71, 72, 65, 69, 88, 88, 59, 66, 64, 78, 69, 72, 81, 74, 64, 72, 88, 68, 82, 80, 71, 79, 75, 56, 87, 86, 65, 68, 83, 62, 66, 64, 57, 56, 70, 85, 79, 70, 76, 64, 72, 65, 59, 58, 72, 46, 56, 64, 67, 69, 85, 63, 87, 83, 59, 84, 81, 80, 83, 79, 61, 82, 57, 77, 71, 75, 80, 74, 83, 53, 58, 77, 72, 70, 48, 67, 71, 77, 70, 86, 82, 76, 76, 82, 77, 85, 81, 86, 92, 95, 95, 75, 50, 50, 71, 89, 91, 94, 78, 78, 84, 87, 90, 72, 63, 69, 75, 76, 63, 62, 64, 51, 69, 50, 58, 69, 72, 74, 83, 91, 80, 79, 81, 57, 72, 63, 69, 75, 82, 89, 81, 65, 73, 85, 73, 68, 57, 71, 46, 54, 58, 86, 89, 92, 81, 85, 71, 82, 51, 69, 64, 54, 47, 59, 69, 79, 83, 66, 86, 74, 76, 91, 91, 90, 50, 36, 44, 45, 59, 49, 44, 41, 56, 54, 56, 64, 94, 95, 90, 63, 91, 94, 88, 89, 79, 73, 74, 70, 83, 75, 78, 65, 73, 72, 72, 73, 66, 57, 84, 66, 69, 58, 58, 74, 78, 89, 78, 85, 91, 69, 85, 57, 56, 56, 86, 82, 79, 75, 96, 76, 57, 68, 78, 84, 64, 70, 56, 56, 44, 36, 67, 82, 39, 47, 48, 57, 37, 75, 49, 66, 27, 59, 31, 36, 53, 44, 65, 90, 52, 63, 59, 74, 43, 49, 88, 76, 73, 76, 67, 88, 93, 89, 77, 39, 49, 70, 65, 84, 62, 52, 57, 67, 100, 59, 76, 80, 53, 81, 78, 59, 67, 70, 75, 100, 73, 64, 88, 60, 62, 56, 54, 78, 77, 61, 46, 64, 52, 77, 93, 77, 76, 78, 62, 85, 93, 75, 89, 95, 42, 55, 66, 77, 51, 63, 57, 70, 61, 77, 64, 86, 81, 74, 69, 92, 62, 60, 59, 64, 50, 67, 77, 79, 71, 76, 79, 75, 65, 61, 69, 60, 69, 74, 69, 56, 54, 58, 69, 61, 75, 64, 73, 79, 38, 36, 43, 56, 68, 95, 84, 59, 75, 75, 73, 65, 60, 76, 84, 90, 80, 68, 74, 69, 50, 87, 72, 95, 92, 84, 76, 91, 68, 71, 74, 87, 80, 87, 83, 56, 68, 62, 73, 75, 81, 82, 69, 77, 78, 71, 80, 73, 66, 89, 90, 88, 66, 75, 59, 66, 62, 96, 75, 82, 71, 76, 78, 85, 80, 81, 94, 66, 72, 84, 83, 79, 84, 47, 76, 77, 69, 77, 75, 84, 81, 67, 75, 88, 60, 64, 67, 69, 62, 41, 45, 59, 80, 75, 74, 65, 63, 91, 95, 92, 91, 92, 81, 79, 48, 56, 68, 80, 73, 70, 76, 79, 63, 45, 64, 65, 64, 68, 68, 67, 63, 60, 42, 49, 56, 68, 77, 82, 71, 75, 78, 70, 69, 79, 77, 43, 65, 66, 94, 80, 79, 89, 91, 96, 91, 53, 70, 68, 71, 78, 87, 96, 71, 95, 93, 89, 88, 68, 66, 65, 74, 70, 44, 66, 55, 84, 84, 89, 91, 79, 69, 56, 61, 55, 75, 89, 86, 81, 90, 92, 76, 80, 74, 73, 52, 62, 82, 70, 63, 65, 81, 92, 95, 93, 57, 74, 68, 66, 54, 60, 62, 58, 58, 60, 50, 45, 54, 55, 51, 42, 48, 47, 36, 45, 54, 62, 70, 59, 45, 36, 42, 48, 47, 39, 45, 61, 52, 55, 28, 28, 22, 39, 66, 66, 39, 50, 54, 57, 71, 63, 57, 73, 83, 49, 64, 31, 51, 67, 58, 63, 29, 51, 58, 53, 39, 22, 90, 39, 60, 67, 83, 84, 47, 77, 65, 43, 62, 58, 78, 44, 66, 68, 56, 57, 63, 68, 39, 51, 59, 65, 64, 55, 44, 82, 80, 70, 65, 78, 58, 77, 56, 42, 55, 60, 80, 72, 86, 57, 65, 44, 61, 60, 66, 59, 67, 60, 74, 80, 84, 71, 73, 70, 70, 54, 59, 56, 65, 74, 52, 64, 63, 62, 53, 71, 69, 62, 64, 75, 62, 65, 67, 71, 63, 74, 70, 69, 73, 90, 88, 93, 70, 66, 86, 73, 63, 53, 70, 78, 67, 67, 75, 67, 72, 78, 72, 72, 78, 70, 48, 55, 66, 71, 60, 56, 73, 71, 57, 83, 75, 71, 48, 62, 78, 83, 67, 88, 93, 83, 93, 73, 72, 90, 72, 71, 73, 71, 72, 75, 88, 75, 76, 50, 92, 71, 85, 57, 62, 52, 56, 65, 59, 59, 80, 86, 53, 72, 50, 56, 68, 76, 80, 79, 77, 77, 93, 88, 60, 59, 55, 50, 53, 54, 61, 55, 71, 93, 89, 83, 70, 84, 94, 94, 90, 84, 62, 92, 57, 66, 87, 61, 70, 73, 80, 90, 94, 85, 89, 64, 58, 59, 65, 76, 80, 71, 79, 87, 93, 91, 93, 84, 93, 93, 90, 94, 89, 77, 82, 57, 54, 57, 62, 68, 83, 84, 91, 92, 85, 88, 78, 88, 85, 85, 66, 65, 49, 54, 60, 61, 72, 75, 62, 84, 53, 73, 82, 71, 83, 51, 54, 52, 48, 57, 85, 60, 46, 61, 40, 35, 39, 42, 61, 41, 38, 33, 43, 50, 48, 50, 52, 72, 54, 58, 72, 69, 46, 60, 57, 71, 66, 75, 62, 74, 74, 78, 70, 24, 38, 41, 67, 75, 74, 75, 73, 53, 31, 34, 49, 57, 55, 32, 40, 30, 29, 47, 34, 46, 33, 31, 41, 45, 56, 41, 60, 58, 59, 22, 64, 63, 45, 44, 40, 33, 23, 30, 57, 65, 56, 72, 47, 41, 28, 34, 51, 81, 78, 57, 62, 63, 71, 49, 34, 58, 58, 59, 43, 46, 87, 91, 92, 59, 32, 68, 74, 83, 80, 79, 71, 64, 79, 78, 58, 57, 61, 52, 56, 72, 59, 64, 52, 51, 61, 80, 37, 47, 58, 52, 34, 31, 69, 63, 65, 81, 83, 60, 57, 60, 59, 59, 67, 61, 58, 85, 82, 78, 62, 65, 47, 60, 58, 50, 62, 60, 63, 30, 55, 68, 49, 66, 65, 71, 66, 59, 62, 64, 67, 65, 65, 71, 79, 74, 60, 69, 63, 77, 56, 45, 54, 56, 51, 72, 67, 55, 62, 59, 67, 63, 59, 63, 83, 72, 78, 66, 81, 88, 78, 90, 77, 81, 52, 33, 63, 50, 68, 72, 59, 82, 86, 90, 85, 70, 83, 69, 75, 69, 63, 68, 60, 67, 69, 81, 70, 64, 57, 47, 58, 66, 58, 75, 68, 70, 79, 82, 89, 89, 84, 80, 69, 79, 78, 91, 82, 82, 80, 86, 83, 77, 68, 74, 64, 76, 86, 64, 58, 69, 65, 68, 60, 61, 48, 67, 59, 53, 84, 72, 83, 75, 71, 83, 59, 71, 81, 61, 54, 58, 59, 66, 84, 80, 76, 73, 74, 78, 82, 75, 72, 69, 72, 69, 66, 82, 64, 62, 75, 81, 68, 54, 59, 71, 86, 87, 85, 70, 69, 91, 86, 67, 65, 71, 91, 86, 86, 85, 89, 65, 78, 63, 67, 81, 66, 79, 79, 76, 47, 45, 47, 68, 36, 45, 53, 64, 67, 71, 71, 62, 59, 59, 66, 49, 52, 58, 64, 54, 62, 88, 86, 56, 47, 50, 66, 69, 81, 87, 83, 82, 90, 65, 62, 49, 44, 40, 41, 45, 60, 69, 75, 64, 53, 76, 94, 46, 62, 84, 77, 64, 81, 86, 90, 94, 69, 68, 86, 88, 92, 88, 81, 93, 80, 81, 85, 89, 67, 77, 59, 52, 53, 72, 92, 90, 93, 56, 84, 36, 67, 80, 69, 68, 33, 50, 50, 71, 55, 58, 66, 60, 59, 53, 54, 29, 42, 19, 45, 63, 73, 65, 67, 44, 80, 61, 53, 61, 66, 60, 49, 79, 61, 75, 66, 57, 59, 50, 54, 64, 78, 81, 64, 60, 36, 35, 61, 26, 52, 60, 67, 64, 54, 61, 60, 73, 51, 66, 64, 69, 60, 87, 38, 60, 65, 56, 36, 50, 62, 71, 65, 58, 64, 59, 71, 68, 80, 64, 70, 68, 81, 71, 73, 92, 53, 69, 54, 60, 61, 80, 53, 51, 65, 63, 84, 82, 77, 67, 50, 75, 62, 59, 64, 68, 78, 76, 69, 82, 80, 64, 55, 72, 81, 96, 76, 94, 55, 45, 67, 35, 73, 66, 88, 78, 68, 74, 69, 77, 84, 96, 95, 54, 43, 59, 75, 81, 72, 70, 59, 80, 77, 71, 76, 82, 72, 62, 94, 82, 85, 62, 59, 59, 88, 82, 88, 82, 76, 89, 76, 86, 97, 78, 69, 70, 60, 79, 28, 44, 89, 87, 75, 79, 85, 76, 70, 73, 75, 77, 63, 76, 72, 75, 75, 71, 81, 86, 72, 70, 34, 39, 78, 84, 93, 95, 86, 91, 95, 76, 81, 67, 43, 49, 82, 94, 80, 65, 63, 72, 67, 86, 71, 50, 96, 87, 98, 98, 89, 78, 81, 59, 63, 81, 92, 98, 79, 98, 83, 84, 41, 51, 51, 52, 49, 48, 56, 42, 49, 59, 87, 89, 91, 84, 79, 67, 94, 69, 87, 84, 77, 69, 82, 79, 84, 78, 47, 47, 64, 82, 69, 66, 89, 67, 57, 94, 83, 88, 85, 88, 85, 85, 95, 80, 98, 76, 90, 94, 85, 82, 77, 85, 87, 73, 84, 94, 85, 70, 55, 82, 66, 58, 58, 86, 92, 92, 100, 60, 96, 62, 62, 91, 95, 58, 84, 84, 93, 71, 96, 95, 50, 53, 41, 56, 70, 80, 49, 54, 51, 48, 57, 46, 53, 60, 63, 68, 66, 52, 54, 50, 55, 63, 70, 53, 40, 58, 71, 73, 45, 85, 90, 66, 80, 87, 48, 60, 52, 48, 50, 61, 69, 92, 68, 84, 62, 42, 48, 59, 56, 61, 61, 58, 33, 42, 53, 65, 88, 62, 74, 36, 55, 63, 91, 86, 70, 56, 58, 57, 68, 57, 62, 28, 42, 37, 61, 53, 51, 62, 77, 50, 82, 75, 65, 60, 66, 69, 81, 60, 58, 89, 70, 62, 62, 54, 65, 70, 55, 59, 59, 67, 75, 91, 91, 94, 77, 69, 67, 59, 61, 82, 53, 63, 81, 64, 56, 55, 45, 62, 63, 65, 59, 60, 57, 31, 54, 69, 80, 65, 58, 66, 52, 53, 58, 61, 68, 70, 80, 66, 57, 58, 63, 72, 87, 70, 58, 59, 56, 89, 65, 60, 55, 74, 74, 78, 51, 60, 62, 57, 60, 63, 86, 87, 92, 91, 58, 71, 67, 69, 56, 69, 92, 66, 71, 64, 60, 39, 66, 85, 60, 73, 73, 73, 66, 74, 72, 84, 83, 42, 62, 67, 87, 59, 75, 76, 68, 70, 68, 65, 63, 60, 58, 75, 36, 57, 59, 70, 75, 89, 71, 62, 60, 62, 67, 60, 62, 73, 72, 59, 71, 70, 64, 64, 71, 61, 71, 84, 79, 73, 63, 84, 89, 88, 92, 71, 43, 63, 91, 74, 66, 73, 78, 71, 83, 88, 84, 81, 51, 69, 63, 74, 91, 64, 54, 59, 71, 65, 70, 51, 85, 72, 88, 66, 69, 73, 75, 83, 82, 79, 70, 83, 61, 76, 75, 78, 84, 75, 74, 86, 56, 61, 49, 55, 69, 75, 86, 76, 51, 51, 52, 60, 62, 42, 66, 55, 49, 54, 53, 72, 82, 53, 50, 54, 52, 42, 63, 59, 62, 76, 89, 85, 78, 91, 89, 59, 59, 65, 62, 64, 53, 62, 65, 80, 72, 81, 53, 90, 81, 76, 56, 60, 58, 52, 49, 61, 74, 57, 66, 62, 72, 77, 90, 54, 85, 92, 88, 90, 63, 41, 40, 54, 60, 71, 91, 92, 71, 91, 92, 66, 35, 50, 50, 52, 53, 57, 61, 63, 75, 66, 76, 77, 90, 78, 80, 75, 73, 52, 48, 56, 49, 52, 72, 75, 63, 62, 66, 51, 48, 66, 69, 79, 67, 57, 57, 50, 57, 71, 61, 63, 90, 50, 48, 55, 66, 82, 69, 61, 54, 44, 47, 73, 86, 35, 55, 52, 66, 53, 48, 61, 54, 55, 55, 74, 41, 37, 46, 76, 42, 40, 44, 41, 34, 34, 34, 40, 63, 51, 37, 33, 45, 56, 50, 57, 31, 43, 39, 30, 47, 55, 84, 53, 45, 56, 52, 65, 73, 86, 65, 24, 31, 34, 57, 58, 21, 25, 34, 25, 72, 71, 68, 72, 29, 40, 61, 54, 57, 52, 67, 58, 67, 51, 42, 33, 55, 71, 71, 65, 61, 68, 44, 64, 64, 71, 86, 86, 60, 35, 54, 57, 59, 49, 23, 88, 89, 67, 61, 49, 52, 64, 60, 56, 66, 64, 59, 66, 63, 49, 58, 57, 70, 71, 66, 53, 89, 86, 61, 52, 57, 73, 53, 68, 68, 59, 56, 55, 64, 26, 61, 62, 49, 50, 60, 34, 68, 70, 67, 63, 74, 67, 36, 83, 70, 79, 78, 50, 55, 88, 79, 72, 61, 72, 67, 29, 68, 66, 63, 66, 79, 69, 32, 41, 50, 55, 69, 89, 67, 60, 63, 87, 81, 89, 87, 78, 63, 73, 67, 69, 73, 61, 62, 68, 71, 76, 84, 83, 88, 86, 74, 77, 82, 72, 85, 81, 74, 76, 76, 84, 70, 56, 63, 66, 90, 78, 72, 69, 69, 68, 62, 51, 56, 71, 80, 69, 72, 75, 68, 73, 72, 83, 68, 68, 74, 74, 69, 46, 51, 60, 66, 78, 65, 61, 78, 74, 77, 47, 49, 67, 70, 73, 78, 86, 89, 75, 59, 72, 79, 78, 86, 69, 84, 82, 77, 60, 58, 77, 83, 44, 60, 58, 54, 61, 64, 77, 78, 58, 82, 91, 90, 85, 90, 92, 82, 82, 89, 79, 81, 83, 79, 88, 73, 78, 85, 56, 73], 'Humidity3pm': [84, 73, 86, 90, 74, 62, 80, 61, 91, 53, 53, 67, 70, 51, 56, 52, 62, 59, 65, 60, 62, 66, 45, 40, 54, 65, 52, 88, 51, 46, 54, 57, 57, 64, 65, 75, 71, 64, 50, 58, 60, 69, 62, 64, 69, 60, 58, 60, 58, 80, 60, 57, 72, 58, 38, 42, 51, 65, 22, 31, 54, 34, 21, 37, 50, 55, 70, 75, 62, 60, 61, 59, 75, 64, 71, 85, 72, 75, 61, 75, 70, 55, 89, 80, 38, 28, 33, 41, 50, 56, 44, 52, 47, 34, 48, 44, 45, 60, 67, 67, 63, 67, 64, 60, 66, 41, 36, 36, 38, 64, 52, 53, 39, 58, 58, 71, 74, 76, 58, 61, 74, 90, 90, 88, 84, 70, 49, 71, 89, 68, 70, 64, 42, 52, 87, 83, 73, 69, 69, 60, 40, 54, 43, 45, 43, 38, 32, 43, 42, 35, 34, 35, 42, 88, 48, 59, 55, 49, 43, 38, 27, 45, 58, 54, 70, 50, 38, 21, 32, 55, 31, 31, 61, 70, 81, 47, 41, 79, 59, 43, 42, 46, 32, 34, 45, 52, 70, 75, 38, 37, 38, 35, 28, 34, 28, 33, 42, 35, 33, 32, 35, 44, 87, 53, 47, 48, 51, 59, 62, 65, 71, 41, 39, 64, 64, 88, 88, 51, 51, 43, 44, 60, 35, 47, 79, 23, 25, 58, 61, 47, 17, 61, 33, 60, 50, 54, 53, 62, 62, 63, 48, 69, 39, 20, 88, 86, 71, 42, 47, 58, 57, 65, 69, 43, 84, 55, 42, 49, 82, 48, 55, 59, 74, 75, 51, 47, 57, 38, 70, 91, 70, 24, 64, 60, 35, 62, 60, 45, 60, 47, 60, 56, 49, 54, 65, 57, 73, 64, 50, 60, 78, 59, 46, 30, 55, 49, 63, 55, 64, 75, 79, 55, 21, 65, 19, 57, 70, 56, 78, 72, 60, 66, 58, 92, 25, 32, 43, 48, 73, 68, 58, 69, 50, 57, 56, 78, 60, 71, 70, 63, 68, 72, 42, 22, 57, 49, 58, 60, 64, 67, 72, 47, 53, 57, 61, 56, 49, 39, 61, 48, 46, 57, 54, 55, 45, 58, 20, 51, 72, 93, 60, 67, 59, 54, 66, 63, 60, 71, 58, 64, 34, 53, 81, 89, 61, 56, 90, 67, 66, 62, 71, 62, 60, 68, 68, 59, 63, 57, 63, 58, 50, 61, 60, 60, 55, 49, 37, 48, 58, 77, 69, 53, 70, 57, 76, 64, 61, 29, 48, 52, 67, 69, 58, 58, 61, 59, 60, 56, 59, 49, 66, 65, 89, 73, 79, 73, 58, 67, 59, 55, 59, 58, 65, 69, 84, 70, 25, 38, 51, 56, 62, 59, 64, 65, 60, 63, 40, 29, 26, 30, 63, 88, 53, 56, 61, 53, 61, 61, 44, 61, 46, 46, 55, 51, 39, 31, 34, 38, 40, 52, 53, 62, 62, 85, 80, 48, 61, 57, 86, 72, 65, 78, 67, 67, 68, 87, 86, 55, 45, 42, 34, 44, 32, 28, 41, 40, 61, 40, 88, 87, 85, 46, 87, 82, 59, 58, 49, 50, 51, 79, 54, 47, 54, 27, 32, 41, 34, 32, 48, 60, 61, 63, 65, 58, 56, 53, 34, 42, 47, 59, 42, 37, 34, 43, 39, 42, 51, 54, 68, 34, 38, 41, 39, 38, 33, 46, 29, 33, 40, 55, 21, 41, 55, 59, 64, 32, 35, 62, 35, 27, 20, 45, 50, 58, 33, 47, 51, 59, 26, 20, 37, 21, 59, 23, 30, 36, 58, 84, 43, 35, 58, 57, 56, 35, 38, 47, 27, 17, 60, 66, 79, 25, 51, 63, 30, 67, 34, 36, 26, 33, 19, 23, 31, 45, 34, 10, 68, 89, 61, 65, 64, 29, 48, 76, 59, 57, 63, 21, 34, 28, 19, 43, 61, 57, 62, 28, 63, 70, 56, 94, 60, 56, 60, 65, 58, 68, 18, 76, 68, 57, 60, 89, 61, 54, 64, 54, 60, 56, 63, 62, 59, 51, 63, 52, 45, 19, 68, 74, 74, 67, 41, 51, 20, 61, 59, 44, 52, 61, 64, 58, 62, 70, 59, 70, 30, 55, 61, 69, 62, 70, 51, 83, 34, 59, 64, 53, 85, 80, 83, 55, 57, 83, 56, 79, 74, 58, 60, 71, 59, 59, 51, 56, 60, 65, 69, 75, 74, 63, 68, 14, 31, 34, 58, 64, 17, 66, 70, 69, 72, 81, 53, 66, 70, 66, 60, 66, 76, 88, 95, 86, 70, 65, 61, 60, 32, 80, 92, 67, 57, 56, 51, 51, 54, 59, 46, 60, 52, 46, 58, 60, 72, 84, 52, 53, 67, 83, 77, 68, 65, 35, 67, 49, 54, 52, 50, 57, 54, 54, 51, 60, 68, 56, 57, 60, 58, 61, 52, 66, 66, 56, 88, 67, 45, 46, 56, 59, 64, 62, 65, 71, 55, 41, 33, 22, 46, 49, 62, 64, 63, 65, 57, 63, 63, 50, 49, 70, 46, 41, 32, 35, 64, 74, 30, 60, 54, 41, 34, 33, 46, 50, 61, 19, 29, 36, 35, 47, 60, 68, 92, 62, 55, 58, 58, 93, 68, 84, 94, 62, 53, 87, 56, 68, 60, 63, 90, 94, 67, 70, 77, 62, 34, 30, 37, 42, 50, 50, 56, 59, 69, 40, 80, 90, 64, 65, 50, 53, 36, 36, 41, 40, 65, 38, 56, 83, 67, 70, 83, 65, 76, 61, 78, 33, 34, 46, 39, 40, 53, 53, 54, 69, 62, 54, 64, 69, 49, 90, 77, 62, 37, 35, 36, 62, 44, 33, 40, 50, 50, 58, 90, 35, 47, 44, 36, 37, 31, 26, 53, 23, 26, 33, 48, 65, 28, 24, 33, 35, 40, 56, 60, 33, 74, 64, 84, 35, 33, 51, 54, 56, 34, 44, 61, 24, 87, 30, 33, 45, 66, 65, 66, 61, 63, 69, 33, 74, 82, 77, 72, 48, 73, 28, 30, 57, 58, 63, 82, 75, 56, 69, 53, 59, 64, 64, 77, 59, 54, 68, 53, 81, 59, 52, 54, 72, 43, 56, 95, 65, 61, 59, 58, 54, 58, 53, 72, 56, 64, 77, 91, 89, 78, 74, 80, 67, 63, 68, 62, 72, 56, 40, 51, 69, 91, 71, 44, 44, 32, 26, 61, 57, 47, 61, 56, 78, 50, 56, 63, 65, 58, 62, 84, 60, 57, 57, 67, 62, 67, 65, 79, 71, 65, 53, 61, 65, 68, 57, 73, 55, 60, 55, 57, 36, 64, 73, 71, 59, 48, 56, 49, 49, 70, 54, 73, 22, 77, 58, 52, 83, 70, 60, 76, 88, 59, 54, 64, 67, 70, 67, 49, 62, 78, 45, 49, 41, 65, 63, 65, 39, 59, 35, 63, 50, 44, 48, 60, 38, 68, 76, 69, 60, 79, 62, 65, 66, 67, 84, 81, 82, 73, 41, 36, 42, 77, 87, 59, 59, 61, 68, 57, 75, 66, 54, 51, 48, 52, 34, 63, 45, 37, 27, 40, 33, 36, 48, 59, 58, 70, 69, 56, 59, 37, 75, 69, 51, 62, 67, 77, 91, 62, 63, 75, 58, 62, 47, 62, 38, 28, 40, 60, 80, 67, 62, 78, 63, 68, 40, 39, 39, 38, 37, 30, 36, 40, 53, 39, 51, 62, 87, 59, 67, 57, 43, 55, 27, 30, 28, 29, 32, 29, 23, 31, 48, 35, 84, 62, 86, 49, 72, 83, 92, 95, 67, 46, 53, 32, 59, 41, 32, 43, 31, 53, 37, 41, 50, 30, 44, 77, 43, 37, 39, 47, 83, 51, 71, 58, 62, 80, 27, 74, 47, 56, 49, 69, 51, 64, 60, 75, 63, 28, 62, 60, 57, 51, 54, 57, 62, 28, 39, 60, 67, 31, 32, 43, 50, 14, 62, 49, 71, 59, 67, 20, 42, 57, 14, 76, 92, 45, 53, 84, 38, 27, 46, 63, 50, 47, 47, 62, 64, 74, 31, 62, 36, 65, 51, 70, 68, 51, 38, 42, 55, 50, 39, 64, 71, 21, 86, 52, 50, 58, 69, 99, 45, 55, 46, 50, 55, 67, 58, 57, 63, 63, 43, 51, 56, 50, 73, 94, 68, 64, 57, 63, 75, 86, 76, 89, 73, 34, 63, 76, 41, 41, 50, 45, 72, 69, 58, 71, 63, 57, 65, 89, 77, 49, 49, 48, 48, 47, 51, 75, 63, 57, 77, 69, 62, 62, 68, 64, 52, 39, 48, 54, 48, 52, 57, 59, 61, 57, 52, 66, 59, 28, 18, 39, 52, 60, 67, 70, 61, 63, 58, 82, 50, 55, 84, 91, 68, 70, 81, 62, 52, 68, 66, 82, 83, 61, 70, 63, 63, 66, 60, 63, 81, 60, 66, 59, 52, 47, 67, 60, 66, 60, 60, 55, 59, 61, 60, 66, 55, 44, 92, 58, 83, 81, 65, 58, 53, 60, 71, 39, 61, 59, 64, 57, 79, 60, 69, 88, 64, 57, 53, 72, 75, 31, 26, 55, 60, 65, 84, 60, 55, 56, 59, 64, 56, 62, 54, 45, 59, 72, 28, 40, 55, 54, 54, 63, 72, 58, 85, 81, 82, 72, 72, 85, 47, 32, 49, 57, 51, 52, 43, 55, 64, 53, 38, 55, 37, 44, 37, 30, 50, 43, 28, 35, 40, 41, 50, 46, 40, 37, 82, 52, 64, 88, 93, 37, 41, 50, 52, 69, 63, 63, 67, 94, 94, 57, 64, 79, 42, 46, 44, 87, 96, 66, 91, 65, 52, 91, 38, 36, 37, 45, 47, 56, 32, 38, 87, 58, 66, 70, 41, 28, 36, 40, 43, 72, 52, 71, 57, 67, 67, 44, 79, 62, 31, 33, 36, 34, 33, 50, 38, 54, 62, 85, 50, 48, 32, 45, 45, 36, 52, 38, 37, 32, 27, 27, 22, 25, 26, 18, 76, 35, 43, 35, 33, 43, 47, 36, 54, 25, 23, 26, 41, 18, 24, 38, 45, 37, 33, 13, 10, 22, 31, 51, 67, 83, 36, 44, 54, 61, 66, 45, 60, 46, 50, 46, 29, 63, 59, 59, 29, 30, 53, 45, 40, 16, 59, 81, 32, 46, 52, 58, 87, 39, 52, 41, 23, 46, 56, 56, 57, 23, 40, 41, 48, 46, 66, 40, 47, 55, 48, 52, 57, 38, 58, 63, 61, 61, 68, 64, 86, 54, 45, 51, 51, 71, 62, 81, 50, 57, 45, 50, 59, 59, 55, 63, 56, 69, 74, 74, 63, 62, 68, 61, 54, 60, 56, 56, 65, 14, 44, 54, 59, 50, 77, 49, 53, 65, 67, 14, 59, 59, 52, 63, 61, 52, 64, 70, 90, 92, 71, 58, 64, 85, 78, 56, 49, 48, 55, 52, 57, 53, 49, 64, 58, 52, 68, 70, 65, 35, 44, 48, 53, 50, 41, 73, 65, 49, 73, 64, 34, 48, 53, 38, 56, 41, 79, 89, 55, 75, 62, 61, 73, 57, 43, 47, 55, 54, 49, 69, 65, 69, 39, 68, 56, 39, 43, 27, 45, 30, 51, 29, 73, 71, 61, 51, 51, 56, 38, 60, 55, 51, 54, 53, 69, 59, 53, 31, 34, 36, 33, 31, 30, 37, 32, 79, 71, 47, 50, 45, 58, 75, 60, 67, 40, 61, 68, 44, 53, 70, 59, 55, 53, 63, 67, 54, 90, 45, 46, 46, 50, 56, 52, 65, 57, 58, 83, 90, 77, 90, 63, 64, 83, 87, 82, 56, 46, 53, 38, 30, 31, 35, 36, 84, 71, 62, 46, 61, 60, 58, 67, 48, 72, 73, 38, 29, 28, 42, 46, 38, 32, 56, 64, 35, 49, 61, 54, 31, 29, 29, 34, 30, 49, 74, 43, 33, 38, 40, 25, 22, 29, 36, 34, 28, 25, 26, 30, 32, 42, 42, 53, 30, 60, 38, 59, 53, 34, 62, 41, 56, 52, 29, 70, 23, 73, 69, 14, 22, 27, 56, 59, 66, 91, 42, 28, 21, 30, 42, 51, 54, 32, 32, 20, 39, 13, 35, 35, 32, 26, 41, 37, 41, 24, 44, 49, 36, 10, 49, 62, 10, 34, 32, 32, 10, 43, 43, 59, 48, 65, 16, 18, 31, 42, 55, 61, 68, 49, 56, 61, 63, 11, 38, 47, 51, 51, 44, 37, 62, 91, 66, 59, 45, 62, 75, 83, 91, 55, 66, 64, 67, 60, 51, 69, 46, 48, 60, 83, 49, 49, 44, 52, 63, 32, 39, 45, 45, 46, 33, 40, 59, 63, 56, 59, 60, 52, 54, 59, 40, 57, 66, 34, 56, 88, 51, 64, 63, 47, 49, 55, 62, 22, 52, 54, 70, 26, 63, 60, 53, 59, 49, 61, 53, 53, 53, 58, 57, 51, 60, 65, 68, 60, 54, 61, 45, 48, 52, 56, 45, 44, 45, 59, 55, 51, 83, 46, 48, 52, 53, 52, 54, 60, 68, 64, 79, 82, 83, 56, 68, 82, 40, 44, 56, 51, 59, 54, 44, 78, 68, 75, 86, 75, 58, 62, 58, 64, 64, 53, 55, 46, 52, 56, 55, 62, 74, 25, 33, 57, 54, 58, 60, 63, 89, 67, 72, 77, 66, 59, 55, 64, 66, 67, 70, 74, 63, 86, 63, 53, 58, 82, 55, 74, 88, 69, 64, 57, 39, 31, 42, 56, 31, 32, 36, 28, 67, 63, 87, 67, 61, 28, 44, 35, 46, 31, 32, 35, 41, 65, 62, 51, 59, 51, 52, 54, 51, 40, 55, 41, 33, 41, 58, 30, 41, 45, 43, 59, 46, 31, 61, 58, 61, 70, 54, 42, 53, 80, 85, 60, 59, 73, 49, 62, 52, 48, 53, 49, 36, 46, 51, 57, 54, 31, 49, 57, 35, 35, 31, 39, 34, 37, 29, 36, 36, 54, 33, 33, 36, 35, 51, 22, 32, 32, 33, 47, 64, 74, 52, 33, 35, 57, 60, 64, 59, 57, 48, 59, 42, 38, 41, 27, 31, 21, 23, 36, 45, 58, 40, 43, 36, 64, 62, 27, 45, 78, 46, 49, 53, 70, 74, 90, 80, 54, 65, 61, 85, 64, 61, 87, 54, 51, 65, 84, 55, 51, 66, 45, 52, 57, 73, 65, 60, 56, 28, 32, 52, 72, 66, 55, 31, 33, 41, 49, 51, 53, 66, 65, 51, 45, 50, 17, 16, 28, 45, 58, 68, 23, 64, 30, 54, 49, 58, 61, 61, 69, 42, 52, 43, 45, 46, 49, 74, 49, 54, 56, 70, 59, 55, 26, 18, 63, 32, 23, 57, 64, 75, 57, 56, 60, 53, 61, 66, 51, 68, 39, 50, 27, 48, 45, 59, 57, 46, 60, 54, 76, 56, 66, 63, 69, 56, 55, 74, 59, 61, 81, 42, 70, 69, 85, 54, 48, 48, 67, 51, 70, 44, 50, 61, 69, 81, 71, 71, 66, 53, 61, 66, 50, 57, 69, 76, 70, 66, 66, 64, 50, 55, 64, 78, 92, 78, 77, 32, 57, 63, 23, 43, 61, 64, 61, 58, 61, 54, 44, 88, 93, 92, 47, 28, 42, 55, 59, 45, 58, 54, 53, 50, 58, 66, 65, 59, 61, 61, 55, 59, 57, 56, 60, 63, 67, 74, 62, 63, 66, 77, 72, 60, 62, 57, 57, 54, 63, 56, 22, 57, 62, 57, 79, 65, 52, 65, 49, 51, 45, 55, 49, 54, 65, 55, 59, 64, 93, 53, 24, 20, 45, 59, 64, 58, 72, 57, 89, 93, 54, 62, 42, 39, 42, 58, 69, 63, 50, 54, 66, 44, 89, 51, 69, 94, 96, 94, 56, 59, 49, 81, 41, 50, 77, 65, 83, 95, 86, 66, 33, 29, 31, 31, 36, 33, 35, 34, 32, 34, 61, 50, 66, 84, 66, 58, 58, 56, 50, 44, 52, 55, 40, 60, 65, 52, 59, 25, 41, 56, 53, 42, 45, 43, 36, 29, 92, 69, 57, 46, 52, 79, 94, 92, 84, 88, 59, 88, 45, 47, 41, 74, 40, 44, 53, 54, 56, 37, 40, 46, 31, 35, 34, 85, 64, 46, 61, 48, 42, 41, 31, 42, 68, 51, 78, 55, 64, 54, 57, 70, 58, 29, 31, 28, 40, 50, 30, 31, 28, 30, 29, 42, 46, 39, 40, 44, 56, 41, 27, 37, 23, 38, 61, 63, 29, 46, 54, 59, 63, 32, 73, 95, 53, 59, 44, 43, 31, 44, 39, 39, 46, 28, 54, 53, 68, 32, 32, 39, 41, 44, 51, 60, 59, 25, 60, 57, 44, 54, 72, 60, 47, 74, 62, 63, 48, 51, 49, 55, 62, 65, 57, 47, 13, 16, 26, 56, 57, 51, 60, 65, 55, 77, 60, 63, 52, 64, 56, 54, 55, 43, 74, 55, 54, 59, 53, 47, 45, 40, 48, 61, 59, 53, 89, 83, 80, 87, 69, 65, 48, 45, 66, 69, 60, 70, 70, 43, 46, 17, 54, 13, 56, 58, 52, 55, 14, 60, 55, 65, 65, 34, 59, 49, 44, 46, 57, 64, 58, 63, 13, 50, 56, 59, 65, 82, 60, 53, 53, 79, 90, 59, 52, 48, 77, 47, 50, 38, 50, 52, 52, 51, 84, 89, 87, 91, 66, 53, 52, 53, 52, 70, 59, 71, 45, 49, 55, 54, 39, 48, 76, 59, 62, 64, 54, 63, 64, 86, 62, 26, 52, 45, 59, 55, 56, 49, 54, 54, 47, 46, 58, 58, 54, 53, 62, 51, 34, 47, 60, 52, 67, 59, 51, 58, 45, 60, 55, 53, 60, 47, 52, 58, 53, 55, 59, 57, 57, 55, 59, 66, 60, 63, 54, 66, 58, 59, 67, 36, 81, 65, 63, 51, 51, 62, 59, 63, 64, 84, 31, 42, 58, 19, 64, 71, 58, 46, 54, 70, 57, 51, 46, 68, 57, 62, 51, 49, 77, 68, 68, 66, 69, 69, 85, 49, 53, 56, 54, 61, 65, 54, 55, 60, 27, 41, 54, 42, 60, 74, 72, 35, 21, 35, 32, 50, 41, 59, 26, 34, 29, 51, 56, 66, 32, 21, 29, 48, 27, 70, 29, 30, 87, 74, 60, 73, 82, 85, 43, 40, 40, 32, 41, 34, 34, 51, 42, 45, 42, 60, 64, 89, 52, 38, 34, 43, 33, 31, 45, 74, 36, 33, 36, 42, 58, 55, 47, 86, 80, 64, 69, 54, 26, 26, 27, 35, 65, 73, 45, 58, 90, 79, 44, 31, 39, 31, 47, 32, 34, 34, 50, 37, 54, 77, 89, 67, 71, 64, 52, 52, 33, 30, 37, 31, 46, 54, 59, 35, 40, 37, 35, 32, 67, 57, 90, 48, 50, 45, 36, 38, 62, 53, 46, 91, 39, 33, 54, 58, 55, 67, 60, 31, 53, 53, 69, 55, 31, 29, 44, 79, 38, 47, 78, 63, 48, 63, 75, 44, 22, 42, 50, 40, 34, 45, 14, 25, 16, 20, 16, 50, 40, 24, 26, 32, 57, 37, 36, 37, 78, 23, 20, 47, 55, 69, 42, 33, 46, 34, 63, 57, 66, 61, 28, 37, 32, 50, 33, 16, 27, 46, 57, 67, 62, 59, 59, 21, 52, 45, 52, 53, 36, 58, 55, 64, 54, 39, 46, 53, 66, 63, 57, 57, 51, 24, 55, 60, 65, 83, 56, 61, 14, 52, 56, 53, 36, 16, 81, 86, 27, 55, 47, 52, 50, 52, 56, 55, 55, 51, 60, 48, 30, 34, 62, 70, 54, 60, 45, 69, 57, 57, 52, 57, 49, 47, 52, 57, 52, 57, 57, 44, 52, 53, 68, 42, 50, 51, 33, 62, 64, 57, 59, 56, 54, 58, 79, 56, 63, 65, 41, 44, 89, 85, 55, 35, 51, 59, 32, 73, 52, 51, 59, 58, 48, 18, 36, 47, 52, 56, 87, 54, 47, 61, 67, 69, 85, 86, 76, 49, 62, 56, 54, 51, 47, 50, 63, 67, 67, 85, 81, 79, 76, 66, 72, 57, 71, 70, 58, 66, 62, 69, 71, 88, 53, 48, 59, 49, 60, 45, 42, 41, 49, 35, 56, 48, 75, 51, 41, 55, 30, 55, 55, 63, 48, 58, 60, 58, 61, 65, 45, 39, 51, 59, 40, 33, 67, 45, 54, 39, 25, 41, 45, 52, 56, 71, 67, 74, 49, 39, 52, 62, 72, 58, 49, 65, 65, 31, 43, 56, 65, 37, 30, 37, 43, 39, 50, 66, 57, 41, 43, 85, 84, 64, 70, 85, 59, 62, 78, 69, 69, 67, 62, 69, 60, 52, 53, 56, 35, 32], 'Pressure9am': [1017.6, 1017.9, 1016.7, 1014.2, 1008.3, 1002.7, 999.0, 1008.3, 1006.4, 1014.0, 1017.6, 1010.7, 1009.2, 1017.2, 1020.2, 1023.0, 1024.7, 1021.7, 1018.0, 1013.4, 1011.4, 1009.2, 1007.4, 1007.9, 1017.5, 1018.3, 1014.1, 1010.0, 1015.3, 1020.9, 1026.2, 1025.8, 1020.5, 1024.8, 1024.2, 1021.3, 1023.4, 1025.5, 1025.1, 1022.0, 1021.9, 1019.7, 1022.8, 1022.1, 1024.6, 1024.8, 1023.3, 1021.2, 1014.3, 1017.3, 1022.8, 1023.1, 1018.7, 1011.1, 1008.9, 1014.7, 1017.1, 1015.4, 1013.0, 1015.0, 1023.0, 1019.0, 1009.9, 1020.8, 1024.5, 1027.2, 1026.3, 1026.5, 1024.6, 1022.1, 1020.1, 1018.6, 1016.4, 1019.6, 1025.4, 1026.4, 1025.1, 1025.4, 1027.2, 1026.6, 1023.2, 1023.6, 1024.0, 1021.3, 1011.2, 1005.2, 1007.4, 1020.4, 1024.2, 1019.7, 1018.7, 1019.3, 1021.1, 1018.7, 1017.1, 1014.3, 1019.2, 1021.4, 1022.2, 1023.1, 1023.5, 1023.4, 1023.8, 1022.2, 1017.1, 1008.4, 1007.0, 1015.7, 1020.1, 1022.4, 1028.2, 1026.9, 1025.4, 1025.1, 1025.9, 1024.6, 1025.6, 1030.2, 1032.0, 1028.6, 1029.3, 1027.3, 1026.4, 1023.1, 1020.1, 1021.2, 1025.0, 1032.1, 1030.9, 1027.5, 1022.9, 1022.4, 1012.2, 1022.0, 1024.4, 1024.2, 1026.7, 1025.5, 1020.3, 1018.3, 1020.7, 1023.2, 1023.7, 1027.0, 1024.6, 1017.0, 1025.9, 1027.6, 1024.1, 1017.1, 1011.0, 1012.5, 1022.7, 1029.0, 1031.9, 1029.2, 1024.4, 1020.9, 1018.0, 1014.6, 1016.5, 1027.5, 1024.2, 1021.5, 1020.8, 1022.2, 1019.2, 1010.1, 1016.2, 1015.4, 1006.2, 1024.8, 1031.5, 1029.3, 1022.6, 1018.3, 1013.1, 1011.3, 1017.2, 1016.7, 1016.6, 1004.8, 1013.2, 1020.4, 1020.4, 1019.1, 1014.9, 1017.9, 1016.4, 1021.9, 1016.2, 1016.0, 1021.7, 1023.0, 1021.1, 1013.4, 1011.8, 1021.9, 1024.9, 1028.8, 1026.6, 1022.5, 1016.1, 1022.8, 1029.6, 1029.9, 1023.4, 1028.0, 1025.7, 1023.4, 1011.2, 1022.9, 1026.1, 1032.6, 1034.2, 1024.9, 1014.8, 1016.4, 1019.5, 1025.0, 1022.7, 1019.2, 1014.9, 1014.1, 1011.8, 1009.7, 1015.8, 1026.4, 1021.4, 1015.8, 1010.1, 1019.8, 1011.6, 1015.5, 1030.3, 1031.6, 1024.3, 1021.6, 1009.8, 1013.8, 1020.3, 1020.9, 1016.9, 1014.8, 1015.2, 1018.4, 1009.2, 1017.7, 1018.8, 1026.2, 1029.0, 1027.4, 1025.0, 1021.4, 1021.7, 1022.4, 1025.5, 1024.2, 1025.4, 1022.3, 1022.3, 1020.9, 1022.1, 1023.2, 1023.2, 1018.3, 1016.8, 1015.2, 1020.8, 1024.3, 1022.6, 1010.0, 1021.9, 1024.9, 1009.7, 1015.0, 1015.5, 1009.6, 1014.5, 1001.8, 1017.2, 1023.5, 1023.9, 1020.1, 1019.3, 1013.8, 1013.6, 1016.4, 1019.8, 1017.0, 1011.4, 1001.1, 1001.2, 990.2, 986.7, 1003.5, 1015.6, 1016.6, 1012.7, 1005.0, 1002.2, 1009.9, 1009.1, 1011.1, 1007.7, 1020.2, 1015.0, 1006.9, 1007.9, 1014.3, 1011.2, 1007.1, 1013.8, 1015.8, 995.0, 996.5, 1006.8, 1013.1, 1011.9, 1005.0, 1005.9, 1019.2, 1022.0, 1018.8, 1009.3, 1013.3, 1014.5, 1013.9, 1009.0, 1006.6, 1004.8, 1004.3, 1002.7, 1005.5, 1012.8, 1021.6, 1018.6, 1013.2, 1011.6, 1009.9, 1012.4, 1020.2, 1017.1, 1013.8, 1015.4, 1019.5, 1014.6, 1009.1, 1012.7, 1020.5, 1021.9, 1019.3, 1013.7, 1011.9, 1008.9, 1009.2, 1004.8, 1019.5, 1019.3, 1021.1, 1018.5, 1018.6, 1018.7, 1017.5, 1016.1, 1016.3, 1010.8, 1011.6, 1009.1, 1010.9, 1013.3, 1010.8, 1011.9, 1011.9, 1011.1, 1017.5, 1025.4, 1022.9, 1014.7, 1017.6, 1017.0, 1010.2, 1008.0, 1011.6, 1013.3, 1018.5, 1016.9, 1014.1, 1016.7, 1020.4, 1018.2, 1009.5, 1010.7, 1016.6, 1018.0, 1008.0, 1009.5, 1013.4, 1014.2, 1017.8, 1022.2, 1022.0, 1023.8, 1022.9, 1018.6, 1014.7, 1010.7, 1011.7, 1013.4, 1019.0, 1016.7, 1017.4, 1018.9, 1017.9, 1017.1, 1017.9, 1019.7, 1019.4, 1023.9, 1025.4, 1023.6, 1024.1, 1021.8, 1021.1, 1023.3, 1021.1, 1017.7, 1020.1, 1020.5, 1025.6, 1026.9, 1025.5, 1023.6, 1025.4, 1022.5, 1015.1, 1011.1, 1015.2, 1016.3, 1020.0, 1019.9, 1020.7, 1022.8, 1024.3, 1021.8, 1012.7, 1004.4, 1003.1, 1013.0, 1015.5, 1022.3, 1020.5, 1024.6, 1025.1, 1027.8, 1028.5, 1030.7, 1028.3, 1024.3, 1027.5, 1024.2, 1024.6, 1025.2, 1021.6, 1016.8, 1012.6, 1012.8, 1008.2, 1018.7, 1025.7, 1024.5, 1022.1, 1023.9, 1023.6, 1023.6, 1026.8, 1025.8, 1022.3, 1020.4, 1021.4, 1023.3, 1028.2, 1033.3, 1032.9, 1030.1, 1025.9, 1020.7, 1014.7, 1014.1, 1008.2, 1009.8, 1011.5, 1012.2, 1020.9, 1024.3, 1017.7, 1014.5, 1013.1, 1017.9, 1027.6, 1030.0, 1030.2, 1028.0, 1023.9, 1020.3, 1019.9, 1015.2, 1014.6, 1012.7, 1008.1, 1006.3, 1012.3, 1013.2, 1005.8, 1007.9, 1003.5, 1012.5, 1016.4, 1020.8, 1025.0, 1029.6, 1030.9, 1028.1, 1022.6, 1014.6, 1007.5, 1007.4, 1010.1, 1012.3, 1019.2, 1022.5, 1021.1, 1025.1, 1021.2, 1011.5, 1012.7, 1026.0, 1026.1, 1019.1, 1016.3, 1022.5, 1024.3, 1024.4, 1020.0, 1025.4, 1027.7, 1020.3, 1021.7, 1022.8, 1023.6, 1015.8, 1023.4, 1020.8, 1019.8, 1016.3, 1012.6, 1014.1, 1019.1, 1019.6, 1015.7, 1013.4, 1028.0, 1027.7, 1019.5, 1009.2, 1012.7, 1012.0, 1006.1, 1007.1, 1013.1, 1017.6, 1016.4, 1008.9, 1011.4, 1017.4, 1021.6, 1024.7, 1020.7, 1014.8, 1016.1, 1018.9, 1008.5, 1008.2, 1010.2, 1015.9, 1022.6, 1022.5, 1019.6, 1021.8, 1021.4, 1023.0, 1017.0, 1017.9, 1019.2, 1014.8, 1014.7, 1002.8, 996.8, 1012.1, 1013.5, 1004.3, 1006.4, 1007.6, 1014.1, 1017.7, 1013.4, 1013.4, 1011.9, 1021.5, 1020.3, 1020.6, 1014.2, 1018.0, 1025.4, 1029.7, 1025.2, 1011.8, 1002.0, 1000.7, 1008.4, 1012.0, 1020.8, 1027.4, 1027.1, 1023.5, 1019.8, 1024.9, 1019.9, 1019.5, 1016.0, 1023.7, 1029.5, 1023.2, 1025.2, 1024.5, 1021.0, 1011.9, 1017.9, 1020.9, 1027.6, 1030.5, 1030.7, 1027.2, 1022.5, 1022.6, 1020.0, 1020.1, 1016.4, 1012.1, 1008.8, 1008.7, 1013.2, 1010.3, 1009.8, 1009.8, 1005.0, 1021.0, 1026.2, 1022.3, 1017.5, 1009.7, 1006.4, 1000.9, 1008.1, 1016.1, 1022.0, 1022.6, 1015.6, 1015.2, 1017.3, 1011.8, 1009.1, 1011.1, 1011.0, 1012.7, 1018.7, 1016.3, 1021.2, 1022.5, 1020.3, 1013.7, 1014.1, 1015.1, 1021.2, 1016.9, 1011.5, 1016.2, 1017.9, 1014.8, 1021.4, 1025.0, 1020.9, 1013.9, 1007.7, 1015.3, 1020.6, 1018.1, 1015.9, 1018.3, 1021.7, 1018.0, 1016.1, 1019.4, 1013.0, 1010.9, 1017.7, 1018.9, 1014.0, 1004.2, 1002.9, 1009.5, 1010.4, 1012.3, 1013.6, 1007.8, 1016.3, 1014.8, 1010.9, 1015.1, 1012.1, 1008.6, 1018.6, 1016.7, 1015.9, 1017.8, 1014.9, 1013.9, 1010.1, 1015.7, 1021.6, 1022.9, 1023.0, 1020.6, 1017.1, 1008.7, 1011.9, 1007.3, 1006.7, 1011.8, 1016.7, 1022.4, 1024.8, 1021.9, 1018.0, 1015.4, 1013.6, 1021.7, 1026.4, 1027.0, 1021.6, 1017.1, 1018.9, 1019.3, 1019.4, 1016.2, 1011.5, 1011.9, 1013.8, 1011.6, 1013.4, 1020.8, 1031.1, 1035.0, 1034.3, 1030.4, 1025.7, 1023.5, 1025.7, 1026.5, 1022.2, 1021.0, 1017.9, 1020.1, 1020.1, 1021.6, 1023.4, 1019.1, 1019.6, 1019.2, 1016.9, 1019.8, 1019.5, 1018.3, 1019.9, 1021.4, 1022.9, 1021.1, 1020.5, 1016.6, 1012.5, 1014.8, 1010.5, 1007.9, 1014.3, 1021.8, 1022.8, 1021.9, 1027.0, 1028.1, 1026.0, 1025.2, 1023.4, 1022.9, 1020.6, 1014.3, 1013.2, 1024.3, 1020.4, 1021.0, 1019.9, 1025.2, 1027.6, 1024.8, 1027.6, 1021.3, 1012.2, 1020.0, 1022.4, 1021.9, 1022.0, 1020.3, 1012.6, 1017.9, 1018.8, 1018.4, 1017.6, 1020.9, 1019.7, 1018.2, 1022.1, 1023.1, 1020.6, 1021.5, 1023.6, 1019.7, 1011.7, 1004.8, 1018.0, 1021.0, 1009.5, 1003.2, 1008.3, 1019.2, 1020.9, 1023.0, 1018.7, 1014.2, 1014.7, 1024.3, 1023.5, 1012.0, 1017.5, 1019.9, 1022.0, 1029.8, 1034.7, 1032.7, 1028.9, 1016.0, 1025.0, 1032.8, 1036.7, 1031.6, 1025.1, 1017.3, 1021.0, 1021.0, 1020.1, 1020.8, 1024.9, 1026.8, 1025.6, 1029.7, 1027.2, 1016.7, 1023.9, 1029.6, 1028.9, 1022.2, 1023.6, 1020.3, 1008.7, 1015.4, 1025.9, 1028.1, 1022.6, 1017.8, 1022.4, 1026.7, 1028.5, 1032.6, 1030.7, 1029.9, 1034.0, 1035.7, 1029.8, 1019.1, 1016.9, 1012.1, 1019.9, 1015.8, 1016.2, 1019.0, 1018.1, 1020.5, 1024.7, 1022.2, 1023.5, 1019.2, 1008.6, 1001.5, 1011.9, 1014.5, 1006.2, 1011.5, 1022.0, 1020.5, 1007.7, 1012.4, 1017.0, 1023.7, 1017.1, 1012.3, 1008.1, 1003.5, 1008.1, 1021.8, 1027.1, 1025.3, 1017.8, 1016.3, 1025.8, 1014.2, 1007.9, 1018.6, 1023.4, 1027.3, 1017.5, 1004.1, 1017.4, 1022.5, 1015.8, 1016.4, 1014.8, 1021.1, 1017.4, 1022.0, 1024.0, 1023.0, 1026.5, 1024.7, 1022.2, 1016.0, 1020.1, 1029.8, 1030.0, 1026.2, 1011.2, 999.6, 999.3, 1012.9, 1028.8, 1025.9, 1021.4, 1016.6, 1021.1, 1018.0, 1016.0, 1021.5, 1020.7, 1015.1, 1012.0, 1014.7, 1011.8, 1018.1, 1022.3, 1023.9, 1023.8, 1021.3, 1017.2, 1025.0, 1021.8, 1014.9, 1015.7, 1012.8, 1013.3, 1017.1, 1015.2, 1021.8, 1026.0, 1025.3, 1020.5, 1017.3, 1015.6, 1010.9, 1013.6, 1016.4, 1016.4, 1018.0, 1017.3, 1013.0, 1014.2, 1016.5, 1016.7, 1010.8, 1009.4, 1007.9, 1004.0, 1013.5, 1010.8, 1003.8, 1005.7, 1003.1, 1003.5, 997.6, 1008.7, 1018.5, 1018.1, 1026.1, 1017.2, 1006.3, 1005.5, 1018.9, 1018.5, 1016.6, 1016.0, 1013.2, 1011.9, 1014.5, 1014.1, 1008.0, 1010.8, 1013.6, 1013.8, 1014.4, 1016.4, 1014.5, 1012.3, 1014.8, 1012.4, 1009.4, 1010.2, 1002.8, 1007.5, 1009.8, 1013.5, 1015.2, 1016.3, 1012.2, 1004.1, 1008.0, 1011.5, 1013.5, 1019.0, 1021.6, 1020.2, 1015.0, 1011.3, 1015.3, 1011.0, 1014.7, 1010.0, 1012.7, 1023.9, 1019.5, 1024.5, 1023.4, 1016.0, 1014.7, 1017.5, 1023.6, 1023.7, 1019.7, 1013.7, 1014.7, 1011.2, 1006.4, 1012.7, 1021.6, 1023.1, 1019.9, 1014.5, 1012.5, 1008.3, 1009.9, 1002.4, 1017.1, 1009.1, 1011.7, 1022.5, 1026.9, 1024.8, 1019.7, 1015.2, 1013.3, 1016.0, 1020.8, 1021.5, 1019.4, 1021.4, 1017.2, 1019.4, 1015.2, 1014.1, 1012.4, 1006.6, 1001.3, 1002.6, 1005.0, 1007.8, 1019.2, 1024.6, 1026.7, 1025.8, 1019.9, 1022.7, 1018.9, 1016.6, 1015.0, 1016.4, 1021.1, 1023.9, 1019.5, 1014.0, 1014.5, 1015.6, 1009.2, 1010.7, 1012.0, 1016.0, 1028.8, 1030.1, 1030.5, 1032.6, 1031.5, 1028.3, 1025.4, 1021.0, 1005.4, 1005.1, 1011.1, 1016.6, 1019.1, 1023.8, 1025.1, 1020.5, 1019.5, 1025.3, 1025.3, 1019.7, 1015.4, 1018.0, 1016.1, 1017.7, 1015.0, 1013.4, 1016.0, 1024.4, 1025.5, 1023.9, 1021.2, 1023.3, 1021.2, 1008.2, 1011.6, 1016.4, 1015.5, 1005.3, 1010.6, 1016.8, 1026.7, 1031.3, 1026.8, 1028.1, 1034.2, 1036.8, 1037.9, 1031.6, 1026.6, 1022.1, 1014.1, 1008.8, 1010.2, 1007.5, 1022.4, 1018.8, 1014.5, 1017.6, 1022.2, 1018.2, 1025.7, 1034.7, 1031.7, 1025.2, 1018.5, 1014.6, 1012.7, 1016.6, 1018.3, 1020.4, 1019.9, 1017.9, 1020.0, 1027.1, 1029.3, 1027.0, 1024.6, 1022.3, 1022.7, 1023.1, 1023.2, 1026.5, 1025.4, 1021.2, 1017.1, 1010.9, 1008.2, 1007.2, 1008.5, 1018.0, 1024.5, 1025.8, 1026.4, 1021.9, 1018.4, 1008.4, 1014.2, 1028.8, 1034.8, 1038.0, 1036.1, 1030.4, 1025.4, 1025.4, 1021.8, 1021.3, 1017.2, 1022.8, 1023.7, 1024.2, 1029.5, 1030.9, 1027.9, 1026.2, 1019.6, 1019.2, 1020.9, 1009.0, 1010.3, 1013.0, 1023.0, 1025.6, 1022.3, 1022.5, 1018.3, 1017.3, 1013.3, 1020.6, 1004.7, 1020.1, 1024.0, 1015.9, 1021.4, 1018.6, 1024.8, 1023.1, 1015.7, 997.8, 1003.8, 1006.5, 1012.8, 1023.0, 1024.6, 1022.6, 1016.5, 1013.6, 1011.3, 1008.1, 1010.0, 1011.1, 1017.4, 1023.2, 1020.8, 1010.7, 1014.1, 1031.2, 1034.8, 1031.4, 1028.0, 1023.8, 1024.7, 1022.2, 1013.7, 1010.6, 1022.7, 1024.0, 1019.8, 1011.1, 1012.1, 1020.8, 1020.1, 1011.3, 1013.0, 1019.3, 1019.6, 1013.1, 1013.2, 1014.4, 1014.4, 1011.6, 1024.7, 1019.4, 1019.3, 1017.0, 1020.5, 1018.6, 1015.3, 1010.2, 1018.4, 1011.0, 1016.4, 1026.6, 1021.8, 1007.6, 1006.7, 1017.4, 1017.1, 1010.5, 1020.7, 1022.2, 1020.4, 1014.3, 1021.1, 1020.1, 1016.3, 1014.2, 1014.9, 1011.5, 1003.8, 1006.9, 1007.9, 1015.8, 1019.7, 1021.4, 1023.1, 1020.0, 1011.2, 1013.2, 1018.3, 1018.5, 1014.9, 1013.9, 1012.1, 1006.4, 1010.0, 1013.8, 1014.4, 1019.4, 1020.8, 1017.9, 1018.4, 1018.3, 1012.6, 1018.0, 1015.1, 1015.6, 1009.3, 1006.8, 1009.7, 1004.1, 1015.7, 1017.3, 1017.2, 1019.4, 1022.9, 1023.3, 1017.6, 1017.3, 1015.4, 1021.4, 1022.7, 1018.5, 1014.3, 1014.0, 1017.5, 1015.9, 1011.5, 1002.2, 1005.2, 1014.4, 1012.0, 1006.8, 1005.1, 1003.9, 1002.4, 1007.5, 1011.2, 1013.7, 1012.3, 1011.4, 1015.3, 1018.2, 1021.2, 1021.8, 1020.0, 1017.4, 1017.2, 1017.9, 1011.8, 1010.3, 1016.1, 1019.8, 1022.6, 1023.6, 1020.8, 1017.4, 1013.3, 1013.9, 1007.7, 1013.4, 1019.6, 1014.3, 1013.4, 1018.8, 1018.1, 1005.4, 1008.8, 1013.5, 1019.0, 1020.2, 1022.3, 1020.6, 1017.2, 1012.8, 1014.0, 1022.3, 1023.7, 1020.6, 1010.8, 1009.5, 1003.6, 1012.6, 1022.1, 1023.6, 1023.6, 1023.2, 1019.4, 1019.1, 1018.9, 1018.3, 1017.8, 1016.0, 1017.8, 1021.3, 1021.6, 1015.2, 1019.2, 1016.6, 1024.5, 1030.6, 1032.8, 1031.9, 1028.2, 1025.2, 1023.9, 1022.9, 1021.1, 1019.7, 1016.5, 1015.5, 1014.0, 1011.7, 1011.6, 1018.5, 1022.0, 1022.0, 1020.8, 1027.3, 1027.2, 1023.0, 1019.7, 1020.6, 1016.8, 1016.9, 1018.2, 1018.7, 1021.1, 1021.7, 1018.5, 1017.6, 1013.4, 1021.4, 1024.3, 1025.0, 1025.0, 1025.1, 1023.1, 1026.1, 1025.5, 1024.2, 1024.4, 1020.5, 1012.5, 1013.9, 1020.3, 1026.5, 1031.6, 1035.0, 1033.6, 1029.6, 1022.3, 1014.6, 1004.2, 1000.4, 1016.1, 1023.2, 1026.0, 1026.7, 1026.2, 1022.5, 1020.5, 1021.1, 1019.4, 1016.7, 1018.2, 1018.8, 1022.1, 1019.6, 1022.8, 1016.4, 1006.6, 1022.2, 1028.1, 1030.7, 1031.7, 1026.1, 1016.1, 1013.6, 1016.2, 1016.0, 1020.3, 1024.6, 1031.0, 1033.1, 1032.5, 1031.2, 1030.4, 1026.6, 1020.1, 1017.5, 1011.6, 1013.2, 1016.9, 1027.5, 1026.5, 1019.4, 1020.2, 1025.9, 1029.3, 1029.6, 1027.9, 1023.9, 1015.4, 1012.6, 1016.2, 1022.5, 1024.2, 1025.8, 1022.5, 1022.3, 1017.8, 1017.9, 1016.1, 1014.8, 1024.4, 1022.0, 1014.7, 1015.4, 1016.8, 1014.7, 1007.7, 1007.0, 1020.3, 1024.3, 1020.6, 1015.5, 1009.5, 1014.2, 1018.0, 1018.7, 1010.5, 1016.6, 1021.9, 1024.3, 1022.2, 1022.9, 1016.0, 1007.7, 1005.8, 1014.5, 1025.0, 1023.1, 1006.2, 1019.6, 1024.9, 1021.9, 1019.4, 1018.4, 1016.0, 1019.3, 1012.7, 1016.2, 1011.5, 1012.6, 1022.1, 1022.5, 1018.7, 1009.7, 1019.2, 1027.9, 1032.7, 1026.3, 1018.8, 1014.0, 1019.2, 1013.8, 1017.1, 1012.8, 1005.4, 1006.3, 1019.8, 1025.6, 1024.9, 1018.4, 1016.4, 1022.7, 1016.4, 1007.8, 1013.7, 1016.2, 1027.4, 1024.3, 1013.0, 1010.6, 1015.7, 1025.5, 1025.1, 1019.8, 1016.1, 1008.3, 1015.2, 1020.9, 1020.5, 1018.7, 1015.8, 1013.8, 1011.9, 1014.0, 1022.7, 1028.6, 1025.0, 1020.3, 1019.5, 1014.7, 1012.7, 1016.7, 1012.9, 1014.2, 1022.2, 1018.1, 1017.1, 1020.3, 1018.8, 1013.9, 1015.9, 1014.1, 1018.4, 1016.5, 1013.6, 1012.0, 1013.8, 1018.8, 1016.7, 1016.1, 1021.0, 1022.5, 1005.8, 999.3, 1009.7, 1010.1, 1005.8, 1011.5, 1015.2, 1019.4, 1014.6, 1012.5, 1002.9, 1013.2, 1017.3, 1015.8, 1010.4, 1015.3, 1017.5, 1012.9, 1012.5, 1009.2, 1009.2, 1001.7, 1014.7, 1013.2, 1014.4, 1021.0, 1021.6, 1021.9, 1021.7, 1020.9, 1019.9, 1022.1, 1021.3, 1020.1, 1020.7, 1021.0, 1014.5, 1012.0, 1016.1, 1013.6, 1013.0, 1021.1, 1024.2, 1025.4, 1019.4, 1013.5, 1016.5, 1015.9, 1018.3, 1019.4, 1019.0, 1016.8, 1018.5, 1017.6, 1011.4, 1017.9, 1016.0, 1020.9, 1028.2, 1030.4, 1028.0, 1024.5, 1025.3, 1026.7, 1024.8, 1023.5, 1025.9, 1021.5, 1013.9, 1010.1, 1015.0, 1016.7, 1014.7, 1014.7, 1013.7, 1016.1, 1011.0, 1012.7, 1018.9, 1021.8, 1022.6, 1022.0, 1019.0, 1022.4, 1025.6, 1018.7, 1025.3, 1026.7, 1017.9, 1025.1, 1026.6, 1028.7, 1031.1, 1030.7, 1030.8, 1030.2, 1027.2, 1018.9, 1013.8, 1013.2, 1010.3, 1011.9, 1014.7, 1016.8, 1018.7, 1015.3, 1015.0, 1013.7, 1019.1, 1023.7, 1025.7, 1029.4, 1032.8, 1031.4, 1029.3, 1028.0, 1019.4, 1006.1, 1020.5, 1026.3, 1025.8, 1022.8, 1019.8, 1030.7, 1028.6, 1021.6, 1021.0, 1015.1, 1007.0, 1005.2, 1009.9, 1014.4, 1009.5, 1013.5, 1021.7, 1024.2, 1021.6, 1024.9, 1028.5, 1021.7, 1016.3, 1019.8, 1022.9, 1023.7, 1024.8, 1025.7, 1024.4, 1024.9, 1024.4, 1016.3, 1010.9, 1020.1, 1026.9, 1031.7, 1035.0, 1033.5, 1035.3, 1031.1, 1029.2, 1028.4, 1024.6, 1024.7, 1023.8, 1022.9, 1015.7, 1009.3, 1016.0, 1019.4, 1019.9, 1026.6, 1029.8, 1025.9, 1031.0, 1029.8, 1025.2, 1019.9, 1023.9, 1023.3, 1018.0, 1016.0, 1013.6, 1017.6, 1011.9, 1013.6, 1008.3, 1018.9, 1016.0, 1018.2, 1005.8, 1013.7, 1013.6, 1019.0, 1023.7, 1010.1, 1016.9, 1009.7, 1013.7, 1016.3, 1013.8, 1010.2, 1020.1, 1024.0, 1024.6, 1022.0, 1021.5, 1024.4, 1015.1, 1021.5, 1028.5, 1031.2, 1034.0, 1033.6, 1027.3, 1026.9, 1022.4, 1026.2, 1021.0, 1005.5, 1011.7, 1015.2, 1021.9, 1011.2, 1018.4, 1016.0, 1000.8, 1002.0, 1005.7, 1007.9, 1014.8, 1014.9, 1012.0, 1004.1, 1009.8, 1002.9, 1019.9, 1011.1, 1017.4, 1016.6, 1003.8, 1015.6, 1010.9, 1022.4, 1016.5, 1010.5, 1011.2, 1014.0, 1019.0, 1009.7, 1013.1, 1016.0, 1002.2, 1014.5, 1022.6, 1018.9, 1005.9, 1025.8, 1028.1, 1021.5, 1016.3, 1016.2, 1004.8, 1011.7, 1023.2, 1020.9, 1022.5, 1019.5, 1006.6, 1019.6, 1022.0, 1023.8, 1018.2, 1010.3, 1022.5, 1028.0, 1024.3, 1017.1, 1011.0, 1006.4, 1017.5, 1018.1, 1013.2, 1014.4, 1014.1, 1015.8, 1016.0, 1015.5, 1013.3, 1011.4, 1012.4, 1012.8, 1009.1, 1005.8, 1006.3, 1008.1, 1016.7, 1018.3, 1011.7, 1005.8, 1018.8, 1025.1, 1022.5, 1017.6, 1006.3, 996.7, 1011.7, 1020.4, 1019.0, 1009.1, 1002.5, 1009.7, 1011.9, 1012.5, 1014.8, 1018.6, 1020.6, 1021.8, 1024.2, 1022.5, 1016.3, 1016.8, 1012.6, 1007.2, 1018.3, 1019.3, 1012.3, 1012.5, 1012.3, 1009.5, 1015.3, 1013.2, 1014.6, 1003.6, 1005.3, 1003.4, 1010.5, 1008.9, 1018.3, 1023.7, 1024.3, 1022.2, 1018.9, 1017.7, 1021.9, 1022.3, 1021.7, 1019.2, 1016.7, 1012.6, 1010.0, 1009.2, 1010.2, 1017.7, 1023.2, 1014.0, 1012.0, 1023.8, 1024.4, 1021.5, 1017.0, 1019.9, 1014.9, 1015.2, 1015.6, 1015.7, 1017.1, 1023.9, 1020.3, 1017.7, 1018.1, 1018.9, 1019.5, 1017.6, 1016.5, 1015.1, 1008.1, 1003.7, 999.5, 1013.5, 1013.0, 1004.8, 1007.8, 1016.0, 1020.3, 1023.4, 1020.7, 1017.9, 1011.8, 1017.3, 1022.7, 1020.5, 1020.3, 1024.8, 1026.1, 1018.6, 1018.6, 1020.3, 1022.6, 1023.6, 1023.4, 1023.6, 1018.1, 1020.4, 1018.4, 1013.0, 1005.5, 1016.9, 1021.0, 1023.9, 1026.9, 1022.5, 1017.8, 1017.6, 1016.4, 1020.0, 1022.5, 1022.3, 1017.0, 1015.3, 1020.1, 1022.4, 1019.7, 1017.9, 1017.5, 1018.5, 1018.8, 1020.9, 1025.5, 1023.9, 1021.4, 1016.9, 1005.5, 1011.1, 1016.8, 1020.4, 1020.7, 1019.8, 1019.6, 1016.3, 1016.4, 1018.4, 1021.1, 1018.7, 1017.6, 1013.7, 1023.2, 1015.0, 1023.5, 1025.9, 1017.7, 1012.5, 1017.7, 1006.9, 996.5, 1001.9, 1017.9, 1021.2, 1023.8, 1026.2, 1026.3, 1023.9, 1022.2, 1030.1, 1030.5, 1029.3, 1028.7, 1029.4, 1030.4, 1028.3, 1026.0, 1022.9, 1024.4, 1023.5, 1017.9, 1015.4, 1018.3, 1023.4, 1018.0, 1013.8, 1023.1, 1026.8, 1026.9, 1020.5, 1017.2, 1018.4, 1024.1, 1025.7, 1026.3, 1027.2, 1026.9, 1028.4, 1030.5, 1026.6, 1022.0, 1019.4, 1012.1, 1008.9, 1020.8, 1023.4, 1030.1, 1027.8, 1019.9, 1020.4, 1023.0, 1014.9, 1007.1, 1012.2, 1018.8, 1021.0, 1007.2, 1004.5, 1015.1, 1025.0, 1027.6, 1027.3, 1021.3, 1016.2, 1013.6, 1014.4, 1016.6, 1007.6, 1005.8, 1017.4, 1019.6, 1027.4, 1032.0, 1025.8, 1013.7, 1012.6, 1011.2, 1021.2, 1025.7, 1026.9, 1024.6, 1025.5, 1022.5, 1023.0, 1024.9, 1024.6, 1021.3, 1018.0, 1018.0, 1014.2, 1007.2, 1024.6, 1034.1, 1034.4, 1032.0, 1032.6, 1029.6, 1032.1, 1029.9, 1022.4, 1025.4, 1030.0, 1033.3, 1035.0, 1031.6, 1023.8, 1010.3, 1001.8, 1015.3, 1024.7, 1029.2, 1031.8, 1031.6, 1029.7, 1025.7, 1024.3, 1025.3, 1026.8, 1026.7, 1023.9, 1021.1, 1016.9, 1009.1, 1013.3, 1015.9, 1021.8, 1029.7, 1032.0, 1029.5, 1019.4, 1008.2, 1016.7, 1025.7, 1026.9, 1020.6, 1018.6, 1018.6, 1022.3, 1024.5, 1030.5, 1032.1, 1030.2, 1022.7, 1011.9, 1017.9, 1021.1, 1021.9, 1014.6, 1013.7, 1017.7, 1022.1, 1021.1, 1020.2, 1016.0, 1019.2, 1007.8, 1018.7, 1023.2, 1019.5, 1016.8, 1017.5, 1007.6, 1008.5, 1011.7, 1018.4, 1024.6, 1029.8, 1027.5, 1028.7, 1032.5, 1027.1, 1018.0, 1020.1, 1015.3, 1010.2, 1007.8, 1012.2, 1017.2, 1015.6, 1017.9, 1025.4, 1024.0, 1017.1, 1014.8, 1019.4, 1022.4, 1018.8, 1018.2, 1020.1, 1019.7, 1019.2, 1011.8, 1009.9, 1005.6, 1013.8, 1016.7, 1021.8, 1014.3, 1007.4, 1015.9, 1011.5, 1015.0, 1013.0, 1019.7, 1014.2, 1011.0, 1011.9, 1013.2, 1012.5, 1008.3, 1007.7, 1006.0, 1006.8, 1015.0, 1014.8, 1005.5, 1018.6, 1014.4, 1012.2, 1007.9, 1006.3, 1010.3, 1012.4, 1018.5, 1018.6, 1016.9, 1015.4, 1013.7, 1011.5, 1007.8, 1021.0, 1019.2, 1009.7, 1007.4, 1015.6, 1014.5, 1018.8, 1020.2, 1015.9, 1019.4, 1020.7, 1020.6, 1016.1, 1010.6, 1010.8, 1013.6, 1014.7, 1010.2, 999.1, 1004.0, 1008.6, 1008.0, 1011.7, 1014.9, 1014.3, 1011.0, 1014.5, 1010.1, 1008.1, 1003.1, 1013.2, 1013.3, 1013.3, 1012.9, 1009.4, 1008.1, 1009.5, 1015.5, 1020.1, 1015.7, 1023.2, 1027.7, 1025.2, 1018.9, 1023.8, 1024.6, 1023.6, 1021.8, 1024.2, 1023.1, 1017.0, 1016.9, 1019.0, 1019.9, 1021.8, 1018.0, 1017.1, 1017.7, 1016.9, 1014.8, 1015.6, 1010.9, 1010.8, 1010.8, 1005.9, 1018.7, 1015.9, 1013.4, 1005.9, 1007.6, 1012.8, 1011.1, 1011.9, 1017.7, 1016.9, 1014.9, 1019.9, 1018.7, 1010.0, 1017.2, 1015.9, 1007.2, 1011.5, 1010.5, 1024.7, 1024.4, 1018.9, 1012.1, 1017.2, 1017.8, 1020.5, 1023.4, 1023.4, 1024.3, 1026.2, 1025.0, 1018.9, 1023.9, 1020.3, 1010.5, 1008.0, 1007.9, 1010.7, 1020.6, 1024.8, 1023.3, 1018.7, 1023.7, 1023.9, 1025.1, 1022.4, 1024.6, 1017.8, 1018.5, 1023.6, 1019.6, 1013.4, 1012.3, 1008.0, 1008.8, 1008.0, 1018.9, 1026.1, 1030.6, 1031.3, 1028.2, 1020.6, 1014.8, 1016.0, 1008.3, 1014.0, 1018.2, 1019.4, 1017.1, 1011.3, 1010.2, 1014.3, 1015.3, 1024.7, 1031.4, 1035.4, 1035.5, 1031.8, 1020.6, 1015.9, 1018.6, 1016.9, 1029.1, 1032.3, 1032.2, 1030.0, 1025.4, 1023.6, 1020.6, 1022.0, 1016.5, 1014.7, 1023.8, 1023.2, 1022.0, 1019.3, 1028.3, 1029.0, 1024.5, 1020.7, 1031.1, 1036.8, 1034.6, 1031.3, 1028.5, 1027.8, 1022.8, 1012.5, 1014.4, 1017.2, 1024.1, 1028.7, 1029.6, 1026.5, 1023.2, 1023.3, 1032.9, 1032.6, 1032.9, 1033.4, 1029.4, 1026.2, 1020.0, 1026.5, 1022.7, 1022.2, 1016.3, 1019.8, 1028.7, 1030.8, 1022.6, 1015.4, 1003.6, 1000.9, 1011.5, 1018.1, 1016.8, 1010.1, 1025.6, 1032.6, 1034.6, 1033.1, 1027.4, 1026.1, 1020.0, 1017.5, 1017.0, 1025.0, 1032.9, 1035.0, 1026.3, 1021.4, 1018.6, 1015.1, 1015.2, 1023.0, 1014.5, 1016.5, 1024.0, 1024.7, 1024.8, 1017.7, 1014.6, 1007.9, 1014.9, 1025.1, 1030.5, 1027.4, 1017.1, 1020.8, 1027.2, 1028.3, 1025.8, 1021.0, 1021.8, 1018.4, 1013.4, 1018.1, 1019.7, 1019.8, 1022.7, 1020.3, 1017.3, 1015.8, 1018.0, 1006.0, 1021.5, 1022.3, 1024.9, 1018.3, 1018.8, 1023.1, 1030.9, 1032.1, 1028.5, 1028.5, 1025.9, 1015.4, 1017.7, 1018.4, 1026.2, 1026.5, 1024.5, 1019.9, 1016.8, 1025.5, 1025.6, 1029.3, 1028.5, 1023.7, 1021.1, 1019.5, 1022.1, 1026.4, 1033.4, 1030.6, 1023.4, 1024.0, 1023.2, 1029.6, 1038.8, 1034.4, 1028.9, 1022.7, 1016.7, 1022.3, 1026.8, 1026.2, 1021.7, 1023.1, 1029.2, 1026.6, 1020.6, 1013.8, 1011.4, 1022.1, 1024.4, 1022.1, 1014.4, 1025.8, 1025.3, 1023.6, 1023.8, 1021.8, 1015.2, 1011.2, 1017.0, 1017.6, 1014.8, 1007.7, 1012.3, 1020.7, 1021.3, 1016.0, 1020.3, 1020.4, 1013.1, 1014.4, 1017.7, 1020.0, 1019.1, 1013.6, 1015.0, 1012.5, 1015.6, 1019.7, 1011.9, 1017.4, 999.8, 1016.1, 1016.7, 1013.7, 1012.4, 1010.3, 1015.1, 1027.1, 1026.3, 1020.5, 1021.4, 1018.6, 1014.2, 1015.9, 1005.8, 1014.7, 1019.3, 1015.4, 1015.3, 1014.8, 1018.5, 1016.8, 1014.6, 1014.8, 1023.2, 1019.4, 1019.9, 1018.7, 1009.7, 1016.7, 1023.7, 1022.4, 1019.9, 1019.4, 1016.4, 1013.4, 1015.2, 1016.8, 1016.5, 1012.3, 1014.0, 1020.1, 1021.9, 1020.4, 1013.3, 1010.4, 1019.7, 1024.4, 1026.9, 1025.1, 1020.6, 1017.4, 1012.6, 1010.5, 1011.0, 1006.7, 1013.4, 1014.5, 1017.7, 1016.2, 1008.2, 1003.3, 1004.9, 1004.4, 1004.2, 1006.3, 1003.6, 1012.0, 1017.4, 1018.0, 1018.0, 1019.1, 1020.7, 1016.7, 1015.8, 1017.0, 1014.6, 1008.4, 1011.8, 1009.1, 1011.4, 1009.8, 1012.4, 1017.7, 1025.4, 1025.4, 1021.3, 1016.1, 1012.4, 1014.9, 1019.3, 1018.8, 1021.2, 1022.0, 1021.1, 1021.3, 1022.0, 1021.7, 1022.9, 1021.6, 1023.4, 1021.6, 1019.7, 1020.1, 1019.6, 1020.5, 1016.3, 1019.5, 1019.7, 1017.0, 1003.6, 1010.9, 1017.5, 1018.8, 1017.5, 1018.2, 1020.7, 1018.9, 1018.6, 1018.2, 1018.7, 1017.5, 1015.0, 1017.1, 1019.1, 1016.4, 1024.6, 1023.2, 1020.1, 1015.9, 1023.2, 1023.5, 1022.0, 1019.8, 1017.5, 1023.1, 1027.4, 1030.2, 1026.4, 1021.2, 1022.1, 1021.8, 1021.7, 1024.6, 1023.1, 1020.1, 1024.2, 1029.8, 1032.0, 1030.9, 1028.1, 1024.9, 1022.8, 1018.7, 1013.6, 1017.3, 1012.6, 1015.2, 1020.7, 1019.6, 1021.3, 1018.5, 1008.8, 1006.5, 1015.5, 1014.7, 1021.8, 1023.7, 1017.4, 1021.4, 1017.0, 1018.8, 1017.9, 1020.3, 1027.3, 1024.4, 1013.9, 1018.1, 1017.8, 1006.9, 1003.5, 1007.2, 1017.2, 1025.5, 1029.6, 1029.1, 1027.0, 1025.4, 1015.4, 1002.5, 999.8, 1004.1, 1011.4, 1006.8, 1017.4, 1022.5, 1036.2, 1039.0, 1035.8, 1033.4, 1025.5, 1017.7, 1017.4, 1017.2, 999.5, 1003.3, 1004.8, 1012.6, 1003.8, 1018.1, 1021.1, 1015.3, 1022.9, 1028.4, 1025.5, 1026.6, 1020.8, 1011.9, 1004.0, 1015.4, 1019.8, 1023.5, 1025.1, 1015.2, 1010.3, 1017.3, 1029.4, 1030.3, 1033.3, 1031.2, 1024.6, 1021.7, 1019.7, 1019.9, 1009.1, 1004.3, 1015.8, 1012.7, 1014.7, 1012.2, 1024.3, 1023.0, 1023.3, 1018.0, 1017.2, 1013.7, 1018.0, 1030.4, 1029.0, 1027.4, 1026.4, 1023.1, 1015.6, 1018.4, 1024.4, 1022.5, 1027.7, 1032.7, 1031.0, 1026.3, 1024.5, 1020.1, 1015.3, 1019.8, 1016.8, 1014.4, 1013.3, 1010.2, 1018.7, 1023.6, 1022.9, 1027.4, 1026.9, 1018.7, 1020.3, 1011.6, 998.3, 1021.6, 1030.4, 1030.4, 1031.7, 1029.7, 1021.9, 1012.7, 1019.0, 1021.5, 1021.4, 1014.1, 1009.8, 1016.5, 1022.0, 1012.6, 1008.5, 1018.9, 1012.5, 1006.9, 1011.7, 1012.6, 1006.7, 1013.0, 1009.7, 1014.7, 1000.5, 999.1, 1005.0, 1012.9, 999.4, 1007.8, 1016.4, 1019.1, 1021.0, 1016.3, 1022.9, 1007.7, 1013.2, 1016.5, 1021.2, 1025.9, 1023.1, 1014.9, 1005.8, 1014.5, 1017.9, 1024.4, 1018.9, 1010.0, 1018.3, 1019.6, 1018.9, 1016.6, 1015.9, 1020.6, 1020.1, 1013.7, 1011.0, 1014.4, 1014.6, 1018.9, 1014.8, 1002.9, 1009.1, 1011.1, 1007.3, 1013.3, 1009.4, 1012.9, 1002.5, 998.6, 1002.0, 1016.1, 1020.0, 1025.6, 1017.4, 1018.3, 1021.3, 1018.4, 1014.8, 1013.0, 1012.8, 1017.4, 1017.8, 1015.0, 1011.8, 1012.4, 1008.0, 1008.4, 1016.0, 1016.0, 1009.6, 1012.4, 1015.2, 1008.7, 1007.9, 1022.5, 1022.2, 1022.6, 1015.5, 1008.5, 1017.2, 1013.3, 1007.4, 1018.8, 1021.0, 1010.4, 1012.3, 1019.4, 1019.3, 1015.7, 1017.1, 1014.7, 1014.5, 1013.0, 1007.2, 1003.6, 1003.7, 1007.4, 1009.9, 1018.5, 1021.4, 1019.0, 1018.3, 1018.4, 1013.5, 1011.5, 1012.0, 1007.6, 1012.4, 1008.9, 1003.4, 1015.1, 1017.1, 1013.6, 1005.4, 1015.3, 1001.1, 1010.5, 1017.9, 1014.9, 1007.4, 1020.5, 1015.9, 1018.5, 1015.9, 1016.8, 1012.5, 1008.1, 1016.1, 1013.2, 1015.5, 1013.9, 1010.4, 1011.3, 1017.6, 1022.1, 1018.6, 1010.4, 1007.8, 1000.5, 1008.1, 1015.0, 1017.4, 1012.1, 1009.8, 1007.1, 1008.7, 1010.5, 1019.7, 1021.6, 1019.8, 1020.8, 1020.5, 1021.8, 1024.0, 1022.7, 1021.0, 1018.1, 1016.9, 1015.2, 1010.2, 1012.8, 1017.6, 1018.5, 1017.0, 1015.1, 1014.2, 1010.6, 1011.1, 1019.2, 1020.6, 1013.2, 1018.4, 1022.9, 1020.3, 1018.5, 1015.7, 1012.6, 1018.5, 1019.9, 1017.8, 1015.9, 1017.1, 1013.9, 1012.3, 1007.0, 1016.4, 1018.2, 1025.1, 1028.4, 1028.1, 1026.1, 1026.2, 1028.4, 1026.2, 1015.3, 1009.3, 1017.2, 1023.7, 1023.8, 1022.1, 1021.0, 1020.0, 1024.4, 1027.0, 1030.6, 1030.3, 1028.4, 1025.9, 1024.1, 1022.7, 1014.0, 1015.8, 1022.7, 1020.8, 1023.0, 1019.5, 1017.5, 1027.0, 1031.6, 1031.2, 1025.9, 1023.6, 1027.9, 1026.9, 1025.1, 1024.7, 1027.0, 1024.9, 1021.9, 1017.1, 1017.9, 1023.4, 1027.0, 1025.3, 1017.9, 1021.0, 1024.7, 1022.1, 1014.7, 1021.3, 1021.7, 1021.8, 1013.2, 1017.8, 1023.1, 1025.4, 1032.8, 1032.7, 1031.1, 1028.3, 1025.0, 1019.7, 1020.2, 1024.2, 1027.6, 1031.9, 1029.2, 1025.0, 1030.0, 1031.3, 1027.9, 1026.2, 1024.3, 1025.7, 1030.4, 1028.7, 1025.9, 1028.5, 1020.8, 1017.3, 1018.6], 'Pressure3pm': [1017.4, 1016.4, 1015.6, 1011.8, 1004.8, 998.6, 1000.3, 1007.4, 1007.6, 1013.4, 1015.3, 1007.5, 1011.7, 1016.5, 1018.9, 1022.6, 1023.1, 1019.4, 1015.4, 1010.8, 1009.7, 1003.1, 1007.0, 1008.0, 1016.9, 1015.6, 1010.6, 1010.1, 1015.6, 1020.6, 1025.2, 1022.5, 1018.6, 1024.2, 1019.8, 1020.7, 1022.3, 1025.2, 1022.5, 1021.4, 1018.8, 1019.0, 1020.0, 1020.9, 1022.6, 1022.8, 1020.0, 1019.4, 1009.6, 1018.9, 1022.2, 1020.6, 1015.3, 1006.9, 1007.9, 1013.4, 1016.2, 1011.2, 1009.0, 1012.5, 1021.5, 1012.4, 1010.8, 1019.2, 1023.4, 1024.6, 1024.2, 1024.1, 1021.4, 1019.7, 1017.5, 1016.0, 1013.4, 1019.2, 1023.9, 1024.6, 1023.4, 1023.7, 1026.1, 1023.7, 1021.4, 1022.3, 1022.1, 1018.6, 1007.0, 999.1, 1008.6, 1019.8, 1021.3, 1016.7, 1015.3, 1016.9, 1018.3, 1015.2, 1013.3, 1011.8, 1017.5, 1020.2, 1019.6, 1021.2, 1020.5, 1021.7, 1020.5, 1017.8, 1013.0, 1003.6, 1006.3, 1013.3, 1017.5, 1022.8, 1026.2, 1024.6, 1022.7, 1022.2, 1022.6, 1021.8, 1023.9, 1029.1, 1028.7, 1026.66, 1027.0, 1024.8, 1024.1, 1020.5, 1018.6, 1020.3, 1025.7, 1029.8, 1028.0, 1023.9, 1020.6, 1018.1, 1011.5, 1022.5, 1022.8, 1023.0, 1024.8, 1022.1, 1017.4, 1016.2, 1018.9, 1024.0, 1020.4, 1023.1, 1020.6, 1016.8, 1023.6, 1024.7, 1018.8, 1010.3, 1008.5, 1011.2, 1020.8, 1028.2, 1028.9, 1025.7, 1019.7, 1017.4, 1015.7, 1010.0, 1017.0, 1023.5, 1021.2, 1017.3, 1018.4, 1019.1, 1013.3, 1007.3, 1014.1, 1008.6, 1008.1, 1025.2, 1029.6, 1025.4, 1020.1, 1014.3, 1008.6, 1011.3, 1015.1, 1013.7, 1011.6, 1003.3, 1013.3, 1017.7, 1017.1, 1016.1, 1015.6, 1014.6, 1016.9, 1018.1, 1011.8, 1015.4, 1018.8, 1021.9, 1015.6, 1010.2, 1010.5, 1021.8, 1021.2, 1025.4, 1023.2, 1017.1, 1015.5, 1024.1, 1027.9, 1024.8, 1019.3, 1025.3, 1022.3, 1019.1, 1009.555, 1020.8, 1024.4, 1032.4, 1031.0, 1020.8, 1013.1, 1014.1, 1018.2, 1021.9, 1019.1, 1014.2, 1010.8, 1010.4, 1007.4, 1003.4, 1016.5, 1023.4, 1016.2, 1011.0, 1005.9, 1014.4, 1007.0, 1018.0, 1028.6, 1027.8, 1018.4, 1015.7, 1007.1, 1015.6, 1016.777, 1015.7, 1013.5, 1010.3, 1012.9, 1015.3, 1003.9, 1014.4, 1018.6, 1025.7, 1025.4, 1024.3, 1021.8, 1016.6, 1016.0, 1021.2, 1023.4, 1021.0, 1022.0, 1018.5, 1019.3, 1019.6, 1021.9, 1022.5, 1019.0, 1015.1, 1013.4, 1010.8, 1019.9, 1023.8, 1016.7, 1005.3, 1022.9, 1021.0, 1006.0, 1015.9, 1010.6, 1006.7, 1011.1, 1003.8, 1017.9, 1021.9, 1020.9, 1017.1, 1016.0, 1010.6, 1012.1, 1016.7, 1017.5, 1013.7, 1008.2, 997.5, 996.4, 991.4, 991.0, 1005.1, 1015.3, 1014.1, 1008.9, 1003.9, 1002.0, 1007.2, 1004.6, 1007.2, 1005.6, 1018.5, 1008.6, 1004.1, 1008.4, 1010.9, 1006.3, 1009.6, 1015.0, 1009.9, 990.3, 997.4, 1007.9, 1010.1, 1008.0, 1001.2, 1007.8, 1019.3, 1019.9, 1014.8, 1008.4, 1012.6, 1013.5, 1010.7, 1005.0, 1003.2, 1003.7, 999.3, 1002.4, 1000.7, 1013.8, 1019.4, 1015.2, 1008.9, 1008.0, 1005.1, 1013.4, 1018.8, 1013.9, 1011.5, 1016.4, 1016.5, 1011.2, 1006.0, 1008.8, 1020.5, 1020.0, 1015.0, 1010.6, 1008.1, 1005.5, 1007.6, 1002.8, 1018.3, 1019.1, 1019.9, 1016.0, 1016.5, 1015.8, 1014.2, 1016.2, 1012.2, 1010.0, 1009.4, 1005.9, 1008.4, 1010.6, 1007.5, 1011.7, 1010.1, 1011.2, 1018.7, 1025.0, 1019.2, 1013.9, 1017.8, 1015.4, 1008.1, 1005.0, 1010.2, 1013.2, 1017.6, 1013.0, 1013.2, 1014.6, 1018.7, 1015.9, 1006.9, 1010.8, 1015.2, 1015.2, 1008.5, 1008.6, 1011.4, 1011.8, 1018.7, 1020.4, 1021.3, 1022.7, 1020.4, 1016.2, 1010.1, 1007.8, 1008.2, 1012.5, 1016.1, 1013.7, 1016.6, 1017.2, 1015.1, 1015.1, 1016.3, 1017.5, 1016.7, 1023.7, 1023.2, 1021.7, 1022.3, 1020.4, 1021.0, 1021.8, 1016.9, 1019.2, 1014.4, 1019.6, 1024.4, 1024.9, 1022.3, 1021.0, 1023.0, 1019.3, 1011.2, 1006.9, 1011.7, 1015.9, 1018.1, 1017.9, 1018.9, 1021.3, 1022.5, 1018.2, 1006.6, 1002.4, 1003.1, 1012.7, 1014.9, 1019.5, 1020.4, 1020.9, 1022.7, 1025.5, 1025.5, 1028.3, 1023.7, 1021.7, 1025.0, 1020.4, 1023.6, 1022.4, 1018.1, 1012.8, 1010.6, 1009.7, 1008.1, 1017.7, 1023.3, 1021.4, 1020.1, 1022.0, 1020.8, 1023.3, 1025.4, 1023.2, 1018.9, 1018.4, 1020.2, 1022.3, 1027.1, 1031.9, 1030.4, 1027.1, 1022.3, 1016.8, 1012.4, 1010.1, 1004.8, 1007.3, 1008.3, 1012.5, 1018.2, 1020.2, 1014.0, 1011.9, 1010.6, 1020.1, 1026.5, 1028.1, 1028.0, 1024.6, 1020.7, 1017.7, 1016.7, 1010.7, 1012.2, 1009.2, 1005.4, 1004.5, 1010.3, 1008.2, 1004.1, 1006.4, 1004.0, 1011.1, 1016.4, 1017.8, 1024.1, 1028.2, 1028.5, 1024.7, 1018.6, 1009.4, 1005.9, 1004.4, 1008.2, 1010.3, 1019.2, 1018.4, 1019.2, 1020.4, 1015.7, 1005.4, 1014.5, 1024.6, 1022.1, 1014.2, 1015.4, 1020.2, 1022.3, 1019.3, 1017.9, 1021.4, 1022.7, 1019.6, 1017.4, 1020.4, 1019.2, 1009.4, 1020.8, 1017.9, 1017.0, 1012.5, 1009.4, 1011.7, 1016.5, 1016.2, 1009.0, 1013.7, 1026.3, 1023.2, 1014.2, 1002.1, 1009.9, 1007.8, 1005.9, 1006.8, 1010.8, 1013.5, 1013.1, 998.9, 1010.6, 1014.0, 1019.6, 1021.8, 1018.9, 1010.0, 1015.1, 1014.0, 1000.8, 1007.6, 1008.8, 1013.9, 1019.4, 1019.1, 1015.5, 1021.3, 1016.4, 1019.7, 1010.1, 1018.4, 1013.0, 1010.9, 1012.0, 998.3, 997.8, 1009.6, 1007.0, 1004.5, 1004.1, 1005.6, 1011.8, 1012.6, 1007.7, 1010.0, 1014.1, 1019.8, 1017.1, 1016.7, 1011.3, 1019.9, 1026.0, 1027.3, 1019.8, 1006.4, 998.7, 1000.7, 1006.2, 1011.8, 1020.6, 1025.3, 1024.7, 1018.7, 1016.8, 1022.6, 1014.7, 1016.3, 1015.7, 1025.3, 1027.7, 1020.6, 1023.4, 1019.9, 1017.5, 1006.6, 1015.5, 1021.9, 1027.1, 1030.0, 1028.8, 1024.0, 1020.0, 1021.3, 1013.4, 1019.2, 1011.4, 1011.7, 1002.0, 1009.7, 1010.3, 1009.2, 1005.7, 1006.6, 1001.5, 1022.6, 1024.3, 1018.4, 1011.2, 1007.1, 1000.2, 998.7, 1009.2, 1017.4, 1021.7, 1017.9, 1015.6, 1012.6, 1015.0, 1007.4, 1000.8, 1010.2, 1006.0, 1013.1, 1014.0, 1015.2, 1021.1, 1020.3, 1016.1, 1008.5, 1016.7, 1013.9, 1019.8, 1012.6, 1009.7, 1016.4, 1016.1, 1015.4, 1021.2, 1023.1, 1017.2, 1010.4, 1005.7, 1016.0, 1019.1, 1014.6, 1013.8, 1017.4, 1019.7, 1014.6, 1015.4, 1016.1, 1008.5, 1011.0, 1017.6, 1017.2, 1009.6, 1003.0, 1002.5, 1007.4, 1007.8, 1008.4, 1008.8, 1005.4, 1014.5, 1011.8, 1007.2, 1013.6, 1009.5, 1010.0, 1017.9, 1014.6, 1016.1, 1016.4, 1014.3, 1011.3, 1008.8, 1016.2, 1020.8, 1021.9, 1021.2, 1017.6, 1013.5, 1005.5, 1010.2, 1004.5, 1003.5, 1013.6, 1016.0, 1023.4, 1023.1, 1018.4, 1014.8, 1011.7, 1016.3, 1021.4, 1026.6, 1024.4, 1017.8, 1014.3, 1018.4, 1018.2, 1018.2, 1013.7, 1009.6, 1010.8, 1012.0, 1009.6, 1012.2, 1022.5, 1031.5, 1034.8, 1032.9, 1027.8, 1022.4, 1022.7, 1024.5, 1023.7, 1019.2, 1019.5, 1014.3, 1018.7, 1017.4, 1020.8, 1019.6, 1015.4, 1018.4, 1014.9, 1016.4, 1018.4, 1017.5, 1016.3, 1018.5, 1020.0, 1020.5, 1019.0, 1017.6, 1012.3, 1011.8, 1011.1, 1007.6, 1006.0, 1011.7, 1020.3, 1019.3, 1020.5, 1025.1, 1026.0, 1023.7, 1021.7, 1020.4, 1019.4, 1016.0, 1009.9, 1013.5, 1022.3, 1017.8, 1016.7, 1017.0, 1024.4, 1024.4, 1022.1, 1024.3, 1015.8, 1011.3, 1018.3, 1018.3, 1019.3, 1018.3, 1015.8, 1008.7, 1016.9, 1015.8, 1014.9, 1016.1, 1018.4, 1016.7, 1017.4, 1020.3, 1019.9, 1017.9, 1019.7, 1020.8, 1015.7, 1006.3, 1004.9, 1017.6, 1017.1, 1004.7, 1002.4, 1010.2, 1017.7, 1019.6, 1020.0, 1015.5, 1012.0, 1015.8, 1023.0, 1018.7, 1008.3, 1017.7, 1016.0, 1021.7, 1028.9, 1032.0, 1028.9, 1024.1, 1010.5, 1023.8, 1032.5, 1034.1, 1027.1, 1020.7, 1016.3, 1018.9, 1017.7, 1017.0, 1018.5, 1022.8, 1023.5, 1026.1, 1026.9, 1024.1, 1015.1, 1022.5, 1027.9, 1025.0, 1019.8, 1021.1, 1014.6, 1008.6, 1017.1, 1024.0, 1024.7, 1017.8, 1016.0, 1021.4, 1024.6, 1028.1, 1030.3, 1027.4, 1027.7, 1032.6, 1032.5, 1024.8, 1016.0, 1013.6, 1012.0, 1013.0, 1011.6, 1016.9, 1014.9, 1015.1, 1019.2, 1022.2, 1019.1, 1020.9, 1013.8, 1003.7, 1002.3, 1012.0, 1009.7, 1004.0, 1010.3, 1019.9, 1012.0, 1004.6, 1010.9, 1015.2, 1020.4, 1010.8, 1007.9, 1005.2, 1000.7, 1008.0, 1022.3, 1024.3, 1019.8, 1012.5, 1014.4, 1023.6, 1006.7, 1009.7, 1017.1, 1023.3, 1023.6, 1010.6, 1001.3, 1017.2, 1017.8, 1012.1, 1011.4, 1010.6, 1017.8, 1013.8, 1019.7, 1022.7, 1022.3, 1020.8, 1022.3, 1017.6, 1013.5, 1017.3, 1027.7, 1027.4, 1022.8, 1008.1, 989.8, 1003.6, 1011.3, 1025.6, 1022.4, 1017.8, 1015.1, 1020.6, 1015.0, 1014.7, 1020.4, 1017.5, 1012.2, 1010.6, 1012.1, 1012.8, 1016.3, 1020.5, 1022.1, 1021.9, 1018.1, 1015.1, 1024.2, 1017.1, 1012.0, 1012.8, 1012.6, 1011.3, 1015.7, 1012.2, 1024.0, 1024.3, 1022.0, 1017.7, 1015.3, 1012.0, 1010.2, 1012.9, 1014.5, 1015.3, 1015.9, 1014.7, 1010.2, 1013.3, 1015.4, 1012.5, 1008.2, 1006.0, 1003.1, 1003.7, 1012.7, 1006.7, 1006.0, 1003.5, 999.6, 995.6, 1000.7, 1007.9, 1017.6, 1016.5, 1023.7, 1011.4, 1001.4, 1005.8, 1019.1, 1014.8, 1015.3, 1013.9, 1010.1, 1010.8, 1013.9, 1011.6, 1005.8, 1011.1, 1013.0, 1012.1, 1014.3, 1014.7, 1012.1, 1011.6, 1013.5, 1009.3, 1007.0, 1007.4, 1001.5, 1007.3, 1009.3, 1013.4, 1013.1, 1015.2, 1009.1, 1001.4, 1006.9, 1010.2, 1011.1, 1019.1, 1021.3, 1016.3, 1011.8, 1006.9, 1012.7, 1009.9, 1011.1, 1006.6, 1016.1, 1020.6, 1018.6, 1023.6, 1020.3, 1011.4, 1016.4, 1018.4, 1023.4, 1022.0, 1016.3, 1011.2, 1014.0, 1006.3, 1005.7, 1012.4, 1022.6, 1021.3, 1016.0, 1012.2, 1009.5, 1007.5, 1007.8, 1003.1, 1015.0, 1007.1, 1009.8, 1023.5, 1026.3, 1022.2, 1015.8, 1013.1, 1012.0, 1015.3, 1019.2, 1018.2, 1020.6, 1018.2, 1016.8, 1017.0, 1014.0, 1011.8, 1010.1, 1003.3, 999.4, 1000.4, 1003.2, 1008.7, 1020.1, 1024.5, 1025.5, 1022.3, 1016.1, 1022.9, 1015.9, 1014.7, 1013.7, 1015.6, 1021.3, 1020.4, 1015.2, 1010.4, 1013.7, 1013.1, 1006.4, 1009.3, 1008.1, 1017.6, 1026.9, 1026.2, 1028.1, 1029.6, 1028.2, 1024.4, 1021.5, 1015.3, 1001.4, 1005.0, 1011.1, 1015.1, 1017.8, 1022.5, 1021.9, 1018.4, 1019.3, 1025.0, 1022.7, 1014.7, 1013.7, 1012.9, 1016.2, 1013.2, 1012.7, 1011.0, 1017.0, 1024.6, 1022.9, 1021.1, 1019.9, 1021.4, 1016.8, 1005.5, 1009.8, 1014.0, 1011.9, 1000.6, 1010.4, 1017.3, 1024.7, 1028.0, 1023.3, 1027.2, 1032.6, 1035.7, 1034.8, 1028.1, 1022.6, 1017.5, 1010.0, 1004.8, 1007.4, 1013.8, 1018.2, 1015.5, 1010.2, 1018.1, 1017.9, 1016.5, 1027.4, 1032.4, 1027.7, 1021.5, 1015.0, 1011.6, 1013.5, 1014.3, 1018.0, 1019.1, 1017.8, 1014.8, 1018.6, 1026.8, 1025.6, 1023.6, 1020.5, 1019.4, 1019.4, 1020.9, 1021.6, 1024.0, 1021.8, 1016.7, 1012.6, 1007.8, 1005.6, 1004.5, 1008.2, 1018.7, 1022.2, 1023.9, 1022.8, 1018.7, 1014.1, 1008.7, 1015.8, 1028.6, 1034.6, 1036.7, 1031.8, 1026.6, 1020.6, 1022.9, 1017.7, 1017.0, 1015.1, 1021.1, 1021.3, 1022.4, 1028.6, 1027.0, 1024.0, 1023.2, 1014.3, 1017.5, 1017.6, 1006.1, 1008.2, 1011.0, 1022.6, 1019.9, 1017.0, 1018.1, 1012.5, 1013.2, 1015.9, 1013.7, 1006.5, 1017.5, 1019.0, 1012.8, 1017.8, 1020.3, 1022.1, 1018.9, 1010.6, 996.3, 1002.8, 1005.0, 1016.7, 1021.3, 1022.9, 1018.2, 1013.5, 1010.2, 1009.4, 1004.9, 1006.5, 1009.5, 1017.0, 1021.3, 1017.4, 1007.5, 1014.8, 1031.8, 1031.6, 1027.8, 1023.5, 1021.4, 1021.5, 1017.9, 1007.7, 1013.6, 1022.3, 1021.9, 1015.5, 1008.9, 1009.5, 1019.7, 1016.0, 1009.4, 1013.8, 1018.1, 1015.0, 1009.2, 1012.2, 1008.8, 1011.2, 1011.5, 1022.5, 1015.1, 1016.6, 1018.7, 1018.7, 1016.1, 1010.4, 1007.4, 1015.2, 1008.8, 1019.7, 1025.7, 1020.4, 1003.9, 1007.9, 1015.6, 1014.2, 1009.1, 1020.6, 1020.8, 1016.9, 1015.0, 1019.9, 1017.9, 1014.0, 1013.1, 1013.3, 1008.0, 1002.1, 1006.3, 1007.9, 1016.2, 1018.0, 1020.8, 1021.4, 1016.2, 1008.0, 1014.4, 1016.6, 1017.0, 1012.9, 1012.5, 1009.8, 1004.2, 1010.7, 1011.8, 1014.9, 1019.5, 1018.8, 1015.3, 1016.5, 1015.4, 1010.2, 1014.2, 1016.4, 1012.1, 1003.5, 1005.7, 1006.8, 1001.5, 1015.6, 1013.5, 1015.8, 1019.2, 1022.1, 1021.1, 1014.3, 1015.0, 1015.8, 1021.5, 1021.1, 1016.5, 1013.0, 1013.4, 1016.8, 1013.2, 1008.8, 998.7, 1008.0, 1013.7, 1010.5, 1004.6, 1003.6, 1000.5, 1002.9, 1007.2, 1011.5, 1012.2, 1009.9, 1010.7, 1013.4, 1016.7, 1020.3, 1019.9, 1017.9, 1015.7, 1016.6, 1014.1, 1010.6, 1010.9, 1015.4, 1018.3, 1022.4, 1021.4, 1018.4, 1014.8, 1011.0, 1012.5, 1001.4, 1015.4, 1018.5, 1009.8, 1014.0, 1018.0, 1015.7, 1005.9, 1007.9, 1014.4, 1016.8, 1020.0, 1020.0, 1018.0, 1014.5, 1009.4, 1015.1, 1022.3, 1022.7, 1016.7, 1005.1, 1007.9, 1001.7, 1011.8, 1021.0, 1021.2, 1021.9, 1020.3, 1016.6, 1016.9, 1016.7, 1015.0, 1014.7, 1013.6, 1016.3, 1019.2, 1017.2, 1016.9, 1013.6, 1013.6, 1025.9, 1029.7, 1030.9, 1028.1, 1024.0, 1022.4, 1021.7, 1020.6, 1018.3, 1016.2, 1014.4, 1012.8, 1011.0, 1009.2, 1007.8, 1017.2, 1020.5, 1017.4, 1021.9, 1025.0, 1023.2, 1018.4, 1017.3, 1016.8, 1013.2, 1014.2, 1015.7, 1016.5, 1018.9, 1019.4, 1013.8, 1014.1, 1011.5, 1021.5, 1021.9, 1022.5, 1022.0, 1021.1, 1020.3, 1024.1, 1021.6, 1020.7, 1020.2, 1018.7, 1008.8, 1012.8, 1019.5, 1025.3, 1030.6, 1032.5, 1030.7, 1025.7, 1018.7, 1010.6, 1000.4, 1000.7, 1017.9, 1021.2, 1023.8, 1024.0, 1023.4, 1020.4, 1018.5, 1019.2, 1016.4, 1013.2, 1014.2, 1016.6, 1019.7, 1017.7, 1017.9, 1010.7, 1007.9, 1021.2, 1026.1, 1029.5, 1028.6, 1020.8, 1010.9, 1011.4, 1013.4, 1015.5, 1018.1, 1025.1, 1030.1, 1031.4, 1030.5, 1028.2, 1026.6, 1021.1, 1017.6, 1012.7, 1008.0, 1009.7, 1016.9, 1025.4, 1021.5, 1015.8, 1020.3, 1024.7, 1028.5, 1027.6, 1025.6, 1019.3, 1011.3, 1009.8, 1015.7, 1021.6, 1022.2, 1022.9, 1019.5, 1018.5, 1014.4, 1014.3, 1011.3, 1014.9, 1021.3, 1015.2, 1009.9, 1016.6, 1011.5, 1010.7, 1004.3, 1007.4, 1019.1, 1019.1, 1016.0, 1010.4, 1005.9, 1011.8, 1015.5, 1016.9, 1008.9, 1013.7, 1020.2, 1019.9, 1019.8, 1019.6, 1007.3, 1005.3, 1006.2, 1012.8, 1022.4, 1015.7, 1007.3, 1017.1, 1023.5, 1016.3, 1016.9, 1013.8, 1014.4, 1014.7, 1009.8, 1013.1, 1005.4, 1010.6, 1020.0, 1019.0, 1013.5, 1003.5, 1018.0, 1025.5, 1029.2, 1020.5, 1013.1, 1013.0, 1014.6, 1013.7, 1013.4, 1011.1, 1004.1, 1010.7, 1019.3, 1024.0, 1020.9, 1013.9, 1016.4, 1019.6, 1011.6, 1008.5, 1009.5, 1019.7, 1026.5, 1017.7, 1006.6, 1007.3, 1016.4, 1024.3, 1021.2, 1015.7, 1013.0, 1002.0, 1015.5, 1020.1, 1017.5, 1014.9, 1012.7, 1010.3, 1011.7, 1012.6, 1023.1, 1026.6, 1019.7, 1019.0, 1017.4, 1010.7, 1011.0, 1015.1, 1007.7, 1015.6, 1021.6, 1012.2, 1017.0, 1018.5, 1014.8, 1012.6, 1012.3, 1014.7, 1016.5, 1013.6, 1010.4, 1008.6, 1015.1, 1016.6, 1014.1, 1014.3, 1019.7, 1018.4, 999.1, 1002.1, 1009.6, 1005.5, 1006.7, 1008.5, 1017.5, 1016.7, 1011.8, 1007.9, 997.9, 1013.8, 1016.1, 1013.4, 1007.4, 1015.3, 1015.3, 1010.5, 1011.1, 1009.0, 1008.1, 1004.9, 1014.0, 1008.4, 1016.2, 1020.8, 1020.4, 1020.9, 1020.0, 1018.4, 1017.4, 1020.5, 1019.0, 1017.5, 1019.6, 1018.4, 1010.9, 1011.2, 1015.7, 1008.9, 1015.0, 1020.2, 1022.8, 1022.3, 1014.3, 1011.0, 1013.7, 1011.5, 1017.5, 1016.3, 1015.7, 1012.1, 1017.7, 1012.8, 1010.8, 1015.5, 1013.8, 1021.7, 1027.8, 1028.4, 1025.2, 1021.6, 1023.9, 1024.3, 1021.3, 1021.6, 1022.8, 1016.4, 1010.9, 1007.4, 1013.5, 1014.0, 1012.5, 1012.8, 1014.1, 1012.4, 1006.9, 1011.7, 1015.9, 1019.5, 1019.1, 1017.7, 1016.0, 1020.9, 1022.4, 1014.3, 1025.2, 1020.5, 1018.5, 1022.1, 1024.5, 1027.1, 1028.1, 1027.4, 1028.4, 1027.5, 1022.7, 1014.2, 1011.1, 1009.6, 1007.3, 1010.4, 1011.8, 1014.1, 1014.7, 1012.3, 1010.1, 1012.7, 1017.9, 1022.1, 1023.0, 1028.2, 1030.2, 1027.8, 1025.9, 1023.8, 1014.1, 1009.8, 1018.9, 1023.8, 1021.6, 1020.0, 1018.5, 1028.6, 1024.3, 1018.7, 1017.6, 1009.7, 1004.3, 1002.9, 1009.9, 1011.6, 1008.3, 1012.2, 1021.3, 1021.0, 1019.1, 1024.2, 1026.7, 1017.9, 1014.8, 1020.0, 1020.7, 1022.5, 1023.0, 1023.5, 1021.9, 1021.0, 1020.8, 1011.5, 1010.8, 1018.1, 1025.6, 1029.9, 1033.6, 1031.6, 1032.2, 1027.1, 1027.3, 1025.4, 1021.9, 1022.1, 1020.6, 1019.4, 1011.7, 1005.4, 1013.2, 1016.3, 1018.5, 1026.4, 1026.6, 1023.3, 1028.2, 1025.8, 1020.8, 1017.8, 1022.7, 1020.1, 1012.7, 1012.1, 1012.2, 1013.6, 1008.0, 1009.3, 1009.8, 1014.0, 1013.4, 1013.5, 1004.2, 1012.2, 1007.7, 1019.8, 1016.9, 1006.7, 1011.9, 1007.0, 1011.9, 1013.4, 1010.2, 1008.5, 1020.0, 1020.4, 1020.4, 1018.6, 1020.2, 1019.4, 1011.4, 1020.0, 1026.6, 1029.1, 1031.3, 1028.7, 1023.0, 1023.1, 1018.1, 1023.0, 1014.0, 1000.4, 1008.7, 1010.1, 1018.1, 1009.1, 1016.3, 1010.0, 998.3, 1000.0, 1002.9, 1006.2, 1012.2, 1011.6, 1007.3, 1000.4, 1006.0, 1005.8, 1016.6, 1005.2, 1014.8, 1010.7, 1005.0, 1007.6, 1014.3, 1019.1, 1010.4, 1005.0, 1010.8, 1015.8, 1013.1, 1003.1, 1012.7, 1009.5, 996.3, 1014.4, 1018.7, 1012.4, 1003.3, 1025.1, 1024.4, 1016.5, 1011.9, 1011.7, 1002.3, 1012.9, 1019.2, 1019.1, 1020.4, 1014.3, 1008.7, 1018.0, 1019.3, 1020.2, 1012.5, 1006.1, 1024.0, 1026.5, 1019.2, 1012.2, 1006.4, 1006.6, 1017.2, 1016.4, 1011.8, 1011.2, 1011.3, 1014.6, 1014.5, 1014.5, 1010.5, 1010.3, 1010.7, 1010.4, 1006.6, 1003.2, 1005.2, 1009.1, 1016.4, 1014.8, 1005.0, 1008.8, 1019.5, 1024.3, 1019.6, 1013.5, 1000.5, 996.9, 1013.3, 1018.3, 1013.5, 1004.0, 1002.6, 1005.0, 1009.8, 1009.8, 1015.0, 1016.9, 1019.2, 1019.5, 1022.9, 1018.8, 1011.6, 1015.4, 1008.3, 1004.3, 1018.5, 1016.4, 1010.5, 1010.7, 1007.6, 1012.9, 1011.7, 1011.0, 1011.3, 1002.0, 1000.0, 1002.3, 1005.7, 1007.3, 1019.4, 1022.4, 1023.1, 1019.6, 1014.6, 1017.0, 1020.2, 1019.7, 1018.2, 1016.6, 1014.0, 1009.4, 1008.9, 1008.0, 1008.0, 1019.9, 1021.0, 1008.0, 1014.8, 1024.1, 1022.3, 1018.4, 1014.0, 1016.8, 1012.0, 1012.6, 1014.3, 1012.0, 1019.4, 1022.3, 1017.7, 1015.2, 1016.3, 1015.4, 1017.5, 1014.6, 1015.6, 1011.3, 1006.4, 999.5, 1001.6, 1013.3, 1009.9, 1002.1, 1007.9, 1015.8, 1019.2, 1021.8, 1018.2, 1013.6, 1010.1, 1019.2, 1022.5, 1019.1, 1020.6, 1024.5, 1023.7, 1014.0, 1018.3, 1018.7, 1021.5, 1020.9, 1021.5, 1021.3, 1015.4, 1018.2, 1014.7, 1008.4, 1004.7, 1015.0, 1018.7, 1023.6, 1024.2, 1018.9, 1014.5, 1013.2, 1015.3, 1019.6, 1021.2, 1020.0, 1013.3, 1015.0, 1019.2, 1019.7, 1017.5, 1014.6, 1015.0, 1016.5, 1016.9, 1020.8, 1023.6, 1020.1, 1017.9, 1012.7, 1002.9, 1011.9, 1016.1, 1018.8, 1018.4, 1017.3, 1017.4, 1011.7, 1014.8, 1014.7, 1018.5, 1014.9, 1014.9, 1011.3, 1019.2, 1011.5, 1023.1, 1022.1, 1013.3, 1011.4, 1013.8, 1001.9, 994.8, 1003.7, 1016.8, 1018.5, 1022.9, 1024.3, 1023.6, 1020.0, 1022.1, 1028.5, 1027.2, 1025.8, 1025.3, 1027.0, 1026.7, 1025.2, 1022.4, 1019.6, 1022.6, 1018.7, 1013.0, 1014.0, 1017.1, 1020.9, 1010.8, 1013.5, 1022.1, 1024.5, 1022.8, 1018.0, 1014.9, 1016.2, 1022.9, 1024.1, 1024.8, 1025.0, 1025.8, 1027.3, 1027.4, 1022.8, 1018.9, 1015.0, 1009.2, 1008.3, 1018.4, 1024.0, 1027.9, 1022.9, 1015.9, 1018.5, 1020.0, 1008.6, 1003.4, 1012.8, 1017.9, 1015.1, 999.9, 1004.8, 1015.7, 1024.0, 1025.2, 1023.3, 1016.6, 1012.0, 1010.8, 1011.9, 1012.2, 999.6, 1005.1, 1016.0, 1017.1, 1027.3, 1029.0, 1021.3, 1010.7, 1008.6, 1011.1, 1021.4, 1024.9, 1023.3, 1022.3, 1021.6, 1019.2, 1019.9, 1020.4, 1021.5, 1018.1, 1013.2, 1014.5, 1007.3, 1008.7, 1026.8, 1032.2, 1030.4, 1030.1, 1026.2, 1027.5, 1029.6, 1024.7, 1017.6, 1025.1, 1028.2, 1031.9, 1032.5, 1026.5, 1019.0, 1004.2, 1005.0, 1016.6, 1024.5, 1027.0, 1029.0, 1029.3, 1026.4, 1022.4, 1022.7, 1023.9, 1025.9, 1024.0, 1021.7, 1017.2, 1010.9, 1007.9, 1012.3, 1015.1, 1021.7, 1028.5, 1028.2, 1024.2, 1012.8, 1008.9, 1013.7, 1024.1, 1023.5, 1016.0, 1015.1, 1017.1, 1018.5, 1023.7, 1027.3, 1028.9, 1026.2, 1016.6, 1009.8, 1015.9, 1019.3, 1016.2, 1011.2, 1007.2, 1018.5, 1017.2, 1019.6, 1015.5, 1012.9, 1012.4, 1008.3, 1018.0, 1020.2, 1015.5, 1014.2, 1013.4, 1005.7, 1008.5, 1013.4, 1015.8, 1024.9, 1027.4, 1022.6, 1029.8, 1030.7, 1022.0, 1015.9, 1014.9, 1013.6, 1007.9, 1002.7, 1008.3, 1015.8, 1011.6, 1017.9, 1023.7, 1019.4, 1012.6, 1013.9, 1019.5, 1018.9, 1017.6, 1016.8, 1019.6, 1016.0, 1015.7, 1006.7, 1010.0, 1001.5, 1011.8, 1016.4, 1018.6, 1008.7, 1004.6, 1011.5, 1007.4, 1007.4, 1016.4, 1016.6, 1011.2, 1007.9, 1008.8, 1009.4, 1009.4, 1005.6, 1004.1, 1003.9, 1006.3, 1014.3, 1011.4, 1008.8, 1016.9, 1010.7, 1010.8, 999.6, 1007.8, 1005.5, 1013.0, 1016.6, 1016.0, 1014.8, 1012.8, 1013.9, 1005.7, 1011.3, 1020.6, 1015.9, 1004.1, 1004.0, 1014.4, 1011.4, 1017.7, 1017.5, 1012.8, 1018.7, 1019.9, 1018.3, 1011.7, 1007.8, 1009.1, 1012.6, 1013.3, 1005.6, 997.2, 1004.2, 1005.8, 1005.2, 1010.0, 1015.2, 1011.9, 1010.6, 1012.1, 1007.0, 1004.9, 1001.6, 1013.3, 1012.5, 1013.5, 1011.0, 1005.4, 1005.8, 1009.3, 1015.9, 1017.5, 1015.7, 1024.1, 1026.2, 1021.8, 1017.0, 1023.9, 1023.1, 1021.0, 1021.0, 1023.3, 1019.9, 1014.8, 1015.7, 1017.6, 1019.0, 1019.4, 1016.2, 1016.0, 1016.9, 1014.6, 1015.1, 1015.2, 1007.2, 1009.5, 1008.5, 1002.9, 1017.3, 1013.1, 1010.2, 1008.5, 1003.7, 1009.9, 1009.5, 1009.9, 1016.5, 1013.3, 1013.3, 1019.5, 1014.6, 1012.5, 1015.7, 1012.0, 1003.7, 1010.5, 1012.0, 1025.3, 1022.0, 1013.6, 1010.4, 1016.5, 1015.1, 1017.1, 1021.9, 1021.1, 1022.9, 1024.8, 1021.0, 1016.3, 1022.9, 1017.4, 1005.7, 1006.6, 1007.2, 1013.1, 1020.2, 1022.8, 1019.6, 1018.0, 1021.3, 1021.4, 1021.6, 1019.3, 1021.3, 1013.9, 1019.6, 1020.7, 1016.8, 1010.5, 1009.6, 1004.4, 1004.7, 1010.4, 1019.0, 1024.5, 1028.9, 1028.4, 1024.5, 1016.5, 1012.8, 1013.2, 1003.9, 1012.5, 1015.4, 1016.1, 1013.9, 1006.0, 1009.6, 1010.2, 1016.3, 1024.2, 1031.1, 1033.7, 1032.2, 1027.3, 1015.5, 1013.4, 1016.9, 1020.4, 1028.1, 1030.7, 1028.5, 1026.6, 1021.6, 1020.2, 1020.1, 1017.8, 1012.3, 1016.7, 1022.4, 1020.7, 1017.8, 1019.3, 1027.0, 1024.1, 1019.5, 1019.5, 1031.2, 1034.4, 1031.5, 1027.1, 1025.7, 1025.2, 1018.3, 1009.1, 1013.6, 1017.5, 1023.4, 1027.6, 1026.1, 1023.3, 1019.9, 1023.5, 1031.1, 1029.2, 1030.9, 1030.0, 1025.0, 1022.6, 1016.8, 1024.6, 1020.3, 1018.0, 1013.3, 1021.7, 1027.6, 1026.9, 1019.0, 1009.4, 1001.5, 1002.9, 1010.4, 1016.1, 1013.7, 1012.9, 1027.2, 1031.1, 1032.1, 1029.3, 1025.0, 1023.4, 1014.5, 1015.8, 1012.4, 1024.5, 1030.8, 1030.2, 1020.1, 1019.5, 1015.6, 1010.4, 1013.7, 1018.9, 1010.3, 1016.7, 1021.0, 1022.5, 1019.6, 1012.9, 1011.1, 1004.0, 1014.7, 1023.4, 1028.8, 1021.4, 1013.3, 1021.0, 1025.0, 1025.0, 1021.2, 1016.2, 1018.4, 1015.0, 1012.8, 1017.8, 1015.1, 1018.9, 1017.9, 1017.5, 1013.8, 1013.3, 1012.0, 1005.6, 1020.5, 1019.6, 1021.9, 1013.3, 1015.7, 1022.0, 1029.8, 1027.6, 1024.7, 1025.0, 1020.5, 1009.0, 1015.0, 1018.3, 1025.5, 1023.9, 1021.7, 1015.2, 1017.5, 1025.4, 1024.6, 1027.8, 1025.4, 1021.1, 1017.8, 1015.8, 1021.4, 1022.8, 1031.8, 1024.7, 1021.8, 1021.1, 1019.7, 1033.6, 1036.0, 1029.7, 1025.8, 1018.6, 1012.4, 1022.3, 1025.2, 1022.0, 1018.7, 1021.4, 1027.9, 1022.4, 1016.3, 1011.5, 1010.3, 1021.6, 1020.9, 1017.8, 1015.1, 1025.8, 1022.5, 1022.1, 1020.8, 1018.6, 1010.6, 1009.0, 1016.5, 1016.3, 1010.5, 1006.3, 1012.3, 1020.0, 1017.5, 1013.5, 1020.3, 1018.0, 1009.8, 1013.4, 1017.4, 1018.0, 1016.0, 1009.7, 1011.7, 1006.3, 1017.3, 1016.7, 1010.8, 1014.1, 1000.0, 1013.8, 1016.0, 1009.7, 1008.7, 1006.7, 1017.0, 1026.0, 1024.1, 1017.8, 1019.9, 1015.8, 1012.1, 1011.7, 1001.1, 1015.1, 1016.1, 1013.4, 1012.5, 1016.7, 1016.9, 1014.0, 1012.8, 1017.2, 1021.5, 1017.7, 1018.7, 1015.4, 1006.0, 1018.4, 1023.0, 1020.7, 1018.7, 1016.8, 1013.7, 1012.3, 1014.7, 1016.3, 1014.6, 1011.6, 1015.8, 1019.0, 1018.8, 1017.5, 1009.1, 1012.1, 1016.2, 1024.0, 1026.1, 1022.6, 1017.7, 1013.3, 1009.8, 1007.4, 1006.4, 1008.6, 1012.1, 1013.3, 1017.3, 1014.0, 1004.7, 1001.9, 1002.7, 1003.3, 1001.1, 1004.0, 1002.2, 1012.8, 1017.6, 1016.9, 1016.6, 1017.9, 1019.6, 1012.9, 1014.2, 1015.1, 1011.5, 1005.3, 1007.7, 1008.8, 1008.4, 1008.7, 1009.8, 1018.2, 1024.6, 1022.0, 1017.7, 1012.9, 1009.3, 1015.5, 1019.0, 1017.2, 1020.4, 1019.9, 1018.9, 1019.4, 1020.1, 1019.4, 1021.2, 1018.8, 1022.6, 1017.9, 1018.9, 1017.9, 1018.0, 1017.9, 1014.3, 1018.6, 1018.0, 1012.9, 997.6, 1011.2, 1016.8, 1016.5, 1015.5, 1016.9, 1019.0, 1016.3, 1016.0, 1017.0, 1015.7, 1016.0, 1012.0, 1016.2, 1015.1, 1014.6, 1022.1, 1019.6, 1015.2, 1011.6, 1022.3, 1021.2, 1018.8, 1015.5, 1016.4, 1021.8, 1026.3, 1027.5, 1021.8, 1017.8, 1020.4, 1019.2, 1020.1, 1022.0, 1019.1, 1019.1, 1024.5, 1029.3, 1029.4, 1027.6, 1023.7, 1021.5, 1018.5, 1015.6, 1009.6, 1012.2, 1006.4, 1014.2, 1016.9, 1017.2, 1018.4, 1013.8, 1003.7, 1004.3, 1012.2, 1013.9, 1019.6, 1019.9, 1013.7, 1017.7, 1014.3, 1015.2, 1013.4, 1019.3, 1024.0, 1020.2, 1012.4, 1013.6, 1013.5, 1000.4, 1001.7, 1006.0, 1016.5, 1024.1, 1027.2, 1026.6, 1024.3, 1021.6, 1009.5, 995.9, 998.4, 1002.7, 1009.2, 1005.9, 1016.8, 1020.7, 1034.9, 1035.5, 1031.6, 1029.8, 1019.3, 1014.6, 1015.4, 1010.4, 994.2, 1002.0, 1005.0, 1007.4, 1003.2, 1018.1, 1017.0, 1013.6, 1023.1, 1025.4, 1023.2, 1022.6, 1016.2, 1006.1, 1003.0, 1016.5, 1018.4, 1022.4, 1021.3, 1009.7, 1007.1, 1019.8, 1025.9, 1027.3, 1030.2, 1027.1, 1019.8, 1019.1, 1018.4, 1016.1, 1001.0, 1003.8, 1012.1, 1011.3, 1012.8, 1013.3, 1020.5, 1018.0, 1020.2, 1015.3, 1013.0, 1013.9, 1017.7, 1028.3, 1026.8, 1024.7, 1022.9, 1017.9, 1011.4, 1017.0, 1019.8, 1020.2, 1027.2, 1029.7, 1025.8, 1022.1, 1020.7, 1013.9, 1013.8, 1016.4, 1015.0, 1013.5, 1007.5, 1010.6, 1017.6, 1020.3, 1020.9, 1025.0, 1023.1, 1013.9, 1015.3, 1006.0, 1004.3, 1022.0, 1027.1, 1026.3, 1029.3, 1024.8, 1015.9, 1010.9, 1017.1, 1018.5, 1017.8, 1008.4, 1007.5, 1015.5, 1018.0, 1005.7, 1008.7, 1016.0, 1007.5, 1005.9, 1010.7, 1007.9, 1006.1, 1009.0, 1006.8, 1011.3, 994.0, 998.3, 1005.5, 1008.3, 997.8, 1003.7, 1013.2, 1017.0, 1015.6, 1017.6, 1018.1, 1004.1, 1012.9, 1012.5, 1022.4, 1023.2, 1017.5, 1008.7, 1008.3, 1010.8, 1017.0, 1021.4, 1012.8, 1010.1, 1017.7, 1016.7, 1014.4, 1013.0, 1015.7, 1018.5, 1017.7, 1006.5, 1010.8, 1010.0, 1013.0, 1014.8, 1009.2, 1006.2, 1007.8, 1006.4, 1007.1, 1009.8, 1007.0, 1009.9, 996.9, 995.4, 1004.5, 1015.0, 1021.3, 1021.9, 1013.5, 1018.4, 1018.2, 1015.1, 1012.1, 1011.8, 1012.5, 1013.7, 1016.9, 1010.4, 1010.8, 1008.8, 1005.3, 1007.7, 1015.0, 1013.1, 1005.9, 1010.6, 1014.4, 999.4, 1009.9, 1020.5, 1020.4, 1018.1, 1011.1, 1007.0, 1017.4, 1009.3, 1005.2, 1020.0, 1017.5, 1005.3, 1012.2, 1018.1, 1016.6, 1013.8, 1015.5, 1011.4, 1013.3, 1009.7, 1004.4, 1001.7, 1003.4, 1005.5, 1011.8, 1018.3, 1020.0, 1017.2, 1017.5, 1015.0, 1010.0, 1009.2, 1008.1, 1003.4, 1010.7, 1001.3, 1003.2, 1015.7, 1013.9, 1008.3, 1006.8, 1013.7, 994.3, 1012.2, 1015.8, 1010.1, 1008.4, 1018.0, 1014.9, 1016.9, 1012.2, 1015.4, 1008.0, 1009.7, 1012.7, 1013.9, 1013.5, 1010.4, 1007.3, 1009.3, 1018.7, 1021.8, 1013.0, 1006.4, 1002.7, 998.0, 1007.3, 1015.9, 1013.6, 1009.0, 1005.7, 1004.9, 1006.1, 1009.6, 1018.5, 1018.5, 1017.2, 1018.6, 1020.1, 1021.8, 1022.8, 1021.4, 1019.4, 1016.0, 1016.0, 1013.1, 1009.6, 1013.2, 1017.7, 1017.4, 1016.0, 1014.0, 1012.3, 1007.7, 1012.4, 1020.2, 1018.7, 1009.0, 1020.6, 1022.2, 1017.9, 1015.6, 1012.6, 1010.7, 1017.4, 1019.1, 1014.1, 1014.7, 1012.3, 1012.4, 1007.4, 1007.7, 1015.6, 1016.6, 1024.7, 1026.3, 1026.3, 1023.3, 1023.9, 1025.7, 1021.4, 1007.1, 1008.5, 1017.3, 1022.2, 1020.9, 1019.3, 1018.7, 1017.4, 1022.1, 1025.3, 1028.1, 1027.5, 1024.8, 1022.2, 1020.9, 1018.4, 1008.8, 1015.2, 1020.3, 1018.2, 1020.9, 1014.9, 1016.0, 1027.3, 1029.4, 1027.8, 1021.1, 1023.2, 1025.1, 1024.0, 1021.9, 1022.9, 1024.5, 1021.7, 1019.2, 1014.0, 1016.5, 1021.3, 1024.7, 1020.9, 1015.4, 1019.3, 1021.9, 1017.2, 1012.7, 1018.9, 1019.7, 1017.6, 1009.0, 1018.6, 1020.1, 1026.0, 1031.2, 1030.8, 1028.8, 1024.5, 1021.5, 1017.7, 1019.6, 1023.4, 1026.7, 1030.2, 1025.9, 1024.0, 1029.1, 1028.4, 1024.4, 1023.5, 1021.8, 1025.8, 1028.4, 1025.2, 1025.3, 1024.6, 1015.0, 1015.1, 1015.4], 'Cloud9am': [8, 7, 7, 8, 8, 6, 4, 7, 7, 4, 7, 7, 8, 7, 7, 7, 7, 7, 7, 3, 7, 4, 1, 0, 7, 1, 7, 8, 5, 0, 7, 1, 0, 6, 1, 5, 1, 1, 1, 0, 1, 1, 3, 1, 2, 4, 0, 5, 2, 8, 7, 5, 6, 5, 1, 1, 4, 3, 0, 4, 1, 1, 6, 1, 0, 5, 5, 6, 7, 5, 4, 7, 5, 7, 7, 7, 7, 8, 6, 7, 8, 7, 7, 7, 2, 6, 2, 1, 1, 7, 1, 1, 1, 1, 6, 1, 1, 0, 1, 7, 1, 6, 1, 1, 6, 3, 1, 1, 1, 4, 1, 1, 1, 4, 6, 3, 3, 3, 1, 1, 7, 8, 8, 8, 7, 7, 1, 8, 7, 7, 7, 8, 1, 5, 7, 6, 7, 7, 6, 7, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 0, 1, 1, 7, 6, 1, 7, 1, 2, 7, 1, 4, 8, 7, 1, 1, 4, 1, 1, 8, 1, 0, 6, 8, 8, 1, 2, 6, 6, 2, 1, 6, 1, 0, 6, 1, 7, 1, 7, 1, 2, 1, 1, 1, 0, 1, 1, 1, 6, 1, 7, 8, 8, 7, 1, 7, 2, 3, 2, 5, 7, 0, 0, 7, 7, 8, 8, 2, 1, 1, 1, 1, 1, 3, 8, 1, 1, 6, 1, 1, 0, 4, 0, 8, 3, 1, 1, 4, 2, 1, 2, 6, 3, 1, 7, 8, 8, 1, 4, 1, 3, 5, 1, 2, 8, 7, 1, 1, 5, 1, 7, 6, 7, 6, 6, 1, 6, 2, 5, 8, 8, 6, 7, 7, 2, 7, 6, 5, 6, 7, 1, 5, 3, 7, 3, 5, 8, 7, 7, 7, 8, 3, 1, 3, 7, 1, 5, 7, 7, 8, 7, 2, 3, 1, 7, 8, 8, 7, 8, 7, 3, 3, 8, 8, 6, 1, 5, 1, 1, 2, 2, 5, 4, 1, 6, 8, 7, 7, 7, 1, 2, 6, 0, 4, 6, 8, 2, 4, 0, 1, 8, 7, 7, 3, 1, 6, 0, 5, 2, 6, 1, 1, 0, 3, 5, 1, 6, 7, 8, 8, 6, 1, 1, 2, 1, 6, 7, 7, 1, 3, 0, 0, 8, 8, 7, 7, 8, 8, 8, 7, 8, 8, 2, 5, 8, 7, 7, 0, 7, 8, 7, 7, 8, 7, 7, 7, 1, 1, 3, 5, 7, 6, 3, 2, 7, 3, 2, 1, 1, 1, 2, 2, 4, 1, 5, 1, 4, 4, 7, 3, 5, 2, 8, 8, 8, 6, 7, 7, 7, 7, 2, 1, 5, 7, 8, 6, 0, 0, 0, 1, 7, 7, 5, 7, 3, 6, 1, 2, 1, 1, 7, 7, 3, 1, 4, 1, 7, 2, 1, 1, 1, 7, 6, 1, 1, 1, 1, 7, 1, 3, 6, 7, 7, 8, 5, 5, 7, 1, 7, 3, 3, 8, 6, 7, 7, 8, 7, 4, 1, 6, 2, 3, 1, 1, 1, 7, 7, 1, 6, 7, 7, 6, 6, 7, 7, 1, 7, 6, 3, 7, 4, 1, 7, 1, 1, 1, 1, 2, 6, 6, 7, 7, 5, 7, 7, 6, 1, 3, 6, 3, 1, 2, 0, 0, 2, 1, 1, 0, 7, 1, 1, 1, 1, 5, 0, 1, 3, 7, 4, 7, 3, 2, 3, 7, 7, 4, 0, 3, 0, 1, 0, 1, 0, 7, 2, 7, 1, 2, 1, 0, 0, 0, 8, 1, 1, 1, 0, 3, 7, 2, 3, 7, 1, 1, 1, 0, 0, 0, 5, 7, 8, 2, 3, 1, 4, 3, 0, 9, 1, 0, 1, 1, 1, 1, 2, 3, 7, 8, 8, 7, 6, 1, 6, 5, 4, 7, 2, 1, 1, 6, 1, 1, 6, 1, 0, 1, 8, 3, 4, 7, 8, 8, 5, 6, 1, 8, 6, 8, 7, 7, 6, 8, 6, 1, 1, 0, 6, 2, 4, 5, 7, 7, 3, 0, 7, 6, 7, 8, 2, 7, 1, 0, 0, 4, 2, 7, 1, 0, 7, 5, 1, 7, 6, 8, 2, 1, 3, 7, 6, 4, 0, 8, 0, 8, 4, 3, 8, 8, 8, 4, 5, 8, 8, 7, 8, 7, 1, 7, 8, 7, 1, 1, 6, 7, 1, 8, 8, 6, 3, 1, 1, 0, 3, 3, 5, 8, 8, 6, 8, 8, 1, 8, 6, 6, 6, 7, 7, 7, 7, 7, 8, 6, 2, 2, 6, 8, 7, 6, 7, 3, 5, 5, 1, 1, 0, 1, 8, 2, 6, 5, 7, 8, 7, 3, 7, 7, 6, 2, 6, 1, 8, 2, 2, 2, 2, 7, 3, 0, 6, 6, 3, 6, 7, 0, 7, 6, 0, 6, 2, 7, 8, 7, 2, 5, 2, 6, 5, 6, 8, 3, 2, 6, 5, 1, 1, 0, 6, 7, 1, 2, 1, 1, 1, 1, 7, 7, 1, 6, 0, 1, 8, 7, 2, 4, 7, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 8, 8, 7, 6, 3, 7, 7, 7, 7, 8, 6, 7, 7, 4, 7, 7, 6, 7, 7, 5, 1, 2, 5, 5, 5, 0, 1, 1, 5, 5, 2, 8, 5, 7, 7, 7, 6, 7, 1, 1, 0, 0, 4, 7, 1, 2, 7, 6, 7, 6, 6, 7, 6, 7, 3, 1, 2, 1, 0, 6, 1, 7, 1, 2, 7, 3, 6, 6, 8, 6, 4, 7, 1, 5, 7, 1, 3, 1, 1, 3, 2, 8, 7, 2, 1, 0, 6, 1, 1, 3, 1, 1, 1, 1, 7, 1, 1, 3, 5, 1, 3, 1, 6, 8, 8, 8, 1, 1, 2, 1, 6, 6, 1, 3, 5, 6, 5, 2, 1, 6, 4, 0, 3, 7, 0, 4, 1, 5, 5, 5, 5, 5, 5, 5, 3, 2, 1, 5, 5, 1, 2, 5, 7, 5, 5, 8, 5, 1, 7, 7, 5, 5, 3, 7, 5, 5, 5, 5, 7, 7, 3, 7, 6, 2, 1, 5, 5, 5, 5, 8, 8, 8, 2, 5, 5, 6, 3, 7, 8, 5, 5, 2, 4, 5, 8, 5, 5, 1, 1, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 1, 1, 3, 5, 4, 7, 2, 3, 7, 1, 7, 5, 2, 1, 0, 1, 4, 4, 1, 8, 6, 7, 8, 6, 0, 1, 1, 1, 6, 2, 1, 7, 3, 1, 1, 1, 1, 7, 3, 2, 1, 1, 2, 1, 3, 5, 6, 7, 1, 1, 3, 5, 1, 1, 1, 0, 5, 1, 0, 0, 1, 7, 6, 4, 1, 1, 3, 7, 1, 1, 6, 7, 1, 0, 1, 2, 6, 6, 5, 0, 1, 4, 1, 0, 0, 8, 1, 6, 7, 8, 5, 1, 7, 0, 7, 5, 7, 7, 1, 4, 7, 6, 1, 3, 8, 1, 7, 6, 5, 0, 7, 2, 7, 4, 1, 6, 8, 6, 5, 6, 1, 4, 1, 8, 8, 8, 8, 5, 2, 7, 7, 7, 7, 5, 1, 8, 7, 7, 6, 6, 6, 7, 4, 1, 0, 3, 8, 6, 6, 7, 3, 6, 8, 7, 3, 3, 5, 0, 6, 7, 7, 2, 7, 7, 2, 7, 8, 8, 8, 5, 3, 8, 7, 7, 3, 6, 7, 1, 4, 5, 5, 5, 7, 1, 6, 7, 1, 2, 2, 2, 3, 2, 6, 4, 1, 1, 7, 1, 1, 1, 1, 7, 6, 0, 7, 8, 7, 5, 3, 1, 6, 1, 1, 1, 1, 2, 7, 8, 1, 1, 2, 8, 1, 6, 1, 1, 2, 1, 1, 1, 1, 7, 7, 1, 1, 7, 6, 3, 2, 7, 1, 1, 5, 8, 7, 7, 1, 2, 1, 1, 2, 4, 3, 6, 7, 7, 1, 1, 5, 8, 8, 4, 1, 6, 8, 1, 3, 8, 7, 8, 7, 4, 2, 3, 7, 3, 2, 4, 2, 6, 1, 6, 3, 5, 7, 7, 7, 8, 7, 7, 7, 8, 7, 1, 1, 1, 0, 1, 0, 1, 0, 5, 7, 2, 1, 7, 4, 7, 7, 4, 7, 4, 2, 1, 2, 1, 1, 1, 5, 1, 6, 6, 6, 7, 2, 7, 4, 6, 1, 5, 2, 7, 4, 0, 1, 3, 1, 2, 1, 0, 1, 0, 2, 1, 2, 7, 7, 2, 1, 3, 4, 1, 6, 1, 7, 1, 6, 1, 1, 1, 7, 5, 7, 2, 2, 5, 1, 7, 5, 7, 8, 6, 6, 0, 2, 1, 1, 1, 7, 0, 0, 0, 1, 1, 6, 7, 1, 2, 2, 4, 2, 2, 1, 0, 7, 5, 0, 2, 5, 1, 1, 7, 2, 0, 0, 0, 7, 3, 1, 1, 7, 3, 7, 7, 6, 5, 7, 7, 7, 1, 7, 1, 0, 3, 4, 8, 8, 8, 1, 0, 3, 7, 7, 8, 6, 4, 6, 7, 3, 1, 3, 7, 1, 6, 8, 7, 5, 4, 2, 5, 7, 1, 3, 3, 7, 1, 1, 6, 1, 3, 7, 7, 6, 3, 2, 2, 6, 7, 7, 7, 8, 7, 5, 4, 2, 5, 2, 5, 7, 7, 1, 6, 1, 5, 7, 7, 6, 1, 2, 6, 4, 0, 0, 2, 0, 7, 6, 7, 7, 5, 8, 4, 7, 3, 1, 0, 3, 1, 6, 3, 1, 7, 6, 8, 1, 0, 2, 8, 8, 7, 4, 8, 8, 8, 7, 7, 7, 5, 1, 7, 1, 2, 3, 6, 7, 8, 7, 7, 3, 7, 1, 7, 4, 7, 4, 3, 1, 6, 6, 6, 4, 2, 1, 1, 1, 3, 7, 3, 3, 8, 1, 7, 8, 7, 6, 3, 3, 7, 2, 1, 8, 7, 7, 6, 7, 7, 7, 5, 7, 7, 6, 7, 5, 5, 2, 1, 3, 1, 7, 7, 6, 8, 7, 5, 6, 1, 7, 1, 2, 7, 5, 1, 5, 3, 2, 4, 3, 1, 3, 1, 1, 1, 0, 6, 7, 7, 7, 2, 1, 3, 2, 5, 6, 7, 1, 2, 6, 5, 7, 7, 1, 1, 8, 7, 2, 3, 1, 7, 6, 7, 7, 8, 7, 1, 1, 1, 3, 2, 1, 7, 7, 1, 1, 1, 7, 7, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 6, 7, 8, 1, 2, 6, 7, 7, 2, 3, 5, 7, 8, 1, 7, 7, 6, 1, 1, 1, 1, 3, 0, 1, 6, 7, 8, 6, 7, 7, 2, 1, 1, 7, 8, 8, 7, 7, 7, 6, 5, 4, 0, 8, 7, 2, 7, 8, 1, 4, 5, 6, 3, 3, 7, 7, 1, 1, 7, 1, 7, 7, 0, 1, 1, 7, 1, 6, 4, 0, 0, 7, 5, 5, 0, 2, 4, 1, 1, 4, 7, 1, 7, 7, 7, 1, 6, 1, 0, 7, 6, 8, 2, 7, 7, 1, 7, 8, 7, 3, 6, 1, 0, 5, 2, 1, 2, 1, 3, 7, 7, 6, 4, 2, 1, 8, 6, 6, 7, 3, 8, 8, 2, 3, 7, 7, 2, 4, 3, 6, 7, 6, 2, 6, 6, 4, 7, 7, 6, 2, 6, 7, 6, 7, 5, 5, 1, 7, 2, 8, 1, 5, 1, 3, 7, 7, 7, 3, 7, 7, 1, 0, 5, 1, 7, 3, 1, 7, 5, 3, 1, 1, 7, 8, 7, 6, 1, 2, 3, 0, 5, 8, 8, 5, 5, 7, 1, 2, 8, 8, 8, 3, 1, 2, 7, 7, 5, 7, 7, 7, 8, 0, 7, 5, 6, 1, 7, 2, 7, 3, 3, 2, 7, 7, 8, 3, 5, 7, 7, 7, 6, 7, 1, 6, 1, 5, 4, 5, 4, 7, 0, 7, 6, 5, 7, 1, 6, 7, 3, 7, 2, 1, 7, 7, 1, 7, 1, 1, 1, 1, 7, 8, 7, 1, 7, 8, 8, 4, 1, 6, 3, 3, 7, 7, 5, 3, 5, 7, 6, 7, 7, 6, 8, 8, 8, 4, 4, 3, 6, 1, 1, 6, 8, 8, 7, 8, 7, 4, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 3, 3, 7, 8, 7, 1, 8, 3, 3, 7, 3, 6, 1, 8, 7, 8, 5, 1, 1, 3, 7, 2, 1, 5, 6, 7, 7, 7, 7, 4, 7, 7, 8, 7, 7, 2, 7, 1, 1, 5, 6, 1, 0, 0, 7, 7, 5, 7, 1, 6, 1, 1, 5, 6, 1, 4, 0, 7, 7, 1, 1, 7, 8, 3, 3, 3, 1, 7, 8, 7, 1, 6, 1, 1, 3, 5, 2, 6, 5, 1, 7, 6, 3, 1, 5, 1, 1, 1, 1, 1, 1, 3, 5, 3, 1, 3, 1, 0, 2, 7, 8, 7, 7, 7, 3, 1, 1, 1, 1, 5, 3, 7, 1, 7, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 5, 7, 5, 1, 3, 3, 7, 7, 6, 7, 1, 0, 7, 4, 1, 0, 7, 1, 1, 5, 7, 7, 1, 6, 1, 4, 7, 1, 0, 1, 8, 7, 2, 4, 7, 7, 5, 2, 3, 8, 7, 5, 1, 7, 1, 5, 8, 8, 8, 4, 3, 7, 5, 3, 7, 7, 1, 8, 7, 5, 0, 5, 1, 1, 7, 7, 1, 4, 1, 7, 8, 7, 4, 1, 7, 7, 4, 3, 7, 7, 5, 7, 3, 3, 5, 3, 6, 7, 4, 0, 1, 6, 8, 7, 4, 5, 5, 8, 7, 6, 0, 1, 6, 7, 8, 8, 8, 8, 7, 5, 5, 3, 1, 6, 3, 8, 7, 6, 2, 3, 1, 5, 7, 3, 8, 8, 8, 6, 7, 3, 8, 1, 5, 2, 5, 8, 6, 7, 5, 2, 6, 2, 3, 2, 1, 1, 7, 1, 3, 3, 4, 7, 6, 1, 1, 0, 0, 1, 7, 1, 7, 4, 7, 3, 7, 1, 2, 2, 1, 4, 7, 8, 1, 4, 7, 7, 8, 7, 7, 1, 7, 8, 3, 1, 6, 7, 2, 5, 6, 7, 1, 1, 3, 7, 6, 8, 1, 1, 8, 8, 2, 5, 3, 7, 6, 7, 6, 6, 7, 6, 3, 3, 2, 1, 7, 5, 1, 3, 1, 7, 4, 8, 7, 0, 1, 1, 1, 4, 0, 7, 7, 1, 1, 2, 1, 0, 6, 1, 2, 7, 0, 0, 6, 1, 3, 1, 4, 7, 1, 6, 1, 1, 7, 7, 2, 7, 8, 8, 7, 4, 1, 7, 1, 1, 4, 5, 1, 5, 1, 6, 7, 7, 6, 7, 2, 7, 5, 1, 6, 8, 1, 1, 1, 1, 5, 8, 6, 7, 8, 3, 3, 7, 6, 3, 7, 1, 2, 7, 1, 7, 8, 7, 6, 1, 7, 1, 1, 2, 1, 1, 1, 7, 6, 7, 8, 6, 7, 7, 1, 5, 3, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 7, 1, 8, 7, 7, 1, 1, 7, 7, 7, 2, 8, 4, 1, 0, 0, 6, 7, 6, 2, 1, 3, 8, 8, 1, 6, 1, 8, 1, 7, 7, 3, 6, 1, 7, 1, 2, 1, 8, 6, 3, 0, 7, 1, 0, 4, 7, 6, 7, 6, 1, 1, 2, 1, 0, 0, 7, 1, 3, 6, 5, 7, 7, 1, 7, 7, 4, 8, 6, 7, 1, 4, 1, 1, 2, 1, 1, 2, 7, 7, 6, 5, 7, 1, 3, 7, 0, 4, 1, 7, 4, 6, 1, 1, 4, 3, 7, 6, 7, 7, 7, 3, 7, 7, 7, 8, 5, 1, 1, 3, 3, 6, 3, 7, 8, 8, 3, 8, 6, 2, 3, 8, 5, 7, 3, 1, 7, 6, 7, 8, 6, 7, 7, 7, 7, 8, 7, 3, 2, 2, 7, 4, 7, 8, 8, 6, 3, 5, 1, 8, 7, 7, 1, 3, 6, 7, 8, 7, 1, 7, 1, 7, 8, 7, 8, 8, 7, 1, 8, 7, 3, 6, 5, 1, 1, 5, 4, 1, 4, 3, 5, 0, 6, 2, 1, 8, 8, 6, 7, 6, 6, 3, 7, 7, 7, 5, 7, 8, 7, 3, 5, 1, 6, 7, 7, 8, 8, 8, 7, 7, 7, 7, 7, 2, 6, 1, 1, 7, 8, 8, 4, 1, 6, 8, 3, 3, 2, 2, 4, 1, 7, 7, 7, 4, 1, 1, 3, 2, 1, 3, 4, 5, 7, 1, 1, 7, 2, 1, 1, 7, 5, 3, 6, 6, 1, 7, 1, 2, 5, 1, 1, 7, 1, 7, 7, 1, 1, 7, 7, 8, 2, 2, 1, 5, 1, 2, 3, 1, 1, 1, 6, 1, 1, 4, 1, 3, 2, 8, 5, 6, 7, 5, 2, 2, 3, 2, 7, 7, 3, 6, 6, 2, 2, 6, 5, 1], 'Cloud3pm': [8, 7, 8, 8, 8, 6, 7, 8, 7, 2, 8, 7, 7, 1, 3, 6, 7, 6, 7, 1, 7, 1, 1, 0, 7, 6, 7, 8, 3, 1, 2, 1, 2, 3, 1, 7, 2, 2, 0, 0, 1, 4, 1, 1, 2, 1, 2, 7, 2, 8, 7, 6, 2, 7, 5, 1, 3, 2, 1, 1, 1, 7, 1, 0, 1, 6, 6, 6, 5, 1, 2, 4, 6, 3, 7, 8, 7, 7, 7, 6, 7, 5, 7, 7, 7, 2, 6, 1, 3, 7, 3, 1, 1, 2, 7, 3, 1, 1, 1, 7, 1, 7, 1, 1, 2, 7, 1, 0, 1, 7, 2, 5, 1, 3, 2, 1, 6, 2, 2, 1, 7, 7, 8, 8, 8, 6, 1, 7, 8, 1, 8, 1, 2, 7, 8, 7, 7, 8, 7, 7, 1, 3, 7, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 7, 6, 3, 5, 4, 7, 3, 1, 7, 8, 1, 1, 1, 5, 1, 2, 8, 1, 1, 6, 7, 7, 5, 7, 8, 6, 1, 2, 7, 1, 1, 6, 5, 7, 7, 5, 4, 2, 4, 1, 2, 1, 1, 4, 1, 7, 5, 7, 7, 8, 7, 2, 5, 3, 5, 4, 7, 7, 0, 1, 7, 8, 8, 8, 6, 2, 1, 1, 2, 1, 1, 6, 1, 1, 6, 4, 0, 6, 0, 7, 5, 1, 1, 5, 1, 2, 7, 1, 1, 1, 7, 8, 8, 7, 1, 1, 1, 3, 3, 1, 2, 7, 8, 1, 2, 2, 2, 1, 7, 7, 7, 6, 1, 7, 1, 8, 8, 6, 7, 7, 7, 4, 6, 8, 7, 8, 8, 2, 1, 2, 1, 3, 5, 7, 7, 7, 8, 8, 5, 3, 6, 5, 4, 3, 8, 1, 7, 7, 1, 7, 1, 5, 6, 5, 6, 7, 6, 6, 8, 8, 8, 4, 5, 1, 1, 6, 6, 6, 7, 1, 1, 7, 8, 3, 1, 8, 5, 6, 5, 0, 6, 7, 8, 1, 4, 0, 7, 8, 6, 6, 1, 6, 0, 1, 6, 0, 3, 3, 5, 1, 5, 5, 2, 2, 5, 7, 8, 1, 1, 0, 3, 5, 2, 4, 5, 1, 1, 1, 1, 8, 8, 7, 8, 8, 8, 8, 7, 8, 6, 5, 3, 8, 4, 5, 1, 5, 5, 4, 4, 6, 5, 7, 7, 1, 1, 1, 7, 7, 5, 7, 2, 7, 6, 3, 0, 1, 1, 7, 1, 2, 5, 4, 3, 4, 6, 6, 1, 5, 6, 8, 7, 7, 5, 8, 5, 3, 3, 4, 3, 4, 7, 8, 5, 1, 1, 1, 5, 6, 7, 7, 7, 5, 7, 3, 2, 2, 2, 7, 7, 5, 2, 2, 1, 5, 1, 1, 2, 1, 5, 5, 6, 1, 1, 2, 7, 1, 5, 6, 7, 7, 8, 8, 5, 7, 1, 8, 5, 7, 6, 7, 8, 7, 7, 7, 6, 1, 3, 2, 7, 1, 1, 7, 7, 7, 3, 7, 6, 7, 5, 8, 7, 2, 1, 1, 7, 7, 7, 6, 1, 3, 1, 1, 4, 1, 1, 6, 7, 6, 5, 6, 7, 6, 6, 1, 4, 7, 6, 1, 1, 0, 1, 4, 4, 2, 1, 8, 1, 1, 5, 1, 2, 1, 1, 6, 3, 1, 3, 4, 1, 4, 8, 6, 4, 1, 1, 0, 2, 1, 1, 1, 2, 6, 2, 2, 8, 1, 0, 0, 1, 4, 1, 1, 1, 1, 8, 5, 1, 1, 6, 6, 3, 1, 1, 0, 0, 6, 6, 7, 6, 1, 3, 6, 8, 1, 3, 1, 0, 3, 3, 3, 2, 3, 1, 8, 8, 7, 7, 4, 5, 5, 6, 7, 7, 8, 2, 5, 7, 2, 1, 3, 1, 0, 3, 7, 1, 1, 8, 8, 8, 1, 1, 1, 7, 6, 8, 7, 7, 6, 8, 1, 0, 1, 6, 5, 2, 5, 7, 7, 2, 3, 8, 7, 7, 8, 8, 0, 1, 1, 6, 5, 7, 5, 2, 1, 5, 6, 1, 2, 3, 5, 8, 1, 1, 1, 8, 7, 1, 5, 8, 0, 8, 6, 5, 8, 8, 7, 1, 4, 8, 7, 7, 8, 7, 2, 5, 8, 2, 3, 2, 3, 1, 6, 8, 7, 7, 7, 2, 1, 0, 2, 2, 5, 8, 7, 3, 8, 8, 1, 7, 7, 7, 7, 4, 7, 7, 8, 8, 7, 3, 2, 2, 7, 8, 8, 3, 7, 2, 5, 6, 2, 1, 3, 7, 7, 2, 7, 1, 8, 8, 7, 5, 5, 8, 3, 7, 7, 1, 8, 4, 4, 6, 5, 2, 1, 1, 4, 3, 1, 6, 5, 5, 5, 1, 2, 7, 7, 8, 8, 6, 1, 2, 3, 6, 7, 7, 7, 3, 6, 1, 3, 2, 1, 2, 3, 6, 3, 2, 5, 1, 1, 1, 7, 5, 1, 7, 1, 1, 7, 6, 1, 6, 5, 3, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 6, 8, 8, 3, 6, 6, 3, 6, 7, 7, 8, 7, 5, 8, 6, 7, 7, 5, 7, 8, 7, 7, 7, 4, 3, 4, 1, 2, 1, 4, 4, 2, 5, 4, 4, 7, 2, 6, 2, 6, 1, 0, 1, 4, 8, 2, 4, 8, 7, 6, 7, 7, 7, 7, 8, 1, 3, 2, 1, 1, 7, 3, 4, 5, 7, 5, 5, 7, 7, 8, 7, 7, 2, 1, 5, 4, 1, 5, 2, 5, 1, 1, 8, 3, 7, 1, 0, 2, 1, 3, 5, 1, 1, 2, 5, 7, 2, 1, 3, 3, 1, 2, 5, 7, 7, 7, 8, 2, 6, 3, 1, 8, 7, 1, 5, 3, 8, 2, 5, 1, 7, 5, 5, 1, 7, 0, 7, 3, 4, 4, 4, 4, 4, 4, 4, 1, 5, 4, 4, 4, 5, 7, 4, 7, 4, 4, 8, 7, 3, 7, 7, 4, 4, 7, 8, 7, 3, 4, 4, 3, 6, 6, 8, 2, 1, 1, 7, 4, 4, 4, 8, 8, 7, 6, 4, 5, 3, 5, 8, 7, 4, 4, 1, 4, 8, 6, 4, 4, 2, 1, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 3, 5, 7, 7, 2, 7, 2, 5, 7, 5, 8, 6, 1, 1, 0, 0, 2, 5, 1, 7, 6, 7, 2, 7, 3, 4, 6, 1, 6, 2, 3, 1, 2, 7, 1, 0, 1, 2, 7, 7, 2, 6, 4, 2, 1, 1, 6, 7, 1, 1, 3, 6, 6, 6, 1, 1, 1, 0, 0, 5, 1, 1, 1, 8, 1, 1, 3, 6, 5, 3, 2, 1, 1, 1, 1, 6, 1, 5, 7, 1, 1, 1, 7, 0, 5, 7, 1, 6, 6, 7, 7, 1, 1, 2, 2, 6, 1, 4, 2, 7, 2, 3, 2, 6, 7, 1, 8, 2, 6, 3, 7, 1, 8, 4, 4, 4, 8, 7, 5, 6, 2, 7, 3, 8, 7, 8, 4, 3, 3, 3, 6, 7, 7, 1, 2, 7, 7, 7, 2, 6, 3, 7, 1, 0, 1, 1, 1, 6, 6, 7, 5, 7, 7, 2, 3, 4, 1, 3, 8, 8, 7, 7, 7, 2, 1, 6, 8, 8, 6, 2, 1, 8, 8, 6, 3, 3, 3, 1, 4, 3, 5, 5, 2, 1, 7, 7, 3, 1, 2, 3, 3, 7, 7, 5, 1, 2, 7, 1, 7, 7, 6, 6, 3, 2, 8, 8, 6, 7, 3, 6, 3, 2, 1, 1, 1, 2, 4, 6, 7, 6, 4, 7, 1, 2, 2, 1, 1, 0, 1, 1, 3, 7, 5, 4, 7, 3, 1, 7, 6, 4, 1, 1, 6, 2, 8, 6, 3, 3, 1, 1, 1, 3, 7, 8, 6, 7, 1, 1, 5, 8, 3, 5, 5, 7, 7, 1, 1, 7, 8, 6, 7, 7, 8, 6, 6, 3, 6, 7, 4, 6, 2, 7, 6, 2, 7, 7, 7, 6, 7, 7, 7, 8, 5, 1, 2, 0, 1, 1, 0, 1, 3, 7, 6, 5, 1, 6, 8, 7, 4, 3, 7, 7, 2, 1, 2, 7, 6, 3, 1, 1, 6, 1, 5, 4, 3, 3, 1, 5, 2, 5, 7, 7, 7, 1, 1, 7, 1, 1, 1, 0, 4, 1, 5, 1, 3, 7, 7, 4, 1, 6, 2, 2, 7, 1, 4, 1, 2, 1, 1, 5, 7, 4, 7, 7, 4, 3, 4, 7, 3, 5, 8, 5, 1, 1, 6, 2, 2, 1, 5, 1, 0, 0, 1, 1, 3, 7, 7, 4, 1, 6, 3, 2, 5, 0, 1, 1, 0, 1, 2, 0, 1, 7, 2, 0, 5, 6, 8, 1, 1, 0, 1, 7, 2, 7, 2, 1, 7, 7, 6, 1, 5, 1, 1, 6, 3, 7, 7, 7, 3, 1, 6, 7, 8, 8, 2, 1, 5, 7, 5, 2, 7, 1, 1, 7, 7, 2, 4, 5, 1, 7, 6, 1, 6, 2, 7, 1, 3, 2, 1, 5, 5, 3, 1, 1, 1, 3, 1, 7, 7, 7, 8, 1, 5, 1, 1, 1, 1, 8, 7, 6, 1, 2, 1, 7, 7, 7, 3, 2, 3, 2, 0, 1, 0, 0, 0, 6, 7, 7, 7, 7, 8, 4, 7, 3, 1, 1, 0, 1, 3, 1, 0, 8, 7, 7, 1, 0, 0, 6, 2, 7, 8, 8, 8, 8, 4, 7, 8, 2, 1, 4, 2, 1, 1, 7, 7, 7, 8, 8, 7, 7, 3, 7, 5, 2, 3, 2, 1, 7, 3, 1, 7, 7, 1, 5, 6, 3, 4, 2, 7, 8, 7, 7, 8, 8, 7, 3, 6, 7, 1, 7, 8, 3, 8, 6, 6, 7, 8, 7, 6, 7, 5, 8, 3, 1, 3, 1, 1, 3, 7, 3, 7, 1, 7, 7, 6, 7, 2, 1, 6, 7, 1, 3, 3, 2, 6, 7, 7, 3, 2, 3, 2, 1, 1, 3, 7, 1, 7, 2, 1, 5, 6, 2, 6, 7, 1, 5, 3, 4, 8, 3, 1, 3, 7, 7, 6, 7, 7, 1, 6, 6, 7, 2, 7, 1, 5, 1, 3, 6, 1, 1, 7, 1, 1, 5, 7, 2, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 0, 1, 3, 6, 8, 2, 3, 4, 6, 7, 7, 2, 5, 7, 7, 3, 1, 6, 1, 1, 0, 1, 1, 1, 4, 1, 1, 1, 3, 3, 1, 5, 7, 2, 2, 1, 7, 7, 8, 7, 6, 3, 3, 7, 2, 2, 7, 5, 4, 4, 7, 1, 7, 7, 5, 6, 2, 7, 2, 2, 4, 3, 1, 4, 4, 1, 5, 3, 7, 1, 2, 1, 0, 3, 7, 5, 1, 0, 0, 5, 1, 0, 7, 1, 1, 2, 1, 2, 1, 6, 1, 1, 8, 7, 7, 6, 3, 1, 1, 8, 7, 1, 2, 5, 6, 5, 7, 1, 2, 3, 1, 4, 2, 7, 6, 5, 0, 6, 6, 8, 1, 7, 7, 8, 2, 3, 1, 5, 6, 2, 7, 3, 6, 5, 7, 4, 7, 2, 7, 7, 5, 7, 4, 7, 6, 7, 7, 4, 1, 1, 3, 7, 6, 1, 1, 1, 5, 8, 7, 7, 6, 7, 7, 1, 0, 2, 3, 7, 1, 7, 7, 3, 1, 1, 2, 8, 8, 7, 5, 2, 1, 2, 1, 6, 8, 5, 3, 1, 2, 1, 5, 8, 8, 7, 3, 3, 2, 6, 2, 2, 6, 7, 7, 4, 1, 7, 3, 2, 5, 5, 7, 3, 7, 2, 2, 5, 7, 8, 6, 4, 6, 7, 7, 2, 7, 7, 7, 2, 3, 4, 1, 2, 7, 1, 7, 1, 6, 7, 2, 6, 5, 7, 2, 1, 5, 6, 7, 6, 8, 3, 1, 0, 2, 6, 5, 6, 5, 7, 8, 8, 4, 8, 2, 6, 3, 3, 5, 7, 3, 3, 2, 7, 8, 8, 7, 8, 8, 7, 4, 4, 3, 6, 1, 1, 7, 6, 7, 7, 6, 6, 1, 0, 1, 0, 1, 5, 1, 1, 6, 2, 5, 3, 6, 8, 6, 7, 5, 6, 3, 2, 7, 7, 6, 5, 6, 7, 7, 2, 1, 6, 2, 1, 1, 5, 1, 5, 7, 7, 6, 7, 3, 7, 7, 8, 7, 7, 7, 7, 7, 4, 7, 7, 3, 1, 1, 6, 5, 1, 1, 1, 2, 1, 1, 8, 4, 1, 7, 1, 2, 1, 4, 3, 6, 7, 7, 2, 6, 1, 7, 7, 7, 1, 1, 1, 2, 1, 5, 1, 6, 5, 1, 4, 6, 7, 2, 1, 1, 1, 1, 1, 1, 1, 5, 4, 1, 2, 6, 1, 7, 5, 7, 7, 7, 7, 6, 5, 2, 3, 2, 1, 1, 6, 2, 5, 7, 4, 2, 1, 7, 0, 5, 1, 1, 3, 3, 7, 2, 6, 7, 2, 2, 7, 7, 7, 3, 7, 1, 1, 7, 1, 1, 1, 7, 7, 1, 7, 7, 5, 4, 7, 6, 8, 1, 0, 1, 4, 7, 4, 2, 7, 7, 7, 1, 3, 7, 7, 5, 1, 7, 8, 3, 5, 8, 8, 8, 7, 7, 6, 1, 7, 7, 8, 7, 8, 7, 1, 2, 1, 4, 1, 7, 8, 2, 1, 2, 4, 8, 2, 1, 5, 7, 5, 3, 5, 7, 7, 3, 3, 7, 4, 7, 3, 8, 8, 1, 1, 1, 8, 8, 7, 2, 4, 7, 1, 7, 1, 1, 5, 4, 7, 8, 8, 8, 8, 7, 1, 6, 1, 1, 7, 1, 7, 5, 4, 2, 3, 6, 4, 7, 6, 7, 8, 4, 8, 7, 7, 7, 5, 4, 3, 4, 7, 5, 3, 3, 1, 1, 1, 7, 1, 1, 5, 3, 2, 1, 1, 1, 5, 4, 6, 1, 1, 0, 7, 5, 1, 5, 1, 7, 4, 2, 1, 1, 1, 3, 4, 7, 7, 2, 7, 6, 6, 4, 4, 7, 1, 8, 7, 7, 3, 3, 7, 2, 6, 6, 8, 6, 2, 1, 3, 2, 7, 3, 1, 7, 8, 7, 3, 6, 5, 2, 7, 5, 7, 7, 7, 7, 2, 5, 7, 6, 3, 1, 3, 2, 1, 8, 6, 5, 7, 0, 2, 1, 1, 6, 7, 7, 1, 6, 6, 1, 0, 5, 1, 1, 7, 1, 1, 7, 4, 1, 2, 7, 2, 1, 6, 1, 1, 7, 7, 7, 7, 8, 8, 7, 7, 1, 1, 1, 5, 1, 1, 4, 3, 1, 7, 6, 8, 6, 4, 1, 4, 3, 1, 7, 8, 1, 1, 1, 0, 7, 2, 6, 7, 8, 5, 3, 7, 7, 7, 2, 2, 7, 7, 0, 5, 8, 5, 4, 1, 2, 1, 1, 3, 0, 2, 3, 2, 8, 8, 8, 6, 7, 6, 1, 7, 3, 1, 7, 2, 1, 1, 0, 6, 1, 6, 3, 1, 7, 7, 8, 3, 7, 1, 2, 7, 6, 7, 3, 8, 5, 1, 0, 0, 3, 5, 4, 7, 6, 3, 7, 7, 7, 3, 7, 8, 1, 7, 8, 7, 2, 1, 7, 1, 2, 1, 2, 3, 3, 0, 7, 1, 1, 8, 5, 5, 7, 7, 3, 5, 7, 1, 0, 1, 7, 3, 2, 5, 7, 7, 2, 1, 1, 7, 7, 8, 5, 8, 1, 1, 1, 1, 1, 1, 7, 1, 7, 7, 2, 1, 3, 1, 7, 3, 3, 1, 2, 7, 7, 5, 3, 1, 2, 1, 7, 1, 6, 2, 7, 5, 5, 7, 7, 8, 4, 2, 1, 2, 1, 1, 5, 7, 8, 8, 4, 8, 3, 3, 2, 5, 2, 7, 3, 1, 7, 6, 6, 7, 7, 8, 5, 7, 7, 7, 6, 3, 6, 2, 4, 7, 2, 1, 1, 7, 0, 2, 2, 8, 7, 1, 4, 1, 7, 8, 6, 4, 1, 6, 3, 7, 8, 7, 8, 5, 7, 1, 7, 7, 1, 2, 3, 7, 1, 6, 2, 1, 7, 2, 2, 0, 2, 1, 1, 7, 8, 3, 3, 6, 7, 5, 8, 7, 7, 3, 7, 8, 7, 3, 2, 1, 6, 8, 6, 7, 8, 7, 7, 7, 6, 6, 8, 7, 7, 2, 1, 8, 1, 8, 2, 2, 6, 7, 6, 3, 3, 2, 4, 4, 7, 7, 7, 3, 1, 4, 5, 2, 1, 6, 2, 6, 5, 2, 3, 7, 4, 5, 3, 4, 5, 6, 8, 7, 1, 6, 1, 1, 1, 1, 7, 7, 7, 7, 1, 1, 2, 4, 7, 3, 1, 4, 2, 1, 0, 3, 3, 6, 1, 6, 4, 1, 4, 7, 2, 5, 2, 8, 6, 7, 7, 6, 3, 3, 7, 6, 7, 7, 5, 7, 1, 2, 2, 6, 2, 1], 'Temp9am': [20.7, 22.4, 23.5, 21.4, 22.5, 23.8, 21.7, 18.9, 17.1, 17.2, 18.9, 22.9, 20.9, 18.4, 19.5, 19.8, 21.8, 21.2, 20.8, 21.3, 22.1, 22.3, 22.5, 21.2, 21.6, 23.0, 21.3, 20.4, 17.1, 15.9, 15.1, 18.2, 18.7, 22.6, 22.1, 22.9, 18.8, 19.7, 22.9, 21.9, 22.2, 22.4, 21.8, 22.5, 22.8, 22.0, 22.2, 23.9, 23.5, 17.8, 19.6, 18.5, 19.9, 21.4, 20.5, 17.5, 18.3, 16.7, 16.9, 16.3, 16.7, 17.8, 16.6, 13.9, 15.2, 17.7, 18.2, 17.0, 16.3, 18.7, 17.1, 17.6, 17.4, 15.9, 15.9, 17.2, 16.4, 16.4, 19.3, 17.3, 16.6, 16.1, 16.2, 16.8, 15.6, 20.3, 13.7, 11.7, 11.6, 13.4, 14.5, 14.1, 12.4, 12.4, 13.7, 16.5, 14.0, 14.3, 15.2, 16.8, 14.9, 15.0, 13.8, 13.9, 15.9, 19.2, 11.6, 12.5, 13.0, 13.5, 15.1, 12.7, 13.3, 11.1, 12.9, 13.6, 12.8, 12.7, 12.7, 11.7, 14.3, 15.3, 15.6, 17.5, 16.0, 15.1, 13.3, 14.1, 13.9, 13.2, 17.3, 14.1, 16.6, 11.2, 13.7, 15.0, 14.2, 14.8, 13.9, 14.3, 13.2, 11.4, 9.9, 10.7, 11.8, 14.6, 10.8, 10.1, 9.2, 13.8, 13.1, 14.6, 10.7, 9.1, 11.3, 9.8, 11.3, 12.1, 9.6, 10.2, 11.3, 7.8, 11.5, 12.0, 11.1, 10.8, 10.1, 10.1, 10.9, 14.6, 13.1, 8.8, 7.0, 10.9, 10.5, 8.4, 9.1, 8.4, 9.1, 9.4, 7.9, 17.2, 11.9, 11.6, 10.6, 9.2, 9.5, 10.9, 11.7, 9.9, 10.5, 9.4, 10.7, 12.2, 10.2, 12.4, 13.2, 10.4, 9.2, 9.5, 12.6, 12.0, 10.5, 11.2, 9.8, 11.1, 11.1, 12.0, 12.5, 12.1, 15.3, 15.0, 14.1, 15.8, 15.4, 15.6, 13.0, 14.1, 13.9, 12.6, 12.4, 12.3, 14.8, 24.3, 18.0, 22.5, 14.3, 14.8, 15.7, 19.4, 25.8, 18.0, 19.1, 15.6, 16.2, 16.0, 17.9, 20.4, 25.4, 19.4, 16.5, 19.0, 24.7, 29.6, 18.9, 14.9, 18.5, 12.8, 14.0, 15.8, 16.9, 16.0, 18.6, 20.2, 16.8, 15.9, 16.6, 17.6, 18.6, 21.3, 18.1, 16.8, 10.3, 11.9, 14.4, 17.3, 20.2, 23.7, 20.8, 17.2, 17.0, 25.6, 18.9, 18.3, 23.1, 17.5, 18.2, 21.0, 18.7, 22.1, 20.7, 21.9, 20.5, 20.5, 23.4, 24.3, 18.6, 19.1, 18.8, 20.6, 18.4, 22.0, 22.1, 20.3, 13.8, 19.7, 18.5, 18.5, 21.8, 22.9, 20.3, 19.8, 24.9, 20.8, 22.5, 19.6, 20.9, 27.0, 21.1, 20.3, 19.5, 21.9, 17.5, 17.6, 24.5, 21.5, 20.9, 21.0, 22.3, 23.1, 21.6, 18.4, 19.6, 22.1, 23.8, 19.6, 20.7, 23.1, 24.5, 23.4, 22.6, 20.9, 24.7, 22.0, 20.1, 18.8, 23.0, 23.4, 23.1, 23.7, 21.2, 19.2, 19.7, 23.4, 23.2, 23.5, 25.5, 28.6, 21.4, 19.0, 19.5, 22.5, 24.7, 25.7, 27.8, 29.5, 31.5, 21.9, 21.9, 20.8, 23.7, 25.2, 24.6, 25.0, 24.9, 24.8, 25.4, 23.2, 26.0, 25.5, 25.6, 24.2, 21.2, 18.2, 17.7, 18.9, 18.0, 19.1, 19.4, 20.3, 20.8, 20.2, 23.1, 22.4, 22.5, 21.7, 22.6, 23.0, 22.0, 20.7, 18.9, 20.7, 23.1, 22.8, 24.1, 24.2, 19.3, 17.8, 20.5, 22.2, 19.1, 22.8, 23.3, 20.3, 21.1, 22.3, 21.7, 18.7, 18.8, 20.1, 20.6, 23.5, 22.1, 20.4, 23.1, 23.6, 23.0, 23.8, 22.0, 17.9, 18.9, 22.9, 21.1, 20.5, 21.9, 21.4, 18.4, 19.1, 19.5, 18.8, 18.7, 19.6, 18.4, 19.8, 21.6, 19.2, 20.5, 17.4, 18.4, 18.3, 16.1, 19.5, 20.5, 17.2, 16.9, 17.4, 19.3, 17.7, 14.1, 16.1, 12.6, 12.8, 13.0, 14.0, 12.8, 14.5, 14.7, 14.1, 15.0, 14.9, 13.4, 13.9, 14.3, 12.0, 12.4, 15.2, 14.2, 18.7, 13.0, 13.2, 14.5, 19.2, 19.2, 19.1, 19.6, 19.7, 15.4, 13.9, 15.3, 13.5, 12.4, 11.7, 14.5, 13.3, 13.7, 16.0, 13.4, 14.5, 11.6, 12.6, 13.8, 11.7, 10.5, 7.9, 8.2, 9.4, 11.0, 10.2, 13.1, 11.2, 10.7, 10.9, 11.7, 14.1, 15.1, 11.2, 10.7, 11.9, 10.7, 10.4, 12.4, 12.3, 15.6, 16.5, 13.0, 12.3, 10.1, 11.8, 7.5, 9.0, 10.5, 10.3, 10.8, 10.3, 11.8, 14.5, 12.1, 8.9, 9.2, 10.7, 9.0, 10.2, 10.3, 11.2, 19.7, 13.6, 9.9, 8.9, 9.9, 10.5, 11.2, 11.3, 10.7, 12.8, 11.5, 10.2, 13.4, 11.7, 10.5, 11.2, 15.4, 9.8, 8.5, 9.1, 11.7, 11.9, 12.8, 14.0, 11.1, 13.0, 18.5, 12.1, 10.8, 12.2, 18.4, 15.3, 17.0, 23.3, 15.8, 15.1, 16.0, 17.2, 16.6, 13.9, 14.7, 16.1, 14.4, 15.2, 16.0, 18.2, 14.4, 14.6, 16.2, 15.7, 16.0, 15.2, 17.3, 25.2, 18.5, 16.9, 17.4, 22.2, 22.7, 18.3, 20.7, 18.8, 25.8, 17.3, 18.8, 21.0, 17.7, 13.9, 15.2, 17.0, 18.4, 25.6, 18.3, 13.8, 13.5, 14.2, 13.5, 14.1, 13.8, 13.5, 12.0, 13.1, 17.8, 20.1, 19.7, 18.8, 15.1, 16.8, 15.5, 16.6, 19.0, 21.1, 18.5, 21.3, 19.7, 20.3, 14.7, 17.0, 20.5, 20.0, 21.7, 20.6, 24.0, 19.7, 19.4, 19.2, 20.9, 20.4, 20.9, 21.6, 21.0, 22.0, 21.7, 20.1, 22.2, 22.6, 21.1, 19.8, 23.6, 26.2, 25.4, 24.0, 21.4, 18.7, 21.3, 22.3, 26.1, 26.0, 25.3, 21.2, 17.9, 17.3, 19.7, 21.8, 20.2, 23.4, 25.4, 22.6, 19.2, 23.4, 24.1, 22.7, 23.5, 21.3, 24.3, 24.1, 26.0, 20.2, 21.4, 20.9, 22.4, 24.6, 17.8, 20.2, 20.6, 23.0, 22.4, 20.9, 24.3, 25.6, 20.1, 21.4, 23.6, 22.5, 21.8, 22.9, 24.4, 28.3, 24.2, 25.0, 27.0, 19.6, 21.7, 23.4, 24.6, 21.0, 19.8, 23.2, 24.0, 25.0, 31.9, 19.5, 22.4, 25.1, 23.4, 23.7, 22.2, 21.6, 25.6, 25.6, 25.0, 22.0, 25.2, 25.8, 21.6, 21.1, 23.5, 24.3, 25.6, 25.3, 26.9, 22.1, 23.5, 21.4, 22.3, 21.4, 23.7, 22.6, 22.2, 23.5, 26.7, 28.5, 22.4, 23.3, 20.2, 21.9, 23.7, 19.4, 19.5, 22.7, 20.9, 23.9, 22.4, 25.0, 24.8, 23.9, 19.3, 20.4, 23.3, 20.5, 18.7, 19.7, 20.0, 18.8, 19.8, 20.1, 22.8, 23.5, 22.5, 21.6, 20.3, 21.1, 22.6, 23.0, 23.1, 23.2, 20.6, 21.0, 18.4, 19.0, 18.6, 17.7, 19.6, 21.4, 19.1, 22.2, 20.8, 18.6, 24.5, 16.8, 17.6, 15.9, 17.5, 18.1, 19.1, 20.5, 20.0, 17.6, 19.3, 20.2, 22.8, 17.3, 15.1, 14.2, 16.0, 18.2, 14.4, 15.1, 15.3, 18.0, 19.2, 18.7, 13.9, 13.5, 14.1, 15.3, 15.7, 16.3, 12.7, 12.0, 13.0, 13.2, 12.7, 13.1, 13.0, 13.0, 12.7, 13.9, 11.3, 10.4, 12.1, 14.1, 13.5, 15.9, 12.9, 15.8, 13.0, 16.5, 14.5, 12.7, 15.2, 17.3, 13.5, 11.3, 10.6, 10.6, 11.1, 11.3, 9.0, 11.5, 8.4, 8.9, 10.0, 10.6, 14.2, 11.3, 11.5, 14.4, 12.2, 13.7, 15.2, 8.1, 7.0, 7.0, 6.4, 8.5, 9.2, 9.1, 8.9, 9.7, 10.8, 10.3, 10.7, 9.9, 16.7, 11.4, 14.1, 14.4, 11.9, 9.0, 8.6, 8.9, 11.1, 10.2, 9.2, 8.8, 9.8, 10.3, 12.5, 11.9, 11.2, 12.3, 12.8, 12.8, 14.5, 13.2, 11.2, 13.9, 11.2, 11.1, 10.5, 9.1, 8.8, 9.3, 12.2, 12.8, 12.2, 12.7, 13.0, 15.1, 14.3, 10.8, 9.3, 19.5, 14.3, 12.8, 11.4, 12.4, 13.9, 14.1, 13.8, 14.1, 12.3, 14.9, 15.8, 18.2, 17.8, 15.2, 17.6, 18.6, 15.1, 14.4, 13.1, 13.0, 16.2, 15.3, 13.6, 16.2, 17.6, 15.3, 13.5, 15.0, 15.0, 16.8, 15.3, 16.6, 16.6, 19.0, 18.5, 19.5, 18.3, 15.3, 17.9, 22.3, 21.5, 12.9, 14.7, 16.9, 17.6, 19.0, 21.4, 14.1, 17.8, 20.2, 18.3, 16.2, 22.0, 20.7, 18.7, 13.3, 17.6, 14.8, 15.2, 14.1, 16.6, 23.3, 19.7, 20.9, 20.1, 26.1, 23.9, 18.8, 17.5, 22.3, 17.4, 19.3, 22.8, 22.5, 23.9, 22.3, 21.7, 18.0, 17.3, 18.9, 20.1, 23.7, 20.9, 23.6, 23.5, 24.8, 23.4, 23.6, 22.2, 24.8, 22.6, 24.0, 24.7, 20.5, 20.7, 19.8, 16.7, 21.3, 22.0, 21.4, 19.8, 21.5, 21.1, 18.5, 19.0, 21.1, 24.7, 24.0, 25.5, 24.7, 19.9, 20.1, 21.1, 22.6, 22.1, 24.3, 24.0, 24.1, 24.3, 25.2, 25.0, 26.5, 22.6, 23.1, 25.8, 22.4, 21.6, 24.8, 25.1, 25.0, 25.2, 26.6, 24.3, 25.8, 25.1, 23.1, 20.7, 23.1, 26.1, 26.1, 28.7, 30.6, 27.3, 33.7, 28.7, 18.7, 21.2, 21.8, 21.3, 25.3, 22.7, 21.5, 21.9, 20.7, 20.9, 24.4, 23.5, 25.1, 30.1, 20.9, 20.4, 19.0, 20.3, 21.1, 23.7, 22.3, 22.7, 28.8, 20.5, 20.9, 22.5, 18.7, 21.0, 20.3, 21.2, 21.8, 23.8, 23.2, 23.3, 24.5, 24.3, 21.0, 22.3, 21.1, 21.1, 21.2, 19.4, 21.4, 21.6, 22.5, 21.5, 20.5, 18.4, 16.6, 17.1, 19.4, 20.5, 20.3, 16.6, 14.3, 15.0, 15.2, 16.2, 13.1, 12.0, 12.2, 14.5, 11.8, 11.3, 10.5, 12.8, 11.7, 9.9, 9.6, 10.0, 11.6, 13.8, 12.8, 13.7, 13.9, 16.0, 14.6, 12.3, 12.9, 10.5, 10.4, 11.2, 15.4, 17.9, 18.7, 17.4, 12.2, 13.3, 11.6, 12.2, 8.6, 9.8, 9.7, 11.6, 12.6, 13.6, 13.7, 15.7, 15.3, 15.9, 10.0, 11.3, 10.5, 11.9, 14.2, 11.2, 12.6, 9.8, 9.8, 9.0, 10.4, 10.7, 15.0, 14.4, 12.3, 12.3, 10.1, 17.0, 14.0, 13.0, 13.9, 8.1, 9.1, 10.4, 11.7, 9.5, 10.3, 11.0, 7.5, 10.4, 11.9, 11.2, 8.7, 14.3, 12.0, 13.1, 9.1, 8.3, 10.9, 10.1, 10.4, 9.4, 9.6, 8.7, 10.5, 12.5, 12.5, 13.9, 14.0, 13.9, 15.5, 14.2, 11.1, 9.7, 10.7, 11.5, 14.8, 10.4, 13.7, 11.6, 12.8, 12.4, 12.9, 9.1, 16.3, 16.2, 15.7, 13.6, 13.7, 13.0, 17.2, 13.3, 13.6, 16.3, 16.8, 15.2, 15.3, 14.9, 13.8, 17.2, 18.0, 20.5, 14.9, 15.6, 12.2, 11.5, 14.5, 14.0, 13.5, 19.0, 16.2, 17.8, 20.5, 25.4, 19.9, 25.6, 18.0, 17.6, 22.8, 16.5, 14.2, 17.0, 17.3, 17.3, 17.5, 15.8, 15.8, 13.1, 13.3, 13.3, 13.5, 15.4, 15.7, 16.1, 15.7, 14.4, 15.6, 15.6, 16.8, 17.4, 19.2, 20.4, 16.2, 17.7, 16.9, 18.0, 20.5, 19.6, 20.5, 24.8, 19.4, 14.9, 18.4, 19.0, 21.7, 21.6, 18.6, 16.2, 19.3, 14.5, 18.0, 20.3, 23.9, 26.5, 23.3, 24.2, 24.4, 21.5, 21.2, 23.0, 21.2, 17.2, 21.3, 22.9, 22.6, 20.4, 19.6, 15.6, 17.4, 18.3, 19.9, 23.4, 23.6, 24.6, 23.7, 17.5, 16.6, 17.6, 19.9, 15.9, 15.3, 17.7, 18.0, 20.0, 20.7, 23.0, 17.7, 19.2, 19.0, 19.6, 18.9, 20.8, 18.7, 20.2, 19.9, 20.6, 20.1, 22.7, 23.7, 24.0, 24.5, 20.1, 20.8, 20.7, 19.3, 20.5, 22.2, 24.1, 24.1, 25.0, 22.3, 19.3, 20.0, 22.1, 22.4, 22.6, 23.5, 17.6, 19.7, 20.5, 17.8, 20.4, 23.9, 23.1, 23.1, 22.6, 22.9, 22.9, 21.7, 23.7, 22.5, 23.5, 23.5, 23.8, 26.5, 27.2, 18.8, 20.1, 17.1, 19.9, 22.2, 22.3, 19.6, 22.3, 22.2, 22.3, 20.4, 19.7, 19.9, 20.8, 22.7, 22.8, 23.8, 23.0, 23.0, 22.8, 20.9, 20.1, 21.5, 22.7, 23.3, 22.8, 23.6, 26.2, 20.5, 21.3, 19.5, 20.9, 22.4, 22.7, 21.4, 19.0, 15.6, 18.5, 20.1, 20.4, 22.6, 20.1, 20.2, 22.5, 22.6, 18.6, 19.4, 21.1, 19.6, 20.5, 18.6, 19.5, 16.1, 16.5, 19.5, 20.6, 20.4, 20.1, 17.5, 18.9, 21.0, 21.7, 18.6, 24.6, 23.8, 22.3, 21.5, 22.0, 17.6, 15.5, 15.6, 16.4, 16.4, 18.9, 20.2, 19.0, 18.6, 17.6, 19.5, 19.1, 19.8, 19.4, 18.4, 13.5, 16.8, 15.4, 16.0, 17.7, 13.5, 15.5, 15.6, 17.7, 13.7, 15.1, 12.9, 12.4, 13.8, 15.3, 16.7, 16.5, 15.1, 13.5, 11.8, 12.1, 12.0, 12.5, 12.4, 12.4, 13.0, 13.6, 11.8, 13.2, 12.2, 15.7, 12.5, 12.3, 12.1, 12.1, 12.8, 12.9, 12.8, 14.9, 14.2, 14.3, 12.0, 14.0, 10.4, 8.6, 8.3, 10.0, 11.8, 16.1, 12.1, 12.9, 11.8, 12.0, 12.1, 11.6, 11.4, 9.1, 10.7, 16.4, 9.3, 9.9, 12.8, 12.4, 10.5, 12.3, 12.1, 10.4, 11.3, 9.6, 9.6, 10.7, 11.0, 9.9, 10.4, 9.3, 10.2, 13.2, 13.0, 17.2, 13.4, 12.2, 11.3, 9.8, 10.5, 10.8, 8.1, 13.3, 10.6, 11.2, 10.0, 14.7, 11.3, 9.8, 11.5, 9.6, 9.9, 9.5, 9.2, 9.7, 9.9, 12.2, 14.3, 9.8, 9.5, 13.5, 10.4, 14.6, 13.5, 15.9, 12.7, 13.4, 10.1, 11.0, 16.1, 22.2, 13.6, 13.8, 11.7, 17.2, 12.8, 10.5, 12.1, 13.3, 13.6, 20.8, 21.5, 21.3, 15.0, 16.4, 15.8, 21.0, 13.5, 15.6, 17.5, 16.4, 17.9, 17.2, 15.6, 15.5, 19.0, 17.8, 17.3, 15.0, 17.8, 19.4, 21.7, 15.4, 16.4, 17.5, 18.7, 23.9, 27.9, 16.0, 16.1, 15.3, 13.8, 14.6, 8.7, 14.3, 14.0, 16.3, 20.9, 21.7, 19.4, 17.7, 22.8, 19.9, 15.6, 15.7, 17.3, 18.2, 18.4, 18.0, 17.0, 17.2, 18.6, 21.6, 22.6, 18.1, 15.5, 18.3, 21.5, 24.0, 21.7, 24.1, 22.2, 19.6, 19.4, 19.4, 19.6, 16.9, 20.5, 17.2, 17.4, 19.2, 18.1, 18.9, 19.8, 18.8, 18.7, 21.0, 25.3, 22.5, 22.4, 20.5, 23.6, 25.9, 23.2, 21.8, 21.8, 24.4, 25.2, 25.6, 23.2, 27.3, 22.5, 22.3, 25.0, 29.4, 22.4, 18.8, 20.5, 23.2, 24.3, 28.9, 22.7, 22.3, 24.2, 26.5, 21.8, 22.7, 25.8, 26.5, 20.5, 22.7, 21.5, 22.2, 25.9, 19.5, 19.0, 23.1, 23.7, 23.1, 21.6, 22.8, 22.4, 22.5, 22.3, 23.2, 21.9, 21.5, 23.1, 20.8, 23.3, 19.2, 16.8, 16.3, 19.3, 21.1, 26.1, 24.2, 22.6, 21.8, 21.7, 23.4, 23.4, 19.2, 18.7, 18.3, 18.6, 19.0, 17.0, 16.6, 17.5, 17.0, 19.0, 18.4, 16.7, 18.9, 19.0, 19.7, 19.6, 19.0, 19.0, 17.2, 17.7, 18.5, 15.3, 14.6, 14.4, 14.6, 16.9, 15.5, 15.1, 17.3, 17.2, 18.6, 18.5, 19.7, 18.1, 15.1, 14.0, 17.4, 14.5, 14.3, 15.2, 15.2, 14.7, 14.3, 15.2, 14.3, 14.4, 14.2, 13.6, 16.9, 14.7, 13.2, 12.1, 11.3, 15.4, 11.2, 13.4, 13.0, 12.2, 11.3, 11.6, 12.9, 12.3, 12.8, 13.9, 18.7, 14.7, 11.7, 12.2, 11.7, 14.9, 18.5, 14.2, 12.6, 11.1, 11.3, 11.6, 13.4, 14.0, 13.8, 11.8, 11.0, 9.6, 10.5, 9.9, 9.6, 7.9, 11.0, 10.2, 10.6, 16.7, 13.4, 13.3, 13.6, 12.4, 10.3, 10.2, 9.5, 14.7, 16.0, 10.2, 10.0, 9.3, 9.3, 10.3, 9.1, 9.6, 10.9, 10.7, 15.4, 15.1, 14.5, 15.1, 18.1, 16.5, 11.0, 12.2, 11.0, 12.3, 8.8, 9.2, 9.4, 9.7, 17.6, 12.8, 13.9, 11.0, 10.9, 13.5, 14.0, 13.1, 16.4, 13.0, 9.3, 11.2, 13.4, 12.7, 19.6, 14.5, 15.9, 12.3, 10.8, 17.6, 16.2, 17.0, 10.7, 11.3, 12.5, 14.8, 15.9, 12.7, 14.2, 15.4, 14.9, 15.3, 21.7, 15.9, 15.8, 15.9, 16.4, 15.7, 17.7, 20.5, 19.2, 17.5, 21.1, 25.9, 16.9, 17.5, 14.9, 17.0, 16.4, 16.5, 17.7, 20.7, 19.9, 18.6, 16.8, 16.9, 19.1, 22.4, 23.4, 26.9, 18.1, 18.9, 19.4, 20.3, 24.7, 20.8, 17.7, 16.1, 17.8, 20.1, 18.3, 17.7, 17.6, 27.3, 18.4, 18.5, 24.7, 14.8, 15.4, 21.1, 27.5, 17.9, 17.6, 20.7, 21.4, 21.4, 27.0, 20.2, 16.0, 17.2, 20.5, 19.5, 19.5, 16.7, 18.2, 19.0, 19.3, 23.8, 17.0, 16.6, 17.4, 20.6, 24.5, 24.8, 15.8, 16.0, 17.4, 20.7, 22.5, 20.7, 18.0, 16.4, 17.9, 20.0, 20.8, 23.6, 21.1, 21.7, 20.8, 20.8, 17.0, 19.5, 23.3, 20.9, 18.5, 19.0, 21.3, 22.8, 23.5, 21.5, 17.1, 20.0, 22.6, 25.4, 28.6, 23.7, 20.6, 24.3, 23.7, 20.1, 20.1, 22.5, 24.5, 23.1, 26.2, 25.1, 25.5, 27.5, 21.8, 18.9, 21.5, 21.0, 23.6, 21.4, 22.1, 22.5, 24.4, 27.1, 22.2, 22.9, 24.2, 25.3, 20.9, 18.3, 21.1, 22.3, 23.5, 24.8, 21.9, 22.8, 25.6, 25.3, 24.2, 25.1, 24.9, 24.1, 21.6, 21.8, 22.4, 23.9, 22.5, 18.1, 20.6, 24.7, 24.5, 25.2, 24.7, 23.6, 24.6, 24.9, 25.1, 20.6, 19.2, 19.6, 24.3, 24.6, 20.8, 22.4, 23.5, 25.1, 21.6, 21.5, 24.7, 19.0, 20.6, 23.8, 22.2, 21.1, 22.0, 23.0, 21.7, 23.2, 25.1, 21.7, 19.7, 19.6, 19.3, 21.7, 20.9, 21.9, 22.3, 23.0, 23.8, 22.8, 25.6, 22.8, 22.1, 19.6, 22.7, 22.5, 24.2, 19.4, 19.9, 23.9, 25.5, 21.7, 23.6, 23.0, 20.3, 19.8, 21.2, 21.2, 18.7, 20.6, 22.4, 19.6, 20.5, 18.9, 21.3, 20.4, 20.6, 19.2, 16.9, 19.6, 20.4, 20.2, 24.1, 19.1, 17.8, 17.2, 17.3, 17.7, 17.2, 16.7, 19.2, 16.3, 15.9, 15.8, 17.6, 19.3, 17.7, 18.2, 17.9, 17.4, 18.4, 18.6, 14.7, 16.1, 12.7, 15.0, 12.8, 14.6, 13.9, 14.2, 13.9, 14.5, 16.7, 16.7, 15.6, 14.8, 13.7, 14.6, 14.3, 14.8, 15.8, 16.2, 17.5, 14.9, 16.5, 17.7, 17.2, 16.3, 19.4, 19.3, 15.3, 15.9, 15.2, 17.0, 14.5, 13.2, 13.6, 15.3, 15.3, 12.2, 11.9, 10.4, 13.0, 11.9, 12.1, 11.8, 14.3, 13.0, 11.3, 13.5, 12.5, 12.0, 15.5, 11.8, 11.9, 13.5, 12.1, 14.8, 15.1, 12.1, 15.8, 12.1, 11.4, 10.1, 9.6, 9.1, 9.3, 10.1, 11.6, 10.7, 9.0, 11.9, 11.9, 11.8, 8.9, 8.2, 9.2, 11.5, 13.2, 13.1, 9.6, 10.1, 11.2, 9.9, 10.8, 10.7, 10.9, 11.5, 13.0, 11.9, 11.9, 14.9, 17.3, 17.7, 16.8, 9.6, 8.4, 9.9, 10.0, 9.7, 11.4, 10.9, 10.2, 12.7, 10.3, 8.9, 10.5, 9.5, 10.5, 10.3, 14.4, 13.8, 15.5, 12.5, 11.7, 13.2, 11.8, 13.0, 13.7, 13.6, 15.3, 15.3, 12.1, 12.5, 14.8, 14.6, 15.8, 13.1, 13.4, 13.2, 12.3, 12.5, 12.2, 19.3, 14.8, 18.1, 14.7, 14.4, 17.3, 17.7, 15.6, 14.7, 15.4, 15.4, 16.9, 17.2, 18.5, 20.0, 18.8, 18.8, 20.4, 25.2, 23.7, 18.2, 17.6, 19.0, 19.2, 18.4, 19.7, 24.1, 16.7, 18.6, 20.2, 19.9, 20.3, 22.5, 14.9, 11.6, 14.3, 15.2, 15.3, 18.6, 19.8, 17.4, 17.8, 19.7, 22.0, 21.0, 23.5, 23.2, 21.7, 22.6, 21.1, 16.8, 17.0, 20.4, 20.7, 20.1, 20.6, 21.4, 23.1, 20.7, 21.3, 18.8, 20.0, 23.3, 20.1, 18.2, 21.3, 22.3, 21.9, 24.8, 31.0, 23.6, 24.9, 23.5, 24.0, 21.5, 23.8, 25.1, 23.7, 26.2, 22.7, 24.3, 23.4, 24.5, 22.0, 22.5, 22.5, 21.7, 20.6, 20.0, 24.3, 22.1, 21.2, 19.1, 21.2, 20.7, 22.5, 24.8, 21.1, 22.4, 23.2, 24.1, 20.6, 20.2, 23.6, 23.4, 22.2, 25.2, 23.2, 26.3, 26.9, 21.8, 24.4, 27.1, 25.8, 25.7, 24.3, 21.1, 22.9, 21.2, 28.6, 26.1, 24.7, 27.0, 24.5, 21.7, 20.3, 24.4, 26.4, 25.8, 26.7, 25.0, 20.4, 19.2, 17.9, 19.0, 19.6, 21.4, 22.0, 19.6, 20.1, 20.1, 21.9, 20.5, 20.3, 23.3, 23.7, 24.0, 25.8, 26.1, 22.1, 23.1, 22.4, 25.4, 25.7, 26.4, 23.0, 23.8, 22.9, 23.8, 24.1, 23.3, 22.2, 21.5, 21.1, 23.3, 26.2, 20.1, 22.5, 23.7, 25.2, 21.1, 19.8, 21.0, 23.7, 22.8, 22.5, 25.0, 20.8, 20.1, 21.8, 17.9, 20.4, 22.5, 22.8, 23.8, 19.6, 22.2, 22.8, 22.2, 18.0, 20.4, 17.2, 18.5, 17.3, 19.1, 19.7, 18.8, 20.3, 18.1, 18.0, 19.9, 19.9, 20.0, 18.3, 18.6, 16.8, 17.5, 18.7, 19.1, 18.2, 18.6, 21.6, 21.0, 23.7, 19.4, 15.0, 14.9, 16.1, 16.4, 17.3, 17.2, 13.8, 15.3, 14.0, 14.0, 16.0, 16.7, 21.7, 19.0, 18.3, 19.0, 15.3, 15.1, 13.8, 14.5, 15.4, 16.8, 16.2, 13.9, 11.3, 14.2, 15.1, 13.0, 13.8, 16.9, 17.4, 16.5, 15.2, 11.8, 10.1, 11.4, 10.4, 13.1, 13.6, 17.3, 13.1, 12.1, 13.4, 9.5, 8.8, 8.9, 10.2, 11.9, 10.8, 14.8, 17.1, 12.9, 13.3, 13.5, 13.8, 11.2, 12.9, 16.5, 16.0, 13.5, 9.9, 9.8, 9.1, 9.3, 10.2, 13.2, 15.2, 11.7, 9.7, 9.3, 11.0, 10.7, 12.0, 8.4, 8.1, 7.6, 7.7, 8.6, 11.2, 8.4, 8.3, 9.4, 7.2, 9.8, 8.6, 11.5, 8.7, 10.3, 6.7, 10.4, 10.3, 10.0, 9.9, 13.4, 12.0, 12.9, 14.3, 13.8, 10.2, 9.6, 9.3, 10.7, 14.7, 14.3, 16.9, 11.7, 8.9, 9.4, 9.5, 10.0, 11.0, 9.1, 11.8, 13.3, 11.1, 12.3, 11.8, 12.4, 14.0, 13.4, 12.6, 12.5, 12.1, 13.0, 19.8, 15.6, 16.3, 16.1, 16.3, 15.1, 14.6, 13.0, 12.1, 13.9, 12.7, 11.9, 14.4, 13.7, 15.2, 14.6, 17.4, 13.3, 15.4, 15.5, 17.6, 17.2, 18.3, 20.7, 23.5, 17.2, 18.0, 15.8, 14.7, 16.6, 16.3, 18.7, 13.3, 13.0, 13.4, 14.4, 15.3, 17.3, 19.1, 21.0, 19.9, 21.3, 21.5, 26.4, 21.1, 23.8, 20.3, 18.5, 20.1, 21.2, 18.7, 22.7, 18.3, 20.1, 21.6, 23.3, 21.5, 19.5, 21.8, 23.7, 24.5, 19.6, 16.6, 17.8, 21.1, 24.6, 16.5, 16.4, 18.2, 19.0, 22.2, 21.9, 21.6, 19.0, 19.5, 18.2, 23.3, 22.5, 18.0, 19.5, 20.6, 20.0, 23.5, 22.7, 18.7, 18.2, 19.1, 20.2, 25.1, 23.1, 25.2, 20.8, 19.8, 22.4, 23.6, 32.4, 21.1, 21.5, 21.1, 21.1, 26.3, 21.0, 19.4, 20.3, 23.0, 23.2, 22.7, 24.6, 21.3, 24.4, 20.8, 21.4, 23.4, 23.1, 22.9, 21.6, 24.5, 26.3, 27.1, 17.8, 21.8, 21.6, 21.8, 22.7, 17.1, 16.7, 21.2, 20.2, 21.3, 22.9, 22.3, 22.2, 18.8, 19.1, 18.2, 18.1, 20.6, 21.2, 22.9, 24.5, 26.5, 23.2, 14.5, 19.7, 20.4, 22.1, 24.2, 27.9, 26.2, 24.9, 25.6, 21.9, 23.2, 22.9, 24.0, 23.5, 26.3, 22.4, 22.6, 26.0, 20.9, 23.4, 19.7, 22.0, 22.8, 22.5, 23.0, 25.0, 23.2, 24.6, 25.4, 25.3, 26.2, 24.1, 25.3, 20.5, 22.9, 23.7, 24.6, 21.9, 24.3, 25.4, 26.1, 26.1, 25.4, 26.0, 23.7, 23.0, 23.6, 25.1, 25.2, 24.9, 24.6, 24.9, 24.5, 26.2, 24.8, 24.0, 23.8, 24.6, 25.8, 22.9, 20.2, 20.7, 19.6, 23.4, 18.4, 18.6, 15.6, 17.1, 18.3, 19.4, 20.4, 20.0, 22.2, 20.6, 21.2, 20.5, 19.9, 20.2, 19.9, 21.2, 19.5, 23.5, 25.0, 20.1, 18.8, 19.3, 19.3, 19.6, 18.3, 19.7, 18.6, 21.3, 19.8, 20.1, 18.9, 19.5, 19.3, 20.2, 20.2, 16.8, 20.1, 16.3, 17.2, 17.8, 18.4, 18.8, 20.5, 19.4, 16.3, 16.0, 19.1, 16.2, 16.4, 15.4, 18.2, 20.1, 19.8, 15.3, 17.5, 17.3, 14.7, 17.8, 16.4, 18.3, 14.6, 14.5, 17.3, 15.5, 16.0, 21.5, 14.1, 12.9, 15.0, 14.0, 12.9, 11.0, 9.5, 11.0, 13.1, 12.3, 13.3, 17.0, 18.8, 14.9, 13.8, 13.8, 17.4, 15.3, 13.4, 9.4, 10.3, 11.6, 10.6, 12.9, 17.4, 15.4, 15.2, 16.2, 15.8, 15.0, 12.8, 15.8, 8.4, 7.4, 9.3, 9.6, 8.8, 10.1, 9.2, 7.6, 9.6, 12.9, 14.9, 12.7, 10.5, 11.9, 15.5, 16.6, 10.5, 8.6, 8.8, 9.3, 13.3, 11.5, 18.0, 16.7, 14.6, 19.3, 14.5, 8.7, 12.2, 14.0, 14.7, 11.1, 9.8, 10.4, 11.9, 13.3, 12.8, 13.6, 11.2, 10.8, 12.4, 11.0, 11.0, 17.6, 14.0, 9.7, 12.4, 14.2, 12.0, 12.8, 14.2, 14.2, 14.2, 13.2, 12.5, 11.4, 11.9, 13.4, 11.4, 10.4, 11.3, 12.2, 12.9, 13.8, 18.8, 16.9, 15.7, 17.6, 15.5, 14.1, 15.0, 16.0, 18.7, 19.5, 17.9, 16.8, 16.6, 17.5, 17.4, 17.4, 16.9, 17.5, 14.9, 17.7, 15.1, 16.0, 18.4, 17.3, 18.4, 15.5, 16.5, 18.6, 16.2, 14.8, 16.1, 19.5, 18.4, 21.5, 17.5, 14.7, 19.9, 22.5, 21.0, 17.5, 25.3, 14.9, 14.3, 15.9, 15.1, 15.9, 23.1, 22.4, 18.3, 19.1, 19.0, 21.5, 17.0, 13.1, 15.0, 17.6, 18.7, 20.8, 15.4, 18.3, 23.0, 18.3, 16.8, 19.1, 19.7, 21.0, 25.7, 19.6, 22.6, 26.8, 20.1, 20.0, 20.2, 22.1, 24.9, 20.5, 17.9, 19.9, 21.1, 23.0, 21.7, 22.3, 24.6, 26.6, 18.3, 20.6, 22.3, 20.5, 22.8, 22.4, 22.4, 21.2, 25.6, 22.6, 23.0, 26.1, 20.6, 20.7, 24.6, 20.2, 20.8, 23.6, 23.8, 27.5, 32.4, 17.7, 18.8, 25.4, 19.8, 20.8, 22.8, 22.8, 21.1, 23.0, 23.2, 23.9, 25.8, 25.7, 24.9, 28.1, 27.3, 27.7, 24.6, 22.1, 21.9, 24.0, 20.5, 20.0, 24.8, 25.1, 27.0, 24.8, 29.2, 24.7, 24.6, 28.7, 25.6, 26.2, 25.3, 36.5, 21.5, 24.1, 22.2, 23.8, 25.5, 32.6, 21.7, 22.6, 21.7, 26.4, 24.5, 27.9, 33.2, 21.1, 23.1, 22.8, 26.0, 29.5, 29.6, 22.2, 24.6, 25.7, 27.4, 26.4, 28.1, 21.9, 22.3, 21.3, 23.4, 26.6, 22.9, 19.7, 19.9, 19.4, 25.8, 25.4, 24.5, 18.7, 20.7, 23.3, 25.1, 21.4, 23.0, 21.7, 21.5, 20.4, 20.5, 19.3, 19.9, 20.3, 19.3, 20.1, 22.3, 23.7, 23.9, 22.9, 23.1, 20.3, 21.8, 23.7, 25.8, 24.5, 23.9, 21.5, 20.4, 20.2, 21.3, 21.8, 21.8, 22.5, 25.2, 16.9, 17.1, 19.8, 15.7, 17.9, 18.1, 17.1, 18.7, 18.4, 20.1, 13.9, 17.9, 17.4, 17.3, 17.2, 16.5, 18.2, 17.4, 19.2, 17.7, 19.0, 17.9, 19.9, 18.5, 18.2, 20.6, 13.1, 13.5, 14.0, 17.2, 15.9, 17.2, 16.9, 14.7, 15.1, 14.8, 17.2, 12.2, 13.3, 13.3, 13.4, 14.1, 15.8, 16.3, 14.6, 14.4, 12.7, 14.8, 19.5, 17.5, 15.7, 14.7, 16.6, 16.7, 14.0, 14.0, 14.2, 13.3, 13.5, 9.7, 13.4, 10.3, 10.7, 13.4, 12.2, 11.5, 11.2, 13.3, 13.3, 12.5, 15.8, 13.1, 11.6, 11.2, 13.3, 11.9, 13.3, 14.6, 12.9, 12.7, 11.9, 10.5, 11.0, 10.2, 12.4, 9.4], 'Temp3pm': [20.9, 24.8, 23.0, 20.9, 25.5, 26.0, 22.3, 21.1, 16.5, 23.3, 23.7, 24.7, 21.0, 23.3, 23.8, 23.3, 23.4, 23.8, 23.4, 25.2, 24.9, 24.9, 24.0, 26.1, 23.5, 25.8, 24.7, 19.2, 19.9, 21.2, 22.4, 22.5, 23.8, 24.1, 24.7, 23.3, 21.5, 23.8, 25.5, 26.0, 25.0, 25.3, 25.7, 25.6, 24.7, 25.4, 25.6, 24.9, 27.6, 18.4, 21.7, 24.8, 23.3, 27.0, 27.1, 21.8, 21.2, 21.7, 25.9, 24.9, 23.3, 28.0, 21.2, 21.0, 21.0, 22.1, 19.8, 18.9, 21.1, 21.9, 22.1, 22.2, 19.7, 18.8, 19.0, 16.2, 19.4, 19.6, 19.5, 18.4, 19.0, 20.1, 17.2, 19.3, 24.6, 25.7, 15.6, 17.8, 18.1, 18.1, 21.7, 18.6, 19.4, 22.2, 21.1, 22.0, 20.8, 20.6, 19.3, 18.7, 19.2, 18.1, 20.0, 21.3, 20.9, 20.9, 17.0, 20.3, 21.3, 17.3, 17.4, 17.1, 19.3, 16.9, 19.5, 19.1, 18.6, 17.6, 19.6, 19.4, 18.7, 17.1, 16.7, 17.2, 16.6, 16.6, 17.9, 17.2, 16.2, 19.1, 19.6, 20.1, 16.7, 14.1, 14.5, 15.8, 17.3, 19.2, 18.6, 17.2, 18.0, 16.3, 17.0, 18.8, 19.4, 19.3, 18.9, 18.1, 20.8, 21.6, 19.2, 18.8, 17.4, 12.9, 16.8, 17.7, 19.3, 16.4, 13.2, 15.8, 16.1, 15.0, 17.1, 22.9, 17.4, 17.4, 17.3, 17.9, 18.2, 16.8, 16.7, 13.9, 14.1, 14.7, 12.6, 15.5, 16.4, 10.2, 13.5, 16.2, 18.5, 16.8, 16.6, 18.7, 15.0, 16.3, 14.3, 11.4, 18.4, 16.4, 13.5, 15.4, 15.8, 16.0, 18.0, 18.1, 16.6, 15.5, 15.3, 17.5, 19.2, 18.2, 10.5, 13.4, 16.6, 16.0, 18.7, 15.8, 16.1, 15.7, 19.1, 19.0, 18.9, 16.0, 15.8, 14.2, 12.3, 18.3, 16.4, 15.4, 16.6, 16.8, 21.9, 25.0, 19.3, 27.8, 19.5, 15.0, 18.3, 24.0, 31.6, 20.7, 27.6, 16.9, 17.5, 18.2, 21.6, 21.4, 21.5, 16.1, 19.0, 20.5, 29.7, 33.9, 19.0, 16.0, 20.2, 17.2, 18.4, 19.2, 20.5, 20.0, 20.8, 27.7, 17.6, 18.1, 20.3, 22.4, 19.7, 26.6, 21.8, 18.8, 12.4, 14.1, 18.2, 22.2, 23.6, 29.8, 20.5, 16.7, 23.5, 34.6, 20.4, 20.0, 28.6, 17.8, 20.1, 25.0, 21.3, 22.8, 21.5, 22.2, 22.3, 24.0, 24.2, 26.1, 21.5, 19.4, 20.0, 21.6, 20.9, 26.7, 23.7, 17.2, 18.4, 20.7, 19.3, 19.2, 22.7, 22.2, 19.8, 21.4, 30.8, 23.4, 32.3, 21.5, 24.1, 28.8, 21.7, 21.9, 24.9, 21.7, 19.7, 18.4, 32.5, 23.9, 22.8, 23.4, 23.1, 24.0, 21.2, 18.2, 21.4, 22.9, 26.0, 19.7, 22.8, 25.4, 26.2, 26.5, 22.4, 23.8, 25.3, 34.3, 20.8, 21.4, 24.1, 26.2, 25.8, 26.1, 20.1, 21.2, 22.5, 23.9, 25.6, 25.4, 29.1, 33.1, 24.0, 21.6, 22.9, 23.8, 27.0, 29.2, 32.7, 29.1, 40.1, 24.7, 25.3, 22.4, 26.6, 27.5, 27.5, 29.0, 26.9, 27.1, 27.9, 26.2, 28.9, 27.4, 32.2, 28.1, 20.6, 18.7, 23.0, 21.4, 17.9, 20.4, 23.1, 22.6, 22.0, 25.7, 27.5, 25.1, 23.6, 24.4, 26.5, 28.2, 26.1, 23.6, 23.2, 24.1, 24.8, 25.1, 25.6, 22.9, 24.2, 22.5, 25.8, 22.0, 23.6, 24.3, 22.3, 24.7, 23.9, 26.8, 25.0, 26.7, 23.9, 24.3, 24.9, 25.3, 24.9, 25.0, 25.6, 25.9, 25.2, 25.7, 22.5, 23.0, 23.0, 24.7, 19.9, 23.9, 23.8, 24.4, 20.1, 21.5, 19.4, 20.1, 21.3, 21.8, 22.4, 23.0, 20.9, 23.1, 29.0, 22.6, 22.5, 20.9, 21.7, 19.7, 20.1, 20.1, 20.0, 22.6, 22.2, 19.5, 17.9, 20.5, 16.6, 14.1, 20.7, 20.8, 20.4, 21.6, 20.5, 20.7, 21.6, 19.6, 21.0, 19.6, 17.4, 18.5, 20.9, 20.5, 21.4, 21.7, 19.6, 19.7, 20.0, 20.4, 18.7, 17.5, 18.1, 20.7, 19.4, 21.6, 16.3, 17.1, 16.6, 15.9, 16.8, 16.1, 18.5, 17.6, 16.8, 18.4, 18.7, 18.7, 18.6, 15.0, 13.6, 15.4, 17.1, 16.8, 14.4, 18.4, 13.6, 14.2, 14.2, 17.8, 15.5, 17.8, 20.6, 18.8, 18.6, 15.8, 16.6, 15.1, 17.5, 20.4, 19.1, 20.5, 17.8, 14.5, 16.7, 17.2, 14.8, 14.7, 15.4, 16.2, 16.8, 15.8, 16.7, 16.8, 16.8, 17.0, 14.5, 15.1, 18.4, 19.5, 21.2, 21.3, 24.0, 16.4, 16.1, 15.5, 14.1, 18.8, 17.9, 18.7, 18.7, 18.4, 18.8, 17.3, 19.9, 18.2, 17.5, 17.6, 23.2, 15.9, 16.0, 15.7, 16.3, 19.6, 20.5, 17.9, 22.1, 25.2, 22.7, 17.0, 17.5, 19.0, 25.0, 17.9, 22.3, 18.9, 19.5, 21.3, 20.4, 22.0, 20.4, 18.8, 21.4, 19.2, 17.7, 16.3, 25.0, 19.8, 17.7, 19.1, 17.0, 20.4, 19.8, 18.4, 25.5, 31.9, 18.4, 19.7, 19.5, 31.2, 21.2, 19.4, 23.7, 19.3, 30.9, 20.9, 24.0, 22.4, 18.4, 16.9, 19.7, 18.8, 22.0, 32.8, 19.4, 14.5, 16.6, 18.4, 18.0, 18.5, 16.9, 13.9, 17.6, 19.2, 21.1, 24.0, 17.8, 22.0, 20.5, 20.3, 18.5, 20.4, 22.0, 29.7, 20.0, 21.6, 20.9, 16.5, 16.6, 18.4, 22.8, 22.1, 23.4, 24.5, 36.3, 19.1, 19.1, 20.8, 22.5, 19.9, 22.8, 23.2, 23.1, 26.0, 22.5, 23.4, 23.8, 26.6, 21.0, 23.2, 26.0, 29.0, 30.2, 39.8, 20.4, 20.6, 24.0, 24.8, 28.7, 28.2, 29.3, 19.6, 19.4, 21.5, 22.0, 22.5, 22.0, 23.8, 27.3, 24.1, 22.0, 24.8, 25.1, 24.8, 25.9, 21.1, 23.6, 26.0, 29.8, 18.5, 27.4, 21.8, 23.3, 27.1, 18.6, 22.3, 22.7, 25.9, 24.5, 23.3, 29.0, 24.9, 20.8, 23.2, 25.7, 24.8, 23.4, 25.5, 30.6, 28.9, 25.8, 28.4, 25.4, 21.0, 24.4, 24.5, 25.6, 25.1, 22.9, 26.6, 27.4, 29.2, 39.9, 22.6, 25.7, 27.7, 25.0, 24.6, 29.6, 26.4, 26.0, 26.6, 25.9, 27.2, 26.1, 24.9, 22.2, 23.8, 26.3, 27.3, 27.3, 27.4, 37.4, 25.2, 23.9, 28.5, 25.0, 25.4, 24.9, 25.0, 26.1, 28.6, 32.5, 23.7, 23.8, 24.2, 24.6, 26.5, 25.8, 19.2, 21.8, 23.5, 24.7, 23.5, 25.1, 25.6, 27.4, 29.6, 20.4, 23.6, 22.5, 22.8, 23.0, 24.5, 25.1, 24.4, 25.3, 26.9, 26.5, 28.0, 24.1, 26.1, 25.3, 24.8, 29.5, 25.5, 26.2, 26.7, 21.2, 22.0, 24.8, 24.3, 22.1, 20.7, 20.5, 22.4, 24.5, 24.3, 22.4, 27.6, 27.7, 24.2, 21.3, 23.0, 23.3, 21.8, 24.2, 24.2, 24.4, 23.9, 23.9, 26.5, 26.4, 19.2, 21.5, 20.1, 24.5, 24.5, 19.2, 20.6, 26.3, 22.7, 24.2, 18.1, 21.5, 22.9, 22.6, 22.4, 22.0, 25.7, 18.5, 20.7, 20.3, 20.5, 19.7, 16.5, 14.9, 20.0, 19.3, 18.4, 18.4, 14.3, 17.8, 16.8, 15.6, 18.3, 19.8, 16.2, 18.7, 19.1, 18.5, 19.0, 17.1, 16.4, 17.4, 15.2, 14.3, 16.3, 15.7, 16.8, 16.9, 15.8, 17.1, 17.8, 17.6, 18.3, 16.6, 20.0, 15.7, 14.6, 17.0, 18.4, 19.7, 13.9, 15.3, 14.4, 15.7, 16.9, 11.9, 15.6, 16.9, 13.1, 15.1, 15.3, 13.9, 16.6, 17.3, 16.0, 17.7, 17.4, 17.4, 16.2, 18.4, 18.7, 15.0, 14.9, 15.5, 13.6, 16.4, 17.6, 15.5, 15.5, 16.6, 14.4, 15.8, 21.0, 20.5, 20.6, 15.1, 15.5, 18.7, 15.8, 15.7, 15.5, 15.2, 17.0, 16.2, 17.4, 15.0, 17.0, 21.4, 20.0, 18.3, 15.9, 17.7, 24.4, 19.2, 16.7, 15.7, 13.9, 19.6, 17.2, 16.4, 18.8, 16.5, 16.8, 18.4, 24.1, 17.8, 16.5, 19.0, 20.4, 18.9, 16.1, 17.2, 18.0, 21.2, 17.5, 17.6, 23.3, 15.7, 20.8, 17.2, 19.5, 17.3, 18.5, 20.4, 18.1, 17.3, 20.2, 24.8, 19.7, 16.5, 18.9, 19.9, 26.6, 21.8, 15.2, 23.3, 19.8, 21.3, 22.2, 19.3, 15.7, 22.5, 20.6, 20.2, 20.5, 23.8, 24.2, 18.6, 17.8, 20.7, 17.6, 17.8, 16.7, 20.7, 23.8, 23.2, 23.5, 25.0, 27.2, 19.4, 22.8, 21.0, 22.6, 18.5, 23.2, 24.1, 25.2, 22.4, 25.5, 23.0, 20.8, 20.2, 19.9, 22.7, 23.2, 22.0, 25.5, 25.4, 25.7, 28.3, 24.0, 23.4, 26.1, 25.5, 24.7, 20.6, 23.0, 25.4, 26.4, 21.3, 27.1, 25.2, 26.2, 23.6, 25.5, 28.7, 18.9, 20.7, 24.1, 24.8, 26.4, 27.1, 26.6, 19.2, 21.8, 23.0, 24.9, 26.5, 26.4, 26.6, 26.0, 24.3, 26.4, 24.9, 27.6, 29.6, 28.0, 26.3, 24.8, 24.5, 26.3, 26.3, 26.7, 26.1, 32.4, 27.2, 27.7, 27.3, 24.1, 24.6, 27.5, 30.0, 31.8, 28.4, 33.6, 27.8, 40.9, 22.8, 22.6, 24.2, 21.6, 24.3, 28.3, 22.2, 21.3, 23.6, 24.0, 25.7, 26.8, 27.0, 28.4, 32.0, 24.4, 19.2, 26.1, 24.9, 27.1, 26.8, 26.9, 26.1, 32.5, 21.2, 29.5, 25.4, 22.2, 22.2, 23.8, 25.2, 30.6, 25.2, 25.3, 26.1, 27.2, 22.3, 24.5, 25.3, 25.8, 24.8, 22.9, 22.2, 24.0, 26.2, 29.6, 26.3, 24.8, 18.6, 18.4, 23.5, 24.3, 26.0, 20.9, 21.6, 18.1, 18.5, 20.7, 18.8, 18.4, 19.6, 21.6, 16.9, 17.6, 14.8, 16.2, 19.8, 16.2, 19.0, 17.5, 18.9, 19.4, 19.3, 19.8, 20.9, 20.6, 22.4, 15.5, 13.9, 19.3, 16.2, 16.8, 16.7, 14.0, 19.6, 18.7, 18.2, 18.5, 18.3, 16.5, 15.0, 14.0, 13.1, 15.2, 14.2, 13.8, 15.3, 16.3, 15.4, 17.4, 16.3, 15.5, 17.0, 17.7, 18.6, 18.5, 15.7, 19.5, 17.6, 18.2, 20.5, 19.1, 16.3, 14.6, 16.2, 16.2, 18.9, 19.8, 18.6, 16.5, 17.0, 16.0, 16.6, 16.4, 15.9, 17.3, 18.5, 11.9, 14.6, 12.7, 14.8, 14.5, 18.5, 10.3, 15.0, 11.4, 11.5, 14.5, 13.8, 16.7, 18.0, 16.3, 19.6, 19.0, 18.8, 21.1, 19.3, 21.7, 23.0, 23.0, 24.7, 21.7, 16.7, 15.9, 16.1, 16.5, 16.9, 14.2, 17.2, 15.7, 17.2, 17.5, 15.2, 17.9, 16.2, 18.7, 17.6, 17.5, 16.6, 18.4, 19.0, 19.1, 18.1, 18.7, 23.3, 16.6, 18.4, 19.3, 16.5, 18.6, 19.4, 20.1, 26.6, 17.1, 17.1, 14.1, 15.3, 17.9, 17.1, 19.1, 26.0, 18.1, 20.1, 19.9, 21.9, 20.9, 23.0, 19.3, 20.4, 30.4, 16.3, 13.2, 19.3, 18.5, 15.8, 16.9, 20.2, 18.3, 15.2, 17.5, 19.4, 17.8, 17.9, 20.0, 19.0, 21.3, 18.2, 19.6, 17.5, 19.7, 17.8, 21.7, 21.9, 19.6, 19.2, 20.9, 23.0, 26.3, 23.1, 22.4, 33.8, 16.9, 17.2, 19.3, 21.2, 24.1, 21.6, 20.2, 19.8, 22.7, 18.0, 20.4, 21.5, 25.8, 25.6, 27.0, 27.6, 28.2, 22.5, 23.4, 23.3, 20.7, 17.9, 22.9, 26.6, 26.1, 21.2, 21.8, 17.2, 17.3, 18.6, 24.3, 27.2, 24.4, 24.6, 30.6, 20.9, 20.7, 21.2, 16.3, 16.4, 17.4, 19.1, 21.8, 22.9, 22.4, 20.5, 18.8, 23.2, 19.7, 21.4, 20.8, 21.3, 22.2, 21.7, 22.8, 23.5, 19.7, 24.2, 25.1, 25.0, 24.4, 21.3, 23.9, 23.8, 23.9, 22.8, 25.0, 25.4, 25.5, 27.8, 23.4, 21.5, 23.8, 25.6, 25.8, 29.4, 26.9, 21.2, 24.1, 22.4, 21.9, 23.2, 25.0, 26.1, 25.2, 22.6, 25.7, 23.5, 21.7, 22.7, 26.4, 24.1, 23.7, 26.1, 31.2, 24.4, 21.2, 18.5, 20.7, 25.6, 25.3, 23.8, 23.2, 23.2, 24.6, 24.3, 18.1, 25.0, 23.8, 23.3, 25.0, 26.0, 24.0, 26.8, 25.6, 27.2, 24.9, 25.8, 25.6, 26.9, 25.5, 25.6, 27.5, 31.9, 21.1, 29.2, 19.4, 19.9, 26.4, 25.9, 23.9, 21.3, 20.1, 27.0, 24.7, 23.0, 23.2, 24.1, 23.0, 25.4, 25.5, 19.4, 21.6, 23.2, 24.0, 23.8, 19.1, 26.1, 24.2, 20.8, 22.7, 23.1, 20.4, 23.9, 24.3, 24.6, 23.7, 24.0, 25.6, 24.5, 24.4, 24.1, 23.3, 23.4, 24.6, 18.0, 19.9, 22.2, 22.4, 22.0, 22.5, 23.5, 19.1, 20.5, 21.5, 24.0, 23.4, 19.1, 19.8, 19.4, 19.8, 21.5, 23.0, 18.7, 19.9, 21.4, 22.1, 21.3, 20.9, 20.3, 21.0, 17.9, 22.8, 26.7, 26.3, 24.7, 19.2, 16.8, 17.2, 19.1, 19.9, 20.1, 22.2, 20.4, 15.0, 20.6, 20.5, 21.7, 13.7, 18.4, 15.9, 17.9, 17.7, 16.6, 17.3, 17.4, 18.2, 15.8, 15.2, 18.7, 12.4, 13.7, 17.4, 16.6, 17.6, 13.6, 13.0, 17.4, 14.8, 17.5, 20.4, 13.8, 18.3, 19.0, 19.0, 17.2, 18.4, 14.8, 16.2, 18.1, 12.9, 15.8, 16.8, 17.9, 18.0, 15.8, 16.1, 15.8, 15.9, 13.6, 15.3, 13.9, 16.6, 16.7, 17.6, 20.1, 17.1, 21.3, 19.1, 17.8, 18.3, 20.4, 20.2, 14.6, 16.6, 14.8, 16.2, 13.6, 18.0, 17.8, 17.0, 16.7, 16.1, 15.3, 13.7, 15.7, 15.8, 18.1, 20.3, 19.8, 18.4, 18.2, 21.4, 18.9, 12.2, 20.1, 17.4, 14.5, 17.9, 16.9, 16.0, 19.0, 20.8, 26.3, 18.9, 20.0, 17.2, 21.2, 16.6, 16.2, 17.0, 19.6, 21.4, 27.5, 27.6, 18.4, 20.4, 21.0, 19.6, 15.0, 16.9, 19.8, 18.5, 19.4, 18.2, 20.1, 19.7, 21.9, 20.9, 23.5, 21.7, 16.8, 19.6, 21.0, 31.2, 20.3, 18.0, 18.5, 24.0, 31.9, 22.8, 17.2, 19.3, 17.5, 17.1, 18.2, 12.2, 18.9, 18.5, 23.2, 30.7, 20.8, 20.4, 24.1, 24.6, 26.9, 18.0, 18.3, 21.0, 24.8, 20.0, 19.1, 19.1, 20.8, 22.4, 24.4, 24.7, 20.3, 17.8, 21.9, 24.3, 23.9, 22.4, 23.4, 20.9, 18.5, 20.8, 22.0, 21.0, 18.4, 23.6, 17.5, 19.8, 22.2, 19.9, 21.8, 22.3, 19.4, 20.5, 23.8, 27.2, 24.1, 22.4, 21.9, 26.2, 28.0, 24.1, 21.1, 23.5, 24.8, 27.2, 27.0, 25.9, 39.8, 21.7, 24.3, 27.3, 28.1, 22.2, 22.2, 23.1, 24.9, 26.5, 44.7, 22.4, 23.6, 25.5, 26.5, 24.4, 29.3, 27.6, 27.0, 20.9, 21.6, 24.0, 24.9, 27.2, 18.7, 20.1, 24.8, 25.1, 25.8, 25.6, 26.3, 26.2, 26.0, 25.5, 25.4, 25.7, 26.3, 24.0, 22.5, 25.8, 23.2, 22.3, 23.0, 24.5, 25.0, 31.5, 24.0, 26.4, 29.5, 25.5, 26.7, 30.9, 20.9, 22.6, 24.4, 23.5, 25.4, 18.0, 17.7, 22.9, 18.8, 22.2, 22.5, 20.7, 23.0, 24.7, 24.2, 23.7, 25.2, 26.2, 21.4, 21.9, 21.4, 20.0, 17.5, 20.0, 24.2, 23.4, 23.4, 20.3, 25.9, 22.6, 28.1, 22.6, 20.5, 24.2, 18.7, 20.9, 20.2, 19.7, 19.2, 19.9, 21.2, 22.0, 22.9, 20.8, 21.4, 21.9, 20.0, 20.1, 19.4, 18.6, 19.1, 19.0, 19.6, 21.8, 14.5, 16.4, 20.1, 20.8, 20.2, 19.4, 17.8, 20.6, 20.0, 24.1, 19.9, 14.0, 19.1, 20.7, 18.3, 19.2, 21.6, 17.5, 18.4, 18.5, 18.4, 15.8, 20.1, 18.5, 17.3, 16.6, 15.7, 16.1, 14.3, 15.6, 16.1, 11.9, 11.9, 13.1, 13.8, 19.2, 17.6, 16.0, 13.2, 16.6, 18.5, 18.9, 19.2, 22.6, 18.5, 17.1, 17.7, 17.7, 11.8, 14.8, 17.0, 19.2, 17.3, 17.5, 19.4, 19.6, 23.0, 19.4, 17.5, 19.8, 16.0, 16.6, 15.9, 16.6, 17.9, 19.5, 17.8, 18.1, 23.3, 19.7, 17.0, 17.5, 19.7, 19.2, 18.0, 20.4, 22.1, 16.0, 12.6, 17.1, 23.5, 19.2, 18.9, 22.2, 23.9, 17.7, 19.1, 22.6, 22.8, 19.8, 15.4, 17.5, 17.7, 17.4, 21.8, 19.6, 21.6, 19.9, 22.1, 20.0, 23.5, 23.6, 20.6, 21.4, 21.2, 20.7, 28.5, 21.2, 29.9, 18.7, 22.5, 30.6, 24.5, 22.4, 16.9, 20.2, 17.9, 16.5, 23.2, 24.7, 22.9, 18.9, 20.1, 21.6, 22.8, 26.9, 27.3, 26.3, 19.9, 27.9, 20.8, 26.2, 26.4, 26.0, 17.2, 19.3, 23.4, 28.9, 20.3, 19.8, 25.7, 37.1, 20.5, 23.3, 34.2, 19.3, 21.5, 25.1, 31.5, 19.7, 21.3, 23.4, 26.7, 24.2, 32.9, 23.7, 20.7, 21.6, 20.5, 22.2, 18.9, 21.7, 21.1, 21.0, 23.5, 32.8, 19.0, 19.1, 20.7, 24.7, 27.6, 28.4, 18.7, 17.3, 21.9, 23.2, 23.7, 22.6, 18.8, 16.8, 18.4, 24.5, 24.2, 23.5, 22.6, 22.6, 22.7, 20.0, 22.2, 22.5, 25.6, 17.1, 21.9, 21.8, 23.3, 23.4, 24.9, 22.3, 22.0, 23.9, 25.3, 29.2, 30.4, 24.9, 24.0, 25.1, 23.6, 23.8, 23.9, 24.7, 24.5, 25.1, 31.4, 26.5, 26.8, 31.5, 22.1, 20.1, 25.2, 24.3, 24.9, 23.5, 23.4, 25.9, 24.9, 34.5, 24.8, 24.6, 24.9, 28.9, 19.5, 20.5, 22.4, 23.8, 27.4, 26.1, 24.7, 26.2, 28.2, 27.3, 27.2, 28.3, 26.4, 25.1, 23.9, 22.3, 23.5, 26.0, 23.3, 21.1, 24.7, 25.5, 29.0, 27.6, 27.2, 26.6, 26.4, 25.9, 19.5, 22.7, 23.2, 25.0, 25.9, 27.1, 25.5, 25.9, 25.8, 25.6, 22.8, 23.1, 21.5, 23.7, 23.9, 23.5, 25.6, 24.4, 23.1, 24.2, 24.9, 26.1, 30.3, 21.2, 21.0, 22.0, 19.8, 22.2, 24.7, 26.6, 25.8, 25.7, 24.7, 25.7, 26.4, 26.3, 27.6, 26.0, 25.2, 25.8, 22.5, 27.5, 28.7, 27.8, 26.4, 25.2, 25.7, 25.7, 17.5, 24.7, 24.4, 20.3, 24.3, 24.4, 27.0, 23.5, 24.6, 24.7, 25.1, 21.5, 23.8, 19.5, 21.1, 22.9, 23.2, 20.0, 25.7, 20.0, 18.5, 19.4, 20.8, 21.9, 23.1, 26.1, 20.8, 21.9, 24.4, 24.4, 24.0, 28.9, 20.7, 22.6, 17.0, 20.4, 23.6, 24.3, 19.6, 21.5, 14.8, 19.3, 20.2, 21.6, 19.3, 18.2, 18.8, 21.4, 19.9, 22.7, 21.0, 21.4, 21.5, 23.3, 22.4, 24.4, 25.8, 25.2, 22.6, 26.8, 23.8, 22.6, 24.9, 23.3, 23.8, 23.2, 19.7, 20.7, 20.0, 17.8, 19.9, 19.5, 22.0, 18.0, 14.9, 17.8, 16.0, 16.9, 18.8, 17.7, 19.5, 20.4, 19.2, 16.9, 19.4, 17.8, 18.7, 19.8, 19.6, 21.4, 19.6, 15.8, 16.1, 17.7, 21.1, 20.4, 20.3, 15.5, 16.0, 18.3, 19.2, 17.2, 19.6, 17.3, 16.2, 18.8, 16.2, 20.7, 16.8, 18.2, 17.7, 15.1, 15.7, 15.3, 17.9, 19.1, 14.1, 13.6, 15.2, 15.7, 16.5, 17.1, 19.7, 18.3, 17.2, 18.7, 17.4, 22.9, 23.3, 24.5, 16.7, 15.0, 16.5, 16.0, 17.5, 20.1, 18.8, 16.9, 18.6, 22.7, 13.7, 12.3, 16.2, 18.1, 17.8, 16.4, 17.0, 13.3, 14.5, 15.7, 17.1, 18.5, 14.8, 18.4, 18.8, 14.9, 18.7, 17.8, 15.8, 14.9, 20.5, 20.7, 13.7, 16.2, 14.7, 16.7, 15.7, 17.7, 18.2, 20.6, 23.2, 23.7, 16.9, 16.8, 20.5, 19.2, 18.4, 18.2, 19.4, 18.3, 18.9, 19.6, 20.8, 20.2, 20.1, 20.2, 21.2, 32.3, 32.7, 19.6, 21.3, 19.1, 21.5, 30.8, 21.8, 25.2, 18.8, 21.0, 21.9, 23.6, 23.3, 21.5, 17.1, 15.1, 20.1, 19.9, 19.6, 23.1, 17.0, 18.5, 20.4, 25.1, 23.1, 25.9, 25.8, 29.6, 28.0, 21.8, 28.4, 21.8, 19.5, 21.0, 21.0, 20.9, 21.8, 21.9, 25.2, 22.2, 19.0, 21.6, 22.1, 31.7, 22.6, 28.1, 22.9, 25.2, 22.7, 26.0, 30.3, 23.4, 28.9, 23.6, 21.6, 21.9, 24.6, 23.6, 27.8, 28.4, 25.3, 26.3, 25.5, 23.6, 29.2, 23.0, 24.7, 18.6, 21.2, 23.2, 24.6, 24.3, 22.3, 24.4, 23.2, 22.2, 24.1, 25.1, 23.8, 22.7, 25.6, 22.7, 20.7, 23.5, 25.4, 26.9, 23.9, 27.5, 26.3, 27.7, 27.1, 25.9, 26.8, 27.9, 27.4, 26.9, 25.2, 21.1, 22.9, 24.5, 33.4, 24.8, 26.6, 33.5, 28.6, 21.7, 23.9, 27.1, 27.5, 28.7, 28.3, 31.2, 19.7, 20.2, 18.2, 22.1, 26.8, 24.2, 24.2, 23.4, 25.7, 22.9, 22.5, 23.6, 26.0, 28.3, 25.3, 27.7, 27.1, 27.6, 25.1, 26.9, 26.4, 26.8, 26.1, 26.7, 25.8, 25.6, 24.5, 26.8, 26.9, 24.8, 22.9, 24.9, 26.4, 26.5, 29.3, 23.7, 25.8, 26.9, 23.1, 29.6, 24.6, 25.6, 27.7, 24.0, 27.0, 27.3, 21.4, 23.7, 23.0, 23.4, 22.5, 27.2, 27.2, 24.9, 21.7, 24.1, 26.4, 22.5, 24.2, 27.8, 26.4, 22.2, 23.2, 23.1, 22.7, 23.6, 27.1, 18.5, 17.4, 25.6, 20.2, 21.2, 21.0, 21.2, 21.7, 20.4, 21.4, 22.2, 20.8, 23.2, 29.2, 21.0, 26.1, 20.0, 17.1, 14.6, 17.2, 23.1, 23.9, 22.5, 16.2, 20.7, 20.1, 17.5, 20.4, 19.8, 19.0, 20.8, 21.6, 27.0, 20.4, 19.8, 20.5, 20.7, 20.8, 21.1, 21.9, 16.4, 18.4, 17.8, 19.6, 18.4, 18.2, 20.9, 21.6, 19.2, 16.9, 17.9, 18.9, 18.2, 17.9, 20.5, 20.3, 18.7, 17.0, 14.5, 14.8, 15.6, 15.6, 17.5, 16.8, 20.6, 21.3, 22.5, 21.9, 14.2, 15.9, 19.2, 19.0, 18.6, 16.4, 15.8, 16.4, 15.8, 12.5, 14.1, 13.7, 17.5, 18.7, 20.0, 17.6, 18.7, 19.0, 18.5, 17.8, 17.9, 17.4, 16.1, 15.9, 15.5, 16.6, 17.1, 11.8, 13.7, 16.4, 16.0, 19.2, 13.1, 16.5, 17.6, 14.9, 12.9, 13.5, 11.8, 15.8, 15.9, 18.3, 16.5, 16.4, 18.6, 20.5, 19.5, 15.2, 16.6, 16.4, 19.2, 20.4, 20.7, 23.8, 19.0, 14.4, 13.0, 14.3, 16.1, 16.3, 16.3, 18.8, 20.4, 16.2, 19.3, 18.0, 17.0, 17.4, 20.4, 14.7, 16.4, 18.7, 19.8, 26.9, 17.9, 16.4, 18.7, 18.9, 20.1, 18.5, 20.1, 18.1, 18.4, 17.0, 18.6, 20.6, 18.3, 18.7, 16.0, 22.7, 19.7, 18.9, 18.9, 20.5, 21.3, 21.4, 21.4, 29.2, 19.3, 17.7, 18.9, 18.1, 17.4, 21.3, 17.8, 11.7, 13.6, 15.9, 18.4, 18.3, 19.1, 21.7, 18.7, 21.7, 21.1, 27.3, 32.6, 35.6, 30.6, 19.0, 19.9, 22.0, 22.3, 21.4, 23.4, 19.8, 22.7, 23.1, 27.3, 23.0, 22.1, 24.4, 26.0, 26.3, 20.1, 19.4, 20.7, 22.3, 22.2, 19.3, 20.6, 21.9, 21.8, 22.5, 25.4, 26.4, 19.2, 19.4, 20.5, 20.5, 21.8, 20.4, 21.8, 24.8, 22.1, 22.2, 23.3, 18.9, 18.5, 21.7, 23.7, 35.6, 28.6, 40.7, 20.7, 20.8, 25.4, 23.0, 36.0, 21.6, 22.5, 25.1, 23.8, 32.0, 19.4, 20.3, 22.8, 24.9, 24.1, 24.4, 27.5, 25.0, 34.7, 21.4, 23.2, 25.5, 25.0, 18.2, 24.6, 27.1, 27.5, 21.5, 17.7, 22.0, 23.9, 24.5, 23.4, 22.3, 21.6, 24.1, 23.7, 24.2, 24.2, 23.5, 19.9, 19.1, 19.5, 17.9, 21.0, 24.1, 24.5, 26.2, 31.1, 25.9, 26.7, 19.4, 22.8, 25.1, 25.1, 29.2, 32.1, 32.3, 25.7, 25.5, 24.1, 24.7, 26.4, 24.3, 27.2, 23.2, 28.1, 31.0, 25.5, 26.6, 27.7, 23.5, 23.9, 26.4, 25.7, 27.0, 27.3, 27.6, 26.7, 27.5, 27.7, 31.5, 27.4, 25.6, 25.5, 26.1, 28.6, 28.8, 26.6, 28.0, 28.2, 28.4, 32.2, 26.7, 25.2, 26.3, 27.5, 27.6, 28.1, 28.4, 26.9, 27.2, 26.3, 26.8, 27.0, 29.1, 28.5, 26.8, 27.6, 26.2, 29.9, 24.3, 25.4, 25.5, 26.4, 23.8, 18.1, 20.7, 21.5, 23.9, 25.8, 22.9, 24.5, 23.0, 26.0, 21.1, 26.8, 24.7, 24.9, 29.7, 23.3, 23.3, 25.6, 29.3, 19.9, 20.5, 24.0, 23.7, 24.1, 20.5, 22.5, 22.3, 24.2, 24.7, 20.5, 21.2, 22.2, 23.2, 24.1, 21.8, 16.5, 21.5, 21.7, 22.2, 23.0, 23.7, 23.3, 26.0, 25.4, 21.2, 25.8, 23.1, 21.3, 23.2, 21.6, 20.5, 21.8, 23.8, 21.3, 23.3, 25.6, 22.3, 22.4, 22.4, 27.7, 21.4, 23.0, 22.2, 20.8, 21.8, 23.8, 20.8, 20.8, 19.9, 17.9, 14.3, 18.7, 19.1, 15.8, 16.0, 18.6, 18.3, 18.8, 19.7, 17.9, 17.9, 20.2, 21.6, 20.8, 19.3, 17.6, 17.7, 20.9, 19.2, 21.2, 18.7, 20.7, 16.7, 17.9, 17.8, 19.3, 17.4, 14.4, 14.3, 13.7, 11.0, 16.9, 18.6, 17.8, 16.5, 14.4, 17.7, 15.9, 14.6, 15.5, 16.4, 16.7, 18.3, 18.7, 13.3, 16.4, 16.9, 17.1, 17.8, 23.9, 23.0, 16.2, 17.6, 25.1, 17.0, 13.6, 17.1, 17.7, 18.5, 19.0, 17.6, 17.9, 20.5, 17.0, 13.2, 12.6, 14.7, 14.7, 15.9, 17.9, 18.8, 24.6, 19.6, 17.3, 19.8, 17.6, 19.2, 19.6, 22.7, 20.7, 22.4, 15.7, 19.9, 12.2, 15.4, 13.7, 15.7, 16.4, 17.7, 18.0, 18.1, 19.6, 21.2, 20.7, 15.9, 20.1, 19.2, 19.0, 20.2, 21.0, 20.1, 21.2, 21.8, 17.6, 18.3, 18.9, 23.1, 20.9, 21.7, 19.2, 15.1, 20.6, 18.5, 16.8, 17.0, 21.5, 20.6, 16.3, 18.9, 20.6, 19.6, 22.3, 17.3, 20.2, 22.7, 22.9, 23.0, 22.9, 27.2, 30.8, 20.1, 20.3, 31.8, 20.1, 20.7, 15.6, 19.4, 23.0, 25.4, 14.5, 25.5, 22.9, 20.4, 23.3, 16.4, 17.5, 19.8, 22.8, 25.8, 19.9, 19.1, 22.0, 25.3, 21.7, 20.9, 21.6, 23.7, 27.1, 24.9, 23.2, 25.5, 24.7, 21.3, 23.4, 22.6, 26.4, 28.0, 20.3, 20.5, 22.0, 23.1, 30.0, 22.1, 23.2, 25.5, 26.2, 21.8, 23.4, 23.9, 21.6, 25.5, 24.1, 24.2, 25.4, 30.9, 23.8, 25.1, 27.1, 22.2, 24.4, 26.9, 26.4, 22.1, 24.3, 25.5, 31.1, 34.1, 17.7, 20.2, 32.4, 19.9, 21.4, 26.9, 25.0, 23.0, 23.8, 26.3, 26.8, 27.9, 27.5, 27.5, 31.8, 32.1, 26.4, 24.9, 24.8, 25.4, 23.7, 22.6, 25.3, 25.2, 27.5, 26.7, 30.5, 31.4, 26.8, 29.0, 29.2, 25.5, 26.3, 32.6, 30.1, 22.7, 28.3, 26.6, 26.0, 28.6, 35.0, 23.3, 24.9, 25.7, 28.1, 28.9, 30.3, 29.2, 22.4, 25.4, 26.1, 28.1, 34.1, 33.9, 21.0, 23.1, 29.7, 36.2, 33.1, 28.1, 26.9, 21.2, 26.1, 28.8, 26.8, 28.8, 25.0, 27.5, 26.3, 26.2, 27.3, 27.3, 19.0, 24.3, 25.6, 26.4, 25.0, 25.0, 22.2, 20.9, 22.1, 25.5, 21.7, 22.0, 23.3, 25.1, 25.5, 26.0, 27.0, 21.4, 24.8, 24.5, 20.5, 24.1, 25.3, 26.9, 26.0, 29.8, 22.2, 21.7, 24.2, 26.0, 26.0, 23.6, 27.0, 19.2, 21.6, 22.5, 20.1, 21.8, 20.7, 22.9, 23.2, 23.7, 23.1, 27.9, 15.7, 22.2, 20.2, 22.6, 23.5, 22.0, 26.2, 22.3, 23.0, 22.3, 23.0, 22.4, 22.5, 23.6, 22.7, 21.9, 18.5, 20.1, 21.2, 20.5, 24.2, 23.2, 16.3, 19.5, 20.5, 25.2, 21.1, 18.9, 19.8, 20.3, 19.7, 18.5, 20.1, 18.1, 20.2, 20.3, 19.6, 20.2, 20.2, 22.8, 21.9, 20.1, 22.4, 22.5, 19.7, 19.6, 19.4, 23.2, 17.5, 16.7, 15.9, 17.8, 16.4, 16.4, 19.0, 19.2, 14.7, 14.2, 16.9, 18.2, 17.5, 16.0, 19.1, 18.2, 17.4, 18.7, 17.2, 17.4, 17.6, 17.2, 19.7, 17.9, 18.7, 17.3, 19.0, 18.8], 'RainToday': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'], 'RainTomorrow': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No']}

df=pd.DataFrame(weather_dict)
df

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
3267,6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
3268,6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
3269,6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [4]:
weather_tuple={}
for i, rows in df.iterrows():
    key=tuple(rows)
    weather_tuple[i]=key
print(weather_tuple.values())

dict_values([('2/1/2008', 19.5, 22.4, 15.6, 6.2, 0.0, 'W', 41, 'S', 'SSW', 17, 20, 92, 84, 1017.6, 1017.4, 8, 8, 20.7, 20.9, 'Yes', 'Yes'), ('2/2/2008', 19.5, 25.6, 6.0, 3.4, 2.7, 'W', 41, 'W', 'E', 9, 13, 83, 73, 1017.9, 1016.4, 7, 7, 22.4, 24.8, 'Yes', 'Yes'), ('2/3/2008', 21.6, 24.5, 6.6, 2.4, 0.1, 'W', 41, 'ESE', 'ESE', 17, 2, 88, 86, 1016.7, 1015.6, 7, 8, 23.5, 23.0, 'Yes', 'Yes'), ('2/4/2008', 20.2, 22.8, 18.8, 2.2, 0.0, 'W', 41, 'NNE', 'E', 22, 20, 83, 90, 1014.2, 1011.8, 8, 8, 21.4, 20.9, 'Yes', 'Yes'), ('2/5/2008', 19.7, 25.7, 77.4, 4.8, 0.0, 'W', 41, 'NNE', 'W', 11, 6, 88, 74, 1008.3, 1004.8, 8, 8, 22.5, 25.5, 'Yes', 'Yes'), ('2/6/2008', 20.2, 27.2, 1.6, 2.6, 8.6, 'W', 41, 'W', 'ENE', 9, 22, 69, 62, 1002.7, 998.6, 6, 6, 23.8, 26.0, 'Yes', 'Yes'), ('2/7/2008', 18.6, 26.3, 6.2, 5.2, 5.2, 'W', 41, 'W', 'S', 15, 15, 75, 80, 999.0, 1000.3, 4, 7, 21.7, 22.3, 'Yes', 'Yes'), ('2/8/2008', 17.2, 22.3, 27.6, 5.8, 2.1, 'W', 41, 'S', 'SE', 7, 15, 77, 61, 1008.3, 1007.4, 7, 8, 18.9, 21.1, 'Yes', 'Yes'), ('2/9/2008', 16.4, 20.8, 12.6, 4.8, 3.0, 'W', 41, 'SSW', 'W', 19, 9, 92, 91, 1006.4, 1007.6, 7, 7, 17.1, 16.5, 'Yes', 'Yes'), ('2/10/2008', 14.6, 24.2, 8.8, 4.4, 10.1, 'W', 41, 'W', 'SSE', 11, 20, 80, 53, 1014.0, 1013.4, 4, 2, 17.2, 23.3, 'Yes', 'No'), ('2/11/2008', 16.4, 23.9, 0.0, 6.4, 8.0, 'W', 41, 'WNW', 'E', 9, 26, 78, 53, 1017.6, 1015.3, 7, 8, 18.9, 23.7, 'No', 'No'), ('2/12/2008', 18.9, 27.3, 0.0, 6.8, 6.7, 'W', 41, 'N', 'NE', 7, 24, 68, 67, 1010.7, 1007.5, 7, 7, 22.9, 24.7, 'No', 'Yes'), ('2/13/2008', 18.4, 22.8, 14.4, 7.0, 3.3, 'W', 41, 'S', 'S', 24, 30, 87, 70, 1009.2, 1011.7, 8, 7, 20.9, 21.0, 'Yes', 'Yes'), ('2/14/2008', 16.9, 24.3, 3.0, 3.2, 8.7, 'W', 41, 'SSW', 'SSE', 15, 19, 81, 51, 1017.2, 1016.5, 7, 1, 18.4, 23.3, 'Yes', 'No'), ('2/15/2008', 18.3, 24.4, 0.0, 6.2, 8.5, 'W', 41, 'SW', 'SSE', 19, 22, 80, 56, 1020.2, 1018.9, 7, 3, 19.5, 23.8, 'No', 'No'), ('2/16/2008', 16.7, 24.1, 0.0, 6.2, 8.8, 'W', 41, 'WNW', 'SSE', 11, 26, 77, 52, 1023.0, 1022.6, 7, 6, 19.8, 23.3, 'No', 'No'), ('2/17/2008', 19.5, 24.8, 0.0, 7.6, 3.2, 'W', 41, 'SE', 'ESE', 13, 24, 63, 62, 1024.7, 1023.1, 7, 7, 21.8, 23.4, 'No', 'No'), ('2/18/2008', 18.6, 25.3, 0.0, 4.2, 4.5, 'W', 41, 'SSE', 'ENE', 13, 24, 70, 59, 1021.7, 1019.4, 7, 6, 21.2, 23.8, 'No', 'No'), ('2/19/2008', 19.0, 24.8, 0.0, 5.2, 7.5, 'W', 41, 'WNW', 'E', 7, 17, 79, 65, 1018.0, 1015.4, 7, 7, 20.8, 23.4, 'No', 'No'), ('2/20/2008', 18.3, 26.4, 0.0, 4.6, 11.1, 'W', 41, 'W', 'E', 13, 22, 80, 60, 1013.4, 1010.8, 3, 1, 21.3, 25.2, 'No', 'No'), ('2/21/2008', 20.6, 26.8, 0.0, 6.8, 6.4, 'W', 41, 'WNW', 'SE', 4, 15, 86, 62, 1011.4, 1009.7, 7, 7, 22.1, 24.9, 'No', 'No'), ('2/22/2008', 19.1, 25.4, 0.4, 4.4, 9.4, 'W', 41, 'WNW', 'E', 11, 28, 77, 66, 1009.2, 1003.1, 4, 1, 22.3, 24.9, 'No', 'No'), ('2/23/2008', 20.5, 26.0, 0.0, 6.6, 12.2, 'W', 41, 'WSW', 'ESE', 20, 24, 38, 45, 1007.4, 1007.0, 1, 1, 22.5, 24.0, 'No', 'No'), ('2/24/2008', 16.5, 28.3, 0.0, 8.6, 12.0, 'W', 41, 'WNW', 'ESE', 11, 24, 48, 40, 1007.9, 1008.0, 0, 0, 21.2, 26.1, 'No', 'No'), ('2/25/2008', 20.5, 24.2, 0.0, 8.6, 1.5, 'W', 41, 'E', 'E', 15, 20, 58, 54, 1017.5, 1016.9, 7, 7, 21.6, 23.5, 'No', 'No'), ('2/26/2008', 19.3, 26.2, 0.0, 3.6, 8.4, 'W', 41, 'WSW', 'E', 2, 28, 73, 65, 1018.3, 1015.6, 1, 6, 23.0, 25.8, 'No', 'Yes'), ('2/27/2008', 19.0, 29.0, 22.2, 8.2, 3.3, 'W', 41, 'W', 'NNE', 0, 15, 82, 52, 1014.1, 1010.6, 7, 7, 21.3, 24.7, 'Yes', 'Yes'), ('2/28/2008', 17.9, 21.4, 4.2, 4.2, 0.0, 'W', 41, 'S', 'ESE', 20, 9, 77, 88, 1010.0, 1010.1, 8, 8, 20.4, 19.2, 'Yes', 'Yes'), ('2/29/2008', 14.7, 20.6, 33.0, 7.0, 8.9, 'W', 41, 'SW', 'S', 24, 28, 65, 51, 1015.3, 1015.6, 5, 3, 17.1, 19.9, 'Yes', 'No'), ('3/1/2008', 12.8, 22.0, 0.2, 6.2, 11.3, 'W', 41, 'W', 'SSE', 19, 31, 55, 46, 1020.9, 1020.6, 0, 1, 15.9, 21.2, 'No', 'Yes'), ('3/2/2008', 14.2, 23.4, 5.4, 6.4, 7.3, 'W', 41, 'W', 'SE', 13, 17, 93, 54, 1026.2, 1025.2, 7, 2, 15.1, 22.4, 'Yes', 'No'), ('3/3/2008', 15.0, 23.1, 0.2, 2.6, 11.2, 'W', 41, 'W', 'ENE', 15, 19, 78, 57, 1025.8, 1022.5, 1, 1, 18.2, 22.5, 'No', 'No'), ('3/4/2008', 15.5, 25.4, 0.0, 6.8, 11.3, 'W', 41, 'WNW', 'E', 9, 19, 77, 57, 1020.5, 1018.6, 0, 2, 18.7, 23.8, 'No', 'No'), ('3/5/2008', 18.7, 25.8, 0.0, 6.0, 8.7, 'W', 41, 'S', 'ESE', 19, 22, 72, 64, 1024.8, 1024.2, 6, 3, 22.6, 24.1, 'No', 'No'), ('3/6/2008', 19.6, 26.0, 0.0, 5.0, 10.4, 'W', 41, 'N', 'ENE', 11, 19, 67, 65, 1024.2, 1019.8, 1, 1, 22.1, 24.7, 'No', 'No'), ('3/7/2008', 19.9, 24.9, 0.0, 7.6, 4.5, 'W', 41, 'SSW', 'SSE', 13, 24, 83, 75, 1021.3, 1020.7, 5, 7, 22.9, 23.3, 'No', 'Yes'), ('3/8/2008', 16.5, 24.8, 17.4, 6.0, 9.6, 'W', 41, 'WNW', 'E', 9, 22, 88, 71, 1023.4, 1022.3, 1, 2, 18.8, 21.5, 'Yes', 'No'), ('3/9/2008', 16.4, 24.3, 0.0, 4.6, 10.2, 'W', 41, 'W', 'E', 9, 19, 82, 64, 1025.5, 1025.2, 1, 2, 19.7, 23.8, 'No', 'No'), ('3/10/2008', 19.3, 26.3, 0.0, 4.6, 10.8, 'W', 41, 'WNW', 'NE', 9, 24, 76, 50, 1025.1, 1022.5, 1, 0, 22.9, 25.5, 'No', 'No'), ('3/11/2008', 18.6, 26.1, 0.0, 7.6, 11.3, 'W', 41, 'ENE', 'E', 2, 20, 72, 58, 1022.0, 1021.4, 0, 0, 21.9, 26.0, 'No', 'No'), ('3/12/2008', 19.3, 26.4, 0.0, 7.0, 11.1, 'W', 41, 'W', 'NE', 7, 22, 77, 60, 1021.9, 1018.8, 1, 1, 22.2, 25.0, 'No', 'No'), ('3/13/2008', 19.2, 26.1, 0.0, 6.0, 10.6, 'W', 41, 'WNW', 'ESE', 6, 20, 84, 69, 1019.7, 1019.0, 1, 4, 22.4, 25.3, 'No', 'No'), ('3/14/2008', 18.8, 26.0, 0.0, 5.4, 11.0, 'W', 41, 'W', 'ENE', 9, 24, 84, 62, 1022.8, 1020.0, 3, 1, 21.8, 25.7, 'No', 'No'), ('3/15/2008', 19.3, 26.1, 0.0, 7.0, 11.3, 'W', 41, 'NW', 'ENE', 2, 20, 80, 64, 1022.1, 1020.9, 1, 1, 22.5, 25.6, 'No', 'No'), ('3/16/2008', 19.7, 25.8, 0.0, 5.6, 10.1, 'W', 41, 'W', 'E', 7, 24, 81, 69, 1024.6, 1022.6, 2, 2, 22.8, 24.7, 'No', 'No'), ('3/17/2008', 19.5, 25.7, 0.0, 6.4, 10.0, 'W', 41, 'WNW', 'E', 4, 19, 82, 60, 1024.8, 1022.8, 4, 1, 22.0, 25.4, 'No', 'No'), ('3/18/2008', 19.0, 26.7, 0.0, 8.0, 9.7, 'W', 41, 'N', 'ENE', 11, 20, 73, 58, 1023.3, 1020.0, 0, 2, 22.2, 25.6, 'No', 'No'), ('3/19/2008', 19.9, 26.9, 0.0, 6.6, 6.3, 'W', 41, 'SSE', 'E', 7, 13, 70, 60, 1021.2, 1019.4, 5, 7, 23.9, 24.9, 'No', 'No'), ('3/20/2008', 19.7, 28.1, 0.0, 6.0, 10.4, 'W', 41, 'NNE', 'NE', 6, 17, 70, 58, 1014.3, 1009.6, 2, 2, 23.5, 27.6, 'No', 'No'), ('3/21/2008', 17.7, 19.6, 1.0, 7.0, 0.0, 'W', 41, 'S', 'SSW', 26, 22, 87, 80, 1017.3, 1018.9, 8, 8, 17.8, 18.4, 'No', 'Yes'), ('3/22/2008', 16.9, 23.2, 2.2, 2.2, 0.6, 'W', 41, 'ESE', 'E', 24, 30, 81, 60, 1022.8, 1022.2, 7, 7, 19.6, 21.7, 'Yes', 'No'), ('3/23/2008', 16.3, 24.8, 0.4, 4.0, 6.1, 'W', 41, 'WNW', 'ESE', 9, 13, 82, 57, 1023.1, 1020.6, 5, 6, 18.5, 24.8, 'No', 'Yes'), ('3/24/2008', 18.5, 24.3, 17.0, 2.6, 8.0, 'W', 41, 'NNW', 'ENE', 7, 26, 95, 72, 1018.7, 1015.3, 6, 2, 19.9, 23.3, 'Yes', 'No'), ('3/25/2008', 19.8, 27.5, 0.4, 6.4, 2.5, 'W', 41, 'NE', 'NNW', 4, 17, 81, 58, 1011.1, 1006.9, 5, 7, 21.4, 27.0, 'No', 'Yes'), ('3/26/2008', 17.0, 27.2, 19.0, 2.4, 10.5, 'W', 41, 'W', 'NW', 0, 6, 76, 38, 1008.9, 1007.9, 1, 5, 20.5, 27.1, 'Yes', 'No'), ('3/27/2008', 15.0, 23.6, 0.0, 5.8, 11.0, 'W', 41, 'W', 'ESE', 20, 19, 52, 42, 1014.7, 1013.4, 1, 1, 17.5, 21.8, 'No', 'No'), ('3/28/2008', 15.2, 21.7, 0.0, 2.6, 8.3, 'W', 41, 'SSW', 'SE', 13, 17, 71, 51, 1017.1, 1016.2, 4, 3, 18.3, 21.2, 'No', 'No'), ('3/29/2008', 14.4, 22.9, 0.2, 4.8, 9.3, 'W', 41, 'W', 'E', 15, 15, 85, 65, 1015.4, 1011.2, 3, 2, 16.7, 21.7, 'No', 'No'), ('3/30/2008', 13.1, 26.8, 0.0, 4.6, 10.9, 'W', 41, 'W', 'WNW', 22, 15, 61, 22, 1013.0, 1009.0, 0, 1, 16.9, 25.9, 'No', 'No'), ('3/31/2008', 13.5, 25.6, 0.0, 5.8, 10.4, 'W', 41, 'WNW', 'WNW', 9, 17, 57, 31, 1015.0, 1012.5, 4, 1, 16.3, 24.9, 'No', 'No'), ('4/1/2008', 13.7, 23.9, 0.0, 6.6, 11.0, 'W', 41, 'W', 'ESE', 20, 15, 55, 54, 1023.0, 1021.5, 1, 1, 16.7, 23.3, 'No', 'No'), ('4/2/2008', 14.1, 28.7, 0.0, 3.8, 10.5, 'W', 41, 'W', 'N', 6, 22, 75, 34, 1019.0, 1012.4, 1, 7, 17.8, 28.0, 'No', 'No'), ('4/3/2008', 16.4, 22.2, 0.0, 10.6, 9.7, 'W', 41, 'SW', 'WSW', 26, 20, 42, 21, 1009.9, 1010.8, 6, 1, 16.6, 21.2, 'No', 'No'), ('4/4/2008', 11.2, 22.2, 0.0, 7.6, 10.6, 'W', 41, 'W', 'E', 24, 15, 47, 37, 1020.8, 1019.2, 1, 0, 13.9, 21.0, 'No', 'No'), ('4/5/2008', 11.6, 22.7, 0.0, 4.2, 10.7, 'W', 41, 'WNW', 'E', 13, 17, 71, 50, 1024.5, 1023.4, 0, 1, 15.2, 21.0, 'No', 'No'), ('4/6/2008', 13.1, 22.7, 0.0, 3.6, 6.4, 'W', 41, 'W', 'ESE', 13, 20, 71, 55, 1027.2, 1024.6, 5, 6, 17.7, 22.1, 'No', 'Yes'), ('4/7/2008', 15.3, 22.0, 12.0, 3.2, 4.7, 'W', 41, 'SSW', 'SSE', 11, 15, 83, 70, 1026.3, 1024.2, 5, 6, 18.2, 19.8, 'Yes', 'Yes'), ('4/8/2008', 14.6, 22.1, 9.6, 5.4, 5.1, 'W', 41, 'SE', 'SE', 20, 17, 86, 75, 1026.5, 1024.1, 6, 6, 17.0, 18.9, 'Yes', 'Yes'), ('4/9/2008', 15.6, 22.2, 22.8, 5.4, 5.8, 'W', 41, 'W', 'E', 13, 20, 96, 62, 1024.6, 1021.4, 7, 5, 16.3, 21.1, 'Yes', 'Yes'), ('4/10/2008', 13.8, 22.7, 2.2, 3.6, 10.6, 'W', 41, 'W', 'E', 15, 15, 77, 60, 1022.1, 1019.7, 5, 1, 18.7, 21.9, 'Yes', 'No'), ('4/11/2008', 14.1, 23.5, 0.0, 3.2, 8.9, 'W', 41, 'W', 'E', 15, 15, 83, 61, 1020.1, 1017.5, 4, 2, 17.1, 22.1, 'No', 'No'), ('4/12/2008', 14.0, 23.8, 0.0, 4.0, 7.8, 'W', 41, 'W', 'E', 11, 9, 79, 59, 1018.6, 1016.0, 7, 4, 17.6, 22.2, 'No', 'No'), ('4/13/2008', 15.1, 22.7, 0.0, 1.8, 6.6, 'W', 41, 'W', 'ESE', 11, 4, 81, 75, 1016.4, 1013.4, 5, 6, 17.4, 19.7, 'No', 'Yes'), ('4/14/2008', 13.2, 18.9, 11.0, 3.2, 5.2, 'W', 41, 'SSW', 'S', 19, 30, 82, 64, 1019.6, 1019.2, 7, 3, 15.9, 18.8, 'Yes', 'Yes'), ('4/15/2008', 13.8, 19.7, 2.8, 2.8, 1.7, 'W', 41, 'SW', 'S', 20, 22, 85, 71, 1025.4, 1023.9, 7, 7, 15.9, 19.0, 'Yes', 'Yes'), ('4/16/2008', 13.8, 20.9, 1.4, 4.6, 2.2, 'W', 41, 'SSW', 'SSW', 15, 20, 78, 85, 1026.4, 1024.6, 7, 8, 17.2, 16.2, 'Yes', 'Yes'), ('4/17/2008', 14.9, 19.7, 4.6, 1.4, 0.8, 'W', 41, 'SSW', 'S', 17, 13, 91, 72, 1025.1, 1023.4, 7, 7, 16.4, 19.4, 'Yes', 'Yes'), ('4/18/2008', 15.3, 20.0, 6.4, 3.2, 0.3, 'W', 41, 'W', 'SSE', 4, 15, 94, 75, 1025.4, 1023.7, 8, 7, 16.4, 19.6, 'Yes', 'Yes'), ('4/19/2008', 15.9, 21.4, 5.0, 4.8, 5.0, 'W', 41, 'SE', 'SE', 22, 24, 51, 61, 1027.2, 1026.1, 6, 7, 19.3, 19.5, 'Yes', 'Yes'), ('4/20/2008', 15.2, 19.1, 2.8, 4.0, 1.3, 'W', 41, 'ESE', 'S', 15, 6, 79, 75, 1026.6, 1023.7, 7, 6, 17.3, 18.4, 'Yes', 'Yes'), ('4/21/2008', 14.7, 19.3, 21.8, 7.5, 4.6, 'W', 41, 'SSW', 'S', 9, 19, 91, 70, 1023.2, 1021.4, 8, 7, 16.6, 19.0, 'Yes', 'Yes'), ('4/22/2008', 14.4, 20.3, 10.2, 3.6, 2.0, 'W', 41, 'SSE', 'SE', 9, 20, 90, 55, 1023.6, 1022.3, 7, 5, 16.1, 20.1, 'Yes', 'Yes'), ('4/23/2008', 14.7, 17.9, 12.6, 4.0, 0.7, 'W', 41, 'SW', 'SSE', 6, 22, 90, 89, 1024.0, 1022.1, 7, 7, 16.2, 17.2, 'Yes', 'Yes'), ('4/24/2008', 14.7, 20.0, 15.6, 1.6, 2.5, 'W', 41, 'S', 'S', 19, 20, 93, 80, 1021.3, 1018.6, 7, 7, 16.8, 19.3, 'Yes', 'Yes'), ('4/26/2008', 12.7, 24.8, 0.4, 2.6, 10.2, 'W', 41, 'W', 'E', 15, 6, 81, 38, 1011.2, 1007.0, 2, 7, 15.6, 24.6, 'No', 'No'), ('4/27/2008', 15.6, 26.1, 0.0, 5.2, 7.6, 'W', 41, 'NNW', 'N', 20, 22, 51, 28, 1005.2, 999.1, 6, 2, 20.3, 25.7, 'No', 'No'), ('4/28/2008', 11.9, 16.8, 0.0, 7.6, 8.5, 'W', 41, 'W', 'WSW', 20, 24, 46, 33, 1007.4, 1008.6, 2, 6, 13.7, 15.6, 'No', 'No'), ('4/29/2008', 8.6, 18.4, 0.0, 3.8, 10.5, 'W', 41, 'W', 'SSE', 24, 9, 54, 41, 1020.4, 1019.8, 1, 1, 11.7, 17.8, 'No', 'No'), ('4/30/2008', 8.4, 19.6, 0.0, 3.6, 9.8, 'W', 41, 'W', 'E', 15, 17, 68, 50, 1024.2, 1021.3, 1, 3, 11.6, 18.1, 'No', 'No'), ('5/1/2008', 11.6, 18.2, 0.0, 4.0, 2.7, 'W', 41, 'WNW', 'W', 11, 7, 74, 56, 1019.7, 1016.7, 7, 7, 13.4, 18.1, 'No', 'No'), ('5/2/2008', 10.8, 22.2, 0.0, 2.4, 9.1, 'W', 41, 'W', 'WSW', 19, 17, 65, 44, 1018.7, 1015.3, 1, 3, 14.5, 21.7, 'No', 'No'), ('5/3/2008', 10.9, 19.6, 0.0, 3.4, 10.5, 'W', 41, 'W', 'SSE', 19, 11, 62, 52, 1019.3, 1016.9, 1, 1, 14.1, 18.6, 'No', 'No'), ('5/4/2008', 9.4, 20.3, 0.0, 3.6, 10.3, 'W', 41, 'W', 'SE', 22, 11, 64, 47, 1021.1, 1018.3, 1, 1, 12.4, 19.4, 'No', 'No'), ('5/5/2008', 9.4, 22.3, 0.0, 2.0, 10.0, 'W', 41, 'W', 'NW', 15, 7, 71, 34, 1018.7, 1015.2, 1, 2, 12.4, 22.2, 'No', 'No'), ('5/6/2008', 11.8, 23.6, 0.0, 3.4, 3.1, 'W', 41, 'W', 'WNW', 9, 9, 74, 48, 1017.1, 1013.3, 6, 7, 13.7, 21.1, 'No', 'No'), ('5/7/2008', 13.0, 23.0, 0.0, 3.6, 9.4, 'W', 41, 'W', 'SSE', 22, 13, 57, 44, 1014.3, 1011.8, 1, 3, 16.5, 22.0, 'No', 'No'), ('5/8/2008', 11.0, 21.8, 0.0, 3.2, 10.2, 'W', 41, 'W', 'S', 24, 15, 63, 45, 1019.2, 1017.5, 1, 1, 14.0, 20.8, 'No', 'No'), ('5/9/2008', 11.0, 21.9, 0.0, 3.2, 10.1, 'W', 41, 'W', 'SE', 17, 11, 75, 60, 1021.4, 1020.2, 0, 1, 14.3, 20.6, 'No', 'No'), ('5/10/2008', 12.6, 21.3, 0.0, 3.0, 9.6, 'W', 41, 'WNW', 'E', 11, 11, 86, 67, 1022.2, 1019.6, 1, 1, 15.2, 19.3, 'No', 'No'), ('5/11/2008', 14.0, 19.4, 0.0, 1.2, 2.1, 'W', 41, 'WNW', 'SSE', 13, 15, 84, 67, 1023.1, 1021.2, 7, 7, 16.8, 18.7, 'No', 'No'), ('5/12/2008', 12.4, 19.5, 0.0, 1.6, 7.3, 'W', 41, 'W', 'E', 11, 15, 88, 63, 1023.5, 1020.5, 1, 1, 14.9, 19.2, 'No', 'No'), ('5/13/2008', 13.2, 19.7, 0.0, 1.8, 4.2, 'W', 41, 'W', 'E', 11, 9, 88, 67, 1023.4, 1021.7, 6, 7, 15.0, 18.1, 'No', 'No'), ('5/14/2008', 11.2, 20.6, 0.0, 2.0, 9.7, 'W', 41, 'W', 'ENE', 20, 19, 82, 64, 1023.8, 1020.5, 1, 1, 13.8, 20.0, 'No', 'No'), ('5/15/2008', 12.0, 21.4, 0.2, 3.2, 8.7, 'W', 41, 'W', 'E', 13, 9, 90, 60, 1022.2, 1017.8, 1, 1, 13.9, 21.3, 'No', 'Yes'), ('5/16/2008', 13.8, 23.2, 1.2, 2.2, 6.4, 'W', 41, 'WNW', 'NE', 15, 15, 78, 66, 1017.1, 1013.0, 6, 2, 15.9, 20.9, 'Yes', 'No'), ('5/17/2008', 15.2, 21.8, 0.0, 4.2, 6.9, 'W', 41, 'NNW', 'NNW', 20, 17, 52, 41, 1008.4, 1003.6, 3, 7, 19.2, 20.9, 'No', 'No'), ('5/18/2008', 8.8, 17.8, 0.0, 4.2, 9.4, 'W', 41, 'W', 'W', 19, 31, 57, 36, 1007.0, 1006.3, 1, 1, 11.6, 17.0, 'No', 'No'), ('5/19/2008', 10.7, 20.5, 0.0, 4.4, 9.9, 'W', 41, 'W', 'WNW', 22, 7, 58, 36, 1015.7, 1013.3, 1, 0, 12.5, 20.3, 'No', 'No'), ('5/20/2008', 10.3, 21.7, 0.0, 3.0, 10.0, 'W', 41, 'W', 'W', 24, 7, 64, 38, 1020.1, 1017.5, 1, 1, 13.0, 21.3, 'No', 'No'), ('5/21/2008', 11.1, 18.9, 0.0, 2.4, 6.1, 'W', 41, 'WNW', 'S', 19, 22, 74, 64, 1022.4, 1022.8, 4, 7, 13.5, 17.3, 'No', 'No'), ('5/22/2008', 11.9, 18.7, 0.0, 4.0, 7.5, 'W', 41, 'SSW', 'SSE', 20, 19, 63, 52, 1028.2, 1026.2, 1, 2, 15.1, 17.4, 'No', 'No'), ('5/23/2008', 11.0, 18.4, 0.0, 3.4, 5.4, 'W', 41, 'WNW', 'SSE', 17, 13, 76, 53, 1026.9, 1024.6, 1, 5, 12.7, 17.1, 'No', 'No'), ('5/24/2008', 11.4, 20.1, 0.0, 2.4, 9.1, 'W', 41, 'W', 'NW', 13, 2, 71, 39, 1025.4, 1022.7, 1, 1, 13.3, 19.3, 'No', 'No'), ('5/25/2008', 8.8, 18.3, 0.0, 3.6, 6.5, 'W', 41, 'W', 'ENE', 17, 11, 78, 58, 1025.1, 1022.2, 4, 3, 11.1, 16.9, 'No', 'No'), ('5/26/2008', 10.9, 21.1, 0.4, 0.4, 9.1, 'W', 41, 'W', 'ENE', 20, 13, 81, 58, 1025.9, 1022.6, 6, 2, 12.9, 19.5, 'No', 'No'), ('5/27/2008', 11.5, 22.4, 0.0, 3.2, 8.7, 'W', 41, 'W', 'E', 15, 13, 82, 71, 1024.6, 1021.8, 3, 1, 13.6, 19.1, 'No', 'No'), ('5/28/2008', 11.0, 19.2, 0.0, 1.6, 3.9, 'W', 41, 'W', 'NE', 26, 2, 80, 74, 1025.6, 1023.9, 3, 6, 12.8, 18.6, 'No', 'No'), ('5/29/2008', 11.0, 18.6, 1.0, 1.0, 4.6, 'W', 41, 'W', 'S', 19, 4, 86, 76, 1030.2, 1029.1, 3, 2, 12.7, 17.6, 'No', 'No'), ('5/30/2008', 10.9, 21.0, 0.2, 1.4, 5.6, 'W', 41, 'W', 'E', 19, 7, 87, 58, 1032.0, 1028.7, 1, 2, 12.7, 19.6, 'No', 'No'), ('5/31/2008', 10.8, 20.1, 0.0, 1.0, 9.4, 'W', 41, 'WNW', 'SSE', 17, 17, 90, 61, 1028.6, 1026.66, 1, 1, 11.7, 19.4, 'No', 'No'), ('6/1/2008', 11.6, 20.5, 0.2, 2.2, 0.3, 'W', 41, 'W', 'SE', 19, 17, 91, 74, 1029.3, 1027.0, 7, 7, 14.3, 18.7, 'No', 'Yes'), ('6/2/2008', 14.3, 17.6, 22.0, 1.8, 0.1, 'W', 41, 'W', 'W', 9, 7, 97, 90, 1027.3, 1024.8, 8, 7, 15.3, 17.1, 'Yes', 'Yes'), ('6/3/2008', 15.2, 19.1, 4.0, 0.4, 0.0, 'W', 41, 'W', 'E', 17, 22, 98, 90, 1026.4, 1024.1, 8, 8, 15.6, 16.7, 'Yes', 'Yes'), ('6/4/2008', 15.5, 18.3, 9.2, 2.4, 0.0, 'W', 41, 'SE', 'ESE', 19, 26, 87, 88, 1023.1, 1020.5, 8, 8, 17.5, 17.2, 'Yes', 'Yes'), ('6/5/2008', 15.2, 16.9, 46.4, 2.4, 0.0, 'W', 41, 'SSW', 'S', 24, 24, 82, 84, 1020.1, 1018.6, 7, 8, 16.0, 16.6, 'Yes', 'Yes'), ('6/6/2008', 14.7, 17.4, 12.4, 0.4, 1.8, 'W', 41, 'WSW', 'SSW', 15, 24, 81, 70, 1021.2, 1020.3, 7, 6, 15.1, 16.6, 'Yes', 'No'), ('6/7/2008', 11.7, 18.2, 0.0, 2.2, 8.8, 'W', 41, 'W', 'S', 19, 24, 76, 49, 1025.0, 1025.7, 1, 1, 13.3, 17.9, 'No', 'Yes'), ('6/8/2008', 12.7, 17.7, 6.0, 1.4, 0.5, 'W', 41, 'WNW', 'ESE', 17, 17, 97, 71, 1032.1, 1029.8, 8, 7, 14.1, 17.2, 'Yes', 'Yes'), ('6/9/2008', 13.0, 16.9, 3.6, 1.2, 1.2, 'W', 41, 'W', 'ESE', 13, 2, 96, 89, 1030.9, 1028.0, 7, 8, 13.9, 16.2, 'Yes', 'Yes'), ('6/10/2008', 12.4, 19.9, 1.6, 1.6, 3.9, 'W', 41, 'W', 'N', 13, 9, 98, 68, 1027.5, 1023.9, 7, 1, 13.2, 19.1, 'Yes', 'No'), ('6/11/2008', 13.2, 19.9, 0.0, 1.8, 0.0, 'W', 41, 'NNW', 'N', 6, 4, 74, 70, 1022.9, 1020.6, 7, 8, 17.3, 19.6, 'No', 'Yes'), ('6/12/2008', 13.7, 22.1, 5.4, 1.8, 6.9, 'W', 41, 'W', 'ENE', 11, 7, 97, 64, 1022.4, 1018.1, 8, 1, 14.1, 20.1, 'Yes', 'No'), ('6/13/2008', 14.0, 18.8, 0.0, 3.4, 8.6, 'W', 41, 'NW', 'WSW', 20, 26, 67, 42, 1012.2, 1011.5, 1, 2, 16.6, 16.7, 'No', 'No'), ('6/14/2008', 9.6, 14.6, 0.0, 3.8, 3.4, 'W', 41, 'W', 'SW', 30, 24, 49, 52, 1022.0, 1022.5, 5, 7, 11.2, 14.1, 'No', 'No'), ('6/15/2008', 10.6, 15.3, 0.0, 2.8, 0.1, 'W', 41, 'SSW', 'SSW', 24, 26, 75, 87, 1024.4, 1022.8, 7, 8, 13.7, 14.5, 'No', 'Yes'), ('6/16/2008', 13.3, 16.8, 7.2, 5.0, 2.4, 'W', 41, 'SSW', 'SSW', 19, 20, 86, 83, 1024.2, 1023.0, 6, 7, 15.0, 15.8, 'Yes', 'Yes'), ('6/17/2008', 13.1, 17.5, 3.4, 0.8, 1.3, 'W', 41, 'W', 'SSW', 11, 13, 88, 73, 1026.7, 1024.8, 7, 7, 14.2, 17.3, 'Yes', 'No'), ('6/18/2008', 13.6, 19.4, 0.0, 1.6, 4.1, 'W', 41, 'W', 'NE', 13, 2, 90, 69, 1025.5, 1022.1, 7, 8, 14.8, 19.2, 'No', 'No'), ('6/19/2008', 12.8, 20.3, 0.0, 2.0, 5.0, 'W', 41, 'WNW', 'ESE', 13, 13, 91, 69, 1020.3, 1017.4, 6, 7, 13.9, 18.6, 'No', 'Yes'), ('6/20/2008', 13.8, 17.9, 3.6, 0.6, 0.6, 'W', 41, 'W', 'W', 19, 19, 81, 60, 1018.3, 1016.2, 7, 7, 14.3, 17.2, 'Yes', 'Yes'), ('6/21/2008', 11.6, 18.5, 2.2, 1.8, 9.4, 'W', 41, 'W', 'WSW', 15, 17, 66, 40, 1020.7, 1018.9, 1, 1, 13.2, 18.0, 'Yes', 'No'), ('6/22/2008', 9.7, 17.3, 0.0, 3.4, 9.3, 'W', 41, 'W', 'SSW', 22, 22, 61, 54, 1023.2, 1024.0, 1, 3, 11.4, 16.3, 'No', 'No'), ('6/23/2008', 8.2, 17.1, 0.0, 3.4, 7.0, 'W', 41, 'WNW', 'WSW', 13, 13, 74, 43, 1023.7, 1020.4, 1, 7, 9.9, 17.0, 'No', 'No'), ('6/24/2008', 9.2, 19.2, 0.0, 1.8, 9.2, 'W', 41, 'W', 'WNW', 19, 9, 72, 45, 1027.0, 1023.1, 1, 1, 10.7, 18.8, 'No', 'No'), ('6/25/2008', 9.9, 19.6, 0.0, 2.8, 9.8, 'W', 41, 'W', 'WNW', 17, 6, 69, 43, 1024.6, 1020.6, 1, 0, 11.8, 19.4, 'No', 'No'), ('6/26/2008', 10.2, 20.2, 0.0, 3.2, 9.7, 'W', 41, 'WNW', 'W', 28, 28, 47, 38, 1017.0, 1016.8, 0, 1, 14.6, 19.3, 'No', 'No'), ('6/27/2008', 9.5, 19.4, 0.0, 4.4, 9.3, 'W', 41, 'W', 'WSW', 24, 15, 57, 32, 1025.9, 1023.6, 0, 0, 10.8, 18.9, 'No', 'No'), ('6/28/2008', 7.9, 18.7, 0.0, 3.0, 8.8, 'W', 41, 'W', 'SSE', 20, 9, 68, 43, 1027.6, 1024.7, 1, 1, 10.1, 18.1, 'No', 'No'), ('6/29/2008', 7.9, 21.0, 0.0, 0.8, 9.8, 'W', 41, 'WNW', 'NNW', 13, 6, 84, 42, 1024.1, 1018.8, 2, 1, 9.2, 20.8, 'No', 'No'), ('6/30/2008', 9.2, 22.1, 0.0, 3.2, 9.8, 'W', 41, 'NNW', 'NW', 19, 28, 47, 35, 1017.1, 1010.3, 1, 1, 13.8, 21.6, 'No', 'No'), ('7/1/2008', 10.3, 19.6, 0.2, 3.8, 9.5, 'W', 41, 'W', 'W', 0, 41, 45, 34, 1011.0, 1008.5, 0, 1, 13.1, 19.2, 'No', 'No'), ('7/2/2008', 10.8, 19.2, 0.0, 4.0, 9.7, 'W', 41, 'WNW', 'W', 26, 31, 55, 35, 1012.5, 1011.2, 1, 1, 14.6, 18.8, 'No', 'No'), ('7/3/2008', 9.2, 17.9, 0.0, 3.2, 9.6, 'W', 41, 'W', 'WNW', 17, 7, 63, 42, 1022.7, 1020.8, 1, 1, 10.7, 17.4, 'No', 'Yes'), ('7/4/2008', 8.2, 15.0, 1.2, 2.4, 0.4, 'W', 41, 'W', 'S', 20, 9, 84, 88, 1029.0, 1028.2, 7, 7, 9.1, 12.9, 'Yes', 'Yes'), ('7/5/2008', 9.1, 17.4, 14.2, 1.6, 2.5, 'W', 41, 'WNW', 'NE', 11, 15, 78, 48, 1031.9, 1028.9, 6, 6, 11.3, 16.8, 'Yes', 'No'), ('7/6/2008', 8.3, 18.4, 0.0, 2.2, 7.8, 'W', 41, 'W', 'SSE', 15, 4, 84, 59, 1029.2, 1025.7, 1, 3, 9.8, 17.7, 'No', 'No'), ('7/7/2008', 9.7, 19.8, 0.0, 2.2, 4.3, 'W', 41, 'W', 'N', 9, 11, 87, 55, 1024.4, 1019.7, 7, 5, 11.3, 19.3, 'No', 'No'), ('7/8/2008', 10.5, 17.2, 0.2, 1.6, 5.5, 'W', 41, 'W', 'SE', 11, 7, 80, 49, 1020.9, 1017.4, 1, 4, 12.1, 16.4, 'No', 'No'), ('7/9/2008', 6.9, 13.3, 0.0, 2.8, 4.6, 'W', 41, 'W', 'WSW', 15, 20, 57, 43, 1018.0, 1015.7, 2, 7, 9.6, 13.2, 'No', 'Yes'), ('7/10/2008', 7.2, 15.8, 1.8, 2.4, 4.9, 'W', 41, 'WNW', 'NW', 11, 26, 58, 38, 1014.6, 1010.0, 7, 3, 10.2, 15.8, 'Yes', 'No'

In [5]:
tupledata=[('2/1/2008', 19.5, 22.4, 15.6, 6.2, 0.0, 'W', 41, 'S', 'SSW', 17, 20, 92, 84, 1017.6, 1017.4, 8, 8, 20.7, 20.9, 'Yes', 'Yes'), ('2/2/2008', 19.5, 25.6, 6.0, 3.4, 2.7, 'W', 41, 'W', 'E', 9, 13, 83, 73, 1017.9, 1016.4, 7, 7, 22.4, 24.8, 'Yes', 'Yes'), ('2/3/2008', 21.6, 24.5, 6.6, 2.4, 0.1, 'W', 41, 'ESE', 'ESE', 17, 2, 88, 86, 1016.7, 1015.6, 7, 8, 23.5, 23.0, 'Yes', 'Yes'), ('2/4/2008', 20.2, 22.8, 18.8, 2.2, 0.0, 'W', 41, 'NNE', 'E', 22, 20, 83, 90, 1014.2, 1011.8, 8, 8, 21.4, 20.9, 'Yes', 'Yes'), ('2/5/2008', 19.7, 25.7, 77.4, 4.8, 0.0, 'W', 41, 'NNE', 'W', 11, 6, 88, 74, 1008.3, 1004.8, 8, 8, 22.5, 25.5, 'Yes', 'Yes'), ('2/6/2008', 20.2, 27.2, 1.6, 2.6, 8.6, 'W', 41, 'W', 'ENE', 9, 22, 69, 62, 1002.7, 998.6, 6, 6, 23.8, 26.0, 'Yes', 'Yes'), ('2/7/2008', 18.6, 26.3, 6.2, 5.2, 5.2, 'W', 41, 'W', 'S', 15, 15, 75, 80, 999.0, 1000.3, 4, 7, 21.7, 22.3, 'Yes', 'Yes'), ('2/8/2008', 17.2, 22.3, 27.6, 5.8, 2.1, 'W', 41, 'S', 'SE', 7, 15, 77, 61, 1008.3, 1007.4, 7, 8, 18.9, 21.1, 'Yes', 'Yes'), ('2/9/2008', 16.4, 20.8, 12.6, 4.8, 3.0, 'W', 41, 'SSW', 'W', 19, 9, 92, 91, 1006.4, 1007.6, 7, 7, 17.1, 16.5, 'Yes', 'Yes'), ('2/10/2008', 14.6, 24.2, 8.8, 4.4, 10.1, 'W', 41, 'W', 'SSE', 11, 20, 80, 53, 1014.0, 1013.4, 4, 2, 17.2, 23.3, 'Yes', 'No'), ('2/11/2008', 16.4, 23.9, 0.0, 6.4, 8.0, 'W', 41, 'WNW', 'E', 9, 26, 78, 53, 1017.6, 1015.3, 7, 8, 18.9, 23.7, 'No', 'No'), ('2/12/2008', 18.9, 27.3, 0.0, 6.8, 6.7, 'W', 41, 'N', 'NE', 7, 24, 68, 67, 1010.7, 1007.5, 7, 7, 22.9, 24.7, 'No', 'Yes'), ('2/13/2008', 18.4, 22.8, 14.4, 7.0, 3.3, 'W', 41, 'S', 'S', 24, 30, 87, 70, 1009.2, 1011.7, 8, 7, 20.9, 21.0, 'Yes', 'Yes'), ('2/14/2008', 16.9, 24.3, 3.0, 3.2, 8.7, 'W', 41, 'SSW', 'SSE', 15, 19, 81, 51, 1017.2, 1016.5, 7, 1, 18.4, 23.3, 'Yes', 'No'), ('2/15/2008', 18.3, 24.4, 0.0, 6.2, 8.5, 'W', 41, 'SW', 'SSE', 19, 22, 80, 56, 1020.2, 1018.9, 7, 3, 19.5, 23.8, 'No', 'No'), ('2/16/2008', 16.7, 24.1, 0.0, 6.2, 8.8, 'W', 41, 'WNW', 'SSE', 11, 26, 77, 52, 1023.0, 1022.6, 7, 6, 19.8, 23.3, 'No', 'No'), ('2/17/2008', 19.5, 24.8, 0.0, 7.6, 3.2, 'W', 41, 'SE', 'ESE', 13, 24, 63, 62, 1024.7, 1023.1, 7, 7, 21.8, 23.4, 'No', 'No'), ('2/18/2008', 18.6, 25.3, 0.0, 4.2, 4.5, 'W', 41, 'SSE', 'ENE', 13, 24, 70, 59, 1021.7, 1019.4, 7, 6, 21.2, 23.8, 'No', 'No'), ('2/19/2008', 19.0, 24.8, 0.0, 5.2, 7.5, 'W', 41, 'WNW', 'E', 7, 17, 79, 65, 1018.0, 1015.4, 7, 7, 20.8, 23.4, 'No', 'No'), ('2/20/2008', 18.3, 26.4, 0.0, 4.6, 11.1, 'W', 41, 'W', 'E', 13, 22, 80, 60, 1013.4, 1010.8, 3, 1, 21.3, 25.2, 'No', 'No'), ('2/21/2008', 20.6, 26.8, 0.0, 6.8, 6.4, 'W', 41, 'WNW', 'SE', 4, 15, 86, 62, 1011.4, 1009.7, 7, 7, 22.1, 24.9, 'No', 'No'), ('2/22/2008', 19.1, 25.4, 0.4, 4.4, 9.4, 'W', 41, 'WNW', 'E', 11, 28, 77, 66, 1009.2, 1003.1, 4, 1, 22.3, 24.9, 'No', 'No'), ('2/23/2008', 20.5, 26.0, 0.0, 6.6, 12.2, 'W', 41, 'WSW', 'ESE', 20, 24, 38, 45, 1007.4, 1007.0, 1, 1, 22.5, 24.0, 'No', 'No'), ('2/24/2008', 16.5, 28.3, 0.0, 8.6, 12.0, 'W', 41, 'WNW', 'ESE', 11, 24, 48, 40, 1007.9, 1008.0, 0, 0, 21.2, 26.1, 'No', 'No'), ('2/25/2008', 20.5, 24.2, 0.0, 8.6, 1.5, 'W', 41, 'E', 'E', 15, 20, 58, 54, 1017.5, 1016.9, 7, 7, 21.6, 23.5, 'No', 'No'), ('2/26/2008', 19.3, 26.2, 0.0, 3.6, 8.4, 'W', 41, 'WSW', 'E', 2, 28, 73, 65, 1018.3, 1015.6, 1, 6, 23.0, 25.8, 'No', 'Yes'), ('2/27/2008', 19.0, 29.0, 22.2, 8.2, 3.3, 'W', 41, 'W', 'NNE', 0, 15, 82, 52, 1014.1, 1010.6, 7, 7, 21.3, 24.7, 'Yes', 'Yes'), ('2/28/2008', 17.9, 21.4, 4.2, 4.2, 0.0, 'W', 41, 'S', 'ESE', 20, 9, 77, 88, 1010.0, 1010.1, 8, 8, 20.4, 19.2, 'Yes', 'Yes'), ('2/29/2008', 14.7, 20.6, 33.0, 7.0, 8.9, 'W', 41, 'SW', 'S', 24, 28, 65, 51, 1015.3, 1015.6, 5, 3, 17.1, 19.9, 'Yes', 'No'), ('3/1/2008', 12.8, 22.0, 0.2, 6.2, 11.3, 'W', 41, 'W', 'SSE', 19, 31, 55, 46, 1020.9, 1020.6, 0, 1, 15.9, 21.2, 'No', 'Yes'), ('3/2/2008', 14.2, 23.4, 5.4, 6.4, 7.3, 'W', 41, 'W', 'SE', 13, 17, 93, 54, 1026.2, 1025.2, 7, 2, 15.1, 22.4, 'Yes', 'No'), ('3/3/2008', 15.0, 23.1, 0.2, 2.6, 11.2, 'W', 41, 'W', 'ENE', 15, 19, 78, 57, 1025.8, 1022.5, 1, 1, 18.2, 22.5, 'No', 'No'), ('3/4/2008', 15.5, 25.4, 0.0, 6.8, 11.3, 'W', 41, 'WNW', 'E', 9, 19, 77, 57, 1020.5, 1018.6, 0, 2, 18.7, 23.8, 'No', 'No'), ('3/5/2008', 18.7, 25.8, 0.0, 6.0, 8.7, 'W', 41, 'S', 'ESE', 19, 22, 72, 64, 1024.8, 1024.2, 6, 3, 22.6, 24.1, 'No', 'No'), ('3/6/2008', 19.6, 26.0, 0.0, 5.0, 10.4, 'W', 41, 'N', 'ENE', 11, 19, 67, 65, 1024.2, 1019.8, 1, 1, 22.1, 24.7, 'No', 'No'), ('3/7/2008', 19.9, 24.9, 0.0, 7.6, 4.5, 'W', 41, 'SSW', 'SSE', 13, 24, 83, 75, 1021.3, 1020.7, 5, 7, 22.9, 23.3, 'No', 'Yes'), ('3/8/2008', 16.5, 24.8, 17.4, 6.0, 9.6, 'W', 41, 'WNW', 'E', 9, 22, 88, 71, 1023.4, 1022.3, 1, 2, 18.8, 21.5, 'Yes', 'No'), ('3/9/2008', 16.4, 24.3, 0.0, 4.6, 10.2, 'W', 41, 'W', 'E', 9, 19, 82, 64, 1025.5, 1025.2, 1, 2, 19.7, 23.8, 'No', 'No'), ('3/10/2008', 19.3, 26.3, 0.0, 4.6, 10.8, 'W', 41, 'WNW', 'NE', 9, 24, 76, 50, 1025.1, 1022.5, 1, 0, 22.9, 25.5, 'No', 'No'), ('3/11/2008', 18.6, 26.1, 0.0, 7.6, 11.3, 'W', 41, 'ENE', 'E', 2, 20, 72, 58, 1022.0, 1021.4, 0, 0, 21.9, 26.0, 'No', 'No'), ('3/12/2008', 19.3, 26.4, 0.0, 7.0, 11.1, 'W', 41, 'W', 'NE', 7, 22, 77, 60, 1021.9, 1018.8, 1, 1, 22.2, 25.0, 'No', 'No'), ('3/13/2008', 19.2, 26.1, 0.0, 6.0, 10.6, 'W', 41, 'WNW', 'ESE', 6, 20, 84, 69, 1019.7, 1019.0, 1, 4, 22.4, 25.3, 'No', 'No'), ('3/14/2008', 18.8, 26.0, 0.0, 5.4, 11.0, 'W', 41, 'W', 'ENE', 9, 24, 84, 62, 1022.8, 1020.0, 3, 1, 21.8, 25.7, 'No', 'No'), ('3/15/2008', 19.3, 26.1, 0.0, 7.0, 11.3, 'W', 41, 'NW', 'ENE', 2, 20, 80, 64, 1022.1, 1020.9, 1, 1, 22.5, 25.6, 'No', 'No'), ('3/16/2008', 19.7, 25.8, 0.0, 5.6, 10.1, 'W', 41, 'W', 'E', 7, 24, 81, 69, 1024.6, 1022.6, 2, 2, 22.8, 24.7, 'No', 'No'), ('3/17/2008', 19.5, 25.7, 0.0, 6.4, 10.0, 'W', 41, 'WNW', 'E', 4, 19, 82, 60, 1024.8, 1022.8, 4, 1, 22.0, 25.4, 'No', 'No'), ('3/18/2008', 19.0, 26.7, 0.0, 8.0, 9.7, 'W', 41, 'N', 'ENE', 11, 20, 73, 58, 1023.3, 1020.0, 0, 2, 22.2, 25.6, 'No', 'No'), ('3/19/2008', 19.9, 26.9, 0.0, 6.6, 6.3, 'W', 41, 'SSE', 'E', 7, 13, 70, 60, 1021.2, 1019.4, 5, 7, 23.9, 24.9, 'No', 'No'), ('3/20/2008', 19.7, 28.1, 0.0, 6.0, 10.4, 'W', 41, 'NNE', 'NE', 6, 17, 70, 58, 1014.3, 1009.6, 2, 2, 23.5, 27.6, 'No', 'No'), ('3/21/2008', 17.7, 19.6, 1.0, 7.0, 0.0, 'W', 41, 'S', 'SSW', 26, 22, 87, 80, 1017.3, 1018.9, 8, 8, 17.8, 18.4, 'No', 'Yes'), ('3/22/2008', 16.9, 23.2, 2.2, 2.2, 0.6, 'W', 41, 'ESE', 'E', 24, 30, 81, 60, 1022.8, 1022.2, 7, 7, 19.6, 21.7, 'Yes', 'No'), ('3/23/2008', 16.3, 24.8, 0.4, 4.0, 6.1, 'W', 41, 'WNW', 'ESE', 9, 13, 82, 57, 1023.1, 1020.6, 5, 6, 18.5, 24.8, 'No', 'Yes'), ('3/24/2008', 18.5, 24.3, 17.0, 2.6, 8.0, 'W', 41, 'NNW', 'ENE', 7, 26, 95, 72, 1018.7, 1015.3, 6, 2, 19.9, 23.3, 'Yes', 'No'), ('3/25/2008', 19.8, 27.5, 0.4, 6.4, 2.5, 'W', 41, 'NE', 'NNW', 4, 17, 81, 58, 1011.1, 1006.9, 5, 7, 21.4, 27.0, 'No', 'Yes'), ('3/26/2008', 17.0, 27.2, 19.0, 2.4, 10.5, 'W', 41, 'W', 'NW', 0, 6, 76, 38, 1008.9, 1007.9, 1, 5, 20.5, 27.1, 'Yes', 'No'), ('3/27/2008', 15.0, 23.6, 0.0, 5.8, 11.0, 'W', 41, 'W', 'ESE', 20, 19, 52, 42, 1014.7, 1013.4, 1, 1, 17.5, 21.8, 'No', 'No'), ('3/28/2008', 15.2, 21.7, 0.0, 2.6, 8.3, 'W', 41, 'SSW', 'SE', 13, 17, 71, 51, 1017.1, 1016.2, 4, 3, 18.3, 21.2, 'No', 'No'), ('3/29/2008', 14.4, 22.9, 0.2, 4.8, 9.3, 'W', 41, 'W', 'E', 15, 15, 85, 65, 1015.4, 1011.2, 3, 2, 16.7, 21.7, 'No', 'No'), ('3/30/2008', 13.1, 26.8, 0.0, 4.6, 10.9, 'W', 41, 'W', 'WNW', 22, 15, 61, 22, 1013.0, 1009.0, 0, 1, 16.9, 25.9, 'No', 'No'), ('3/31/2008', 13.5, 25.6, 0.0, 5.8, 10.4, 'W', 41, 'WNW', 'WNW', 9, 17, 57, 31, 1015.0, 1012.5, 4, 1, 16.3, 24.9, 'No', 'No'), ('4/1/2008', 13.7, 23.9, 0.0, 6.6, 11.0, 'W', 41, 'W', 'ESE', 20, 15, 55, 54, 1023.0, 1021.5, 1, 1, 16.7, 23.3, 'No', 'No'), ('4/2/2008', 14.1, 28.7, 0.0, 3.8, 10.5, 'W', 41, 'W', 'N', 6, 22, 75, 34, 1019.0, 1012.4, 1, 7, 17.8, 28.0, 'No', 'No'), ('4/3/2008', 16.4, 22.2, 0.0, 10.6, 9.7, 'W', 41, 'SW', 'WSW', 26, 20, 42, 21, 1009.9, 1010.8, 6, 1, 16.6, 21.2, 'No', 'No'), ('4/4/2008', 11.2, 22.2, 0.0, 7.6, 10.6, 'W', 41, 'W', 'E', 24, 15, 47, 37, 1020.8, 1019.2, 1, 0, 13.9, 21.0, 'No', 'No'), ('4/5/2008', 11.6, 22.7, 0.0, 4.2, 10.7, 'W', 41, 'WNW', 'E', 13, 17, 71, 50, 1024.5, 1023.4, 0, 1, 15.2, 21.0, 'No', 'No'), ('4/6/2008', 13.1, 22.7, 0.0, 3.6, 6.4, 'W', 41, 'W', 'ESE', 13, 20, 71, 55, 1027.2, 1024.6, 5, 6, 17.7, 22.1, 'No', 'Yes'), ('4/7/2008', 15.3, 22.0, 12.0, 3.2, 4.7, 'W', 41, 'SSW', 'SSE', 11, 15, 83, 70, 1026.3, 1024.2, 5, 6, 18.2, 19.8, 'Yes', 'Yes'), ('4/8/2008', 14.6, 22.1, 9.6, 5.4, 5.1, 'W', 41, 'SE', 'SE', 20, 17, 86, 75, 1026.5, 1024.1, 6, 6, 17.0, 18.9, 'Yes', 'Yes'), ('4/9/2008', 15.6, 22.2, 22.8, 5.4, 5.8, 'W', 41, 'W', 'E', 13, 20, 96, 62, 1024.6, 1021.4, 7, 5, 16.3, 21.1, 'Yes', 'Yes'), ('4/10/2008', 13.8, 22.7, 2.2, 3.6, 10.6, 'W', 41, 'W', 'E', 15, 15, 77, 60, 1022.1, 1019.7, 5, 1, 18.7, 21.9, 'Yes', 'No'), ('4/11/2008', 14.1, 23.5, 0.0, 3.2, 8.9, 'W', 41, 'W', 'E', 15, 15, 83, 61, 1020.1, 1017.5, 4, 2, 17.1, 22.1, 'No', 'No'), ('4/12/2008', 14.0, 23.8, 0.0, 4.0, 7.8, 'W', 41, 'W', 'E', 11, 9, 79, 59, 1018.6, 1016.0, 7, 4, 17.6, 22.2, 'No', 'No'), ('4/13/2008', 15.1, 22.7, 0.0, 1.8, 6.6, 'W', 41, 'W', 'ESE', 11, 4, 81, 75, 1016.4, 1013.4, 5, 6, 17.4, 19.7, 'No', 'Yes'), ('4/14/2008', 13.2, 18.9, 11.0, 3.2, 5.2, 'W', 41, 'SSW', 'S', 19, 30, 82, 64, 1019.6, 1019.2, 7, 3, 15.9, 18.8, 'Yes', 'Yes'), ('4/15/2008', 13.8, 19.7, 2.8, 2.8, 1.7, 'W', 41, 'SW', 'S', 20, 22, 85, 71, 1025.4, 1023.9, 7, 7, 15.9, 19.0, 'Yes', 'Yes'), ('4/16/2008', 13.8, 20.9, 1.4, 4.6, 2.2, 'W', 41, 'SSW', 'SSW', 15, 20, 78, 85, 1026.4, 1024.6, 7, 8, 17.2, 16.2, 'Yes', 'Yes'), ('4/17/2008', 14.9, 19.7, 4.6, 1.4, 0.8, 'W', 41, 'SSW', 'S', 17, 13, 91, 72, 1025.1, 1023.4, 7, 7, 16.4, 19.4, 'Yes', 'Yes'), ('4/18/2008', 15.3, 20.0, 6.4, 3.2, 0.3, 'W', 41, 'W', 'SSE', 4, 15, 94, 75, 1025.4, 1023.7, 8, 7, 16.4, 19.6, 'Yes', 'Yes'), ('4/19/2008', 15.9, 21.4, 5.0, 4.8, 5.0, 'W', 41, 'SE', 'SE', 22, 24, 51, 61, 1027.2, 1026.1, 6, 7, 19.3, 19.5, 'Yes', 'Yes'), ('4/20/2008', 15.2, 19.1, 2.8, 4.0, 1.3, 'W', 41, 'ESE', 'S', 15, 6, 79, 75, 1026.6, 1023.7, 7, 6, 17.3, 18.4, 'Yes', 'Yes'), ('4/21/2008', 14.7, 19.3, 21.8, 7.5, 4.6, 'W', 41, 'SSW', 'S', 9, 19, 91, 70, 1023.2, 1021.4, 8, 7, 16.6, 19.0, 'Yes', 'Yes'), ('4/22/2008', 14.4, 20.3, 10.2, 3.6, 2.0, 'W', 41, 'SSE', 'SE', 9, 20, 90, 55, 1023.6, 1022.3, 7, 5, 16.1, 20.1, 'Yes', 'Yes'), ('4/23/2008', 14.7, 17.9, 12.6, 4.0, 0.7, 'W', 41, 'SW', 'SSE', 6, 22, 90, 89, 1024.0, 1022.1, 7, 7, 16.2, 17.2, 'Yes', 'Yes'), ('4/24/2008', 14.7, 20.0, 15.6, 1.6, 2.5, 'W', 41, 'S', 'S', 19, 20, 93, 80, 1021.3, 1018.6, 7, 7, 16.8, 19.3, 'Yes', 'Yes'), ('4/26/2008', 12.7, 24.8, 0.4, 2.6, 10.2, 'W', 41, 'W', 'E', 15, 6, 81, 38, 1011.2, 1007.0, 2, 7, 15.6, 24.6, 'No', 'No'), ('4/27/2008', 15.6, 26.1, 0.0, 5.2, 7.6, 'W', 41, 'NNW', 'N', 20, 22, 51, 28, 1005.2, 999.1, 6, 2, 20.3, 25.7, 'No', 'No'), ('4/28/2008', 11.9, 16.8, 0.0, 7.6, 8.5, 'W', 41, 'W', 'WSW', 20, 24, 46, 33, 1007.4, 1008.6, 2, 6, 13.7, 15.6, 'No', 'No'), ('4/29/2008', 8.6, 18.4, 0.0, 3.8, 10.5, 'W', 41, 'W', 'SSE', 24, 9, 54, 41, 1020.4, 1019.8, 1, 1, 11.7, 17.8, 'No', 'No'), ('4/30/2008', 8.4, 19.6, 0.0, 3.6, 9.8, 'W', 41, 'W', 'E', 15, 17, 68, 50, 1024.2, 1021.3, 1, 3, 11.6, 18.1, 'No', 'No'), ('5/1/2008', 11.6, 18.2, 0.0, 4.0, 2.7, 'W', 41, 'WNW', 'W', 11, 7, 74, 56, 1019.7, 1016.7, 7, 7, 13.4, 18.1, 'No', 'No'), ('5/2/2008', 10.8, 22.2, 0.0, 2.4, 9.1, 'W', 41, 'W', 'WSW', 19, 17, 65, 44, 1018.7, 1015.3, 1, 3, 14.5, 21.7, 'No', 'No'), ('5/3/2008', 10.9, 19.6, 0.0, 3.4, 10.5, 'W', 41, 'W', 'SSE', 19, 11, 62, 52, 1019.3, 1016.9, 1, 1, 14.1, 18.6, 'No', 'No'), ('5/4/2008', 9.4, 20.3, 0.0, 3.6, 10.3, 'W', 41, 'W', 'SE', 22, 11, 64, 47, 1021.1, 1018.3, 1, 1, 12.4, 19.4, 'No', 'No'), ('5/5/2008', 9.4, 22.3, 0.0, 2.0, 10.0, 'W', 41, 'W', 'NW', 15, 7, 71, 34, 1018.7, 1015.2, 1, 2, 12.4, 22.2, 'No', 'No'), ('5/6/2008', 11.8, 23.6, 0.0, 3.4, 3.1, 'W', 41, 'W', 'WNW', 9, 9, 74, 48, 1017.1, 1013.3, 6, 7, 13.7, 21.1, 'No', 'No'), ('5/7/2008', 13.0, 23.0, 0.0, 3.6, 9.4, 'W', 41, 'W', 'SSE', 22, 13, 57, 44, 1014.3, 1011.8, 1, 3, 16.5, 22.0, 'No', 'No'), ('5/8/2008', 11.0, 21.8, 0.0, 3.2, 10.2, 'W', 41, 'W', 'S', 24, 15, 63, 45, 1019.2, 1017.5, 1, 1, 14.0, 20.8, 'No', 'No'), ('5/9/2008', 11.0, 21.9, 0.0, 3.2, 10.1, 'W', 41, 'W', 'SE', 17, 11, 75, 60, 1021.4, 1020.2, 0, 1, 14.3, 20.6, 'No', 'No'), ('5/10/2008', 12.6, 21.3, 0.0, 3.0, 9.6, 'W', 41, 'WNW', 'E', 11, 11, 86, 67, 1022.2, 1019.6, 1, 1, 15.2, 19.3, 'No', 'No'), ('5/11/2008', 14.0, 19.4, 0.0, 1.2, 2.1, 'W', 41, 'WNW', 'SSE', 13, 15, 84, 67, 1023.1, 1021.2, 7, 7, 16.8, 18.7, 'No', 'No'), ('5/12/2008', 12.4, 19.5, 0.0, 1.6, 7.3, 'W', 41, 'W', 'E', 11, 15, 88, 63, 1023.5, 1020.5, 1, 1, 14.9, 19.2, 'No', 'No'), ('5/13/2008', 13.2, 19.7, 0.0, 1.8, 4.2, 'W', 41, 'W', 'E', 11, 9, 88, 67, 1023.4, 1021.7, 6, 7, 15.0, 18.1, 'No', 'No'), ('5/14/2008', 11.2, 20.6, 0.0, 2.0, 9.7, 'W', 41, 'W', 'ENE', 20, 19, 82, 64, 1023.8, 1020.5, 1, 1, 13.8, 20.0, 'No', 'No'), ('5/15/2008', 12.0, 21.4, 0.2, 3.2, 8.7, 'W', 41, 'W', 'E', 13, 9, 90, 60, 1022.2, 1017.8, 1, 1, 13.9, 21.3, 'No', 'Yes'), ('5/16/2008', 13.8, 23.2, 1.2, 2.2, 6.4, 'W', 41, 'WNW', 'NE', 15, 15, 78, 66, 1017.1, 1013.0, 6, 2, 15.9, 20.9, 'Yes', 'No'), ('5/17/2008', 15.2, 21.8, 0.0, 4.2, 6.9, 'W', 41, 'NNW', 'NNW', 20, 17, 52, 41, 1008.4, 1003.6, 3, 7, 19.2, 20.9, 'No', 'No'), ('5/18/2008', 8.8, 17.8, 0.0, 4.2, 9.4, 'W', 41, 'W', 'W', 19, 31, 57, 36, 1007.0, 1006.3, 1, 1, 11.6, 17.0, 'No', 'No'), ('5/19/2008', 10.7, 20.5, 0.0, 4.4, 9.9, 'W', 41, 'W', 'WNW', 22, 7, 58, 36, 1015.7, 1013.3, 1, 0, 12.5, 20.3, 'No', 'No'), ('5/20/2008', 10.3, 21.7, 0.0, 3.0, 10.0, 'W', 41, 'W', 'W', 24, 7, 64, 38, 1020.1, 1017.5, 1, 1, 13.0, 21.3, 'No', 'No'), ('5/21/2008', 11.1, 18.9, 0.0, 2.4, 6.1, 'W', 41, 'WNW', 'S', 19, 22, 74, 64, 1022.4, 1022.8, 4, 7, 13.5, 17.3, 'No', 'No'), ('5/22/2008', 11.9, 18.7, 0.0, 4.0, 7.5, 'W', 41, 'SSW', 'SSE', 20, 19, 63, 52, 1028.2, 1026.2, 1, 2, 15.1, 17.4, 'No', 'No'), ('5/23/2008', 11.0, 18.4, 0.0, 3.4, 5.4, 'W', 41, 'WNW', 'SSE', 17, 13, 76, 53, 1026.9, 1024.6, 1, 5, 12.7, 17.1, 'No', 'No'), ('5/24/2008', 11.4, 20.1, 0.0, 2.4, 9.1, 'W', 41, 'W', 'NW', 13, 2, 71, 39, 1025.4, 1022.7, 1, 1, 13.3, 19.3, 'No', 'No'), ('5/25/2008', 8.8, 18.3, 0.0, 3.6, 6.5, 'W', 41, 'W', 'ENE', 17, 11, 78, 58, 1025.1, 1022.2, 4, 3, 11.1, 16.9, 'No', 'No'), ('5/26/2008', 10.9, 21.1, 0.4, 0.4, 9.1, 'W', 41, 'W', 'ENE', 20, 13, 81, 58, 1025.9, 1022.6, 6, 2, 12.9, 19.5, 'No', 'No'), ('5/27/2008', 11.5, 22.4, 0.0, 3.2, 8.7, 'W', 41, 'W', 'E', 15, 13, 82, 71, 1024.6, 1021.8, 3, 1, 13.6, 19.1, 'No', 'No'), ('5/28/2008', 11.0, 19.2, 0.0, 1.6, 3.9, 'W', 41, 'W', 'NE', 26, 2, 80, 74, 1025.6, 1023.9, 3, 6, 12.8, 18.6, 'No', 'No'), ('5/29/2008', 11.0, 18.6, 1.0, 1.0, 4.6, 'W', 41, 'W', 'S', 19, 4, 86, 76, 1030.2, 1029.1, 3, 2, 12.7, 17.6, 'No', 'No'), ('5/30/2008', 10.9, 21.0, 0.2, 1.4, 5.6, 'W', 41, 'W', 'E', 19, 7, 87, 58, 1032.0, 1028.7, 1, 2, 12.7, 19.6, 'No', 'No'), ('5/31/2008', 10.8, 20.1, 0.0, 1.0, 9.4, 'W', 41, 'WNW', 'SSE', 17, 17, 90, 61, 1028.6, 1026.66, 1, 1, 11.7, 19.4, 'No', 'No'), ('6/1/2008', 11.6, 20.5, 0.2, 2.2, 0.3, 'W', 41, 'W', 'SE', 19, 17, 91, 74, 1029.3, 1027.0, 7, 7, 14.3, 18.7, 'No', 'Yes'), ('6/2/2008', 14.3, 17.6, 22.0, 1.8, 0.1, 'W', 41, 'W', 'W', 9, 7, 97, 90, 1027.3, 1024.8, 8, 7, 15.3, 17.1, 'Yes', 'Yes'), ('6/3/2008', 15.2, 19.1, 4.0, 0.4, 0.0, 'W', 41, 'W', 'E', 17, 22, 98, 90, 1026.4, 1024.1, 8, 8, 15.6, 16.7, 'Yes', 'Yes'), ('6/4/2008', 15.5, 18.3, 9.2, 2.4, 0.0, 'W', 41, 'SE', 'ESE', 19, 26, 87, 88, 1023.1, 1020.5, 8, 8, 17.5, 17.2, 'Yes', 'Yes'), ('6/5/2008', 15.2, 16.9, 46.4, 2.4, 0.0, 'W', 41, 'SSW', 'S', 24, 24, 82, 84, 1020.1, 1018.6, 7, 8, 16.0, 16.6, 'Yes', 'Yes'), ('6/6/2008', 14.7, 17.4, 12.4, 0.4, 1.8, 'W', 41, 'WSW', 'SSW', 15, 24, 81, 70, 1021.2, 1020.3, 7, 6, 15.1, 16.6, 'Yes', 'No'), ('6/7/2008', 11.7, 18.2, 0.0, 2.2, 8.8, 'W', 41, 'W', 'S', 19, 24, 76, 49, 1025.0, 1025.7, 1, 1, 13.3, 17.9, 'No', 'Yes'), ('6/8/2008', 12.7, 17.7, 6.0, 1.4, 0.5, 'W', 41, 'WNW', 'ESE', 17, 17, 97, 71, 1032.1, 1029.8, 8, 7, 14.1, 17.2, 'Yes', 'Yes'), ('6/9/2008', 13.0, 16.9, 3.6, 1.2, 1.2, 'W', 41, 'W', 'ESE', 13, 2, 96, 89, 1030.9, 1028.0, 7, 8, 13.9, 16.2, 'Yes', 'Yes'), ('6/10/2008', 12.4, 19.9, 1.6, 1.6, 3.9, 'W', 41, 'W', 'N', 13, 9, 98, 68, 1027.5, 1023.9, 7, 1, 13.2, 19.1, 'Yes', 'No'), ('6/11/2008', 13.2, 19.9, 0.0, 1.8, 0.0, 'W', 41, 'NNW', 'N', 6, 4, 74, 70, 1022.9, 1020.6, 7, 8, 17.3, 19.6, 'No', 'Yes'), ('6/12/2008', 13.7, 22.1, 5.4, 1.8, 6.9, 'W', 41, 'W', 'ENE', 11, 7, 97, 64, 1022.4, 1018.1, 8, 1, 14.1, 20.1, 'Yes', 'No'), ('6/13/2008', 14.0, 18.8, 0.0, 3.4, 8.6, 'W', 41, 'NW', 'WSW', 20, 26, 67, 42, 1012.2, 1011.5, 1, 2, 16.6, 16.7, 'No', 'No'), ('6/14/2008', 9.6, 14.6, 0.0, 3.8, 3.4, 'W', 41, 'W', 'SW', 30, 24, 49, 52, 1022.0, 1022.5, 5, 7, 11.2, 14.1, 'No', 'No'), ('6/15/2008', 10.6, 15.3, 0.0, 2.8, 0.1, 'W', 41, 'SSW', 'SSW', 24, 26, 75, 87, 1024.4, 1022.8, 7, 8, 13.7, 14.5, 'No', 'Yes'), ('6/16/2008', 13.3, 16.8, 7.2, 5.0, 2.4, 'W', 41, 'SSW', 'SSW', 19, 20, 86, 83, 1024.2, 1023.0, 6, 7, 15.0, 15.8, 'Yes', 'Yes'), ('6/17/2008', 13.1, 17.5, 3.4, 0.8, 1.3, 'W', 41, 'W', 'SSW', 11, 13, 88, 73, 1026.7, 1024.8, 7, 7, 14.2, 17.3, 'Yes', 'No'), ('6/18/2008', 13.6, 19.4, 0.0, 1.6, 4.1, 'W', 41, 'W', 'NE', 13, 2, 90, 69, 1025.5, 1022.1, 7, 8, 14.8, 19.2, 'No', 'No'), ('6/19/2008', 12.8, 20.3, 0.0, 2.0, 5.0, 'W', 41, 'WNW', 'ESE', 13, 13, 91, 69, 1020.3, 1017.4, 6, 7, 13.9, 18.6, 'No', 'Yes'), ('6/20/2008', 13.8, 17.9, 3.6, 0.6, 0.6, 'W', 41, 'W', 'W', 19, 19, 81, 60, 1018.3, 1016.2, 7, 7, 14.3, 17.2, 'Yes', 'Yes'), ('6/21/2008', 11.6, 18.5, 2.2, 1.8, 9.4, 'W', 41, 'W', 'WSW', 15, 17, 66, 40, 1020.7, 1018.9, 1, 1, 13.2, 18.0, 'Yes', 'No'), ('6/22/2008', 9.7, 17.3, 0.0, 3.4, 9.3, 'W', 41, 'W', 'SSW', 22, 22, 61, 54, 1023.2, 1024.0, 1, 3, 11.4, 16.3, 'No', 'No'), ('6/23/2008', 8.2, 17.1, 0.0, 3.4, 7.0, 'W', 41, 'WNW', 'WSW', 13, 13, 74, 43, 1023.7, 1020.4, 1, 7, 9.9, 17.0, 'No', 'No'), ('6/24/2008', 9.2, 19.2, 0.0, 1.8, 9.2, 'W', 41, 'W', 'WNW', 19, 9, 72, 45, 1027.0, 1023.1, 1, 1, 10.7, 18.8, 'No', 'No'), ('6/25/2008', 9.9, 19.6, 0.0, 2.8, 9.8, 'W', 41, 'W', 'WNW', 17, 6, 69, 43, 1024.6, 1020.6, 1, 0, 11.8, 19.4, 'No', 'No'), ('6/26/2008', 10.2, 20.2, 0.0, 3.2, 9.7, 'W', 41, 'WNW', 'W', 28, 28, 47, 38, 1017.0, 1016.8, 0, 1, 14.6, 19.3, 'No', 'No'), ('6/27/2008', 9.5, 19.4, 0.0, 4.4, 9.3, 'W', 41, 'W', 'WSW', 24, 15, 57, 32, 1025.9, 1023.6, 0, 0, 10.8, 18.9, 'No', 'No'), ('6/28/2008', 7.9, 18.7, 0.0, 3.0, 8.8, 'W', 41, 'W', 'SSE', 20, 9, 68, 43, 1027.6, 1024.7, 1, 1, 10.1, 18.1, 'No', 'No'), ('6/29/2008', 7.9, 21.0, 0.0, 0.8, 9.8, 'W', 41, 'WNW', 'NNW', 13, 6, 84, 42, 1024.1, 1018.8, 2, 1, 9.2, 20.8, 'No', 'No'), ('6/30/2008', 9.2, 22.1, 0.0, 3.2, 9.8, 'W', 41, 'NNW', 'NW', 19, 28, 47, 35, 1017.1, 1010.3, 1, 1, 13.8, 21.6, 'No', 'No'), ('7/1/2008', 10.3, 19.6, 0.2, 3.8, 9.5, 'W', 41, 'W', 'W', 0, 41, 45, 34, 1011.0, 1008.5, 0, 1, 13.1, 19.2, 'No', 'No'), ('7/2/2008', 10.8, 19.2, 0.0, 4.0, 9.7, 'W', 41, 'WNW', 'W', 26, 31, 55, 35, 1012.5, 1011.2, 1, 1, 14.6, 18.8, 'No', 'No'), ('7/3/2008', 9.2, 17.9, 0.0, 3.2, 9.6, 'W', 41, 'W', 'WNW', 17, 7, 63, 42, 1022.7, 1020.8, 1, 1, 10.7, 17.4, 'No', 'Yes'), ('7/4/2008', 8.2, 15.0, 1.2, 2.4, 0.4, 'W', 41, 'W', 'S', 20, 9, 84, 88, 1029.0, 1028.2, 7, 7, 9.1, 12.9, 'Yes', 'Yes'), ('7/5/2008', 9.1, 17.4, 14.2, 1.6, 2.5, 'W', 41, 'WNW', 'NE', 11, 15, 78, 48, 1031.9, 1028.9, 6, 6, 11.3, 16.8, 'Yes', 'No'), ('7/6/2008', 8.3, 18.4, 0.0, 2.2, 7.8, 'W', 41, 'W', 'SSE', 15, 4, 84, 59, 1029.2, 1025.7, 1, 3, 9.8, 17.7, 'No', 'No'), ('7/7/2008', 9.7, 19.8, 0.0, 2.2, 4.3, 'W', 41, 'W', 'N', 9, 11, 87, 55, 1024.4, 1019.7, 7, 5, 11.3, 19.3, 'No', 'No'), ('7/8/2008', 10.5, 17.2, 0.2, 1.6, 5.5, 'W', 41, 'W', 'SE', 11, 7, 80, 49, 1020.9, 1017.4, 1, 4, 12.1, 16.4, 'No', 'No'), ('7/9/2008', 6.9, 13.3, 0.0, 2.8, 4.6, 'W', 41, 'W', 'WSW', 15, 20, 57, 43, 1018.0, 1015.7, 2, 7, 9.6, 13.2, 'No', 'Yes'), ('7/10/2008', 7.2, 15.8, 1.8, 2.4, 4.9, 'W', 41, 'WNW', 'NW', 11, 26, 58, 38, 1014.6, 1010.0, 7, 3, 10.2, 15.8, 'Yes', 'No'), ('7/11/2008', 10.0, 16.5, 0.0, 4.8, 9.8, 'W', 41, 'W', 'WSW', 24, 20, 46, 27, 1016.5, 1017.0, 1, 1, 11.3, 16.1, 'No', 'No'), ('7/12/2008', 5.7, 15.9, 0.0, 3.4, 8.3, 'W', 41, 'W', 'NE', 17, 13, 67, 45, 1027.5, 1023.5, 4, 7, 7.8, 15.0, 'No', 'No'), ('7/13/2008', 7.8, 17.3, 0.0, 2.6, 0.0, 'W', 41, 'W', 'N', 4, 17, 67, 58, 1024.2, 1021.2, 8, 8, 11.5, 17.1, 'No', 'No'), ('7/14/2008', 10.1, 23.1, 0.0, 1.8, 6.1, 'W', 41, 'W', 'E', 0, 7, 80, 54, 1021.5, 1017.3, 7, 1, 12.0, 22.9, 'No', 'No'), ('7/15/2008', 9.7, 19.8, 0.0, 1.8, 9.7, 'W', 41, 'W', 'ESE', 20, 11, 81, 70, 1020.8, 1018.4, 1, 1, 11.1, 17.4, 'No', 'No'), ('7/16/2008', 8.9, 18.0, 0.0, 2.0, 9.6, 'W', 41, 'WNW', 'SSE', 13, 11, 81, 50, 1022.2, 1019.1, 1, 1, 10.8, 17.4, 'No', 'No'), ('7/17/2008', 8.2, 18.5, 0.0, 1.4, 9.0, 'W', 41, 'W', 'N', 15, 17, 84, 38, 1019.2, 1013.3, 4, 5, 10.1, 17.3, 'No', 'No'), ('7/18/2008', 8.2, 18.7, 0.0, 4.0, 8.7, 'W', 41, 'W', 'W', 13, 39, 73, 21, 1010.1, 1007.3, 1, 1, 10.1, 17.9, 'No', 'No'), ('7/19/2008', 8.1, 18.2, 0.0, 3.4, 9.5, 'W', 41, 'W', 'W', 4, 6, 53, 32, 1016.2, 1014.1, 1, 2, 10.9, 18.2, 'No', 'No'), ('7/20/2008', 10.8, 17.6, 0.0, 3.2, 0.0, 'W', 41, 'N', 'NE', 6, 4, 41, 55, 1015.4, 1008.6, 8, 8, 14.6, 16.8, 'No', 'Yes'), ('7/21/2008', 10.4, 17.5, 2.8, 1.6, 9.7, 'W', 41, 'NW', 'W', 26, 31, 56, 31, 1006.2, 1008.1, 1, 1, 13.1, 16.7, 'Yes', 'No'), ('7/22/2008', 7.2, 15.1, 0.0, 3.8, 10.0, 'W', 41, 'W', 'SSW', 19, 22, 52, 31, 1024.8, 1025.2, 0, 1, 8.8, 13.9, 'No', 'No'), ('7/23/2008', 5.5, 14.7, 0.0, 4.0, 4.0, 'W', 41, 'W', 'SSW', 22, 19, 67, 61, 1031.5, 1029.6, 6, 6, 7.0, 14.1, 'No', 'Yes'), ('7/24/2008', 6.9, 15.9, 7.0, 0.2, 1.7, 'W', 41, 'W', 'ESE', 19, 22, 95, 70, 1029.3, 1025.4, 8, 7, 10.9, 14.7, 'Yes', 'Yes'), ('7/25/2008', 9.8, 12.7, 8.8, 2.4, 0.1, 'W', 41, 'WSW', 'S', 15, 17, 93, 81, 1022.6, 1020.1, 8, 7, 10.5, 12.6, 'Yes', 'Yes'), ('7/26/2008', 6.2, 17.0, 16.2, 1.4, 8.6, 'W', 41, 'W', 'SSE', 24, 13, 79, 47, 1018.3, 1014.3, 1, 5, 8.4, 15.5, 'Yes', 'No'), ('7/27/2008', 6.3, 17.6, 0.0, 2.0, 7.6, 'W', 41, 'W', 'ESE', 11, 6, 71, 41, 1013.1, 1008.6, 2, 7, 9.1, 16.4, 'No', 'Yes'), ('7/28/2008', 7.0, 13.6, 3.8, 3.0, 3.6, 'W', 41, 'W', 'SW', 20, 31, 79, 79, 1011.3, 1011.3, 6, 8, 8.4, 10.2, 'Yes', 'Yes'), ('7/29/2008', 8.0, 15.0, 33.2, 1.4, 6.9, 'W', 41, 'W', 'SSW', 22, 20, 86, 59, 1017.2, 1015.1, 6, 6, 9.1, 13.5, 'Yes', 'No'), ('7/30/2008', 6.0, 17.0, 0.2, 2.6, 9.7, 'W', 41, 'W', 'ESE', 19, 11, 65, 43, 1016.7, 1013.7, 2, 1, 9.4, 16.2, 'No', 'No'), ('7/31/2008', 6.0, 20.3, 0.0, 3.4, 10.2, 'W', 41, 'W', 'E', 19, 11, 71, 42, 1016.6, 1011.6, 1, 2, 7.9, 18.5, 'No', 'No'), ('8/1/2008', 7.9, 20.8, 0.0, 4.6, 1.8, 'W', 41, 'WNW', 'WNW', 17, 26, 40, 46, 1004.8, 1003.3, 6, 7, 17.2, 16.8, 'No', 'No'), ('8/2/2008', 9.7, 16.8, 0.0, 4.6, 10.1, 'W', 41, 'W', 'W', 28, 24, 48, 32, 1013.2, 1013.3, 1, 1, 11.9, 16.6, 'No', 'No'), ('8/3/2008', 9.4, 18.8, 0.0, 3.6, 10.0, 'W', 41, 'W', 'W', 20, 7, 52, 34, 1020.4, 1017.7, 0, 1, 11.6, 18.7, 'No', 'No'), ('8/4/2008', 8.1, 17.2, 0.0, 3.0, 5.9, 'W', 41, 'W', 'E', 13, 13, 62, 45, 1020.4, 1017.1, 6, 6, 10.6, 15.0, 'No', 'No'), ('8/5/2008', 6.6, 16.3, 0.0, 3.4, 8.5, 'W', 41, 'W', 'SSE', 22, 13, 67, 52, 1019.1, 1016.1, 1, 5, 9.2, 16.3, 'No', 'No'), ('8/6/2008', 8.8, 15.5, 0.0, 3.4, 3.4, 'W', 41, 'W', 'SSW', 15, 13, 89, 70, 1014.9, 1015.6, 7, 7, 9.5, 14.3, 'No', 'No'), ('8/7/2008', 8.3, 16.5, 0.8, 0.4, 6.0, 'W', 41, 'W', 'NW', 20, 19, 74, 75, 1017.9, 1014.6, 1, 7, 10.9, 11.4, 'No', 'Yes'), ('8/8/2008', 8.2, 18.6, 4.6, 1.4, 5.7, 'W', 41, 'W', 'SW', 17, 19, 58, 38, 1016.4, 1016.9, 7, 5, 11.7, 18.4, 'Yes', 'No'), ('8/9/2008', 6.9, 17.3, 0.0, 4.0, 9.6, 'W', 41, 'W', 'WNW', 19, 15, 56, 37, 1021.9, 1018.1, 1, 4, 9.9, 16.4, 'No', 'No'), ('8/10/2008', 6.7, 15.6, 0.0, 3.0, 5.9, 'W', 41, 'NW', 'WNW', 19, 24, 62, 38, 1016.2, 1011.8, 2, 2, 10.5, 13.5, 'No', 'No'), ('8/11/2008', 7.0, 15.9, 0.4, 3.6, 10.7, 'W', 41, 'W', 'W', 33, 20, 46, 35, 1016.0, 1015.4, 1, 4, 9.4, 15.4, 'No', 'No'), ('8/12/2008', 6.8, 16.3, 0.0, 3.0, 10.0, 'W', 41, 'W', 'W', 19, 30, 50, 28, 1021.7, 1018.8, 1, 1, 10.7, 15.8, 'No', 'No'), ('8/13/2008', 8.4, 17.4, 0.0, 4.0, 10.5, 'W', 41, 'WSW', 'ESE', 22, 15, 49, 34, 1023.0, 1021.9, 1, 2, 12.2, 16.0, 'No', 'No'), ('8/14/2008', 7.2, 18.5, 0.0, 4.0, 10.4, 'W', 41, 'W', 'WSW', 22, 26, 51, 28, 1021.1, 1015.6, 0, 1, 10.2, 18.0, 'No', 'No'), ('8/15/2008', 9.4, 18.8, 0.0, 4.6, 10.7, 'W', 41, 'W', 'W', 22, 31, 49, 33, 1013.4, 1010.2, 1, 1, 12.4, 18.1, 'No', 'No'), ('8/16/2008', 10.5, 18.0, 0.0, 4.0, 9.2, 'W', 41, 'W', 'SE', 22, 15, 48, 42, 1011.8, 1010.5, 1, 4, 13.2, 16.6, 'No', 'No'), ('8/17/2008', 6.9, 16.4, 0.0, 4.6, 10.4, 'W', 41, 'W', 'SSE', 17, 15, 45, 35, 1021.9, 1021.8, 1, 1, 10.4, 15.5, 'No', 'No'), ('8/18/2008', 5.6, 15.8, 0.0, 3.4, 7.6, 'W', 41, 'W', 'SSW', 20, 19, 59, 33, 1024.9, 1021.2, 6, 7, 9.2, 15.3, 'No', 'No'), ('8/19/2008', 5.3, 17.6, 0.6, 1.8, 10.8, 'W', 41, 'W', 'ENE', 22, 15, 65, 32, 1028.8, 1025.4, 1, 5, 9.5, 17.5, 'No', 'No'), ('8/20/2008', 8.2, 19.5, 0.0, 3.8, 7.4, 'W', 41, 'E', 'W', 2, 4, 58, 35, 1026.6, 1023.2, 7, 7, 12.6, 19.2, 'No', 'No'), ('8/21/2008', 9.4, 20.2, 0.0, 3.2, 1.1, 'W', 41, 'W', 'ENE', 7, 11, 58, 44, 1022.5, 1017.1, 8, 7, 12.0, 18.2, 'No', 'Yes'), ('8/22/2008', 10.2, 11.9, 2.6, 3.4, 0.0, 'W', 41, 'W', 'SSW', 15, 17, 90, 87, 1016.1, 1015.5, 8, 8, 10.5, 10.5, 'Yes', 'Yes'), ('8/23/2008', 7.3, 14.8, 20.8, 1.6, 5.9, 'W', 41, 'SSW', 'S', 24, 28, 65, 53, 1022.8, 1024.1, 7, 7, 11.2, 13.4, 'Yes', 'No'), ('8/24/2008', 5.5, 17.3, 0.0, 3.0, 10.4, 'W', 41, 'W', 'SSE', 24, 22, 63, 47, 1029.6, 1027.9, 1, 2, 9.8, 16.6, 'No', 'No'), ('8/25/2008', 8.2, 16.4, 0.0, 3.6, 7.1, 'W', 41, 'W', 'NE', 15, 19, 76, 48, 1029.9, 1024.8, 7, 5, 11.1, 16.0, 'No', 'No'), ('8/26/2008', 8.5, 21.5, 0.0, 2.6, 9.3, 'W', 41, 'WNW', 'E', 19, 15, 78, 51, 1023.4, 1019.3, 2, 3, 11.1, 18.7, 'No', 'No'), ('8/28/2008', 8.8, 16.9, 2.4, 3.2, 8.5, 'W', 41, 'W', 'S', 13, 20, 85, 59, 1028.0, 1025.3, 3, 5, 12.0, 15.8, 'Yes', 'No'), ('8/29/2008', 8.7, 18.2, 0.0, 4.2, 10.1, 'W', 41, 'WNW', 'SSE', 19, 20, 70, 62, 1025.7, 1022.3, 2, 4, 12.5, 16.1, 'No', 'No'), ('8/30/2008', 8.1, 16.0, 0.0, 4.8, 6.3, 'W', 41, 'W', 'ENE', 13, 17, 82, 65, 1023.4, 1019.1, 5, 7, 12.1, 15.7, 'No', 'Yes'), ('8/31/2008', 12.1, 19.2, 12.0, 4.8, 0.3, 'W', 41, 'NNE', 'N', 15, 22, 91, 71, 1011.2, 1009.555, 7, 7, 15.3, 19.1, 'Yes', 'No'), ('9/1/2008', 10.4, 21.0, 0.2, 4.0, 11.3, 'W', 41, 'W', 'E', 7, 19, 54, 41, 1022.9, 1020.8, 0, 0, 15.0, 19.0, 'No', 'No'), ('9/2/2008', 8.7, 20.6, 0.0, 3.0, 11.1, 'W', 41, 'W', 'ESE', 19, 17, 56, 39, 1026.1, 1024.4, 0, 1, 14.1, 18.9, 'No', 'No'), ('9/3/2008', 9.7, 17.9, 0.0, 3.4, 6.2, 'W', 41, 'SSE', 'SSE', 22, 30, 67, 64, 1032.6, 1032.4, 7, 7, 15.8, 16.0, 'No', 'No'), ('9/4/2008', 13.5, 17.1, 0.4, 4.6, 0.7, 'W', 41, 'SE', 'ESE', 20, 26, 55, 64, 1034.2, 1031.0, 7, 8, 15.4, 15.8, 'No', 'Yes'), ('9/5/2008', 13.1, 15.7, 1.6, 4.4, 0.0, 'W', 41, 'ESE', 'ESE', 28, 20, 76, 88, 1024.9, 1020.8, 8, 8, 15.6, 14.2, 'Yes', 'Yes'), ('9/6/2008', 11.8, 14.2, 62.2, 4.8, 0.0, 'W', 41, 'S', 'S', 22, 30, 92, 88, 1014.8, 1013.1, 8, 8, 13.0, 12.3, 'Yes', 'Yes'), ('9/7/2008', 9.5, 19.0, 21.6, 0.0, 9.4, 'W', 41, 'W', 'ESE', 15, 15, 69, 51, 1016.4, 1014.1, 2, 6, 14.1, 18.3, 'Yes', 'No'), ('9/8/2008', 9.4, 17.5, 0.0, 3.4, 9.9, 'W', 41, 'W', 'SSE', 15, 24, 68, 51, 1019.5, 1018.2, 1, 2, 13.9, 16.4, 'No', 'No'), ('9/9/2008', 8.4, 16.4, 0.0, 6.2, 10.9, 'W', 41, 'WSW', 'SE', 13, 20, 49, 43, 1025.0, 1021.9, 1, 1, 12.6, 15.4, 'No', 'No'), ('9/10/2008', 7.0, 16.8, 0.0, 4.0, 10.7, 'W', 41, 'W', 'ESE', 17, 19, 66, 44, 1022.7, 1019.1, 1, 1, 12.4, 16.6, 'No', 'No'), ('9/11/2008', 7.1, 17.7, 0.0, 3.0, 10.3, 'W', 41, 'WNW', 'ENE', 15, 20, 72, 60, 1019.2, 1014.2, 1, 2, 12.3, 16.8, 'No', 'No'), ('9/12/2008', 8.7, 24.3, 0.0, 3.6, 10.8, 'W', 41, 'W', 'NE', 11, 20, 53, 35, 1014.9, 1010.8, 1, 1, 14.8, 21.9, 'No', 'No'), ('9/13/2008', 14.8, 30.6, 0.0, 7.4, 10.6, 'W', 41, 'E', 'NE', 4, 7, 40, 47, 1014.1, 1010.4, 3, 1, 24.3, 25.0, 'No', 'Yes'), ('9/14/2008', 17.2, 23.5, 3.6, 9.6, 2.8, 'W', 41, 'N', 'NW', 15, 7, 82, 79, 1011.8, 1007.4, 8, 6, 18.0, 19.3, 'Yes', 'Yes'), ('9/15/2008', 16.9, 27.9, 4.0, 3.0, 11.0, 'W', 41, 'N', 'NW', 28, 39, 58, 23, 1009.7, 1003.4, 1, 1, 22.5, 27.8, 'Yes', 'No'), ('9/16/2008', 12.3, 19.8, 0.0, 10.6, 11.3, 'W', 41, 'W', 'WSW', 39, 19, 30, 25, 1015.8, 1016.5, 1, 1, 14.3, 19.5, 'No', 'No'), ('9/17/2008', 10.7, 16.3, 0.0, 7.2, 4.6, 'W', 41, 'S', 'SE', 15, 11, 60, 58, 1026.4, 1023.4, 6, 6, 14.8, 15.0, 'No', 'No'), ('9/18/2008', 9.4, 19.4, 0.0, 3.6, 10.1, 'W', 41, 'W', 'NE', 6, 22, 63, 61, 1021.4, 1016.2, 1, 4, 15.7, 18.3, 'No', 'No'), ('9/19/2008', 14.6, 25.8, 0.0, 4.2, 10.4, 'W', 41, 'W', 'NE', 0, 20, 67, 47, 1015.8, 1011.0, 1, 0, 19.4, 24.0, 'No', 'No'), ('9/20/2008', 18.8, 32.8, 0.0, 7.6, 10.9, 'W', 41, 'N', 'W', 6, 26, 46, 17, 1010.1, 1005.9, 0, 6, 25.8, 31.6, 'No', 'No'), ('9/21/2008', 15.8, 21.6, 0.0, 9.0, 10.9, 'W', 41, 'E', 'NE', 9, 19, 73, 61, 1019.8, 1014.4, 4, 0, 18.0, 20.7, 'No', 'No'), ('9/22/2008', 13.2, 29.8, 0.0, 4.4, 7.5, 'W', 41, 'W', 'NW', 6, 37, 64, 33, 1011.6, 1007.0, 0, 7, 19.1, 27.6, 'No', 'Yes'), ('9/23/2008', 15.6, 17.0, 2.6, 10.4, 3.0, 'W', 41, 'SSW', 'SSE', 17, 24, 88, 60, 1015.5, 1018.0, 8, 5, 15.6, 16.9, 'Yes', 'Yes'), ('9/24/2008', 9.7, 18.6, 2.2, 2.4, 11.1, 'W', 41, 'WNW', 'E', 11, 19, 60, 50, 1030.3, 1028.6, 3, 1, 16.2, 17.5, 'Yes', 'No'), ('9/25/2008', 10.3, 18.6, 0.0, 4.0, 10.9, 'W', 41, 'W', 'E', 6, 19, 67, 54, 1031.6, 1027.8, 1, 1, 16.0, 18.2, 'No', 'No'), ('9/26/2008', 11.3, 22.2, 0.0, 6.2, 11.4, 'W', 41, 'ESE', 'NE', 4, 11, 56, 53, 1024.3, 1018.4, 1, 5, 17.9, 21.6, 'No', 'No'), ('9/27/2008', 14.0, 25.4, 0.0, 5.6, 11.4, 'W', 41, 'S', 'E', 7, 9, 67, 62, 1021.6, 1015.7, 4, 1, 20.4, 21.4, 'No', 'No'), ('9/28/2008', 19.8, 32.9, 0.0, 6.6, 8.4, 'W', 41, 'WNW', 'SSE', 17, 28, 35, 62, 1009.8, 1007.1, 2, 2, 25.4, 21.5, 'No', 'No'), ('9/29/2008', 13.5, 21.8, 0.0, 6.6, 7.1, 'W', 41, 'SW', 'SE', 19, 24, 42, 63, 1013.8, 1015.6, 1, 7, 19.4, 16.1, 'No', 'No'), ('9/30/2008', 11.9, 19.2, 0.8, 6.4, 11.1, 'W', 41, 'W', 'NE', 6, 15, 61, 48, 1020.3, 1016.777, 2, 1, 16.5, 19.0, 'No', 'No'), ('10/1/2008', 12.6, 24.7, 0.0, 5.2, 10.6, 'W', 41, 'WNW', 'NE', 9, 22, 70, 69, 1020.9, 1015.7, 6, 1, 19.0, 20.5, 'No', 'No'), ('10/2/2008', 18.9, 31.1, 0.0, 6.6, 10.0, 'W', 41, 'NE', 'NE', 4, 19, 44, 39, 1016.9, 1013.5, 3, 1, 24.7, 29.7, 'No', 'No'), ('10/3/2008', 22.5, 34.8, 0.0, 8.6, 9.8, 'W', 41, 'WNW', 'W', 15, 11, 41, 20, 1014.8, 1010.3, 1, 7, 29.6, 33.9, 'No', 'Yes'), ('10/4/2008', 17.5, 19.4, 9.6, 10.4, 0.0, 'W', 41, 'ESE', 'NE', 13, 9, 89, 88, 1015.2, 1012.9, 7, 8, 18.9, 19.0, 'Yes', 'Yes'), ('10/5/2008', 14.6, 19.1, 3.4, 1.0, 0.0, 'W', 41, 'SSW', 'S', 11, 11, 93, 86, 1018.4, 1015.3, 8, 8, 14.9, 16.0, 'Yes', 'Yes'), ('10/6/2008', 14.9, 22.8, 1.8, 2.0, 3.3, 'W', 41, 'SSW', 'ENE', 15, 22, 85, 71, 1009.2, 1003.9, 8, 7, 18.5, 20.2, 'Yes', 'No'), ('10/7/2008', 9.7, 20.6, 0.4, 3.4, 11.7, 'W', 41, 'W', 'E', 22, 24, 51, 42, 1017.7, 1014.4, 1, 1, 12.8, 17.2, 'No', 'No'), ('10/8/2008', 10.9, 19.7, 0.0, 4.8, 10.0, 'W', 41, 'W', 'E', 19, 15, 53, 47, 1018.8, 1018.6, 4, 1, 14.0, 18.4, 'No', 'No'), ('10/9/2008', 10.5, 19.9, 0.0, 5.4, 11.7, 'W', 41, 'W', 'ESE', 17, 22, 56, 58, 1026.2, 1025.7, 1, 1, 15.8, 19.2, 'No', 'No'), ('10/10/2008', 12.6, 21.5, 0.0, 6.0, 10.7, 'W', 41, 'WNW', 'E', 11, 20, 76, 57, 1029.0, 1025.4, 3, 3, 16.9, 20.5, 'No', 'No'), ('10/11/2008', 14.6, 22.3, 0.0, 6.6, 7.2, 'W', 41, 'W', 'E', 6, 22, 82, 65, 1027.4, 1024.3, 5, 3, 16.0, 20.0, 'No', 'No'), ('10/12/2008', 14.2, 22.5, 0.0, 3.6, 10.6, 'W', 41, 'W', 'E', 11, 28, 76, 69, 1025.0, 1021.8, 1, 1, 18.6, 20.8, 'No', 'No'), ('10/13/2008', 16.1, 29.2, 0.0, 7.0, 9.2, 'W', 41, 'W', 'NE', 6, 24, 72, 43, 1021.4, 1016.6, 2, 2, 20.2, 27.7, 'No', 'No'), ('10/14/2008', 16.6, 21.0, 0.6, 9.2, 2.3, 'W', 41, 'SSW', 'E', 20, 20, 89, 84, 1021.7, 1016.0, 8, 7, 16.8, 17.6, 'No', 'Yes'), ('10/15/2008', 15.1, 18.9, 9.0, 3.2, 5.0, 'W', 41, 'SSE', 'SE', 20, 17, 63, 55, 1022.4, 1021.2, 7, 8, 15.9, 18.1, 'Yes', 'No'), ('10/16/2008', 11.8, 22.1, 0.0, 4.2, 11.4, 'W', 41, 'W', 'E', 7, 19, 64, 42, 1025.5, 1023.4, 1, 1, 16.6, 20.3, 'No', 'No'), ('10/17/2008', 12.9, 24.9, 0.0, 5.8, 11.7, 'W', 41, 'W', 'ENE', 7, 20, 71, 49, 1024.2, 1021.0, 1, 2, 17.6, 22.4, 'No', 'No'), ('10/18/2008', 16.7, 23.2, 0.0, 7.4, 10.3, 'W', 41, 'S', 'E', 4, 24, 77, 82, 1025.4, 1022.0, 5, 2, 18.6, 19.7, 'No', 'No'), ('10/19/2008', 16.5, 26.8, 0.0, 7.8, 10.8, 'W', 41, 'W', 'NE', 6, 9, 64, 48, 1022.3, 1018.5, 1, 2, 21.3, 26.6, 'No', 'No'), ('10/20/2008', 17.1, 22.2, 0.0, 8.0, 5.7, 'W', 41, 'SSW', 'SE', 20, 20, 76, 55, 1022.3, 1019.3, 7, 1, 18.1, 21.8, 'No', 'Yes'), ('10/21/2008', 14.5, 19.2, 1.8, 5.2, 8.4, 'W', 41, 'SSW', 'SSE', 26, 35, 68, 59, 1020.9, 1019.6, 6, 7, 16.8, 18.8, 'Yes', 'Yes'), ('10/22/2008', 9.9, 14.3, 12.6, 6.0, 2.3, 'W', 41, 'WSW', 'S', 19, 24, 87, 74, 1022.1, 1021.9, 7, 7, 10.3, 12.4, 'Yes', 'Yes'), ('10/23/2008', 7.9, 15.7, 11.4, 4.2, 5.0, 'W', 41, 'SW', 'S', 24, 26, 71, 75, 1023.2, 1022.5, 6, 7, 11.9, 14.1, 'Yes', 'Yes'), ('10/24/2008', 9.0, 20.2, 2.0, 2.4, 10.2, 'W', 41, 'WNW', 'E', 15, 17, 66, 51, 1023.2, 1019.0, 6, 6, 14.4, 18.2, 'Yes', 'No'), ('10/25/2008', 12.3, 24.0, 0.0, 4.8, 11.5, 'W', 41, 'W', 'E', 17, 19, 66, 47, 1018.3, 1015.1, 1, 1, 17.3, 22.2, 'No', 'No'), ('10/26/2008', 14.4, 24.4, 0.0, 8.0, 8.7, 'W', 41, 'ESE', 'NNE', 6, 19, 58, 57, 1016.8, 1013.4, 6, 7, 20.2, 23.6, 'No', 'No'), ('10/27/2008', 19.8, 33.6, 0.0, 7.6, 11.8, 'W', 41, 'E', 'NE', 6, 20, 55, 38, 1015.2, 1010.8, 2, 1, 23.7, 29.8, 'No', 'No'), ('10/28/2008', 17.6, 21.9, 0.0, 11.4, 5.7, 'W', 41, 'S', 'SSE', 11, 22, 67, 70, 1020.8, 1019.9, 5, 8, 20.8, 20.5, 'No', 'Yes'), ('10/29/2008', 16.8, 17.3, 6.2, 4.6, 0.0, 'W', 41, 'ESE', 'SE', 11, 13, 93, 91, 1024.3, 1023.8, 8, 8, 17.2, 16.7, 'Yes', 'Yes'), ('10/30/2008', 15.1, 25.8, 7.6, 1.2, 3.7, 'W', 41, 'W', 'NE', 9, 20, 92, 70, 1022.6, 1016.7, 8, 6, 17.0, 23.5, 'Yes', 'No'), ('10/31/2008', 16.9, 35.0, 0.2, 3.2, 5.0, 'W', 41, 'N', 'WNW', 17, 26, 53, 24, 1010.0, 1005.3, 6, 7, 25.6, 34.6, 'No', 'No'), ('11/1/2008', 18.0, 21.2, 0.4, 10.2, 2.4, 'W', 41, 'S', 'SSE', 19, 24, 73, 64, 1021.9, 1022.9, 7, 7, 18.9, 20.4, 'No', 'No'), ('11/2/2008', 17.5, 23.1, 0.8, 4.6, 0.2, 'W', 41, 'W', 'NE', 11, 17, 72, 60, 1024.9, 1021.0, 7, 7, 18.3, 20.0, 'No', 'Yes'), ('11/3/2008', 17.2, 30.3, 2.8, 3.4, 10.3, 'W', 41, 'WNW', 'W', 22, 24, 62, 35, 1009.7, 1006.0, 2, 4, 23.1, 28.6, 'Yes', 'No'), ('11/4/2008', 15.5, 19.0, 0.2, 7.8, 6.2, 'W', 41, 'S', 'SSE', 22, 31, 59, 62, 1015.0, 1015.9, 7, 6, 17.5, 17.8, 'No', 'No'), ('11/5/2008', 14.5, 21.0, 0.0, 7.8, 5.0, 'W', 41, 'W', 'NE', 4, 20, 59, 60, 1015.5, 1010.6, 6, 8, 18.2, 20.1, 'No', 'No'), ('11/6/2008', 15.2, 30.3, 0.0, 6.0, 10.3, 'W', 41, 'W', 'ENE', 9, 17, 58, 45, 1009.6, 1006.7, 5, 7, 21.0, 25.0, 'No', 'No'), ('11/7/2008', 16.0, 24.1, 0.0, 8.4, 4.1, 'W', 41, 'WNW', 'E', 15, 13, 61, 60, 1014.5, 1011.1, 6, 8, 18.7, 21.3, 'No', 'No'), ('11/8/2008', 18.4, 25.2, 0.2, 5.2, 0.2, 'W', 41, 'NNW', 'WSW', 24, 17, 62, 47, 1001.8, 1003.8, 7, 8, 22.1, 22.8, 'No', 'No'), ('11/9/2008', 16.6, 23.0, 0.4, 4.4, 11.0, 'W', 41, 'W', 'E', 13, 20, 46, 60, 1017.2, 1017.9, 1, 2, 20.7, 21.5, 'No', 'No'), ('11/10/2008', 17.4, 23.3, 0.0, 8.0, 8.1, 'W', 41, 'E', 'E', 2, 20, 63, 56, 1023.5, 1021.9, 5, 1, 21.9, 22.2, 'No', 'No'), ('11/11/2008', 15.9, 23.1, 0.0, 5.2, 9.9, 'W', 41, 'W', 'E', 0, 19, 66, 49, 1023.9, 1020.9, 3, 2, 20.5, 22.3, 'No', 'No'), ('11/12/2008', 16.4, 24.6, 0.0, 6.6, 10.7, 'W', 41, 'NNW', 'ENE', 6, 22, 69, 54, 1020.1, 1017.1, 7, 1, 20.5, 24.0, 'No', 'No'), ('11/13/2008', 19.0, 24.9, 0.0, 8.0, 11.9, 'W', 41, 'ENE', 'E', 13, 19, 61, 65, 1019.3, 1016.0, 3, 3, 23.4, 24.2, 'No', 'No'), ('11/14/2008', 19.2, 27.0, 0.0, 10.6, 9.1, 'W', 41, 'ENE', 'NE', 13, 22, 65, 57, 1013.8, 1010.6, 5, 5, 24.3, 26.1, 'No', 'Yes'), ('11/15/2008', 18.5, 23.1, 6.6, 9.4, 2.4, 'W', 41, 'SSE', 'SE', 17, 19, 92, 73, 1013.6, 1012.1, 8, 7, 18.6, 21.5, 'Yes', 'Yes'), ('11/16/2008', 17.2, 22.4, 1.2, 3.4, 4.0, 'W', 41, 'S', 'SE', 20, 28, 75, 64, 1016.4, 1016.7, 7, 7, 19.1, 19.4, 'Yes', 'No'), ('11/17/2008', 15.5, 20.9, 0.0, 6.8, 1.4, 'W', 41, 'E', 'NE', 4, 15, 60, 50, 1019.8, 1017.5, 7, 7, 18.8, 20.0, 'No', 'No'), ('11/18/2008', 16.2, 23.4, 0.0, 4.0, 8.3, 'W', 41, 'NNE', 'NE', 22, 24, 60, 60, 1017.0, 1013.7, 7, 8, 20.6, 21.6, 'No', 'Yes'), ('11/19/2008', 17.0, 22.1, 6.2, 7.8, 1.0, 'W', 41, 'NNE', 'E', 9, 20, 91, 78, 1011.4, 1008.2, 8, 8, 18.4, 20.9, 'Yes', 'Yes'), ('11/20/2008', 17.3, 27.6, 29.4, 4.6, 7.5, 'W', 41, 'WNW', 'N', 15, 13, 70, 59, 1001.1, 997.5, 3, 5, 22.0, 26.7, 'Yes', 'No'), ('11/21/2008', 16.7, 27.7, 0.2, 7.0, 11.8, 'W', 41, 'WSW', 'E', 19, 31, 34, 46, 1001.2, 996.4, 1, 3, 22.1, 23.7, 'No', 'No'), ('11/22/2008', 17.9, 20.6, 0.0, 10.0, 9.8, 'W', 41, 'WNW', 'E', 31, 19, 49, 30, 990.2, 991.4, 3, 6, 20.3, 17.2, 'No', 'No'), ('11/23/2008', 12.2, 19.7, 0.2, 9.8, 2.1, 'W', 41, 'WNW', 'SSW', 19, 26, 50, 55, 986.7, 991.0, 7, 5, 13.8, 18.4, 'No', 'Yes'), ('11/24/2008', 13.6, 22.3, 2.4, 5.0, 10.5, 'W', 41, 'SSW', 'SSE', 19, 20, 47, 49, 1003.5, 1005.1, 1, 4, 19.7, 20.7, 'Yes', 'No'), ('11/25/2008', 15.5, 21.8, 0.0, 5.6, 9.4, 'W', 41, 'SSW', 'SSE', 15, 24, 62, 63, 1015.6, 1015.3, 5, 3, 18.5, 19.3, 'No', 'No'), ('11/26/2008', 16.4, 21.8, 0.0, 7.6, 0.1, 'W', 41, 'E', 'E', 7, 19, 55, 55, 1016.6, 1014.1, 7, 8, 18.5, 19.2, 'No', 'No'), ('11/27/2008', 15.9, 23.6, 0.0, 5.0, 10.5, 'W', 41, 'NNE', 'NE', 17, 26, 58, 64, 1012.7, 1008.9, 7, 1, 21.8, 22.7, 'No', 'No'), ('11/28/2008', 19.5, 24.6, 0.2, 7.8, 0.7, 'W', 41, 'NW', 'N', 24, 17, 71, 75, 1005.0, 1003.9, 8, 7, 22.9, 22.2, 'No', 'Yes'), ('11/29/2008', 19.3, 23.3, 10.8, 2.6, 6.9, 'W', 41, 'S', 'S', 13, 24, 92, 79, 1002.2, 1002.0, 7, 7, 20.3, 19.8, 'Yes', 'Yes'), ('11/30/2008', 15.0, 24.9, 11.2, 4.8, 12.3, 'W', 41, 'SSW', 'E', 13, 19, 64, 55, 1009.9, 1007.2, 2, 1, 19.8, 21.4, 'Yes', 'No'), ('12/1/2008', 17.6, 31.3, 0.0, 7.6, 10.9, 'W', 41, 'ENE', 'WNW', 2, 24, 29, 21, 1009.1, 1004.6, 3, 7, 24.9, 30.8, 'No', 'No'), ('12/2/2008', 16.6, 23.8, 0.0, 12.0, 12.9, 'W', 41, 'W', 'E', 6, 26, 65, 65, 1011.1, 1007.2, 1, 1, 20.8, 23.4, 'No', 'No'), ('12/3/2008', 18.4, 33.2, 0.0, 8.0, 8.0, 'W', 41, 'W', 'W', 13, 19, 67, 19, 1007.7, 1005.6, 7, 5, 22.5, 32.3, 'No', 'No'), ('12/4/2008', 18.4, 21.8, 0.0, 10.0, 2.2, 'W', 41, 'ESE', 'E', 20, 22, 59, 57, 1020.2, 1018.5, 8, 6, 19.6, 21.5, 'No', 'No'), ('12/5/2008', 19.3, 27.0, 0.0, 4.8, 6.7, 'W', 41, 'N', 'E', 15, 24, 78, 70, 1015.0, 1008.6, 8, 5, 20.9, 24.1, 'No', 'No'), ('12/6/2008', 20.8, 34.8, 0.0, 6.4, 9.8, 'W', 41, 'W', 'SSE', 13, 20, 57, 56, 1006.9, 1004.1, 7, 6, 27.0, 28.8, 'No', 'No'), ('12/7/2008', 20.0, 26.1, 0.0, 7.6, 4.9, 'W', 41, 'W', 'SE', 11, 20, 81, 78, 1007.9, 1008.4, 8, 7, 21.1, 21.7, 'No', 'Yes'), ('12/8/2008', 18.2, 22.3, 6.8, 4.4, 6.3, 'W', 41, 'E', 'E', 19, 31, 74, 72, 1014.3, 1010.9, 7, 6, 20.3, 21.9, 'Yes', 'Yes'), ('12/9/2008', 17.4, 25.9, 1.8, 5.4, 9.9, 'W', 41, 'W', 'NE', 7, 17, 81, 60, 1011.2, 1006.3, 3, 6, 19.5, 24.9, 'Yes', 'No'), ('12/10/2008', 19.5, 23.4, 0.0, 9.4, 5.2, 'W', 41, 'S', 'SSE', 35, 30, 71, 66, 1007.1, 1009.6, 3, 8, 21.9, 21.7, 'No', 'Yes'), ('12/11/2008', 17.2, 19.9, 3.4, 4.6, 0.0, 'W', 41, 'ESE', 'ESE', 15, 26, 90, 58, 1013.8, 1015.0, 8, 8, 17.5, 19.7, 'Yes', 'Yes'), ('12/12/2008', 17.4, 24.5, 3.6, 4.0, 0.0, 'W', 41, 'ENE', 'ENE', 13, 30, 85, 92, 1015.8, 1009.9, 8, 8, 17.6, 18.4, 'Yes', 'Yes'), ('12/13/2008', 17.0, 32.9, 28.2, 4.8, 7.5, 'W', 41, 'N', 'W', 24, 37, 82, 25, 995.0, 990.3, 6, 4, 24.5, 32.5, 'Yes', 'No'), ('12/14/2008', 19.2, 25.4, 0.0, 12.0, 12.7, 'W', 41, 'W', 'WSW', 33, 44, 42, 32, 996.5, 997.4, 1, 5, 21.5, 23.9, 'No', 'No'), ('12/15/2008', 16.7, 23.8, 0.0, 9.8, 12.1, 'W', 41, 'S', 'SE', 24, 20, 39, 43, 1006.8, 1007.9, 5, 1, 20.9, 22.8, 'No', 'No'), ('12/16/2008', 15.0, 24.1, 0.0, 6.8, 13.0, 'W', 41, 'NNW', 'NE', 13, 20, 58, 48, 1013.1, 1010.1, 1, 1, 21.0, 23.4, 'No', 'No'), ('12/17/2008', 17.7, 26.0, 0.0, 9.2, 9.6, 'W', 41, 'WNW', 'E', 6, 17, 68, 73, 1011.9, 1008.0, 1, 6, 22.3, 23.1, 'No', 'No'), ('12/18/2008', 19.3, 27.4, 0.0, 4.8, 8.4, 'W', 41, 'WNW', 'E', 13, 17, 65, 68, 1005.0, 1001.2, 2, 6, 23.1, 24.0, 'No', 'No'), ('12/19/2008', 17.3, 26.4, 0.6, 10.2, 12.2, 'W', 41, 'WNW', 'SE', 7, 30, 67, 58, 1005.9, 1007.8, 2, 6, 21.6, 21.2, 'No', 'No'), ('12/20/2008', 15.7, 20.4, 0.0, 10.6, 4.6, 'W', 41, 'S', 'SSE', 26, 15, 57, 69, 1019.2, 1019.3, 5, 7, 18.4, 18.2, 'No', 'No'), ('12/21/2008', 14.3, 22.1, 0.4, 5.2, 12.0, 'W', 41, 'NNW', 'E', 2, 20, 60, 50, 1022.0, 1019.9, 4, 1, 19.6, 21.4, 'No', 'No'), ('12/22/2008', 15.9, 24.1, 0.0, 7.2, 12.1, 'W', 41, 'NNE', 'NE', 22, 26, 56, 57, 1018.8, 1014.8, 1, 1, 22.1, 22.9, 'No', 'No'), ('12/23/2008', 19.0, 26.9, 0.0, 10.8, 6.5, 'W', 41, 'E', 'ENE', 11, 9, 60, 56, 1009.3, 1008.4, 6, 7, 23.8, 26.0, 'No', 'No'), ('12/24/2008', 18.7, 20.7, 0.4, 4.8, 0.0, 'W', 41, 'S', 'SSE', 17, 6, 77, 78, 1013.3, 1012.6, 8, 8, 19.6, 19.7, 'No', 'No'), ('12/25/2008', 16.4, 23.3, 0.0, 0.8, 7.2, 'W', 41, 'E', 'E', 7, 19, 73, 60, 1014.5, 1013.5, 7, 3, 20.7, 22.8, 'No', 'No'), ('12/26/2008', 19.1, 26.0, 0.0, 4.0, 10.0, 'W', 41, 'ESE', 'NE', 4, 22, 75, 71, 1013.9, 1010.7, 7, 1, 23.1, 25.4, 'No', 'No'), ('12/27/2008', 20.5, 27.2, 0.0, 7.2, 0.7, 'W', 41, 'E', 'NE', 9, 13, 79, 70, 1009.0, 1005.0, 7, 8, 24.5, 26.2, 'No', 'Yes'), ('12/28/2008', 19.7, 28.3, 7.0, 6.0, 12.1, 'W', 41, 'W', 'E', 4, 20, 72, 63, 1006.6, 1003.2, 1, 5, 23.4, 26.5, 'Yes', 'No'), ('12/29/2008', 20.7, 24.9, 0.0, 8.0, 7.2, 'W', 41, 'SSE', 'SE', 28, 15, 72, 68, 1004.8, 1003.7, 2, 6, 22.6, 22.4, 'No', 'Yes'), ('12/30/2008', 18.2, 27.6, 2.0, 5.6, 10.9, 'W', 41, 'W', 'E', 9, 26, 81, 72, 1004.3, 999.3, 6, 5, 20.9, 23.8, 'Yes', 'No'), ('12/31/2008', 19.2, 31.5, 0.0, 7.4, 13.1, 'W', 41, 'W', 'E', 19, 20, 37, 42, 1002.7, 1002.4, 0, 0, 24.7, 25.3, 'No', 'No'), ('1/1/2009', 18.4, 34.7, 0.0, 9.8, 12.9, 'W', 41, 'W', 'NNW', 11, 17, 73, 22, 1005.5, 1000.7, 4, 6, 22.0, 34.3, 'No', 'No'), ('1/2/2009', 18.8, 22.7, 0.0, 11.0, 5.9, 'W', 41, 'E', 'ESE', 11, 33, 62, 57, 1012.8, 1013.8, 6, 7, 20.1, 20.8, 'No', 'No'), ('1/3/2009', 17.0, 23.0, 0.0, 9.0, 0.5, 'W', 41, 'ESE', 'ENE', 13, 15, 58, 49, 1021.6, 1019.4, 8, 8, 18.8, 21.4, 'No', 'No'), ('1/4/2009', 18.7, 24.6, 0.0, 5.4, 11.3, 'W', 41, 'NNE', 'NE', 13, 31, 59, 58, 1018.6, 1015.2, 2, 1, 23.0, 24.1, 'No', 'No'), ('1/5/2009', 19.5, 27.9, 0.0, 10.0, 12.2, 'W', 41, 'ESE', 'ENE', 6, 13, 66, 60, 1013.2, 1008.9, 4, 4, 23.4, 26.2, 'No', 'No'), ('1/6/2009', 20.2, 28.3, 0.0, 10.0, 11.8, 'W', 41, 'SSW', 'E', 11, 20, 77, 64, 1011.6, 1008.0, 0, 0, 23.1, 25.8, 'No', 'No'), ('1/7/2009', 20.7, 33.1, 0.0, 9.0, 9.3, 'W', 41, 'SSW', 'E', 6, 15, 72, 67, 1009.9, 1005.1, 1, 7, 23.7, 26.1, 'No', 'No'), ('1/8/2009', 20.4, 22.4, 0.0, 9.8, 0.0, 'W', 41, 'SSE', 'SSE', 24, 31, 78, 72, 1012.4, 1013.4, 8, 8, 21.2, 20.1, 'No', 'No'), ('1/9/2009', 17.2, 22.6, 0.4, 7.6, 5.9, 'W', 41, 'SSE', 'ESE', 22, 19, 54, 47, 1020.2, 1018.8, 7, 6, 19.2, 21.2, 'No', 'No'), ('1/10/2009', 18.3, 23.4, 0.0, 7.6, 6.1, 'W', 41, 'ENE', 'E', 17, 20, 54, 53, 1017.1, 1013.9, 7, 6, 19.7, 22.5, 'No', 'No'), ('1/11/2009', 17.4, 24.6, 0.0, 6.6, 8.7, 'W', 41, 'NE', 'ENE', 19, 31, 58, 57, 1013.8, 1011.5, 3, 1, 23.4, 23.9, 'No', 'Yes'), ('1/12/2009', 18.7, 26.8, 1.2, 8.8, 11.4, 'W', 41, 'E', 'ESE', 7, 15, 71, 61, 1015.4, 1016.4, 1, 6, 23.2, 25.6, 'Yes', 'No'), ('1/13/2009', 19.6, 26.2, 0.2, 4.2, 11.1, 'W', 41, 'ESE', 'NE', 7, 26, 74, 56, 1019.5, 1016.5, 6, 0, 23.5, 25.4, 'No', 'No'), ('1/14/2009', 20.8, 29.7, 0.0, 10.2, 13.0, 'W', 41, 'E', 'NNE', 7, 24, 67, 49, 1014.6, 1011.2, 0, 1, 25.5, 29.1, 'No', 'No'), ('1/15/2009', 23.0, 33.4, 0.0, 14.2, 9.4, 'W', 41, 'ESE', 'NE', 7, 19, 61, 39, 1009.1, 1006.0, 5, 6, 28.6, 33.1, 'No', 'Yes'), ('1/16/2009', 18.8, 25.0, 1.8, 10.2, 10.1, 'W', 41, 'S', 'E', 4, 24, 69, 61, 1012.7, 1008.8, 2, 0, 21.4, 24.0, 'Yes', 'No'), ('1/17/2009', 17.7, 22.6, 0.0, 10.4, 6.5, 'W', 41, 'SSE', 'SSE', 26, 28, 52, 48, 1020.5, 1020.5, 6, 3, 19.0, 21.6, 'No', 'No'), ('1/18/2009', 14.8, 23.3, 0.0, 5.6, 12.7, 'W', 41, 'WNW', 'E', 11, 22, 62, 46, 1021.9, 1020.0, 1, 3, 19.5, 22.9, 'No', 'No'), ('1/19/2009', 16.4, 25.1, 0.0, 11.0, 12.7, 'W', 41, 'N', 'NE', 15, 26, 55, 57, 1019.3, 1015.0, 1, 5, 22.5, 23.8, 'No', 'No'), ('1/20/2009', 20.1, 28.7, 0.0, 9.0, 12.4, 'W', 41, 'E', 'NE', 9, 22, 61, 54, 1013.7, 1010.6, 0, 1, 24.7, 27.0, 'No', 'Yes'), ('1/21/2009', 21.3, 31.1, 1.6, 12.8, 7.4, 'W', 41, 'W', 'ENE', 11, 22, 66, 55, 1011.9, 1008.1, 3, 5, 25.7, 29.2, 'Yes', 'No'), ('1/22/2009', 23.4, 33.6, 1.0, 8.0, 9.8, 'W', 41, 'NNW', 'NNW', 15, 26, 52, 45, 1008.9, 1005.5, 5, 5, 27.8, 32.7, 'No', 'No'), ('1/23/2009', 25.0, 31.7, 0.0, 14.2, 11.9, 'W', 41, 'ESE', 'E', 9, 19, 59, 58, 1009.2, 1007.6, 1, 2, 29.5, 29.1, 'No', 'No'), ('1/24/2009', 24.8, 40.9, 0.0, 10.6, 11.1, 'W', 41, 'NW', 'W', 11, 26, 55, 20, 1004.8, 1002.8, 6, 2, 31.5, 40.1, 'No', 'No'), ('1/25/2009', 20.5, 25.9, 0.0, 13.6, 6.8, 'W', 41, 'SE', 'ESE', 15, 17, 57, 51, 1019.5, 1018.3, 7, 5, 21.9, 24.7, 'No', 'No'), ('1/26/2009', 20.8, 26.8, 0.0, 6.8, 1.2, 'W', 41, 'S', 'S', 9, 15, 80, 72, 1019.3, 1019.1, 8, 7, 21.9, 25.3, 'No', 'Yes'), ('1/27/2009', 20.2, 23.9, 14.2, 1.8, 1.7, 'W', 41, 'S', 'SSE', 9, 7, 95, 93, 1021.1, 1019.9, 8, 8, 20.8, 22.4, 'Yes', 'Yes'), ('1/28/2009', 19.9, 27.1, 4.4, 1.8, 12.3, 'W', 41, 'N', 'NE', 4, 22, 78, 60, 1018.5, 1016.0, 6, 1, 23.7, 26.6, 'Yes', 'No'), ('1/29/2009', 21.2, 28.3, 0.0, 8.6, 12.5, 'W', 41, 'E', 'NE', 4, 26, 73, 67, 1018.6, 1016.5, 1, 1, 25.2, 27.5, 'No', 'No'), ('1/30/2009', 21.1, 28.2, 0.0, 10.2, 13.0, 'W', 41, 'E', 'NE', 4, 24, 72, 59, 1018.7, 1015.8, 1, 0, 24.6, 27.5, 'No', 'No'), ('1/31/2009', 21.8, 29.1, 0.0, 10.6, 11.5, 'W', 41, 'ENE', 'NE', 7, 19, 76, 54, 1017.5, 1014.2, 2, 3, 25.0, 29.0, 'No', 'No'), ('2/1/2009', 21.2, 28.1, 0.0, 9.2, 11.1, 'W', 41, 'E', 'ESE', 13, 17, 71, 66, 1016.1, 1016.2, 1, 5, 24.9, 26.9, 'No', 'No'), ('2/2/2009', 22.9, 28.3, 0.0, 6.4, 9.8, 'W', 41, 'ESE', 'NE', 4, 24, 79, 63, 1016.3, 1012.2, 6, 2, 24.8, 27.1, 'No', 'No'), ('2/3/2009', 21.8, 28.0, 0.0, 10.8, 7.5, 'W', 41, 'W', 'SE', 0, 19, 63, 60, 1010.8, 1010.0, 7, 4, 25.4, 27.9, 'No', 'No'), ('2/4/2009', 21.6, 27.3, 0.4, 7.0, 7.1, 'W', 41, 'S', 'E', 6, 17, 84, 71, 1011.6, 1009.4, 7, 5, 23.2, 26.2, 'No', 'No'), ('2/5/2009', 22.2, 29.2, 0.0, 6.6, 12.2, 'W', 41, 'E', 'NE', 6, 22, 73, 58, 1009.1, 1005.9, 1, 1, 26.0, 28.9, 'No', 'No'), ('2/6/2009', 21.9, 29.5, 0.0, 9.8, 10.8, 'W', 41, 'E', 'ENE', 6, 11, 75, 64, 1010.9, 1008.4, 3, 1, 25.5, 27.4, 'No', 'No'), ('2/7/2009', 21.8, 33.5, 0.0, 10.4, 11.8, 'W', 41, 'E', 'NNE', 9, 31, 68, 34, 1013.3, 1010.6, 0, 1, 25.6, 32.2, 'No', 'No'), ('2/8/2009', 21.4, 28.6, 0.0, 14.2, 12.2, 'W', 41, 'E', 'ENE', 9, 17, 69, 53, 1010.8, 1007.5, 0, 1, 24.2, 28.1, 'No', 'No'), ('2/9/2009', 20.9, 22.5, 0.0, 9.0, 0.0, 'W', 41, 'S', 'S', 20, 17, 84, 81, 1011.9, 1011.7, 8, 8, 21.2, 20.6, 'No', 'Yes'), ('2/10/2009', 17.9, 19.4, 3.4, 1.6, 0.0, 'W', 41, 'SSW', 'SSW', 6, 19, 94, 89, 1011.9, 1010.1, 8, 8, 18.2, 18.7, 'Yes', 'Yes'), ('2/11/2009', 16.7, 23.0, 5.6, 2.2, 1.5, 'W', 41, 'SSW', 'S', 26, 20, 77, 61, 1011.1, 1011.2, 7, 7, 17.7, 23.0, 'Yes', 'No'), ('2/12/2009', 17.5, 22.0, 0.6, 4.0, 1.1, 'W', 41, 'SSW', 'SSE', 19, 31, 76, 56, 1017.5, 1018.7, 7, 8, 18.9, 21.4, 'No', 'Yes'), ('2/13/2009', 16.4, 20.4, 23.2, 5.4, 0.0, 'W', 41, 'SE', 'SE', 24, 24, 86, 90, 1025.4, 1025.0, 8, 8, 18.0, 17.9, 'Yes', 'Yes'), ('2/14/2009', 17.0, 21.2, 19.6, 4.4, 0.0, 'W', 41, 'ESE', 'ESE', 30, 19, 66, 67, 1022.9, 1019.2, 8, 8, 19.1, 20.4, 'Yes', 'Yes'), ('2/15/2009', 16.5, 23.3, 25.6, 2.4, 0.2, 'W', 41, 'SSE', 'SE', 19, 22, 88, 66, 1014.7, 1013.9, 8, 8, 19.4, 23.1, 'Yes', 'Yes'), ('2/16/2009', 18.6, 25.0, 16.4, 4.8, 6.4, 'W', 41, 'SE', 'SE', 19, 24, 82, 62, 1017.6, 1017.8, 7, 7, 20.3, 22.6, 'Yes', 'Yes'), ('2/17/2009', 19.4, 22.9, 3.8, 7.4, 0.0, 'W', 41, 'SE', 'SE', 9, 17, 70, 71, 1017.0, 1015.4, 8, 8, 20.8, 22.0, 'Yes', 'Yes'), ('2/18/2009', 19.4, 26.6, 24.6, 3.2, 7.1, 'W', 41, 'W', 'S', 19, 15, 93, 62, 1010.2, 1008.1, 8, 6, 20.2, 25.7, 'Yes', 'Yes'), ('2/19/2009', 18.9, 28.4, 1.4, 3.6, 11.4, 'W', 41, 'NNW', 'E', 19, 20, 74, 60, 1008.0, 1005.0, 2, 5, 23.1, 27.5, 'Yes', 'No'), ('2/20/2009', 20.3, 26.1, 0.0, 7.8, 9.6, 'W', 41, 'W', 'E', 2, 19, 78, 68, 1011.6, 1010.2, 5, 3, 22.4, 25.1, 'No', 'No'), ('2/21/2009', 21.9, 24.4, 0.0, 6.4, 0.3, 'W', 41, 'W', 'E', 0, 11, 85, 68, 1013.3, 1013.2, 8, 8, 22.5, 23.6, 'No', 'Yes'), ('2/22/2009', 20.3, 24.9, 2.2, 2.4, 6.3, 'W', 41, 'SSE', 'E', 13, 13, 70, 59, 1018.5, 1017.6, 7, 4, 21.7, 24.4, 'Yes', 'No'), ('2/23/2009', 19.6, 27.0, 0.0, 4.6, 5.3, 'W', 41, 'W', 'ENE', 0, 15, 78, 63, 1016.9, 1013.0, 7, 5, 22.6, 26.5, 'No', 'No'), ('2/24/2009', 19.9, 30.5, 0.8, 5.4, 10.7, 'W', 41, 'W', 'SE', 11, 15, 82, 57, 1014.1, 1013.2, 0, 1, 23.0, 28.2, 'No', 'No'), ('2/25/2009', 21.1, 26.4, 0.0, 7.0, 7.0, 'W', 41, 'S', 'ESE', 4, 20, 83, 63, 1016.7, 1014.6, 7, 5, 22.0, 26.1, 'No', 'No'), ('2/26/2009', 19.6, 24.6, 0.0, 7.6, 6.8, 'W', 41, 'S', 'S', 11, 20, 74, 58, 1020.4, 1018.7, 8, 5, 20.7, 23.6, 'No', 'No'), ('2/27/2009', 17.5, 23.5, 0.0, 6.0, 5.6, 'W', 41, 'W', 'E', 13, 11, 78, 50, 1018.2, 1015.9, 7, 4, 18.9, 23.2, 'No', 'No'), ('2/28/2009', 17.5, 25.4, 0.0, 4.8, 5.6, 'W', 41, 'N', 'E', 7, 20, 70, 61, 1009.5, 1006.9, 7, 4, 20.7, 24.1, 'No', 'No'), ('3/1/2009', 20.5, 25.7, 0.0, 6.8, 10.0, 'W', 41, 'E', 'E', 9, 19, 70, 60, 1010.7, 1010.8, 8, 6, 23.1, 24.8, 'No', 'No'), ('3/2/2009', 21.8, 25.5, 0.0, 6.0, 9.0, 'W', 41, 'W', 'E', 0, 17, 71, 60, 1016.6, 1015.2, 7, 5, 22.8, 25.1, 'No', 'No'), ('3/3/2009', 20.8, 26.9, 0.0, 6.8, 6.9, 'W', 41, 'ENE', 'ENE', 19, 20, 61, 55, 1018.0, 1015.2, 7, 7, 24.1, 25.6, 'No', 'No'), ('3/4/2009', 22.5, 25.1, 0.0, 7.6, 0.5, 'W', 41, 'E', 'SW', 4, 13, 73, 49, 1008.0, 1008.5, 7, 7, 24.2, 22.9, 'No', 'No'), ('3/5/2009', 16.8, 24.6, 0.0, 5.0, 11.0, 'W', 41, 'W', 'SE', 30, 20, 39, 37, 1009.5, 1008.6, 1, 1, 19.3, 24.2, 'No', 'No'), ('3/6/2009', 14.4, 23.6, 0.0, 7.8, 9.8, 'W', 41, 'W', 'ESE', 15, 19, 67, 48, 1013.4, 1011.4, 1, 1, 17.8, 22.5, 'No', 'No'), ('3/7/2009', 17.7, 26.3, 0.0, 4.8, 9.2, 'W', 41, 'SW', 'ESE', 11, 19, 77, 58, 1014.2, 1011.8, 3, 1, 20.5, 25.8, 'No', 'No'), ('3/8/2009', 20.2, 25.3, 0.0, 5.0, 4.1, 'W', 41, 'SSW', 'S', 11, 19, 80, 77, 1017.8, 1018.7, 5, 7, 22.2, 22.0, 'No', 'Yes'), ('3/9/2009', 18.2, 24.5, 36.8, 2.0, 4.4, 'W', 41, 'SW', 'E', 6, 13, 94, 69, 1022.2, 1020.4, 7, 7, 19.1, 23.6, 'Yes', 'No'), ('3/10/2009', 19.1, 24.5, 0.6, 3.6, 6.7, 'W', 41, 'ENE', 'E', 17, 20, 66, 53, 1022.0, 1021.3, 6, 5, 22.8, 24.3, 'No', 'No'), ('3/11/2009', 20.2, 23.4, 0.0, 6.2, 1.8, 'W', 41, 'ESE', 'E', 17, 24, 59, 70, 1023.8, 1022.7, 3, 7, 23.3, 22.3, 'No', 'Yes'), ('3/12/2009', 18.2, 25.3, 1.2, 5.0, 9.8, 'W', 41, 'W', 'E', 4, 22, 87, 57, 1022.9, 1020.4, 2, 2, 20.3, 24.7, 'Yes', 'No'), ('3/13/2009', 19.6, 25.5, 0.0, 6.4, 2.2, 'W', 41, 'W', 'NW', 7, 2, 85, 76, 1018.6, 1016.2, 7, 7, 21.1, 23.9, 'No', 'No'), ('3/14/2009', 19.9, 27.2, 0.0, 4.0, 6.4, 'W', 41, 'NE', 'ENE', 2, 20, 82, 64, 1014.7, 1010.1, 3, 6, 22.3, 26.8, 'No', 'Yes'), ('3/15/2009', 19.2, 27.4, 17.0, 8.4, 6.6, 'W', 41, 'WNW', 'E', 6, 15, 81, 61, 1010.7, 1007.8, 2, 3, 21.7, 25.0, 'Yes', 'No'), ('3/16/2009', 16.1, 26.8, 0.4, 6.8, 10.8, 'W', 41, 'W', 'E', 17, 22, 42, 29, 1011.7, 1008.2, 1, 0, 18.7, 26.7, 'No', 'No'), ('3/17/2009', 15.9, 25.7, 0.0, 6.1, 11.0, 'W', 41, 'W', 'SE', 20, 19, 47, 48, 1013.4, 1012.5, 1, 1, 18.8, 23.9, 'No', 'No'), ('3/18/2009', 17.1, 24.5, 0.0, 5.4, 10.1, 'W', 41, 'WNW', 'ENE', 11, 17, 72, 52, 1019.0, 1016.1, 1, 1, 20.1, 24.3, 'No', 'No'), ('3/19/2009', 17.5, 27.7, 0.0, 6.0, 9.7, 'W', 41, 'W', 'E', 13, 13, 76, 67, 1016.7, 1013.7, 2, 7, 20.6, 24.9, 'No', 'No'), ('3/20/2009', 19.9, 26.1, 0.0, 6.2, 8.6, 'W', 41, 'W', 'E', 0, 17, 80, 69, 1017.4, 1016.6, 2, 1, 23.5, 25.3, 'No', 'No'), ('3/21/2009', 19.6, 25.3, 0.0, 6.2, 8.7, 'W', 41, 'W', 'E', 6, 17, 83, 58, 1018.9, 1017.2, 4, 2, 22.1, 24.9, 'No', 'No'), ('3/22/2009', 17.6, 26.7, 0.0, 5.6, 8.4, 'W', 41, 'W', 'NE', 11, 19, 82, 58, 1017.9, 1015.1, 1, 5, 20.4, 25.0, 'No', 'No'), ('3/23/2009', 19.5, 25.7, 0.2, 8.0, 10.2, 'W', 41, 'NE', 'NE', 7, 17, 66, 61, 1017.1, 1015.1, 5, 4, 23.1, 25.6, 'No', 'No'), ('3/24/2009', 20.5, 26.1, 0.0, 5.8, 10.8, 'W', 41, 'NNE', 'NE', 6, 19, 67, 59, 1017.9, 1016.3, 1, 3, 23.6, 25.9, 'No', 'No'), ('3/25/2009', 20.8, 26.0, 0.0, 7.0, 8.0, 'W', 41, 'NNE', 'E', 4, 17, 69, 60, 1019.7, 1017.5, 4, 4, 23.0, 25.2, 'No', 'Yes'), ('3/26/2009', 20.5, 26.6, 1.4, 5.2, 7.6, 'W', 41, 'NE', 'ENE', 2, 17, 72, 56, 1019.4, 1016.7, 4, 6, 23.8, 25.7, 'Yes', 'No'), ('3/27/2009', 20.6, 23.5, 0.4, 5.8, 4.8, 'W', 41, 'SSE', 'SSE', 17, 26, 69, 59, 1023.9, 1023.7, 7, 6, 22.0, 22.5, 'No', 'No'), ('3/28/2009', 16.4, 23.5, 0.0, 4.4, 10.8, 'W', 41, 'WNW', 'E', 9, 17, 85, 49, 1025.4, 1023.2, 3, 1, 17.9, 23.0, 'No', 'No'), ('3/29/2009', 16.1, 24.4, 0.0, 6.6, 9.4, 'W', 41, 'WNW', 'E', 9, 19, 77, 66, 1023.6, 1021.7, 5, 5, 18.9, 23.0, 'No', 'No'), ('3/30/2009', 18.6, 26.2, 0.0, 4.0, 6.7, 'W', 41, 'ESE', 'SE', 7, 22, 66, 65, 1024.1, 1022.3, 2, 6, 22.9, 24.7, 'No', 'Yes'), ('3/31/2009', 19.8, 22.5, 2.6, 6.0, 0.0, 'W', 41, 'SE', 'E', 20, 26, 86, 89, 1021.8, 1020.4, 8, 8, 21.1, 19.9, 'Yes', 'Yes'), ('4/1/2009', 18.4, 24.7, 46.0, 5.0, 2.3, 'W', 41, 'ESE', 'ESE', 28, 30, 93, 73, 1021.1, 1021.0, 8, 7, 20.5, 23.9, 'Yes', 'Yes'), ('4/2/2009', 19.6, 24.7, 11.4, 3.8, 2.4, 'W', 41, 'ESE', 'ESE', 22, 17, 87, 79, 1023.3, 1021.8, 8, 7, 21.9, 23.8, 'Yes', 'Yes'), ('4/3/2009', 20.1, 25.1, 5.0, 2.6, 7.9, 'W', 41, 'W', 'ENE', 0, 24, 92, 73, 1021.1, 1016.9, 6, 5, 21.4, 24.4, 'Yes', 'Yes'), ('4/4/2009', 18.3, 20.8, 3.0, 4.2, 1.4, 'W', 41, 'S', 'SSE', 24, 28, 84, 58, 1017.7, 1019.2, 7, 8, 18.4, 20.1, 'Yes', 'No'), ('4/5/2009', 17.1, 22.8, 0.0, 5.6, 8.0, 'W', 41, 'W', 'NE', 9, 20, 72, 67, 1020.1, 1014.4, 7, 5, 19.1, 21.5, 'No', 'No'), ('4/6/2009', 17.0, 21.1, 0.2, 3.4, 6.9, 'W', 41, 'S', 'SSE', 30, 26, 69, 59, 1020.5, 1019.6, 7, 3, 19.5, 19.4, 'No', 'No'), ('4/7/2009', 16.3, 21.3, 0.2, 5.8, 7.7, 'W', 41, 'S', 'SE', 11, 24, 67, 55, 1025.6, 1024.4, 7, 3, 18.8, 20.1, 'No', 'No'), ('4/8/2009', 12.8, 22.4, 0.0, 5.6, 9.3, 'W', 41, 'W', 'SE', 11, 22, 66, 59, 1026.9, 1024.9, 2, 4, 18.7, 21.3, 'No', 'No'), ('4/9/2009', 15.1, 23.2, 0.0, 2.8, 8.4, 'W', 41, 'WNW', 'E', 9, 19, 72, 58, 1025.5, 1022.3, 1, 3, 19.6, 21.8, 'No', 'No'), ('4/10/2009', 14.7, 22.7, 0.0, 4.0, 8.3, 'W', 41, 'W', 'E', 15, 9, 81, 65, 1023.6, 1021.0, 5, 4, 18.4, 22.4, 'No', 'No'), ('4/11/2009', 17.4, 23.8, 0.0, 3.2, 0.8, 'W', 41, 'W', 'ENE', 0, 9, 80, 69, 1025.4, 1023.0, 7, 7, 19.8, 23.0, 'No', 'No'), ('4/13/2009', 20.4, 22.6, 0.0, 3.6, 0.1, 'W', 41, 'SE', 'S', 15, 7, 79, 84, 1022.5, 1019.3, 8, 8, 21.6, 20.9, 'No', 'Yes'), ('4/14/2009', 17.6, 26.9, 48.0, 4.8, 7.8, 'W', 41, 'W', 'E', 19, 20, 89, 70, 1015.1, 1011.2, 6, 5, 19.2, 23.1, 'Yes', 'No'), ('4/15/2009', 16.1, 29.3, 0.2, 5.0, 10.0, 'W', 41, 'W', 'NW', 11, 20, 70, 25, 1011.1, 1006.9, 0, 1, 20.5, 29.0, 'No', 'No'), ('4/16/2009', 14.9, 24.1, 0.0, 10.0, 9.8, 'W', 41, 'W', 'E', 15, 15, 43, 38, 1015.2, 1011.7, 0, 1, 17.4, 22.6, 'No', 'No'), ('4/17/2009', 13.5, 24.1, 0.0, 4.8, 10.3, 'W', 41, 'WNW', 'S', 13, 19, 56, 51, 1016.3, 1015.9, 0, 1, 18.4, 22.5, 'No', 'No'), ('4/18/2009', 14.2, 22.8, 0.0, 5.2, 7.9, 'W', 41, 'WSW', 'S', 11, 28, 66, 56, 1020.0, 1018.1, 1, 5, 18.3, 20.9, 'No', 'Yes'), ('4/19/2009', 15.8, 22.5, 13.4, 3.4, 8.3, 'W', 41, 'SSW', 'S', 20, 17, 91, 62, 1019.9, 1017.9, 7, 6, 16.1, 21.7, 'Yes', 'Yes'), ('4/20/2009', 15.9, 21.4, 9.0, 7.0, 2.9, 'W', 41, 'SSE', 'S', 26, 24, 60, 59, 1020.7, 1018.9, 7, 7, 19.5, 19.7, 'Yes', 'No'), ('4/21/2009', 16.4, 22.1, 0.6, 5.4, 5.0, 'W', 41, 'ESE', 'S', 33, 15, 59, 64, 1022.8, 1021.3, 5, 7, 20.5, 20.1, 'No', 'Yes'), ('4/22/2009', 16.0, 22.7, 6.8, 3.4, 7.7, 'W', 41, 'SW', 'S', 9, 17, 85, 65, 1024.3, 1022.5, 7, 7, 17.2, 20.1, 'Yes', 'Yes'), ('4/23/2009', 14.7, 21.6, 2.0, 4.2, 6.3, 'W', 41, 'WNW', 'ENE', 15, 7, 87, 60, 1021.8, 1018.2, 3, 5, 16.9, 20.0, 'Yes', 'No'), ('4/24/2009', 13.1, 24.7, 0.0, 2.0, 9.0, 'W', 41, 'NNW', 'E', 9, 11, 75, 63, 1012.7, 1006.6, 6, 7, 17.4, 22.6, 'No', 'No'), ('4/25/2009', 16.3, 23.9, 0.4, 5.4, 10.3, 'W', 41, 'NW', 'W', 11, 22, 52, 40, 1004.4, 1002.4, 1, 3, 19.3, 22.2, 'No', 'No'), ('4/26/2009', 16.7, 20.2, 0.0, 6.8, 9.2, 'W', 41, 'WNW', 'WNW', 20, 28, 47, 29, 1003.1, 1003.1, 2, 2, 17.7, 19.5, 'No', 'No'), ('4/27/2009', 11.2, 18.7, 0.0, 7.2, 9.9, 'W', 41, 'W', 'WNW', 28, 24, 43, 26, 1013.0, 1012.7, 1, 2, 14.1, 17.9, 'No', 'No'), ('4/28/2009', 11.8, 21.9, 0.0, 4.0, 10.5, 'W', 41, 'W', 'W', 19, 26, 54, 30, 1015.5, 1014.9, 1, 2, 16.1, 20.5, 'No', 'No'), ('4/29/2009', 10.2, 17.6, 0.0, 4.6, 2.4, 'W', 41, 'WNW', 'S', 20, 22, 59, 63, 1022.3, 1019.5, 7, 7, 12.6, 16.6, 'No', 'Yes'), ('4/30/2009', 11.0, 17.4, 6.2, 2.4, 2.7, 'W', 41, 'W', 'WSW', 17, 4, 92, 88, 1020.5, 1020.4, 7, 7, 12.8, 14.1, 'Yes', 'Yes'), ('5/1/2009', 10.2, 22.5, 5.6, 3.0, 10.3, 'W', 41, 'W', 'E', 17, 11, 76, 53, 1024.6, 1020.9, 3, 5, 13.0, 20.7, 'Yes', 'No'), ('5/2/2009', 10.9, 22.0, 0.0, 2.2, 9.4, 'W', 41, 'W', 'S', 22, 22, 61, 56, 1025.1, 1022.7, 1, 2, 14.0, 20.8, 'No', 'Yes'), ('5/3/2009', 11.4, 20.5, 13.0, 3.6, 7.0, 'W', 41, 'W', 'SE', 7, 6, 85, 61, 1027.8, 1025.5, 4, 2, 12.8, 20.4, 'Yes', 'No'), ('5/4/2009', 12.1, 23.3, 0.0, 3.2, 10.0, 'W', 41, 'W', 'E', 19, 15, 84, 53, 1028.5, 1025.5, 1, 1, 14.5, 21.6, 'No', 'Yes'), ('5/5/2009', 14.0, 21.0, 1.2, 1.8, 4.2, 'W', 41, 'W', 'S', 13, 19, 86, 61, 1030.7, 1028.3, 7, 5, 14.7, 20.5, 'Yes', 'No'), ('5/6/2009', 12.9, 22.9, 0.8, 3.2, 9.7, 'W', 41, 'W', 'ENE', 11, 17, 92, 61, 1028.3, 1023.7, 2, 1, 14.1, 20.7, 'No', 'No'), ('5/7/2009', 12.0, 22.7, 0.0, 4.0, 10.2, 'W', 41, 'W', 'SSE', 20, 17, 67, 44, 1024.3, 1021.7, 1, 1, 15.0, 21.6, 'No', 'No'), ('5/8/2009', 12.3, 20.9, 0.0, 2.6, 9.5, 'W', 41, 'W', 'S', 20, 24, 71, 61, 1027.5, 1025.0, 1, 2, 14.9, 19.6, 'No', 'No'), ('5/9/2009', 11.1, 22.8, 0.0, 4.4, 9.8, 'W', 41, 'W', 'E', 19, 9, 74, 46, 1024.2, 1020.4, 1, 1, 13.4, 21.0, 'No', 'No'), ('5/10/2009', 13.0, 20.1, 0.8, 3.4, 3.4, 'W', 41, 'SSW', 'SSE', 11, 17, 86, 46, 1024.6, 1023.6, 7, 5, 13.9, 19.6, 'No', 'Yes'), ('5/11/2009', 11.8, 18.9, 1.4, 3.4, 6.4, 'W', 41, 'W', 'SW', 15, 2, 74, 55, 1025.2, 1022.4, 6, 5, 14.3, 17.4, 'Yes', 'No'), ('5/12/2009', 9.6, 20.1, 0.0, 2.6, 5.5, 'W', 41, 'W', 'S', 19, 11, 78, 51, 1021.6, 1018.1, 1, 6, 12.0, 18.5, 'No', 'No'), ('5/13/2009', 10.4, 21.3, 0.0, 1.6, 9.7, 'W', 41, 'W', 'WNW', 22, 11, 80, 39, 1016.8, 1012.8, 1, 1, 12.4, 20.9, 'No', 'No'), ('5/14/2009', 11.1, 21.5, 0.0, 2.6, 10.1, 'W', 41, 'NW', 'W', 17, 35, 50, 31, 1012.6, 1010.6, 1, 1, 15.2, 20.5, 'No', 'No'), ('5/15/2009', 12.4, 21.7, 0.0, 6.2, 8.7, 'W', 41, 'W', 'W', 15, 30, 58, 34, 1012.8, 1009.7, 1, 2, 14.2, 21.4, 'No', 'No'), ('5/16/2009', 14.2, 21.7, 0.0, 5.0, 7.8, 'W', 41, 'W', 'WSW', 24, 30, 49, 38, 1008.2, 1008.1, 7, 7, 18.7, 21.7, 'No', 'No'), ('5/17/2009', 11.4, 20.7, 0.0, 4.8, 9.7, 'W', 41, 'W', 'SE', 15, 15, 64, 40, 1018.7, 1017.7, 1, 1, 13.0, 19.6, 'No', 'No'), ('5/18/2009', 10.5, 20.9, 0.0, 2.6, 5.2, 'W', 41, 'W', 'ESE', 19, 17, 74, 52, 1025.7, 1023.3, 3, 5, 13.2, 19.7, 'No', 'Yes'), ('5/19/2009', 13.0, 21.4, 2.6, 2.4, 4.4, 'W', 41, 'W', 'E', 15, 20, 91, 53, 1024.5, 1021.4, 6, 6, 14.5, 20.0, 'Yes', 'Yes'), ('5/20/2009', 14.5, 21.2, 20.2, 4.4, 3.0, 'W', 41, 'E', 'ESE', 33, 31, 68, 62, 1022.1, 1020.1, 7, 7, 19.2, 20.4, 'Yes', 'Yes'), ('5/21/2009', 14.8, 19.7, 27.2, 1.8, 0.2, 'W', 41, 'W', 'E', 15, 19, 53, 62, 1023.9, 1022.0, 7, 7, 19.2, 18.7, 'Yes', 'Yes'), ('5/22/2009', 15.6, 19.6, 4.6, 6.6, 0.0, 'W', 41, 'W', 'E', 15, 19, 59, 85, 1023.6, 1020.8, 8, 8, 19.1, 17.5, 'Yes', 'Yes'), ('5/23/2009', 15.4, 20.8, 17.6, 5.0, 6.0, 'W', 41, 'W', 'E', 15, 19, 66, 80, 1023.6, 1023.3, 5, 8, 19.6, 18.1, 'Yes', 'Yes'), ('5/24/2009', 17.4, 21.3, 1.6, 4.4, 7.4, 'W', 41, 'W', 'E', 15, 19, 52, 48, 1026.8, 1025.4, 5, 5, 19.7, 20.7, 'Yes', 'No'), ('5/25/2009', 13.6, 20.3, 0.0, 3.6, 2.2, 'W', 41, 'W', 'E', 15, 19, 82, 61, 1025.8, 1023.2, 7, 7, 15.4, 19.4, 'No', 'No'), ('5/26/2009', 12.8, 23.4, 0.0, 0.6, 8.4, 'W', 41, 'W', 'E', 15, 11, 89, 57, 1022.3, 1018.9, 1, 1, 13.9, 21.6, 'No', 'No'), ('5/27/2009', 13.9, 16.9, 0.0, 3.0, 0.1, 'W', 41, 'W', 'W', 15, 6, 88, 86, 1020.4, 1018.4, 7, 8, 15.3, 16.3, 'No', 'Yes'), ('5/28/2009', 12.0, 19.2, 3.6, 0.4, 7.7, 'W', 41, 'W', 'S', 17, 22, 92, 72, 1021.4, 1020.2, 3, 5, 13.5, 17.1, 'Yes', 'No'), ('5/29/2009', 11.4, 17.5, 0.0, 2.4, 6.1, 'W', 41, 'W', 'S', 20, 26, 65, 65, 1023.3, 1022.3, 3, 7, 12.4, 16.6, 'No', 'Yes'), ('5/30/2009', 9.9, 16.5, 15.0, 4.6, 4.0, 'W', 41, 'W', 'SSW', 19, 13, 82, 78, 1028.2, 1027.1, 8, 6, 11.7, 15.9, 'Yes', 'Yes'), ('5/31/2009', 11.6, 18.8, 10.6, 1.2, 2.8, 'W', 41, 'E', 'E', 24, 24, 86, 67, 1033.3, 1031.9, 6, 7, 14.5, 16.8, 'Yes', 'No'), ('6/1/2009', 13.1, 16.8, 0.6, 3.0, 0.0, 'W', 41, 'W', 'E', 17, 2, 83, 67, 1032.9, 1030.4, 7, 8, 13.3, 16.1, 'No', 'No'), ('6/2/2009', 12.5, 19.1, 0.0, 1.2, 3.4, 'W', 41, 'WNW', 'ENE', 13, 15, 91, 68, 1030.1, 1027.1, 7, 7, 13.7, 18.5, 'No', 'Yes'), ('6/3/2009', 13.7, 18.5, 8.0, 2.8, 0.1, 'W', 41, 'SE', 'E', 6, 19, 89, 87, 1025.9, 1022.3, 8, 7, 16.0, 17.6, 'Yes', 'Yes'), ('6/4/2009', 13.1, 17.0, 10.4, 0.0, 0.6, 'W', 41, 'W', 'ENE', 15, 2, 97, 86, 1020.7, 1016.8, 7, 7, 13.4, 16.8, 'Yes', 'No'), ('6/5/2009', 13.1, 18.5, 0.6, 1.0, 3.5, 'W', 41, 'W', 'W', 17, 15, 93, 55, 1014.7, 1012.4, 4, 6, 14.5, 18.4, 'No', 'No'), ('6/6/2009', 9.3, 19.0, 0.0, 2.2, 9.8, 'W', 41, 'W', 'WNW', 17, 7, 71, 45, 1014.1, 1010.1, 1, 1, 11.6, 18.7, 'No', 'No'), ('6/7/2009', 10.7, 19.8, 0.2, 3.8, 6.6, 'W', 41, 'NW', 'WNW', 13, 19, 80, 42, 1008.2, 1004.8, 6, 3, 12.6, 18.7, 'No', 'No'), ('6/8/2009', 11.4, 19.2, 0.0, 3.2, 9.0, 'W', 41, 'NNW', 'W', 13, 22, 63, 34, 1009.8, 1007.3, 2, 2, 13.8, 18.6, 'No', 'No'), ('6/9/2009', 10.0, 16.2, 0.0, 2.6, 6.0, 'W', 41, 'W', 'WNW', 17, 22, 62, 44, 1011.5, 1008.3, 3, 7, 11.7, 15.0, 'No', 'No'), ('6/10/2009', 9.7, 14.2, 0.0, 4.4, 9.6, 'W', 41, 'W', 'WSW', 35, 31, 37, 32, 1012.2, 1012.5, 1, 1, 10.5, 13.6, 'No', 'No'), ('6/11/2009', 6.1, 15.8, 0.0, 4.0, 9.8, 'W', 41, 'W', 'W', 26, 22, 48, 28, 1020.9, 1018.2, 1, 1, 7.9, 15.4, 'No', 'No'), ('6/12/2009', 6.2, 17.1, 0.0, 3.0, 9.4, 'W', 41, 'W', 'W', 22, 4, 67, 41, 1024.3, 1020.2, 1, 7, 8.2, 17.1, 'No', 'No'), ('6/13/2009', 7.8, 18.5, 0.0, 2.6, 4.6, 'W', 41, 'W', 'WNW', 9, 7, 70, 40, 1017.7, 1014.0, 7, 7, 9.4, 16.8, 'No', 'No'), ('6/14/2009', 9.4, 15.6, 0.0, 3.4, 0.3, 'W', 41, 'W', 'NNE', 6, 2, 74, 61, 1014.5, 1011.9, 7, 7, 11.0, 14.4, 'No', 'Yes'), ('6/15/2009', 8.2, 19.8, 1.2, 0.8, 8.6, 'W', 41, 'W', 'SSW', 15, 7, 79, 40, 1013.1, 1010.6, 1, 3, 10.2, 18.4, 'Yes', 'No'), ('6/16/2009', 9.2, 16.3, 0.6, 3.0, 0.5, 'W', 41, 'SW', 'S', 17, 19, 81, 88, 1017.9, 1020.1, 6, 7, 13.1, 13.6, 'No', 'Yes'), ('6/17/2009', 10.5, 15.6, 29.8, 0.8, 3.3, 'W', 41, 'W', 'WSW', 19, 6, 92, 87, 1027.6, 1026.5, 7, 6, 11.2, 14.2, 'Yes', 'Yes'), ('6/18/2009', 10.1, 15.4, 7.8, 1.0, 3.3, 'W', 41, 'W', 'E', 11, 9, 95, 85, 1030.0, 1028.1, 7, 7, 10.7, 14.2, 'Yes', 'Yes'), ('6/19/2009', 9.2, 18.0, 23.6, 1.4, 7.2, 'W', 41, 'ENE', 'E', 11, 19, 95, 46, 1030.2, 1028.0, 6, 5, 10.9, 17.8, 'Yes', 'No'), ('6/20/2009', 10.9, 16.0, 0.2, 3.8, 0.6, 'W', 41, 'W', 'NNE', 15, 11, 95, 87, 1028.0, 1024.6, 6, 8, 11.7, 15.5, 'No', 'Yes'), ('6/21/2009', 11.7, 19.1, 31.8, 0.6, 1.9, 'W', 41, 'W', 'NE', 4, 11, 93, 82, 1023.9, 1020.7, 7, 7, 14.1, 17.8, 'Yes', 'Yes'), ('6/22/2009', 14.1, 21.0, 12.2, 1.8, 6.7, 'W', 41, 'WNW', 'NE', 9, 4, 96, 59, 1020.3, 1017.7, 7, 2, 15.1, 20.6, 'Yes', 'No'), ('6/23/2009', 10.1, 19.6, 0.0, 1.6, 9.5, 'W', 41, 'W', 'E', 13, 11, 91, 58, 1019.9, 1016.7, 1, 1, 11.2, 18.8, 'No', 'No'), ('6/24/2009', 9.1, 18.9, 0.0, 1.4, 6.3, 'W', 41, 'NNW', 'E', 7, 7, 86, 49, 1015.2, 1010.7, 7, 1, 10.7, 18.6, 'No', 'No'), ('6/25/2009', 8.7, 16.9, 0.0, 2.2, 6.5, 'W', 41, 'WNW', 'WNW', 13, 13, 69, 50, 1014.6, 1012.2, 6, 7, 11.9, 15.8, 'No', 'No'), ('6/26/2009', 8.7, 18.6, 0.0, 1.8, 8.8, 'W', 41, 'W', 'ENE', 15, 11, 76, 51, 1012.7, 1009.2, 3, 7, 10.7, 16.6, 'No', 'No'), ('6/27/2009', 9.4, 15.8, 0.0, 2.2, 0.2, 'W', 41, 'WNW', 'N', 7, 9, 84, 79, 1008.1, 1005.4, 7, 7, 10.4, 15.1, 'No', 'No'), ('6/28/2009', 10.4, 18.7, 0.0, 2.2, 5.3, 'W', 41, 'W', 'WNW', 11, 7, 86, 54, 1006.3, 1004.5, 4, 6, 12.4, 17.5, 'No', 'Yes'), ('6/29/2009', 9.6, 20.7, 2.8, 2.0, 9.8, 'W', 41, 'W', 'W', 17, 7, 67, 47, 1012.3, 1010.3, 1, 1, 12.3, 20.4, 'Yes', 'No'), ('6/30/2009', 12.3, 19.9, 0.0, 1.4, 2.2, 'W', 41, 'NNW', 'NNW', 28, 24, 66, 54, 1013.2, 1008.2, 7, 3, 15.6, 19.1, 'No', 'No'), ('7/1/2009', 15.7, 21.2, 0.0, 4.0, 8.6, 'W', 41, 'W', 'W', 7, 28, 61, 27, 1005.8, 1004.1, 1, 1, 16.5, 20.5, 'No', 'No'), ('7/2/2009', 11.0, 18.9, 0.0, 4.8, 8.4, 'W', 41, 'NNW', 'W', 13, 33, 55, 32, 1007.9, 1006.4, 1, 1, 13.0, 17.8, 'No', 'No'), ('7/3/2009', 11.1, 16.2, 0.0, 5.6, 9.4, 'W', 41, 'W', 'W', 44, 37, 50, 41, 1003.5, 1004.0, 1, 4, 12.3, 14.5, 'No', 'No'), ('7/4/2009', 8.5, 17.1, 0.0, 3.8, 9.8, 'W', 41, 'W', 'W', 15, 30, 59, 34, 1012.5, 1011.1, 1, 1, 10.1, 16.7, 'No', 'No'), ('7/5/2009', 10.1, 18.1, 0.0, 3.0, 9.8, 'W', 41, 'W', 'S', 20, 11, 54, 32, 1016.4, 1016.4, 2, 1, 11.8, 17.2, 'No', 'No'), ('7/6/2009', 6.2, 15.7, 0.0, 3.0, 6.5, 'W', 41, 'W', 'WSW', 19, 7, 74, 48, 1020.8, 1017.8, 6, 6, 7.5, 14.8, 'No', 'No'), ('7/7/2009', 7.5, 15.1, 0.6, 2.6, 3.9, 'W', 41, 'W', 'SSW', 19, 19, 81, 60, 1025.0, 1024.1, 6, 7, 9.0, 14.7, 'No', 'Yes'), ('7/8/2009', 8.6, 16.8, 13.8, 2.6, 3.2, 'W', 41, 'WNW', 'ESE', 15, 4, 96, 61, 1029.6, 1028.2, 7, 6, 10.5, 15.4, 'Yes', 'Yes'), ('7/9/2009', 9.1, 17.6, 6.2, 0.4, 4.4, 'W', 41, 'WNW', 'ESE', 13, 30, 96, 63, 1030.9, 1028.5, 7, 5, 10.3, 16.2, 'Yes', 'Yes'), ('7/10/2009', 9.5, 18.6, 8.8, 1.8, 8.4, 'W', 41, 'W', 'SSE', 13, 20, 97, 65, 1028.1, 1024.7, 5, 6, 10.8, 16.8, 'Yes', 'No'), ('7/11/2009', 9.1, 16.4, 0.0, 2.0, 3.6, 'W', 41, 'W', 'ENE', 13, 13, 94, 58, 1022.6, 1018.6, 7, 7, 10.3, 15.8, 'No', 'No'), ('7/12/2009', 10.3, 16.8, 0.0, 1.4, 2.3, 'W', 41, 'W', 'N', 9, 26, 80, 56, 1014.6, 1009.4, 7, 6, 11.8, 16.7, 'No', 'No'), ('7/13/2009', 11.6, 17.4, 0.2, 2.4, 2.8, 'W', 41, 'W', 'N', 9, 7, 67, 53, 1007.5, 1005.9, 6, 6, 14.5, 16.8, 'No', 'No'), ('7/14/2009', 10.2, 17.2, 0.0, 3.2, 9.7, 'W', 41, 'W', 'WNW', 15, 28, 68, 34, 1007.4, 1004.4, 1, 1, 12.1, 16.8, 'No', 'No'), ('7/15/2009', 6.7, 17.3, 0.0, 2.6, 6.9, 'W', 41, 'W', 'NW', 17, 7, 79, 42, 1010.1, 1008.2, 3, 4, 8.9, 17.0, 'No', 'No'), ('7/16/2009', 8.1, 16.5, 0.0, 2.0, 2.5, 'W', 41, 'W', 'SW', 24, 22, 78, 47, 1012.3, 1010.3, 6, 7, 9.2, 14.5, 'No', 'Yes'), ('7/17/2009', 9.2, 15.8, 7.0, 3.2, 4.5, 'W', 41, 'W', 'SSW', 20, 22, 80, 59, 1019.2, 1019.2, 3, 6, 10.7, 15.1, 'Yes', 'No'), ('7/18/2009', 8.0, 18.6, 0.0, 3.0, 9.8, 'W', 41, 'W', 'WNW', 15, 6, 84, 42, 1022.5, 1018.4, 1, 1, 9.0, 18.4, 'No', 'No'), ('7/19/2009', 8.0, 19.9, 0.0, 2.2, 9.4, 'W', 41, 'W', 'WNW', 9, 11, 66, 37, 1021.1, 1019.2, 2, 1, 10.2, 19.5, 'No', 'No'), ('7/20/2009', 8.2, 21.3, 0.0, 2.6, 10.0, 'W', 41, 'W', 'N', 15, 13, 72, 34, 1025.1, 1020.4, 0, 0, 10.3, 21.2, 'No', 'No'), ('7/21/2009', 8.8, 23.4, 0.0, 5.4, 10.0, 'W', 41, 'W', 'E', 15, 11, 68, 43, 1021.2, 1015.7, 0, 1, 11.2, 21.3, 'No', 'No'), ('7/22/2009', 11.2, 24.7, 0.0, 4.8, 8.0, 'W', 41, 'NW', 'NNW', 15, 24, 54, 39, 1011.5, 1005.4, 2, 4, 19.7, 24.0, 'No', 'Yes'), ('7/23/2009', 11.4, 18.3, 3.6, 5.6, 8.1, 'W', 41, 'NNW', 'SSW', 4, 19, 62, 42, 1012.7, 1014.5, 1, 4, 13.6, 16.4, 'Yes', 'No'), ('7/24/2009', 8.4, 17.5, 0.6, 2.2, 9.4, 'W', 41, 'W', 'E', 20, 9, 62, 51, 1026.0, 1024.6, 1, 2, 9.9, 16.1, 'No', 'No'), ('7/25/2009', 7.6, 18.6, 0.0, 1.8, 9.9, 'W', 41, 'W', 'ENE', 15, 17, 81, 54, 1026.1, 1022.1, 0, 1, 8.9, 15.5, 'No', 'No'), ('7/26/2009', 8.9, 15.3, 0.0, 5.8, 0.3, 'W', 41, 'W', 'W', 4, 9, 83, 68, 1019.1, 1014.2, 7, 8, 9.9, 14.1, 'No', 'Yes'), ('7/27/2009', 8.3, 18.9, 12.2, 0.4, 9.0, 'W', 41, 'W', 'WSW', 19, 17, 72, 34, 1016.3, 1015.4, 1, 1, 10.5, 18.8, 'Yes', 'No'), ('7/28/2009', 8.1, 18.7, 0.0, 3.6, 10.0, 'W', 41, 'W', 'WSW', 11, 20, 63, 38, 1022.5, 1020.2, 1, 1, 11.2, 17.9, 'No', 'No'), ('7/29/2009', 9.5, 19.5, 0.0, 2.2, 9.1, 'W', 41, 'WNW', 'WSW', 17, 9, 61, 41, 1024.3, 1022.3, 1, 5, 11.3, 18.7, 'No', 'No'), ('7/30/2009', 8.5, 18.9, 0.0, 4.0, 9.5, 'W', 41, 'W', 'W', 22, 15, 65, 39, 1024.4, 1019.3, 1, 1, 10.7, 18.7, 'No', 'No'), ('7/31/2009', 9.2, 19.7, 0.0, 3.0, 8.5, 'W', 41, 'NNW', 'W', 9, 22, 66, 38, 1020.0, 1017.9, 5, 2, 12.8, 18.4, 'No', 'No'), ('8/1/2009', 9.2, 19.2, 0.0, 3.8, 10.2, 'W', 41, 'W', 'WNW', 20, 11, 60, 33, 1025.4, 1021.4, 0, 1, 11.5, 18.8, 'No', 'No'), ('8/2/2009', 7.9, 19.2, 0.0, 4.0, 10.1, 'W', 41, 'W', 'E', 20, 13, 63, 46, 1027.7, 1022.7, 1, 1, 10.2, 17.3, 'No', 'No'), ('8/3/2009', 8.3, 20.5, 0.0, 4.0, 8.8, 'W', 41, 'WNW', 'W', 13, 22, 58, 29, 1020.3, 1019.6, 3, 6, 13.4, 19.9, 'No', 'No'), ('8/4/2009', 10.0, 19.8, 0.0, 3.2, 5.1, 'W', 41, 'W', 'W', 11, 13, 70, 33, 1021.7, 1017.4, 7, 3, 11.7, 18.2, 'No', 'No'), ('8/5/2009', 7.6, 19.3, 0.0, 2.8, 9.9, 'W', 41, 'W', 'ESE', 17, 15, 69, 40, 1022.8, 1020.4, 4, 1, 10.5, 17.5, 'No', 'No'), ('8/6/2009', 8.0, 19.5, 0.0, 2.0, 9.2, 'W', 41, 'W', 'NE', 13, 15, 73, 55, 1023.6, 1019.2, 7, 3, 11.2, 17.6, 'No', 'No'), ('8/7/2009', 11.0, 23.5, 0.0, 4.8, 8.9, 'W', 41, 'NNW', 'WNW', 22, 24, 47, 21, 1015.8, 1009.4, 3, 4, 15.4, 23.2, 'No', 'No'), ('8/8/2009', 7.8, 16.8, 0.0, 6.4, 9.9, 'W', 41, 'W', 'S', 22, 17, 46, 41, 1023.4, 1020.8, 2, 1, 9.8, 15.9, 'No', 'No'), ('8/9/2009', 5.9, 16.8, 0.0, 2.6, 8.4, 'W', 41, 'W', 'E', 17, 15, 70, 55, 1020.8, 1017.9, 3, 4, 8.5, 16.0, 'No', 'No'), ('8/10/2009', 6.8, 16.3, 0.0, 1.8, 4.1, 'W', 41, 'WNW', 'E', 11, 15, 77, 59, 1019.8, 1017.0, 7, 8, 9.1, 15.7, 'No', 'No'), ('8/11/2009', 9.1, 16.8, 0.0, 1.2, 2.4, 'W', 41, 'W', 'N', 13, 13, 81, 64, 1016.3, 1012.5, 7, 6, 11.7, 16.3, 'No', 'Yes'), ('8/12/2009', 8.9, 19.8, 4.2, 1.6, 9.7, 'W', 41, 'W', 'WNW', 19, 11, 77, 32, 1012.6, 1009.4, 4, 4, 11.9, 19.6, 'Yes', 'No'), ('8/13/2009', 9.0, 21.0, 0.0, 5.4, 10.2, 'W', 41, 'W', 'WSW', 9, 19, 63, 35, 1014.1, 1011.7, 0, 1, 12.8, 20.5, 'No', 'No'), ('8/14/2009', 10.8, 21.0, 0.0, 3.0, 9.9, 'W', 41, 'W', 'E', 20, 17, 61, 62, 1019.1, 1016.5, 3, 1, 14.0, 17.9, 'No', 'No'), ('8/15/2009', 8.7, 22.1, 0.0, 3.2, 10.5, 'W', 41, 'WNW', 'WNW', 13, 9, 77, 35, 1019.6, 1016.2, 0, 0, 11.1, 22.1, 'No', 'No'), ('8/16/2009', 9.4, 25.7, 0.0, 2.0, 10.2, 'W', 41, 'W', 'NE', 6, 19, 66, 27, 1015.7, 1009.0, 1, 2, 13.0, 25.2, 'No', 'No'), ('8/17/2009', 13.0, 22.9, 0.0, 8.0, 10.2, 'W', 41, 'W', 'SW', 22, 13, 37, 20, 1013.4, 1013.7, 0, 1, 18.5, 22.7, 'No', 'No'), ('8/18/2009', 9.0, 18.9, 0.0, 6.2, 10.4, 'W', 41, 'W', 'E', 19, 15, 48, 45, 1028.0, 1026.3, 1, 1, 12.1, 17.0, 'No', 'No'), ('8/19/2009', 7.8, 17.9, 0.0, 4.2, 10.4, 'W', 41, 'WNW', 'NE', 13, 20, 70, 50, 1027.7, 1023.2, 0, 1, 10.8, 17.5, 'No', 'No'), ('8/20/2009', 9.9, 21.1, 0.0, 2.8, 4.9, 'W', 41, 'W', 'E', 13, 13, 74, 58, 1019.5, 1014.2, 7, 2, 12.2, 19.0, 'No', 'No'), ('8/21/2009', 11.1, 25.0, 0.0, 4.0, 4.8, 'W', 41, 'N', 'NNE', 13, 20, 47, 33, 1009.2, 1002.1, 2, 6, 18.4, 25.0, 'No', 'No'), ('8/22/2009', 14.5, 20.8, 0.0, 7.0, 6.3, 'W', 41, 'SSW', 'ENE', 7, 17, 51, 47, 1012.7, 1009.9, 7, 2, 15.3, 17.9, 'No', 'No'), ('8/23/2009', 13.3, 25.1, 0.0, 3.6, 10.2, 'W', 41, 'W', 'ENE', 13, 17, 64, 51, 1012.0, 1007.8, 1, 2, 17.0, 22.3, 'No', 'No'), ('8/24/2009', 17.0, 23.9, 0.0, 5.6, 3.5, 'W', 41, 'W', 'NW', 26, 19, 47, 59, 1006.1, 1005.9, 2, 8, 23.3, 18.9, 'No', 'Yes'), ('8/25/2009', 15.6, 20.2, 1.6, 5.0, 10.5, 'W', 41, 'W', 'WNW', 31, 22, 29, 26, 1007.1, 1006.8, 1, 1, 15.8, 19.5, 'Yes', 'No'), ('8/26/2009', 12.0, 21.6, 0.0, 8.4, 10.9, 'W', 41, 'WNW', 'WNW', 13, 24, 32, 20, 1013.1, 1010.8, 0, 0, 15.1, 21.3, 'No', 'No'), ('8/27/2009', 11.3, 20.9, 0.0, 6.0, 11.0, 'W', 41, 'E', 'NE', 4, 17, 44, 37, 1017.6, 1013.5, 0, 0, 16.0, 20.4, 'No', 'No'), ('8/28/2009', 10.6, 24.8, 0.0, 3.2, 10.2, 'W', 41, 'W', 'NE', 2, 17, 44, 21, 1016.4, 1013.1, 0, 1, 17.2, 22.0, 'No', 'No'), ('8/29/2009', 14.8, 25.7, 0.0, 9.2, 5.2, 'W', 41, 'NNW', 'NE', 20, 15, 51, 59, 1008.9, 998.9, 8, 4, 16.6, 20.4, 'No', 'No'), ('8/30/2009', 13.7, 19.5, 0.2, 9.2, 10.9, 'W', 41, 'W', 'W', 30, 30, 34, 23, 1011.4, 1010.6, 1, 1, 13.9, 18.8, 'No', 'No'), ('8/31/2009', 9.2, 21.5, 0.0, 6.0, 10.9, 'W', 41, 'WNW', 'W', 20, 13, 40, 30, 1017.4, 1014.0, 1, 1, 14.7, 21.4, 'No', 'No'), ('9/1/2009', 11.1, 22.0, 0.0, 4.2, 10.7, 'W', 41, 'W', 'ESE', 13, 19, 49, 36, 1021.6, 1019.6, 1, 1, 16.1, 19.2, 'No', 'No'), ('9/2/2009', 9.7, 18.7, 0.0, 3.8, 10.9, 'W', 41, 'WNW', 'E', 11, 19, 60, 58, 1024.7, 1021.8, 0, 1, 14.4, 17.7, 'No', 'No'), ('9/3/2009', 12.0, 21.1, 0.0, 4.6, 4.7, 'W', 41, 'W', 'W', 11, 11, 80, 84, 1020.7, 1018.9, 3, 8, 15.2, 16.3, 'No', 'Yes'), ('9/4/2009', 14.7, 25.3, 6.0, 1.8, 6.9, 'W', 41, 'W', 'WNW', 11, 13, 81, 43, 1014.8, 1010.0, 7, 5, 16.0, 25.0, 'Yes', 'No'), ('9/5/2009', 14.7, 21.2, 0.0, 6.4, 10.2, 'W', 41, 'WSW', 'ESE', 19, 17, 36, 35, 1016.1, 1015.1, 2, 1, 18.2, 19.8, 'No', 'No'), ('9/6/2009', 10.4, 18.2, 0.0, 3.8, 10.0, 'W', 41, 'W', 'ENE', 13, 26, 53, 58, 1018.9, 1014.0, 3, 1, 14.4, 17.7, 'No', 'No'), ('9/7/2009', 13.5, 19.9, 0.0, 5.4, 2.1, 'W', 41, 'W', 'NE', 17, 28, 74, 57, 1008.5, 1000.8, 7, 6, 14.6, 19.1, 'No', 'Yes'), ('9/8/2009', 11.6, 21.1, 5.4, 3.6, 8.3, 'W', 41, 'W', 'ENE', 7, 11, 56, 56, 1008.2, 1007.6, 1, 6, 16.2, 17.0, 'Yes', 'No'), ('9/9/2009', 10.3, 20.8, 0.2, 3.6, 11.2, 'W', 41, 'W', 'WSW', 20, 26, 47, 35, 1010.2, 1008.8, 1, 3, 15.7, 20.4, 'No', 'No'), ('9/10/2009', 10.0, 22.2, 0.0, 5.0, 10.9, 'W', 41, 'W', 'E', 20, 24, 45, 38, 1015.9, 1013.9, 1, 1, 16.0, 19.8, 'No', 'No'), ('9/11/2009', 9.5, 22.4, 0.0, 5.0, 10.7, 'W', 41, 'WNW', 'E', 15, 20, 50, 47, 1022.6, 1019.4, 0, 1, 15.2, 18.4, 'No', 'No'), ('9/12/2009', 11.0, 28.5, 0.0, 6.0, 10.9, 'W', 41, 'WNW', 'NE', 11, 9, 49, 27, 1022.5, 1019.1, 0, 0, 17.3, 25.5, 'No', 'No'), ('9/13/2009', 17.3, 32.2, 0.0, 8.2, 10.9, 'W', 41, 'NNW', 'E', 20, 13, 24, 17, 1019.6, 1015.5, 0, 0, 25.2, 31.9, 'No', 'No'), ('9/14/2009', 18.1, 19.7, 0.0, 7.4, 6.2, 'W', 41, 'S', 'SSE', 30, 20, 70, 60, 1021.8, 1021.3, 5, 6, 18.5, 18.4, 'No', 'No'), ('9/15/2009', 15.4, 20.4, 0.0, 6.4, 6.9, 'W', 41, 'W', 'NE', 9, 17, 77, 66, 1021.4, 1016.4, 7, 6, 16.9, 19.7, 'No', 'No'), ('9/16/2009', 15.6, 22.2, 0.0, 3.4, 0.0, 'W', 41, 'SW', 'SSE', 9, 11, 80, 79, 1023.0, 1019.7, 8, 7, 17.4, 19.5, 'No', 'No'), ('9/17/2009', 14.7, 32.1, 0.0, 1.6, 7.6, 'W', 41, 'SE', 'NNW', 4, 31, 68, 25, 1017.0, 1010.1, 2, 6, 22.2, 31.2, 'No', 'No'), ('9/18/2009', 19.0, 23.5, 0.0, 10.4, 10.2, 'W', 41, 'SW', 'SE', 17, 30, 43, 51, 1017.9, 1018.4, 3, 1, 22.7, 21.2, 'No', 'No'), ('9/19/2009', 13.1, 20.8, 0.0, 5.4, 9.7, 'W', 41, 'W', 'E', 9, 20, 63, 63, 1019.2, 1013.0, 1, 3, 18.3, 19.4, 'No', 'No'), ('9/20/2009', 13.8, 24.7, 0.0, 5.8, 8.5, 'W', 41, 'WNW', 'NE', 9, 15, 49, 30, 1014.8, 1010.9, 4, 6, 20.7, 23.7, 'No', 'No'), ('9/21/2009', 15.7, 25.8, 0.0, 8.2, 8.1, 'W', 41, 'S', 'E', 13, 17, 69, 67, 1014.7, 1012.0, 3, 8, 18.8, 19.3, 'No', 'No'), ('9/22/2009', 17.1, 31.7, 0.0, 3.4, 8.2, 'W', 41, 'NW', 'NNW', 24, 31, 45, 34, 1002.8, 998.3, 0, 1, 25.8, 30.9, 'No', 'Yes'), ('9/23/2009', 17.0, 21.8, 4.4, 11.2, 8.0, 'W', 41, 'W', 'W', 30, 37, 40, 36, 996.8, 997.8, 9, 3, 17.3, 20.9, 'Yes', 'No'), ('9/24/2009', 15.1, 25.0, 0.0, 7.6, 11.3, 'W', 41, 'W', 'WNW', 31, 17, 36, 26, 1012.1, 1009.6, 1, 1, 18.8, 24.0, 'No', 'No'), ('9/25/2009', 13.5, 25.4, 0.0, 8.0, 11.2, 'W', 41, 'N', 'NE', 17, 24, 36, 33, 1013.5, 1007.0, 0, 0, 21.0, 22.4, 'No', 'No'), ('9/26/2009', 17.1, 19.6, 0.0, 11.2, 9.0, 'W', 41, 'W', 'W', 15, 33, 24, 19, 1004.3, 1004.5, 1, 3, 17.7, 18.4, 'No', 'No'), ('9/27/2009', 10.1, 17.2, 0.0, 8.0, 10.8, 'W', 41, 'W', 'W', 39, 35, 30, 23, 1006.4, 1004.1, 1, 3, 13.9, 16.9, 'No', 'No'), ('9/28/2009', 11.0, 21.4, 0.0, 8.2, 7.8, 'W', 41, 'W', 'S', 30, 9, 39, 31, 1007.6, 1005.6, 1, 3, 15.2, 19.7, 'No', 'No'), ('9/29/2009', 11.4, 21.0, 0.0, 4.0, 11.1, 'W', 41, 'W', 'E', 17, 19, 42, 45, 1014.1, 1011.8, 1, 2, 17.0, 18.8, 'No', 'No'), ('9/30/2009', 10.9, 25.6, 0.0, 5.4, 11.0, 'W', 41, 'W', 'ENE', 9, 20, 57, 34, 1017.7, 1012.6, 2, 3, 18.4, 22.0, 'No', 'No'), ('10/1/2009', 14.9, 33.1, 0.0, 7.0, 10.8, 'W', 41, 'NW', 'E', 15, 19, 21, 10, 1013.4, 1007.7, 3, 1, 25.6, 32.8, 'No', 'No'), ('10/2/2009', 16.5, 20.7, 0.0, 10.2, 0.5, 'W', 41, 'W', 'SE', 15, 15, 72, 68, 1013.4, 1010.0, 7, 8, 18.3, 19.4, 'No', 'Yes'), ('10/3/2009', 13.6, 15.2, 12.6, 3.0, 0.0, 'W', 41, 'SSW', 'S', 22, 19, 91, 89, 1011.9, 1014.1, 8, 8, 13.8, 14.5, 'Yes', 'Yes'), ('10/4/2009', 12.9, 17.0, 38.2, 2.4, 0.0, 'W', 41, 'E', 'E', 6, 19, 88, 61, 1021.5, 1019.8, 8, 7, 13.5, 16.6, 'Yes', 'Yes'), ('10/5/2009', 13.1, 20.2, 3.4, 1.8, 2.2, 'W', 41, 'W', 'E', 13, 11, 91, 65, 1020.3, 1017.1, 7, 7, 14.2, 18.4, 'Yes', 'Yes'), ('10/6/2009', 11.5, 19.6, 6.6, 2.6, 6.4, 'W', 41, 'W', 'E', 22, 17, 77, 64, 1020.6, 1016.7, 6, 4, 13.5, 18.0, 'Yes', 'Yes'), ('10/7/2009', 10.6, 19.3, 7.0, 3.6, 8.8, 'W', 41, 'W', 'WSW', 20, 22, 51, 29, 1014.2, 1011.3, 1, 5, 14.1, 18.5, 'Yes', 'Yes'), ('10/8/2009', 10.5, 17.5, 2.2, 6.8, 7.4, 'W', 41, 'SW', 'SSW', 26, 39, 49, 48, 1018.0, 1019.9, 6, 5, 13.8, 16.9, 'Yes', 'No'), ('10/9/2009', 9.6, 17.1, 0.0, 5.2, 4.7, 'W', 41, 'WSW', 'S', 15, 17, 65, 76, 1025.4, 1026.0, 5, 6, 13.5, 13.9, 'No', 'Yes'), ('10/10/2009', 8.9, 18.6, 24.4, 3.4, 6.7, 'W', 41, 'W', 'S', 15, 19, 84, 59, 1029.7, 1027.3, 4, 7, 12.0, 17.6, 'Yes', 'Yes'), ('10/11/2009', 11.8, 19.3, 2.2, 3.4, 6.7, 'W', 41, 'W', 'NNE', 15, 11, 91, 57, 1025.2, 1019.8, 7, 7, 13.1, 19.2, 'Yes', 'No'), ('10/12/2009', 11.3, 22.6, 0.0, 4.8, 4.7, 'W', 41, 'E', 'E', 4, 6, 61, 63, 1011.8, 1006.4, 2, 8, 17.8, 21.1, 'No', 'No'), ('10/13/2009', 17.0, 24.5, 0.0, 5.0, 11.2, 'W', 41, 'W', 'WNW', 26, 35, 38, 21, 1002.0, 998.7, 1, 2, 20.1, 24.0, 'No', 'No'), ('10/14/2009', 15.2, 22.1, 0.0, 11.2, 8.9, 'W', 41, 'NW', 'WNW', 20, 30, 36, 34, 1000.7, 1000.7, 1, 5, 19.7, 17.8, 'No', 'No'), ('10/15/2009', 13.8, 23.0, 0.0, 7.6, 10.0, 'W', 41, 'WNW', 'WNW', 11, 24, 46, 28, 1008.4, 1006.2, 6, 7, 18.8, 22.0, 'No', 'No'), ('10/16/2009', 11.8, 21.2, 0.0, 7.4, 12.1, 'W', 41, 'W', 'W', 33, 26, 42, 19, 1012.0, 1011.8, 1, 2, 15.1, 20.5, 'No', 'No'), ('10/17/2009', 11.6, 21.2, 0.0, 8.0, 12.2, 'W', 41, 'WNW', 'SE', 15, 20, 53, 43, 1020.8, 1020.6, 1, 1, 16.8, 20.3, 'No', 'Yes'), ('10/18/2009', 13.8, 18.8, 7.0, 5.8, 7.9, 'W', 41, 'ENE', 'ESE', 4, 17, 80, 61, 1027.4, 1025.3, 6, 3, 15.5, 18.5, 'Yes', 'No'), ('10/19/2009', 12.4, 20.8, 1.0, 4.4, 12.2, 'W', 41, 'W', 'E', 7, 19, 71, 57, 1027.1, 1024.7, 1, 1, 16.6, 20.4, 'No', 'No'), ('10/20/2009', 14.3, 23.0, 0.0, 5.8, 12.1, 'W', 41, 'W', 'ENE', 9, 22, 71, 62, 1023.5, 1018.7, 0, 0, 19.0, 22.0, 'No', 'No'), ('10/21/2009', 15.6, 34.6, 0.0, 7.6, 11.6, 'W', 41, 'WNW', 'E', 15, 19, 44, 28, 1019.8, 1016.8, 1, 3, 21.1, 29.7, 'No', 'No'), ('10/22/2009', 17.9, 21.3, 0.0, 9.4, 1.2, 'W', 41, 'ESE', 'E', 9, 17, 67, 63, 1024.9, 1022.6, 8, 7, 18.5, 20.0, 'No', 'No'), ('10/23/2009', 17.5, 22.9, 0.0, 5.0, 11.1, 'W', 41, 'NNW', 'E', 7, 22, 66, 70, 1019.9, 1014.7, 3, 1, 21.3, 21.6, 'No', 'No'), ('10/24/2009', 16.8, 22.1, 0.0, 7.0, 9.2, 'W', 41, 'SSE', 'E', 17, 19, 63, 56, 1019.5, 1016.3, 4, 1, 19.7, 20.9, 'No', 'No'), ('10/25/2009', 17.9, 20.9, 0.0, 5.6, 1.1, 'W', 41, 'E', 'WNW', 7, 7, 72, 94, 1016.0, 1015.7, 7, 8, 20.3, 16.5, 'No', 'Yes'), ('10/26/2009', 14.4, 17.0, 73.2, 4.8, 0.0, 'W', 41, 'SE', 'SE', 31, 26, 91, 60, 1023.7, 1025.3, 8, 8, 14.7, 16.6, 'Yes', 'Yes'), ('10/27/2009', 14.7, 18.8, 1.4, 3.8, 0.0, 'W', 41, 'ESE', 'E', 22, 13, 58, 56, 1029.5, 1027.7, 8, 8, 17.0, 18.4, 'Yes', 'No'), ('10/30/2009', 17.3, 23.4, 0.0, 4.0, 9.8, 'W', 41, 'E', 'ENE', 11, 22, 78, 60, 1023.2, 1020.6, 5, 1, 20.5, 22.8, 'No', 'No'), ('10/31/2009', 18.7, 22.8, 0.0, 7.4, 10.3, 'W', 41, 'ENE', 'E', 17, 30, 80, 65, 1025.2, 1023.4, 6, 1, 20.0, 22.1, 'No', 'No'), ('11/1/2009', 16.9, 24.2, 0.0, 8.0, 10.1, 'W', 41, 'NNE', 'NE', 19, 26, 62, 58, 1024.5, 1019.9, 1, 1, 21.7, 23.4, 'No', 'No'), ('11/2/2009', 18.8, 26.0, 0.0, 7.0, 6.9, 'W', 41, 'SSW', 'ESE', 17, 19, 82, 68, 1021.0, 1017.5, 8, 7, 20.6, 24.5, 'No', 'No'), ('11/3/2009', 18.9, 36.9, 0.0, 6.2, 11.0, 'W', 41, 'ESE', 'WNW', 9, 30, 73, 18, 1011.9, 1006.6, 6, 6, 24.0, 36.3, 'No', 'No'), ('11/4/2009', 19.4, 19.9, 0.0, 13.2, 0.0, 'W', 41, 'SE', 'E', 11, 17, 71, 76, 1017.9, 1015.5, 8, 8, 19.7, 19.1, 'No', 'No'), ('11/5/2009', 16.9, 19.8, 0.0, 2.2, 1.1, 'W', 41, 'SE', 'ESE', 13, 24, 75, 68, 1020.9, 1021.9, 7, 7, 19.4, 19.1, 'No', 'Yes'), ('11/6/2009', 16.7, 21.3, 1.4, 3.0, 0.8, 'W', 41, 'ESE', 'E', 24, 19, 66, 57, 1027.6, 1027.1, 7, 7, 19.2, 20.8, 'Yes', 'Yes'), ('11/7/2009', 17.2, 22.9, 4.2, 4.2, 6.2, 'W', 41, 'E', 'E', 20, 19, 69, 60, 1030.5, 1030.0, 6, 6, 20.9, 22.5, 'Yes', 'No'), ('11/8/2009', 19.1, 21.9, 0.0, 6.4, 0.7, 'W', 41, 'ESE', 'E', 9, 15, 75, 89, 1030.7, 1028.8, 8, 8, 20.4, 19.9, 'No', 'No'), ('11/9/2009', 19.1, 23.2, 0.8, 2.6, 11.0, 'W', 41, 'ENE', 'E', 19, 19, 77, 61, 1027.2, 1024.0, 6, 1, 20.9, 22.8, 'No', 'No'), ('11/10/2009', 15.9, 23.9, 0.0, 5.4, 12.8, 'W', 41, 'NNE', 'ENE', 4, 26, 61, 54, 1022.5, 1020.0, 1, 0, 21.6, 23.2, 'No', 'No'), ('11/11/2009', 15.4, 23.9, 0.0, 10.2, 12.4, 'W', 41, 'W', 'E', 15, 19, 74, 64, 1022.6, 1021.3, 1, 1, 21.0, 23.1, 'No', 'No'), ('11/12/2009', 16.6, 26.7, 0.0, 6.8, 11.2, 'W', 41, 'NNW', 'NNE', 17, 20, 70, 54, 1020.0, 1013.4, 0, 6, 22.0, 26.0, 'No', 'Yes'), ('11/13/2009', 19.5, 23.0, 4.0, 8.8, 9.7, 'W', 41, 'S', 'SSE', 26, 26, 66, 60, 1020.1, 1019.2, 6, 5, 21.7, 22.5, 'Yes', 'No'), ('11/14/2009', 15.0, 24.3, 0.2, 6.2, 12.6, 'W', 41, 'WSW', 'ENE', 6, 26, 66, 56, 1016.4, 1011.4, 2, 2, 20.1, 23.4, 'No', 'No'), ('11/15/2009', 18.5, 25.1, 0.0, 8.8, 9.3, 'W', 41, 'S', 'SE', 17, 20, 74, 63, 1012.1, 1011.7, 4, 5, 22.2, 23.8, 'No', 'No'), ('11/16/2009', 18.7, 27.6, 0.0, 6.4, 10.3, 'W', 41, 'W', 'E', 6, 19, 72, 62, 1008.8, 1002.0, 5, 7, 22.6, 26.6, 'No', 'Yes'), ('11/17/2009', 19.4, 23.6, 1.4, 8.8, 5.0, 'W', 41, 'SSE', 'SSE', 20, 28, 61, 59, 1008.7, 1009.7, 7, 7, 21.1, 21.0, 'Yes', 'No'), ('11/18/2009', 17.8, 23.8, 0.0, 7.2, 6.6, 'W', 41, 'E', 'ENE', 4, 26, 72, 51, 1013.2, 1010.3, 7, 2, 19.8, 23.2, 'No', 'No'), ('11/19/2009', 18.4, 26.5, 0.0, 8.0, 10.6, 'W', 41, 'E', 'ENE', 9, 13, 70, 63, 1010.3, 1009.2, 3, 3, 23.6, 26.0, 'No', 'No'), ('11/20/2009', 21.0, 33.2, 0.0, 8.8, 7.6, 'W', 41, 'NW', 'E', 9, 4, 71, 52, 1009.8, 1005.7, 0, 8, 26.2, 29.0, 'No', 'No'), ('11/21/2009', 22.0, 31.5, 0.0, 12.4, 10.3, 'W', 41, 'WSW', 'SE', 4, 13, 56, 45, 1009.8, 1006.6, 7, 7, 25.4, 30.2, 'No', 'No'), ('11/22/2009', 21.2, 40.4, 0.0, 7.4, 6.0, 'W', 41, 'ENE', 'N', 11, 26, 75, 19, 1005.0, 1001.5, 6, 7, 24.0, 39.8, 'No', 'No'), ('11/23/2009', 19.9, 22.8, 0.0, 13.4, 0.3, 'W', 41, 'SSE', 'SSE', 28, 30, 62, 68, 1021.0, 1022.6, 7, 8, 21.4, 20.4, 'No', 'No'), ('11/24/2009', 18.1, 21.5, 0.0, 5.2, 2.1, 'W', 41, 'SSE', 'SSE', 13, 13, 84, 74, 1026.2, 1024.3, 8, 8, 18.7, 20.6, 'No', 'No'), ('11/25/2009', 18.3, 25.0, 0.2, 3.0, 12.2, 'W', 41, 'W', 'E', 4, 30, 82, 74, 1022.3, 1018.4, 2, 0, 21.3, 24.0, 'No', 'No'), ('11/26/2009', 21.3, 26.6, 0.0, 7.8, 8.4, 'W', 41, 'NE', 'NE', 15, 20, 80, 67, 1017.5, 1011.2, 7, 1, 22.3, 24.8, 'No', 'No'), ('11/27/2009', 21.3, 33.2, 1.0, 7.8, 12.4, 'W', 41, 'WNW', 'E', 17, 24, 50, 41, 1009.7, 1007.1, 1, 1, 26.1, 28.7, 'No', 'No'), ('11/28/2009', 21.1, 29.3, 0.0, 12.8, 9.5, 'W', 41, 'E', 'NE', 7, 22, 63, 51, 1006.4, 1000.2, 0, 6, 26.0, 28.2, 'No', 'No'), ('11/29/2009', 19.5, 30.5, 0.0, 10.6, 12.4, 'W', 41, 'WNW', 'W', 13, 28, 28, 20, 1000.9, 998.7, 0, 5, 25.3, 29.3, 'No', 'No'), ('11/30/2009', 18.1, 23.1, 0.0, 11.8, 3.9, 'W', 41, 'SSW', 'S', 19, 33, 55, 61, 1008.1, 1009.2, 4, 7, 21.2, 19.6, 'No', 'Yes'), ('12/1/2009', 14.3, 21.2, 4.4, 6.4, 9.6, 'W', 41, 'S', 'S', 22, 24, 58, 59, 1016.1, 1017.4, 2, 5, 17.9, 19.4, 'Yes', 'Yes'), ('12/2/2009', 13.5, 22.6, 10.2, 6.4, 11.2, 'W', 41, 'SSW', 'SE', 17, 22, 69, 44, 1022.0, 1021.7, 7, 2, 17.3, 21.5, 'Yes', 'No'), ('12/3/2009', 15.2, 22.6, 0.0, 6.8, 12.9, 'W', 41, 'WNW', 'ENE', 2, 30, 58, 52, 1022.6, 1017.9, 1, 1, 19.7, 22.0, 'No', 'No'), ('12/4/2009', 17.3, 24.4, 0.0, 8.0, 12.5, 'W', 41, 'S', 'SSE', 26, 30, 69, 61, 1015.6, 1015.6, 0, 5, 21.8, 22.5, 'No', 'No'), ('12/5/2009', 18.2, 23.4, 0.0, 9.8, 6.5, 'W', 41, 'ENE', 'E', 2, 20, 59, 64, 1015.2, 1012.6, 7, 6, 20.2, 22.0, 'No', 'No'), ('12/6/2009', 18.7, 25.6, 0.0, 6.2, 10.5, 'W', 41, 'ENE', 'ENE', 11, 30, 61, 58, 1017.3, 1015.0, 5, 1, 23.4, 23.8, 'No', 'No'), ('12/7/2009', 21.7, 28.5, 0.0, 8.2, 11.1, 'W', 41, 'E', 'E', 11, 20, 67, 62, 1011.8, 1007.4, 1, 2, 25.4, 27.3, 'No', 'No'), ('12/8/2009', 20.1, 27.6, 0.0, 10.2, 8.8, 'W', 41, 'WNW', 'E', 9, 26, 68, 70, 1009.1, 1000.8, 7, 3, 22.6, 24.1, 'No', 'No'), ('12/9/2009', 18.4, 24.0, 0.6, 8.2, 9.8, 'W', 41, 'S', 'ESE', 17, 24, 76, 59, 1011.1, 1010.2, 6, 5, 19.2, 22.0, 'No', 'No'), ('12/10/2009', 19.2, 28.8, 0.0, 7.8, 1.2, 'W', 41, 'NNW', 'NE', 4, 20, 75, 70, 1011.0, 1006.0, 8, 8, 23.4, 24.8, 'No', 'No'), ('12/11/2009', 19.9, 28.8, 0.0, 7.0, 12.9, 'W', 41, 'WSW', 'ESE', 11, 24, 30, 30, 1012.7, 1013.1, 2, 1, 24.1, 25.1, 'No', 'No'), ('12/12/2009', 16.9, 27.1, 0.0, 11.4, 13.0, 'W', 41, 'NNW', 'ENE', 7, 28, 57, 55, 1018.7, 1014.0, 1, 1, 22.7, 24.8, 'No', 'No'), ('12/13/2009', 20.3, 27.4, 0.0, 8.4, 11.1, 'W', 41, 'S', 'SE', 15, 31, 68, 61, 1016.3, 1015.2, 3, 1, 23.5, 25.9, 'No', 'No'), ('12/14/2009', 20.0, 24.3, 0.0, 9.0, 0.0, 'W', 41, 'ESE', 'ESE', 11, 19, 72, 69, 1021.2, 1021.1, 7, 8, 21.3, 21.1, 'No', 'No'), ('12/15/2009', 19.1, 24.5, 0.0, 4.8, 4.3, 'W', 41, 'NE', 'ENE', 15, 22, 59, 62, 1022.5, 1020.3, 6, 7, 24.3, 23.6, 'No', 'No'), ('12/16/2009', 21.7, 26.5, 0.0, 9.2, 10.6, 'W', 41, 'NE', 'NE', 13, 28, 74, 70, 1020.3, 1016.1, 4, 1, 24.1, 26.0, 'No', 'No'), ('12/17/2009', 21.5, 32.0, 0.0, 10.4, 11.6, 'W', 41, 'E', 'NNE', 13, 37, 71, 51, 1013.7, 1008.5, 0, 5, 26.0, 29.8, 'No', 'Yes'), ('12/18/2009', 20.2, 21.4, 5.4, 13.6, 0.0, 'W', 41, 'NE', 'SSE', 11, 20, 87, 83, 1014.1, 1016.7, 8, 8, 20.2, 18.5, 'Yes', 'Yes'), ('12/19/2009', 16.9, 28.9, 8.0, 3.8, 10.0, 'W', 41, 'W', 'SSE', 15, 26, 70, 34, 1015.1, 1013.9, 0, 0, 21.4, 27.4, 'Yes', 'No'), ('12/20/2009', 19.6, 22.5, 0.0, 10.2, 0.0, 'W', 41, 'SE', 'E', 15, 11, 62, 59, 1021.2, 1019.8, 8, 8, 20.9, 21.8, 'No', 'No'), ('12/21/2009', 19.9, 24.9, 0.0, 4.4, 9.7, 'W', 41, 'NE', 'NE', 17, 26, 65, 64, 1016.9, 1012.6, 4, 6, 22.4, 23.3, 'No', 'No'), ('12/22/2009', 19.7, 29.4, 0.0, 9.0, 12.0, 'W', 41, 'SSW', 'ENE', 2, 19, 58, 53, 1011.5, 1009.7, 3, 5, 24.6, 27.1, 'No', 'No'), ('12/26/2009', 17.7, 20.2, 12.0, 2.8, 0.0, 'W', 41, 'SSW', 'SSW', 17, 20, 91, 85, 1016.2, 1016.4, 8, 8, 17.8, 18.6, 'Yes', 'Yes'), ('12/27/2009', 17.7, 22.9, 4.8, 1.8, 0.0, 'W', 41, 'SSW', 'SSE', 20, 13, 92, 80, 1017.9, 1016.1, 8, 8, 20.2, 22.3, 'Yes', 'Yes'), ('12/28/2009', 20.1, 23.1, 16.0, 2.6, 1.4, 'W', 41, 'SE', 'S', 13, 22, 97, 83, 1014.8, 1015.4, 8, 7, 20.6, 22.7, 'Yes', 'Yes'), ('12/29/2009', 19.8, 26.1, 5.4, 2.4, 11.9, 'W', 41, 'S', 'SE', 17, 17, 69, 55, 1021.4, 1021.2, 4, 1, 23.0, 25.9, 'Yes', 'No'), ('12/30/2009', 19.8, 25.2, 0.0, 8.6, 12.8, 'W', 41, 'S', 'SSE', 20, 20, 66, 57, 1025.0, 1023.1, 5, 4, 22.4, 24.5, 'No', 'No'), ('12/31/2009', 20.1, 24.8, 0.0, 8.0, 2.0, 'W', 41, 'W', 'ENE', 2, 11, 92, 83, 1020.9, 1017.2, 8, 8, 20.9, 23.3, 'No', 'No'), ('1/1/2010', 20.9, 29.3, 0.4, 2.8, 1.1, 'W', 41, 'E', 'E', 2, 19, 84, 56, 1013.9, 1010.4, 8, 7, 24.3, 29.0, 'No', 'No'), ('1/2/2010', 23.3, 30.7, 0.0, 6.8, 4.8, 'W', 41, 'W', 'E', 15, 19, 70, 79, 1007.7, 1005.7, 7, 7, 25.6, 24.9, 'No', 'Yes'), ('1/3/2010', 18.9, 21.5, 8.6, 7.0, 0.0, 'W', 41, 'W', 'E', 15, 19, 80, 74, 1015.3, 1016.0, 8, 8, 20.1, 20.8, 'Yes', 'No'), ('1/4/2010', 18.2, 23.9, 1.0, 2.4, 2.8, 'W', 41, 'E', 'ENE', 7, 19, 64, 58, 1020.6, 1019.1, 7, 7, 21.4, 23.2, 'No', 'No'), ('1/5/2010', 18.3, 26.1, 0.2, 4.6, 10.4, 'W', 41, 'ENE', 'ENE', 13, 20, 64, 60, 1018.1, 1014.6, 1, 2, 23.6, 25.7, 'No', 'No'), ('1/6/2010', 21.8, 27.6, 0.0, 8.4, 9.5, 'W', 41, 'S', 'SE', 15, 17, 83, 71, 1015.9, 1013.8, 7, 5, 22.5, 24.8, 'No', 'No'), ('1/7/2010', 20.8, 24.9, 0.0, 8.0, 0.8, 'W', 41, 'S', 'SE', 13, 15, 66, 59, 1018.3, 1017.4, 8, 8, 21.8, 23.4, 'No', 'No'), ('1/8/2010', 20.9, 25.6, 0.4, 6.0, 7.7, 'W', 41, 'E', 'E', 13, 24, 66, 59, 1021.7, 1019.7, 7, 2, 22.9, 25.5, 'No', 'No'), ('1/9/2010', 20.8, 32.4, 0.0, 5.4, 13.2, 'W', 41, 'WSW', 'NE', 2, 13, 76, 51, 1018.0, 1014.6, 1, 3, 24.4, 30.6, 'No', 'No'), ('1/10/2010', 24.1, 30.0, 0.0, 11.0, 12.7, 'W', 41, 'N', 'SSE', 2, 20, 65, 56, 1016.1, 1015.4, 1, 2, 28.3, 28.9, 'No', 'No'), ('1/11/2010', 22.1, 25.8, 0.0, 8.6, 7.8, 'W', 41, 'E', 'NE', 11, 24, 64, 60, 1019.4, 1016.1, 6, 3, 24.2, 25.8, 'No', 'No'), ('1/12/2010', 23.0, 30.3, 0.0, 8.8, 9.4, 'W', 41, 'N', 'ENE', 6, 26, 77, 65, 1013.0, 1008.5, 7, 1, 25.0, 28.4, 'No', 'No'), ('1/13/2010', 23.7, 27.7, 0.2, 9.2, 8.8, 'W', 41, 'SSE', 'SSE', 19, 35, 64, 69, 1010.9, 1011.0, 1, 6, 27.0, 25.4, 'No', 'Yes'), ('1/14/2010', 19.5, 22.9, 13.0, 7.8, 0.2, 'W', 41, 'S', 'S', 22, 17, 90, 75, 1017.7, 1017.6, 8, 8, 19.6, 21.0, 'Yes', 'No'), ('1/15/2010', 19.0, 25.1, 0.2, 3.8, 3.0, 'W', 41, 'SSW', 'ESE', 9, 17, 83, 74, 1018.9, 1017.2, 8, 7, 21.7, 24.4, 'No', 'No'), ('1/16/2010', 21.7, 25.9, 0.2, 5.4, 4.8, 'W', 41, 'NE', 'ENE', 11, 22, 72, 63, 1014.0, 1009.6, 6, 7, 23.4, 24.5, 'No', 'No'), ('1/17/2010', 20.3, 27.3, 0.0, 6.6, 10.3, 'W', 41, 'W', 'SSE', 0, 26, 64, 68, 1004.2, 1003.0, 3, 7, 24.6, 25.6, 'No', 'No'), ('1/18/2010', 16.7, 25.7, 0.0, 8.0, 13.0, 'W', 41, 'W', 'W', 15, 28, 55, 14, 1002.9, 1002.5, 1, 2, 21.0, 25.1, 'No', 'No'), ('1/19/2010', 15.6, 26.8, 0.0, 10.0, 13.3, 'W', 41, 'WSW', 'E', 15, 22, 39, 31, 1009.5, 1007.4, 1, 1, 19.8, 22.9, 'No', 'No'), ('1/20/2010', 17.4, 28.9, 0.0, 10.4, 13.0, 'W', 41, 'WNW', 'E', 7, 24, 41, 34, 1010.4, 1007.8, 0, 0, 23.2, 26.6, 'No', 'No'), ('1/21/2010', 19.5, 27.4, 0.0, 9.0, 12.8, 'W', 41, 'W', 'E', 6, 24, 74, 58, 1012.3, 1008.4, 3, 2, 24.0, 27.4, 'No', 'No'), ('1/22/2010', 22.6, 32.6, 0.0, 8.2, 9.6, 'W', 41, 'W', 'E', 7, 15, 77, 64, 1013.6, 1008.8, 3, 2, 25.0, 29.2, 'No', 'No'), ('1/23/2010', 25.0, 41.3, 0.0, 13.4, 5.6, 'W', 41, 'NW', 'SSE', 26, 6, 28, 17, 1007.8, 1005.4, 5, 5, 31.9, 39.9, 'No', 'Yes'), ('1/24/2010', 18.4, 23.0, 6.2, 8.6, 0.1, 'W', 41, 'SSW', 'ESE', 7, 11, 92, 66, 1016.3, 1014.5, 8, 8, 19.5, 22.6, 'Yes', 'No'), ('1/25/2010', 19.5, 26.1, 0.4, 3.6, 2.8, 'W', 41, 'WNW', 'E', 2, 19, 80, 70, 1014.8, 1011.8, 8, 7, 22.4, 25.7, 'No', 'No'), ('1/26/2010', 22.3, 29.0, 0.0, 4.0, 8.6, 'W', 41, 'NE', 'ENE', 6, 19, 83, 69, 1010.9, 1007.2, 6, 3, 25.1, 27.7, 'No', 'No'), ('1/27/2010', 22.9, 27.1, 0.0, 6.2, 4.6, 'W', 41, 'S', 'SSE', 19, 20, 78, 72, 1015.1, 1013.6, 8, 8, 23.4, 25.0, 'No', 'No'), ('1/28/2010', 22.2, 26.6, 0.0, 4.8, 1.8, 'W', 41, 'W', 'ENE', 0, 17, 80, 81, 1012.1, 1009.5, 8, 8, 23.7, 24.6, 'No', 'Yes'), ('1/29/2010', 19.6, 30.2, 2.6, 3.4, 9.5, 'W', 41, 'WNW', 'SE', 7, 20, 81, 53, 1008.6, 1010.0, 1, 1, 22.2, 29.6, 'Yes', 'Yes'), ('1/30/2010', 20.5, 27.3, 2.6, 6.4, 7.0, 'W', 41, 'S', 'SE', 26, 13, 82, 66, 1018.6, 1017.9, 8, 7, 21.6, 26.4, 'Yes', 'No'), ('1/31/2010', 21.5, 26.6, 0.0, 5.4, 9.2, 'W', 41, 'E', 'E', 19, 24, 75, 70, 1016.7, 1014.6, 6, 7, 25.6, 26.0, 'No', 'No'), ('2/1/2010', 22.6, 27.7, 0.0, 7.8, 7.9, 'W', 41, 'E', 'E', 13, 24, 73, 66, 1015.9, 1016.1, 6, 7, 25.6, 26.6, 'No', 'No'), ('2/2/2010', 22.7, 27.7, 0.6, 8.0, 9.8, 'W', 41, 'ESE', 'SE', 19, 30, 61, 60, 1017.8, 1016.4, 6, 7, 25.0, 25.9, 'No', 'Yes'), ('2/3/2010', 21.4, 27.3, 23.4, 6.4, 7.3, 'W', 41, 'E', 'E', 26, 26, 90, 66, 1014.9, 1014.3, 7, 4, 22.0, 27.2, 'Yes', 'Yes'), ('2/4/2010', 21.9, 27.2, 3.4, 6.0, 3.9, 'W', 41, 'E', 'E', 28, 28, 83, 76, 1013.9, 1011.3, 7, 7, 25.2, 26.1, 'Yes', 'Yes'), ('2/5/2010', 23.1, 26.5, 4.0, 4.8, 3.0, 'W', 41, 'NE', 'NNE', 11, 19, 79, 88, 1010.1, 1008.8, 7, 7, 25.8, 24.9, 'Yes', 'Yes'), ('2/6/2010', 20.5, 22.4, 31.2, 5.0, 0.0, 'W', 41, 'S', 'S', 31, 24, 95, 95, 1015.7, 1016.2, 7, 8, 21.6, 22.2, 'Yes', 'Yes'), ('2/7/2010', 20.2, 25.0, 77.4, 7.4, 0.2, 'W', 41, 'SSW', 'SE', 19, 15, 95, 86, 1021.6, 1020.8, 7, 8, 21.1, 23.8, 'Yes', 'Yes'), ('2/8/2010', 21.0, 27.6, 3.4, 1.8, 2.3, 'W', 41, 'ESE', 'E', 7, 22, 76, 70, 1022.9, 1021.9, 8, 7, 23.5, 26.3, 'Yes', 'No'), ('2/9/2010', 22.8, 27.6, 0.0, 5.8, 9.9, 'W', 41, 'W', 'E', 4, 24, 83, 65, 1023.0, 1021.2, 6, 3, 24.3, 27.3, 'No', 'No'), ('2/10/2010', 21.7, 27.9, 0.4, 5.8, 10.1, 'W', 41, 'NE', 'ENE', 9, 20, 72, 61, 1020.6, 1017.6, 2, 2, 25.6, 27.3, 'No', 'No'), ('2/11/2010', 21.4, 28.2, 0.0, 8.8, 6.9, 'W', 41, 'E', 'ENE', 4, 26, 71, 60, 1017.1, 1013.5, 2, 2, 25.3, 27.4, 'No', 'No'), ('2/12/2010', 23.9, 37.8, 0.0, 9.0, 9.8, 'W', 41, 'W', 'WNW', 2, 15, 71, 32, 1008.7, 1005.5, 6, 7, 26.9, 37.4, 'No', 'Yes'), ('2/13/2010', 21.4, 25.5, 70.0, 9.4, 0.3, 'W', 41, 'S', 'E', 17, 11, 92, 80, 1011.9, 1010.2, 8, 8, 22.1, 25.2, 'Yes', 'Yes'), ('2/14/2010', 22.1, 26.4, 10.0, 2.0, 1.4, 'W', 41, 'W', 'E', 9, 11, 91, 92, 1007.3, 1004.5, 7, 8, 23.5, 23.9, 'Yes', 'Yes'), ('2/15/2010', 20.2, 30.0, 15.2, 2.8, 9.9, 'W', 41, 'W', 'ENE', 11, 17, 95, 67, 1006.7, 1003.5, 6, 3, 21.4, 28.5, 'Yes', 'No'), ('2/16/2010', 21.3, 26.4, 0.2, 7.6, 8.7, 'W', 41, 'W', 'S', 22, 35, 65, 57, 1011.8, 1013.6, 7, 7, 22.3, 25.0, 'No', 'No'), ('2/17/2010', 18.5, 25.6, 0.0, 7.8, 12.8, 'W', 41, 'SW', 'SE', 9, 20, 64, 56, 1016.7, 1016.0, 3, 2, 21.4, 25.4, 'No', 'No'), ('2/18/2010', 18.3, 25.9, 0.0, 8.0, 12.0, 'W', 41, 'SE', 'SE', 19, 20, 52, 51, 1022.4, 1023.4, 5, 5, 23.7, 24.9, 'No', 'No'), ('2/19/2010', 20.2, 25.5, 0.0, 7.2, 8.0, 'W', 41, 'ESE', 'E', 19, 13, 60, 51, 1024.8, 1023.1, 5, 6, 22.6, 25.0, 'No', 'No'), ('2/20/2010', 18.9, 27.3, 0.0, 6.4, 11.8, 'W', 41, 'W', 'NE', 13, 24, 76, 54, 1021.9, 1018.4, 1, 2, 22.2, 26.1, 'No', 'No'), ('2/21/2010', 20.7, 29.8, 0.0, 9.6, 11.6, 'W', 41, 'W', 'E', 4, 15, 75, 59, 1018.0, 1014.8, 1, 1, 23.5, 28.6, 'No', 'No'), ('2/22/2010', 23.2, 35.4, 0.0, 9.4, 11.9, 'W', 41, 'W', 'E', 7, 20, 61, 46, 1015.4, 1011.7, 0, 3, 26.7, 32.5, 'No', 'No'), ('2/23/2010', 26.0, 28.6, 0.0, 10.4, 7.4, 'W', 41, 'S', 'SE', 24, 28, 54, 60, 1013.6, 1016.3, 1, 7, 28.5, 23.7, 'No', 'No'), ('2/24/2010', 21.1, 24.1, 0.0, 9.2, 1.5, 'W', 41, 'ESE', 'E', 9, 13, 55, 52, 1021.7, 1021.4, 8, 7, 22.4, 23.8, 'No', 'No'), ('2/25/2010', 20.5, 24.6, 0.0, 4.4, 9.3, 'W', 41, 'E', 'ESE', 15, 22, 45, 46, 1026.4, 1026.6, 2, 2, 23.3, 24.2, 'No', 'No'), ('2/26/2010', 18.1, 25.1, 0.0, 6.0, 1.6, 'W', 41, 'W', 'ESE', 7, 7, 73, 58, 1027.0, 1024.4, 6, 7, 20.2, 24.6, 'No', 'No'), ('2/27/2010', 18.4, 27.0, 0.2, 3.8, 11.8, 'W', 41, 'W', 'NE', 2, 19, 79, 60, 1021.6, 1017.8, 5, 1, 21.9, 26.5, 'No', 'No'), ('2/28/2010', 21.0, 26.7, 0.0, 8.0, 3.8, 'W', 41, 'WSW', 'ESE', 4, 13, 83, 72, 1017.1, 1014.3, 7, 8, 23.7, 25.8, 'No', 'Yes'), ('3/1/2010', 19.2, 19.7, 4.2, 5.0, 0.0, 'W', 41, 'SSW', 'SE', 19, 17, 68, 84, 1018.9, 1018.4, 8, 8, 19.4, 19.2, 'Yes', 'Yes'), ('3/2/2010', 17.3, 23.0, 9.0, 3.8, 1.3, 'W', 41, 'SE', 'SE', 17, 17, 52, 52, 1019.3, 1018.2, 7, 7, 19.5, 21.8, 'Yes', 'No'), ('3/3/2010', 18.2, 24.4, 0.2, 7.2, 7.5, 'W', 41, 'SE', 'ESE', 11, 19, 53, 53, 1019.4, 1018.2, 3, 5, 22.7, 23.5, 'No', 'No'), ('3/4/2010', 17.2, 25.2, 0.0, 4.4, 7.9, 'W', 41, 'W', 'E', 0, 26, 73, 67, 1016.2, 1013.7, 7, 5, 20.9, 24.7, 'No', 'No'), ('3/5/2010', 20.5, 25.1, 0.0, 5.2, 1.0, 'W', 41, 'NE', 'ENE', 20, 15, 72, 83, 1011.5, 1009.6, 7, 8, 23.9, 23.5, 'No', 'Yes'), ('3/6/2010', 20.9, 26.7, 14.0, 3.4, 6.2, 'W', 41, 'NNW', 'NE', 2, 15, 90, 77, 1011.9, 1010.8, 6, 3, 22.4, 25.1, 'Yes', 'No'), ('3/7/2010', 22.3, 26.4, 0.0, 5.0, 5.0, 'W', 41, 'ENE', 'ENE', 19, 33, 71, 68, 1013.8, 1012.0, 2, 7, 25.0, 25.6, 'No', 'No'), ('3/8/2010', 22.6, 29.2, 0.0, 6.4, 6.4, 'W', 41, 'ENE', 'NE', 11, 17, 72, 65, 1011.6, 1009.6, 6, 7, 24.8, 27.4, 'No', 'No'), ('3/9/2010', 20.8, 30.0, 0.0, 9.2, 11.7, 'W', 41, 'WNW', 'W', 11, 22, 46, 35, 1013.4, 1012.2, 1, 1, 23.9, 29.6, 'No', 'No'), ('3/10/2010', 19.2, 20.8, 0.2, 8.0, 0.3, 'W', 41, 'S', 'SSE', 20, 24, 85, 67, 1020.8, 1022.5, 8, 8, 19.3, 20.4, 'No', 'No'), ('3/11/2010', 18.2, 24.2, 0.0, 5.2, 9.0, 'W', 41, 'S', 'SSE', 24, 24, 63, 49, 1031.1, 1031.5, 2, 4, 20.4, 23.6, 'No', 'No'), ('3/12/2010', 18.7, 24.5, 0.2, 9.0, 7.9, 'W', 41, 'SE', 'SE', 19, 28, 55, 54, 1035.0, 1034.8, 2, 4, 23.3, 22.5, 'No', 'No'), ('3/13/2010', 17.4, 24.7, 0.0, 7.4, 7.1, 'W', 41, 'SSE', 'SE', 22, 19, 68, 52, 1034.3, 1032.9, 2, 6, 20.5, 22.8, 'No', 'Yes'), ('3/14/2010', 16.2, 24.6, 5.6, 5.6, 6.9, 'W', 41, 'W', 'ESE', 13, 17, 87, 50, 1030.4, 1027.8, 2, 5, 18.7, 23.0, 'Yes', 'No'), ('3/15/2010', 18.0, 25.2, 0.0, 5.4, 5.9, 'W', 41, 'W', 'E', 11, 15, 78, 57, 1025.7, 1022.4, 7, 2, 19.7, 24.5, 'No', 'No'), ('3/16/2010', 17.4, 25.5, 0.0, 5.8, 11.0, 'W', 41, 'W', 'E', 15, 19, 82, 54, 1023.5, 1022.7, 3, 1, 20.0, 25.1, 'No', 'No'), ('3/17/2010', 15.6, 26.0, 0.0, 5.4, 11.3, 'W', 41, 'W', 'E', 13, 19, 80, 54, 1025.7, 1024.5, 0, 1, 18.8, 24.4, 'No', 'No'), ('3/18/2010', 17.0, 26.5, 0.0, 6.6, 10.2, 'W', 41, 'W', 'ENE', 9, 17, 77, 51, 1026.5, 1023.7, 6, 4, 19.8, 25.3, 'No', 'No'), ('3/19/2010', 18.2, 27.4, 0.0, 7.0, 11.2, 'W', 41, 'W', 'ENE', 6, 17, 82, 60, 1022.2, 1019.2, 6, 3, 20.1, 26.9, 'No', 'No'), ('3/20/2010', 19.8, 29.0, 0.0, 6.2, 11.1, 'W', 41, 'W', 'E', 15, 15, 64, 68, 1021.0, 1019.5, 3, 1, 22.8, 26.5, 'No', 'No'), ('3/21/2010', 21.7, 30.9, 0.0, 7.0, 9.0, 'W', 41, 'W', 'E', 9, 19, 64, 56, 1017.9, 1014.3, 6, 6, 23.5, 28.0, 'No', 'No'), ('3/22/2010', 20.8, 25.0, 0.0, 8.4, 6.3, 'W', 41, 'ESE', 'ESE', 9, 19, 64, 57, 1020.1, 1018.7, 7, 5, 22.5, 24.1, 'No', 'No'), ('3/23/2010', 18.7, 27.0, 0.0, 4.4, 10.9, 'W', 41, 'WNW', 'ENE', 13, 22, 74, 60, 1020.1, 1017.4, 0, 5, 21.6, 26.1, 'No', 'No'), ('3/24/2010', 18.7, 26.0, 0.0, 7.6, 6.1, 'W', 41, 'W', 'ESE', 17, 20, 79, 58, 1021.6, 1020.8, 7, 5, 20.3, 25.3, 'No', 'No'), ('3/25/2010', 19.5, 25.5, 0.0, 4.0, 8.7, 'W', 41, 'W', 'NE', 7, 20, 75, 61, 1023.4, 1019.6, 6, 1, 21.1, 24.8, 'No', 'No'), ('3/26/2010', 19.5, 29.6, 0.0, 5.6, 8.9, 'W', 41, 'W', 'ENE', 9, 9, 80, 52, 1019.1, 1015.4, 0, 2, 22.6, 29.5, 'No', 'No'), ('3/27/2010', 22.4, 26.9, 0.0, 7.4, 7.2, 'W', 41, 'SSW', 'S', 17, 19, 80, 66, 1019.6, 1018.4, 6, 7, 23.0, 25.5, 'No', 'No'), ('3/28/2010', 20.8, 26.4, 0.0, 5.4, 8.2, 'W', 41, 'W', 'NE', 6, 19, 82, 66, 1019.2, 1014.9, 2, 7, 23.1, 26.2, 'No', 'No'), ('3/29/2010', 22.4, 27.5, 0.0, 2.8, 0.1, 'W', 41, 'W', 'W', 7, 11, 78, 56, 1016.9, 1016.4, 7, 8, 23.2, 26.7, 'No', 'Yes'), ('3/30/2010', 20.5, 21.3, 4.0, 4.8, 0.0, 'W', 41, 'SSW', 'SSW', 4, 9, 92, 88, 1019.8, 1018.4, 8, 8, 20.6, 21.2, 'Yes', 'Yes'), ('3/31/2010', 18.9, 23.1, 14.0, 2.6, 3.1, 'W', 41, 'S', 'S', 24, 30, 68, 67, 1019.5, 1017.5, 7, 6, 21.0, 22.0, 'Yes', 'No'), ('4/1/2010', 16.0, 25.3, 0.2, 3.6, 10.8, 'W', 41, 'W', 'S', 24, 19, 68, 45, 1018.3, 1016.3, 2, 1, 18.4, 24.8, 'No', 'No'), ('4/2/2010', 17.2, 24.6, 0.0, 5.8, 9.4, 'W', 41, 'W', 'S', 13, 24, 74, 46, 1019.9, 1018.5, 5, 2, 19.0, 24.3, 'No', 'No'), ('4/3/2010', 15.9, 24.0, 0.0, 6.6, 7.2, 'W', 41, 'WNW', 'SE', 17, 15, 72, 56, 1021.4, 1020.0, 2, 3, 18.6, 22.1, 'No', 'Yes'), ('4/4/2010', 15.4, 22.4, 6.8, 3.2, 6.6, 'W', 41, 'W', 'SSE', 13, 19, 84, 59, 1022.9, 1020.5, 6, 6, 17.7, 20.7, 'Yes', 'Yes'), ('4/5/2010', 15.2, 21.5, 1.2, 4.4, 2.5, 'W', 41, 'WNW', 'SE', 9, 7, 76, 64, 1021.1, 1019.0, 5, 7, 19.6, 20.5, 'Yes', 'No'), ('4/6/2010', 17.0, 23.3, 0.8, 2.2, 3.6, 'W', 41, 'W', 'E', 0, 17, 74, 62, 1020.5, 1017.6, 6, 7, 21.4, 22.4, 'No', 'Yes'), ('4/7/2010', 18.5, 25.9, 3.8, 2.8, 1.1, 'W', 41, 'NNE', 'NNW', 15, 22, 90, 65, 1016.6, 1012.3, 8, 7, 19.1, 24.5, 'Yes', 'Yes'), ('4/8/2010', 19.0, 28.7, 3.0, 1.4, 9.4, 'W', 41, 'W', 'SSE', 17, 17, 77, 71, 1012.5, 1011.8, 3, 3, 22.2, 24.3, 'Yes', 'Yes'), ('4/9/2010', 16.4, 25.0, 4.4, 5.0, 9.9, 'W', 41, 'WNW', 'SE', 15, 20, 68, 55, 1014.8, 1011.1, 2, 6, 20.8, 22.4, 'Yes', 'No'), ('4/10/2010', 17.2, 27.9, 0.0, 6.2, 7.4, 'W', 41, 'W', 'E', 9, 17, 78, 41, 1010.5, 1007.6, 6, 1, 18.6, 27.6, 'No', 'No'), ('4/11/2010', 18.6, 27.9, 0.0, 3.8, 10.1, 'W', 41, 'NNW', 'WNW', 15, 20, 58, 33, 1007.9, 1006.0, 5, 3, 24.5, 27.7, 'No', 'No'), ('4/12/2010', 14.9, 24.5, 0.0, 8.6, 10.6, 'W', 41, 'W', 'WSW', 30, 20, 33, 22, 1014.3, 1011.7, 1, 2, 16.8, 24.2, 'No', 'No'), ('4/13/2010', 13.1, 22.3, 0.0, 5.6, 10.7, 'W', 41, 'W', 'SSE', 17, 19, 52, 46, 1021.8, 1020.3, 1, 1, 17.6, 21.3, 'No', 'No'), ('4/14/2010', 12.3, 25.0, 0.0, 3.8, 10.7, 'W', 41, 'W', 'ENE', 15, 17, 71, 49, 1022.8, 1019.3, 0, 2, 15.9, 23.0, 'No', 'No'), ('4/15/2010', 14.9, 24.9, 0.0, 6.0, 9.3, 'W', 41, 'W', 'ESE', 15, 19, 77, 62, 1021.9, 1020.5, 6, 3, 17.5, 23.3, 'No', 'No'), ('4/16/2010', 16.9, 22.3, 0.0, 3.6, 1.5, 'W', 41, 'WNW', 'SSE', 9, 15, 77, 64, 1027.0, 1025.1, 7, 6, 18.1, 21.8, 'No', 'No'), ('4/17/2010', 15.8, 25.3, 0.6, 2.4, 10.8, 'W', 41, 'W', 'ESE', 11, 15, 82, 63, 1028.1, 1026.0, 1, 3, 19.1, 24.2, 'No', 'No'), ('4/19/2010', 17.2, 24.9, 0.0, 2.8, 9.6, 'W', 41, 'WNW', 'E', 6, 13, 82, 65, 1026.0, 1023.7, 2, 2, 20.5, 24.2, 'No', 'No'), ('4/20/2010', 17.3, 24.8, 0.0, 4.4, 9.3, 'W', 41, 'W', 'E', 13, 15, 87, 57, 1025.2, 1021.7, 1, 5, 20.0, 24.4, 'No', 'No'), ('4/21/2010', 16.7, 24.2, 0.0, 3.4, 10.3, 'W', 41, 'W', 'ENE', 15, 20, 95, 63, 1023.4, 1020.4, 1, 1, 17.6, 23.9, 'No', 'No'), ('4/22/2010', 16.7, 25.7, 0.0, 5.4, 10.6, 'W', 41, 'WNW', 'E', 11, 19, 81, 63, 1022.9, 1019.4, 1, 1, 19.3, 23.9, 'No', 'No'), ('4/23/2010', 16.6, 30.7, 0.0, 3.2, 10.6, 'W', 41, 'W', 'NE', 13, 11, 68, 50, 1020.6, 1016.0, 1, 1, 20.2, 26.5, 'No', 'No'), ('4/24/2010', 20.2, 28.6, 0.0, 7.2, 3.4, 'W', 41, 'NW', 'NNW', 11, 20, 57, 49, 1014.3, 1009.9, 7, 7, 22.8, 26.4, 'No', 'Yes'), ('4/25/2010', 17.2, 22.8, 8.8, 5.0, 3.8, 'W', 41, 'W', 'S', 20, 20, 77, 70, 1013.2, 1013.5, 7, 5, 17.3, 19.2, 'Yes', 'No'), ('4/26/2010', 12.5, 21.8, 0.4, 3.0, 10.5, 'W', 41, 'W', 'SE', 24, 15, 56, 46, 1024.3, 1022.3, 1, 1, 15.1, 21.5, 'No', 'No'), ('4/27/2010', 11.7, 20.4, 0.0, 4.4, 2.2, 'W', 41, 'W', 'W', 19, 11, 65, 41, 1020.4, 1017.8, 6, 7, 14.2, 20.1, 'No', 'No'), ('4/28/2010', 12.6, 24.9, 0.0, 2.4, 10.6, 'W', 41, 'W', 'W', 15, 9, 64, 32, 1021.0, 1016.7, 0, 1, 16.0, 24.5, 'No', 'No'), ('4/29/2010', 13.4, 24.6, 0.0, 5.0, 10.7, 'W', 41, 'W', 'WNW', 24, 17, 44, 35, 1019.9, 1017.0, 1, 1, 18.2, 24.5, 'No', 'No'), ('4/30/2010', 14.0, 19.4, 0.0, 5.0, 0.3, 'W', 41, 'W', 'S', 20, 13, 79, 64, 1025.2, 1024.4, 8, 7, 14.4, 19.2, 'No', 'Yes'), ('5/1/2010', 14.3, 21.7, 1.8, 2.4, 4.6, 'W', 41, 'W', 'ENE', 13, 13, 89, 74, 1027.6, 1024.4, 7, 6, 15.1, 20.6, 'Yes', 'No'), ('5/2/2010', 13.9, 26.5, 0.0, 1.2, 8.2, 'W', 41, 'W', 'SW', 19, 2, 90, 30, 1024.8, 1022.1, 2, 1, 15.3, 26.3, 'No', 'No'), ('5/3/2010', 14.8, 23.1, 0.2, 4.0, 6.5, 'W', 41, 'W', 'ESE', 15, 6, 75, 60, 1027.6, 1024.3, 4, 6, 18.0, 22.7, 'No', 'No'), ('5/4/2010', 16.2, 24.8, 0.0, 2.8, 4.2, 'W', 41, 'WNW', 'NE', 2, 17, 80, 54, 1021.3, 1015.8, 7, 5, 19.2, 24.2, 'No', 'No'), ('5/5/2010', 15.4, 21.1, 0.0, 3.8, 5.9, 'W', 41, 'NNE', 'W', 7, 28, 59, 41, 1012.2, 1011.3, 7, 3, 18.7, 18.1, 'No', 'Yes'), ('5/6/2010', 10.4, 22.3, 2.0, 4.4, 10.2, 'W', 41, 'W', 'WSW', 24, 7, 48, 34, 1020.0, 1018.3, 1, 1, 13.9, 21.5, 'Yes', 'No'), ('5/7/2010', 11.3, 23.1, 0.0, 3.8, 10.1, 'W', 41, 'W', 'WSW', 20, 6, 62, 33, 1022.4, 1018.3, 1, 1, 13.5, 22.9, 'No', 'No'), ('5/8/2010', 11.1, 24.4, 0.0, 4.0, 10.1, 'W', 41, 'W', 'E', 20, 11, 65, 46, 1021.9, 1019.3, 1, 1, 14.1, 22.6, 'No', 'No'), ('5/9/2010', 12.3, 24.6, 0.0, 2.0, 10.2, 'W', 41, 'W', 'E', 15, 17, 68, 50, 1022.0, 1018.3, 1, 1, 15.3, 22.4, 'No', 'No'), ('5/10/2010', 12.7, 22.6, 0.0, 4.4, 10.2, 'W', 41, 'W', 'NE', 13, 19, 78, 61, 1020.3, 1015.8, 1, 1, 15.7, 22.0, 'No', 'No'), ('5/11/2010', 12.8, 27.0, 0.0, 4.2, 9.7, 'W', 41, 'W', 'W', 11, 30, 64, 19, 1012.6, 1008.7, 1, 1, 16.3, 25.7, 'No', 'No'), ('5/12/2010', 10.5, 18.9, 0.0, 8.0, 10.2, 'W', 41, 'WSW', 'S', 28, 26, 40, 29, 1017.9, 1016.9, 1, 1, 12.7, 18.5, 'No', 'No'), ('5/13/2010', 9.0, 21.9, 0.0, 4.4, 9.4, 'W', 41, 'W', 'S', 24, 17, 53, 36, 1018.8, 1015.8, 1, 2, 12.0, 20.7, 'No', 'No'), ('5/14/2010', 10.6, 21.1, 0.0, 4.4, 10.1, 'W', 41, 'W', 'SW', 19, 22, 60, 35, 1018.4, 1014.9, 1, 2, 13.0, 20.3, 'No', 'No'), ('5/15/2010', 10.5, 21.7, 0.0, 4.0, 9.0, 'W', 41, 'W', 'S', 20, 24, 62, 47, 1017.6, 1016.1, 1, 3, 13.2, 20.5, 'No', 'No'), ('5/16/2010', 11.0, 21.6, 0.0, 4.4, 7.7, 'W', 41, 'W', 'SSE', 17, 13, 71, 60, 1020.9, 1018.4, 2, 6, 12.7, 19.7, 'No', 'No'), ('5/17/2010', 12.7, 17.9, 1.0, 2.4, 0.2, 'W', 41, 'W', 'WNW', 19, 4, 85, 68, 1019.7, 1016.7, 8, 8, 13.1, 16.5, 'No', 'Yes'), ('5/18/2010', 12.4, 15.4, 13.8, 1.0, 0.0, 'W', 41, 'W', 'SW', 22, 17, 94, 92, 1018.2, 1017.4, 8, 8, 13.0, 14.9, 'Yes', 'Yes'), ('5/19/2010', 11.7, 20.0, 47.8, 4.8, 6.1, 'W', 41, 'W', 'SSE', 20, 9, 91, 62, 1022.1, 1020.3, 7, 3, 13.0, 20.0, 'Yes', 'No'), ('5/20/2010', 11.2, 19.7, 1.0, 2.8, 6.1, 'W', 41, 'W', 'ESE', 19, 11, 82, 55, 1023.1, 1019.9, 6, 6, 12.7, 19.3, 'No', 'No'), ('5/21/2010', 11.7, 19.5, 0.0, 1.2, 6.4, 'W', 41, 'WNW', 'SSE', 13, 20, 83, 58, 1020.6, 1017.9, 3, 6, 13.9, 18.4, 'No', 'Yes'), ('5/22/2010', 10.8, 18.6, 17.2, 2.8, 4.8, 'W', 41, 'W', 'SSW', 22, 24, 92, 58, 1021.5, 1019.7, 7, 3, 11.3, 18.4, 'Yes', 'Yes'), ('5/23/2010', 9.5, 14.7, 14.2, 5.0, 0.4, 'W', 41, 'W', 'W', 19, 11, 91, 93, 1023.6, 1020.8, 7, 6, 10.4, 14.3, 'Yes', 'Yes'), ('5/24/2010', 10.4, 18.0, 5.6, 0.2, 1.1, 'W', 41, 'W', 'E', 15, 4, 86, 68, 1019.7, 1015.7, 7, 7, 12.1, 17.8, 'Yes', 'No'), ('5/25/2010', 12.1, 16.9, 0.8, 4.8, 0.1, 'W', 41, 'WNW', 'WNW', 11, 7, 89, 84, 1011.7, 1006.3, 7, 7, 14.1, 16.8, 'No', 'Yes'), ('5/26/2010', 13.4, 17.3, 9.0, 2.2, 0.0, 'W', 41, 'W', 'ESE', 17, 50, 96, 94, 1004.8, 1004.9, 8, 8, 13.5, 15.6, 'Yes', 'Yes'), ('5/27/2010', 13.5, 18.7, 33.6, 5.8, 3.3, 'W', 41, 'SE', 'S', 15, 11, 82, 62, 1018.0, 1017.6, 6, 7, 15.9, 18.3, 'Yes', 'Yes'), ('5/28/2010', 11.7, 19.9, 1.6, 1.4, 4.6, 'W', 41, 'W', 'E', 15, 7, 92, 53, 1021.0, 1017.1, 7, 5, 12.9, 19.8, 'Yes', 'Yes'), ('5/29/2010', 12.9, 17.1, 3.0, 2.8, 0.0, 'W', 41, 'N', 'NE', 11, 4, 88, 87, 1009.5, 1004.7, 7, 8, 15.8, 16.2, 'Yes', 'Yes'), ('5/30/2010', 11.8, 19.1, 3.0, 1.4, 2.2, 'W', 41, 'WNW', 'W', 15, 2, 78, 56, 1003.2, 1002.4, 4, 6, 13.0, 18.7, 'Yes', 'Yes'), ('5/31/2010', 12.6, 20.0, 12.8, 1.6, 3.9, 'W', 41, 'SSW', 'S', 22, 28, 87, 68, 1008.3, 1010.2, 7, 7, 16.5, 19.1, 'Yes', 'Yes'), ('6/1/2010', 11.7, 19.7, 12.4, 2.6, 3.6, 'W', 41, 'W', 'S', 15, 19, 80, 60, 1019.2, 1017.7, 7, 7, 14.5, 18.5, 'Yes', 'No'), ('6/2/2010', 11.2, 20.1, 0.0, 3.0, 7.0, 'W', 41, 'W', 'SSW', 19, 13, 81, 63, 1020.9, 1019.6, 6, 5, 12.7, 19.0, 'No', 'Yes'), ('6/3/2010', 12.7, 18.6, 6.0, 2.4, 0.8, 'W', 41, 'SSW', 'ESE', 19, 24, 91, 90, 1023.0, 1020.0, 7, 7, 15.2, 17.1, 'Yes', 'Yes'), ('6/4/2010', 15.2, 17.7, 26.4, 3.4, 0.0, 'W', 41, 'E', 'SSE', 26, 30, 85, 94, 1018.7, 1015.5, 7, 8, 17.3, 16.4, 'Yes', 'Yes'), ('6/5/2010', 12.5, 20.5, 61.4, 1.0, 4.4, 'W', 41, 'W', 'SSW', 22, 15, 80, 67, 1014.2, 1012.0, 5, 7, 13.5, 17.4, 'Yes', 'No'), ('6/6/2010', 9.5, 18.5, 0.4, 2.2, 6.5, 'W', 41, 'W', 'SW', 28, 22, 64, 70, 1014.7, 1015.8, 1, 7, 11.3, 15.2, 'No', 'Yes'), ('6/7/2010', 9.1, 15.5, 4.2, 3.4, 3.9, 'W', 41, 'W', 'SSW', 24, 20, 60, 77, 1024.3, 1023.0, 2, 7, 10.6, 14.3, 'Yes', 'No'), ('6/8/2010', 9.1, 18.5, 0.4, 4.8, 9.0, 'W', 41, 'W', 'NE', 22, 6, 78, 62, 1023.5, 1018.7, 5, 4, 10.6, 16.3, 'No', 'No'), ('6/9/2010', 9.5, 16.7, 0.0, 2.2, 7.2, 'W', 41, 'W', 'WNW', 6, 30, 71, 34, 1012.0, 1008.3, 5, 3, 11.1, 15.7, 'No', 'No'), ('6/10/2010', 10.3, 17.2, 0.0, 3.8, 7.2, 'W', 41, 'W', 'SSW', 26, 13, 48, 30, 1017.5, 1017.7, 5, 4, 11.3, 16.8, 'No', 'No'), ('6/11/2010', 6.2, 17.4, 0.0, 3.2, 9.8, 'W', 41, 'W', 'W', 19, 22, 64, 37, 1019.9, 1016.0, 0, 1, 9.0, 16.9, 'No', 'No'), ('6/12/2010', 9.0, 16.7, 0.0, 3.0, 9.6, 'W', 41, 'W', 'S', 20, 22, 63, 42, 1022.0, 1021.7, 1, 2, 11.5, 15.8, 'No', 'No'), ('6/13/2010', 6.6, 17.9, 0.0, 3.8, 9.5, 'W', 41, 'W', 'S', 22, 13, 66, 50, 1029.8, 1028.9, 1, 1, 8.4, 17.1, 'No', 'No'), ('6/14/2010', 6.9, 18.3, 0.0, 1.8, 9.5, 'W', 41, 'W', 'ENE', 22, 2, 75, 50, 1034.7, 1032.0, 5, 4, 8.9, 17.8, 'No', 'No'), ('6/15/2010', 8.1, 19.3, 0.0, 2.0, 9.3, 'W', 41, 'W', 'ENE', 17, 7, 86, 56, 1032.7, 1028.9, 5, 4, 10.0, 17.6, 'No', 'No'), ('6/16/2010', 9.1, 18.9, 0.0, 1.6, 9.6, 'W', 41, 'WNW', 'ENE', 11, 15, 89, 59, 1028.9, 1024.1, 2, 2, 10.6, 18.3, 'No', 'No'), ('6/17/2010', 10.6, 17.3, 0.0, 4.0, 1.7, 'W', 41, 'NNW', 'N', 11, 22, 67, 69, 1016.0, 1010.5, 8, 5, 14.2, 16.6, 'No', 'No'), ('6/20/2010', 9.5, 20.2, 0.0, 3.0, 9.8, 'W', 41, 'W', 'ESE', 19, 7, 71, 40, 1025.0, 1023.8, 5, 4, 11.3, 20.0, 'No', 'Yes'), ('6/21/2010', 10.1, 16.0, 8.2, 3.4, 4.2, 'W', 41, 'W', 'S', 15, 17, 95, 80, 1032.8, 1032.5, 7, 4, 11.5, 15.7, 'Yes', 'Yes'), ('6/23/2010', 12.6, 15.6, 4.0, 2.2, 0.2, 'W', 41, 'SSE', 'S', 17, 6, 83, 90, 1036.7, 1034.1, 7, 7, 14.4, 14.6, 'Yes', 'Yes'), ('6/24/2010', 11.8, 17.0, 18.8, 0.6, 5.2, 'W', 41, 'W', 'E', 15, 19, 96, 64, 1031.6, 1027.1, 7, 2, 12.2, 17.0, 'Yes', 'No'), ('6/25/2010', 12.2, 18.4, 0.0, 3.2, 2.8, 'W', 41, 'W', 'N', 13, 17, 83, 65, 1025.1, 1020.7, 6, 6, 13.7, 18.4, 'No', 'No'), ('6/26/2010', 13.5, 20.0, 1.0, 1.4, 4.0, 'W', 41, 'WNW', 'WSW', 20, 17, 78, 50, 1017.3, 1016.3, 7, 2, 15.2, 19.7, 'No', 'No'), ('6/27/2010', 6.7, 14.9, 0.0, 2.8, 6.8, 'W', 41, 'W', 'SSW', 20, 22, 72, 53, 1021.0, 1018.9, 1, 6, 8.1, 13.9, 'No', 'No'), ('6/28/2010', 5.5, 15.8, 0.0, 2.0, 9.7, 'W', 41, 'W', 'W', 22, 9, 68, 36, 1021.0, 1017.7, 1, 1, 7.0, 15.3, 'No', 'No'), ('6/29/2010', 4.7, 14.4, 0.0, 2.6, 9.9, 'W', 41, 'WNW', 'WSW', 13, 6, 63, 36, 1020.1, 1017.0, 0, 0, 7.0, 14.4, 'No', 'No'), ('6/30/2010', 4.3, 16.1, 0.0, 3.0, 9.3, 'W', 41, 'W', 'WNW', 11, 4, 70, 41, 1020.8, 1018.5, 0, 1, 6.4, 15.7, 'No', 'No'), ('7/1/2010', 6.4, 17.1, 0.0, 2.0, 8.6, 'W', 41, 'W', 'W', 20, 7, 70, 40, 1024.9, 1022.8, 4, 4, 8.5, 16.9, 'No', 'No'), ('7/2/2010', 7.6, 12.1, 0.0, 2.0, 0.0, 'W', 41, 'W', 'W', 15, 11, 74, 65, 1026.8, 1023.5, 7, 8, 9.2, 11.9, 'No', 'No'), ('7/3/2010', 7.7, 16.3, 0.6, 1.8, 9.8, 'W', 41, 'W', 'SSW', 24, 24, 68, 38, 1025.6, 1026.1, 1, 2, 9.1, 15.6, 'No', 'No'), ('7/4/2010', 7.8, 17.8, 0.0, 3.2, 8.8, 'W', 41, 'W', 'S', 22, 17, 68, 56, 1029.7, 1026.9, 2, 4, 8.9, 16.9, 'No', 'No'), ('7/5/2010', 8.8, 13.5, 0.0, 3.4, 0.1, 'W', 41, 'W', 'W', 20, 11, 76, 83, 1027.2, 1024.1, 7, 8, 9.7, 13.1, 'No', 'Yes'), ('7/6/2010', 9.7, 17.2, 4.2, 0.4, 3.5, 'W', 41, 'W', 'SSW', 7, 17, 95, 67, 1016.7, 1015.1, 6, 7, 10.8, 15.1, 'Yes', 'Yes'), ('7/7/2010', 9.6, 16.0, 2.6, 1.4, 2.9, 'W', 41, 'W', 'S', 22, 20, 83, 70, 1023.9, 1022.5, 7, 6, 10.3, 15.3, 'Yes', 'Yes'), ('7/9/2010', 9.7, 15.6, 32.0, 0.0, 3.8, 'W', 41, 'WNW', 'S', 19, 9, 96, 83, 1029.6, 1027.9, 6, 7, 10.7, 13.9, 'Yes', 'Yes'), ('7/10/2010', 8.6, 17.6, 4.6, 2.0, 4.8, 'W', 41, 'W', 'ENE', 17, 11, 95, 65, 1028.9, 1025.0, 6, 7, 9.9, 16.6, 'Yes', 'No'), ('7/11/2010', 9.9, 19.0, 0.2, 1.2, 1.0, 'W', 41, 'N', 'NW', 13, 7, 61, 76, 1022.2, 1019.8, 7, 7, 16.7, 17.3, 'No', 'No'), ('7/12/2010', 10.1, 16.9, 0.2, 2.0, 2.1, 'W', 41, 'W', 'WNW', 19, 6, 87, 61, 1023.6, 1021.1, 6, 7, 11.4, 16.0, 'No', 'No'), ('7/13/2010', 11.4, 18.6, 0.0, 0.6, 0.0, 'W', 41, 'W', 'NNE', 7, 7, 83, 78, 1020.3, 1014.6, 7, 8, 14.1, 17.7, 'No', 'No'), ('7/14/2010', 13.9, 18.1, 1.0, 1.8, 8.0, 'W', 41, 'WNW', 'WNW', 20, 22, 56, 33, 1008.7, 1008.6, 3, 1, 14.4, 17.4, 'No', 'No'), ('7/15/2010', 10.4, 18.2, 0.0, 5.2, 9.8, 'W', 41, 'W', 'WSW', 24, 17, 50, 34, 1015.4, 1017.1, 1, 3, 11.9, 17.4, 'No', 'No'), ('7/16/2010', 7.2, 18.2, 0.0, 4.4, 9.4, 'W', 41, 'W', 'S', 24, 19, 63, 46, 1025.9, 1024.0, 2, 2, 9.0, 16.2, 'No', 'No'), ('7/17/2010', 7.1, 18.5, 0.0, 2.6, 9.9, 'W', 41, 'W', 'E', 26, 9, 71, 39, 1028.1, 1024.7, 1, 1, 8.6, 18.4, 'No', 'No'), ('7/18/2010', 7.3, 19.4, 0.0, 2.0, 10.0, 'W', 41, 'W', 'ESE', 20, 7, 81, 40, 1022.6, 1017.8, 0, 1, 8.9, 18.7, 'No', 'No'), ('7/19/2010', 8.7, 16.7, 0.0, 3.6, 0.8, 'W', 41, 'W', 'SSW', 15, 7, 67, 53, 1017.8, 1016.0, 6, 7, 11.1, 15.0, 'No', 'No'), ('7/20/2010', 8.0, 16.5, 0.0, 1.0, 8.5, 'W', 41, 'W', 'SSW', 19, 19, 71, 53, 1022.4, 1021.4, 1, 3, 10.2, 14.9, 'No', 'Yes'), ('7/21/2010', 8.0, 15.7, 6.6, 3.2, 4.1, 'W', 41, 'W', 'SSW', 19, 13, 73, 54, 1026.7, 1024.6, 7, 4, 9.2, 15.5, 'Yes', 'No'), ('7/22/2010', 6.0, 14.7, 0.4, 1.0, 5.0, 'W', 41, 'W', 'SSW', 28, 20, 64, 69, 1028.5, 1028.1, 1, 5, 8.8, 13.6, 'No', 'No'), ('7/23/2010', 8.0, 18.2, 0.2, 2.0, 5.8, 'W', 41, 'W', 'S', 20, 20, 75, 62, 1032.6, 1030.3, 2, 7, 9.8, 16.4, 'No', 'Yes'), ('7/24/2010', 9.6, 18.3, 4.6, 2.6, 3.9, 'W', 41, 'W', 'SE', 22, 13, 81, 54, 1030.7, 1027.4, 7, 5, 10.3, 17.6, 'Yes', 'No'), ('7/25/2010', 10.2, 16.9, 0.0, 1.0, 6.2, 'W', 41, 'W', 'SE', 11, 15, 83, 64, 1029.9, 1027.7, 3, 5, 12.5, 15.5, 'No', 'Yes'), ('7/26/2010', 9.2, 17.0, 16.0, 3.8, 3.2, 'W', 41, 'W', 'SE', 15, 7, 90, 69, 1034.0, 1032.6, 6, 7, 11.9, 15.5, 'Yes', 'Yes'), ('7/27/2010', 9.3, 16.9, 2.4, 1.6, 3.2, 'W', 41, 'W', 'E', 13, 9, 86, 49, 1035.7, 1032.5, 6, 7, 11.2, 16.6, 'Yes', 'Yes'), ('7/28/2010', 11.2, 15.2, 2.6, 1.6, 0.8, 'W', 41, 'N', 'NNE', 4, 11, 96, 90, 1029.8, 1024.8, 8, 8, 12.3, 14.4, 'Yes', 'Yes'), ('7/29/2010', 11.4, 16.2, 24.2, 1.4, 0.6, 'W', 41, 'NW', 'N', 6, 9, 93, 77, 1019.1, 1016.0, 6, 7, 12.8, 15.8, 'Yes', 'Yes'), ('7/30/2010', 12.0, 21.1, 3.4, 3.8, 5.8, 'W', 41, 'W', 'NNE', 22, 9, 97, 62, 1016.9, 1013.6, 4, 7, 12.8, 21.0, 'Yes', 'Yes'), ('7/31/2010', 12.8, 20.7, 6.6, 0.2, 5.8, 'W', 41, 'W', 'W', 7, 28, 96, 37, 1012.1, 1012.0, 7, 2, 14.5, 20.5, 'Yes', 'No'), ('8/1/2010', 9.6, 20.9, 0.0, 3.8, 10.3, 'W', 41, 'N', 'NW', 11, 26, 62, 35, 1019.9, 1013.0, 1, 1, 13.2, 20.6, 'No', 'No'), ('8/2/2010', 9.1, 15.7, 0.4, 4.0, 7.3, 'W', 41, 'W', 'WSW', 24, 28, 49, 36, 1015.8, 1011.6, 5, 5, 11.2, 15.1, 'No', 'Yes'), ('8/3/2010', 10.3, 17.3, 16.4, 4.0, 6.6, 'W', 41, 'W', 'E', 15, 19, 75, 62, 1016.2, 1016.9, 7, 4, 13.9, 15.5, 'Yes', 'No'), ('8/4/2010', 8.3, 18.9, 0.0, 4.0, 10.2, 'W', 41, 'W', 'W', 15, 9, 75, 44, 1019.0, 1014.9, 1, 1, 11.2, 18.7, 'No', 'No'), ('8/5/2010', 7.1, 16.9, 0.0, 3.8, 8.3, 'W', 41, 'NNW', 'W', 17, 20, 57, 33, 1018.1, 1015.1, 3, 5, 11.1, 15.8, 'No', 'No'), ('8/6/2010', 7.6, 17.0, 0.0, 2.4, 10.3, 'W', 41, 'W', 'S', 19, 19, 56, 40, 1020.5, 1019.2, 1, 2, 10.5, 15.7, 'No', 'No'), ('8/7/2010', 6.8, 16.1, 0.0, 4.2, 10.2, 'W', 41, 'W', 'S', 26, 20, 58, 50, 1024.7, 1022.2, 1, 5, 9.1, 15.5, 'No', 'No'), ('8/8/2010', 6.4, 17.2, 0.0, 3.0, 10.3, 'W', 41, 'W', 'E', 20, 15, 73, 50, 1022.2, 1019.1, 3, 1, 8.8, 15.2, 'No', 'No'), ('8/9/2010', 7.2, 17.1, 0.0, 2.6, 8.9, 'W', 41, 'W', 'E', 15, 20, 83, 58, 1023.5, 1020.9, 2, 1, 9.3, 17.0, 'No', 'Yes'), ('8/10/2010', 9.3, 16.4, 2.8, 2.4, 0.0, 'W', 41, 'WSW', 'NNE', 2, 13, 93, 90, 1019.2, 1013.8, 8, 8, 12.2, 16.2, 'Yes', 'Yes'), ('8/11/2010', 12.2, 18.0, 4.6, 0.6, 6.0, 'W', 41, 'NW', 'WNW', 19, 20, 59, 35, 1008.6, 1003.7, 7, 3, 12.8, 17.4, 'Yes', 'No'), ('8/12/2010', 10.7, 16.7, 0.2, 6.6, 5.9, 'W', 41, 'W', 'W', 35, 22, 55, 47, 1001.5, 1002.3, 2, 7, 12.2, 15.0, 'No', 'No'), ('8/13/2010', 9.9, 18.3, 0.0, 2.6, 10.6, 'W', 41, 'W', 'S', 26, 31, 54, 44, 1011.9, 1012.0, 1, 1, 12.7, 17.0, 'No', 'No'), ('8/14/2010', 8.2, 21.8, 0.0, 4.2, 10.7, 'W', 41, 'N', 'N', 11, 6, 69, 36, 1014.5, 1009.7, 0, 0, 13.0, 21.4, 'No', 'No'), ('8/15/2010', 12.8, 20.1, 0.0, 6.4, 7.3, 'W', 41, 'NNW', 'WNW', 22, 17, 53, 37, 1006.2, 1004.0, 6, 2, 15.1, 20.0, 'No', 'No'), ('8/16/2010', 12.6, 18.8, 0.4, 4.0, 10.7, 'W', 41, 'W', 'W', 24, 24, 44, 31, 1011.5, 1010.3, 1, 1, 14.3, 18.3, 'No', 'No'), ('8/17/2010', 7.6, 17.6, 0.0, 4.4, 10.4, 'W', 41, 'W', 'E', 26, 15, 44, 26, 1022.0, 1019.9, 1, 3, 10.8, 15.9, 'No', 'No'), ('8/18/2010', 6.5, 19.9, 0.0, 4.2, 6.6, 'W', 41, 'W', 'NE', 13, 19, 69, 53, 1020.5, 1012.0, 3, 5, 9.3, 17.7, 'No', 'Yes'), ('8/19/2010', 9.3, 24.6, 2.2, 5.0, 10.8, 'W', 41, 'NNW', 'WNW', 22, 31, 57, 23, 1007.7, 1004.6, 1, 1, 19.5, 24.4, 'Yes', 'No'), ('8/20/2010', 11.3, 19.3, 0.0, 6.2, 10.8, 'W', 41, 'WNW', 'WNW', 11, 19, 45, 26, 1012.4, 1010.9, 1, 1, 14.3, 19.2, 'No', 'No'), ('8/21/2010', 8.8, 16.7, 0.0, 5.6, 10.9, 'W', 41, 'WNW', 'W', 20, 30, 44, 33, 1017.0, 1015.2, 1, 2, 12.8, 16.7, 'No', 'No'), ('8/22/2010', 8.4, 17.3, 0.0, 4.6, 9.4, 'W', 41, 'W', 'E', 22, 13, 58, 48, 1023.7, 1020.4, 1, 5, 11.4, 15.7, 'No', 'No'), ('8/23/2010', 11.2, 15.0, 0.0, 3.6, 1.0, 'W', 41, 'NW', 'NE', 6, 7, 77, 65, 1017.1, 1010.8, 7, 7, 12.4, 13.9, 'No', 'No'), ('8/24/2010', 10.9, 19.8, 0.0, 2.2, 10.3, 'W', 41, 'W', 'WNW', 17, 22, 53, 28, 1012.3, 1007.9, 1, 2, 13.9, 19.6, 'No', 'No'), ('8/25/2010', 11.5, 18.1, 0.0, 6.0, 10.4, 'W', 41, 'SW', 'WNW', 17, 26, 36, 24, 1008.1, 1005.2, 1, 1, 14.1, 17.2, 'No', 'No'), ('8/26/2010', 10.3, 18.0, 0.0, 6.4, 8.9, 'W', 41, 'NW', 'W', 19, 33, 48, 33, 1003.5, 1000.7, 3, 3, 13.8, 16.4, 'No', 'No'), ('8/27/2010', 10.3, 19.2, 0.0, 5.8, 8.4, 'W', 41, 'WNW', 'WNW', 20, 28, 47, 35, 1008.1, 1008.0, 5, 3, 14.1, 18.8, 'No', 'No'), ('8/28/2010', 9.2, 17.5, 0.0, 4.0, 10.9, 'W', 41, 'W', 'S', 20, 19, 52, 40, 1021.8, 1022.3, 1, 1, 12.3, 16.5, 'No', 'No'), ('8/30/2010', 10.5, 17.6, 0.0, 2.2, 8.2, 'W', 41, 'W', 'E', 4, 15, 70, 56, 1027.1, 1024.3, 3, 2, 14.9, 16.8, 'No', 'No'), ('8/31/2010', 11.5, 20.0, 0.0, 3.2, 9.7, 'W', 41, 'W', 'NE', 9, 22, 71, 60, 1025.3, 1019.8, 1, 5, 15.8, 18.4, 'No', 'No'), ('9/1/2010', 14.9, 25.9, 0.0, 6.4, 3.3, 'W', 41, 'W', 'E', 15, 19, 53, 33, 1017.8, 1012.5, 6, 7, 18.2, 24.1, 'No', 'No'), ('9/2/2010', 16.6, 18.1, 0.8, 3.8, 0.0, 'W', 41, 'W', 'E', 15, 19, 77, 74, 1016.3, 1014.4, 8, 7, 17.8, 17.8, 'No', 'Yes'), ('9/3/2010', 13.7, 17.6, 3.2, 1.8, 0.0, 'W', 41, 'W', 'E', 15, 19, 80, 64, 1025.8, 1023.6, 8, 7, 15.2, 16.5, 'Yes', 'Yes'), ('9/4/2010', 15.2, 20.3, 7.4, 2.8, 0.0, 'W', 41, 'W', 'E', 15, 19, 90, 84, 1014.2, 1006.7, 8, 8, 17.6, 19.0, 'Yes', 'No'), ('9/5/2010', 16.4, 21.3, 0.6, 5.6, 11.3, 'W', 41, 'W', 'E', 15, 19, 44, 35, 1007.9, 1009.7, 1, 2, 18.6, 20.4, 'No', 'No'), ('9/6/2010', 11.5, 20.4, 0.0, 8.0, 8.4, 'W', 41, 'W', 'E', 15, 19, 45, 33, 1018.6, 1017.1, 1, 6, 15.1, 18.9, 'No', 'No'), ('9/7/2010', 10.4, 16.8, 0.0, 3.2, 10.3, 'W', 41, 'W', 'S', 15, 24, 54, 51, 1023.4, 1023.3, 2, 3, 14.4, 16.1, 'No', 'No'), ('9/8/2010', 8.2, 18.3, 0.0, 4.0, 10.7, 'W', 41, 'W', 'ESE', 15, 15, 58, 54, 1027.3, 1023.6, 1, 1, 13.1, 17.2, 'No', 'No'), ('9/9/2010', 9.7, 18.4, 0.0, 4.0, 2.4, 'W', 41, 'W', 'NW', 2, 6, 77, 56, 1017.5, 1010.6, 6, 8, 13.0, 18.0, 'No', 'Yes'), ('9/10/2010', 11.0, 24.5, 2.4, 2.0, 5.4, 'W', 41, 'W', 'W', 9, 39, 82, 34, 1004.1, 1001.3, 6, 7, 16.2, 21.2, 'Yes', 'No'), ('9/11/2010', 11.1, 19.9, 0.8, 4.4, 10.9, 'W', 41, 'W', 'E', 20, 15, 46, 44, 1017.4, 1017.2, 1, 1, 15.3, 17.5, 'No', 'No'), ('9/12/2010', 9.2, 18.9, 0.0, 3.8, 10.0, 'W', 41, 'W', 'NE', 15, 17, 64, 61, 1022.5, 1017.8, 3, 5, 13.6, 17.6, 'No', 'No'), ('9/13/2010', 13.3, 23.9, 0.0, 4.2, 6.9, 'W', 41, 'W', 'W', 13, 24, 64, 24, 1015.8, 1012.1, 5, 3, 16.2, 23.3, 'No', 'No'), ('9/14/2010', 13.9, 18.1, 0.0, 5.4, 1.7, 'W', 41, 'ESE', 'ESE', 28, 28, 70, 87, 1016.4, 1011.4, 6, 8, 17.6, 15.7, 'No', 'Yes'), ('9/16/2010', 10.4, 21.2, 0.0, 5.0, 9.6, 'W', 41, 'W', 'WNW', 24, 19, 42, 30, 1014.8, 1010.6, 5, 2, 15.3, 20.8, 'No', 'No'), ('9/17/2010', 9.5, 19.3, 0.0, 6.4, 11.2, 'W', 41, 'W', 'ENE', 20, 19, 41, 33, 1021.1, 1017.8, 2, 5, 13.5, 17.2, 'No', 'No'), ('9/18/2010', 9.6, 23.3, 0.0, 5.0, 11.0, 'W', 41, 'W', 'ESE', 17, 20, 48, 45, 1017.4, 1013.8, 1, 1, 15.0, 19.5, 'No', 'No'), ('9/19/2010', 11.7, 18.1, 0.0, 4.0, 4.1, 'W', 41, 'W', 'ENE', 11, 13, 56, 66, 1022.0, 1019.7, 6, 7, 15.0, 17.3, 'No', 'No'), ('9/20/2010', 11.1, 20.1, 0.0, 3.6, 9.1, 'W', 41, 'W', 'E', 13, 20, 66, 65, 1024.0, 1022.7, 4, 5, 16.8, 18.5, 'No', 'No'), ('9/21/2010', 11.6, 23.7, 0.0, 3.0, 8.2, 'W', 41, 'W', 'SSE', 15, 24, 82, 66, 1023.0, 1022.3, 0, 5, 15.3, 20.4, 'No', 'Yes'), ('9/22/2010', 13.0, 20.1, 1.8, 4.6, 9.5, 'W', 41, 'W', 'E', 11, 22, 75, 61, 1026.5, 1020.8, 3, 1, 16.6, 18.1, 'Yes', 'No'), ('9/23/2010', 15.2, 19.0, 0.2, 5.0, 1.1, 'W', 41, 'SE', 'E', 13, 15, 69, 63, 1024.7, 1022.3, 7, 7, 16.6, 17.3, 'No', 'No'), ('9/24/2010', 13.7, 21.1, 0.0, 3.2, 10.7, 'W', 41, 'NNW', 'NE', 13, 13, 67, 69, 1022.2, 1017.6, 0, 0, 19.0, 20.2, 'No', 'No'), ('9/25/2010', 13.4, 26.9, 0.0, 5.4, 8.0, 'W', 41, 'W', 'ESE', 9, 15, 58, 33, 1016.0, 1013.5, 4, 7, 18.5, 24.8, 'No', 'No'), ('9/26/2010', 13.1, 22.0, 0.0, 5.4, 10.8, 'W', 41, 'W', 'E', 6, 24, 57, 74, 1020.1, 1017.3, 1, 3, 19.5, 19.7, 'No', 'No'), ('10/2/2010', 12.7, 19.6, 0.0, 2.6, 0.0, 'W', 41, 'E', 'ENE', 13, 20, 70, 82, 1029.8, 1027.7, 5, 4, 18.3, 16.5, 'No', 'Yes'), ('10/3/2010', 15.0, 19.7, 14.2, 1.0, 1.2, 'W', 41, 'ENE', 'E', 19, 24, 93, 77, 1030.0, 1027.4, 5, 4, 15.3, 18.9, 'Yes', 'Yes'), ('10/4/2010', 15.3, 20.6, 12.0, 4.0, 2.3, 'W', 41, 'E', 'E', 7, 24, 83, 72, 1026.2, 1022.8, 5, 4, 17.9, 19.9, 'Yes', 'Yes'), ('10/14/2010', 17.8, 28.9, 2.0, 4.0, 10.8, 'NNW', 41, 'NNW', 'E', 22, 17, 63, 48, 1011.2, 1008.1, 5, 4, 22.3, 26.6, 'Yes', 'No'), ('10/15/2010', 19.5, 24.7, 0.0, 7.8, 0.2, 'NNW', 76, 'NE', 'NE', 13, 31, 66, 73, 999.6, 989.8, 5, 4, 21.5, 21.8, 'No', 'No'), ('10/16/2010', 11.7, 16.1, 0.8, 3.4, 9.3, 'WNW', 85, 'W', 'W', 46, 48, 34, 28, 999.3, 1003.6, 5, 4, 12.9, 15.2, 'No', 'No'), ('10/17/2010', 9.9, 24.0, 0.0, 6.6, 12.1, 'W', 41, 'W', 'SSE', 24, 4, 44, 30, 1012.9, 1011.3, 5, 4, 14.7, 23.3, 'No', 'No'), ('10/20/2010', 12.9, 20.3, 0.2, 3.0, 10.9, 'ENE', 37, 'W', 'E', 11, 26, 70, 57, 1028.8, 1025.6, 3, 1, 16.9, 19.8, 'No', 'No'), ('10/21/2010', 13.3, 21.5, 0.0, 6.6, 11.0, 'ENE', 41, 'W', 'ENE', 11, 28, 75, 58, 1025.9, 1022.4, 2, 5, 17.6, 21.3, 'No', 'No'), ('10/22/2010', 15.3, 23.0, 0.0, 5.6, 11.0, 'NNE', 41, 'W', 'ENE', 6, 19, 70, 63, 1021.4, 1017.8, 1, 4, 19.0, 22.2, 'No', 'No'), ('10/23/2010', 15.8, 27.2, 0.0, 8.0, 6.9, 'NW', 52, 'W', 'WSW', 7, 4, 59, 82, 1016.6, 1015.1, 5, 4, 21.4, 19.3, 'No', 'Yes'), ('10/24/2010', 14.1, 15.7, 30.6, 7.4, 0.0, 'SSE', 48, 'SSE', 'S', 22, 20, 92, 75, 1021.1, 1020.6, 5, 4, 14.1, 15.7, 'Yes', 'Yes'), ('10/26/2010', 12.9, 26.7, 0.2, 3.8, 12.1, 'NE', 33, 'W', 'ENE', 13, 24, 73, 56, 1018.0, 1015.0, 1, 5, 17.8, 22.5, 'No', 'No'), ('10/27/2010', 14.8, 23.8, 0.0, 6.8, 9.6, 'SSE', 54, 'SSE', 'SE', 13, 26, 76, 69, 1016.0, 1014.7, 2, 7, 20.2, 20.6, 'No', 'Yes'), ('10/28/2010', 16.4, 21.4, 1.8, 5.4, 8.9, 'ESE', 33, 'SE', 'ESE', 17, 19, 65, 53, 1021.5, 1020.4, 5, 4, 18.3, 20.2, 'Yes', 'No'), ('10/29/2010', 14.5, 22.1, 0.2, 6.2, 1.8, 'ENE', 31, 'WNW', 'ENE', 11, 15, 82, 59, 1020.7, 1017.5, 7, 7, 16.2, 20.5, 'No', 'No'), ('10/30/2010', 16.2, 24.4, 0.0, 3.2, 9.9, 'NE', 56, 'N', 'NE', 9, 22, 70, 64, 1015.1, 1012.2, 5, 4, 22.0, 23.8, 'No', 'No'), ('10/31/2010', 19.3, 24.7, 0.0, 7.2, 5.5, 'NE', 50, 'NE', 'NE', 19, 28, 81, 64, 1012.0, 1010.6, 5, 4, 20.7, 24.2, 'No', 'Yes'), ('11/1/2010', 18.1, 20.4, 5.2, 6.6, 0.1, 'SSE', 48, 'S', 'SSE', 22, 28, 78, 77, 1014.7, 1012.1, 8, 8, 18.7, 18.6, 'Yes', 'Yes'), ('11/2/2010', 11.8, 17.9, 32.6, 3.8, 1.7, 'WSW', 54, 'W', 'SSE', 31, 24, 77, 59, 1011.8, 1012.8, 5, 7, 13.3, 17.8, 'Yes', 'No'), ('11/3/2010', 12.0, 23.9, 0.2, 4.0, 11.9, 'SE', 44, 'W', 'ESE', 13, 24, 65, 54, 1018.1, 1016.3, 1, 3, 17.6, 20.7, 'No', 'No'), ('11/4/2010', 14.4, 18.1, 0.4, 5.4, 2.8, 'ESE', 48, 'S', 'SE', 15, 20, 83, 68, 1022.3, 1020.5, 7, 7, 14.8, 17.6, 'No', 'Yes'), ('11/5/2010', 13.4, 19.2, 8.4, 8.4, 2.7, 'SE', 46, 'SE', 'SSE', 17, 30, 67, 53, 1023.9, 1022.1, 7, 7, 15.2, 17.8, 'Yes', 'Yes'), ('11/6/2010', 13.6, 18.8, 26.0, 4.8, 2.5, 'ESE', 37, 'SSW', 'SSE', 7, 15, 93, 81, 1023.8, 1021.9, 5, 4, 14.1, 16.7, 'Yes', 'Yes'), ('11/7/2010', 13.4, 23.3, 8.8, 3.6, 10.9, 'NE', 37, 'WNW', 'E', 13, 26, 77, 59, 1021.3, 1018.1, 5, 4, 16.6, 20.7, 'Yes', 'No'), ('11/8/2010', 16.1, 26.3, 0.0, 5.8, 7.9, 'SW', 74, 'E', 'NNE', 7, 28, 64, 52, 1017.2, 1015.1, 3, 7, 23.3, 23.8, 'No', 'Yes'), ('11/9/2010', 17.2, 23.6, 5.6, 11.2, 7.0, 'SSE', 37, 'SSE', 'E', 22, 11, 80, 54, 1025.0, 1024.2, 7, 8, 19.7, 23.2, 'Yes', 'No'), ('11/10/2010', 18.2, 24.5, 0.0, 3.2, 6.0, 'N', 52, 'WNW', 'ENE', 6, 30, 87, 72, 1021.8, 1017.1, 5, 7, 20.9, 23.5, 'No', 'Yes'), ('11/11/2010', 19.7, 27.2, 8.6, 7.2, 9.3, 'E', 30, 'ESE', 'E', 7, 24, 77, 43, 1014.9, 1012.0, 5, 3, 20.1, 25.0, 'Yes', 'No'), ('11/14/2010', 20.5, 30.4, 0.0, 9.0, 10.2, 'NNE', 50, 'ENE', 'NNE', 13, 28, 70, 56, 1015.7, 1012.8, 5, 4, 26.1, 27.2, 'No', 'No'), ('11/15/2010', 22.3, 23.9, 0.0, 10.4, 0.0, 'SSE', 30, 'SW', 'SE', 9, 7, 70, 95, 1012.8, 1012.6, 5, 4, 23.9, 19.4, 'No', 'Yes'), ('11/16/2010', 17.4, 23.5, 21.0, 1.0, 7.9, 'ESE', 35, 'S', 'SSE', 13, 20, 82, 65, 1013.3, 1011.3, 7, 3, 18.8, 22.8, 'Yes', 'No'), ('11/17/2010', 17.1, 22.3, 0.4, 6.6, 4.2, 'SSE', 28, 'S', 'E', 17, 15, 80, 61, 1017.1, 1015.7, 7, 6, 17.5, 21.0, 'No', 'No'), ('11/18/2010', 16.8, 23.4, 1.0, 3.6, 8.8, 'NE', 35, 'N', 'NE', 7, 20, 65, 59, 1015.2, 1012.2, 3, 6, 22.3, 22.6, 'No', 'No'), ('11/19/2010', 16.7, 20.0, 0.0, 8.0, 0.4, 'SSE', 67, 'S', 'SSE', 26, 33, 71, 58, 1021.8, 1024.0, 7, 8, 17.4, 18.5, 'No', 'No'), ('11/22/2010', 16.5, 24.0, 0.0, 9.0, 11.4, 'NE', 44, 'WNW', 'E', 4, 26, 82, 54, 1026.0, 1024.3, 6, 2, 19.3, 23.2, 'No', 'No'), ('11/24/2010', 17.5, 24.7, 0.0, 11.0, 12.6, 'NE', 56, 'NNE', 'NE', 17, 26, 60, 58, 1025.3, 1022.0, 2, 1, 22.8, 24.1, 'No', 'No'), ('11/25/2010', 18.5, 26.0, 0.0, 8.8, 12.1, 'NE', 44, 'E', 'NE', 17, 20, 67, 53, 1020.5, 1017.7, 1, 1, 22.5, 25.2, 'No', 'No'), ('11/26/2010', 18.9, 24.1, 0.0, 11.6, 9.0, 'NE', 37, 'E', 'E', 13, 19, 62, 72, 1017.3, 1015.3, 5, 7, 23.9, 22.4, 'No', 'No'), ('11/27/2010', 18.2, 25.8, 0.0, 6.0, 10.8, 'NNE', 63, 'E', 'NE', 6, 28, 77, 56, 1015.6, 1012.0, 5, 4, 22.3, 25.5, 'No', 'No'), ('11/28/2010', 19.0, 23.5, 0.0, 10.8, 0.0, 'NNE', 44, 'NE', 'NE', 9, 13, 73, 64, 1010.9, 1010.2, 5, 4, 21.7, 23.0, 'No', 'Yes'), ('11/29/2010', 16.8, 21.5, 5.8, 3.4, 0.0, 'SSW', 56, 'SSW', 'S', 30, 28, 85, 77, 1013.6, 1012.9, 5, 4, 18.0, 20.8, 'Yes', 'Yes'), ('11/30/2010', 16.4, 21.6, 5.6, 1.8, 0.9, 'SSW', 44, 'S', 'SSE', 11, 17, 94, 91, 1016.4, 1014.5, 8, 8, 17.3, 20.2, 'Yes', 'Yes'), ('12/1/2010', 17.2, 20.1, 27.6, 3.4, 0.0, 'E', 43, 'ENE', 'E', 30, 19, 94, 89, 1016.4, 1015.3, 8, 8, 18.9, 19.9, 'Yes', 'Yes'), ('12/2/2010', 18.5, 24.3, 21.0, 1.8, 5.4, 'ENE', 44, 'ENE', 'ENE', 17, 22, 91, 78, 1018.0, 1015.9, 8, 7, 20.1, 22.7, 'Yes', 'No'), ('12/3/2010', 19.8, 24.4, 0.2, 5.2, 8.7, 'ENE', 43, 'NNE', 'E', 17, 24, 70, 74, 1017.3, 1014.7, 2, 6, 23.7, 23.2, 'No', 'No'), ('12/4/2010', 19.6, 22.7, 0.0, 7.4, 1.6, 'NE', 31, 'NNW', 'E', 6, 19, 84, 80, 1013.0, 1010.2, 5, 4, 20.9, 22.0, 'No', 'Yes'), ('12/6/2010', 20.4, 25.7, 1.0, 5.8, 11.4, 'ESE', 28, 'ESE', 'ESE', 7, 19, 74, 67, 1014.2, 1013.3, 5, 5, 23.6, 25.5, 'No', 'No'), ('12/7/2010', 21.0, 26.0, 0.0, 8.0, 13.2, 'ENE', 43, 'E', 'ENE', 19, 24, 73, 63, 1016.5, 1015.4, 6, 3, 23.5, 25.4, 'No', 'No'), ('12/8/2010', 20.8, 26.3, 0.0, 7.6, 12.2, 'NE', 63, 'NE', 'NE', 15, 28, 67, 68, 1016.7, 1012.5, 3, 5, 24.8, 25.7, 'No', 'No'), ('12/9/2010', 22.0, 30.7, 0.0, 10.4, 2.6, 'N', 31, 'NE', 'SSE', 13, 9, 80, 62, 1010.8, 1008.2, 7, 8, 23.4, 28.3, 'No', 'No'), ('12/10/2010', 22.8, 29.6, 0.0, 4.8, 4.3, 'S', 46, 'WSW', 'E', 17, 28, 74, 72, 1009.4, 1006.0, 8, 7, 23.6, 24.0, 'No', 'No'), ('12/11/2010', 17.2, 26.9, 0.0, 6.8, 13.4, 'NE', 39, 'W', 'ENE', 13, 22, 46, 56, 1007.9, 1003.1, 5, 4, 22.2, 23.4, 'No', 'No'), ('12/12/2010', 17.8, 30.8, 0.0, 9.2, 13.3, 'SSW', 46, 'W', 'ENE', 6, 28, 47, 40, 1004.0, 1003.7, 5, 4, 24.8, 26.1, 'No', 'No'), ('12/13/2010', 18.5, 26.3, 0.0, 10.2, 12.8, 'SSW', 44, 'SSW', 'ESE', 15, 24, 62, 51, 1013.5, 1012.7, 2, 1, 22.6, 25.5, 'No', 'No'), ('12/15/2010', 20.0, 25.6, 0.0, 6.0, 10.7, 'NNE', 43, 'E', 'E', 11, 24, 71, 69, 1010.8, 1006.7, 4, 4, 24.0, 24.7, 'No', 'No'), ('12/16/2010', 21.7, 26.4, 0.0, 7.6, 3.9, 'SSE', 52, 'ENE', 'NNW', 4, 6, 72, 91, 1003.8, 1006.0, 5, 8, 24.7, 20.6, 'No', 'Yes'), ('12/17/2010', 18.0, 26.4, 7.6, 5.8, 3.8, 'NW', 41, 'SSW', 'ESE', 6, 6, 75, 71, 1005.7, 1003.5, 8, 6, 20.5, 23.0, 'Yes', 'No'), ('12/18/2010', 19.6, 25.5, 0.0, 7.8, 4.1, 'W', 57, 'NW', 'NW', 24, 26, 57, 44, 1003.1, 999.6, 5, 4, 20.7, 25.4, 'No', 'No'), ('12/19/2010', 18.5, 27.3, 0.0, 5.0, 5.0, 'WSW', 65, 'N', 'N', 15, 33, 69, 44, 1003.5, 995.6, 5, 4, 19.8, 26.4, 'No', 'Yes'), ('12/20/2010', 13.3, 21.7, 4.8, 9.2, 11.6, 'W', 72, 'W', 'W', 41, 41, 42, 32, 997.6, 1000.7, 1, 2, 16.7, 21.3, 'Yes', 'No'), ('12/21/2010', 15.4, 27.8, 0.0, 8.4, 13.5, 'W', 52, 'WNW', 'WNW', 26, 20, 36, 26, 1008.7, 1007.9, 1, 1, 21.3, 27.1, 'No', 'No'), ('12/22/2010', 17.7, 25.7, 0.0, 9.2, 12.7, 'SE', 41, 'SE', 'SSE', 19, 26, 71, 61, 1018.5, 1017.6, 5, 5, 22.0, 25.2, 'No', 'No'), ('12/23/2010', 19.1, 27.0, 0.0, 8.4, 7.5, 'SSE', 59, 'W', 'E', 9, 19, 72, 57, 1018.1, 1016.5, 6, 5, 21.4, 26.2, 'No', 'No'), ('12/24/2010', 18.7, 24.1, 0.0, 8.0, 8.0, 'SE', 44, 'ESE', 'ESE', 19, 19, 65, 47, 1026.1, 1023.7, 5, 4, 19.8, 23.6, 'No', 'No'), ('12/25/2010', 16.0, 26.3, 0.0, 7.0, 12.5, 'ENE', 43, 'W', 'NE', 0, 19, 69, 61, 1017.2, 1011.4, 5, 4, 21.5, 25.5, 'No', 'No'), ('12/26/2010', 20.8, 31.3, 0.8, 8.0, 3.5, 'SSE', 76, 'W', 'WNW', 20, 15, 88, 56, 1006.3, 1001.4, 5, 4, 21.1, 28.7, 'No', 'Yes'), ('12/27/2010', 18.4, 19.9, 17.0, 11.8, 0.3, 'SSE', 57, 'SSW', 'SSE', 15, 28, 88, 78, 1005.5, 1005.8, 5, 4, 18.5, 18.9, 'Yes', 'Yes'), ('12/28/2010', 15.4, 21.2, 1.8, 5.4, 2.5, 'SSE', 39, 'SSE', 'ESE', 11, 19, 59, 50, 1018.9, 1019.1, 5, 4, 19.0, 20.7, 'Yes', 'No'), ('12/29/2010', 17.3, 24.7, 0.0, 5.2, 12.7, 'NE', 48, 'WSW', 'NE', 4, 28, 66, 56, 1018.5, 1014.8, 5, 4, 21.1, 24.1, 'No', 'No'), ('12/30/2010', 20.0, 26.5, 0.0, 8.6, 13.1, 'E', 30, 'E', 'E', 7, 20, 64, 63, 1016.6, 1015.3, 5, 4, 24.7, 24.8, 'No', 'No'), ('12/31/2010', 21.4, 27.2, 0.0, 8.8, 11.7, 'NE', 46, 'ESE', 'ENE', 7, 28, 78, 65, 1016.0, 1013.9, 5, 4, 24.0, 26.4, 'No', 'No'), ('1/1/2011', 20.5, 29.0, 0.0, 10.0, 10.8, 'NE', 39, 'E', 'ENE', 13, 20, 69, 58, 1013.2, 1010.1, 5, 4, 25.5, 27.1, 'No', 'No'), ('1/2/2011', 20.7, 28.0, 0.0, 10.6, 8.6, 'S', 52, 'SE', 'SSE', 9, 26, 72, 62, 1011.9, 1010.8, 5, 4, 24.7, 26.6, 'No', 'Yes'), ('1/3/2011', 18.9, 21.3, 5.6, 7.2, 0.1, 'SSW', 50, 'S', 'SSE', 17, 20, 81, 84, 1014.5, 1013.9, 5, 4, 19.9, 19.2, 'Yes', 'Yes'), ('1/4/2011', 17.3, 22.6, 3.0, 5.0, 1.9, 'SSE', 35, 'SSW', 'SE', 20, 19, 74, 60, 1014.1, 1011.6, 5, 4, 20.1, 21.8, 'Yes', 'No'), ('1/5/2011', 17.2, 23.4, 0.0, 5.4, 7.2, 'S', 26, 'WNW', 'E', 6, 20, 64, 57, 1008.0, 1005.8, 5, 4, 21.1, 23.0, 'No', 'No'), ('1/6/2011', 19.5, 26.8, 0.0, 5.2, 12.3, 'S', 41, 'S', 'S', 20, 17, 72, 57, 1010.8, 1011.1, 5, 4, 22.6, 24.9, 'No', 'Yes'), ('1/7/2011', 19.9, 26.5, 7.6, 6.4, 4.8, 'ESE', 33, 'SSE', 'E', 9, 17, 88, 67, 1013.6, 1013.0, 5, 4, 22.1, 26.5, 'Yes', 'Yes'), ('1/8/2011', 21.3, 26.7, 6.6, 5.2, 10.3, 'ENE', 31, 'ENE', 'E', 11, 20, 68, 62, 1013.8, 1012.1, 5, 4, 24.3, 26.4, 'Yes', 'Yes'), ('1/9/2011', 22.0, 27.0, 9.4, 4.6, 7.5, 'E', 44, 'ENE', 'E', 22, 20, 82, 67, 1014.4, 1014.3, 5, 4, 24.0, 26.6, 'Yes', 'Yes'), ('1/10/2011', 21.5, 26.2, 5.4, 7.0, 6.6, 'E', 48, 'ENE', 'E', 20, 26, 80, 65, 1016.4, 1014.7, 5, 4, 24.1, 26.0, 'Yes', 'No'), ('1/11/2011', 21.8, 25.2, 0.4, 6.6, 0.8, 'ENE', 44, 'E', 'NE', 20, 20, 71, 79, 1014.5, 1012.1, 5, 4, 24.3, 24.3, 'No', 'Yes'), ('1/12/2011', 22.3, 27.9, 1.6, 4.4, 5.6, 'NE', 54, 'ENE', 'NE', 13, 28, 79, 71, 1012.3, 1011.6, 5, 4, 25.2, 26.4, 'Yes', 'No'), ('1/13/2011', 23.3, 26.6, 0.2, 10.6, 1.9, 'ENE', 44, 'NE', 'ENE', 15, 28, 75, 65, 1014.8, 1013.5, 5, 4, 25.0, 24.9, 'No', 'No'), ('1/14/2011', 21.8, 27.9, 0.2, 4.6, 9.8, 'NNE', 54, 'NNE', 'NE', 19, 28, 56, 53, 1012.4, 1009.3, 5, 4, 26.5, 27.6, 'No', 'No'), ('1/15/2011', 22.0, 30.4, 0.6, 11.4, 1.6, 'NNE', 37, 'N', 'ENE', 9, 7, 87, 61, 1009.4, 1007.0, 5, 4, 22.6, 29.6, 'No', 'No'), ('1/16/2011', 22.1, 28.1, 0.2, 4.2, 7.9, 'SSW', 30, 'S', 'ESE', 11, 15, 86, 65, 1010.2, 1007.4, 5, 4, 23.1, 28.0, 'No', 'No'), ('1/17/2011', 21.4, 29.8, 0.0, 8.8, 9.6, 'S', 52, 'E', 'SSE', 13, 24, 65, 68, 1002.8, 1001.5, 5, 4, 25.8, 26.3, 'No', 'No'), ('1/18/2011', 20.0, 26.1, 0.0, 8.0, 7.3, 'E', 31, 'S', 'ESE', 13, 20, 68, 57, 1007.5, 1007.3, 5, 4, 22.4, 24.8, 'No', 'Yes'), ('1/19/2011', 19.3, 25.4, 7.2, 5.6, 3.6, 'E', 44, 'S', 'ENE', 17, 20, 83, 73, 1009.8, 1009.3, 5, 4, 21.6, 24.5, 'Yes', 'No'), ('1/20/2011', 21.5, 27.3, 0.2, 5.8, 12.3, 'E', 39, 'E', 'ENE', 20, 24, 62, 55, 1013.5, 1013.4, 5, 4, 24.8, 26.3, 'No', 'Yes'), ('1/21/2011', 20.7, 26.9, 5.6, 8.2, 12.4, 'NE', 41, 'ESE', 'ENE', 4, 28, 66, 60, 1015.2, 1013.1, 5, 4, 25.1, 26.3, 'Yes', 'No'), ('1/22/2011', 20.5, 28.4, 0.0, 10.2, 11.7, 'ENE', 31, 'NE', 'E', 13, 26, 64, 55, 1016.3, 1015.2, 5, 4, 25.0, 26.7, 'No', 'No'), ('1/23/2011', 21.4, 28.3, 0.0, 11.0, 10.2, 'NNE', 50, 'NNE', 'NE', 20, 28, 57, 57, 1012.2, 1009.1, 5, 4, 25.2, 26.1, 'No', 'No'), ('1/24/2011', 21.0, 35.4, 0.0, 10.8, 7.5, 'SSW', 69, 'NNE', 'NW', 11, 26, 56, 36, 1004.1, 1001.4, 5, 4, 26.6, 32.4, 'No', 'No'), ('1/25/2011', 21.7, 28.5, 0.0, 10.6, 10.2, 'S', 50, 'WSW', 'ENE', 4, 20, 70, 64, 1008.0, 1006.9, 5, 4, 24.3, 27.2, 'No', 'No'), ('1/26/2011', 22.9, 31.4, 0.0, 7.0, 9.3, 'SSE', 46, 'ESE', 'E', 11, 15, 85, 73, 1011.5, 1010.2, 5, 4, 25.8, 27.7, 'No', 'No'), ('1/27/2011', 22.5, 28.4, 0.0, 7.2, 6.3, 'S', 43, 'S', 'E', 9, 17, 79, 71, 1013.5, 1011.1, 5, 4, 25.1, 27.3, 'No', 'No'), ('1/28/2011', 22.5, 24.3, 0.0, 7.2, 4.3, 'SE', 41, 'SSE', 'SSE', 20, 24, 70, 59, 1019.0, 1019.1, 5, 4, 23.1, 24.1, 'No', 'No'), ('1/29/2011', 19.8, 25.0, 0.0, 7.8, 8.2, 'E', 39, 'ENE', 'ENE', 11, 24, 76, 48, 1021.6, 1021.3, 5, 4, 20.7, 24.6, 'No', 'No'), ('1/30/2011', 17.8, 28.2, 0.0, 8.4, 12.8, 'NNE', 43, 'NNW', 'ENE', 15, 24, 64, 56, 1020.2, 1016.3, 5, 4, 23.1, 27.5, 'No', 'No'), ('1/31/2011', 22.2, 31.6, 0.0, 9.2, 12.8, 'ENE', 33, 'ENE', 'ENE', 2, 17, 72, 49, 1015.0, 1011.8, 5, 4, 26.1, 30.0, 'No', 'No'), ('2/1/2011', 22.7, 33.5, 0.0, 12.0, 12.3, 'NNE', 37, 'W', 'NE', 7, 17, 65, 49, 1011.3, 1006.9, 5, 4, 26.1, 31.8, 'No', 'No'), ('2/2/2011', 26.1, 31.2, 0.0, 12.8, 11.0, 'NE', 35, 'SSE', 'E', 13, 20, 59, 70, 1015.3, 1012.7, 5, 4, 28.7, 28.4, 'No', 'No'), ('2/3/2011', 25.1, 37.5, 0.0, 10.2, 5.7, 'SSW', 70, 'SSE', 'SSW', 11, 24, 58, 54, 1011.0, 1009.9, 5, 4, 30.6, 33.6, 'No', 'No'), ('2/4/2011', 24.0, 33.7, 0.0, 5.2, 6.8, 'ENE', 43, 'N', 'ENE', 7, 28, 72, 73, 1014.7, 1011.1, 5, 4, 27.3, 27.8, 'No', 'No'), ('2/5/2011', 24.2, 41.5, 0.0, 8.4, 12.4, 'NNW', 56, 'NW', 'NNW', 24, 33, 46, 22, 1010.0, 1006.6, 5, 4, 33.7, 40.9, 'No', 'No'), ('2/6/2011', 27.6, 35.6, 0.0, 16.6, 2.6, 'SSE', 67, 'W', 'S', 2, 41, 56, 77, 1012.7, 1016.1, 5, 4, 28.7, 22.8, 'No', 'No'), ('2/7/2011', 18.0, 23.0, 0.2, 6.8, 0.0, 'S', 35, 'WSW', 'SE', 13, 19, 64, 58, 1023.9, 1020.6, 5, 4, 18.7, 22.6, 'No', 'No'), ('2/8/2011', 18.7, 25.3, 0.2, 4.8, 3.9, 'ESE', 30, 'WNW', 'ESE', 11, 17, 67, 52, 1019.5, 1018.6, 5, 4, 21.2, 24.2, 'No', 'No'), ('2/9/2011', 18.1, 24.5, 0.4, 5.2, 6.0, 'E', 33, 'SSW', 'ENE', 13, 11, 69, 83, 1024.5, 1023.6, 5, 4, 21.8, 21.6, 'No', 'No'), ('2/10/2011', 20.4, 25.7, 0.0, 7.2, 4.7, 'NNE', 41, 'W', 'E', 7, 24, 85, 70, 1023.4, 1020.3, 5, 4, 21.3, 24.3, 'No', 'No'), ('2/11/2011', 21.0, 29.2, 0.2, 5.0, 8.0, 'SSW', 39, 'NNE', 'ENE', 7, 13, 63, 60, 1016.0, 1011.4, 5, 4, 25.3, 28.3, 'No', 'Yes'), ('2/12/2011', 22.7, 23.1, 1.4, 8.6, 0.0, 'S', 52, 'S', 'S', 30, 26, 87, 76, 1014.7, 1016.4, 5, 4, 22.7, 22.2, 'Yes', 'Yes'), ('2/13/2011', 19.5, 22.8, 9.6, 2.4, 0.0, 'SSE', 54, 'SSW', 'S', 11, 26, 83, 88, 1017.5, 1018.4, 5, 4, 21.5, 21.3, 'Yes', 'No'), ('2/14/2011', 20.6, 24.2, 0.4, 4.0, 0.1, 'SSE', 41, 'SE', 'SE', 20, 19, 59, 59, 1023.6, 1023.4, 5, 4, 21.9, 23.6, 'No', 'No'), ('2/15/2011', 18.3, 25.0, 0.0, 6.6, 3.0, 'ESE', 31, 'WNW', 'ESE', 9, 20, 84, 54, 1023.7, 1022.0, 5, 4, 20.7, 24.0, 'No', 'Yes'), ('2/16/2011', 19.8, 26.7, 2.2, 3.6, 3.9, 'NE', 28, 'WNW', 'E', 15, 19, 81, 64, 1019.7, 1016.3, 5, 4, 20.9, 25.7, 'Yes', 'No'), ('2/17/2011', 20.9, 28.7, 0.0, 6.4, 8.3, 'NNE', 31, 'NNW', 'E', 11, 15, 80, 67, 1013.7, 1011.2, 5, 4, 24.4, 26.8, 'No', 'No'), ('2/18/2011', 22.6, 27.6, 0.0, 5.0, 3.8, 'S', 43, 'S', 'SE', 20, 13, 83, 70, 1014.7, 1014.0, 5, 4, 23.5, 27.0, 'No', 'No'), ('2/19/2011', 22.4, 30.1, 0.0, 4.4, 7.8, 'NNE', 44, 'NNE', 'NE', 15, 28, 79, 67, 1011.2, 1006.3, 5, 4, 25.1, 28.4, 'No', 'No'), ('2/20/2011', 25.0, 33.2, 0.0, 7.2, 9.5, 'ESE', 28, 'E', 'SE', 6, 13, 61, 49, 1006.4, 1005.7, 5, 4, 30.1, 32.0, 'No', 'No'), ('2/21/2011', 20.0, 24.9, 0.0, 8.2, 4.3, 'S', 65, 'SSE', 'SE', 17, 20, 82, 62, 1012.7, 1012.4, 5, 4, 20.9, 24.4, 'No', 'No'), ('2/22/2011', 19.1, 21.7, 0.4, 9.0, 3.2, 'SSE', 50, 'SSE', 'SSE', 22, 26, 57, 78, 1021.6, 1022.6, 5, 4, 20.4, 19.2, 'No', 'Yes'), ('2/23/2011', 17.3, 26.6, 1.8, 4.2, 7.3, 'SSE', 33, 'W', 'SSE', 13, 20, 77, 45, 1023.1, 1021.3, 5, 4, 19.0, 26.1, 'Yes', 'No'), ('2/24/2011', 16.6, 26.1, 0.4, 5.0, 12.0, 'ENE', 35, 'W', 'E', 17, 22, 71, 49, 1019.9, 1016.0, 5, 4, 20.3, 24.9, 'No', 'No'), ('2/25/2011', 18.0, 28.0, 0.0, 7.4, 7.6, 'E', 30, 'WNW', 'NNE', 7, 20, 75, 41, 1014.5, 1012.2, 5, 4, 21.1, 27.1, 'No', 'No'), ('2/26/2011', 20.9, 27.2, 0.0, 7.6, 11.1, 'ENE', 41, 'WNW', 'E', 4, 26, 80, 65, 1012.5, 1009.5, 5, 4, 23.7, 26.8, 'No', 'No'), ('2/27/2011', 20.3, 30.3, 0.0, 8.0, 1.4, 'SSW', 37, 'W', 'WNW', 17, 6, 74, 63, 1008.3, 1007.5, 5, 4, 22.3, 26.9, 'No', 'No'), ('2/28/2011', 22.2, 28.8, 0.8, 5.0, 2.4, 'N', 46, 'NE', 'ENE', 13, 26, 83, 65, 1009.9, 1007.8, 5, 4, 22.7, 26.1, 'No', 'No'), ('3/1/2011', 22.7, 33.6, 0.6, 4.4, 1.9, 'SSE', 54, 'W', 'WNW', 9, 17, 53, 39, 1002.4, 1003.1, 5, 4, 28.8, 32.5, 'No', 'No'), ('3/2/2011', 19.4, 21.8, 0.0, 9.2, 0.0, 'SSE', 43, 'ESE', 'E', 19, 11, 58, 59, 1017.1, 1015.0, 5, 4, 20.5, 21.2, 'No', 'No'), ('3/3/2011', 17.4, 31.7, 0.0, 2.2, 10.5, 'ESE', 33, 'W', 'SE', 20, 28, 77, 35, 1009.1, 1007.1, 5, 4, 20.9, 29.5, 'No', 'No'), ('3/4/2011', 19.1, 25.8, 0.0, 8.0, 9.4, 'SSE', 46, 'W', 'E', 9, 24, 72, 63, 1011.7, 1009.8, 5, 4, 22.5, 25.4, 'No', 'No'), ('3/5/2011', 18.1, 23.2, 0.2, 8.2, 0.6, 'ESE', 43, 'SSE', 'ESE', 22, 28, 70, 50, 1022.5, 1023.5, 5, 4, 18.7, 22.2, 'No', 'No'), ('3/6/2011', 18.0, 23.6, 0.2, 8.2, 2.9, 'ESE', 35, 'SSE', 'E', 17, 19, 48, 44, 1026.9, 1026.3, 5, 4, 21.0, 22.2, 'No', 'No'), ('3/7/2011', 17.0, 24.4, 0.0, 4.8, 10.1, 'ENE', 33, 'ESE', 'E', 9, 20, 67, 48, 1024.8, 1022.2, 5, 4, 20.3, 23.8, 'No', 'No'), ('3/8/2011', 17.6, 25.8, 0.2, 6.8, 10.4, 'NNE', 48, 'W', 'NE', 7, 30, 71, 60, 1019.7, 1015.8, 5, 4, 21.2, 25.2, 'No', 'No'), ('3/9/2011', 20.7, 30.8, 0.0, 8.0, 2.3, 'NW', 24, 'W', 'NW', 6, 17, 77, 38, 1015.2, 1013.1, 5, 4, 21.8, 30.6, 'No', 'No'), ('3/10/2011', 21.8, 27.4, 0.0, 6.2, 0.0, 'SE', 24, 'W', 'ENE', 6, 9, 70, 68, 1013.3, 1012.0, 5, 4, 23.8, 25.2, 'No', 'No'), ('3/11/2011', 22.0, 26.7, 0.0, 3.6, 1.8, 'ESE', 22, 'S', 'ESE', 7, 19, 86, 76, 1016.0, 1015.3, 5, 4, 23.2, 25.3, 'No', 'No'), ('3/12/2011', 20.6, 28.1, 1.0, 3.2, 9.8, 'W', 41, 'N', 'E', 4, 20, 82, 69, 1020.8, 1019.2, 5, 4, 23.3, 26.1, 'No', 'No'), ('3/13/2011', 21.8, 27.7, 0.2, 6.4, 10.7, 'W', 41, 'N', 'NE', 9, 22, 76, 60, 1021.5, 1018.2, 5, 4, 24.5, 27.2, 'No', 'No'), ('3/14/2011', 21.3, 27.5, 0.0, 8.0, 3.2, 'S', 59, 'WNW', 'S', 11, 31, 76, 79, 1019.4, 1020.6, 5, 4, 24.3, 22.3, 'No', 'No'), ('3/15/2011', 17.5, 24.5, 0.8, 4.0, 3.4, 'W', 28, 'WNW', 'SE', 13, 15, 82, 62, 1021.4, 1018.2, 5, 4, 21.0, 24.5, 'No', 'No'), ('3/16/2011', 19.3, 28.3, 0.0, 3.2, 7.7, 'ESE', 33, 'W', 'SE', 11, 20, 77, 65, 1017.2, 1016.8, 5, 4, 22.3, 25.3, 'No', 'Yes'), ('3/17/2011', 20.6, 26.8, 5.6, 5.8, 5.9, 'S', 31, 'S', 'SE', 17, 17, 85, 66, 1019.4, 1017.0, 5, 4, 21.1, 25.8, 'Yes', 'No'), ('3/18/2011', 20.0, 25.2, 0.0, 5.4, 0.9, 'ESE', 39, 'SSW', 'SSE', 19, 20, 81, 67, 1015.2, 1014.0, 5, 4, 21.1, 24.8, 'No', 'Yes'), ('3/19/2011', 19.4, 24.0, 10.4, 5.2, 0.9, 'ESE', 46, 'ESE', 'ESE', 24, 24, 86, 84, 1014.1, 1011.8, 5, 4, 21.2, 22.9, 'Yes', 'Yes'), ('3/20/2011', 18.8, 23.5, 99.4, 4.8, 3.3, 'E', 59, 'ESE', 'ESE', 22, 39, 92, 81, 1012.4, 1010.1, 5, 4, 19.4, 22.2, 'Yes', 'Yes'), ('3/21/2011', 19.4, 24.8, 20.8, 5.2, 2.6, 'ENE', 57, 'E', 'E', 26, 19, 95, 82, 1006.6, 1003.3, 5, 4, 21.4, 24.0, 'Yes', 'Yes'), ('3/22/2011', 21.1, 27.4, 27.8, 1.6, 10.2, 'ENE', 24, 'WNW', 'ENE', 9, 20, 95, 73, 1001.3, 999.4, 5, 4, 21.6, 26.2, 'Yes', 'No'), ('3/23/2011', 19.9, 30.8, 0.8, 5.8, 11.0, 'W', 39, 'W', 'W', 19, 13, 75, 41, 1002.6, 1000.4, 5, 4, 22.5, 29.6, 'No', 'No'), ('3/24/2011', 18.2, 27.1, 0.2, 8.6, 10.8, 'WNW', 57, 'NW', 'WNW', 28, 35, 50, 36, 1005.0, 1003.2, 5, 4, 21.5, 26.3, 'No', 'No'), ('3/25/2011', 17.7, 26.7, 0.0, 8.8, 8.0, 'W', 46, 'W', 'S', 28, 13, 50, 42, 1007.8, 1008.7, 5, 4, 20.5, 24.8, 'No', 'No'), ('3/26/2011', 17.7, 20.6, 0.0, 5.2, 0.4, 'S', 56, 'SSW', 'S', 28, 20, 71, 77, 1019.2, 1020.1, 5, 4, 18.4, 18.6, 'No', 'Yes'), ('3/27/2011', 16.1, 20.5, 5.0, 5.4, 2.5, 'SSE', 41, 'WNW', 'SSW', 17, 19, 89, 87, 1024.6, 1024.5, 5, 4, 16.6, 18.4, 'Yes', 'Yes'), ('3/28/2011', 15.9, 24.2, 5.8, 1.6, 3.2, 'E', 33, 'W', 'E', 15, 15, 91, 59, 1026.7, 1025.5, 5, 4, 17.1, 23.5, 'Yes', 'Yes'), ('3/29/2011', 17.1, 24.8, 10.8, 1.8, 8.3, 'NE', 43, 'WNW', 'NE', 4, 24, 94, 59, 1025.8, 1022.3, 5, 4, 19.4, 24.3, 'Yes', 'No'), ('3/30/2011', 17.8, 27.7, 0.0, 6.6, 9.2, 'WSW', 41, 'WNW', 'E', 13, 17, 78, 61, 1019.9, 1016.1, 5, 4, 20.5, 26.0, 'No', 'Yes'), ('3/31/2011', 20.1, 21.3, 1.8, 5.2, 0.5, 'SSE', 43, 'SSE', 'SE', 22, 20, 78, 68, 1022.7, 1022.9, 5, 4, 20.3, 20.9, 'Yes', 'Yes'), ('5/1/2011', 14.8, 22.9, 3.6, 0.8, 8.8, 'SSW', 28, 'WNW', 'S', 19, 13, 84, 57, 1018.9, 1015.9, 5, 4, 16.6, 21.6, 'Yes', 'No'), ('5/2/2011', 12.9, 18.4, 0.0, 3.8, 0.5, 'W', 31, 'W', 'WNW', 20, 13, 87, 75, 1016.6, 1014.7, 5, 4, 14.3, 18.1, 'No', 'No'), ('5/3/2011', 14.0, 18.5, 0.6, 2.4, 0.0, 'S', 41, 'W', 'SSW', 15, 20, 90, 66, 1015.0, 1013.7, 5, 4, 15.0, 18.5, 'No', 'No'), ('5/4/2011', 13.0, 21.8, 0.4, 0.2, 9.1, 'W', 41, 'W', 'S', 24, 20, 72, 54, 1016.4, 1015.6, 5, 4, 15.2, 20.7, 'No', 'No'), ('5/5/2011', 11.7, 19.5, 0.2, 4.6, 7.4, 'SSW', 50, 'SW', 'SSW', 24, 26, 63, 51, 1021.1, 1021.3, 5, 4, 16.2, 18.8, 'No', 'No'), ('5/6/2011', 10.1, 19.6, 0.0, 4.4, 8.7, 'SSE', 33, 'W', 'S', 19, 17, 69, 48, 1023.9, 1020.4, 5, 4, 13.1, 18.4, 'No', 'No'), ('5/7/2011', 9.8, 20.8, 0.0, 4.6, 10.0, 'W', 35, 'W', 'ESE', 22, 9, 75, 52, 1019.5, 1015.2, 5, 4, 12.0, 19.6, 'No', 'No'), ('5/8/2011', 9.6, 22.0, 0.0, 1.6, 10.1, 'SW', 31, 'W', 'WSW', 20, 11, 76, 34, 1014.0, 1010.4, 5, 4, 12.2, 21.6, 'No', 'No'), ('5/9/2011', 10.5, 17.7, 0.0, 3.8, 6.9, 'W', 41, 'SSW', 'SSW', 22, 31, 63, 63, 1014.5, 1013.7, 5, 4, 14.5, 16.9, 'No', 'Yes'), ('5/10/2011', 10.1, 18.0, 4.4, 3.4, 9.1, 'SSW', 44, 'W', 'S', 26, 22, 62, 45, 1015.6, 1013.1, 5, 4, 11.8, 17.6, 'Yes', 'No'), ('5/11/2011', 8.2, 16.4, 0.2, 3.8, 3.9, 'W', 56, 'WNW', 'W', 9, 28, 64, 37, 1009.2, 1006.4, 5, 4, 11.3, 14.8, 'No', 'No'), ('5/12/2011', 7.9, 16.7, 0.0, 2.2, 10.2, 'WSW', 43, 'W', 'WSW', 26, 24, 51, 27, 1010.7, 1009.3, 5, 4, 10.5, 16.2, 'No', 'No'), ('5/13/2011', 9.9, 21.0, 0.0, 4.0, 9.3, 'SW', 41, 'W', 'W', 13, 20, 69, 40, 1012.0, 1008.1, 5, 4, 12.8, 19.8, 'No', 'No'), ('5/14/2011', 10.8, 17.9, 0.0, 3.4, 10.0, 'WSW', 52, 'W', 'WSW', 28, 20, 50, 33, 1016.0, 1017.6, 5, 4, 11.7, 16.2, 'No', 'No'), ('5/15/2011', 7.3, 19.2, 0.0, 4.8, 9.8, 'WSW', 41, 'W', 'W', 24, 11, 58, 36, 1028.8, 1026.9, 5, 4, 9.9, 19.0, 'No', 'No'), ('5/16/2011', 7.3, 19.6, 0.0, 5.0, 10.2, 'W', 30, 'W', 'ENE', 17, 13, 69, 48, 1030.1, 1026.2, 5, 4, 9.6, 17.5, 'No', 'No'), ('5/17/2011', 7.9, 20.2, 0.0, 2.2, 9.9, 'W', 30, 'W', 'S', 22, 17, 72, 59, 1030.5, 1028.1, 5, 4, 10.0, 18.9, 'No', 'No'), ('5/18/2011', 8.5, 20.8, 0.0, 2.8, 9.3, 'W', 28, 'W', 'E', 19, 9, 74, 58, 1032.6, 1029.6, 5, 4, 11.6, 19.4, 'No', 'Yes'), ('5/19/2011', 11.5, 20.5, 2.6, 1.8, 6.8, 'N', 26, 'W', 'ENE', 15, 17, 83, 70, 1031.5, 1028.2, 5, 4, 13.8, 19.3, 'Yes', 'No'), ('5/20/2011', 11.3, 21.2, 0.0, 3.8, 9.4, 'WNW', 20, 'W', 'E', 15, 11, 91, 69, 1028.3, 1024.4, 5, 4, 12.8, 19.8, 'No', 'No'), ('5/21/2011', 12.1, 23.3, 0.0, 1.0, 9.9, 'W', 22, 'WNW', 'E', 17, 11, 80, 56, 1025.4, 1021.5, 5, 4, 13.7, 20.9, 'No', 'No'), ('5/22/2011', 12.4, 21.6, 0.0, 3.4, 7.3, 'NNE', 26, 'W', 'NE', 13, 11, 79, 59, 1021.0, 1015.3, 5, 4, 13.9, 20.6, 'No', 'No'), ('5/23/2011', 13.9, 22.9, 1.0, 3.4, 7.6, 'NW', 52, 'NW', 'NW', 15, 26, 81, 37, 1005.4, 1001.4, 5, 4, 16.0, 22.4, 'No', 'No'), ('5/24/2011', 12.1, 18.8, 0.0, 6.6, 3.9, 'WNW', 39, 'WNW', 'SSE', 7, 19, 57, 75, 1005.1, 1005.0, 5, 4, 14.6, 15.5, 'No', 'Yes'), ('5/25/2011', 11.1, 14.2, 12.0, 1.4, 1.8, 'SW', 69, 'SSW', 'SSW', 33, 31, 72, 69, 1011.1, 1011.1, 5, 4, 12.3, 13.9, 'Yes', 'Yes'), ('5/26/2011', 10.7, 19.6, 9.4, 1.6, 4.1, 'SW', 39, 'W', 'S', 20, 17, 63, 51, 1016.6, 1015.1, 5, 4, 12.9, 19.3, 'Yes', 'No'), ('5/27/2011', 8.8, 18.3, 0.0, 2.4, 7.2, 'W', 31, 'W', 'S', 22, 13, 69, 62, 1019.1, 1017.8, 5, 4, 10.5, 16.2, 'No', 'No'), ('5/28/2011', 8.5, 17.4, 0.0, 3.2, 3.1, 'SSE', 37, 'W', 'S', 22, 19, 75, 67, 1023.8, 1022.5, 5, 4, 10.4, 16.8, 'No', 'No'), ('5/29/2011', 10.2, 17.0, 0.0, 0.6, 0.0, 'S', 31, 'W', 'SSW', 20, 17, 82, 77, 1025.1, 1021.9, 5, 4, 11.2, 16.7, 'No', 'Yes'), ('5/30/2011', 11.2, 17.9, 36.0, 4.4, 0.0, 'ESE', 94, 'SSE', 'SSE', 30, 17, 89, 91, 1020.5, 1018.4, 5, 4, 15.4, 14.0, 'Yes', 'Yes'), ('5/31/2011', 13.9, 19.9, 65.2, 4.8, 0.7, 'E', 70, 'ESE', 'ESE', 39, 31, 81, 62, 1019.5, 1019.3, 5, 4, 17.9, 19.6, 'Yes', 'Yes'), ('6/1/2011', 16.1, 21.0, 4.6, 4.6, 0.7, 'ESE', 54, 'SE', 'ESE', 22, 37, 65, 63, 1025.3, 1025.0, 5, 4, 18.7, 18.7, 'Yes', 'Yes'), ('6/2/2011', 13.7, 19.8, 2.6, 3.2, 7.6, 'SE', 37, 'S', 'SE', 11, 19, 73, 75, 1025.3, 1022.7, 5, 4, 17.4, 18.2, 'Yes', 'No'), ('6/3/2011', 10.6, 20.4, 0.0, 1.2, 8.8, 'W', 28, 'WNW', 'WNW', 20, 6, 85, 58, 1019.7, 1014.7, 5, 4, 12.2, 18.5, 'No', 'No'), ('6/4/2011', 11.1, 18.7, 0.0, 2.8, 2.5, 'SSW', 26, 'WNW', 'W', 13, 6, 73, 62, 1015.4, 1013.7, 5, 4, 13.3, 18.3, 'No', 'Yes'), ('6/5/2011', 10.5, 17.7, 1.4, 3.0, 9.2, 'W', 39, 'W', 'W', 20, 9, 68, 47, 1018.0, 1012.9, 5, 4, 11.6, 16.5, 'Yes', 'No'), ('6/6/2011', 9.3, 17.7, 0.0, 2.0, 7.4, 'WSW', 48, 'NW', 'SSE', 7, 20, 57, 62, 1016.1, 1016.2, 5, 4, 12.2, 15.0, 'No', 'No'), ('6/7/2011', 7.0, 15.0, 0.0, 4.0, 7.3, 'W', 39, 'W', 'W', 13, 24, 71, 38, 1017.7, 1013.2, 5, 4, 8.6, 14.0, 'No', 'No'), ('6/8/2011', 8.2, 14.1, 0.0, 1.8, 9.9, 'W', 67, 'WNW', 'W', 22, 30, 46, 28, 1015.0, 1012.7, 5, 4, 9.8, 13.1, 'No', 'No'), ('6/9/2011', 7.5, 16.4, 0.0, 3.6, 9.9, 'W', 54, 'WNW', 'W', 22, 28, 54, 40, 1013.4, 1011.0, 5, 4, 9.7, 15.2, 'No', 'No'), ('6/10/2011', 8.9, 15.7, 0.0, 4.8, 4.6, 'SW', 56, 'W', 'SW', 19, 31, 58, 60, 1016.0, 1017.0, 5, 4, 11.6, 14.2, 'No', 'Yes'), ('6/11/2011', 9.9, 15.7, 7.8, 0.2, 6.1, 'SE', 54, 'SSW', 'SSW', 20, 26, 86, 80, 1024.4, 1024.6, 5, 4, 12.6, 13.8, 'Yes', 'Yes'), ('6/12/2011', 11.6, 15.7, 18.2, 4.8, 0.3, 'S', 57, 'SSE', 'SSE', 28, 35, 89, 67, 1025.5, 1022.9, 5, 4, 13.6, 15.3, 'Yes', 'Yes'), ('6/13/2011', 12.8, 16.7, 23.4, 2.4, 0.0, 'SSE', 50, 'SSW', 'SE', 17, 20, 92, 62, 1023.9, 1021.1, 5, 4, 13.7, 16.3, 'Yes', 'Yes'), ('6/14/2011', 13.7, 17.8, 10.4, 3.4, 0.3, 'SSE', 67, 'SE', 'SSE', 22, 35, 81, 78, 1021.2, 1019.9, 5, 4, 15.7, 15.4, 'Yes', 'Yes'), ('6/15/2011', 14.1, 18.4, 13.8, 6.0, 0.2, 'ESE', 69, 'SSE', 'SE', 37, 28, 85, 63, 1023.3, 1021.4, 5, 4, 15.3, 17.4, 'Yes', 'Yes'), ('6/16/2011', 14.0, 17.1, 4.2, 3.6, 1.3, 'ESE', 54, 'SSE', 'SSW', 31, 22, 71, 68, 1021.2, 1016.8, 5, 4, 15.9, 16.3, 'Yes', 'Yes'), ('6/17/2011', 8.2, 18.3, 4.2, 1.4, 9.5, 'W', 70, 'WNW', 'WSW', 9, 39, 82, 40, 1008.2, 1005.5, 5, 4, 10.0, 15.5, 'Yes', 'No'), ('6/18/2011', 9.9, 17.7, 0.0, 3.6, 9.8, 'W', 54, 'W', 'W', 17, 39, 51, 39, 1011.6, 1009.8, 5, 4, 11.3, 17.0, 'No', 'No'), ('6/19/2011', 8.3, 18.4, 0.0, 2.8, 9.7, 'W', 30, 'W', 'WNW', 19, 9, 69, 39, 1016.4, 1014.0, 5, 4, 10.5, 17.7, 'No', 'No'), ('6/20/2011', 9.3, 19.6, 0.0, 3.4, 9.7, 'NW', 35, 'WSW', 'WNW', 11, 22, 64, 38, 1015.5, 1011.9, 5, 4, 11.9, 18.6, 'No', 'No'), ('6/21/2011', 11.8, 20.7, 0.0, 5.0, 6.8, 'W', 78, 'N', 'WSW', 20, 39, 54, 37, 1005.3, 1000.6, 5, 4, 14.2, 18.5, 'No', 'No'), ('6/22/2011', 9.6, 16.3, 0.0, 4.6, 9.2, 'WSW', 54, 'WNW', 'WSW', 19, 30, 47, 30, 1010.6, 1010.4, 5, 4, 11.2, 15.7, 'No', 'No'), ('6/23/2011', 9.8, 20.5, 0.0, 3.8, 9.4, 'SW', 50, 'W', 'WSW', 9, 9, 59, 36, 1016.8, 1017.3, 5, 4, 12.6, 19.5, 'No', 'No'), ('6/24/2011', 8.1, 18.6, 0.0, 3.4, 9.8, 'W', 26, 'W', 'NE', 20, 9, 69, 40, 1026.7, 1024.7, 5, 4, 9.8, 17.6, 'No', 'No'), ('6/25/2011', 7.7, 19.6, 0.0, 2.4, 9.5, 'W', 26, 'W', 'E', 19, 7, 79, 53, 1031.3, 1028.0, 5, 4, 9.8, 18.2, 'No', 'No'), ('6/26/2011', 7.8, 20.7, 0.0, 1.8, 9.7, 'W', 22, 'W', 'W', 13, 6, 83, 39, 1026.8, 1023.3, 5, 4, 9.0, 20.5, 'No', 'No'), ('6/27/2011', 7.5, 20.0, 0.0, 2.6, 9.6, 'W', 33, 'WNW', 'SSE', 28, 17, 66, 51, 1028.1, 1027.2, 5, 4, 10.4, 19.1, 'No', 'No'), ('6/28/2011', 9.0, 16.6, 0.0, 2.6, 0.7, 'SSE', 43, 'W', 'S', 20, 13, 86, 62, 1034.2, 1032.6, 5, 4, 10.7, 16.3, 'No', 'Yes'), ('6/29/2011', 10.7, 18.0, 2.8, 2.0, 2.6, 'ESE', 43, 'SSE', 'S', 17, 6, 74, 87, 1036.8, 1035.7, 5, 4, 15.0, 14.6, 'Yes', 'No'), ('6/30/2011', 12.1, 18.1, 0.4, 1.6, 0.7, 'SSE', 30, 'S', 'SSE', 7, 15, 76, 59, 1037.9, 1034.8, 5, 4, 14.4, 16.2, 'No', 'No'), ('7/1/2011', 10.8, 16.6, 0.4, 2.6, 1.9, 'SSE', 33, 'WNW', 'SSW', 19, 20, 91, 67, 1031.6, 1028.1, 5, 4, 12.3, 16.2, 'No', 'Yes'), ('7/2/2011', 11.3, 19.3, 2.6, 1.4, 9.6, 'W', 24, 'W', 'E', 11, 2, 91, 57, 1026.6, 1022.6, 5, 4, 12.3, 18.9, 'Yes', 'No'), ('7/3/2011', 8.6, 20.7, 0.0, 3.0, 8.1, 'N', 39, 'WNW', 'N', 17, 20, 90, 43, 1022.1, 1017.5, 5, 4, 10.1, 19.8, 'No', 'No'), ('7/4/2011', 10.1, 20.4, 0.2, 4.4, 6.9, 'NW', 50, 'NNW', 'NW', 28, 26, 50, 55, 1014.1, 1010.0, 5, 4, 17.0, 18.6, 'No', 'No'), ('7/5/2011', 12.2, 17.1, 0.0, 4.8, 9.8, 'W', 65, 'WNW', 'W', 28, 39, 36, 27, 1008.8, 1004.8, 5, 4, 14.0, 16.5, 'No', 'No'), ('7/6/2011', 10.9, 17.6, 0.0, 5.6, 9.4, 'WNW', 52, 'NW', 'NW', 20, 20, 44, 30, 1010.2, 1007.4, 5, 4, 13.0, 17.0, 'No', 'No'), ('7/7/2011', 11.1, 17.6, 0.0, 5.4, 10.0, 'W', 70, 'W', 'WSW', 44, 30, 45, 28, 1007.5, 1013.8, 5, 4, 13.9, 16.0, 'No', 'No'), ('7/8/2011', 5.5, 17.0, 0.0, 4.0, 9.9, 'WSW', 50, 'WNW', 'W', 19, 17, 59, 29, 1022.4, 1018.2, 5, 4, 8.1, 16.6, 'No', 'No'), ('7/9/2011', 6.4, 17.0, 0.0, 4.0, 10.0, 'WSW', 52, 'WNW', 'WSW', 24, 22, 49, 32, 1018.8, 1015.5, 5, 4, 9.1, 16.4, 'No', 'No'), ('7/10/2011', 6.1, 16.4, 0.0, 3.8, 10.0, 'W', 80, 'W', 'NW', 26, 31, 44, 29, 1014.5, 1010.2, 5, 4, 10.4, 15.9, 'No', 'No'), ('7/11/2011', 9.2, 17.9, 0.0, 4.0, 10.0, 'SW', 46, 'WSW', 'W', 22, 13, 41, 23, 1017.6, 1018.1, 5, 4, 11.7, 17.3, 'No', 'No'), ('7/12/2011', 6.9, 18.9, 0.0, 3.2, 9.4, 'WSW', 48, 'W', 'WNW', 19, 11, 56, 31, 1022.2, 1017.9, 5, 4, 9.5, 18.5, 'No', 'No'), ('7/13/2011', 9.5, 12.3, 0.0, 3.8, 0.0, 'WSW', 48, 'W', 'W', 20, 22, 54, 48, 1018.2, 1016.5, 5, 4, 10.3, 11.9, 'No', 'No'), ('7/14/2011', 8.2, 15.6, 0.0, 2.8, 9.9, 'SW', 44, 'W', 'S', 19, 22, 56, 35, 1025.7, 1027.4, 5, 4, 11.0, 14.6, 'No', 'No'), ('7/15/2011', 5.6, 13.2, 0.8, 2.0, 0.6, 'S', 39, 'W', 'S', 26, 13, 64, 84, 1034.7, 1032.4, 5, 4, 7.5, 12.7, 'No', 'Yes'), ('7/16/2011', 7.5, 16.3, 9.0, 1.4, 4.4, 'ENE', 26, 'W', 'E', 13, 17, 94, 62, 1031.7, 1027.7, 5, 4, 10.4, 14.8, 'Yes', 'Yes'), ('7/17/2011', 10.4, 16.1, 2.2, 1.4, 0.7, 'W', 17, 'W', 'ESE', 11, 2, 95, 86, 1025.2, 1021.5, 5, 4, 11.9, 14.5, 'Yes', 'Yes'), ('7/18/2011', 9.6, 20.3, 1.4, 1.0, 7.0, 'SW', 39, 'W', 'WNW', 22, 4, 90, 49, 1018.5, 1015.0, 5, 4, 11.2, 18.5, 'Yes', 'No'), ('7/19/2011', 7.4, 14.7, 0.6, 3.2, 5.1, 'W', 56, 'W', 'W', 22, 26, 63, 72, 1014.6, 1011.6, 5, 4, 8.7, 10.3, 'No', 'Yes'), ('7/20/2011', 8.7, 18.5, 76.8, 4.8, 1.6, 'S', 70, 'SSW', 'SSW', 24, 24, 91, 83, 1012.7, 1013.5, 5, 4, 14.3, 15.0, 'Yes', 'Yes'), ('7/21/2011', 11.1, 13.3, 39.2, 6.4, 0.0, 'WSW', 56, 'SW', 'SW', 22, 30, 94, 92, 1016.6, 1014.3, 5, 4, 12.0, 11.4, 'Yes', 'Yes'), ('7/22/2011', 11.3, 13.9, 88.2, 4.8, 0.0, 'S', 46, 'SE', 'WSW', 19, 19, 88, 95, 1018.3, 1018.0, 5, 4, 13.1, 11.5, 'Yes', 'Yes'), ('7/23/2011', 8.7, 15.6, 57.4, 5.6, 2.7, 'SSW', 41, 'W', 'SSW', 22, 22, 89, 67, 1020.4, 1019.1, 5, 4, 9.1, 14.5, 'Yes', 'Yes'), ('7/24/2011', 6.4, 15.4, 2.0, 2.8, 4.7, 'W', 33, 'W', 'W', 22, 13, 79, 46, 1019.9, 1017.8, 5, 4, 8.3, 13.8, 'Yes', 'No'), ('7/25/2011', 8.3, 19.1, 0.6, 1.6, 6.0, 'NW', 33, 'WNW', 'SSE', 13, 4, 73, 53, 1017.9, 1014.8, 5, 4, 10.9, 16.7, 'No', 'No'), ('7/26/2011', 7.0, 18.4, 0.6, 0.4, 8.3, 'WSW', 35, 'WNW', 'SW', 19, 15, 74, 32, 1020.0, 1018.6, 5, 4, 10.1, 18.0, 'No', 'No'), ('7/27/2011', 8.1, 17.3, 0.2, 3.0, 8.7, 'S', 39, 'WNW', 'S', 19, 20, 70, 59, 1027.1, 1026.8, 5, 4, 10.4, 16.3, 'No', 'No'), ('7/28/2011', 7.1, 20.4, 0.0, 1.8, 10.2, 'W', 28, 'W', 'N', 22, 15, 83, 41, 1029.3, 1025.6, 5, 4, 9.4, 19.6, 'No', 'No'), ('7/29/2011', 7.3, 20.0, 0.0, 3.6, 10.4, 'WNW', 22, 'WNW', 'ENE', 17, 11, 75, 32, 1027.0, 1023.6, 5, 4, 9.6, 19.0, 'No', 'No'), ('7/30/2011', 7.1, 20.2, 0.0, 2.8, 9.7, 'NNE', 24, 'W', 'SE', 17, 6, 78, 43, 1024.6, 1020.5, 5, 4, 8.7, 18.8, 'No', 'No'), ('7/31/2011', 7.4, 21.4, 0.0, 3.4, 8.7, 'W', 28, 'WNW', 'S', 15, 2, 65, 31, 1022.3, 1019.4, 5, 4, 10.5, 21.1, 'No', 'No'), ('8/1/2011', 9.7, 22.7, 0.0, 2.4, 9.6, 'NNE', 26, 'W', 'E', 15, 15, 73, 53, 1022.7, 1019.4, 5, 4, 12.5, 19.3, 'No', 'No'), ('8/2/2011', 9.9, 22.1, 0.0, 3.8, 9.8, 'W', 24, 'WNW', 'NE', 19, 4, 72, 37, 1023.1, 1020.9, 5, 4, 12.5, 21.7, 'No', 'No'), ('8/3/2011', 12.5, 25.7, 0.0, 2.8, 5.2, 'W', 26, 'W', 'ENE', 13, 15, 72, 41, 1023.2, 1021.6, 5, 4, 13.9, 23.0, 'No', 'No'), ('8/4/2011', 12.0, 23.5, 0.0, 4.8, 10.2, 'W', 41, 'WNW', 'NE', 15, 17, 73, 50, 1026.5, 1024.0, 5, 4, 14.0, 23.0, 'No', 'No'), ('8/5/2011', 11.3, 25.2, 0.0, 5.4, 10.1, 'NNW', 33, 'W', 'NNW', 6, 20, 66, 30, 1025.4, 1021.8, 5, 4, 13.9, 24.7, 'No', 'No'), ('8/6/2011', 12.7, 24.0, 0.0, 5.8, 7.7, 'WSW', 37, 'W', 'NNE', 0, 11, 57, 44, 1021.2, 1016.7, 5, 4, 15.5, 21.7, 'No', 'No'), ('8/7/2011', 13.7, 19.5, 0.6, 5.0, 4.3, 'NW', 35, 'NNW', 'N', 9, 17, 84, 77, 1017.1, 1012.6, 5, 4, 14.2, 16.7, 'No', 'Yes'), ('8/8/2011', 9.4, 18.3, 4.4, 2.0, 9.1, 'W', 33, 'W', 'W', 17, 13, 66, 43, 1010.9, 1007.8, 5, 4, 11.1, 15.9, 'Yes', 'No'), ('8/9/2011', 7.8, 17.1, 0.0, 3.8, 2.8, 'WSW', 33, 'W', 'W', 19, 15, 69, 37, 1008.2, 1005.6, 5, 4, 9.7, 16.1, 'No', 'No'), ('8/10/2011', 7.8, 18.5, 0.0, 0.8, 9.8, 'WSW', 39, 'WNW', 'WNW', 9, 15, 58, 39, 1007.2, 1004.5, 5, 4, 10.7, 16.5, 'No', 'No'), ('8/11/2011', 7.3, 18.5, 0.0, 4.8, 6.7, 'W', 33, 'W', 'S', 15, 13, 58, 47, 1008.5, 1008.2, 5, 4, 11.5, 16.9, 'No', 'Yes'), ('8/12/2011', 10.3, 17.3, 13.0, 6.2, 2.7, 'SSW', 41, 'SW', 'SSW', 22, 15, 74, 83, 1018.0, 1018.7, 5, 4, 14.8, 14.2, 'Yes', 'Yes'), ('8/13/2011', 8.3, 18.9, 2.6, 1.2, 7.8, 'W', 28, 'W', 'E', 20, 17, 78, 51, 1024.5, 1022.2, 5, 4, 10.4, 17.2, 'Yes', 'No'), ('8/14/2011', 10.3, 16.5, 1.0, 2.2, 0.8, 'S', 24, 'W', 'E', 7, 11, 89, 71, 1025.8, 1023.9, 5, 4, 13.7, 15.7, 'No', 'No'), ('8/15/2011', 9.4, 17.8, 0.6, 1.6, 5.1, 'W', 26, 'WNW', 'ESE', 17, 15, 78, 58, 1026.4, 1022.8, 5, 4, 11.6, 17.2, 'No', 'No'), ('8/16/2011', 10.6, 17.9, 0.0, 2.4, 8.2, 'ESE', 24, 'W', 'ENE', 13, 11, 85, 62, 1021.9, 1018.7, 5, 4, 12.8, 17.5, 'No', 'No'), ('8/17/2011', 10.2, 16.9, 0.0, 2.0, 1.1, 'NNE', 52, 'W', 'N', 17, 17, 91, 80, 1018.4, 1014.1, 5, 4, 12.4, 15.2, 'No', 'Yes'), ('8/18/2011', 10.9, 18.9, 5.6, 2.2, 9.7, 'NNW', 50, 'NW', 'W', 28, 30, 69, 27, 1008.4, 1008.7, 5, 4, 12.9, 17.9, 'Yes', 'No'), ('8/19/2011', 8.6, 17.4, 0.8, 4.2, 0.7, 'SE', 78, 'W', 'SSE', 28, 39, 85, 74, 1014.2, 1015.8, 5, 4, 9.1, 16.2, 'No', 'Yes'), ('8/20/2011', 8.9, 19.5, 20.2, 3.8, 9.7, 'SSE', 56, 'SSE', 'SE', 24, 26, 57, 47, 1028.8, 1028.6, 5, 4, 16.3, 18.7, 'Yes', 'Yes'), ('8/21/2011', 12.3, 18.5, 2.2, 6.0, 5.8, 'ESE', 46, 'SE', 'SSE', 26, 28, 56, 56, 1034.8, 1034.6, 5, 4, 16.2, 17.6, 'Yes', 'No'), ('8/22/2011', 12.7, 18.2, 0.0, 4.2, 6.9, 'ESE', 44, 'SE', 'SE', 20, 19, 56, 49, 1038.0, 1036.7, 5, 4, 15.7, 17.5, 'No', 'No'), ('8/23/2011', 12.2, 17.5, 0.0, 2.8, 3.0, 'W', 41, 'W', 'ENE', 17, 11, 86, 69, 1036.1, 1031.8, 5, 4, 13.6, 16.6, 'No', 'No'), ('8/24/2011', 10.4, 18.9, 1.0, 1.4, 10.3, 'ENE', 28, 'WNW', 'ENE', 17, 17, 82, 51, 1030.4, 1026.6, 5, 4, 13.7, 18.4, 'No', 'No'), ('8/25/2011', 10.4, 19.9, 0.2, 4.0, 10.6, 'E', 30, 'W', 'NE', 9, 17, 79, 64, 1025.4, 1020.6, 5, 4, 13.0, 19.0, 'No', 'No'), ('8/26/2011', 10.8, 20.4, 0.0, 4.0, 10.4, 'SSE', 30, 'SSE', 'E', 19, 15, 75, 60, 1025.4, 1022.9, 5, 4, 17.2, 19.1, 'No', 'No'), ('8/27/2011', 12.4, 19.0, 0.0, 3.4, 4.0, 'SSE', 28, 'W', 'E', 11, 6, 96, 75, 1021.8, 1017.7, 5, 4, 13.3, 18.1, 'No', 'No'), ('8/28/2011', 11.3, 21.6, 0.0, 0.8, 8.2, 'SSW', 35, 'W', 'ENE', 20, 17, 76, 63, 1021.3, 1017.0, 5, 4, 13.6, 18.7, 'No', 'No'), ('8/29/2011', 11.2, 24.0, 0.0, 3.6, 10.4, 'WSW', 31, 'NW', 'S', 4, 6, 57, 28, 1017.2, 1015.1, 5, 4, 16.3, 23.3, 'No', 'No'), ('8/30/2011', 13.6, 18.7, 0.0, 3.6, 8.4, 'SSE', 31, 'S', 'ESE', 15, 17, 68, 62, 1022.8, 1021.1, 5, 4, 16.8, 16.6, 'No', 'No'), ('8/31/2011', 11.4, 19.7, 0.0, 2.4, 9.7, 'ESE', 24, 'WNW', 'E', 15, 17, 78, 60, 1023.7, 1021.3, 5, 4, 15.2, 18.4, 'No', 'No'), ('9/1/2011', 13.4, 19.5, 0.0, 1.0, 7.9, 'ESE', 30, 'WNW', 'ESE', 6, 19, 84, 57, 1024.2, 1022.4, 5, 4, 15.3, 19.3, 'No', 'No'), ('9/2/2011', 14.2, 17.9, 0.0, 4.0, 4.2, 'S', 37, 'SSW', 'S', 17, 19, 64, 51, 1029.5, 1028.6, 5, 4, 14.9, 16.5, 'No', 'No'), ('9/3/2011', 10.1, 19.1, 0.0, 1.0, 9.7, 'ENE', 37, 'W', 'NE', 15, 26, 70, 54, 1030.9, 1027.0, 5, 4, 13.8, 18.6, 'No', 'No'), ('9/4/2011', 10.6, 20.0, 0.0, 3.4, 10.5, 'NNE', 39, 'N', 'NE', 13, 20, 56, 57, 1027.9, 1024.0, 5, 4, 17.2, 19.4, 'No', 'No'), ('9/5/2011', 14.2, 22.5, 0.0, 5.6, 6.1, 'NNE', 37, 'SE', 'NE', 4, 13, 56, 62, 1026.2, 1023.2, 5, 4, 18.0, 20.1, 'No', 'No'), ('9/6/2011', 14.7, 26.8, 0.0, 3.2, 10.3, 'W', 56, 'N', 'NNE', 20, 15, 44, 28, 1019.6, 1014.3, 5, 4, 20.5, 26.6, 'No', 'Yes'), ('9/7/2011', 11.6, 20.1, 2.4, 8.4, 10.4, 'W', 43, 'W', 'ESE', 28, 19, 36, 39, 1019.2, 1017.5, 5, 4, 14.9, 17.1, 'Yes', 'No'), ('9/8/2011', 12.6, 18.3, 0.0, 5.8, 0.9, 'E', 24, 'S', 'E', 2, 17, 67, 60, 1020.9, 1017.6, 5, 4, 15.6, 17.1, 'No', 'Yes'), ('9/9/2011', 12.2, 14.8, 4.4, 1.6, 1.1, 'WSW', 46, 'W', 'S', 15, 13, 82, 67, 1009.0, 1006.1, 5, 4, 12.2, 14.1, 'Yes', 'Yes'), ('9/10/2011', 7.4, 16.9, 1.6, 2.3, 7.8, 'W', 57, 'WSW', 'WSW', 31, 31, 39, 31, 1010.3, 1008.2, 5, 4, 11.5, 15.3, 'Yes', 'No'), ('9/11/2011', 10.2, 20.4, 0.2, 4.4, 10.2, 'SW', 50, 'WSW', 'SW', 28, 19, 47, 32, 1013.0, 1011.0, 5, 4, 14.5, 17.9, 'No', 'No'), ('9/12/2011', 9.0, 19.8, 0.0, 6.0, 10.8, 'SW', 46, 'W', 'ESE', 19, 19, 48, 43, 1023.0, 1022.6, 5, 4, 14.0, 17.1, 'No', 'No'), ('9/13/2011', 8.2, 22.6, 0.0, 4.0, 10.9, 'NW', 35, 'WNW', 'E', 11, 19, 57, 50, 1025.6, 1019.9, 5, 4, 13.5, 19.1, 'No', 'No'), ('9/14/2011', 11.1, 26.7, 0.0, 5.2, 10.9, 'S', 59, 'SE', 'WNW', 6, 24, 37, 14, 1022.3, 1017.0, 5, 4, 19.0, 26.0, 'No', 'No'), ('9/15/2011', 15.2, 19.3, 0.0, 6.8, 9.1, 'SSE', 37, 'SSE', 'E', 19, 20, 75, 62, 1022.5, 1018.1, 5, 4, 16.2, 18.1, 'No', 'No'), ('9/16/2011', 11.4, 21.4, 0.0, 4.8, 7.6, 'W', 41, 'WNW', 'ENE', 13, 17, 49, 49, 1018.3, 1012.5, 5, 4, 17.8, 20.1, 'No', 'No'), ('9/17/2011', 14.3, 25.4, 0.0, 5.8, 9.6, 'SSW', 31, 'SSE', 'E', 9, 19, 66, 71, 1017.3, 1013.2, 5, 4, 20.5, 19.9, 'No', 'No'), ('9/18/2011', 15.7, 30.6, 0.0, 6.8, 10.5, 'S', 59, 'ESE', 'SSE', 6, 31, 27, 59, 1013.3, 1015.9, 5, 4, 25.4, 21.9, 'No', 'No'), ('9/19/2011', 14.6, 26.0, 0.0, 3.8, 9.8, 'NNE', 56, 'ENE', 'NE', 11, 26, 59, 67, 1020.6, 1013.7, 5, 4, 19.9, 20.9, 'No', 'No'), ('9/20/2011', 17.5, 28.1, 0.0, 8.0, 10.0, 'W', 78, 'N', 'WNW', 22, 43, 31, 20, 1004.7, 1006.5, 5, 4, 25.6, 23.0, 'No', 'No'), ('9/21/2011', 11.9, 22.7, 0.0, 9.0, 11.0, 'W', 41, 'WSW', 'E', 17, 17, 36, 42, 1020.1, 1017.5, 5, 4, 18.0, 19.3, 'No', 'No'), ('9/22/2011', 11.2, 22.8, 0.0, 5.2, 10.9, 'NNE', 44, 'WNW', 'ENE', 11, 20, 53, 57, 1024.0, 1019.0, 5, 4, 17.6, 20.4, 'No', 'No'), ('9/23/2011', 12.7, 32.5, 0.0, 5.6, 9.5, 'SSE', 70, 'W', 'W', 15, 17, 44, 14, 1015.9, 1012.8, 5, 4, 22.8, 30.4, 'No', 'No'), ('9/24/2011', 14.3, 17.7, 0.2, 8.2, 0.4, 'SSE', 39, 'ESE', 'ESE', 15, 19, 65, 76, 1021.4, 1017.8, 5, 4, 16.5, 16.3, 'No', 'Yes'), ('9/25/2011', 13.1, 17.3, 23.8, 6.8, 0.0, 'ESE', 61, 'SE', 'ESE', 31, 20, 90, 92, 1018.6, 1020.3, 5, 4, 14.2, 13.2, 'Yes', 'Yes'), ('9/26/2011', 12.3, 19.7, 30.0, 4.0, 7.2, 'ESE', 44, 'SE', 'ESE', 24, 17, 52, 45, 1024.8, 1022.1, 5, 4, 17.0, 19.3, 'Yes', 'No'), ('9/27/2011', 10.7, 20.8, 0.4, 5.0, 9.3, 'ENE', 41, 'W', 'NE', 9, 22, 63, 53, 1023.1, 1018.9, 5, 4, 17.3, 18.5, 'No', 'No'), ('9/28/2011', 13.4, 18.0, 0.0, 7.2, 0.2, 'NNE', 31, 'N', 'ENE', 9, 11, 59, 84, 1015.7, 1010.6, 5, 4, 17.3, 15.8, 'No', 'Yes'), ('9/29/2011', 15.5, 22.0, 7.8, 1.4, 5.1, 'W', 72, 'NNW', 'WNW', 19, 31, 74, 38, 997.8, 996.3, 5, 4, 17.5, 16.9, 'Yes', 'No'), ('9/30/2011', 12.2, 20.8, 0.8, 7.0, 8.0, 'W', 63, 'WNW', 'W', 28, 33, 43, 27, 1003.8, 1002.8, 5, 4, 15.8, 20.2, 'No', 'No'), ('10/1/2011', 10.8, 20.0, 0.2, 6.6, 5.2, 'SSW', 48, 'SSW', 'SE', 2, 17, 49, 46, 1006.5, 1005.0, 5, 4, 15.8, 18.3, 'No', 'Yes'), ('10/2/2011', 11.4, 17.1, 9.8, 6.4, 0.2, 'SSE', 67, 'SSW', 'SSE', 30, 31, 88, 63, 1012.8, 1016.7, 5, 4, 13.1, 15.2, 'Yes', 'Yes'), ('10/3/2011', 10.3, 18.4, 4.6, 4.2, 7.2, 'S', 50, 'WSW', 'S', 17, 28, 76, 50, 1023.0, 1021.3, 5, 4, 13.3, 17.5, 'Yes', 'No'), ('10/4/2011', 10.7, 19.9, 0.2, 6.0, 5.9, 'SSE', 35, 'W', 'SSE', 19, 20, 73, 47, 1024.6, 1022.9, 5, 4, 13.3, 19.4, 'No', 'No'), ('10/5/2011', 10.0, 20.1, 0.2, 4.0, 2.9, 'WNW', 24, 'W', 'E', 20, 15, 76, 47, 1022.6, 1018.2, 5, 4, 13.5, 17.8, 'No', 'No'), ('10/6/2011', 13.3, 19.0, 0.0, 3.0, 0.9, 'NNE', 22, 'W', 'NE', 7, 15, 67, 62, 1016.5, 1013.5, 5, 4, 15.4, 17.9, 'No', 'Yes'), ('10/7/2011', 14.4, 21.0, 2.2, 2.2, 6.3, 'E', 24, 'WNW', 'E', 9, 19, 88, 64, 1013.6, 1010.2, 5, 4, 15.7, 20.0, 'Yes', 'Yes'), ('10/8/2011', 15.4, 21.6, 2.0, 4.0, 5.0, 'ESE', 31, 'WNW', 'SSE', 9, 20, 93, 74, 1011.3, 1009.4, 5, 4, 16.1, 19.0, 'Yes', 'No'), ('10/9/2011', 13.2, 23.6, 1.0, 4.0, 6.0, 'WSW', 54, 'W', 'SW', 11, 20, 89, 31, 1008.1, 1004.9, 5, 4, 15.7, 21.3, 'No', 'No'), ('10/10/2011', 12.0, 22.0, 0.2, 4.4, 6.9, 'E', 30, 'WNW', 'E', 13, 22, 77, 62, 1010.0, 1006.5, 5, 4, 14.4, 18.2, 'No', 'No'), ('10/11/2011', 12.2, 21.1, 0.0, 5.4, 10.3, 'WSW', 56, 'WSW', 'ESE', 28, 19, 39, 36, 1011.1, 1009.5, 5, 4, 15.6, 19.6, 'No', 'No'), ('10/12/2011', 10.9, 21.1, 0.0, 5.4, 7.2, 'ESE', 41, 'W', 'ESE', 17, 22, 49, 65, 1017.4, 1017.0, 5, 4, 15.6, 17.5, 'No', 'No'), ('10/13/2011', 14.9, 20.1, 0.2, 4.4, 3.1, 'E', 33, 'W', 'E', 2, 24, 70, 51, 1023.2, 1021.3, 5, 4, 16.8, 19.7, 'No', 'No'), ('10/14/2011', 16.6, 19.4, 0.0, 4.6, 0.0, 'ENE', 35, 'ENE', 'ENE', 20, 22, 65, 70, 1020.8, 1017.4, 5, 4, 17.4, 17.8, 'No', 'Yes'), ('10/15/2011', 17.1, 24.6, 7.2, 4.2, 7.6, 'ENE', 39, 'NE', 'ENE', 2, 15, 84, 68, 1010.7, 1007.5, 5, 4, 19.2, 21.7, 'Yes', 'No'), ('10/16/2011', 17.1, 23.3, 0.2, 3.4, 11.6, 'SSW', 37, 'S', 'SE', 15, 24, 62, 51, 1014.1, 1014.8, 5, 4, 20.4, 21.9, 'No', 'Yes'), ('10/17/2011', 13.2, 20.5, 3.2, 7.0, 8.9, 'S', 43, 'SSE', 'SE', 24, 20, 52, 38, 1031.2, 1031.8, 5, 4, 16.2, 19.6, 'Yes', 'No'), ('10/18/2011', 13.0, 19.9, 0.2, 8.0, 8.2, 'E', 28, 'SW', 'E', 4, 17, 57, 42, 1034.8, 1031.6, 5, 4, 17.7, 19.2, 'No', 'No'), ('10/19/2011', 12.3, 21.4, 0.0, 4.0, 12.0, 'NE', 35, 'W', 'ENE', 13, 24, 67, 55, 1031.4, 1027.8, 5, 4, 16.9, 20.9, 'No', 'No'), ('10/20/2011', 13.5, 23.5, 0.0, 8.0, 12.4, 'NNE', 48, 'W', 'ENE', 6, 22, 100, 50, 1028.0, 1023.5, 5, 4, 18.0, 23.0, 'No', 'No'), ('10/21/2011', 15.9, 30.1, 0.2, 7.6, 12.2, 'SSW', 33, 'WNW', 'ENE', 11, 9, 59, 39, 1023.8, 1021.4, 5, 4, 20.5, 26.3, 'No', 'No'), ('10/22/2011', 17.6, 24.6, 0.0, 8.8, 8.2, 'SSW', 31, 'N', 'E', 2, 19, 76, 64, 1024.7, 1021.5, 5, 4, 19.6, 23.1, 'No', 'No'), ('10/23/2011', 19.0, 24.8, 0.0, 4.8, 9.5, 'ENE', 30, 'SSW', 'ENE', 2, 19, 80, 71, 1022.2, 1017.9, 5, 4, 20.5, 22.4, 'No', 'No'), ('10/24/2011', 18.0, 34.3, 0.0, 4.8, 12.1, 'NW', 44, 'ESE', 'NNW', 7, 28, 53, 21, 1013.7, 1007.7, 5, 4, 24.8, 33.8, 'No', 'No'), ('10/25/2011', 18.7, 19.5, 0.8, 11.8, 0.3, 'SSE', 59, 'SSE', 'SSE', 26, 33, 81, 86, 1010.6, 1013.6, 5, 4, 19.4, 16.9, 'No', 'Yes'), ('10/26/2011', 14.2, 18.6, 2.8, 4.0, 0.0, 'SSE', 41, 'SSE', 'SE', 11, 20, 78, 52, 1022.7, 1022.3, 5, 4, 14.9, 17.2, 'Yes', 'Yes'), ('10/27/2011', 13.9, 19.6, 2.2, 3.2, 4.3, 'ESE', 39, 'ESE', 'E', 19, 19, 59, 50, 1024.0, 1021.9, 5, 4, 18.4, 19.3, 'Yes', 'No'), ('10/28/2011', 16.8, 21.7, 0.0, 4.6, 8.3, 'ENE', 43, 'NE', 'ENE', 11, 30, 67, 58, 1019.8, 1015.5, 5, 4, 19.0, 21.2, 'No', 'No'), ('10/29/2011', 17.6, 28.2, 0.0, 6.2, 5.1, 'NNE', 35, 'SE', 'ESE', 4, 11, 70, 69, 1011.1, 1008.9, 5, 4, 21.7, 24.1, 'No', 'No'), ('10/30/2011', 18.1, 25.8, 0.0, 5.6, 8.1, 'S', 59, 'S', 'E', 6, 22, 75, 99, 1012.1, 1009.5, 5, 4, 21.6, 21.6, 'No', 'No'), ('10/31/2011', 14.4, 22.7, 0.0, 6.2, 12.0, 'SSE', 48, 'SW', 'SE', 19, 26, 100, 45, 1020.8, 1019.7, 5, 4, 18.6, 20.2, 'No', 'No'), ('11/1/2011', 15.1, 20.7, 0.4, 5.4, 6.7, 'S', 28, 'SSE', 'ESE', 15, 17, 73, 55, 1020.1, 1016.0, 5, 4, 16.2, 19.8, 'No', 'No'), ('11/2/2011', 14.3, 24.0, 0.0, 5.8, 11.4, 'S', 43, 'WNW', 'SE', 15, 26, 64, 46, 1011.3, 1009.4, 5, 4, 19.3, 22.7, 'No', 'Yes'), ('11/3/2011', 13.8, 18.4, 11.4, 4.6, 3.4, 'SE', 39, 'E', 'ESE', 19, 11, 88, 50, 1013.0, 1013.8, 5, 4, 14.5, 18.0, 'Yes', 'Yes'), ('11/4/2011', 13.9, 21.5, 3.8, 2.6, 9.3, 'ESE', 30, 'WNW', 'ESE', 7, 17, 60, 55, 1019.3, 1018.1, 5, 4, 18.0, 20.4, 'Yes', 'No'), ('11/5/2011', 15.3, 24.1, 0.2, 6.4, 12.6, 'ENE', 43, 'NNW', 'NE', 11, 26, 62, 67, 1019.6, 1015.0, 5, 4, 20.3, 21.5, 'No', 'No'), ('11/6/2011', 17.7, 28.9, 0.0, 7.2, 8.3, 'NE', 31, 'ESE', 'NNE', 6, 17, 56, 58, 1013.1, 1009.2, 5, 4, 23.9, 25.8, 'No', 'No'), ('11/7/2011', 21.2, 29.5, 0.0, 8.2, 7.0, 'E', 28, 'WNW', 'E', 9, 11, 54, 57, 1013.2, 1012.2, 5, 4, 26.5, 25.6, 'No', 'No'), ('11/8/2011', 19.4, 28.9, 0.6, 5.2, 7.4, 'W', 63, 'W', 'NNE', 9, 24, 78, 63, 1014.4, 1008.8, 5, 4, 23.3, 27.0, 'No', 'Yes'), ('11/9/2011', 19.7, 29.0, 19.8, 10.8, 8.8, 'NNE', 43, 'W', 'E', 9, 13, 77, 63, 1014.4, 1011.2, 5, 4, 24.2, 27.6, 'Yes', 'No'), ('11/10/2011', 24.2, 30.4, 0.0, 10.2, 5.0, 'SSE', 52, 'WNW', 'SW', 11, 20, 61, 43, 1011.6, 1011.5, 5, 4, 24.4, 28.2, 'No', 'No'), ('11/11/2011', 18.3, 23.3, 0.4, 6.2, 11.6, 'ENE', 39, 'E', 'E', 15, 24, 46, 51, 1024.7, 1022.5, 5, 4, 21.5, 22.5, 'No', 'No'), ('11/12/2011', 19.3, 24.7, 0.0, 9.0, 8.1, 'NNE', 35, 'NNE', 'E', 20, 17, 64, 56, 1019.4, 1015.1, 5, 4, 21.2, 23.4, 'No', 'No'), ('11/15/2011', 18.8, 24.6, 0.0, 8.6, 11.7, 'NE', 46, 'E', 'E', 11, 24, 52, 50, 1019.3, 1016.6, 5, 4, 23.0, 23.3, 'No', 'No'), ('11/16/2011', 19.1, 22.1, 0.0, 10.0, 1.1, 'S', 65, 'SSW', 'SSW', 13, 22, 77, 73, 1017.0, 1018.7, 5, 4, 21.2, 20.7, 'No', 'Yes'), ('11/17/2011', 15.9, 21.4, 12.8, 2.4, 0.0, 'ESE', 22, 'E', 'ESE', 9, 11, 93, 94, 1020.5, 1018.7, 5, 4, 17.2, 17.9, 'Yes', 'Yes'), ('11/18/2011', 17.1, 23.7, 1.8, 0.4, 9.6, 'ENE', 30, 'E', 'E', 4, 22, 77, 68, 1018.6, 1016.1, 5, 4, 21.3, 22.9, 'Yes', 'No'), ('11/19/2011', 18.1, 27.5, 0.0, 6.2, 12.9, 'NNE', 48, 'E', 'NNE', 15, 17, 76, 64, 1015.3, 1010.4, 5, 4, 22.9, 26.6, 'No', 'No'), ('11/20/2011', 19.6, 28.0, 0.0, 8.8, 7.0, 'W', 74, 'ENE', 'E', 9, 9, 78, 57, 1010.2, 1007.4, 5, 4, 22.6, 26.1, 'No', 'Yes'), ('11/21/2011', 17.5, 22.3, 2.4, 4.8, 0.4, 'NE', 31, 'ENE', 'NE', 9, 17, 62, 63, 1018.4, 1015.2, 5, 4, 20.4, 21.2, 'Yes', 'Yes'), ('11/22/2011', 17.8, 21.9, 4.8, 4.4, 0.2, 'SSE', 41, 'W', 'SSE', 7, 22, 85, 75, 1011.0, 1008.8, 5, 4, 19.6, 21.8, 'Yes', 'Yes'), ('11/23/2011', 14.8, 18.3, 38.8, 7.4, 0.1, 'SE', 48, 'SSE', 'SSE', 19, 24, 93, 86, 1016.4, 1019.7, 5, 4, 15.6, 17.2, 'Yes', 'Yes'), ('11/24/2011', 15.3, 18.3, 14.8, 3.4, 0.0, 'ESE', 43, 'SE', 'ESE', 19, 24, 75, 76, 1026.6, 1025.7, 5, 4, 17.4, 17.3, 'Yes', 'Yes'), ('11/25/2011', 15.4, 20.0, 7.6, 2.4, 0.0, 'E', 52, 'E', 'ESE', 24, 15, 89, 89, 1021.8, 1020.4, 5, 4, 18.3, 18.6, 'Yes', 'Yes'), ('11/26/2011', 18.1, 26.8, 22.0, 3.2, 5.5, 'NE', 59, 'NNE', 'ENE', 28, 30, 95, 73, 1007.6, 1003.9, 5, 4, 19.9, 24.3, 'Yes', 'Yes'), ('11/27/2011', 18.6, 29.8, 6.8, 7.4, 12.5, 'WNW', 54, 'WNW', 'WSW', 26, 26, 42, 34, 1006.7, 1007.9, 5, 4, 23.4, 27.2, 'Yes', 'No'), ('11/28/2011', 17.0, 26.9, 0.0, 6.6, 12.9, 'NE', 46, 'N', 'NE', 13, 24, 55, 63, 1017.4, 1015.6, 5, 4, 23.6, 24.4, 'No', 'No'), ('11/29/2011', 19.7, 26.2, 0.0, 9.4, 8.0, 'NE', 65, 'NE', 'NE', 9, 22, 66, 76, 1017.1, 1014.2, 5, 4, 24.6, 24.6, 'No', 'No'), ('11/30/2011', 20.7, 31.6, 0.0, 7.2, 2.2, 'SW', 54, 'NNE', 'NW', 17, 22, 77, 41, 1010.5, 1009.1, 5, 4, 23.7, 30.6, 'No', 'Yes'), ('12/1/2011', 15.8, 21.9, 1.4, 9.0, 8.7, 'S', 57, 'S', 'SSE', 22, 22, 51, 41, 1020.7, 1020.6, 5, 4, 17.5, 20.9, 'Yes', 'Yes'), ('12/2/2011', 14.1, 21.1, 1.4, 8.0, 8.2, 'SSE', 52, 'SSW', 'S', 22, 30, 63, 50, 1022.2, 1020.8, 5, 4, 16.6, 20.7, 'Yes', 'No'), ('12/3/2011', 13.9, 22.2, 0.0, 6.8, 11.3, 'NNE', 39, 'W', 'E', 13, 24, 57, 45, 1020.4, 1016.9, 5, 4, 17.6, 21.2, 'No', 'No'), ('12/4/2011', 15.6, 21.1, 0.0, 7.2, 3.9, 'SSE', 63, 'SSW', 'SSE', 20, 28, 70, 72, 1014.3, 1015.0, 5, 4, 19.9, 16.3, 'No', 'Yes'), ('12/5/2011', 11.8, 19.0, 4.8, 7.6, 4.5, 'W', 41, 'S', 'SSW', 24, 17, 61, 69, 1021.1, 1019.9, 5, 4, 15.9, 16.4, 'Yes', 'Yes'), ('12/6/2011', 12.6, 19.1, 5.4, 2.8, 0.5, 'ESE', 30, 'SSW', 'SE', 15, 17, 77, 58, 1020.1, 1017.9, 5, 4, 15.3, 17.4, 'Yes', 'Yes'), ('12/7/2011', 12.1, 22.0, 2.2, 4.0, 3.2, 'ESE', 35, 'WNW', 'ESE', 11, 24, 64, 71, 1016.3, 1014.0, 5, 4, 17.7, 19.1, 'Yes', 'Yes'), ('12/8/2011', 16.2, 22.3, 23.6, 3.2, 0.2, 'SSE', 22, 'SE', 'E', 4, 11, 86, 63, 1014.2, 1013.1, 5, 4, 18.0, 21.8, 'Yes', 'No'), ('12/9/2011', 16.7, 23.9, 0.6, 3.4, 10.9, 'ENE', 28, 'W', 'E', 9, 17, 81, 57, 1014.9, 1013.3, 5, 4, 20.0, 22.9, 'No', 'No'), ('12/10/2011', 17.7, 23.5, 0.2, 5.8, 3.1, 'E', 24, 'NNE', 'E', 2, 13, 74, 65, 1011.5, 1008.0, 5, 4, 20.7, 22.4, 'No', 'No'), ('12/11/2011', 18.3, 25.6, 0.0, 3.8, 6.5, 'SSE', 37, 'ENE', 'NNE', 2, 13, 69, 89, 1003.8, 1002.1, 5, 4, 23.0, 20.5, 'No', 'Yes'), ('12/12/2011', 17.5, 19.3, 12.6, 4.8, 0.0, 'S', 46, 'SSE', 'SSE', 20, 19, 92, 77, 1006.9, 1006.3, 5, 4, 17.7, 18.8, 'Yes', 'Yes'), ('12/13/2011', 16.4, 23.4, 4.2, 2.0, 6.8, 'SSW', 48, 'SSW', 'SSE', 19, 31, 62, 49, 1007.9, 1007.9, 5, 4, 19.2, 23.2, 'Yes', 'No'), ('12/14/2011', 15.2, 22.2, 0.4, 8.0, 10.5, 'SE', 46, 'SSW', 'S', 20, 22, 60, 49, 1015.8, 1016.2, 5, 4, 19.0, 19.7, 'No', 'No'), ('12/15/2011', 15.5, 22.6, 0.2, 7.8, 12.2, 'ESE', 31, 'SSE', 'ESE', 13, 20, 59, 48, 1019.7, 1018.0, 5, 4, 19.6, 21.4, 'No', 'No'), ('12/16/2011', 14.7, 21.6, 0.0, 7.2, 6.8, 'SE', 30, 'ESE', 'SE', 15, 17, 64, 48, 1021.4, 1020.8, 5, 4, 18.9, 20.8, 'No', 'No'), ('12/17/2011', 17.0, 21.7, 0.0, 5.4, 10.7, 'ESE', 26, 'ESE', 'E', 15, 20, 50, 47, 1023.1, 1021.4, 5, 4, 20.8, 21.3, 'No', 'No'), ('12/18/2011', 15.8, 23.2, 0.0, 7.6, 3.1, 'NE', 44, 'W', 'NE', 11, 24, 67, 51, 1020.0, 1016.2, 5, 4, 18.7, 22.2, 'No', 'No'), ('12/19/2011', 18.6, 22.8, 0.0, 7.0, 1.7, 'NNE', 46, 'NNW', 'NNE', 9, 24, 77, 75, 1011.2, 1008.0, 5, 4, 20.2, 21.7, 'No', 'Yes'), ('12/20/2011', 18.4, 24.3, 14.8, 2.2, 6.6, 'SW', 37, 'SSW', 'SE', 20, 22, 79, 63, 1013.2, 1014.4, 5, 4, 19.9, 22.8, 'Yes', 'No'), ('12/21/2011', 18.7, 25.0, 0.0, 6.8, 5.5, 'ESE', 33, 'SSW', 'ESE', 9, 24, 71, 57, 1018.3, 1016.6, 5, 4, 20.6, 23.5, 'No', 'No'), ('12/22/2011', 19.2, 22.9, 0.0, 4.6, 2.1, 'ENE', 20, 'SE', 'ENE', 9, 13, 76, 77, 1018.5, 1017.0, 5, 4, 20.1, 19.7, 'No', 'Yes'), ('12/23/2011', 18.7, 25.0, 5.2, 3.0, 5.4, 'E', 31, 'ESE', 'E', 9, 20, 79, 69, 1014.9, 1012.9, 5, 4, 22.7, 24.2, 'Yes', 'No'), ('12/24/2011', 19.7, 26.2, 0.4, 2.6, 10.9, 'ENE', 33, 'E', 'E', 15, 19, 75, 62, 1013.9, 1012.5, 5, 4, 23.7, 25.1, 'No', 'No'), ('12/25/2011', 19.1, 26.6, 0.0, 7.2, 12.7, 'NE', 52, 'NE', 'NE', 15, 31, 65, 62, 1012.1, 1009.8, 5, 4, 24.0, 25.0, 'No', 'No'), ('12/26/2011', 20.0, 26.8, 0.0, 9.0, 4.7, 'S', 59, 'NNE', 'ENE', 17, 9, 61, 68, 1006.4, 1004.2, 5, 4, 24.5, 24.4, 'No', 'No'), ('12/27/2011', 19.1, 23.7, 0.4, 6.8, 4.7, 'SSE', 50, 'S', 'S', 24, 24, 69, 64, 1010.0, 1010.7, 5, 4, 20.1, 21.3, 'No', 'No'), ('12/28/2011', 18.3, 24.4, 0.0, 7.2, 12.5, 'SSE', 50, 'SSW', 'S', 20, 17, 60, 52, 1013.8, 1011.8, 5, 4, 20.8, 23.9, 'No', 'No'), ('12/29/2011', 17.5, 25.0, 0.0, 7.0, 10.8, 'SSE', 43, 'SSW', 'SSE', 15, 24, 69, 39, 1014.4, 1014.9, 5, 4, 20.7, 23.8, 'No', 'No'), ('12/30/2011', 17.1, 25.1, 0.6, 8.8, 11.7, 'ESE', 37, 'W', 'ESE', 13, 20, 74, 48, 1019.4, 1019.5, 5, 4, 19.3, 23.9, 'No', 'No'), ('12/31/2011', 16.9, 23.6, 0.0, 7.0, 5.8, 'ENE', 28, 'W', 'E', 13, 19, 69, 54, 1020.8, 1018.8, 5, 4, 20.5, 22.8, 'No', 'No'), ('1/1/2012', 16.0, 25.3, 0.0, 5.6, 13.1, 'ENE', 41, 'NNW', 'ENE', 17, 26, 56, 48, 1017.9, 1015.3, 5, 4, 22.2, 25.0, 'No', 'No'), ('1/2/2012', 18.1, 26.5, 0.0, 10.2, 13.2, 'NE', 43, 'NNE', 'ENE', 15, 24, 54, 52, 1018.4, 1016.5, 5, 4, 24.1, 25.4, 'No', 'No'), ('1/3/2012', 20.6, 26.8, 0.0, 7.2, 12.6, 'NE', 44, 'NE', 'NE', 15, 24, 58, 57, 1018.3, 1015.4, 5, 4, 24.1, 25.5, 'No', 'No'), ('1/4/2012', 20.7, 29.4, 0.0, 13.4, 8.4, 'S', 67, 'E', 'E', 15, 9, 69, 59, 1012.6, 1010.2, 5, 4, 25.0, 27.8, 'No', 'No'), ('1/5/2012', 20.0, 24.8, 0.0, 9.0, 3.9, 'SSE', 44, 'S', 'E', 11, 17, 61, 61, 1018.0, 1014.2, 5, 4, 22.3, 23.4, 'No', 'No'), ('1/6/2012', 18.5, 22.4, 0.8, 6.6, 3.4, 'SSW', 56, 'S', 'SSE', 24, 28, 75, 57, 1015.1, 1016.4, 5, 4, 19.3, 21.5, 'No', 'No'), ('1/7/2012', 15.1, 24.8, 0.0, 7.2, 12.7, 'ENE', 43, 'W', 'ENE', 11, 28, 64, 52, 1015.6, 1012.1, 5, 4, 20.0, 23.8, 'No', 'No'), ('1/8/2012', 20.0, 26.4, 0.0, 8.8, 1.0, 'NE', 43, 'W', 'NNE', 7, 20, 73, 66, 1009.3, 1003.5, 5, 4, 22.1, 25.6, 'No', 'Yes'), ('1/9/2012', 20.8, 27.5, 31.6, 3.0, 12.5, 'S', 41, 'SSW', 'ESE', 22, 24, 79, 59, 1006.8, 1005.7, 5, 4, 22.4, 25.8, 'Yes', 'No'), ('1/10/2012', 19.4, 29.8, 0.2, 9.0, 7.4, 'W', 35, 'W', 'E', 17, 30, 38, 28, 1009.7, 1006.8, 5, 4, 22.6, 29.4, 'No', 'No'), ('1/11/2012', 19.7, 27.6, 0.0, 8.6, 10.9, 'WSW', 70, 'WNW', 'W', 15, 39, 36, 18, 1004.1, 1001.5, 5, 4, 23.5, 26.9, 'No', 'No'), ('1/12/2012', 13.9, 23.2, 0.0, 13.2, 13.4, 'SW', 43, 'WSW', 'SE', 22, 24, 43, 39, 1015.7, 1015.6, 5, 4, 17.6, 21.2, 'No', 'No'), ('1/13/2012', 14.7, 25.0, 0.0, 7.8, 11.3, 'ENE', 43, 'WNW', 'E', 15, 26, 56, 52, 1017.3, 1013.5, 5, 4, 19.7, 24.1, 'No', 'No'), ('1/14/2012', 18.4, 23.4, 0.0, 9.4, 0.2, 'ESE', 39, 'SE', 'E', 11, 13, 68, 60, 1017.2, 1015.8, 5, 4, 20.5, 22.4, 'No', 'Yes'), ('1/15/2012', 17.3, 22.9, 29.0, 11.0, 1.2, 'ENE', 56, 'ESE', 'ESE', 28, 24, 95, 67, 1019.4, 1019.2, 5, 4, 17.8, 21.9, 'Yes', 'Yes'), ('1/16/2012', 17.5, 24.3, 18.6, 3.4, 9.5, 'E', 39, 'NNW', 'E', 13, 26, 84, 70, 1022.9, 1022.1, 5, 4, 20.4, 23.2, 'Yes', 'Yes'), ('1/17/2012', 18.7, 26.1, 6.0, 6.0, 12.3, 'ENE', 35, 'ENE', 'E', 20, 20, 59, 61, 1023.3, 1021.1, 5, 4, 23.9, 25.0, 'Yes', 'No'), ('1/18/2012', 20.0, 26.9, 0.0, 7.2, 9.4, 'ENE', 33, 'SSW', 'E', 2, 22, 75, 63, 1017.6, 1014.3, 5, 4, 23.1, 26.1, 'No', 'No'), ('1/20/2012', 20.7, 25.7, 0.0, 7.0, 7.2, 'E', 28, 'SSE', 'E', 19, 19, 75, 58, 1017.3, 1015.0, 5, 4, 23.1, 25.2, 'No', 'No'), ('1/21/2012', 21.8, 24.8, 0.0, 4.8, 3.0, 'SE', 31, 'E', 'NNE', 13, 2, 73, 82, 1015.4, 1015.8, 5, 4, 22.6, 22.6, 'No', 'Yes'), ('1/22/2012', 19.7, 26.6, 12.0, 4.6, 8.7, 'ESE', 44, 'ESE', 'SE', 31, 24, 65, 50, 1021.4, 1021.5, 5, 4, 22.9, 25.7, 'Yes', 'No'), ('1/23/2012', 19.6, 24.5, 0.2, 9.8, 7.0, 'W', 41, 'ESE', 'ESE', 30, 20, 60, 55, 1022.7, 1021.1, 5, 4, 22.9, 23.5, 'No', 'No'), ('1/24/2012', 20.5, 23.7, 0.0, 7.6, 0.2, 'ESE', 35, 'W', 'SSE', 6, 7, 76, 84, 1018.5, 1016.5, 5, 4, 21.7, 21.7, 'No', 'Yes'), ('1/25/2012', 20.7, 24.5, 7.2, 2.4, 0.0, 'NNE', 35, 'NNE', 'E', 7, 13, 84, 91, 1014.3, 1013.0, 5, 4, 23.7, 22.7, 'Yes', 'Yes'), ('1/26/2012', 20.8, 26.9, 29.6, 7.8, 3.3, 'E', 26, 'SSE', 'E', 13, 15, 90, 68, 1014.0, 1013.4, 5, 4, 22.5, 26.4, 'Yes', 'Yes'), ('1/27/2012', 21.8, 25.3, 2.0, 2.8, 2.5, 'ESE', 46, 'ESE', 'ESE', 30, 28, 80, 70, 1017.5, 1016.8, 5, 4, 23.5, 24.1, 'Yes', 'No'), ('1/28/2012', 21.6, 26.6, 0.2, 6.2, 3.5, 'ENE', 31, 'ESE', 'E', 19, 19, 68, 81, 1015.9, 1013.2, 5, 4, 23.5, 23.7, 'No', 'No'), ('1/29/2012', 22.0, 27.3, 0.0, 6.6, 6.4, 'NE', 50, 'NNE', 'NE', 20, 28, 74, 62, 1011.5, 1008.8, 5, 4, 23.8, 26.1, 'No', 'Yes'), ('1/30/2012', 21.7, 33.2, 1.4, 8.8, 9.4, 'NNE', 56, 'NE', 'NNW', 17, 24, 69, 52, 1002.2, 998.7, 5, 4, 26.5, 31.2, 'Yes', 'No'), ('1/31/2012', 25.3, 28.8, 0.0, 11.2, 2.4, 'SSE', 44, 'SW', 'SE', 19, 28, 50, 68, 1005.2, 1008.0, 5, 4, 27.2, 24.4, 'No', 'Yes'), ('2/1/2012', 18.4, 21.9, 8.8, 5.6, 0.0, 'SE', 48, 'SE', 'ESE', 26, 28, 87, 66, 1014.4, 1013.7, 5, 4, 18.8, 21.2, 'Yes', 'Yes'), ('2/2/2012', 18.5, 20.2, 5.4, 2.8, 0.0, 'ESE', 39, 'SE', 'SE', 17, 17, 72, 82, 1012.0, 1010.5, 5, 4, 20.1, 18.5, 'Yes', 'Yes'), ('2/3/2012', 16.7, 21.0, 49.8, 1.4, 0.0, 'SSW', 35, 'W', 'WSW', 15, 9, 95, 83, 1006.8, 1004.6, 5, 4, 17.1, 20.7, 'Yes', 'Yes'), ('2/4/2012', 17.0, 25.9, 6.0, 0.2, 10.7, 'ESE', 24, 'WNW', 'ESE', 13, 17, 92, 61, 1005.1, 1003.6, 5, 4, 19.9, 25.6, 'Yes', 'No'), ('2/5/2012', 18.2, 26.8, 0.2, 6.6, 13.0, 'NE', 41, 'W', 'E', 11, 28, 84, 70, 1003.9, 1000.5, 5, 4, 22.2, 25.3, 'No', 'No'), ('2/6/2012', 20.4, 24.8, 0.0, 8.8, 7.5, 'S', 59, 'S', 'SSW', 24, 37, 76, 63, 1002.4, 1002.9, 5, 4, 22.3, 23.8, 'No', 'Yes'), ('2/7/2012', 19.4, 24.0, 2.2, 5.6, 0.6, 'ESE', 39, 'SSW', 'ESE', 13, 28, 91, 63, 1007.5, 1007.2, 5, 4, 19.6, 23.2, 'Yes', 'Yes'), ('2/8/2012', 19.2, 24.5, 1.4, 4.0, 0.4, 'ESE', 30, 'SE', 'ESE', 17, 19, 68, 66, 1011.2, 1011.5, 5, 4, 22.3, 23.2, 'Yes', 'No'), ('2/9/2012', 18.9, 25.8, 0.2, 2.8, 8.0, 'ENE', 43, 'E', 'E', 17, 26, 71, 60, 1013.7, 1012.2, 5, 4, 22.2, 24.6, 'No', 'Yes'), ('2/10/2012', 19.9, 25.7, 3.8, 5.8, 4.4, 'NE', 46, 'N', 'NE', 17, 24, 74, 63, 1012.3, 1009.9, 5, 4, 22.3, 24.3, 'Yes', 'Yes'), ('2/11/2012', 19.6, 25.3, 2.2, 6.8, 7.9, 'SSW', 46, 'WNW', 'W', 7, 11, 87, 81, 1011.4, 1010.7, 5, 4, 20.4, 18.1, 'Yes', 'Yes'), ('2/12/2012', 16.6, 25.8, 3.2, 4.8, 8.7, 'E', 31, 'WNW', 'E', 15, 19, 80, 60, 1015.3, 1013.4, 5, 4, 19.7, 25.0, 'Yes', 'Yes'), ('2/13/2012', 18.6, 25.4, 1.8, 4.8, 9.1, 'ENE', 31, 'W', 'ESE', 9, 20, 87, 66, 1018.2, 1016.7, 5, 4, 19.9, 23.8, 'Yes', 'No'), ('2/14/2012', 19.2, 24.8, 0.0, 4.0, 7.2, 'ESE', 31, 'S', 'ESE', 6, 19, 83, 59, 1021.2, 1020.3, 5, 4, 20.8, 23.3, 'No', 'No'), ('2/15/2012', 19.1, 25.3, 0.6, 5.0, 10.8, 'E', 28, 'E', 'ENE', 15, 19, 56, 52, 1021.8, 1019.9, 5, 4, 22.7, 25.0, 'No', 'No'), ('2/16/2012', 18.5, 26.7, 0.0, 7.4, 11.3, 'NE', 41, 'N', 'NE', 13, 26, 68, 47, 1020.0, 1017.9, 5, 4, 22.8, 26.0, 'No', 'No'), ('2/17/2012', 19.0, 27.4, 0.0, 8.6, 7.6, 'ENE', 39, 'ENE', 'ENE', 7, 22, 62, 67, 1017.4, 1015.7, 5, 4, 23.8, 24.0, 'No', 'No'), ('2/18/2012', 19.4, 27.5, 0.6, 6.4, 8.5, 'ESE', 31, 'SSW', 'SSE', 13, 22, 73, 60, 1017.2, 1016.6, 5, 4, 23.0, 26.8, 'No', 'No'), ('2/19/2012', 19.9, 27.1, 0.0, 6.6, 9.6, 'NNE', 39, 'WNW', 'E', 6, 24, 75, 66, 1017.9, 1014.1, 5, 4, 23.0, 25.6, 'No', 'Yes'), ('2/20/2012', 19.5, 28.2, 15.6, 12.6, 8.6, 'SSE', 33, 'W', 'SE', 9, 19, 81, 60, 1011.8, 1010.6, 5, 4, 22.8, 27.2, 'Yes', 'Yes'), ('2/21/2012', 19.6, 25.7, 6.2, 4.2, 9.8, 'SSE', 57, 'SSW', 'S', 20, 35, 82, 60, 1010.3, 1010.9, 5, 4, 20.9, 24.9, 'Yes', 'No'), ('2/22/2012', 17.3, 26.5, 0.2, 7.0, 10.7, 'SE', 33, 'WSW', 'SE', 13, 22, 69, 55, 1016.1, 1015.4, 5, 4, 20.1, 25.8, 'No', 'No'), ('2/23/2012', 18.2, 26.9, 0.0, 5.6, 12.2, 'ENE', 31, 'W', 'ENE', 11, 22, 77, 59, 1019.8, 1018.3, 5, 4, 21.5, 25.6, 'No', 'No'), ('2/24/2012', 20.6, 27.5, 0.0, 7.6, 12.0, 'ENE', 33, 'WNW', 'E', 11, 22, 78, 61, 1022.6, 1022.4, 5, 4, 22.7, 26.9, 'No', 'No'), ('2/25/2012', 18.9, 26.6, 0.0, 8.0, 11.3, 'ENE', 43, 'ESE', 'ENE', 2, 28, 71, 60, 1023.6, 1021.4, 5, 4, 23.3, 25.5, 'No', 'No'), ('2/26/2012', 21.9, 26.8, 0.0, 7.6, 0.9, 'NNE', 44, 'NE', 'NE', 11, 19, 80, 66, 1020.8, 1018.4, 5, 4, 22.8, 25.6, 'No', 'No'), ('2/27/2012', 21.9, 28.0, 0.0, 5.0, 6.1, 'ENE', 37, 'NE', 'ENE', 6, 22, 73, 55, 1017.4, 1014.8, 5, 4, 23.6, 27.5, 'No', 'No'), ('2/28/2012', 23.5, 33.4, 0.0, 7.4, 4.3, 'WNW', 31, 'E', 'ESE', 6, 20, 66, 44, 1013.3, 1011.0, 5, 4, 26.2, 31.9, 'No', 'Yes'), ('2/29/2012', 20.2, 22.0, 2.8, 4.8, 0.0, 'SE', 52, 'SSW', 'SSW', 20, 15, 89, 92, 1013.9, 1012.5, 5, 4, 20.5, 21.1, 'Yes', 'Yes'), ('3/1/2012', 20.1, 29.5, 27.6, 1.6, 2.1, 'SSW', 67, 'NNW', 'ENE', 17, 17, 90, 58, 1007.7, 1001.4, 5, 4, 21.3, 29.2, 'Yes', 'Yes'), ('3/2/2012', 18.6, 20.9, 16.0, 4.6, 0.0, 'SSW', 65, 'SSE', 'SE', 17, 20, 88, 83, 1013.4, 1015.4, 5, 4, 19.5, 19.4, 'Yes', 'Yes'), ('3/3/2012', 18.0, 22.6, 16.8, 2.8, 0.0, 'ENE', 48, 'E', 'NNE', 26, 17, 66, 81, 1019.6, 1018.5, 5, 4, 20.9, 19.9, 'Yes', 'Yes'), ('3/4/2012', 18.9, 27.3, 2.2, 2.0, 7.0, 'NE', 41, 'N', 'NE', 11, 24, 75, 65, 1014.3, 1009.8, 5, 4, 22.4, 26.4, 'Yes', 'Yes'), ('3/5/2012', 20.0, 27.4, 14.8, 5.8, 11.0, 'SSE', 39, 'SW', 'SE', 17, 26, 59, 58, 1013.4, 1014.0, 5, 4, 22.7, 25.9, 'Yes', 'No'), ('3/6/2012', 19.5, 24.7, 0.0, 8.4, 9.4, 'SSE', 44, 'S', 'SSE', 17, 28, 66, 53, 1018.8, 1018.0, 5, 4, 21.4, 23.9, 'No', 'No'), ('3/7/2012', 17.1, 23.3, 0.0, 6.6, 7.8, 'SSW', 54, 'SSW', 'S', 33, 22, 62, 60, 1018.1, 1015.7, 5, 4, 19.0, 21.3, 'No', 'Yes'), ('3/8/2012', 15.0, 21.2, 109.4, 4.8, 2.3, 'NW', 54, 'W', 'WSW', 30, 15, 96, 71, 1005.4, 1005.9, 5, 4, 15.6, 20.1, 'Yes', 'Yes'), ('3/9/2012', 14.9, 28.4, 18.0, 1.2, 10.7, 'WSW', 48, 'W', 'W', 13, 24, 75, 39, 1008.8, 1007.9, 5, 4, 18.5, 27.0, 'Yes', 'No'), ('3/10/2012', 17.0, 26.5, 0.0, 5.0, 10.8, 'ESE', 43, 'W', 'SE', 11, 26, 82, 61, 1013.5, 1014.4, 5, 4, 20.1, 24.7, 'No', 'No'), ('3/11/2012', 17.5, 24.0, 0.0, 6.4, 10.9, 'ENE', 30, 'W', 'E', 13, 20, 71, 59, 1019.0, 1016.8, 5, 4, 20.4, 23.0, 'No', 'No'), ('3/12/2012', 19.9, 24.0, 0.0, 6.8, 2.3, 'ENE', 43, 'ESE', 'ENE', 4, 26, 76, 64, 1020.2, 1020.0, 5, 4, 22.6, 23.2, 'No', 'No'), ('3/13/2012', 16.8, 25.6, 0.0, 4.0, 11.1, 'NE', 37, 'W', 'E', 13, 19, 78, 57, 1022.3, 1020.0, 5, 4, 20.1, 24.1, 'No', 'No'), ('3/14/2012', 18.1, 25.2, 0.0, 6.8, 7.5, 'E', 39, 'W', 'E', 7, 24, 85, 79, 1020.6, 1018.0, 5, 4, 20.2, 23.0, 'No', 'No'), ('3/15/2012', 20.2, 26.2, 0.0, 4.6, 8.5, 'NNE', 44, 'ENE', 'NE', 13, 22, 80, 60, 1017.2, 1014.5, 5, 4, 22.5, 25.4, 'No', 'No'), ('3/16/2012', 20.1, 28.0, 0.0, 7.8, 10.3, 'NNE', 43, 'ESE', 'ENE', 6, 15, 81, 69, 1012.8, 1009.4, 5, 4, 22.6, 25.5, 'No', 'Yes'), ('3/17/2012', 18.6, 20.2, 41.8, 7.4, 0.2, 'SSW', 50, 'SSW', 'S', 24, 22, 94, 88, 1014.0, 1015.1, 5, 4, 18.6, 19.4, 'Yes', 'Yes'), ('3/18/2012', 17.1, 23.0, 2.4, 3.8, 7.2, 'S', 57, 'SW', 'SSW', 15, 28, 66, 64, 1022.3, 1022.3, 5, 4, 19.4, 21.6, 'Yes', 'Yes'), ('3/19/2012', 17.6, 24.4, 12.0, 6.0, 5.2, 'ESE', 43, 'SE', 'SE', 19, 22, 72, 57, 1023.7, 1022.7, 5, 4, 21.1, 23.2, 'Yes', 'Yes'), ('3/20/2012', 18.9, 24.7, 1.2, 3.6, 5.6, 'E', 31, 'SSW', 'E', 6, 19, 84, 53, 1020.6, 1016.7, 5, 4, 19.6, 24.0, 'Yes', 'No'), ('3/21/2012', 18.9, 25.1, 0.0, 5.6, 7.0, 'NE', 37, 'NNW', 'NE', 13, 20, 83, 72, 1010.8, 1005.1, 5, 4, 20.5, 23.8, 'No', 'No'), ('3/22/2012', 18.3, 20.0, 0.0, 4.8, 0.0, 'S', 63, 'SSW', 'SSW', 17, 13, 79, 75, 1009.5, 1007.9, 5, 4, 18.6, 19.1, 'No', 'No'), ('3/23/2012', 17.6, 26.3, 0.4, 1.4, 10.9, 'W', 57, 'WNW', 'WNW', 11, 20, 84, 31, 1003.6, 1001.7, 5, 4, 19.5, 26.1, 'No', 'No'), ('3/24/2012', 13.9, 25.2, 0.0, 6.6, 11.1, 'W', 44, 'W', 'S', 22, 15, 47, 26, 1012.6, 1011.8, 5, 4, 16.1, 24.2, 'No', 'No'), ('3/25/2012', 14.5, 23.2, 0.0, 7.8, 5.7, 'SE', 28, 'WNW', 'SE', 13, 15, 76, 55, 1022.1, 1021.0, 5, 4, 16.5, 20.8, 'No', 'No'), ('3/26/2012', 16.2, 23.0, 0.4, 3.4, 9.7, 'NE', 37, 'SSW', 'ENE', 2, 22, 77, 60, 1023.6, 1021.2, 5, 4, 19.5, 22.7, 'No', 'No'), ('3/27/2012', 17.7, 24.6, 0.4, 5.6, 7.6, 'N', 33, 'WNW', 'E', 9, 15, 69, 65, 1023.6, 1021.9, 5, 4, 20.6, 23.1, 'No', 'No'), ('3/28/2012', 19.4, 22.5, 0.0, 5.6, 0.4, 'E', 31, 'E', 'ENE', 9, 6, 77, 84, 1023.2, 1020.3, 5, 4, 20.4, 20.4, 'No', 'Yes'), ('3/29/2012', 17.5, 26.5, 6.2, 3.4, 10.2, 'ENE', 26, 'WNW', 'E', 15, 22, 75, 60, 1019.4, 1016.6, 5, 4, 20.1, 23.9, 'Yes', 'No'), ('3/30/2012', 16.7, 24.8, 0.2, 4.0, 7.2, 'W', 22, 'W', 'ESE', 19, 13, 84, 55, 1019.1, 1016.9, 5, 4, 17.5, 24.3, 'No', 'No'), ('3/31/2012', 16.1, 27.0, 0.0, 3.4, 10.7, 'E', 22, 'WNW', 'E', 13, 15, 81, 56, 1018.9, 1016.7, 5, 4, 18.9, 24.6, 'No', 'No'), ('4/1/2012', 16.2, 25.4, 0.0, 5.6, 8.1, 'WSW', 39, 'WNW', 'E', 9, 17, 67, 59, 1018.3, 1015.0, 5, 4, 21.0, 23.7, 'No', 'No'), ('4/2/2012', 17.6, 26.7, 0.6, 3.8, 10.6, 'W', 20, 'W', 'ESE', 9, 15, 75, 64, 1017.8, 1014.7, 5, 4, 21.7, 24.0, 'No', 'No'), ('4/3/2012', 16.8, 26.5, 0.0, 3.0, 8.6, 'W', 24, 'WNW', 'NE', 13, 17, 88, 56, 1016.0, 1013.6, 5, 4, 18.6, 25.6, 'No', 'No'), ('4/4/2012', 18.6, 25.7, 0.0, 6.0, 10.8, 'ENE', 31, 'NE', 'NE', 11, 17, 60, 62, 1017.8, 1016.3, 5, 4, 24.6, 24.5, 'No', 'No'), ('4/5/2012', 19.0, 25.6, 0.0, 3.2, 10.4, 'ENE', 28, 'SSE', 'E', 2, 20, 64, 54, 1021.3, 1019.2, 5, 4, 23.8, 24.4, 'No', 'No'), ('4/6/2012', 17.6, 25.1, 0.0, 6.6, 10.3, 'ENE', 33, 'W', 'ENE', 6, 20, 67, 45, 1021.6, 1017.2, 5, 4, 22.3, 24.1, 'No', 'No'), ('4/7/2012', 18.2, 28.3, 0.0, 8.0, 9.2, 'SSE', 57, 'WSW', 'SSE', 15, 31, 69, 59, 1015.2, 1016.9, 5, 4, 21.5, 23.3, 'No', 'No'), ('4/8/2012', 20.1, 24.3, 0.0, 8.0, 0.5, 'W', 44, 'NE', 'NE', 17, 15, 62, 72, 1019.2, 1013.6, 5, 4, 22.0, 23.4, 'No', 'Yes'), ('4/9/2012', 14.1, 24.8, 6.4, 3.8, 10.7, 'SSE', 61, 'WSW', 'W', 28, 19, 41, 28, 1016.6, 1013.6, 5, 4, 17.6, 24.6, 'Yes', 'No'), ('4/10/2012', 10.1, 19.1, 0.0, 7.0, 10.2, 'SW', 65, 'SSW', 'SSW', 31, 33, 45, 40, 1024.5, 1025.9, 5, 4, 15.5, 18.0, 'No', 'No'), ('4/11/2012', 10.4, 20.2, 0.0, 6.0, 6.1, 'SSW', 54, 'SSW', 'SSW', 24, 31, 59, 55, 1030.6, 1029.7, 5, 4, 15.6, 19.9, 'No', 'Yes'), ('4/12/2012', 13.0, 22.8, 7.2, 2.8, 10.1, 'W', 41, 'W', 'SE', 17, 15, 80, 54, 1032.8, 1030.9, 5, 4, 16.4, 22.2, 'Yes', 'No'), ('4/13/2012', 12.4, 24.7, 0.0, 3.8, 11.0, 'ENE', 28, 'WNW', 'ENE', 17, 20, 75, 54, 1031.9, 1028.1, 5, 4, 16.4, 22.4, 'No', 'No'), ('4/14/2012', 14.7, 24.4, 0.0, 4.8, 7.9, 'ENE', 30, 'W', 'ENE', 4, 17, 74, 63, 1028.2, 1024.0, 5, 4, 18.9, 22.0, 'No', 'No'), ('4/15/2012', 17.0, 25.4, 0.0, 3.8, 4.6, 'W', 22, 'WNW', 'ENE', 19, 11, 65, 72, 1025.2, 1022.4, 5, 4, 20.2, 22.5, 'No', 'No'), ('4/16/2012', 15.9, 25.8, 0.0, 4.8, 7.8, 'S', 35, 'WNW', 'SSE', 11, 20, 63, 58, 1023.9, 1021.7, 5, 4, 19.0, 23.5, 'No', 'Yes'), ('4/17/2012', 17.3, 21.4, 23.6, 5.0, 0.0, 'ESE', 56, 'SSE', 'SE', 20, 9, 91, 85, 1022.9, 1020.6, 5, 4, 18.6, 19.1, 'Yes', 'Yes'), ('4/18/2012', 17.2, 21.1, 48.8, 3.2, 0.2, 'NE', 54, 'WSW', 'ENE', 9, 35, 95, 81, 1021.1, 1018.3, 5, 4, 17.6, 20.5, 'Yes', 'Yes'), ('4/19/2012', 17.5, 23.8, 56.0, 4.8, 3.3, 'ENE', 31, 'ENE', 'E', 2, 13, 92, 82, 1019.7, 1016.2, 5, 4, 19.5, 21.5, 'Yes', 'No'), ('4/20/2012', 17.4, 25.1, 0.8, 1.0, 8.5, 'W', 41, 'W', 'ENE', 9, 9, 91, 72, 1016.5, 1014.4, 5, 4, 19.1, 24.0, 'No', 'No'), ('4/21/2012', 18.2, 24.9, 0.0, 4.0, 5.6, 'SSW', 26, 'SSW', 'SSE', 19, 19, 92, 72, 1015.5, 1012.8, 5, 4, 19.8, 23.4, 'No', 'No'), ('4/23/2012', 17.6, 19.5, 0.0, 1.6, 0.1, 'NW', 33, 'NW', 'N', 20, 15, 81, 85, 1014.0, 1011.0, 5, 4, 19.4, 19.1, 'No', 'Yes'), ('4/24/2012', 15.6, 25.3, 1.6, 1.0, 7.6, 'NW', 74, 'W', 'W', 13, 41, 79, 47, 1011.7, 1009.2, 5, 4, 18.4, 19.8, 'Yes', 'Yes'), ('4/25/2012', 10.8, 19.9, 3.2, 4.0, 10.2, 'W', 65, 'WNW', 'W', 24, 35, 48, 32, 1011.6, 1007.8, 5, 4, 13.5, 19.4, 'Yes', 'No'), ('4/26/2012', 13.5, 21.5, 0.0, 5.8, 6.6, 'W', 37, 'W', 'SSE', 22, 22, 56, 49, 1018.5, 1017.2, 5, 4, 16.8, 19.8, 'No', 'No'), ('4/27/2012', 12.9, 22.8, 0.0, 3.4, 10.3, 'W', 22, 'W', 'ESE', 19, 17, 68, 57, 1022.0, 1020.5, 5, 4, 15.4, 21.5, 'No', 'No'), ('4/28/2012', 13.8, 24.2, 0.0, 2.4, 5.2, 'N', 24, 'W', 'NE', 15, 11, 80, 51, 1022.0, 1017.4, 5, 4, 16.0, 23.0, 'No', 'No'), ('4/29/2012', 13.1, 19.1, 0.0, 3.0, 6.6, 'S', 56, 'SSW', 'SSE', 17, 28, 73, 52, 1020.8, 1021.9, 5, 4, 17.7, 18.7, 'No', 'No'), ('4/30/2012', 10.9, 20.2, 0.0, 5.4, 3.5, 'W', 30, 'W', 'ENE', 20, 11, 70, 43, 1027.3, 1025.0, 5, 4, 13.5, 19.9, 'No', 'No'), ('5/1/2012', 12.7, 22.1, 0.0, 2.4, 9.5, 'ENE', 31, 'WNW', 'NE', 9, 20, 76, 55, 1027.2, 1023.2, 5, 4, 15.5, 21.4, 'No', 'No'), ('5/2/2012', 12.4, 22.3, 0.0, 3.6, 9.0, 'W', 31, 'W', 'ENE', 15, 20, 79, 64, 1023.0, 1018.4, 5, 4, 15.6, 22.1, 'No', 'No'), ('5/3/2012', 15.2, 23.3, 0.0, 3.0, 10.3, 'WSW', 26, 'W', 'ESE', 15, 17, 63, 53, 1019.7, 1017.3, 5, 4, 17.7, 21.3, 'No', 'No'), ('5/4/2012', 11.5, 22.4, 0.0, 5.0, 10.3, 'W', 31, 'W', 'ESE', 20, 19, 45, 38, 1020.6, 1016.8, 5, 4, 13.7, 20.9, 'No', 'No'), ('5/5/2012', 11.8, 20.9, 0.0, 3.0, 6.8, 'SSW', 48, 'W', 'S', 20, 26, 64, 55, 1016.8, 1013.2, 5, 4, 15.1, 20.3, 'No', 'No'), ('5/6/2012', 10.8, 21.3, 0.0, 4.2, 10.3, 'W', 37, 'W', 'NE', 24, 13, 65, 37, 1016.9, 1014.2, 5, 4, 12.9, 21.0, 'No', 'No'), ('5/7/2012', 11.2, 18.5, 0.0, 3.0, 0.7, 'SSW', 30, 'W', 'SW', 13, 7, 64, 44, 1018.2, 1015.7, 5, 4, 12.4, 17.9, 'No', 'No'), ('5/8/2012', 10.8, 23.3, 0.0, 1.2, 10.2, 'W', 30, 'W', 'WNW', 22, 7, 68, 37, 1018.7, 1016.5, 5, 4, 13.8, 22.8, 'No', 'No'), ('5/9/2012', 12.0, 27.1, 0.0, 3.0, 10.2, 'W', 22, 'W', 'E', 15, 9, 68, 30, 1021.1, 1018.9, 5, 4, 15.3, 26.7, 'No', 'No'), ('5/10/2012', 14.1, 29.1, 0.0, 3.8, 10.2, 'W', 28, 'W', 'ESE', 22, 19, 67, 50, 1021.7, 1019.4, 5, 4, 16.7, 26.3, 'No', 'No'), ('5/11/2012', 14.3, 24.9, 0.0, 4.0, 5.2, 'W', 28, 'W', 'E', 9, 7, 63, 43, 1018.5, 1013.8, 5, 4, 16.5, 24.7, 'No', 'No'), ('5/12/2012', 13.8, 20.7, 0.0, 2.6, 6.8, 'WSW', 54, 'WSW', 'WSW', 17, 6, 60, 28, 1017.6, 1014.1, 5, 4, 15.1, 19.2, 'No', 'No'), ('5/13/2012', 9.9, 18.1, 0.0, 5.4, 10.1, 'W', 70, 'WSW', 'W', 31, 39, 42, 35, 1013.4, 1011.5, 5, 4, 13.5, 16.8, 'No', 'No'), ('5/14/2012', 9.1, 18.6, 0.0, 4.6, 10.1, 'W', 43, 'W', 'SSW', 20, 22, 49, 40, 1021.4, 1021.5, 5, 4, 11.8, 17.2, 'No', 'No'), ('5/15/2012', 8.5, 20.2, 0.0, 3.2, 9.9, 'W', 35, 'W', 'SSE', 24, 20, 56, 41, 1024.3, 1021.9, 5, 4, 12.1, 19.1, 'No', 'No'), ('5/16/2012', 9.8, 21.1, 0.0, 3.8, 9.5, 'W', 31, 'W', 'SSE', 22, 13, 68, 50, 1025.0, 1022.5, 5, 4, 12.0, 19.9, 'No', 'No'), ('5/17/2012', 10.0, 21.6, 0.0, 2.0, 9.5, 'W', 26, 'W', 'E', 19, 17, 77, 46, 1025.0, 1022.0, 5, 4, 12.5, 20.1, 'No', 'No'), ('5/18/2012', 10.5, 23.1, 0.0, 1.8, 9.7, 'W', 22, 'W', 'E', 17, 11, 82, 40, 1025.1, 1021.1, 5, 4, 12.4, 22.2, 'No', 'No'), ('5/19/2012', 10.4, 21.1, 0.0, 3.8, 9.0, 'W', 30, 'W', 'WNW', 24, 9, 71, 37, 1023.1, 1020.3, 5, 4, 12.4, 20.4, 'No', 'No'), ('5/20/2012', 10.4, 16.4, 0.0, 3.0, 0.4, 'W', 30, 'WNW', 'SSW', 19, 13, 75, 82, 1026.1, 1024.1, 5, 4, 13.0, 15.0, 'No', 'No'), ('5/21/2012', 12.2, 20.9, 0.4, 0.4, 8.5, 'W', 26, 'W', 'NNE', 20, 13, 78, 52, 1025.5, 1021.6, 5, 4, 13.6, 20.6, 'No', 'No'), ('5/22/2012', 9.8, 20.9, 0.0, 3.0, 10.0, 'WNW', 33, 'W', 'WNW', 20, 13, 70, 64, 1024.2, 1020.7, 5, 4, 11.8, 20.5, 'No', 'No'), ('5/23/2012', 10.3, 23.0, 0.0, 4.0, 10.1, 'NW', 24, 'W', 'N', 11, 17, 69, 88, 1024.4, 1020.2, 5, 4, 13.2, 21.7, 'No', 'No'), ('5/24/2012', 9.6, 17.1, 0.0, 4.0, 2.4, 'W', 37, 'WNW', 'W', 7, 7, 79, 93, 1020.5, 1018.7, 5, 4, 12.2, 13.7, 'No', 'Yes'), ('5/25/2012', 12.2, 18.6, 13.8, 1.0, 4.3, 'WNW', 59, 'NNW', 'NNW', 24, 24, 77, 37, 1012.5, 1008.8, 5, 4, 15.7, 18.4, 'Yes', 'No'), ('5/26/2012', 10.4, 17.5, 0.0, 6.0, 7.8, 'W', 61, 'WNW', 'W', 26, 31, 43, 41, 1013.9, 1012.8, 5, 4, 12.5, 15.9, 'No', 'No'), ('5/27/2012', 10.0, 19.3, 0.2, 3.4, 9.2, 'SW', 41, 'W', 'S', 22, 19, 65, 50, 1020.3, 1019.5, 5, 4, 12.3, 17.9, 'No', 'No'), ('5/28/2012', 9.1, 18.9, 0.0, 2.6, 9.3, 'SSW', 41, 'W', 'S', 20, 26, 66, 52, 1026.5, 1025.3, 5, 4, 12.1, 17.7, 'No', 'Yes'), ('5/29/2012', 11.3, 18.1, 21.4, 3.0, 2.2, 'SSW', 30, 'NW', 'S', 9, 17, 94, 69, 1031.6, 1030.6, 5, 4, 12.1, 16.6, 'Yes', 'Yes'), ('5/30/2012', 10.4, 18.5, 1.4, 1.0, 6.6, 'W', 26, 'W', 'SSE', 19, 13, 80, 63, 1035.0, 1032.5, 5, 4, 12.8, 17.3, 'Yes', 'No'), ('5/31/2012', 11.9, 20.1, 0.0, 3.2, 2.0, 'ENE', 28, 'W', 'SSE', 20, 15, 79, 63, 1033.6, 1030.7, 5, 4, 12.9, 17.4, 'No', 'No'), ('6/1/2012', 11.6, 18.8, 0.2, 1.0, 1.2, 'NNE', 24, 'WNW', 'ESE', 15, 6, 89, 67, 1029.6, 1025.7, 5, 4, 12.8, 18.2, 'No', 'No'), ('6/2/2012', 12.8, 16.8, 0.2, 0.6, 0.0, 'SSW', 24, 'WNW', 'ESE', 13, 6, 91, 94, 1022.3, 1018.7, 5, 4, 14.9, 15.8, 'No', 'Yes'), ('6/3/2012', 14.0, 15.3, 27.4, 1.6, 0.0, 'SSE', 24, 'WNW', 'SSE', 11, 15, 96, 94, 1014.6, 1010.6, 5, 4, 14.2, 15.2, 'Yes', 'Yes'), ('6/4/2012', 12.8, 20.6, 11.2, 0.2, 8.1, 'W', 35, 'W', 'WNW', 13, 9, 91, 57, 1004.2, 1000.4, 5, 4, 14.3, 18.7, 'Yes', 'No'), ('6/5/2012', 9.0, 16.1, 0.0, 4.2, 4.0, 'SSE', 76, 'WNW', 'W', 15, 33, 53, 64, 1000.4, 1000.7, 5, 4, 12.0, 12.4, 'No', 'Yes'), ('6/6/2012', 10.4, 16.0, 19.2, 2.6, 5.0, 'S', 72, 'SSW', 'SSE', 28, 28, 70, 79, 1016.1, 1017.9, 5, 4, 14.0, 13.7, 'Yes', 'Yes'), ('6/7/2012', 9.1, 17.7, 6.8, 1.6, 9.1, 'WSW', 39, 'W', 'SSE', 24, 17, 68, 42, 1023.2, 1021.2, 5, 4, 10.4, 17.4, 'Yes', 'No'), ('6/8/2012', 6.4, 18.0, 0.0, 2.6, 9.6, 'W', 31, 'W', 'ENE', 20, 6, 71, 46, 1026.0, 1023.8, 5, 4, 8.6, 16.6, 'No', 'No'), ('6/9/2012', 6.6, 18.3, 0.0, 2.0, 9.5, 'W', 31, 'W', 'NNW', 24, 4, 78, 44, 1026.7, 1024.0, 5, 4, 8.3, 17.6, 'No', 'Yes'), ('6/10/2012', 8.3, 14.2, 2.4, 0.2, 0.2, 'SE', 30, 'W', 'WSW', 15, 6, 87, 87, 1026.2, 1023.4, 5, 4, 10.0, 13.6, 'Yes', 'Yes'), ('6/11/2012', 9.9, 16.1, 76.4, 4.2, 0.0, 'SE', 41, 'W', 'SW', 20, 15, 96, 96, 1022.5, 1020.4, 5, 4, 11.8, 13.0, 'Yes', 'Yes'), ('6/12/2012', 11.7, 19.3, 49.4, 2.4, 5.7, 'SE', 50, 'SE', 'S', 22, 24, 71, 66, 1020.5, 1018.5, 5, 4, 16.1, 17.4, 'Yes', 'Yes'), ('6/13/2012', 10.7, 15.4, 8.6, 1.6, 1.5, 'SW', 30, 'WNW', 'W', 13, 11, 95, 91, 1021.1, 1019.2, 5, 4, 12.1, 14.8, 'Yes', 'Yes'), ('6/14/2012', 11.2, 19.4, 13.8, 1.2, 5.6, 'WNW', 22, 'W', 'E', 15, 0, 93, 65, 1019.4, 1016.4, 5, 4, 12.9, 17.5, 'Yes', 'No'), ('6/15/2012', 11.4, 20.9, 0.0, 1.6, 3.5, 'N', 24, 'W', 'NNE', 11, 13, 89, 52, 1016.7, 1013.2, 5, 4, 11.8, 20.4, 'No', 'No'), ('6/16/2012', 11.7, 13.9, 0.4, 1.8, 0.0, 'W', 26, 'W', 'NNE', 13, 9, 88, 91, 1018.2, 1014.2, 5, 4, 12.0, 13.8, 'No', 'Yes'), ('6/17/2012', 10.1, 18.5, 8.4, 0.8, 9.7, 'W', 50, 'W', 'W', 15, 30, 68, 38, 1018.8, 1016.6, 5, 4, 12.1, 18.3, 'Yes', 'No'), ('6/18/2012', 9.8, 19.8, 0.0, 3.4, 9.6, 'WSW', 30, 'WNW', 'W', 19, 17, 66, 36, 1022.1, 1019.7, 5, 4, 11.6, 19.0, 'No', 'No'), ('6/19/2012', 8.6, 19.2, 0.0, 2.2, 9.7, 'WSW', 54, 'W', 'WSW', 13, 28, 65, 37, 1019.6, 1017.7, 5, 4, 11.4, 19.0, 'No', 'No'), ('6/20/2012', 7.3, 18.1, 0.0, 4.4, 9.6, 'W', 26, 'WNW', 'NE', 13, 4, 74, 45, 1022.8, 1017.9, 5, 4, 9.1, 17.2, 'No', 'No'), ('6/21/2012', 8.4, 18.7, 0.0, 2.6, 1.4, 'N', 35, 'NW', 'NNE', 2, 17, 70, 47, 1016.4, 1010.7, 5, 4, 10.7, 18.4, 'No', 'No'), ('6/22/2012', 10.7, 17.2, 0.0, 5.0, 1.2, 'NW', 61, 'NNW', 'WNW', 19, 20, 44, 56, 1006.6, 1007.9, 5, 4, 16.4, 14.8, 'No', 'No'), ('6/23/2012', 8.0, 17.0, 0.0, 2.0, 9.6, 'WSW', 43, 'W', 'WSW', 17, 15, 66, 32, 1022.2, 1021.2, 5, 4, 9.3, 16.2, 'No', 'No'), ('6/24/2012', 6.9, 18.3, 0.0, 3.2, 9.8, 'W', 37, 'WNW', 'WSW', 17, 19, 55, 38, 1028.1, 1026.1, 5, 4, 9.9, 18.1, 'No', 'No'), ('6/26/2012', 8.6, 13.7, 8.8, 2.0, 0.0, 'S', 37, 'S', 'S', 11, 15, 84, 87, 1030.7, 1029.5, 5, 4, 12.8, 12.9, 'Yes', 'Yes'), ('6/27/2012', 9.7, 17.6, 9.4, 2.0, 5.7, 'SSE', 28, 'SSW', 'SE', 7, 15, 84, 58, 1031.7, 1028.6, 5, 4, 12.4, 15.8, 'Yes', 'No'), ('6/28/2012', 9.0, 18.5, 0.0, 1.0, 4.6, 'W', 26, 'W', 'ESE', 19, 9, 89, 66, 1026.1, 1020.8, 5, 4, 10.5, 16.8, 'No', 'Yes'), ('6/29/2012', 10.4, 19.0, 1.6, 2.4, 6.7, 'NNE', 24, 'W', 'ENE', 13, 13, 91, 70, 1016.1, 1010.9, 5, 4, 12.3, 17.9, 'Yes', 'No'), ('6/30/2012', 10.1, 20.0, 0.0, 2.0, 7.3, 'NNW', 30, 'W', 'NW', 19, 13, 79, 41, 1013.6, 1011.4, 5, 4, 12.1, 18.0, 'No', 'No'), ('7/1/2012', 9.9, 16.1, 0.0, 3.0, 5.9, 'WSW', 44, 'W', 'W', 15, 28, 69, 28, 1016.2, 1013.4, 6, 2, 10.4, 15.8, 'No', 'No'), ('7/2/2012', 7.5, 16.8, 0.0, 3.8, 9.6, 'W', 52, 'W', 'WSW', 28, 24, 56, 36, 1016.0, 1015.5, 1, 3, 11.3, 16.1, 'No', 'No'), ('7/3/2012', 7.7, 16.8, 0.0, 2.8, 9.5, 'W', 41, 'W', 'S', 20, 19, 61, 40, 1020.3, 1018.1, 1, 5, 9.6, 15.8, 'No', 'No'), ('7/4/2012', 7.2, 16.2, 0.0, 3.6, 6.4, 'W', 41, 'W', 'SSW', 28, 26, 55, 43, 1024.6, 1025.1, 3, 7, 9.6, 15.9, 'No', 'Yes'), ('7/5/2012', 8.7, 14.9, 4.0, 2.6, 4.5, 'SSW', 44, 'W', 'SSW', 17, 24, 75, 72, 1031.0, 1030.1, 5, 7, 10.7, 13.6, 'Yes', 'Yes'), ('7/6/2012', 9.6, 16.0, 19.0, 1.8, 5.8, 'SSW', 44, 'SW', 'S', 17, 22, 89, 52, 1033.1, 1031.4, 4, 2, 11.0, 15.3, 'Yes', 'Yes'), ('7/7/2012', 8.7, 15.1, 1.2, 2.4, 0.7, 'W', 31, 'W', 'SW', 24, 11, 86, 71, 1032.5, 1030.5, 7, 7, 9.9, 13.9, 'Yes', 'No'), ('7/8/2012', 9.1, 18.0, 0.2, 0.8, 8.1, 'W', 26, 'W', 'E', 19, 11, 81, 57, 1031.2, 1028.2, 2, 2, 10.4, 16.6, 'No', 'No'), ('7/9/2012', 8.3, 17.0, 0.0, 1.2, 9.6, 'ENE', 24, 'WNW', 'NE', 15, 13, 90, 67, 1030.4, 1026.6, 3, 5, 9.3, 16.7, 'No', 'No'), ('7/10/2012', 8.4, 18.0, 0.0, 1.8, 2.4, 'NE', 44, 'W', 'NNE', 9, 22, 92, 67, 1026.6, 1021.1, 7, 7, 10.2, 17.6, 'No', 'Yes'), ('7/11/2012', 10.2, 20.6, 5.4, 3.4, 8.6, 'W', 31, 'WNW', 'NW', 11, 15, 76, 44, 1020.1, 1017.6, 1, 5, 13.2, 20.1, 'Yes', 'No'), ('7/12/2012', 11.6, 17.3, 0.0, 3.0, 0.2, 'NNW', 31, 'W', 'NNE', 9, 9, 80, 79, 1017.5, 1012.7, 7, 8, 13.0, 17.1, 'No', 'No'), ('7/13/2012', 12.9, 22.9, 0.2, 0.4, 6.3, 'N', 39, 'NW', 'N', 15, 26, 74, 62, 1011.6, 1008.0, 5, 6, 17.2, 21.3, 'No', 'No'), ('7/14/2012', 11.1, 20.2, 0.0, 3.2, 9.5, 'NW', 39, 'W', 'WNW', 13, 19, 73, 31, 1013.2, 1009.7, 2, 1, 13.4, 19.1, 'No', 'No'), ('7/15/2012', 9.0, 18.2, 0.0, 5.0, 10.0, 'WSW', 46, 'WNW', 'WSW', 9, 17, 52, 33, 1016.9, 1016.9, 1, 1, 12.2, 17.8, 'No', 'No'), ('7/16/2012', 9.4, 20.3, 0.0, 2.6, 9.9, 'W', 43, 'W', 'ENE', 24, 11, 62, 36, 1027.5, 1025.4, 0, 0, 11.3, 18.3, 'No', 'No'), ('7/17/2012', 8.1, 21.0, 0.0, 3.6, 9.7, 'N', 35, 'WNW', 'N', 13, 17, 82, 34, 1026.5, 1021.5, 1, 0, 9.8, 20.4, 'No', 'No'), ('7/18/2012', 9.3, 20.7, 0.0, 3.2, 7.9, 'WSW', 31, 'W', 'SW', 20, 13, 70, 33, 1019.4, 1015.8, 4, 2, 10.5, 20.2, 'No', 'No'), ('7/19/2012', 8.7, 15.4, 0.0, 3.6, 5.4, 'S', 50, 'W', 'SSW', 26, 31, 63, 50, 1020.2, 1020.3, 4, 5, 10.8, 14.6, 'No', 'No'), ('7/20/2012', 5.8, 17.3, 0.0, 2.8, 9.8, 'SSW', 35, 'W', 'SSW', 22, 19, 65, 38, 1025.9, 1024.7, 1, 1, 8.1, 16.6, 'No', 'Yes'), ('7/21/2012', 8.1, 14.9, 5.0, 2.0, 1.4, 'SSW', 52, 'SSW', 'SSW', 17, 22, 81, 54, 1029.3, 1028.5, 8, 7, 13.3, 14.8, 'Yes', 'Yes'), ('7/22/2012', 9.7, 16.9, 2.6, 3.6, 6.8, 'SE', 48, 'W', 'S', 20, 20, 92, 62, 1029.6, 1027.6, 6, 6, 10.6, 16.2, 'Yes', 'Yes'), ('7/24/2012', 10.4, 14.0, 6.8, 2.4, 0.6, 'W', 26, 'W', 'SSW', 17, 11, 95, 85, 1027.9, 1025.6, 7, 7, 11.2, 13.6, 'Yes', 'Yes'), ('7/25/2012', 8.7, 19.6, 4.4, 0.2, 6.5, 'N', 30, 'W', 'ENE', 17, 20, 93, 50, 1023.9, 1019.3, 8, 2, 10.0, 18.0, 'Yes', 'No'), ('7/26/2012', 10.0, 19.5, 0.0, 3.8, 3.9, 'NNW', 31, 'N', 'NE', 13, 7, 57, 48, 1015.4, 1011.3, 6, 7, 14.7, 17.8, 'No', 'No'), ('7/27/2012', 8.7, 17.4, 0.4, 2.4, 10.0, 'W', 41, 'W', 'W', 15, 20, 74, 32, 1012.6, 1009.8, 0, 3, 11.3, 17.0, 'No', 'No'), ('7/28/2012', 7.8, 19.4, 0.0, 4.0, 9.7, 'WSW', 44, 'W', 'S', 22, 11, 68, 45, 1016.2, 1015.7, 1, 4, 9.8, 16.7, 'No', 'No'), ('7/29/2012', 8.4, 16.2, 0.0, 1.6, 7.1, 'S', 39, 'WNW', 'S', 17, 20, 66, 45, 1022.5, 1021.6, 1, 6, 11.5, 16.1, 'No', 'No'), ('7/30/2012', 7.3, 15.9, 0.0, 4.0, 10.0, 'SSW', 54, 'W', 'SSW', 24, 28, 54, 36, 1024.2, 1022.2, 1, 1, 9.6, 15.3, 'No', 'Yes'), ('7/31/2012', 7.5, 16.1, 4.4, 3.0, 6.3, 'SW', 44, 'W', 'SSW', 26, 24, 60, 52, 1025.8, 1022.9, 6, 6, 9.9, 13.7, 'Yes', 'No'), ('8/1/2012', 7.0, 16.2, 0.0, 2.4, 8.3, 'SSW', 43, 'W', 'S', 22, 22, 62, 38, 1022.5, 1019.5, 2, 2, 9.5, 15.7, 'No', 'No'), ('8/2/2012', 6.5, 17.4, 0.0, 4.2, 9.6, 'W', 44, 'W', 'SE', 26, 9, 58, 37, 1022.3, 1018.5, 1, 3, 9.2, 15.8, 'No', 'No'), ('8/3/2012', 6.8, 18.5, 0.0, 3.6, 7.7, 'WNW', 31, 'W', 'NW', 9, 11, 58, 32, 1017.8, 1014.4, 7, 1, 9.7, 18.1, 'No', 'No'), ('8/4/2012', 7.2, 20.8, 0.0, 2.4, 10.2, 'W', 35, 'W', 'NW', 22, 6, 60, 27, 1017.9, 1014.3, 3, 2, 9.9, 20.3, 'No', 'No'), ('8/5/2012', 9.3, 21.6, 0.0, 1.6, 7.7, 'WSW', 44, 'W', 'W', 17, 15, 50, 27, 1016.1, 1011.3, 1, 7, 12.2, 19.8, 'No', 'No'), ('8/6/2012', 11.6, 19.4, 0.0, 7.2, 10.2, 'SSW', 46, 'N', 'SW', 2, 17, 45, 22, 1014.8, 1014.9, 1, 1, 14.3, 18.4, 'No', 'No'), ('8/7/2012', 6.8, 18.6, 0.0, 3.2, 10.2, 'W', 33, 'W', 'WNW', 22, 6, 54, 25, 1024.4, 1021.3, 1, 0, 9.8, 18.2, 'No', 'No'), ('8/8/2012', 5.6, 22.5, 0.0, 3.6, 10.6, 'W', 30, 'W', 'W', 17, 9, 55, 26, 1022.0, 1015.2, 1, 1, 9.5, 21.4, 'No', 'No'), ('8/9/2012', 9.5, 19.8, 0.0, 3.4, 6.6, 'W', 63, 'WNW', 'WSW', 9, 31, 51, 18, 1014.7, 1009.9, 7, 2, 13.5, 18.9, 'No', 'No'), ('8/10/2012', 7.6, 14.9, 0.0, 5.0, 3.8, 'S', 93, 'W', 'SSW', 31, 26, 42, 76, 1015.4, 1016.6, 3, 7, 10.4, 12.2, 'No', 'Yes'), ('8/15/2012', 10.2, 22.2, 0.0, 4.6, 6.0, 'WNW', 30, 'WNW', 'N', 19, 11, 48, 35, 1016.8, 1011.5, 2, 7, 14.6, 20.1, 'No', 'No'), ('8/16/2012', 11.7, 20.6, 0.0, 2.0, 9.2, 'W', 35, 'W', 'E', 26, 19, 47, 43, 1014.7, 1010.7, 1, 2, 13.5, 17.4, 'No', 'No'), ('8/17/2012', 11.1, 22.2, 0.0, 5.8, 8.3, 'W', 76, 'N', 'WNW', 19, 37, 36, 35, 1007.7, 1004.3, 1, 6, 15.9, 14.5, 'No', 'No'), ('8/18/2012', 9.6, 18.1, 0.0, 6.6, 10.4, 'W', 61, 'NW', 'W', 30, 33, 45, 33, 1007.0, 1007.4, 2, 4, 12.7, 17.9, 'No', 'No'), ('8/19/2012', 9.7, 20.1, 0.0, 6.0, 10.0, 'WSW', 37, 'W', 'E', 20, 17, 54, 43, 1020.3, 1019.1, 1, 2, 13.4, 16.9, 'No', 'No'), ('8/20/2012', 7.5, 17.8, 0.0, 3.2, 10.7, 'W', 24, 'W', 'E', 19, 17, 62, 47, 1024.3, 1019.1, 3, 1, 10.1, 16.0, 'No', 'No'), ('8/21/2012', 8.7, 22.2, 0.0, 2.6, 9.2, 'NNE', 31, 'WNW', 'ENE', 13, 19, 70, 36, 1020.6, 1016.0, 5, 1, 11.0, 19.0, 'No', 'No'), ('8/22/2012', 10.6, 24.7, 0.0, 3.8, 9.1, 'W', 41, 'WNW', 'ENE', 9, 19, 59, 54, 1015.5, 1010.4, 6, 6, 16.1, 20.8, 'No', 'No'), ('8/23/2012', 16.1, 29.2, 0.0, 6.4, 6.9, 'NW', 91, 'WNW', 'NW', 17, 41, 45, 25, 1009.5, 1005.9, 7, 7, 22.2, 26.3, 'No', 'Yes'), ('8/24/2012', 12.4, 19.3, 10.2, 7.8, 11.0, 'W', 67, 'WNW', 'WNW', 31, 33, 36, 23, 1014.2, 1011.8, 1, 1, 13.6, 18.9, 'Yes', 'No'), ('8/25/2012', 10.7, 20.7, 0.0, 6.4, 10.7, 'W', 41, 'WNW', 'WNW', 15, 6, 42, 26, 1018.0, 1015.5, 1, 1, 13.8, 20.0, 'No', 'No'), ('8/26/2012', 8.3, 20.9, 0.0, 4.4, 10.0, 'W', 33, 'W', 'E', 19, 15, 48, 41, 1018.7, 1016.9, 3, 3, 11.7, 17.2, 'No', 'No'), ('8/30/2012', 12.0, 22.1, 0.0, 5.0, 9.5, 'NW', 54, 'W', 'WNW', 9, 30, 47, 18, 1010.5, 1008.9, 5, 6, 17.2, 21.2, 'No', 'No'), ('8/31/2012', 9.7, 18.4, 0.0, 6.2, 7.6, 'SSW', 59, 'W', 'W', 26, 24, 39, 24, 1016.6, 1013.7, 1, 6, 12.8, 16.6, 'No', 'No'), ('9/1/2012', 5.5, 17.6, 0.4, 5.0, 9.6, 'S', 61, 'W', 'S', 24, 31, 45, 38, 1021.9, 1020.2, 1, 6, 10.5, 16.2, 'No', 'No'), ('9/2/2012', 7.2, 20.7, 0.8, 3.8, 11.2, 'W', 31, 'W', 'ENE', 20, 19, 61, 45, 1024.3, 1019.9, 1, 1, 12.1, 17.0, 'No', 'No'), ('9/3/2012', 7.5, 22.8, 0.0, 3.4, 10.8, 'WNW', 28, 'W', 'E', 17, 15, 52, 37, 1022.2, 1019.8, 0, 1, 13.3, 19.6, 'No', 'No'), ('9/4/2012', 9.7, 24.4, 0.2, 4.0, 9.9, 'W', 28, 'W', 'E', 19, 17, 55, 33, 1022.9, 1019.6, 5, 1, 13.6, 21.4, 'No', 'No'), ('9/5/2012', 11.1, 28.3, 0.0, 5.2, 10.6, 'NNW', 57, 'NNW', 'NNW', 15, 31, 28, 13, 1016.0, 1007.3, 1, 0, 20.8, 27.5, 'No', 'No'), ('9/6/2012', 18.4, 27.9, 0.0, 13.4, 10.7, 'NW', 54, 'WNW', 'WNW', 28, 22, 28, 10, 1007.7, 1005.3, 0, 0, 21.5, 27.6, 'No', 'No'), ('9/7/2012', 16.4, 21.7, 0.0, 10.8, 8.7, 'W', 72, 'WNW', 'WNW', 20, 39, 22, 22, 1005.8, 1006.2, 0, 5, 21.3, 18.4, 'No', 'No'), ('9/8/2012', 11.3, 21.0, 0.0, 6.6, 10.8, 'W', 59, 'W', 'WSW', 30, 28, 39, 31, 1014.5, 1012.8, 1, 1, 15.0, 20.4, 'No', 'No'), ('9/11/2012', 12.6, 21.8, 0.0, 5.4, 8.7, 'S', 39, 'WNW', 'SSE', 17, 17, 66, 51, 1025.0, 1022.4, 7, 1, 16.4, 21.0, 'No', 'No'), ('9/12/2012', 11.0, 21.3, 0.0, 3.8, 10.2, 'NE', 43, 'W', 'NE', 11, 20, 66, 67, 1023.1, 1015.7, 6, 1, 15.8, 19.6, 'No', 'No'), ('9/13/2012', 14.0, 24.7, 0.0, 5.6, 2.7, 'SSW', 63, 'N', 'S', 20, 33, 39, 83, 1006.2, 1007.3, 4, 8, 21.0, 15.0, 'No', 'Yes'), ('9/14/2012', 7.9, 18.5, 3.8, 3.0, 11.3, 'WSW', 37, 'W', 'ESE', 20, 17, 50, 36, 1019.6, 1017.1, 1, 1, 13.5, 16.9, 'Yes', 'No'), ('9/15/2012', 9.2, 20.1, 0.0, 5.2, 10.7, 'SSE', 37, 'W', 'SE', 19, 19, 54, 44, 1024.9, 1023.5, 1, 1, 15.6, 19.8, 'No', 'No'), ('9/16/2012', 10.5, 21.0, 0.0, 3.2, 10.3, 'NNE', 41, 'N', 'NE', 19, 24, 57, 54, 1021.9, 1016.3, 3, 3, 17.5, 18.5, 'No', 'No'), ('9/17/2012', 14.2, 20.9, 0.0, 5.4, 6.0, 'SSE', 39, 'S', 'SSE', 19, 26, 71, 61, 1019.4, 1016.9, 7, 6, 16.4, 19.4, 'No', 'No'), ('9/18/2012', 12.4, 20.6, 0.0, 3.6, 7.7, 'E', 37, 'W', 'E', 9, 20, 63, 66, 1018.4, 1013.8, 1, 5, 17.9, 18.2, 'No', 'Yes'), ('9/19/2012', 11.1, 22.9, 3.6, 3.8, 11.1, 'W', 35, 'WNW', 'ESE', 11, 17, 57, 45, 1016.0, 1014.4, 1, 3, 17.2, 20.1, 'Yes', 'No'), ('9/20/2012', 12.1, 20.5, 0.2, 6.0, 9.4, 'ENE', 30, 'W', 'E', 13, 22, 73, 60, 1019.3, 1014.7, 6, 2, 15.6, 19.7, 'No', 'No'), ('9/21/2012', 13.8, 22.2, 0.0, 4.4, 4.6, 'WSW', 37, 'NNE', 'ENE', 4, 13, 83, 46, 1012.7, 1009.8, 7, 1, 15.5, 21.9, 'No', 'No'), ('9/22/2012', 12.4, 22.7, 0.8, 4.8, 10.9, 'ESE', 33, 'WNW', 'SE', 11, 17, 49, 50, 1016.2, 1013.1, 1, 1, 19.0, 20.9, 'No', 'No'), ('9/23/2012', 11.2, 23.8, 0.0, 4.4, 11.1, 'SSW', 39, 'SSW', 'NNE', 2, 17, 64, 46, 1011.5, 1005.4, 0, 1, 17.8, 23.5, 'No', 'No'), ('9/24/2012', 13.5, 24.4, 0.0, 8.2, 11.2, 'W', 48, 'WSW', 'E', 26, 17, 31, 29, 1012.6, 1010.6, 1, 1, 17.3, 21.7, 'No', 'No'), ('9/25/2012', 12.0, 19.1, 0.2, 3.2, 3.8, 'ESE', 33, 'W', 'ESE', 13, 26, 51, 63, 1022.1, 1020.0, 2, 6, 15.0, 16.8, 'No', 'No'), ('9/26/2012', 14.6, 20.7, 0.4, 4.2, 8.3, 'ENE', 44, 'S', 'ENE', 4, 33, 67, 59, 1022.5, 1019.0, 6, 1, 17.8, 19.6, 'No', 'No'), ('9/27/2012', 14.1, 22.8, 0.2, 6.8, 6.7, 'NNE', 46, 'NNE', 'NE', 6, 19, 58, 59, 1018.7, 1013.5, 6, 5, 19.4, 21.0, 'No', 'No'), ('9/28/2012', 18.9, 33.2, 0.0, 6.4, 6.0, 'NNW', 65, 'ENE', 'NW', 22, 22, 63, 29, 1009.7, 1003.5, 5, 7, 21.7, 31.2, 'No', 'Yes'), ('9/30/2012', 9.9, 22.4, 0.0, 8.4, 11.5, 'W', 48, 'WSW', 'ESE', 31, 26, 29, 30, 1019.2, 1018.0, 0, 1, 15.4, 20.3, 'No', 'No'), ('10/1/2012', 9.8, 19.9, 0.0, 6.8, 9.8, 'SSE', 30, 'WNW', 'E', 11, 20, 51, 53, 1027.9, 1025.5, 1, 1, 16.4, 18.0, 'No', 'No'), ('10/2/2012', 12.7, 20.3, 0.6, 5.0, 10.6, 'W', 26, 'S', 'E', 11, 17, 58, 45, 1032.7, 1029.2, 4, 1, 17.5, 18.5, 'No', 'No'), ('10/3/2012', 11.2, 27.8, 0.2, 5.8, 11.3, 'NNE', 31, 'W', 'E', 13, 7, 53, 40, 1026.3, 1020.5, 1, 7, 18.7, 24.0, 'No', 'No'), ('10/4/2012', 14.5, 32.2, 0.0, 7.2, 11.4, 'WNW', 37, 'W', 'WNW', 9, 11, 39, 16, 1018.8, 1013.1, 0, 0, 23.9, 31.9, 'No', 'No'), ('10/5/2012', 20.0, 34.2, 0.0, 10.8, 10.3, 'W', 57, 'W', 'SSE', 22, 28, 22, 59, 1014.0, 1013.0, 0, 5, 27.9, 22.8, 'No', 'No'), ('10/6/2012', 15.6, 18.3, 0.0, 7.6, 0.0, 'NE', 48, 'ESE', 'NE', 9, 11, 90, 81, 1019.2, 1014.6, 8, 7, 16.0, 17.2, 'No', 'Yes'), ('10/7/2012', 12.7, 20.6, 3.0, 3.2, 11.2, 'SSW', 57, 'SW', 'SSE', 17, 28, 39, 32, 1013.8, 1013.7, 1, 1, 16.1, 19.3, 'Yes', 'No'), ('10/8/2012', 13.6, 18.2, 0.2, 7.8, 5.9, 'SSE', 35, 'NNW', 'ESE', 7, 19, 60, 46, 1017.1, 1013.4, 6, 6, 15.3, 17.5, 'No', 'No'), ('10/9/2012', 12.1, 19.6, 0.0, 3.8, 9.0, 'S', 33, 'SSE', 'ESE', 7, 19, 67, 52, 1012.8, 1011.1, 7, 6, 13.8, 17.1, 'No', 'No'), ('10/11/2012', 13.5, 19.0, 9.8, 6.8, 3.6, 'WSW', 50, 'SE', 'E', 4, 9, 83, 58, 1005.4, 1004.1, 8, 7, 14.6, 18.2, 'Yes', 'Yes'), ('10/12/2012', 8.5, 16.0, 3.4, 2.0, 4.3, 'SSW', 74, 'W', 'SSW', 35, 22, 84, 87, 1006.3, 1010.7, 5, 7, 8.7, 12.2, 'Yes', 'Yes'), ('10/13/2012', 8.6, 20.1, 4.4, 4.0, 11.0, 'SE', 35, 'W', 'SE', 26, 20, 47, 39, 1019.8, 1019.3, 1, 1, 14.3, 18.9, 'Yes', 'No'), ('10/14/2012', 12.4, 19.5, 0.2, 4.8, 8.8, 'ESE', 28, 'WNW', 'ESE', 13, 20, 77, 52, 1025.6, 1024.0, 7, 1, 14.0, 18.5, 'No', 'No'), ('10/15/2012', 11.4, 23.9, 0.0, 6.4, 11.6, 'NNE', 46, 'W', 'NE', 9, 19, 65, 41, 1024.9, 1020.9, 0, 2, 16.3, 23.2, 'No', 'No'), ('10/16/2012', 15.4, 34.1, 0.0, 7.2, 9.6, 'NNE', 43, 'ESE', 'E', 6, 22, 43, 23, 1018.4, 1013.9, 7, 2, 20.9, 30.7, 'No', 'No'), ('10/17/2012', 20.3, 21.8, 0.0, 11.4, 11.7, 'SSW', 39, 'SE', 'ESE', 22, 24, 62, 46, 1016.4, 1016.4, 5, 6, 21.7, 20.8, 'No', 'No'), ('10/18/2012', 16.6, 21.5, 0.0, 7.4, 8.2, 'ENE', 41, 'ENE', 'NE', 15, 22, 58, 56, 1022.7, 1019.6, 7, 1, 19.4, 20.4, 'No', 'No'), ('10/19/2012', 15.9, 25.6, 0.0, 6.6, 9.8, 'NE', 31, 'WNW', 'E', 11, 19, 78, 56, 1016.4, 1011.6, 7, 4, 17.7, 24.1, 'No', 'No'), ('10/20/2012', 16.6, 33.8, 0.0, 6.8, 11.8, 'SSE', 56, 'WNW', 'S', 22, 33, 44, 57, 1007.8, 1008.5, 1, 2, 22.8, 24.6, 'No', 'No'), ('10/21/2012', 14.9, 27.4, 0.0, 5.0, 5.0, 'S', 46, 'W', 'WNW', 13, 20, 66, 23, 1013.7, 1009.5, 4, 7, 19.9, 26.9, 'No', 'No'), ('10/22/2012', 15.1, 18.7, 0.0, 6.0, 6.6, 'SSE', 80, 'SSE', 'S', 30, 39, 68, 40, 1016.2, 1019.7, 7, 2, 15.6, 18.0, 'No', 'Yes'), ('10/23/2012', 11.8, 19.5, 7.4, 2.0, 10.1, 'SSE', 41, 'SE', 'ESE', 19, 20, 56, 41, 1027.4, 1026.5, 6, 3, 15.7, 18.3, 'Yes', 'No'), ('10/24/2012', 11.7, 23.0, 0.2, 6.0, 11.6, 'NE', 46, 'W', 'NE', 11, 24, 57, 48, 1024.3, 1017.7, 1, 2, 17.3, 21.0, 'No', 'No'), ('10/25/2012', 13.8, 25.6, 0.0, 8.2, 10.5, 'NE', 30, 'W', 'E', 9, 19, 63, 46, 1013.0, 1006.6, 3, 6, 18.2, 24.8, 'No', 'No'), ('10/26/2012', 16.9, 21.2, 0.0, 9.0, 3.3, 'S', 56, 'ESE', 'E', 6, 19, 68, 66, 1010.6, 1007.3, 8, 7, 18.4, 20.0, 'No', 'No'), ('10/27/2012', 13.1, 21.3, 0.0, 5.4, 12.2, 'SSE', 41, 'SSW', 'SE', 7, 24, 39, 40, 1015.7, 1016.4, 1, 1, 18.0, 19.1, 'No', 'No'), ('10/28/2012', 15.3, 19.8, 0.0, 9.2, 5.3, 'SSE', 30, 'ESE', 'E', 13, 15, 51, 47, 1025.5, 1024.3, 7, 8, 17.0, 19.1, 'No', 'No'), ('10/29/2012', 12.1, 21.7, 0.0, 3.6, 9.4, 'ENE', 44, 'WNW', 'E', 9, 30, 59, 55, 1025.1, 1021.2, 6, 2, 17.2, 20.8, 'No', 'No'), ('10/30/2012', 14.1, 23.1, 0.0, 7.2, 9.8, 'NE', 43, 'WSW', 'ENE', 2, 24, 65, 48, 1019.8, 1015.7, 5, 6, 18.6, 22.4, 'No', 'No'), ('10/31/2012', 15.7, 27.8, 0.0, 7.0, 12.0, 'ENE', 33, 'WNW', 'ESE', 11, 20, 64, 52, 1016.1, 1013.0, 0, 3, 21.6, 24.4, 'No', 'No'), ('11/1/2012', 16.8, 33.3, 0.0, 8.0, 5.2, 'W', 52, 'WNW', 'E', 9, 20, 55, 57, 1008.3, 1002.0, 7, 7, 22.6, 24.7, 'No', 'No'), ('11/2/2012', 16.1, 21.9, 0.0, 10.8, 12.2, 'SSE', 54, 'S', 'SSE', 28, 26, 44, 38, 1015.2, 1015.5, 2, 1, 18.1, 20.3, 'No', 'Yes'), ('11/3/2012', 13.7, 18.5, 1.6, 5.6, 0.0, 'SE', 31, 'WSW', 'ESE', 6, 17, 82, 58, 1020.9, 1020.1, 7, 8, 15.5, 17.8, 'Yes', 'Yes'), ('11/4/2012', 14.8, 22.9, 1.4, 2.6, 9.3, 'NE', 41, 'WNW', 'ENE', 6, 26, 80, 63, 1020.5, 1017.5, 4, 4, 18.3, 21.9, 'Yes', 'No'), ('11/5/2012', 17.0, 25.1, 0.2, 5.2, 10.0, 'NNE', 52, 'ESE', 'NE', 9, 20, 70, 61, 1018.7, 1014.9, 1, 4, 21.5, 24.3, 'No', 'No'), ('11/6/2012', 19.6, 25.4, 0.0, 9.0, 8.9, 'NE', 57, 'E', 'NE', 15, 30, 65, 61, 1015.8, 1012.7, 6, 4, 24.0, 23.9, 'No', 'No'), ('11/7/2012', 19.8, 24.2, 0.0, 8.6, 0.0, 'NE', 35, 'NE', 'ENE', 2, 19, 78, 68, 1013.8, 1010.3, 8, 8, 21.7, 22.4, 'No', 'No'), ('11/8/2012', 19.9, 27.3, 0.0, 3.8, 8.4, 'ESE', 35, 'ENE', 'E', 4, 20, 58, 64, 1011.9, 1011.7, 6, 7, 24.1, 23.4, 'No', 'Yes'), ('11/9/2012', 18.5, 27.1, 9.2, 4.2, 9.8, 'S', 50, 'W', 'ENE', 9, 17, 77, 86, 1014.0, 1012.6, 5, 5, 22.2, 20.9, 'Yes', 'Yes'), ('11/10/2012', 16.6, 20.9, 11.4, 7.4, 7.0, 'SSE', 50, 'SSE', 'SSE', 28, 26, 56, 54, 1022.7, 1023.1, 6, 6, 19.6, 18.5, 'Yes', 'No'), ('11/11/2012', 13.1, 21.4, 0.2, 9.6, 12.7, 'ESE', 31, 'ESE', 'ESE', 13, 19, 42, 45, 1028.6, 1026.6, 1, 2, 19.4, 20.8, 'No', 'No'), ('11/12/2012', 13.0, 23.7, 0.0, 6.0, 11.3, 'NE', 54, 'W', 'NE', 13, 31, 55, 51, 1025.0, 1019.7, 4, 7, 19.4, 22.0, 'No', 'No'), ('11/13/2012', 16.9, 23.9, 0.0, 9.8, 9.9, 'S', 57, 'S', 'SSE', 19, 28, 60, 51, 1020.3, 1019.0, 1, 3, 19.6, 21.0, 'No', 'No'), ('11/14/2012', 15.9, 20.7, 0.0, 8.0, 0.3, 'E', 31, 'E', 'E', 15, 20, 80, 71, 1019.5, 1017.4, 8, 8, 16.9, 18.4, 'No', 'No'), ('11/15/2012', 16.2, 24.7, 0.2, 4.2, 7.2, 'ENE', 35, 'NE', 'ENE', 19, 17, 72, 62, 1014.7, 1010.7, 8, 7, 20.5, 23.6, 'No', 'No'), ('11/16/2012', 17.2, 18.0, 0.4, 5.0, 0.0, 'SSW', 41, 'SSW', 'SSE', 11, 9, 86, 81, 1012.7, 1011.0, 8, 8, 17.2, 17.5, 'No', 'Yes'), ('11/17/2012', 15.1, 21.3, 10.4, 2.4, 7.0, 'SE', 33, 'ESE', 'E', 13, 15, 57, 50, 1016.7, 1015.1, 8, 4, 17.4, 19.8, 'Yes', 'No'), ('11/18/2012', 15.3, 23.1, 0.0, 6.0, 12.2, 'S', 70, 'W', 'NE', 6, 35, 65, 57, 1012.9, 1007.7, 5, 3, 19.2, 22.2, 'No', 'No'), ('11/19/2012', 12.8, 21.1, 0.0, 8.4, 6.9, 'S', 50, 'W', 'SSW', 17, 26, 44, 45, 1014.2, 1015.6, 2, 3, 18.1, 19.9, 'No', 'Yes'), ('11/20/2012', 15.8, 23.2, 1.6, 7.0, 7.6, 'SSE', 44, 'SSE', 'SE', 28, 22, 61, 50, 1022.2, 1021.6, 7, 3, 18.9, 21.8, 'Yes', 'No'), ('11/21/2012', 13.4, 24.5, 0.4, 5.2, 10.6, 'NNE', 50, 'W', 'NE', 9, 24, 60, 59, 1018.1, 1012.2, 7, 6, 19.8, 22.3, 'No', 'No'), ('11/22/2012', 17.1, 20.7, 0.0, 9.0, 0.3, 'SSW', 72, 'SSE', 'SE', 22, 22, 66, 59, 1017.1, 1017.0, 7, 7, 18.8, 19.4, 'No', 'No'), ('11/23/2012', 15.7, 22.0, 0.0, 5.4, 5.2, 'SSE', 30, 'E', 'ESE', 13, 17, 59, 55, 1020.3, 1018.5, 7, 7, 18.7, 20.5, 'No', 'No'), ('11/24/2012', 16.4, 25.4, 0.0, 5.2, 10.8, 'ENE', 39, 'ESE', 'E', 9, 28, 67, 63, 1018.8, 1014.8, 5, 1, 21.0, 23.8, 'No', 'No'), ('11/25/2012', 18.5, 31.0, 0.0, 7.8, 12.7, 'ENE', 26, 'W', 'E', 7, 15, 60, 56, 1013.9, 1012.6, 1, 2, 25.3, 27.2, 'No', 'No'), ('11/26/2012', 20.7, 27.2, 0.0, 9.4, 2.9, 'WSW', 41, 'S', 'ESE', 7, 20, 74, 69, 1015.9, 1012.3, 8, 7, 22.5, 24.1, 'No', 'Yes'), ('11/27/2012', 19.8, 24.1, 3.6, 4.4, 1.0, 'NE', 44, 'ESE', 'SE', 6, 13, 80, 74, 1014.1, 1014.7, 7, 7, 22.4, 22.4, 'Yes', 'Yes'), ('11/28/2012', 18.4, 24.5, 10.2, 3.2, 0.0, 'E', 26, 'SE', 'ESE', 9, 13, 84, 74, 1018.4, 1016.5, 7, 7, 20.5, 21.9, 'Yes', 'Yes'), ('11/29/2012', 19.9, 27.0, 1.2, 2.4, 8.3, 'NE', 43, 'ESE', 'NE', 6, 20, 71, 63, 1016.5, 1013.6, 6, 2, 23.6, 26.2, 'Yes', 'No'), ('11/30/2012', 21.3, 29.5, 0.0, 7.0, 6.7, 'E', 44, 'W', 'ENE', 15, 24, 73, 62, 1013.6, 1010.4, 6, 6, 25.9, 28.0, 'No', 'No'), ('1/1/2013', 20.2, 26.2, 0.0, 11.0, 10.9, 'E', 30, 'ESE', 'E', 9, 19, 70, 68, 1012.0, 1008.6, 6, 3, 23.2, 24.1, 'No', 'No'), ('1/2/2013', 20.3, 22.9, 0.0, 7.4, 0.9, 'S', 52, 'SE', 'SE', 17, 24, 70, 61, 1013.8, 1015.1, 7, 7, 21.8, 21.1, 'No', 'No'), ('1/3/2013', 18.4, 24.8, 0.0, 5.6, 12.4, 'E', 30, 'ESE', 'E', 7, 19, 54, 54, 1018.8, 1016.6, 4, 1, 21.8, 23.5, 'No', 'No'), ('1/4/2013', 18.3, 26.6, 0.0, 9.0, 13.1, 'NNE', 52, 'NE', 'ENE', 17, 26, 59, 60, 1016.7, 1014.1, 1, 0, 24.4, 24.8, 'No', 'No'), ('1/5/2013', 20.9, 28.3, 0.0, 9.6, 12.7, 'NE', 52, 'NE', 'ENE', 9, 17, 56, 56, 1016.1, 1014.3, 0, 1, 25.2, 27.2, 'No', 'No'), ('1/6/2013', 21.6, 28.0, 0.0, 11.6, 13.1, 'E', 33, 'ENE', 'E', 13, 20, 65, 56, 1021.0, 1019.7, 3, 1, 25.6, 27.0, 'No', 'No'), ('1/7/2013', 21.4, 27.5, 0.0, 8.0, 9.0, 'NNE', 46, 'S', 'E', 9, 20, 74, 65, 1022.5, 1018.4, 8, 1, 23.2, 25.9, 'No', 'No'), ('1/8/2013', 20.9, 42.3, 0.0, 9.8, 8.7, 'NNW', 69, 'SSE', 'NW', 4, 28, 52, 14, 1005.8, 999.1, 6, 6, 27.3, 39.8, 'No', 'No'), ('1/9/2013', 21.1, 25.0, 0.0, 18.4, 6.1, 'SSE', 50, 'S', 'SSE', 24, 28, 64, 44, 999.3, 1002.1, 6, 6, 22.5, 21.7, 'No', 'No'), ('1/10/2013', 20.2, 25.4, 0.0, 8.4, 1.4, 'ENE', 37, 'ENE', 'ENE', 17, 24, 63, 54, 1009.7, 1009.6, 7, 7, 22.3, 24.3, 'No', 'No'), ('1/11/2013', 21.2, 29.6, 0.0, 6.2, 10.0, 'NE', 43, 'NE', 'ENE', 4, 15, 62, 59, 1010.1, 1005.5, 3, 5, 25.0, 27.3, 'No', 'No'), ('1/12/2013', 23.5, 31.2, 0.0, 9.6, 1.5, 'SSE', 56, 'W', 'S', 13, 26, 53, 50, 1005.8, 1006.7, 6, 7, 29.4, 28.1, 'No', 'No'), ('1/13/2013', 20.7, 23.8, 0.0, 6.2, 0.0, 'SSW', 56, 'ESE', 'SSE', 13, 19, 71, 77, 1011.5, 1008.5, 8, 7, 22.4, 22.2, 'No', 'Yes'), ('1/14/2013', 17.1, 23.7, 8.6, 2.0, 9.4, 'S', 59, 'S', 'SSE', 17, 28, 69, 49, 1015.2, 1017.5, 7, 2, 18.8, 22.2, 'Yes', 'No'), ('1/15/2013', 16.8, 24.9, 0.2, 9.8, 10.8, 'NE', 41, 'NW', 'E', 6, 17, 62, 53, 1019.4, 1016.7, 3, 3, 20.5, 23.1, 'No', 'No'), ('1/16/2013', 19.1, 27.2, 0.0, 6.6, 11.4, 'E', 31, 'WNW', 'E', 7, 24, 64, 65, 1014.6, 1011.8, 3, 4, 23.2, 24.9, 'No', 'No'), ('1/17/2013', 21.4, 29.0, 0.0, 8.2, 12.1, 'ENE', 41, 'NW', 'E', 2, 26, 75, 67, 1012.5, 1007.9, 5, 1, 24.3, 26.5, 'No', 'No'), ('1/18/2013', 21.7, 45.8, 0.0, 9.0, 8.4, 'S', 78, 'E', 'E', 13, 15, 62, 14, 1002.9, 997.9, 0, 3, 28.9, 44.7, 'No', 'No'), ('1/19/2013', 21.5, 24.8, 0.0, 12.6, 2.3, 'SSE', 50, 'S', 'SSE', 19, 20, 65, 59, 1013.2, 1013.8, 6, 8, 22.7, 22.4, 'No', 'No'), ('1/20/2013', 20.2, 24.3, 0.2, 5.0, 0.0, 'SSE', 28, 'SE', 'ESE', 13, 15, 67, 59, 1017.3, 1016.1, 7, 8, 22.3, 23.6, 'No', 'No'), ('1/21/2013', 20.7, 26.6, 0.2, 4.2, 5.3, 'ENE', 37, 'ESE', 'NE', 2, 17, 71, 52, 1015.8, 1013.4, 7, 7, 24.2, 25.5, 'No', 'No'), ('1/22/2013', 20.9, 29.6, 0.0, 7.4, 7.3, 'S', 52, 'NNE', 'NE', 17, 17, 63, 63, 1010.4, 1007.4, 2, 7, 26.5, 26.5, 'No', 'No'), ('1/23/2013', 20.7, 25.7, 0.0, 6.2, 2.3, 'S', 56, 'SSW', 'S', 20, 26, 74, 61, 1015.3, 1015.3, 7, 7, 21.8, 24.4, 'No', 'No'), ('1/24/2013', 20.4, 29.8, 0.0, 7.2, 10.5, 'SSW', 33, 'SSW', 'ESE', 20, 20, 70, 52, 1017.5, 1015.3, 7, 2, 22.7, 29.3, 'No', 'No'), ('1/25/2013', 21.6, 29.2, 0.0, 4.6, 12.8, 'ENE', 44, 'N', 'E', 11, 26, 69, 64, 1012.9, 1010.5, 2, 1, 25.8, 27.6, 'No', 'No'), ('1/26/2013', 23.7, 28.2, 0.0, 11.4, 8.3, 'NE', 57, 'ENE', 'NE', 17, 30, 73, 70, 1012.5, 1011.1, 7, 6, 26.5, 27.0, 'No', 'Yes'), ('1/27/2013', 20.1, 22.7, 16.8, 8.2, 0.0, 'W', 50, 'E', 'NNE', 6, 9, 90, 90, 1009.2, 1009.0, 8, 8, 20.5, 20.9, 'Yes', 'Yes'), ('1/28/2013', 20.5, 23.0, 15.8, 2.2, 0.0, 'NE', 69, 'NE', 'ENE', 7, 24, 88, 92, 1009.2, 1008.1, 8, 8, 22.7, 21.6, 'Yes', 'Yes'), ('1/29/2013', 19.3, 26.2, 95.2, 4.8, 4.5, 'E', 70, 'WNW', 'SSE', 11, 24, 93, 71, 1001.7, 1004.9, 8, 6, 21.5, 24.0, 'Yes', 'No'), ('1/30/2013', 19.8, 26.0, 0.8, 5.6, 8.5, 'ESE', 28, 'SE', 'ESE', 11, 20, 70, 58, 1014.7, 1014.0, 5, 2, 22.2, 24.9, 'No', 'No'), ('1/31/2013', 21.0, 27.8, 0.0, 5.6, 12.2, 'NE', 54, 'N', 'NE', 19, 24, 66, 64, 1013.2, 1008.4, 3, 1, 25.9, 27.2, 'No', 'Yes'), ('3/1/2013', 16.5, 20.1, 31.8, 6.8, 0.0, 'SSE', 63, 'SE', 'SSE', 26, 26, 86, 85, 1014.4, 1016.2, 8, 8, 19.5, 18.7, 'Yes', 'Yes'), ('3/2/2013', 17.9, 23.1, 15.2, 6.2, 0.1, 'SSE', 57, 'SE', 'SSE', 30, 31, 73, 78, 1021.0, 1020.8, 7, 8, 19.0, 20.1, 'Yes', 'Yes'), ('3/3/2013', 17.7, 25.5, 7.4, 4.8, 6.8, 'SE', 56, 'SE', 'ESE', 30, 30, 63, 56, 1021.6, 1020.4, 7, 6, 23.1, 24.8, 'Yes', 'Yes'), ('3/4/2013', 19.5, 26.1, 4.4, 6.6, 9.6, 'ESE', 39, 'E', 'ESE', 22, 22, 53, 49, 1021.9, 1020.9, 3, 3, 23.7, 25.1, 'Yes', 'No'), ('3/5/2013', 20.5, 26.8, 0.2, 6.0, 9.1, 'ENE', 35, 'E', 'ENE', 20, 28, 70, 48, 1021.7, 1020.0, 6, 3, 23.1, 25.8, 'No', 'No'), ('3/6/2013', 20.2, 27.3, 0.0, 7.4, 7.6, 'ENE', 39, 'NNW', 'ENE', 6, 24, 78, 55, 1020.9, 1018.4, 7, 3, 21.6, 25.6, 'No', 'No'), ('3/7/2013', 18.6, 27.1, 0.0, 7.4, 11.4, 'NE', 39, 'WNW', 'NE', 11, 24, 67, 52, 1019.9, 1017.4, 1, 1, 22.8, 26.3, 'No', 'No'), ('3/8/2013', 20.3, 26.8, 0.0, 7.8, 6.1, 'E', 31, 'W', 'E', 9, 20, 67, 57, 1022.1, 1020.5, 4, 4, 22.4, 26.2, 'No', 'No'), ('3/9/2013', 21.2, 27.2, 0.6, 6.8, 6.6, 'ENE', 39, 'W', 'ENE', 13, 24, 75, 53, 1021.3, 1019.0, 5, 3, 22.5, 26.0, 'No', 'No'), ('3/10/2013', 19.6, 28.0, 0.0, 7.4, 9.8, 'ENE', 35, 'W', 'ENE', 7, 20, 67, 49, 1020.1, 1017.5, 5, 5, 22.3, 25.5, 'No', 'No'), ('3/11/2013', 20.7, 27.4, 0.0, 7.8, 9.3, 'ENE', 35, 'W', 'E', 9, 26, 72, 64, 1020.7, 1019.6, 5, 5, 23.2, 25.4, 'No', 'No'), ('3/12/2013', 20.4, 26.4, 0.0, 6.4, 7.9, 'E', 30, 'W', 'E', 13, 19, 78, 58, 1021.0, 1018.4, 7, 2, 21.9, 25.7, 'No', 'No'), ('3/13/2013', 18.3, 28.3, 0.0, 5.4, 11.1, 'NE', 46, 'W', 'NE', 7, 26, 72, 52, 1014.5, 1010.9, 1, 1, 21.5, 26.3, 'No', 'No'), ('3/14/2013', 20.8, 24.3, 0.0, 7.8, 1.3, 'SSW', 43, 'SSE', 'SSW', 7, 11, 72, 68, 1012.0, 1011.2, 6, 7, 23.1, 24.0, 'No', 'No'), ('3/15/2013', 19.7, 25.0, 1.0, 2.6, 2.0, 'SSW', 43, 'SSW', 'SSW', 24, 26, 78, 70, 1016.1, 1015.7, 7, 7, 20.8, 22.5, 'No', 'No'), ('3/16/2013', 20.1, 28.7, 0.2, 4.2, 10.7, 'E', 31, 'N', 'E', 11, 20, 70, 65, 1013.6, 1008.9, 1, 3, 23.3, 25.8, 'No', 'No'), ('3/17/2013', 18.7, 24.0, 0.0, 6.8, 10.8, 'SSW', 65, 'SSW', 'SSW', 24, 31, 48, 35, 1013.0, 1015.0, 2, 1, 19.2, 23.2, 'No', 'No'), ('3/18/2013', 13.9, 23.8, 0.0, 8.6, 10.2, 'SSW', 41, 'W', 'ESE', 20, 24, 55, 44, 1021.1, 1020.2, 2, 2, 16.8, 22.3, 'No', 'No'), ('3/19/2013', 14.3, 24.7, 0.0, 6.4, 10.7, 'ESE', 28, 'W', 'ESE', 17, 19, 66, 48, 1024.2, 1022.8, 2, 3, 16.3, 23.0, 'No', 'No'), ('3/20/2013', 16.1, 24.8, 0.0, 5.4, 9.9, 'NE', 37, 'WNW', 'E', 13, 20, 71, 53, 1025.4, 1022.3, 3, 3, 19.3, 24.5, 'No', 'No'), ('3/21/2013', 18.5, 26.3, 0.0, 6.6, 8.0, 'NNE', 54, 'NNE', 'NE', 7, 26, 60, 50, 1019.4, 1014.3, 2, 7, 21.1, 25.0, 'No', 'No'), ('3/22/2013', 21.1, 31.8, 0.0, 6.8, 4.4, 'NW', 59, 'NNW', 'NNW', 20, 20, 56, 41, 1013.5, 1011.0, 6, 7, 26.1, 31.5, 'No', 'No'), ('3/23/2013', 21.6, 27.0, 1.0, 8.4, 8.5, 'ESE', 30, 'ESE', 'E', 4, 24, 73, 73, 1016.5, 1013.7, 4, 5, 24.2, 24.0, 'No', 'No'), ('3/24/2013', 20.6, 28.4, 0.8, 4.8, 10.5, 'E', 28, 'WNW', 'E', 9, 17, 71, 65, 1015.9, 1011.5, 1, 1, 22.6, 26.4, 'No', 'No'), ('3/25/2013', 17.9, 30.0, 0.0, 7.0, 11.0, 'S', 30, 'WNW', 'S', 19, 13, 57, 49, 1018.3, 1017.5, 1, 2, 21.8, 29.5, 'No', 'No'), ('3/26/2013', 20.6, 26.9, 0.0, 4.4, 4.3, 'ENE', 39, 'WNW', 'ENE', 9, 24, 83, 73, 1019.4, 1016.3, 7, 7, 21.7, 25.5, 'No', 'No'), ('3/27/2013', 20.8, 27.7, 0.0, 5.4, 10.8, 'NNE', 48, 'W', 'ENE', 0, 22, 75, 64, 1019.0, 1015.7, 1, 1, 23.4, 26.7, 'No', 'No'), ('3/28/2013', 21.5, 33.5, 0.0, 7.0, 7.3, 'W', 37, 'E', 'E', 2, 11, 71, 34, 1016.8, 1012.1, 1, 7, 23.4, 30.9, 'No', 'Yes'), ('3/29/2013', 16.7, 22.3, 3.0, 8.0, 8.3, 'SSE', 44, 'SW', 'SSE', 22, 20, 48, 48, 1018.5, 1017.7, 1, 7, 19.2, 20.9, 'Yes', 'No'), ('3/30/2013', 14.8, 23.6, 0.0, 5.2, 10.6, 'NE', 35, 'W', 'ENE', 13, 24, 62, 53, 1017.6, 1012.8, 1, 6, 18.7, 22.6, 'No', 'No'), ('3/31/2013', 17.9, 25.4, 0.0, 5.0, 7.3, 'SSE', 44, 'WSW', 'S', 13, 28, 78, 38, 1011.4, 1010.8, 7, 6, 18.3, 24.4, 'No', 'Yes'), ('4/1/2013', 17.4, 24.3, 2.8, 6.6, 5.8, 'W', 26, 'WSW', 'E', 13, 17, 83, 56, 1017.9, 1015.5, 6, 3, 18.6, 23.5, 'Yes', 'No'), ('4/2/2013', 16.3, 26.2, 0.0, 3.8, 10.9, 'SW', 39, 'W', 'ESE', 19, 19, 67, 41, 1016.0, 1013.8, 0, 2, 19.0, 25.4, 'No', 'Yes'), ('4/3/2013', 17.0, 18.6, 27.4, 6.6, 0.0, 'S', 48, 'S', 'S', 22, 20, 88, 79, 1020.9, 1021.7, 7, 8, 17.0, 18.0, 'Yes', 'Yes'), ('4/4/2013', 15.7, 20.9, 61.4, 5.0, 0.4, 'SSW', 31, 'SE', 'SE', 17, 9, 93, 89, 1028.2, 1027.8, 8, 8, 16.6, 17.7, 'Yes', 'Yes'), ('4/5/2013', 15.6, 23.6, 18.4, 0.8, 4.3, 'W', 24, 'WNW', 'ENE', 9, 7, 83, 55, 1030.4, 1028.4, 7, 6, 17.5, 22.9, 'Yes', 'Yes'), ('4/6/2013', 15.6, 20.6, 2.4, 3.6, 1.6, 'NE', 31, 'W', 'SE', 11, 6, 93, 75, 1028.0, 1025.2, 5, 7, 17.0, 18.8, 'Yes', 'Yes'), ('4/7/2013', 14.2, 22.7, 3.8, 2.4, 7.0, 'W', 22, 'W', 'E', 9, 15, 73, 62, 1024.5, 1021.6, 3, 3, 19.0, 22.2, 'Yes', 'Yes'), ('4/8/2013', 14.6, 24.2, 2.0, 3.4, 8.3, 'ESE', 26, 'W', 'ESE', 15, 17, 72, 61, 1025.3, 1023.9, 1, 6, 18.4, 22.5, 'Yes', 'Yes'), ('4/9/2013', 15.6, 22.0, 5.2, 2.4, 3.6, 'WNW', 24, 'WNW', 'ESE', 15, 6, 90, 73, 1026.7, 1024.3, 6, 3, 16.7, 20.7, 'Yes', 'Yes'), ('4/10/2013', 14.4, 24.1, 2.0, 2.2, 10.4, 'ENE', 30, 'WNW', 'ENE', 13, 20, 72, 57, 1024.8, 1021.3, 1, 2, 18.9, 23.0, 'Yes', 'No'), ('4/11/2013', 15.2, 25.3, 0.0, 4.6, 10.8, 'NE', 26, 'WNW', 'ENE', 13, 17, 71, 43, 1023.5, 1021.6, 1, 1, 19.0, 24.7, 'No', 'No'), ('4/12/2013', 15.6, 26.0, 0.0, 4.4, 10.3, 'ENE', 31, 'WNW', 'ENE', 13, 19, 73, 47, 1025.9, 1022.8, 1, 1, 19.7, 24.2, 'No', 'No'), ('4/13/2013', 15.7, 25.4, 0.0, 4.8, 10.7, 'NE', 35, 'W', 'NE', 17, 22, 71, 55, 1021.5, 1016.4, 1, 1, 19.6, 23.7, 'No', 'No'), ('4/14/2013', 16.1, 27.7, 0.0, 5.4, 10.6, 'W', 24, 'W', 'ENE', 17, 13, 72, 54, 1013.9, 1010.9, 2, 2, 19.0, 25.2, 'No', 'No'), ('4/15/2013', 17.4, 27.9, 0.0, 5.8, 5.7, 'S', 37, 'W', 'E', 9, 11, 75, 49, 1010.1, 1007.4, 7, 4, 19.0, 26.2, 'No', 'Yes'), ('4/16/2013', 16.9, 22.0, 7.0, 3.2, 4.4, 'SSW', 41, 'W', 'S', 17, 20, 88, 69, 1015.0, 1013.5, 8, 6, 17.2, 21.4, 'Yes', 'No'), ('4/17/2013', 14.2, 23.6, 0.0, 4.0, 7.7, 'SSE', 30, 'WNW', 'SSE', 13, 17, 75, 65, 1016.7, 1014.0, 1, 7, 17.7, 21.9, 'No', 'No'), ('4/18/2013', 15.4, 24.5, 0.2, 2.6, 9.1, 'S', 41, 'WNW', 'SSE', 15, 26, 76, 69, 1014.7, 1012.5, 1, 6, 18.5, 21.4, 'No', 'No'), ('4/19/2013', 13.3, 20.2, 0.4, 4.6, 10.5, 'SW', 65, 'WSW', 'SSW', 20, 35, 50, 39, 1014.7, 1012.8, 2, 4, 15.3, 20.0, 'No', 'Yes'), ('4/20/2013', 12.2, 19.0, 33.6, 4.8, 1.2, 'SE', 65, 'S', 'SSE', 17, 30, 92, 68, 1013.7, 1014.1, 8, 7, 14.6, 17.5, 'Yes', 'Yes'), ('4/21/2013', 10.9, 22.2, 32.8, 2.8, 9.7, 'W', 33, 'W', 'ESE', 15, 15, 71, 56, 1016.1, 1012.4, 1, 1, 14.4, 20.0, 'Yes', 'No'), ('4/22/2013', 13.9, 24.7, 0.2, 2.6, 8.1, 'WSW', 41, 'WNW', 'W', 13, 11, 85, 39, 1011.0, 1006.9, 6, 2, 14.6, 24.2, 'No', 'No'), ('4/23/2013', 12.7, 25.3, 0.2, 3.6, 10.4, 'WSW', 43, 'W', 'ESE', 15, 15, 57, 43, 1012.7, 1011.7, 1, 2, 16.9, 23.4, 'No', 'No'), ('4/24/2013', 12.3, 23.8, 0.0, 3.6, 10.8, 'W', 35, 'W', 'ESE', 20, 13, 62, 27, 1018.9, 1015.9, 1, 1, 15.5, 23.4, 'No', 'No'), ('4/25/2013', 12.5, 23.2, 0.0, 4.8, 10.1, 'W', 33, 'W', 'ESE', 20, 17, 52, 45, 1021.8, 1019.5, 2, 1, 15.1, 20.3, 'No', 'No'), ('4/26/2013', 14.0, 27.2, 0.0, 3.4, 10.7, 'W', 41, 'W', 'SW', 17, 13, 56, 30, 1022.6, 1019.1, 1, 0, 17.3, 25.9, 'No', 'No'), ('4/27/2013', 14.0, 26.3, 0.0, 4.4, 9.5, 'ENE', 26, 'W', 'ENE', 17, 19, 65, 51, 1022.0, 1017.7, 1, 1, 17.2, 22.6, 'No', 'No'), ('4/28/2013', 14.4, 28.7, 0.0, 4.6, 10.1, 'WNW', 28, 'W', 'WNW', 7, 15, 59, 29, 1019.0, 1016.0, 1, 1, 18.6, 28.1, 'No', 'No'), ('4/29/2013', 15.9, 26.5, 0.0, 6.2, 9.3, 'WNW', 26, 'WNW', 'ESE', 13, 13, 59, 73, 1022.4, 1020.9, 1, 3, 18.5, 22.6, 'No', 'No'), ('4/30/2013', 18.4, 22.7, 0.0, 2.8, 4.0, 'SSW', 35, 'SSW', 'SSE', 15, 19, 80, 71, 1025.6, 1022.4, 7, 7, 19.7, 20.5, 'No', 'No'), ('5/1/2013', 16.9, 25.0, 0.0, 1.2, 7.4, 'S', 37, 'WNW', 'SE', 15, 17, 86, 61, 1018.7, 1014.3, 7, 5, 18.1, 24.2, 'No', 'No'), ('5/2/2013', 14.4, 20.3, 0.0, 5.6, 7.4, 'S', 46, 'W', 'S', 13, 20, 53, 51, 1025.3, 1025.2, 1, 4, 15.1, 18.7, 'No', 'No'), ('5/3/2013', 11.1, 22.9, 0.0, 3.0, 10.2, 'N', 31, 'WNW', 'ENE', 19, 19, 72, 51, 1026.7, 1020.5, 1, 7, 14.0, 20.9, 'No', 'No'), ('5/4/2013', 14.0, 26.4, 0.0, 4.4, 6.2, 'SSE', 56, 'W', 'SSE', 19, 37, 50, 56, 1017.9, 1018.5, 7, 3, 17.4, 20.2, 'No', 'No'), ('5/5/2013', 12.7, 20.1, 0.0, 6.4, 9.1, 'SSE', 37, 'W', 'S', 15, 7, 56, 38, 1025.1, 1022.1, 6, 1, 14.5, 19.7, 'No', 'No'), ('5/6/2013', 10.8, 20.1, 0.0, 3.4, 8.2, 'SSW', 35, 'W', 'S', 13, 17, 68, 60, 1026.6, 1024.5, 3, 7, 14.3, 19.2, 'No', 'No'), ('5/7/2013', 11.7, 21.5, 0.0, 3.0, 8.8, 'ESE', 31, 'W', 'SSE', 13, 19, 76, 55, 1028.7, 1027.1, 2, 6, 15.2, 19.9, 'No', 'No'), ('5/8/2013', 12.4, 21.6, 0.0, 3.4, 5.3, 'WNW', 22, 'W', 'E', 13, 9, 80, 51, 1031.1, 1028.1, 7, 4, 15.2, 21.2, 'No', 'No'), ('5/9/2013', 12.1, 23.2, 0.0, 1.8, 10.2, 'W', 24, 'W', 'ENE', 17, 13, 79, 54, 1030.7, 1027.4, 1, 1, 14.7, 22.0, 'No', 'No'), ('5/10/2013', 12.5, 23.5, 0.0, 3.6, 10.0, 'W', 26, 'W', 'SE', 20, 13, 77, 53, 1030.8, 1028.4, 1, 1, 14.3, 22.9, 'No', 'No'), ('5/11/2013', 13.0, 22.1, 0.0, 2.0, 4.3, 'ENE', 31, 'W', 'ENE', 22, 22, 77, 69, 1030.2, 1027.5, 5, 6, 15.2, 20.8, 'No', 'No'), ('5/12/2013', 14.0, 22.1, 0.0, 3.6, 7.0, 'ENE', 28, 'W', 'ENE', 13, 13, 93, 59, 1027.2, 1022.7, 8, 2, 14.3, 21.4, 'No', 'No'), ('5/13/2013', 13.7, 22.8, 0.0, 2.0, 1.8, 'NNW', 28, 'W', 'NNE', 9, 11, 88, 53, 1018.9, 1014.2, 7, 8, 14.4, 21.9, 'No', 'No'), ('5/14/2013', 14.2, 21.3, 0.0, 2.4, 6.9, 'W', 41, 'W', 'SE', 20, 13, 60, 31, 1013.8, 1011.1, 7, 6, 14.2, 20.0, 'No', 'No'), ('5/15/2013', 9.2, 20.6, 0.2, 2.8, 9.8, 'W', 46, 'W', 'WNW', 15, 28, 59, 34, 1013.2, 1009.6, 1, 3, 13.6, 20.1, 'No', 'No'), ('5/16/2013', 13.6, 20.6, 0.0, 5.4, 8.3, 'W', 50, 'NNW', 'W', 22, 31, 55, 36, 1010.3, 1007.3, 2, 3, 16.9, 19.4, 'No', 'No'), ('5/17/2013', 12.2, 19.6, 0.0, 4.6, 10.1, 'WSW', 57, 'WSW', 'WSW', 24, 28, 50, 33, 1011.9, 1010.4, 1, 1, 14.7, 18.6, 'No', 'No'), ('5/18/2013', 11.1, 20.6, 0.0, 3.8, 10.1, 'WSW', 41, 'W', 'W', 17, 22, 53, 31, 1014.7, 1011.8, 1, 1, 13.2, 19.1, 'No', 'No'), ('5/19/2013', 9.8, 20.2, 0.0, 3.6, 9.1, 'W', 39, 'W', 'W', 20, 20, 54, 30, 1016.8, 1014.1, 2, 1, 12.1, 19.0, 'No', 'No'), ('5/20/2013', 10.1, 20.7, 0.0, 4.0, 8.5, 'W', 44, 'W', 'WSW', 19, 22, 61, 37, 1018.7, 1014.7, 4, 3, 11.3, 19.6, 'No', 'No'), ('5/21/2013', 10.1, 22.5, 0.0, 4.0, 9.1, 'W', 54, 'W', 'SW', 22, 20, 55, 32, 1015.3, 1012.3, 3, 7, 15.4, 21.8, 'No', 'No'), ('5/22/2013', 9.4, 16.0, 0.0, 2.2, 1.3, 'WNW', 31, 'WNW', 'SSW', 17, 20, 71, 79, 1015.0, 1010.1, 6, 8, 11.2, 14.5, 'No', 'Yes'), ('5/23/2013', 10.6, 17.4, 27.2, 5.2, 0.7, 'SSE', 48, 'WSW', 'SE', 11, 22, 93, 71, 1013.7, 1012.7, 7, 6, 13.4, 16.4, 'Yes', 'Yes'), ('5/24/2013', 12.7, 20.6, 30.6, 2.4, 5.8, 'SE', 48, 'W', 'SSE', 28, 24, 89, 47, 1019.1, 1017.9, 7, 7, 13.0, 20.1, 'Yes', 'Yes'), ('5/25/2013', 10.6, 21.3, 20.0, 3.8, 9.4, 'W', 41, 'W', 'SSE', 22, 15, 83, 50, 1023.7, 1022.1, 1, 1, 12.2, 20.8, 'Yes', 'No'), ('5/26/2013', 9.5, 21.3, 0.0, 1.8, 10.1, 'W', 30, 'W', 'NE', 20, 4, 70, 45, 1025.7, 1023.0, 1, 1, 11.3, 20.2, 'No', 'Yes'), ('5/27/2013', 10.6, 20.2, 3.4, 3.2, 7.1, 'SSW', 41, 'W', 'SSE', 22, 24, 84, 58, 1029.4, 1028.2, 5, 5, 11.6, 19.4, 'Yes', 'Yes'), ('5/28/2013', 11.6, 19.3, 28.6, 1.2, 3.2, 'ENE', 30, 'WNW', 'E', 11, 15, 94, 75, 1032.8, 1030.2, 8, 8, 12.9, 17.8, 'Yes', 'No'), ('5/29/2013', 11.3, 21.1, 0.2, 2.0, 4.9, 'W', 20, 'W', 'ENE', 15, 15, 94, 60, 1031.4, 1027.8, 8, 3, 12.3, 20.6, 'No', 'No'), ('5/30/2013', 11.7, 21.4, 0.0, 2.6, 5.7, 'E', 24, 'WNW', 'ENE', 15, 7, 90, 67, 1029.3, 1025.9, 4, 5, 12.8, 20.0, 'No', 'No'), ('5/31/2013', 11.8, 24.9, 0.0, 1.6, 9.1, 'W', 41, 'W', 'NNE', 9, 13, 84, 40, 1028.0, 1023.8, 1, 5, 13.9, 24.1, 'No', 'No'), ('6/1/2013', 13.9, 21.2, 0.0, 4.0, 3.0, 'NW', 52, 'N', 'N', 11, 17, 62, 61, 1019.4, 1014.1, 6, 7, 18.7, 19.9, 'No', 'Yes'), ('6/2/2013', 14.4, 15.8, 14.8, 3.0, 1.8, 'S', 81, 'W', 'SW', 20, 24, 92, 68, 1006.1, 1009.8, 8, 7, 14.7, 14.0, 'Yes', 'Yes'), ('6/3/2013', 9.9, 19.5, 34.4, 4.6, 9.7, 'W', 41, 'W', 'SSE', 24, 13, 57, 44, 1020.5, 1018.9, 1, 1, 11.7, 19.1, 'Yes', 'No'), ('6/4/2013', 10.3, 21.1, 0.0, 3.6, 9.3, 'W', 41, 'W', 'S', 24, 9, 66, 53, 1026.3, 1023.8, 3, 1, 12.2, 20.7, 'No', 'No'), ('6/5/2013', 10.5, 19.3, 0.0, 3.4, 2.3, 'W', 26, 'WNW', 'ENE', 7, 13, 87, 70, 1025.8, 1021.6, 8, 7, 11.7, 18.3, 'No', 'No'), ('6/6/2013', 11.7, 20.1, 0.0, 1.6, 2.3, 'NNW', 26, 'W', 'NNE', 15, 6, 61, 59, 1022.8, 1020.0, 7, 8, 14.9, 19.2, 'No', 'No'), ('6/7/2013', 14.9, 22.2, 0.0, 2.0, 1.8, 'SSE', 41, 'NNW', 'SSW', 20, 15, 70, 55, 1019.8, 1018.5, 8, 6, 18.5, 21.6, 'No', 'No'), ('6/8/2013', 13.5, 19.2, 0.0, 3.0, 1.5, 'SSE', 43, 'W', 'SE', 19, 11, 73, 53, 1030.7, 1028.6, 7, 7, 14.2, 17.5, 'No', 'No'), ('6/9/2013', 11.0, 18.9, 0.0, 7.0, 6.9, 'ENE', 26, 'W', 'ENE', 13, 15, 80, 63, 1028.6, 1024.3, 4, 7, 12.6, 18.4, 'No', 'No'), ('6/10/2013', 10.5, 21.5, 0.0, 1.4, 3.9, 'NNW', 28, 'W', 'WNW', 13, 17, 90, 67, 1021.6, 1018.7, 2, 8, 11.1, 18.5, 'No', 'No'), ('6/11/2013', 10.5, 19.6, 0.8, 0.2, 8.5, 'W', 30, 'W', 'WNW', 17, 9, 94, 54, 1021.0, 1017.6, 3, 6, 11.3, 18.4, 'No', 'No'), ('6/12/2013', 10.4, 16.0, 0.0, 2.0, 1.0, 'W', 41, 'WNW', 'W', 13, 19, 85, 90, 1015.1, 1009.7, 7, 6, 11.6, 15.8, 'No', 'Yes'), ('6/13/2013', 10.6, 20.9, 8.4, 0.6, 8.6, 'NW', 48, 'WNW', 'WNW', 15, 20, 89, 45, 1007.0, 1004.3, 3, 3, 13.4, 20.1, 'Yes', 'No'), ('6/14/2013', 11.7, 20.1, 0.0, 3.6, 7.0, 'W', 46, 'NNW', 'WSW', 17, 22, 64, 46, 1005.2, 1002.9, 2, 6, 14.0, 18.5, 'No', 'No'), ('6/15/2013', 13.0, 17.6, 0.0, 4.0, 5.0, 'WSW', 43, 'WSW', 'SSW', 24, 11, 58, 46, 1009.9, 1009.9, 4, 7, 13.8, 17.3, 'No', 'No'), ('6/16/2013', 9.7, 19.1, 0.0, 3.2, 9.5, 'W', 41, 'W', 'S', 24, 15, 59, 50, 1014.4, 1011.6, 2, 4, 11.8, 16.6, 'No', 'No'), ('6/17/2013', 8.5, 17.7, 0.0, 3.8, 3.8, 'S', 44, 'W', 'SW', 26, 17, 65, 56, 1009.5, 1008.3, 6, 6, 11.0, 15.7, 'No', 'No'), ('6/18/2013', 8.0, 19.2, 0.0, 1.6, 8.0, 'S', 43, 'W', 'S', 26, 17, 76, 52, 1013.5, 1012.2, 1, 2, 9.6, 16.1, 'No', 'Yes'), ('6/19/2013', 8.7, 16.1, 15.6, 3.2, 0.0, 'S', 52, 'W', 'SSW', 24, 26, 80, 65, 1021.7, 1021.3, 6, 7, 10.5, 14.3, 'Yes', 'Yes'), ('6/20/2013', 8.7, 16.6, 1.4, 2.8, 7.2, 'SSW', 39, 'W', 'SSW', 26, 20, 71, 57, 1024.2, 1021.0, 3, 6, 9.9, 15.6, 'Yes', 'No'), ('6/21/2013', 8.0, 17.3, 0.0, 2.0, 8.1, 'W', 31, 'W', 'SSW', 19, 15, 79, 58, 1021.6, 1019.1, 5, 2, 9.6, 16.1, 'No', 'Yes'), ('6/22/2013', 7.7, 13.5, 1.2, 2.4, 0.0, 'SE', 39, 'W', 'SSW', 26, 17, 87, 83, 1024.9, 1024.2, 7, 7, 7.9, 11.9, 'Yes', 'Yes'), ('6/23/2013', 7.6, 13.9, 56.2, 0.4, 0.2, 'SSE', 41, 'WNW', 'SSW', 7, 19, 93, 90, 1028.5, 1026.7, 7, 7, 11.0, 11.9, 'Yes', 'Yes'), ('6/24/2013', 9.6, 13.8, 53.4, 0.2, 0.1, 'W', 39, 'W', 'WNW', 17, 11, 91, 77, 1021.7, 1017.9, 7, 7, 10.2, 13.1, 'Yes', 'Yes'), ('6/25/2013', 10.0, 16.7, 5.0, 2.4, 0.2, 'SSE', 41, 'W', 'W', 17, 9, 93, 90, 1016.3, 1014.8, 8, 6, 10.6, 13.8, 'Yes', 'Yes'), ('6/26/2013', 10.5, 19.8, 15.6, 1.4, 4.3, 'SSE', 52, 'SE', 'SE', 31, 20, 84, 63, 1019.8, 1020.0, 7, 7, 16.7, 19.2, 'Yes', 'No'), ('6/27/2013', 12.8, 18.8, 0.8, 3.4, 2.4, 'WNW', 26, 'W', 'ESE', 15, 19, 93, 64, 1022.9, 1020.7, 7, 7, 13.4, 17.6, 'No', 'Yes'), ('6/28/2013', 12.9, 16.1, 16.8, 2.8, 0.0, 'ESE', 41, 'W', 'ENE', 9, 15, 93, 83, 1023.7, 1022.5, 7, 7, 13.3, 16.0, 'Yes', 'Yes'), ('6/29/2013', 12.7, 14.2, 41.0, 3.2, 0.0, 'E', 28, 'SSE', 'SSE', 9, 9, 90, 87, 1024.8, 1023.0, 8, 8, 13.6, 13.2, 'Yes', 'Yes'), ('6/30/2013', 11.3, 17.1, 51.0, 2.0, 2.2, 'SE', 37, 'W', 'SSW', 11, 9, 94, 82, 1025.7, 1023.5, 7, 5, 12.4, 16.6, 'Yes', 'Yes'), ('7/1/2013', 8.8, 20.1, 9.8, 0.8, 9.8, 'W', 26, 'W', 'E', 20, 7, 89, 56, 1024.4, 1021.9, 1, 1, 10.3, 18.5, 'Yes', 'No'), ('7/2/2013', 8.8, 19.9, 0.0, 2.2, 9.8, 'W', 33, 'W', 'WNW', 20, 4, 77, 46, 1024.9, 1021.0, 1, 2, 10.2, 18.9, 'No', 'No'), ('7/3/2013', 8.1, 19.8, 0.0, 2.2, 9.5, 'W', 26, 'WNW', 'NNE', 19, 13, 82, 53, 1024.4, 1020.8, 1, 0, 9.5, 19.2, 'No', 'No'), ('7/4/2013', 8.5, 23.4, 0.0, 2.6, 9.8, 'NW', 43, 'NNW', 'NNW', 17, 22, 57, 38, 1016.3, 1011.5, 0, 1, 14.7, 22.6, 'No', 'No'), ('7/5/2013', 14.7, 19.5, 0.0, 4.0, 9.7, 'W', 65, 'NW', 'W', 20, 33, 54, 30, 1010.9, 1010.8, 1, 1, 16.0, 18.5, 'No', 'No'), ('7/6/2013', 7.8, 17.4, 0.0, 4.2, 9.8, 'WSW', 37, 'WNW', 'WNW', 13, 19, 57, 31, 1020.1, 1018.1, 0, 0, 10.2, 17.1, 'No', 'No'), ('7/7/2013', 7.4, 19.1, 0.0, 4.0, 9.5, 'W', 35, 'W', 'WSW', 19, 11, 62, 35, 1026.9, 1025.6, 1, 1, 10.0, 17.7, 'No', 'No'), ('7/8/2013', 7.4, 19.2, 0.0, 2.2, 9.1, 'W', 33, 'W', 'SSE', 19, 17, 68, 36, 1031.7, 1029.9, 0, 3, 9.3, 17.7, 'No', 'Yes'), ('7/9/2013', 8.7, 13.6, 1.6, 3.0, 1.0, 'W', 30, 'W', 'SSW', 19, 17, 83, 84, 1035.0, 1033.6, 5, 7, 9.3, 11.8, 'Yes', 'Yes'), ('7/10/2013', 8.9, 15.9, 8.0, 1.2, 2.7, 'W', 24, 'W', 'SSE', 17, 13, 84, 71, 1033.5, 1031.6, 7, 6, 10.3, 14.8, 'Yes', 'No'), ('7/11/2013', 8.2, 18.4, 0.0, 1.2, 8.2, 'W', 30, 'W', 'E', 20, 9, 91, 62, 1035.3, 1032.2, 2, 5, 9.1, 17.0, 'No', 'No'), ('7/12/2013', 8.3, 20.2, 0.2, 1.2, 8.4, 'W', 30, 'W', 'WNW', 17, 6, 92, 46, 1031.1, 1027.1, 1, 1, 9.6, 19.2, 'No', 'No'), ('7/13/2013', 8.3, 17.4, 0.0, 3.0, 5.0, 'WNW', 26, 'W', 'E', 15, 2, 85, 61, 1029.2, 1027.3, 7, 6, 10.9, 17.3, 'No', 'No'), ('7/14/2013', 8.9, 18.4, 0.0, 1.0, 8.5, 'W', 24, 'W', 'NE', 11, 15, 88, 60, 1028.4, 1025.4, 4, 8, 10.7, 17.5, 'No', 'No'), ('7/15/2013', 10.7, 22.0, 0.2, 3.6, 1.7, 'NNW', 33, 'NW', 'NNW', 4, 13, 78, 58, 1024.6, 1021.9, 7, 7, 15.4, 19.4, 'No', 'Yes'), ('7/16/2013', 14.4, 21.6, 1.4, 0.2, 3.4, 'NW', 26, 'W', 'NE', 9, 13, 88, 67, 1024.7, 1022.1, 7, 4, 15.1, 19.6, 'Yes', 'Yes'), ('7/17/2013', 13.0, 24.3, 4.8, 1.8, 8.7, 'NE', 22, 'W', 'E', 9, 9, 85, 48, 1023.8, 1020.6, 4, 3, 14.5, 23.0, 'Yes', 'No'), ('7/18/2013', 13.3, 22.6, 0.0, 2.4, 3.9, 'NNE', 30, 'W', 'NE', 7, 13, 85, 72, 1022.9, 1019.4, 7, 7, 15.1, 19.4, 'No', 'No'), ('7/19/2013', 15.0, 20.4, 0.0, 3.2, 1.6, 'NNW', 57, 'NE', 'N', 15, 17, 66, 73, 1015.7, 1011.7, 4, 7, 18.1, 17.5, 'No', 'No'), ('7/20/2013', 14.5, 20.4, 0.8, 2.4, 8.9, 'NNW', 48, 'N', 'NW', 17, 26, 65, 38, 1009.3, 1005.4, 2, 2, 16.5, 19.8, 'No', 'No'), ('7/21/2013', 8.5, 16.3, 0.2, 6.4, 10.1, 'NW', 54, 'NW', 'WNW', 24, 31, 49, 29, 1016.0, 1013.2, 1, 1, 11.0, 16.0, 'No', 'No'), ('7/22/2013', 8.7, 17.2, 0.0, 3.8, 9.9, 'WNW', 54, 'WNW', 'W', 17, 26, 54, 28, 1019.4, 1016.3, 2, 2, 12.2, 16.6, 'No', 'No'), ('7/23/2013', 7.1, 17.7, 0.0, 3.2, 8.0, 'WSW', 44, 'W', 'WSW', 17, 19, 60, 42, 1019.9, 1018.5, 1, 7, 11.0, 15.9, 'No', 'No'), ('7/24/2013', 10.1, 17.0, 0.0, 4.0, 4.8, 'SSW', 48, 'WSW', 'SSW', 17, 20, 61, 46, 1026.6, 1026.4, 1, 6, 12.3, 16.6, 'No', 'No'), ('7/25/2013', 7.4, 19.6, 0.0, 3.0, 8.6, 'WNW', 33, 'W', 'E', 20, 9, 72, 38, 1029.8, 1026.6, 1, 3, 8.8, 17.9, 'No', 'No'), ('7/26/2013', 7.9, 20.3, 0.0, 3.4, 9.3, 'WNW', 22, 'WNW', 'WNW', 15, 7, 75, 32, 1025.9, 1023.3, 5, 1, 9.2, 19.5, 'No', 'No'), ('7/27/2013', 7.4, 18.7, 0.0, 1.8, 9.9, 'W', 28, 'W', 'E', 22, 15, 62, 56, 1031.0, 1028.2, 1, 1, 9.4, 17.8, 'No', 'No'), ('7/28/2013', 8.3, 18.8, 0.0, 3.6, 6.8, 'NNE', 26, 'WNW', 'E', 7, 17, 84, 64, 1029.8, 1025.8, 6, 6, 9.7, 18.1, 'No', 'No'), ('7/29/2013', 9.7, 24.0, 0.0, 2.6, 10.2, 'NNW', 37, 'N', 'N', 22, 11, 53, 35, 1025.2, 1020.8, 6, 1, 17.6, 23.3, 'No', 'No'), ('7/30/2013', 11.1, 21.5, 0.0, 3.4, 3.4, 'SSW', 48, 'W', 'ENE', 13, 6, 73, 49, 1019.9, 1017.8, 6, 5, 12.8, 19.7, 'No', 'Yes'), ('7/31/2013', 12.6, 18.4, 5.6, 2.6, 8.1, 'S', 43, 'SSW', 'S', 20, 22, 82, 61, 1023.9, 1022.7, 7, 4, 13.9, 17.0, 'Yes', 'No'), ('8/1/2013', 8.1, 19.6, 0.0, 3.4, 10.1, 'W', 30, 'WNW', 'ESE', 24, 15, 71, 54, 1023.3, 1020.1, 2, 3, 11.0, 17.5, 'No', 'No'), ('8/2/2013', 9.1, 20.3, 0.0, 2.2, 6.8, 'W', 31, 'W', 'W', 15, 19, 83, 31, 1018.0, 1012.7, 7, 3, 10.9, 19.7, 'No', 'No'), ('8/3/2013', 10.4, 19.6, 0.0, 3.6, 10.0, 'NW', 37, 'W', 'W', 7, 4, 51, 29, 1016.0, 1012.1, 4, 1, 13.5, 19.2, 'No', 'No'), ('8/4/2013', 10.9, 19.9, 0.0, 4.2, 8.5, 'WSW', 44, 'NW', 'WSW', 9, 24, 54, 29, 1013.6, 1012.2, 6, 5, 14.0, 18.0, 'No', 'No'), ('8/5/2013', 9.5, 21.0, 0.0, 3.8, 10.0, 'WNW', 50, 'WNW', 'WNW', 11, 15, 52, 34, 1017.6, 1013.6, 1, 2, 13.1, 20.4, 'No', 'No'), ('8/6/2013', 11.9, 23.9, 0.0, 5.6, 8.7, 'NNW', 52, 'NW', 'WNW', 20, 17, 48, 30, 1011.9, 1008.0, 5, 5, 16.4, 22.1, 'No', 'No'), ('8/7/2013', 10.8, 17.9, 0.8, 4.8, 8.3, 'WSW', 35, 'W', 'ESE', 17, 15, 57, 49, 1013.6, 1009.3, 2, 7, 13.0, 16.0, 'No', 'Yes'), ('8/8/2013', 9.3, 13.1, 9.6, 3.8, 1.3, 'SSW', 57, 'W', 'SSW', 24, 24, 85, 74, 1008.3, 1009.8, 7, 7, 9.3, 12.6, 'Yes', 'Yes'), ('8/9/2013', 7.0, 17.4, 4.2, 0.6, 6.7, 'W', 35, 'W', 'NW', 20, 9, 60, 43, 1018.9, 1014.0, 4, 7, 11.2, 17.1, 'Yes', 'No'), ('8/10/2013', 10.5, 23.5, 0.0, 4.0, 10.6, 'W', 31, 'W', 'NW', 11, 11, 46, 33, 1016.0, 1013.4, 0, 1, 13.4, 23.5, 'No', 'No'), ('8/11/2013', 9.0, 21.8, 0.0, 3.8, 10.4, 'WSW', 31, 'WNW', 'E', 13, 11, 61, 38, 1018.2, 1013.5, 1, 1, 12.7, 19.2, 'No', 'No'), ('8/12/2013', 12.0, 24.4, 0.2, 3.8, 5.4, 'W', 94, 'N', 'W', 9, 48, 40, 40, 1005.8, 1004.2, 3, 7, 19.6, 18.9, 'No', 'No'), ('8/13/2013', 9.6, 22.8, 0.0, 5.8, 10.8, 'W', 35, 'NNW', 'WNW', 13, 9, 35, 25, 1013.7, 1012.2, 1, 1, 14.5, 22.2, 'No', 'No'), ('8/14/2013', 12.5, 24.1, 0.0, 4.2, 10.7, 'NNW', 39, 'NNW', 'WNW', 24, 17, 39, 22, 1013.6, 1007.7, 2, 1, 15.9, 23.9, 'No', 'No'), ('8/15/2013', 10.5, 18.7, 0.0, 8.0, 10.7, 'W', 57, 'WSW', 'S', 24, 19, 42, 29, 1019.0, 1019.8, 1, 1, 12.3, 17.7, 'No', 'No'), ('8/16/2013', 7.3, 20.6, 0.0, 3.6, 10.7, 'NE', 41, 'WNW', 'ENE', 17, 26, 61, 36, 1023.7, 1016.9, 0, 0, 10.8, 19.1, 'No', 'No'), ('8/17/2013', 10.7, 24.4, 0.0, 6.2, 10.5, 'WNW', 57, 'NNE', 'W', 20, 26, 41, 34, 1010.1, 1006.7, 1, 4, 17.6, 22.6, 'No', 'No'), ('8/18/2013', 11.3, 23.3, 0.0, 6.6, 10.7, 'WNW', 39, 'NW', 'NNW', 15, 20, 38, 28, 1016.9, 1011.9, 0, 1, 16.2, 22.8, 'No', 'No'), ('8/19/2013', 13.6, 20.9, 0.0, 7.8, 9.9, 'W', 59, 'N', 'WNW', 7, 39, 33, 25, 1009.7, 1007.0, 2, 5, 17.0, 19.8, 'No', 'No'), ('8/20/2013', 8.4, 16.6, 0.0, 6.2, 10.8, 'WSW', 56, 'WSW', 'WSW', 26, 22, 43, 26, 1013.7, 1011.9, 1, 1, 10.7, 15.4, 'No', 'No'), ('8/21/2013', 7.6, 18.1, 0.0, 3.0, 10.3, 'W', 50, 'W', 'W', 20, 20, 50, 30, 1016.3, 1013.4, 2, 3, 11.3, 17.5, 'No', 'No'), ('8/22/2013', 7.6, 18.1, 0.0, 5.6, 6.7, 'W', 50, 'N', 'WNW', 19, 24, 48, 32, 1013.8, 1010.2, 7, 7, 12.5, 17.7, 'No', 'No'), ('8/23/2013', 11.8, 18.6, 0.0, 4.0, 2.5, 'WNW', 56, 'NW', 'WNW', 20, 28, 50, 42, 1010.2, 1008.5, 7, 7, 14.8, 17.4, 'No', 'No'), ('8/24/2013', 12.2, 22.7, 0.0, 4.0, 10.8, 'W', 35, 'WSW', 'ESE', 26, 19, 52, 42, 1020.1, 1020.0, 2, 4, 15.9, 21.8, 'No', 'No'), ('8/25/2013', 9.9, 23.6, 0.0, 4.2, 10.7, 'SW', 35, 'WNW', 'E', 17, 17, 72, 53, 1024.0, 1020.4, 1, 1, 12.7, 19.6, 'No', 'No'), ('8/26/2013', 10.3, 22.0, 0.0, 3.6, 9.6, 'W', 33, 'WNW', 'WNW', 20, 11, 54, 30, 1024.6, 1020.4, 3, 6, 14.2, 21.6, 'No', 'No'), ('8/27/2013', 11.5, 21.9, 0.0, 2.2, 9.4, 'W', 24, 'W', 'ESE', 15, 15, 58, 60, 1022.0, 1018.6, 4, 2, 15.4, 19.9, 'No', 'No'), ('8/28/2013', 11.8, 23.3, 0.0, 3.0, 10.8, 'SSE', 39, 'W', 'SSE', 20, 24, 72, 38, 1021.5, 1020.2, 1, 2, 14.9, 22.1, 'No', 'No'), ('8/29/2013', 11.4, 21.8, 0.0, 3.8, 6.7, 'NNE', 56, 'WNW', 'NE', 17, 17, 69, 59, 1024.4, 1019.4, 6, 7, 15.3, 20.0, 'No', 'No'), ('8/30/2013', 15.2, 24.7, 0.0, 5.2, 10.2, 'N', 39, 'N', 'ENE', 22, 6, 46, 53, 1015.1, 1011.4, 1, 1, 21.7, 23.5, 'No', 'No'), ('8/31/2013', 14.9, 24.5, 0.0, 5.8, 8.2, 'W', 30, 'WNW', 'SE', 22, 11, 60, 34, 1021.5, 1020.0, 7, 4, 15.9, 23.6, 'No', 'No'), ('9/1/2013', 11.4, 22.2, 0.0, 4.8, 10.1, 'ENE', 26, 'WNW', 'E', 17, 20, 57, 62, 1028.5, 1026.6, 1, 1, 15.8, 20.6, 'No', 'No'), ('9/2/2013', 12.2, 22.0, 0.0, 4.0, 11.0, 'NE', 28, 'W', 'NE', 19, 17, 71, 41, 1031.2, 1029.1, 6, 2, 15.9, 21.4, 'No', 'No'), ('9/3/2013', 12.0, 21.9, 0.0, 4.2, 10.4, 'ENE', 31, 'WNW', 'ENE', 11, 20, 66, 56, 1034.0, 1031.3, 1, 1, 16.4, 21.2, 'No', 'No'), ('9/4/2013', 12.2, 21.1, 0.0, 3.8, 10.1, 'NE', 41, 'W', 'NE', 13, 20, 75, 52, 1033.6, 1028.7, 1, 1, 15.7, 20.7, 'No', 'No'), ('9/5/2013', 12.2, 28.8, 0.0, 5.8, 10.1, 'W', 28, 'W', 'WNW', 13, 11, 62, 29, 1027.3, 1023.0, 1, 5, 17.7, 28.5, 'No', 'No'), ('9/6/2013', 16.0, 23.3, 0.0, 5.0, 8.5, 'WNW', 24, 'SSW', 'E', 13, 15, 74, 70, 1026.9, 1023.1, 7, 7, 20.5, 21.2, 'No', 'No'), ('9/7/2013', 15.4, 31.1, 0.0, 3.2, 9.1, 'SSE', 39, 'W', 'ENE', 13, 15, 74, 23, 1022.4, 1018.1, 5, 4, 19.2, 29.9, 'No', 'No'), ('9/8/2013', 17.0, 21.2, 0.0, 4.6, 1.7, 'SSE', 41, 'SSE', 'ESE', 13, 13, 78, 73, 1026.2, 1023.0, 7, 7, 17.5, 18.7, 'No', 'No'), ('9/9/2013', 15.3, 26.1, 0.0, 2.2, 5.1, 'NNW', 33, 'N', 'NE', 9, 11, 70, 69, 1021.0, 1014.0, 2, 7, 21.1, 22.5, 'No', 'No'), ('9/10/2013', 20.1, 31.6, 0.0, 7.4, 9.7, 'NNW', 74, 'NW', 'WNW', 33, 31, 24, 14, 1005.5, 1000.4, 2, 4, 25.9, 30.6, 'No', 'No'), ('9/11/2013', 14.7, 25.0, 0.0, 11.6, 6.8, 'WNW', 43, 'W', 'WSW', 28, 15, 38, 22, 1011.7, 1008.7, 5, 3, 16.9, 24.5, 'No', 'No'), ('9/12/2013', 12.1, 23.6, 0.0, 6.4, 10.2, 'S', 74, 'W', 'SW', 15, 6, 41, 27, 1015.2, 1010.1, 1, 4, 17.5, 22.4, 'No', 'No'), ('9/13/2013', 10.0, 18.5, 0.0, 5.6, 6.1, 'SSW', 41, 'SW', 'ENE', 20, 24, 67, 56, 1021.9, 1018.1, 7, 7, 14.9, 16.9, 'No', 'Yes'), ('9/14/2013', 14.1, 22.9, 2.2, 3.4, 8.4, 'ENE', 54, 'W', 'S', 17, 24, 75, 59, 1011.2, 1009.1, 5, 3, 17.0, 20.2, 'Yes', 'No'), ('9/15/2013', 12.8, 18.8, 0.0, 4.0, 6.2, 'WSW', 33, 'S', 'ENE', 6, 17, 74, 66, 1018.4, 1016.3, 7, 5, 16.4, 17.9, 'No', 'Yes'), ('9/16/2013', 14.6, 17.7, 1.2, 2.2, 0.0, 'ENE', 80, 'S', 'ENE', 6, 35, 75, 91, 1016.0, 1010.0, 8, 8, 16.5, 16.5, 'Yes', 'Yes'), ('9/17/2013', 15.2, 23.9, 32.2, 4.8, 5.7, 'WNW', 57, 'N', 'NNW', 22, 28, 73, 42, 1000.8, 998.3, 6, 5, 17.7, 23.2, 'Yes', 'No'), ('9/18/2013', 15.2, 25.3, 0.0, 6.8, 10.7, 'W', 48, 'NW', 'W', 20, 28, 53, 28, 1002.0, 1000.0, 6, 1, 20.7, 24.7, 'No', 'No'), ('9/19/2013', 14.2, 23.4, 0.2, 7.6, 11.2, 'WNW', 63, 'W', 'WNW', 9, 46, 31, 21, 1005.7, 1002.9, 0, 1, 19.9, 22.9, 'No', 'No'), ('9/20/2013', 11.4, 21.6, 0.0, 6.2, 10.3, 'WSW', 69, 'NNW', 'SW', 13, 24, 34, 30, 1007.9, 1006.2, 2, 6, 18.6, 18.9, 'No', 'No'), ('9/21/2013', 11.3, 22.0, 0.0, 7.0, 11.0, 'W', 37, 'W', 'ESE', 22, 19, 49, 42, 1014.8, 1012.2, 1, 2, 16.8, 20.1, 'No', 'No'), ('9/22/2013', 11.0, 25.2, 0.0, 4.6, 10.5, 'E', 28, 'WNW', 'ENE', 11, 20, 57, 51, 1014.9, 1011.6, 1, 2, 16.9, 21.6, 'No', 'No'), ('9/23/2013', 12.9, 24.4, 0.0, 5.4, 10.9, 'ENE', 24, 'W', 'E', 7, 13, 55, 54, 1012.0, 1007.3, 1, 1, 19.1, 22.8, 'No', 'No'), ('9/24/2013', 17.5, 28.4, 0.0, 7.4, 5.3, 'WSW', 39, 'E', 'ENE', 2, 9, 32, 32, 1004.1, 1000.4, 7, 5, 22.4, 26.9, 'No', 'No'), ('9/25/2013', 15.6, 28.8, 0.0, 6.4, 10.7, 'NNE', 43, 'W', 'NE', 9, 20, 40, 32, 1009.8, 1006.0, 0, 1, 23.4, 27.3, 'No', 'No'), ('9/26/2013', 16.2, 31.8, 0.0, 8.4, 11.4, 'W', 41, 'NW', 'WNW', 17, 35, 30, 20, 1002.9, 1005.8, 0, 0, 26.9, 26.3, 'No', 'No'), ('9/27/2013', 12.7, 22.6, 0.0, 12.2, 11.4, 'W', 46, 'W', 'E', 19, 19, 29, 39, 1019.9, 1016.6, 0, 0, 18.1, 19.9, 'No', 'No'), ('9/28/2013', 11.7, 29.3, 0.0, 8.0, 11.5, 'W', 76, 'W', 'W', 13, 39, 47, 13, 1011.1, 1005.2, 1, 1, 18.9, 27.9, 'No', 'No'), ('9/29/2013', 14.4, 22.8, 0.0, 9.8, 10.8, 'W', 41, 'W', 'E', 13, 22, 34, 35, 1017.4, 1014.8, 1, 1, 19.4, 20.8, 'No', 'No'), ('9/30/2013', 12.4, 27.4, 0.0, 6.4, 10.6, 'NNE', 35, 'W', 'NE', 6, 17, 46, 35, 1016.6, 1010.7, 6, 3, 20.3, 26.2, 'No', 'No'), ('10/1/2013', 20.2, 32.2, 0.0, 8.6, 3.0, 'NW', 85, 'NNW', 'WNW', 35, 41, 33, 32, 1003.8, 1005.0, 7, 7, 24.7, 26.4, 'No', 'No'), ('10/2/2013', 13.0, 26.6, 0.0, 9.8, 11.2, 'NNW', 48, 'NNW', 'ENE', 17, 15, 31, 26, 1015.6, 1007.6, 1, 7, 20.8, 26.0, 'No', 'No'), ('10/3/2013', 15.2, 18.9, 0.0, 10.0, 3.7, 'WSW', 65, 'WSW', 'S', 30, 24, 41, 41, 1010.9, 1014.3, 2, 4, 17.7, 17.2, 'No', 'Yes'), ('10/4/2013', 9.7, 20.4, 5.0, 3.8, 10.6, 'WSW', 39, 'WNW', 'ESE', 15, 15, 45, 37, 1022.4, 1019.1, 2, 1, 16.1, 19.3, 'Yes', 'No'), ('10/5/2013', 11.3, 25.0, 0.0, 5.2, 9.2, 'E', 28, 'W', 'E', 15, 13, 56, 41, 1016.5, 1010.4, 4, 6, 17.8, 23.4, 'No', 'No'), ('10/6/2013', 14.1, 29.8, 0.0, 5.6, 11.2, 'SSW', 33, 'WNW', 'E', 9, 17, 41, 24, 1010.5, 1005.0, 2, 3, 20.1, 28.9, 'No', 'No'), ('10/7/2013', 15.8, 21.9, 0.0, 9.8, 10.4, 'SE', 52, 'SSW', 'SSE', 26, 33, 60, 44, 1011.2, 1010.8, 2, 2, 18.3, 20.3, 'No', 'No'), ('10/8/2013', 14.3, 21.9, 0.0, 5.8, 11.2, 'SSE', 44, 'WNW', 'SSE', 9, 22, 58, 49, 1014.0, 1015.8, 1, 5, 17.7, 19.8, 'No', 'No'), ('10/9/2013', 12.3, 27.3, 0.0, 5.0, 11.9, 'ENE', 30, 'W', 'NE', 13, 15, 59, 36, 1019.0, 1013.1, 0, 0, 17.6, 25.7, 'No', 'No'), ('10/10/2013', 17.6, 37.3, 0.0, 10.0, 10.0, 'S', 74, 'NW', 'WNW', 15, 22, 22, 10, 1009.7, 1003.1, 7, 1, 27.3, 37.1, 'No', 'No'), ('10/11/2013', 17.9, 22.1, 0.0, 13.2, 10.0, 'SSE', 61, 'SSE', 'ENE', 24, 19, 64, 49, 1013.1, 1012.7, 5, 1, 18.4, 20.5, 'No', 'No'), ('10/12/2013', 14.3, 24.7, 0.0, 5.8, 11.2, 'ENE', 31, 'WNW', 'ENE', 13, 24, 63, 62, 1016.0, 1009.5, 0, 0, 18.5, 23.3, 'No', 'No'), ('10/13/2013', 17.5, 35.0, 0.0, 6.6, 10.8, 'WNW', 80, 'WNW', 'WNW', 11, 46, 45, 10, 1002.2, 996.3, 2, 1, 24.7, 34.2, 'No', 'Yes'), ('10/14/2013', 13.1, 20.7, 5.0, 15.2, 6.7, 'WSW', 44, 'SSW', 'ESE', 28, 24, 44, 34, 1014.5, 1014.4, 5, 2, 14.8, 19.3, 'Yes', 'No'), ('10/15/2013', 10.7, 24.3, 0.0, 5.8, 12.1, 'E', 33, 'WNW', 'NE', 15, 20, 40, 32, 1022.6, 1018.7, 1, 0, 15.4, 21.5, 'No', 'No'), ('10/16/2013', 12.7, 28.3, 0.0, 6.4, 11.7, 'NE', 48, 'NNE', 'ENE', 9, 35, 33, 32, 1018.9, 1012.4, 1, 1, 21.1, 25.1, 'No', 'No'), ('10/17/2013', 19.6, 33.6, 0.0, 11.2, 5.2, 'NW', 80, 'N', 'WNW', 31, 43, 23, 10, 1005.9, 1003.3, 7, 7, 27.5, 31.5, 'No', 'No'), ('10/18/2013', 13.7, 22.1, 0.0, 13.4, 11.2, 'SW', 41, 'W', 'E', 15, 22, 30, 43, 1025.8, 1025.1, 2, 2, 17.9, 19.7, 'No', 'No'), ('10/19/2013', 12.6, 22.4, 0.0, 6.8, 12.1, 'ENE', 37, 'WNW', 'E', 13, 28, 57, 43, 1028.1, 1024.4, 0, 0, 17.6, 21.3, 'No', 'No'), ('10/20/2013', 15.5, 24.4, 0.0, 7.2, 10.9, 'NNE', 48, 'W', 'ENE', 4, 19, 65, 59, 1021.5, 1016.5, 0, 5, 20.7, 23.4, 'No', 'No'), ('10/21/2013', 16.6, 28.9, 0.0, 6.2, 10.3, 'NNE', 37, 'W', 'ESE', 11, 15, 56, 48, 1016.3, 1011.9, 0, 6, 21.4, 26.7, 'No', 'No'), ('10/22/2013', 19.5, 27.0, 0.0, 9.4, 0.6, 'SW', 50, 'SSW', 'ESE', 20, 7, 72, 65, 1016.2, 1011.7, 7, 8, 21.4, 24.2, 'No', 'Yes'), ('10/23/2013', 20.1, 33.6, 3.6, 2.8, 11.9, 'NW', 63, 'NNW', 'W', 28, 31, 47, 16, 1004.8, 1002.3, 3, 1, 27.0, 32.9, 'Yes', 'No'), ('10/24/2013', 16.4, 25.9, 0.0, 12.4, 12.5, 'W', 70, 'WSW', 'WSW', 20, 31, 41, 18, 1011.7, 1012.9, 1, 1, 20.2, 23.7, 'No', 'No'), ('10/25/2013', 12.2, 23.4, 0.0, 10.8, 10.4, 'E', 35, 'WSW', 'E', 20, 26, 28, 31, 1023.2, 1019.2, 1, 0, 16.0, 20.7, 'No', 'No'), ('10/26/2013', 14.0, 23.9, 0.0, 8.8, 11.6, 'WSW', 44, 'WSW', 'ESE', 28, 26, 34, 42, 1020.9, 1019.1, 7, 1, 17.2, 21.6, 'No', 'No'), ('10/27/2013', 14.6, 22.3, 0.0, 6.0, 9.1, 'ESE', 37, 'NW', 'E', 17, 20, 51, 55, 1022.5, 1020.4, 3, 7, 20.5, 20.5, 'No', 'Yes'), ('10/28/2013', 15.6, 22.3, 28.2, 3.2, 5.7, 'ENE', 61, 'ENE', 'E', 15, 19, 81, 61, 1019.5, 1014.3, 7, 2, 19.5, 22.2, 'Yes', 'No'), ('10/29/2013', 16.4, 26.3, 0.0, 4.8, 5.0, 'S', 93, 'W', 'E', 15, 0, 78, 68, 1006.6, 1008.7, 7, 7, 19.5, 18.9, 'No', 'No'), ('10/30/2013', 13.2, 22.2, 0.4, 7.4, 12.0, 'W', 41, 'W', 'E', 0, 0, 57, 49, 1019.6, 1018.0, 6, 2, 16.7, 21.7, 'No', 'No'), ('10/31/2013', 15.4, 22.2, 0.0, 5.4, 9.8, 'W', 41, 'W', 'E', 0, 0, 62, 56, 1022.0, 1019.3, 5, 1, 18.2, 21.1, 'No', 'No'), ('11/1/2013', 17.3, 21.7, 0.0, 8.0, 7.7, 'W', 41, 'W', 'E', 0, 0, 63, 61, 1023.8, 1020.2, 7, 7, 19.0, 21.0, 'No', 'No'), ('11/2/2013', 15.9, 26.1, 0.0, 5.6, 7.1, 'W', 41, 'W', 'E', 0, 0, 71, 63, 1018.2, 1012.5, 7, 7, 19.3, 23.5, 'No', 'No'), ('11/3/2013', 18.7, 34.2, 0.0, 7.6, 7.4, 'W', 41, 'W', 'E', 0, 0, 49, 11, 1010.3, 1006.1, 7, 6, 23.8, 32.8, 'No', 'No'), ('11/4/2013', 14.8, 20.5, 0.0, 11.2, 11.7, 'W', 41, 'W', 'E', 0, 0, 34, 38, 1022.5, 1024.0, 1, 1, 17.0, 19.0, 'No', 'No'), ('11/5/2013', 15.0, 21.4, 0.0, 9.8, 4.3, 'ESE', 33, 'W', 'ESE', 0, 20, 58, 47, 1028.0, 1026.5, 7, 5, 16.6, 19.1, 'No', 'No'), ('11/6/2013', 11.8, 21.4, 0.0, 4.6, 12.2, 'ENE', 43, 'W', 'E', 11, 30, 58, 51, 1024.3, 1019.2, 1, 1, 17.4, 20.7, 'No', 'No'), ('11/7/2013', 15.0, 26.2, 0.0, 8.0, 11.9, 'NNE', 48, 'W', 'ENE', 11, 22, 59, 51, 1017.1, 1012.2, 0, 1, 20.6, 24.7, 'No', 'No'), ('11/8/2013', 17.9, 28.1, 0.0, 9.4, 8.3, 'W', 63, 'W', 'NNE', 4, 28, 43, 44, 1011.0, 1006.4, 3, 6, 24.5, 27.6, 'No', 'No'), ('11/9/2013', 22.3, 33.3, 0.0, 10.4, 9.5, 'SSE', 48, 'WNW', 'SE', 9, 20, 46, 37, 1006.4, 1006.6, 4, 3, 24.8, 28.4, 'No', 'Yes'), ('11/10/2013', 15.7, 18.9, 11.6, 9.6, 0.7, 'SE', 50, 'SSW', 'SE', 15, 22, 87, 62, 1017.5, 1017.2, 8, 7, 15.8, 18.7, 'Yes', 'Yes'), ('11/11/2013', 15.1, 18.4, 39.6, 9.4, 0.0, 'SE', 54, 'SSE', 'SSE', 31, 28, 91, 91, 1018.1, 1016.4, 8, 7, 16.0, 17.3, 'Yes', 'Yes'), ('11/12/2013', 15.6, 22.8, 20.2, 1.8, 4.9, 'ENE', 28, 'N', 'E', 4, 6, 92, 66, 1013.2, 1011.8, 8, 7, 17.4, 21.9, 'Yes', 'Yes'), ('11/13/2013', 15.1, 27.6, 7.4, 3.2, 13.0, 'ENE', 37, 'W', 'E', 20, 24, 59, 59, 1014.4, 1011.2, 1, 3, 20.7, 23.2, 'Yes', 'No'), ('11/14/2013', 16.9, 27.0, 0.0, 9.6, 13.2, 'ENE', 33, 'WNW', 'E', 15, 20, 32, 45, 1014.1, 1011.3, 0, 1, 22.5, 23.7, 'No', 'No'), ('11/15/2013', 15.9, 23.3, 0.0, 7.8, 8.0, 'ESE', 69, 'NNW', 'SE', 2, 26, 68, 62, 1015.8, 1014.6, 3, 6, 20.7, 22.6, 'No', 'Yes'), ('11/16/2013', 15.7, 21.7, 23.0, 4.8, 5.6, 'SSE', 50, 'SSE', 'SSE', 19, 33, 74, 75, 1016.0, 1014.5, 7, 7, 18.0, 18.8, 'Yes', 'Yes'), ('11/17/2013', 14.8, 18.0, 40.8, 5.6, 0.0, 'SSE', 50, 'SSW', 'SSE', 22, 17, 83, 83, 1015.5, 1014.5, 7, 8, 16.4, 16.8, 'Yes', 'Yes'), ('11/18/2013', 15.2, 20.0, 11.2, 4.0, 0.0, 'S', 59, 'S', 'SSE', 30, 24, 80, 91, 1013.3, 1010.5, 8, 8, 17.9, 18.4, 'Yes', 'Yes'), ('11/19/2013', 16.4, 25.4, 17.6, 2.0, 10.3, 'S', 39, 'SSW', 'SSE', 17, 17, 79, 55, 1011.4, 1010.3, 6, 2, 20.0, 24.5, 'Yes', 'No'), ('11/20/2013', 16.6, 24.9, 0.2, 6.8, 12.0, 'E', 33, 'W', 'E', 11, 22, 71, 66, 1012.4, 1010.7, 4, 1, 20.8, 24.2, 'No', 'No'), ('11/21/2013', 20.1, 24.6, 0.0, 6.2, 9.8, 'ENE', 52, 'NNE', 'NE', 15, 24, 64, 64, 1012.8, 1010.4, 6, 5, 23.6, 23.5, 'No', 'Yes'), ('11/22/2013', 19.9, 24.3, 3.0, 9.8, 2.9, 'NE', 69, 'NE', 'NNE', 28, 39, 79, 67, 1009.1, 1006.6, 7, 7, 21.1, 22.6, 'Yes', 'Yes'), ('11/23/2013', 18.1, 25.0, 7.4, 4.0, 9.3, 'NE', 31, 'WNW', 'NE', 9, 7, 78, 60, 1005.8, 1003.2, 3, 5, 21.7, 22.6, 'Yes', 'Yes'), ('11/24/2013', 16.8, 23.8, 3.6, 5.0, 13.0, 'SE', 41, 'SSE', 'SE', 7, 20, 58, 51, 1006.3, 1005.2, 1, 2, 20.8, 22.7, 'Yes', 'No'), ('11/25/2013', 16.4, 23.3, 0.0, 8.2, 10.3, 'SSW', 61, 'SW', 'S', 6, 35, 57, 69, 1008.1, 1009.1, 3, 7, 20.8, 20.0, 'No', 'Yes'), ('11/26/2013', 14.7, 22.9, 4.2, 7.4, 7.7, 'SSE', 41, 'WSW', 'SSE', 13, 22, 61, 46, 1016.7, 1016.4, 7, 1, 17.0, 22.2, 'Yes', 'No'), ('11/27/2013', 13.7, 23.9, 0.0, 5.6, 12.6, 'E', 30, 'WNW', 'E', 13, 20, 52, 48, 1018.3, 1014.8, 1, 1, 19.5, 22.5, 'No', 'No'), ('11/28/2013', 16.6, 26.5, 0.0, 8.0, 11.2, 'NNE', 46, 'NNE', 'NE', 9, 19, 56, 60, 1011.7, 1005.0, 6, 7, 23.3, 25.6, 'No', 'No'), ('11/29/2013', 19.5, 20.9, 0.2, 10.6, 0.0, 'S', 59, 'SSE', 'S', 13, 19, 72, 83, 1005.8, 1008.8, 8, 7, 20.9, 17.1, 'No', 'Yes'), ('11/30/2013', 14.9, 22.9, 2.8, 3.4, 7.3, 'SW', 44, 'S', 'SE', 22, 20, 59, 49, 1018.8, 1019.5, 7, 2, 18.5, 21.9, 'Yes', 'No'), ('12/1/2013', 14.0, 22.7, 0.0, 7.0, 7.5, 'ESE', 35, 'WNW', 'E', 6, 17, 64, 49, 1025.1, 1024.3, 5, 4, 19.0, 21.8, 'No', 'No'), ('12/2/2013', 15.2, 24.1, 0.0, 5.0, 12.1, 'ENE', 37, 'E', 'ENE', 11, 22, 52, 44, 1022.5, 1019.6, 4, 5, 21.3, 23.3, 'No', 'No'), ('12/3/2013', 15.2, 24.6, 0.0, 8.0, 13.3, 'ENE', 48, 'N', 'NE', 11, 30, 51, 52, 1017.6, 1013.5, 2, 1, 22.8, 23.4, 'No', 'No'), ('12/4/2013', 17.8, 27.8, 0.0, 8.8, 7.9, 'NNE', 54, 'ENE', 'E', 13, 15, 61, 63, 1006.3, 1000.5, 5, 7, 23.5, 24.9, 'No', 'Yes'), ('12/5/2013', 19.0, 26.3, 4.0, 8.0, 8.4, 'W', 78, 'SSW', 'W', 4, 48, 80, 32, 996.7, 996.9, 7, 6, 21.5, 22.3, 'Yes', 'No'), ('12/6/2013', 12.7, 22.9, 0.0, 10.0, 13.6, 'WSW', 59, 'W', 'ESE', 26, 24, 37, 39, 1011.7, 1013.3, 1, 1, 17.1, 22.0, 'No', 'No'), ('12/7/2013', 13.6, 25.0, 0.0, 7.6, 12.6, 'NNE', 30, 'W', 'E', 13, 22, 47, 45, 1020.4, 1018.3, 3, 6, 20.0, 23.9, 'No', 'No'), ('12/8/2013', 16.2, 25.6, 0.0, 7.2, 11.4, 'NE', 46, 'E', 'NE', 9, 26, 58, 45, 1019.0, 1013.5, 3, 2, 22.6, 25.3, 'No', 'No'), ('12/9/2013', 19.3, 29.8, 0.0, 10.0, 4.1, 'N', 56, 'ESE', 'NE', 6, 6, 52, 46, 1009.1, 1004.0, 7, 7, 25.4, 29.2, 'No', 'No'), ('12/10/2013', 23.0, 33.0, 0.0, 8.0, 12.0, 'W', 54, 'WNW', 'ESE', 24, 13, 34, 33, 1002.5, 1002.6, 1, 1, 28.6, 30.4, 'No', 'No'), ('12/11/2013', 18.1, 28.0, 0.0, 11.2, 13.2, 'ENE', 31, 'WSW', 'E', 13, 24, 31, 40, 1009.7, 1005.0, 1, 3, 23.7, 24.9, 'No', 'No'), ('12/12/2013', 19.9, 24.8, 0.0, 10.4, 9.7, 'NE', 46, 'E', 'ENE', 15, 28, 69, 59, 1011.9, 1009.8, 6, 2, 20.6, 24.0, 'No', 'No'), ('12/13/2013', 18.9, 26.3, 0.0, 6.8, 13.0, 'ENE', 46, 'ESE', 'ENE', 9, 30, 63, 63, 1012.5, 1009.8, 1, 1, 24.3, 25.1, 'No', 'No'), ('12/14/2013', 20.6, 26.7, 0.0, 8.8, 9.8, 'SSE', 50, 'S', 'SSE', 30, 31, 65, 56, 1014.8, 1015.0, 3, 5, 23.7, 23.6, 'No', 'Yes'), ('12/15/2013', 19.1, 24.6, 1.2, 7.8, 2.0, 'ESE', 30, 'NE', 'E', 2, 19, 81, 59, 1018.6, 1016.9, 7, 5, 20.1, 23.8, 'Yes', 'Yes'), ('12/16/2013', 18.7, 24.8, 2.2, 7.0, 6.4, 'ENE', 35, 'NE', 'ENE', 9, 24, 83, 60, 1020.6, 1019.2, 7, 3, 20.1, 23.9, 'Yes', 'No'), ('12/17/2013', 18.7, 26.0, 0.2, 3.6, 11.9, 'NE', 44, 'NNE', 'ENE', 9, 30, 60, 52, 1021.8, 1019.5, 6, 1, 22.5, 24.7, 'No', 'No'), ('12/18/2013', 20.6, 26.0, 0.0, 10.0, 12.9, 'ENE', 33, 'ENE', 'ENE', 15, 26, 57, 54, 1024.2, 1022.9, 3, 1, 24.5, 24.5, 'No', 'No'), ('12/19/2013', 18.9, 26.4, 0.0, 9.0, 12.9, 'NNE', 56, 'NE', 'NE', 17, 28, 60, 59, 1022.5, 1018.8, 2, 1, 23.1, 25.1, 'No', 'No'), ('12/20/2013', 20.3, 33.5, 0.0, 10.0, 10.1, 'ENE', 43, 'E', 'E', 6, 9, 59, 40, 1016.3, 1011.6, 2, 3, 26.2, 31.4, 'No', 'No'), ('12/21/2013', 21.5, 27.8, 0.0, 11.6, 9.9, 'SSE', 57, 'SSW', 'SSE', 28, 37, 59, 57, 1016.8, 1015.4, 6, 1, 25.1, 26.5, 'No', 'No'), ('12/22/2013', 21.7, 28.7, 0.0, 8.0, 6.9, 'NNE', 52, 'NE', 'E', 9, 9, 67, 66, 1012.6, 1008.3, 7, 7, 25.5, 26.8, 'No', 'No'), ('12/23/2013', 22.4, 36.0, 0.0, 7.6, 4.0, 'S', 57, 'ESE', 'ESE', 11, 9, 61, 34, 1007.2, 1004.3, 7, 7, 27.5, 31.5, 'No', 'No'), ('12/24/2013', 19.2, 22.9, 0.0, 6.6, 0.0, 'SSE', 41, 'SSE', 'SSE', 24, 17, 58, 56, 1018.3, 1018.5, 7, 7, 21.8, 22.1, 'No', 'No'), ('12/25/2013', 18.7, 21.5, 0.6, 3.6, 0.0, 'ENE', 35, 'W', 'NE', 6, 13, 85, 88, 1019.3, 1016.4, 8, 8, 18.9, 20.1, 'No', 'Yes'), ('12/26/2013', 18.7, 26.6, 21.0, 1.2, 9.5, 'SW', 43, 'SSW', 'ESE', 13, 24, 82, 51, 1012.3, 1010.5, 7, 1, 21.5, 25.2, 'Yes', 'Yes'), ('12/27/2013', 17.9, 24.8, 1.8, 6.2, 10.5, 'ENE', 31, 'W', 'ENE', 9, 22, 78, 64, 1012.5, 1010.7, 5, 5, 21.0, 24.3, 'Yes', 'No'), ('12/28/2013', 19.4, 25.5, 0.0, 5.6, 12.4, 'NNE', 54, 'ENE', 'NE', 19, 28, 62, 63, 1012.3, 1007.6, 4, 1, 23.6, 24.9, 'No', 'No'), ('12/29/2013', 20.0, 24.6, 0.0, 10.2, 11.7, 'SSE', 78, 'SSE', 'SSE', 39, 28, 65, 47, 1009.5, 1012.9, 2, 1, 21.4, 23.5, 'No', 'No'), ('12/30/2013', 18.8, 24.2, 0.0, 11.4, 10.2, 'ENE', 43, 'E', 'ENE', 9, 24, 47, 49, 1015.3, 1011.7, 5, 1, 22.1, 23.4, 'No', 'No'), ('12/31/2013', 17.5, 26.2, 0.0, 6.4, 10.6, 'ESE', 37, 'W', 'ESE', 9, 24, 60, 55, 1013.2, 1011.0, 2, 1, 22.5, 25.9, 'No', 'No'), ('1/1/2014', 20.5, 27.1, 0.0, 7.4, 5.9, 'W', 41, 'NNE', 'NE', 13, 24, 58, 62, 1014.6, 1011.3, 5, 8, 24.4, 24.9, 'No', 'No'), ('1/2/2014', 22.3, 36.5, 0.0, 8.0, 3.5, 'WSW', 52, 'ESE', 'WSW', 6, 33, 50, 22, 1003.6, 1002.0, 7, 7, 27.1, 34.5, 'No', 'No'), ('1/3/2014', 21.0, 26.2, 0.2, 5.6, 5.6, 'ENE', 37, 'ENE', 'ENE', 13, 26, 62, 52, 1005.3, 1000.0, 7, 6, 22.2, 24.8, 'No', 'No'), ('1/4/2014', 20.1, 27.5, 0.0, 7.4, 11.2, 'S', 57, 'SSW', 'E', 17, 22, 60, 54, 1003.4, 1002.3, 1, 1, 22.9, 24.6, 'No', 'No'), ('1/5/2014', 20.8, 26.0, 0.0, 8.2, 12.2, 'NNE', 59, 'NNE', 'NE', 9, 22, 63, 70, 1010.5, 1005.7, 6, 2, 24.2, 24.9, 'No', 'No'), ('1/6/2014', 19.6, 32.0, 0.0, 9.4, 12.8, 'W', 43, 'WSW', 'SE', 17, 26, 30, 26, 1008.9, 1007.3, 1, 1, 25.3, 28.9, 'No', 'No'), ('1/7/2014', 18.3, 21.6, 0.0, 11.4, 1.7, 'SSE', 44, 'SSE', 'SE', 26, 13, 55, 63, 1018.3, 1019.4, 5, 7, 20.9, 19.5, 'No', 'Yes'), ('1/8/2014', 16.2, 22.3, 5.8, 7.6, 0.4, 'SE', 35, 'SE', 'SE', 11, 15, 68, 60, 1023.7, 1022.4, 7, 7, 18.3, 20.5, 'Yes', 'No'), ('1/9/2014', 18.1, 23.2, 0.0, 3.8, 2.0, 'E', 33, 'ENE', 'ENE', 17, 20, 49, 53, 1024.3, 1023.1, 7, 7, 21.1, 22.4, 'No', 'No'), ('1/10/2014', 19.0, 25.7, 0.4, 6.6, 9.3, 'ENE', 41, 'ESE', 'ENE', 4, 26, 66, 59, 1022.2, 1019.6, 6, 3, 22.3, 23.8, 'No', 'No'), ('1/11/2014', 19.1, 29.1, 0.0, 7.2, 10.9, 'ENE', 35, 'W', 'NE', 6, 17, 65, 49, 1018.9, 1014.6, 1, 2, 23.5, 27.4, 'No', 'No'), ('1/12/2014', 21.1, 28.8, 0.0, 10.4, 10.3, 'ESE', 39, 'ENE', 'ESE', 9, 19, 71, 61, 1017.7, 1017.0, 2, 3, 24.8, 26.1, 'No', 'No'), ('1/13/2014', 19.7, 26.8, 0.0, 7.6, 11.5, 'ESE', 33, 'SW', 'ESE', 7, 17, 66, 53, 1021.9, 1020.2, 6, 2, 21.9, 24.7, 'No', 'No'), ('1/14/2014', 18.3, 27.5, 0.0, 7.2, 12.0, 'ENE', 44, 'W', 'E', 7, 30, 59, 53, 1022.3, 1019.7, 4, 0, 22.8, 26.2, 'No', 'No'), ('1/15/2014', 21.2, 28.8, 0.0, 10.0, 12.8, 'NE', 56, 'ESE', 'NE', 2, 22, 62, 53, 1021.7, 1018.2, 0, 1, 25.6, 28.2, 'No', 'No'), ('1/16/2014', 21.1, 28.1, 0.0, 10.8, 13.1, 'ENE', 41, 'ENE', 'ENE', 9, 28, 64, 58, 1019.2, 1016.6, 0, 0, 25.3, 27.3, 'No', 'No'), ('1/17/2014', 21.3, 27.7, 0.0, 10.4, 12.8, 'NE', 52, 'NNE', 'NE', 6, 26, 67, 57, 1016.7, 1014.0, 2, 0, 24.2, 27.2, 'No', 'No'), ('1/18/2014', 19.3, 28.7, 0.0, 10.6, 13.1, 'NE', 52, 'ENE', 'ENE', 7, 22, 65, 51, 1012.6, 1009.4, 0, 0, 25.1, 28.3, 'No', 'No'), ('1/19/2014', 21.2, 29.4, 0.0, 10.8, 6.1, 'SSE', 37, 'SE', 'SE', 6, 20, 65, 60, 1010.0, 1008.9, 7, 6, 24.9, 26.4, 'No', 'No'), ('1/20/2014', 21.7, 25.9, 0.0, 4.2, 2.8, 'S', 37, 'SSE', 'ESE', 11, 24, 71, 65, 1009.2, 1008.0, 6, 7, 24.1, 25.1, 'No', 'Yes'), ('1/21/2014', 19.8, 25.0, 5.0, 5.0, 0.6, 'E', 33, 'E', 'E', 20, 15, 79, 68, 1010.2, 1008.0, 7, 7, 21.6, 23.9, 'Yes', 'Yes'), ('1/22/2014', 19.8, 22.8, 3.0, 2.8, 0.0, 'SSE', 43, 'SE', 'SSE', 15, 24, 74, 60, 1017.7, 1019.9, 7, 7, 21.8, 22.3, 'Yes', 'No'), ('1/23/2014', 20.2, 24.7, 0.2, 4.4, 4.6, 'E', 31, 'E', 'E', 20, 20, 60, 54, 1023.2, 1021.0, 5, 7, 22.4, 23.5, 'No', 'No'), ('1/24/2014', 19.7, 26.3, 0.0, 7.4, 1.5, 'NNE', 52, 'NNE', 'NE', 20, 28, 69, 61, 1014.0, 1008.0, 8, 8, 23.9, 26.0, 'No', 'Yes'), ('1/25/2014', 19.3, 25.3, 2.4, 5.6, 8.0, 'SE', 56, 'S', 'SSE', 20, 37, 63, 45, 1012.0, 1014.8, 4, 4, 22.5, 23.3, 'Yes', 'No'), ('1/26/2014', 17.2, 22.3, 0.2, 8.6, 2.3, 'SSE', 31, 'SSW', 'E', 7, 19, 77, 48, 1023.8, 1024.1, 7, 7, 18.1, 21.1, 'No', 'No'), ('1/27/2014', 16.0, 25.5, 0.2, 3.6, 12.7, 'NE', 44, 'W', 'ENE', 13, 26, 56, 52, 1024.4, 1022.3, 3, 3, 20.6, 24.7, 'No', 'No'), ('1/28/2014', 19.6, 26.5, 0.0, 9.4, 13.0, 'NE', 57, 'NNE', 'NE', 17, 28, 45, 56, 1021.5, 1018.4, 1, 1, 24.7, 25.5, 'No', 'No'), ('1/29/2014', 20.3, 29.1, 0.0, 12.0, 13.0, 'NE', 44, 'NNE', 'NE', 6, 20, 54, 45, 1017.0, 1014.0, 0, 1, 24.5, 29.0, 'No', 'No'), ('1/30/2014', 21.7, 27.9, 0.0, 9.6, 13.0, 'NE', 52, 'E', 'NE', 13, 30, 56, 44, 1019.9, 1016.8, 3, 0, 25.2, 27.6, 'No', 'No'), ('1/31/2014', 20.3, 28.3, 0.0, 12.6, 13.0, 'NE', 44, 'NE', 'NE', 17, 26, 51, 45, 1014.9, 1012.0, 1, 1, 24.7, 27.2, 'No', 'No'), ('2/1/2014', 21.7, 28.7, 0.0, 11.0, 10.6, 'SSE', 37, 'SSW', 'ESE', 17, 17, 72, 59, 1015.2, 1012.6, 6, 3, 23.6, 26.6, 'No', 'No'), ('2/2/2014', 22.3, 27.4, 0.0, 7.2, 12.7, 'NE', 43, 'NE', 'NE', 22, 26, 67, 55, 1015.6, 1014.3, 3, 1, 24.6, 26.4, 'No', 'No'), ('2/3/2014', 21.3, 27.1, 0.0, 12.0, 11.6, 'NE', 56, 'NNE', 'NE', 26, 33, 55, 51, 1015.7, 1012.0, 1, 0, 24.9, 25.9, 'No', 'No'), ('2/4/2014', 20.7, 25.2, 0.0, 12.0, 1.2, 'SSE', 61, 'ESE', 'S', 17, 31, 62, 83, 1017.1, 1019.4, 7, 8, 25.1, 19.5, 'No', 'Yes'), ('2/5/2014', 17.5, 24.5, 3.2, 5.2, 3.1, 'SSE', 41, 'SSE', 'SSE', 26, 26, 59, 46, 1023.9, 1022.3, 6, 7, 20.6, 22.7, 'Yes', 'Yes'), ('2/6/2014', 17.1, 23.3, 1.2, 7.2, 3.2, 'E', 26, 'WSW', 'ESE', 11, 17, 67, 48, 1020.3, 1017.7, 8, 7, 19.2, 23.2, 'Yes', 'No'), ('2/7/2014', 15.5, 25.4, 0.2, 4.2, 12.3, 'ENE', 41, 'W', 'ENE', 11, 30, 63, 52, 1017.7, 1015.2, 1, 1, 19.6, 25.0, 'No', 'No'), ('2/8/2014', 19.4, 27.3, 0.0, 9.2, 12.1, 'NE', 44, 'SE', 'NE', 2, 26, 59, 53, 1018.1, 1016.3, 0, 0, 24.3, 25.9, 'No', 'No'), ('2/9/2014', 20.6, 27.6, 0.0, 9.6, 12.9, 'NE', 48, 'ENE', 'NE', 9, 22, 63, 52, 1018.9, 1015.4, 2, 0, 24.6, 27.1, 'No', 'No'), ('2/10/2014', 20.6, 27.2, 0.0, 10.4, 0.2, 'SSE', 59, 'SSW', 'S', 20, 17, 83, 54, 1019.5, 1017.5, 8, 6, 20.8, 25.5, 'No', 'No'), ('2/11/2014', 20.1, 27.7, 0.0, 7.2, 4.0, 'SSE', 31, 'S', 'SE', 4, 13, 72, 60, 1017.6, 1014.6, 8, 2, 22.4, 25.9, 'No', 'No'), ('2/12/2014', 22.1, 26.3, 0.2, 6.0, 4.3, 'ESE', 33, 'ESE', 'ESE', 19, 22, 78, 68, 1016.5, 1015.6, 7, 7, 23.5, 25.8, 'No', 'Yes'), ('2/13/2014', 21.5, 27.0, 3.4, 4.6, 7.5, 'ENE', 39, 'NE', 'E', 11, 28, 66, 64, 1015.1, 1011.3, 4, 8, 25.1, 25.6, 'Yes', 'No'), ('2/14/2014', 20.8, 23.5, 1.0, 8.8, 0.0, 'ENE', 28, 'NNE', 'ENE', 6, 17, 81, 79, 1008.1, 1006.4, 8, 8, 21.6, 22.8, 'No', 'No'), ('2/15/2014', 20.9, 24.9, 1.0, 2.2, 0.0, 'NE', 26, 'E', 'ENE', 2, 17, 88, 82, 1003.7, 999.5, 8, 8, 21.5, 23.1, 'No', 'Yes'), ('2/16/2014', 21.4, 25.0, 6.0, 2.4, 0.0, 'SSE', 54, 'S', 'SSE', 6, 24, 78, 83, 999.5, 1001.6, 8, 8, 24.7, 21.5, 'Yes', 'Yes'), ('2/17/2014', 18.4, 26.4, 21.8, 7.0, 8.3, 'SSW', 31, 'SSW', 'ESE', 13, 20, 90, 56, 1013.5, 1013.3, 7, 4, 19.0, 23.7, 'Yes', 'No'), ('2/18/2014', 18.9, 24.7, 0.0, 2.4, 2.7, 'E', 26, 'NW', 'E', 4, 13, 77, 68, 1013.0, 1009.9, 7, 7, 20.6, 23.9, 'No', 'No'), ('2/19/2014', 20.5, 29.1, 0.0, 2.2, 1.8, 'NNE', 35, 'N', 'W', 11, 13, 81, 82, 1004.8, 1002.1, 7, 8, 23.8, 23.5, 'No', 'Yes'), ('2/20/2014', 20.4, 29.1, 13.2, 4.2, 11.2, 'WSW', 33, 'SW', 'ESE', 7, 17, 52, 40, 1007.8, 1007.9, 5, 2, 22.2, 25.6, 'Yes', 'No'), ('2/21/2014', 18.0, 27.0, 0.0, 11.4, 11.9, 'ESE', 41, 'W', 'SE', 20, 28, 33, 44, 1016.0, 1015.8, 1, 1, 21.1, 24.4, 'No', 'No'), ('2/22/2014', 19.5, 24.7, 0.0, 5.8, 9.2, 'ESE', 33, 'SE', 'ESE', 9, 24, 63, 56, 1020.3, 1019.2, 7, 4, 22.0, 23.1, 'No', 'No'), ('2/23/2014', 19.6, 26.5, 0.0, 8.0, 10.7, 'SE', 37, 'SSE', 'SE', 24, 20, 50, 51, 1023.4, 1021.8, 1, 2, 23.0, 24.2, 'No', 'No'), ('2/24/2014', 19.1, 26.4, 0.2, 6.4, 11.0, 'ENE', 33, 'WNW', 'E', 9, 19, 68, 59, 1020.7, 1018.2, 2, 1, 21.7, 24.9, 'No', 'No'), ('2/25/2014', 19.5, 26.7, 0.0, 7.4, 11.8, 'NE', 50, 'NNW', 'NE', 6, 30, 72, 54, 1017.9, 1013.6, 3, 1, 23.2, 26.1, 'No', 'No'), ('2/26/2014', 19.7, 32.4, 0.0, 9.8, 6.2, 'SSE', 43, 'ESE', 'ENE', 7, 17, 59, 44, 1011.8, 1010.1, 6, 7, 25.1, 30.3, 'No', 'Yes'), ('2/27/2014', 20.3, 22.0, 4.4, 5.2, 0.2, 'S', 44, 'S', 'SSE', 24, 26, 82, 78, 1017.3, 1019.2, 7, 7, 21.7, 21.2, 'Yes', 'Yes'), ('2/28/2014', 19.3, 21.6, 2.4, 3.2, 0.0, 'SE', 44, 'SSE', 'SSE', 20, 20, 86, 68, 1022.7, 1022.5, 8, 7, 19.7, 21.0, 'Yes', 'Yes'), ('3/1/2014', 18.2, 22.7, 10.4, 1.6, 0.0, 'NNE', 26, 'WNW', 'ENE', 2, 11, 90, 75, 1020.5, 1019.1, 7, 8, 19.6, 22.0, 'Yes', 'Yes'), ('3/2/2014', 17.9, 22.8, 6.6, 2.4, 1.2, 'ESE', 41, 'SSW', 'S', 11, 17, 85, 86, 1020.3, 1020.6, 7, 8, 19.3, 19.8, 'Yes', 'Yes'), ('3/3/2014', 18.8, 26.3, 4.6, 3.8, 3.8, 'ESE', 37, 'WNW', 'SE', 11, 11, 70, 75, 1024.8, 1024.5, 3, 7, 21.7, 22.2, 'Yes', 'Yes'), ('3/4/2014', 19.0, 25.4, 1.4, 2.6, 3.3, 'ENE', 22, 'WNW', 'E', 7, 11, 83, 58, 1026.1, 1023.7, 7, 7, 20.9, 24.7, 'Yes', 'No'), ('3/5/2014', 18.1, 27.5, 0.2, 4.0, 7.7, 'S', 50, 'WNW', 'NE', 4, 15, 69, 62, 1018.6, 1014.0, 1, 3, 21.9, 26.6, 'No', 'Yes'), ('3/6/2014', 21.0, 26.8, 1.6, 7.0, 5.8, 'SSW', 46, 'SSW', 'S', 20, 22, 75, 58, 1018.6, 1018.3, 7, 7, 22.3, 25.8, 'Yes', 'No'), ('3/7/2014', 19.3, 26.9, 0.2, 5.2, 7.5, 'NNE', 31, 'WNW', 'E', 13, 20, 69, 64, 1020.3, 1018.7, 4, 5, 23.0, 25.7, 'No', 'No'), ('3/8/2014', 21.6, 27.2, 0.0, 5.6, 8.9, 'ESE', 39, 'NNE', 'ESE', 13, 22, 63, 64, 1022.6, 1021.5, 7, 2, 23.8, 24.7, 'No', 'No'), ('3/9/2014', 19.6, 27.1, 0.0, 6.4, 11.1, 'E', 31, 'W', 'E', 6, 20, 68, 53, 1023.6, 1020.9, 4, 3, 22.8, 25.7, 'No', 'No'), ('3/10/2014', 21.9, 27.5, 0.2, 6.8, 11.0, 'ENE', 37, 'NNE', 'E', 11, 26, 60, 55, 1023.4, 1021.5, 3, 2, 25.6, 26.4, 'No', 'No'), ('3/11/2014', 19.6, 27.8, 0.0, 8.6, 10.8, 'NE', 35, 'W', 'NE', 9, 20, 67, 46, 1023.6, 1021.3, 1, 1, 22.8, 26.3, 'No', 'No'), ('3/12/2014', 19.2, 29.2, 0.0, 8.2, 6.2, 'SE', 37, 'WNW', 'E', 7, 11, 69, 52, 1018.1, 1015.4, 6, 7, 22.1, 27.6, 'No', 'Yes'), ('3/13/2014', 18.5, 27.0, 27.8, 7.0, 6.2, 'S', 44, 'SW', 'SE', 15, 15, 81, 56, 1020.4, 1018.2, 6, 3, 19.6, 26.0, 'Yes', 'No'), ('3/14/2014', 19.3, 26.3, 0.2, 4.0, 7.9, 'NNE', 43, 'NNW', 'ENE', 7, 30, 70, 55, 1018.4, 1014.7, 6, 1, 22.7, 25.2, 'No', 'No'), ('3/15/2014', 19.5, 26.6, 0.0, 7.8, 5.8, 'WSW', 91, 'NNW', 'NE', 7, 17, 64, 62, 1013.0, 1008.4, 4, 7, 22.5, 25.8, 'No', 'Yes'), ('3/16/2014', 19.2, 29.3, 5.4, 5.8, 5.8, 'W', 57, 'WNW', 'WNW', 9, 13, 57, 74, 1005.5, 1004.7, 2, 7, 24.2, 22.5, 'Yes', 'Yes'), ('3/17/2014', 15.1, 28.0, 5.0, 6.2, 11.2, 'NNE', 35, 'W', 'ENE', 15, 26, 47, 25, 1016.9, 1015.0, 1, 1, 19.4, 27.5, 'Yes', 'No'), ('3/18/2014', 16.1, 29.7, 0.2, 7.2, 10.4, 'NE', 31, 'W', 'NE', 19, 19, 58, 33, 1021.0, 1018.7, 1, 5, 19.9, 28.7, 'No', 'No'), ('3/19/2014', 19.6, 27.9, 0.0, 6.6, 10.1, 'S', 48, 'SSW', 'SSE', 13, 26, 66, 57, 1023.9, 1023.6, 1, 6, 23.9, 27.8, 'No', 'No'), ('3/20/2014', 21.7, 27.0, 0.0, 6.2, 9.2, 'E', 33, 'W', 'E', 0, 22, 58, 54, 1026.9, 1024.2, 3, 3, 25.5, 26.4, 'No', 'No'), ('3/21/2014', 20.4, 26.8, 1.0, 6.0, 5.2, 'NE', 39, 'NNE', 'ENE', 6, 19, 75, 58, 1022.5, 1018.9, 7, 4, 21.7, 25.2, 'No', 'No'), ('3/22/2014', 18.7, 26.7, 0.0, 6.0, 9.5, 'SSW', 37, 'ESE', 'ENE', 6, 20, 68, 60, 1017.8, 1014.5, 3, 2, 23.6, 25.7, 'No', 'No'), ('3/23/2014', 20.3, 27.0, 0.0, 5.2, 7.2, 'NNW', 41, 'SE', 'ENE', 6, 19, 70, 63, 1017.6, 1013.2, 3, 7, 23.0, 25.7, 'No', 'No'), ('3/24/2014', 20.1, 23.2, 0.4, 6.2, 0.0, 'W', 54, 'SSW', 'W', 24, 31, 79, 89, 1016.4, 1015.3, 8, 8, 20.3, 17.5, 'No', 'Yes'), ('3/25/2014', 17.1, 25.2, 6.8, 4.2, 6.5, 'ESE', 35, 'W', 'ESE', 11, 9, 82, 67, 1020.0, 1019.6, 1, 7, 19.8, 24.7, 'Yes', 'No'), ('3/26/2014', 19.7, 24.9, 0.6, 2.8, 0.0, 'NE', 37, 'WNW', 'E', 11, 9, 89, 72, 1022.5, 1021.2, 7, 7, 21.2, 24.4, 'No', 'Yes'), ('3/27/2014', 20.6, 22.2, 18.0, 2.8, 0.0, 'N', 35, 'NNE', 'N', 2, 7, 89, 77, 1022.3, 1020.0, 8, 8, 21.2, 20.3, 'Yes', 'Yes'), ('3/28/2014', 18.0, 24.7, 7.4, 1.0, 0.0, 'WSW', 26, 'WNW', 'WSW', 13, 11, 84, 66, 1017.0, 1013.3, 7, 8, 18.7, 24.3, 'Yes', 'No'), ('3/29/2014', 18.7, 25.7, 0.8, 3.6, 5.6, 'SSE', 41, 'W', 'SSE', 15, 24, 80, 59, 1015.3, 1015.0, 6, 7, 20.6, 24.4, 'No', 'No'), ('3/30/2014', 19.4, 27.0, 0.2, 3.6, 10.1, 'SE', 35, 'WNW', 'ESE', 11, 22, 69, 55, 1020.1, 1019.2, 3, 3, 22.4, 27.0, 'No', 'Yes'), ('3/31/2014', 17.5, 25.0, 3.6, 5.0, 10.2, 'W', 26, 'WNW', 'ESE', 15, 15, 79, 64, 1022.4, 1019.7, 3, 6, 19.6, 23.5, 'Yes', 'No'), ('4/1/2014', 17.5, 26.4, 0.0, 3.2, 6.2, 'NNE', 31, 'WNW', 'ENE', 13, 17, 78, 66, 1019.7, 1017.5, 7, 7, 20.5, 24.6, 'No', 'No'), ('4/2/2014', 18.1, 26.0, 0.0, 4.8, 10.9, 'E', 26, 'WNW', 'E', 11, 20, 91, 67, 1017.9, 1014.6, 2, 1, 18.9, 24.7, 'No', 'No'), ('4/3/2014', 18.9, 26.3, 0.0, 3.0, 8.8, 'SSW', 31, 'WNW', 'E', 13, 24, 82, 70, 1017.5, 1015.0, 1, 7, 21.3, 25.1, 'No', 'No'), ('4/4/2014', 19.9, 22.3, 0.0, 6.0, 0.0, 'S', 43, 'SSW', 'S', 11, 19, 82, 74, 1018.5, 1016.5, 8, 8, 20.4, 21.5, 'No', 'Yes'), ('4/5/2014', 18.0, 26.0, 5.6, 9.2, 6.4, 'SSW', 50, 'WNW', 'SSE', 13, 24, 80, 63, 1018.8, 1016.9, 7, 3, 20.6, 23.8, 'Yes', 'Yes'), ('4/6/2014', 17.2, 21.7, 3.4, 4.6, 1.1, 'SSW', 48, 'SW', 'SW', 9, 7, 86, 86, 1020.9, 1020.8, 7, 8, 19.2, 19.5, 'Yes', 'Yes'), ('4/7/2014', 15.3, 22.4, 16.0, 4.2, 3.3, 'SSE', 39, 'WSW', 'SSE', 13, 9, 83, 63, 1025.5, 1023.6, 6, 6, 16.9, 21.1, 'Yes', 'Yes'), ('4/8/2014', 17.2, 23.2, 5.0, 5.2, 1.2, 'W', 22, 'WNW', 'E', 13, 13, 77, 53, 1023.9, 1020.1, 7, 6, 19.6, 22.9, 'Yes', 'No'), ('4/9/2014', 15.9, 24.1, 0.0, 0.4, 4.6, 'ENE', 22, 'WNW', 'E', 13, 17, 68, 58, 1021.4, 1017.9, 7, 7, 20.4, 23.2, 'No', 'No'), ('4/10/2014', 17.8, 24.7, 0.0, 2.6, 0.0, 'W', 17, 'W', 'E', 11, 7, 74, 82, 1016.9, 1012.7, 7, 8, 20.2, 20.0, 'No', 'Yes'), ('4/11/2014', 18.9, 28.0, 5.6, 1.6, 3.7, 'NW', 37, 'NW', 'SW', 22, 9, 64, 55, 1005.5, 1002.9, 5, 7, 24.1, 25.7, 'Yes', 'Yes'), ('4/12/2014', 17.9, 21.0, 5.0, 3.8, 0.7, 'SSW', 54, 'SW', 'SSW', 26, 22, 76, 74, 1011.1, 1011.9, 7, 6, 19.1, 20.0, 'Yes', 'Yes'), ('4/13/2014', 16.0, 20.6, 3.8, 1.4, 1.0, 'SSE', 52, 'SW', 'S', 20, 15, 86, 88, 1016.8, 1016.1, 7, 7, 17.8, 18.5, 'Yes', 'Yes'), ('4/14/2014', 13.5, 21.0, 2.8, 3.6, 3.3, 'SSW', 41, 'W', 'S', 20, 15, 64, 69, 1020.4, 1018.8, 6, 5, 17.2, 19.4, 'Yes', 'Yes'), ('4/15/2014', 13.4, 21.9, 4.2, 3.4, 3.5, 'SSE', 50, 'W', 'S', 22, 28, 58, 64, 1020.7, 1018.4, 7, 8, 17.3, 20.8, 'Yes', 'Yes'), ('4/16/2014', 14.3, 23.3, 29.6, 3.2, 9.0, 'SW', 43, 'W', 'S', 20, 22, 69, 57, 1019.8, 1017.3, 5, 3, 17.7, 21.9, 'Yes', 'No'), ('4/17/2014', 13.1, 23.7, 0.0, 5.2, 9.0, 'SSE', 41, 'W', 'SSE', 19, 22, 65, 39, 1019.6, 1017.4, 5, 1, 17.2, 23.1, 'No', 'No'), ('4/18/2014', 13.5, 26.5, 0.0, 2.2, 10.8, 'WSW', 35, 'WNW', 'WNW', 15, 13, 68, 31, 1016.3, 1011.7, 2, 3, 16.7, 26.1, 'No', 'No'), ('4/19/2014', 15.0, 22.7, 0.0, 3.8, 10.7, 'SSE', 41, 'SSW', 'SSE', 17, 22, 60, 42, 1016.4, 1014.8, 1, 1, 19.2, 20.8, 'No', 'No'), ('4/20/2014', 13.2, 22.9, 0.0, 5.2, 10.4, 'WSW', 28, 'W', 'ENE', 17, 17, 61, 56, 1018.4, 1014.7, 3, 1, 16.3, 21.9, 'No', 'No'), ('4/21/2014', 13.2, 25.3, 0.0, 4.0, 9.7, 'W', 35, 'W', 'ESE', 20, 15, 48, 31, 1021.1, 1018.5, 1, 3, 15.9, 24.4, 'No', 'No'), ('4/22/2014', 12.4, 25.8, 0.0, 4.0, 7.9, 'W', 20, 'WNW', 'W', 17, 11, 67, 32, 1018.7, 1014.9, 7, 7, 15.8, 24.4, 'No', 'No'), ('4/23/2014', 13.4, 26.1, 0.0, 4.2, 9.0, 'W', 24, 'W', 'ESE', 20, 13, 59, 36, 1017.6, 1014.9, 7, 3, 17.6, 24.0, 'No', 'No'), ('4/24/2014', 14.1, 29.9, 0.0, 3.8, 9.1, 'SE', 41, 'WNW', 'WNW', 15, 6, 53, 28, 1013.7, 1011.3, 6, 7, 19.3, 28.9, 'No', 'Yes'), ('4/25/2014', 17.6, 20.9, 6.8, 4.6, 3.2, 'SSE', 39, 'S', 'ENE', 7, 15, 84, 67, 1023.2, 1019.2, 8, 1, 17.7, 20.7, 'Yes', 'Yes'), ('4/26/2014', 15.5, 23.1, 9.2, 2.0, 1.2, 'S', 30, 'N', 'WNW', 7, 6, 72, 63, 1015.0, 1011.5, 7, 7, 18.2, 22.6, 'Yes', 'No'), ('4/27/2014', 16.9, 17.9, 0.4, 2.2, 0.0, 'SSW', 35, 'SSE', 'S', 19, 15, 83, 87, 1023.5, 1023.1, 5, 7, 17.9, 17.0, 'No', 'Yes'), ('4/28/2014', 15.0, 20.6, 20.2, 1.0, 2.8, 'W', 20, 'W', 'NNE', 11, 11, 75, 67, 1025.9, 1022.1, 6, 6, 17.4, 20.4, 'Yes', 'No'), ('4/29/2014', 14.9, 25.7, 0.0, 3.0, 8.5, 'NNW', 31, 'NNW', 'NE', 13, 15, 71, 61, 1017.7, 1013.3, 1, 7, 18.4, 23.6, 'No', 'Yes'), ('4/30/2014', 18.2, 25.3, 3.4, 5.0, 7.1, 'WSW', 44, 'WSW', 'SSW', 15, 20, 83, 28, 1012.5, 1011.4, 7, 2, 18.6, 24.3, 'Yes', 'No'), ('5/1/2014', 11.3, 23.0, 0.0, 5.2, 10.2, 'W', 31, 'W', 'ESE', 19, 15, 59, 44, 1017.7, 1013.8, 1, 1, 14.7, 19.6, 'No', 'No'), ('5/2/2014', 13.3, 22.2, 0.0, 2.8, 7.3, 'W', 46, 'W', 'W', 17, 19, 71, 35, 1006.9, 1001.9, 2, 6, 16.1, 21.5, 'No', 'Yes'), ('5/3/2014', 11.7, 15.7, 1.2, 5.6, 1.1, 'W', 57, 'NW', 'W', 13, 35, 81, 46, 996.5, 994.8, 7, 7, 12.7, 14.8, 'Yes', 'Yes'), ('5/4/2014', 10.8, 20.5, 3.8, 3.8, 8.5, 'W', 54, 'W', 'W', 20, 31, 61, 31, 1001.9, 1003.7, 5, 1, 15.0, 19.3, 'Yes', 'No'), ('5/5/2014', 10.3, 20.9, 0.0, 5.4, 10.4, 'W', 39, 'W', 'NW', 22, 7, 54, 32, 1017.9, 1016.8, 1, 3, 12.8, 20.2, 'No', 'No'), ('5/6/2014', 10.7, 23.4, 0.0, 3.4, 8.2, 'W', 39, 'W', 'ENE', 26, 6, 58, 35, 1021.2, 1018.5, 5, 3, 14.6, 21.6, 'No', 'No'), ('5/7/2014', 11.2, 20.7, 0.0, 3.2, 9.7, 'S', 43, 'W', 'S', 20, 20, 59, 41, 1023.8, 1022.9, 3, 2, 13.9, 19.3, 'No', 'No'), ('5/8/2014', 11.1, 21.0, 0.0, 5.8, 6.2, 'SSW', 46, 'W', 'SSE', 19, 19, 66, 65, 1026.2, 1024.3, 2, 6, 14.2, 18.2, 'No', 'Yes'), ('5/9/2014', 11.8, 21.9, 7.4, 3.0, 3.0, 'W', 26, 'WNW', 'E', 9, 13, 84, 62, 1026.3, 1023.6, 4, 7, 13.9, 18.8, 'Yes', 'No'), ('5/10/2014', 12.0, 24.8, 0.4, 2.2, 5.2, 'NW', 35, 'W', 'N', 13, 13, 80, 51, 1023.9, 1020.0, 3, 7, 14.5, 21.4, 'No', 'No'), ('5/11/2014', 14.4, 22.9, 0.8, 2.0, 8.3, 'SSE', 41, 'W', 'SSW', 15, 20, 76, 59, 1022.2, 1022.1, 1, 3, 16.7, 19.9, 'No', 'No'), ('5/12/2014', 12.6, 23.0, 0.0, 4.0, 8.8, 'SSE', 37, 'W', 'S', 17, 20, 73, 51, 1030.1, 1028.5, 3, 2, 16.7, 22.7, 'No', 'Yes'), ('5/13/2014', 13.7, 23.0, 11.2, 4.8, 8.8, 'W', 26, 'W', 'E', 20, 9, 74, 52, 1030.5, 1027.2, 1, 3, 15.6, 21.0, 'Yes', 'No'), ('5/14/2014', 12.6, 23.2, 0.2, 1.8, 9.5, 'ENE', 28, 'WNW', 'NE', 13, 17, 78, 54, 1029.3, 1025.8, 1, 2, 14.8, 21.4, 'No', 'No'), ('5/15/2014', 11.7, 22.9, 0.0, 4.0, 10.0, 'WNW', 24, 'W', 'E', 15, 13, 82, 51, 1028.7, 1025.3, 1, 1, 13.7, 21.5, 'No', 'No'), ('5/16/2014', 12.0, 25.3, 0.0, 3.2, 9.9, 'W', 28, 'W', 'ENE', 19, 13, 75, 40, 1029.4, 1027.0, 0, 1, 14.6, 23.3, 'No', 'No'), ('5/17/2014', 12.0, 24.2, 0.0, 4.0, 9.1, 'NNE', 26, 'WNW', 'ENE', 11, 13, 72, 55, 1030.4, 1026.7, 6, 3, 14.3, 22.4, 'No', 'No'), ('5/18/2014', 13.0, 24.8, 0.0, 3.4, 2.8, 'W', 20, 'W', 'W', 15, 7, 69, 41, 1028.3, 1025.2, 7, 7, 14.8, 24.4, 'No', 'No'), ('5/19/2014', 13.1, 26.1, 0.0, 2.4, 7.5, 'WNW', 24, 'W', 'WNW', 19, 7, 72, 33, 1026.0, 1022.4, 7, 1, 15.8, 25.8, 'No', 'No'), ('5/20/2014', 14.4, 25.5, 0.0, 3.2, 4.7, 'W', 24, 'W', 'WNW', 17, 7, 69, 41, 1022.9, 1019.6, 7, 7, 16.2, 25.2, 'No', 'No'), ('5/21/2014', 14.8, 23.5, 0.0, 3.6, 9.8, 'W', 26, 'WNW', 'ESE', 13, 13, 66, 58, 1024.4, 1022.6, 2, 2, 17.5, 22.6, 'No', 'No'), ('5/22/2014', 13.1, 27.1, 0.0, 2.2, 9.4, 'W', 24, 'W', 'W', 13, 6, 82, 30, 1023.5, 1018.7, 1, 1, 14.9, 26.8, 'No', 'No'), ('5/23/2014', 13.9, 25.1, 0.0, 4.0, 8.0, 'W', 22, 'W', 'WNW', 11, 13, 64, 41, 1017.9, 1013.0, 3, 5, 16.5, 23.8, 'No', 'No'), ('5/24/2014', 15.7, 25.2, 0.0, 4.8, 7.4, 'WSW', 35, 'W', 'SSW', 13, 15, 62, 45, 1015.4, 1014.0, 2, 6, 17.7, 22.6, 'No', 'No'), ('5/25/2014', 15.5, 26.9, 0.0, 3.4, 7.1, 'W', 26, 'W', 'ESE', 19, 17, 75, 43, 1018.3, 1017.1, 5, 2, 17.2, 24.9, 'No', 'No'), ('5/26/2014', 14.1, 23.6, 0.0, 3.4, 9.4, 'NNE', 30, 'WNW', 'ENE', 13, 17, 81, 59, 1023.4, 1020.9, 6, 6, 16.3, 23.3, 'No', 'No'), ('5/27/2014', 16.0, 24.0, 0.0, 2.6, 3.0, 'N', 48, 'NNE', 'NNE', 11, 26, 68, 46, 1018.0, 1010.8, 7, 7, 19.4, 23.8, 'No', 'No'), ('5/28/2014', 17.1, 24.1, 0.0, 5.6, 9.6, 'NW', 48, 'NW', 'WNW', 22, 26, 54, 31, 1013.8, 1013.5, 1, 1, 19.3, 23.2, 'No', 'No'), ('5/29/2014', 12.8, 21.3, 0.0, 5.4, 7.7, 'S', 35, 'W', 'S', 20, 22, 59, 61, 1023.1, 1022.1, 2, 5, 15.3, 19.7, 'No', 'No'), ('5/30/2014', 14.5, 21.4, 0.0, 4.4, 5.2, 'SSW', 33, 'W', 'S', 19, 17, 71, 58, 1026.8, 1024.5, 6, 3, 15.9, 20.7, 'No', 'Yes'), ('5/31/2014', 14.3, 20.7, 2.4, 1.0, 7.5, 'NNE', 31, 'WNW', 'ENE', 15, 17, 86, 61, 1026.9, 1022.8, 5, 4, 15.2, 20.0, 'Yes', 'Yes'), ('6/1/2014', 14.8, 20.7, 11.2, 5.0, 0.4, 'W', 46, 'NW', 'W', 7, 26, 87, 70, 1020.5, 1018.0, 7, 8, 17.0, 17.8, 'Yes', 'No'), ('6/2/2014', 12.4, 22.3, 1.0, 2.0, 5.9, 'W', 30, 'W', 'WNW', 11, 9, 85, 54, 1017.2, 1014.9, 7, 3, 14.5, 19.9, 'No', 'No'), ('6/3/2014', 10.5, 20.3, 0.0, 1.8, 9.9, 'W', 39, 'WSW', 'WNW', 9, 17, 70, 42, 1018.4, 1016.2, 1, 1, 13.2, 19.5, 'No', 'No'), ('6/4/2014', 11.2, 22.3, 0.0, 3.6, 9.6, 'W', 33, 'W', 'SSE', 24, 13, 69, 53, 1024.1, 1022.9, 1, 3, 13.6, 22.0, 'No', 'Yes'), ('6/5/2014', 13.6, 19.8, 8.6, 4.0, 0.4, 'SSE', 30, 'W', 'SSW', 19, 11, 91, 80, 1025.7, 1024.1, 8, 7, 15.3, 18.0, 'Yes', 'Yes'), ('6/6/2014', 14.5, 15.5, 13.2, 7.2, 0.5, 'S', 48, 'SSW', 'SSW', 22, 17, 86, 85, 1026.3, 1024.8, 7, 7, 15.3, 14.9, 'Yes', 'Yes'), ('6/7/2014', 10.1, 19.4, 6.8, 2.4, 7.8, 'SSW', 39, 'W', 'SSW', 26, 19, 67, 60, 1027.2, 1025.0, 2, 6, 12.2, 17.8, 'Yes', 'No'), ('6/8/2014', 10.5, 17.7, 0.0, 3.6, 6.3, 'SSE', 46, 'W', 'SSW', 17, 24, 65, 59, 1026.9, 1025.8, 3, 7, 11.9, 16.0, 'No', 'Yes'), ('6/9/2014', 8.6, 18.4, 2.2, 2.6, 5.1, 'SSE', 46, 'W', 'SE', 22, 17, 71, 73, 1028.4, 1027.3, 1, 7, 10.4, 16.9, 'Yes', 'Yes'), ('6/10/2014', 10.4, 19.2, 13.8, 2.0, 3.6, 'SSE', 31, 'W', 'SE', 20, 19, 91, 49, 1030.5, 1027.4, 7, 1, 13.0, 18.8, 'Yes', 'Yes'), ('6/11/2014', 10.4, 19.6, 5.6, 2.2, 5.6, 'W', 24, 'WNW', 'SSE', 19, 9, 86, 62, 1026.6, 1022.8, 6, 6, 11.9, 17.7, 'Yes', 'No'), ('6/12/2014', 11.1, 20.4, 0.0, 1.0, 5.8, 'W', 30, 'W', 'NNE', 15, 9, 86, 52, 1022.0, 1018.9, 7, 6, 12.1, 19.5, 'No', 'No'), ('6/13/2014', 10.7, 20.9, 0.0, 2.4, 3.3, 'N', 28, 'W', 'N', 15, 15, 85, 48, 1019.4, 1015.0, 7, 7, 11.8, 20.4, 'No', 'Yes'), ('6/14/2014', 11.8, 19.9, 5.0, 2.4, 3.9, 'W', 31, 'WNW', 'W', 17, 19, 89, 53, 1012.1, 1009.2, 8, 2, 14.3, 19.2, 'Yes', 'No'), ('6/15/2014', 10.3, 17.2, 0.2, 2.6, 1.2, 'W', 54, 'NW', 'WSW', 13, 22, 65, 49, 1008.9, 1008.3, 7, 7, 13.0, 16.9, 'No', 'No'), ('6/16/2014', 9.3, 19.5, 0.4, 0.8, 9.7, 'SW', 44, 'W', 'WNW', 15, 11, 78, 36, 1020.8, 1018.4, 1, 1, 11.3, 19.4, 'No', 'No'), ('6/17/2014', 10.0, 19.8, 0.0, 4.4, 9.1, 'WSW', 43, 'W', 'SSW', 20, 19, 63, 46, 1023.4, 1024.0, 1, 5, 13.5, 17.8, 'No', 'No'), ('6/18/2014', 11.4, 20.4, 0.0, 1.8, 9.4, 'W', 35, 'W', 'ESE', 22, 11, 67, 51, 1030.1, 1027.9, 1, 1, 12.5, 18.7, 'No', 'No'), ('6/19/2014', 10.6, 21.5, 0.0, 1.8, 8.5, 'W', 24, 'WNW', 'NE', 15, 13, 81, 57, 1027.8, 1022.9, 3, 3, 12.0, 19.8, 'No', 'No'), ('6/20/2014', 12.0, 21.3, 0.0, 4.6, 6.3, 'WSW', 28, 'N', 'W', 6, 6, 66, 54, 1019.9, 1015.9, 2, 6, 15.5, 19.6, 'No', 'No'), ('6/21/2014', 10.5, 21.9, 0.0, 2.4, 9.5, 'W', 30, 'WNW', 'W', 22, 11, 79, 31, 1020.4, 1018.5, 1, 1, 11.8, 21.4, 'No', 'No'), ('6/22/2014', 11.1, 19.7, 0.0, 3.4, 4.4, 'W', 26, 'WNW', 'NNE', 15, 4, 79, 49, 1023.0, 1020.0, 7, 1, 11.9, 19.6, 'No', 'No'), ('6/23/2014', 10.0, 16.6, 0.0, 0.6, 1.8, 'N', 37, 'NNW', 'N', 15, 22, 76, 57, 1014.9, 1008.6, 7, 7, 13.5, 15.8, 'No', 'No'), ('6/24/2014', 11.5, 16.7, 0.0, 6.2, 9.7, 'WNW', 81, 'NW', 'WNW', 28, 33, 47, 35, 1007.1, 1003.4, 1, 1, 12.1, 16.1, 'No', 'No'), ('6/25/2014', 11.1, 18.1, 0.0, 4.0, 9.7, 'W', 76, 'W', 'W', 31, 39, 45, 35, 1012.2, 1012.8, 1, 1, 14.8, 17.7, 'No', 'No'), ('6/26/2014', 10.7, 22.2, 0.0, 4.8, 9.8, 'WNW', 41, 'WNW', 'WNW', 17, 15, 47, 31, 1018.8, 1017.9, 1, 5, 15.1, 21.1, 'No', 'No'), ('6/27/2014', 10.4, 21.2, 0.0, 4.0, 8.1, 'N', 30, 'NW', 'NNE', 11, 9, 68, 39, 1021.0, 1015.1, 7, 7, 12.1, 20.4, 'No', 'No'), ('6/28/2014', 12.0, 22.8, 0.0, 5.0, 6.9, 'W', 96, 'N', 'NW', 28, 20, 36, 34, 1007.2, 999.9, 7, 2, 15.8, 20.3, 'No', 'No'), ('6/29/2014', 10.0, 16.4, 0.0, 7.0, 9.6, 'NW', 69, 'NW', 'NW', 28, 28, 45, 37, 1004.5, 1004.8, 1, 3, 12.1, 15.5, 'No', 'No'), ('6/30/2014', 9.4, 16.1, 0.0, 3.8, 9.4, 'WSW', 50, 'W', 'WSW', 24, 22, 53, 29, 1015.1, 1015.7, 1, 1, 11.4, 16.0, 'No', 'No'), ('7/1/2014', 8.9, 19.1, 0.0, 3.0, 9.3, 'W', 33, 'W', 'W', 20, 7, 64, 36, 1025.0, 1024.0, 1, 1, 10.1, 18.3, 'No', 'No'), ('7/2/2014', 7.4, 20.2, 0.0, 3.8, 9.6, 'W', 37, 'W', 'SSE', 28, 13, 67, 36, 1027.6, 1025.2, 1, 1, 9.6, 19.2, 'No', 'No'), ('7/3/2014', 6.7, 18.3, 0.0, 1.2, 9.6, 'W', 28, 'W', 'ENE', 19, 13, 71, 54, 1027.3, 1023.3, 1, 1, 9.1, 17.2, 'No', 'No'), ('7/4/2014', 6.7, 20.4, 0.0, 2.4, 9.9, 'NW', 30, 'W', 'ESE', 9, 7, 71, 33, 1021.3, 1016.6, 0, 1, 9.3, 19.6, 'No', 'No'), ('7/5/2014', 8.2, 18.0, 0.0, 3.6, 9.6, 'W', 48, 'W', 'WNW', 17, 28, 62, 33, 1016.2, 1012.0, 1, 1, 10.1, 17.3, 'No', 'No'), ('7/6/2014', 8.2, 18.1, 0.0, 4.0, 9.9, 'W', 43, 'W', 'WSW', 17, 24, 59, 36, 1013.6, 1010.8, 1, 1, 11.6, 16.2, 'No', 'No'), ('7/7/2014', 8.3, 19.5, 0.0, 3.0, 9.2, 'W', 43, 'W', 'WSW', 17, 19, 59, 35, 1014.4, 1011.9, 1, 2, 10.7, 18.8, 'No', 'No'), ('7/8/2014', 7.9, 18.7, 0.0, 3.8, 9.7, 'W', 33, 'W', 'E', 20, 6, 66, 51, 1016.6, 1012.2, 1, 1, 9.0, 16.2, 'No', 'No'), ('7/9/2014', 6.6, 21.3, 0.0, 2.6, 9.4, 'W', 67, 'NNW', 'NNE', 11, 22, 49, 22, 1007.6, 999.6, 0, 1, 11.9, 20.7, 'No', 'No'), ('7/10/2014', 8.8, 17.3, 0.2, 5.8, 9.8, 'WNW', 61, 'WNW', 'W', 15, 37, 52, 32, 1005.8, 1005.1, 1, 2, 11.9, 16.8, 'No', 'No'), ('7/11/2014', 9.0, 18.5, 0.0, 4.0, 9.9, 'W', 35, 'WNW', 'W', 17, 19, 58, 32, 1017.4, 1016.0, 1, 0, 11.8, 18.2, 'No', 'No'), ('7/12/2014', 6.4, 18.5, 0.2, 3.4, 9.5, 'W', 44, 'WNW', 'WSW', 11, 26, 64, 33, 1019.6, 1017.1, 0, 1, 8.9, 17.7, 'No', 'No'), ('7/13/2014', 6.5, 16.3, 0.0, 3.6, 9.6, 'S', 46, 'W', 'S', 28, 24, 54, 47, 1027.4, 1027.3, 1, 3, 8.2, 15.1, 'No', 'No'), ('7/14/2014', 6.6, 17.9, 0.0, 3.2, 5.1, 'W', 35, 'W', 'SSW', 17, 19, 62, 64, 1032.0, 1029.0, 6, 6, 9.2, 15.7, 'No', 'Yes'), ('7/15/2014', 9.2, 15.6, 1.6, 0.4, 0.0, 'W', 22, 'W', 'E', 13, 2, 88, 74, 1025.8, 1021.3, 7, 8, 11.5, 15.3, 'Yes', 'Yes'), ('7/16/2014', 11.4, 18.5, 1.8, 1.2, 3.9, 'W', 41, 'ENE', 'W', 4, 20, 86, 52, 1013.7, 1010.7, 8, 2, 13.2, 17.9, 'Yes', 'No'), ('7/17/2014', 9.5, 19.9, 0.0, 2.0, 9.4, 'W', 56, 'NW', 'WNW', 20, 26, 56, 33, 1012.6, 1008.6, 1, 3, 13.1, 19.1, 'No', 'No'), ('7/18/2014', 8.6, 15.9, 0.0, 4.0, 7.9, 'WSW', 63, 'W', 'WSW', 28, 39, 47, 35, 1011.2, 1011.1, 2, 4, 9.6, 14.1, 'No', 'No'), ('7/19/2014', 8.5, 14.9, 0.0, 4.6, 3.2, 'SW', 70, 'W', 'SSW', 26, 24, 50, 57, 1021.2, 1021.4, 6, 6, 10.1, 13.6, 'No', 'No'), ('7/20/2014', 9.8, 15.3, 0.2, 4.0, 1.1, 'SSW', 54, 'W', 'S', 20, 22, 66, 60, 1025.7, 1024.9, 7, 7, 11.2, 15.2, 'No', 'No'), ('7/21/2014', 8.9, 18.3, 0.0, 2.0, 7.5, 'W', 31, 'W', 'SSE', 22, 17, 69, 64, 1026.9, 1023.3, 7, 7, 9.9, 15.7, 'No', 'No'), ('7/22/2014', 8.7, 19.0, 0.0, 1.4, 9.6, 'W', 24, 'W', 'SE', 22, 11, 81, 59, 1024.6, 1022.3, 2, 2, 10.8, 16.5, 'No', 'No'), ('7/23/2014', 8.9, 18.9, 0.0, 3.2, 6.7, 'W', 22, 'WNW', 'ESE', 17, 13, 87, 57, 1025.5, 1021.6, 3, 5, 10.7, 17.1, 'No', 'No'), ('7/24/2014', 8.5, 19.8, 0.0, 0.6, 2.4, 'N', 20, 'WNW', 'N', 11, 9, 83, 48, 1022.5, 1019.2, 5, 7, 10.9, 19.7, 'No', 'No'), ('7/25/2014', 9.6, 18.8, 0.0, 2.8, 2.6, 'W', 52, 'NW', 'N', 9, 15, 82, 59, 1023.0, 1019.9, 7, 7, 11.5, 18.3, 'No', 'Yes'), ('7/26/2014', 11.3, 18.7, 8.2, 2.0, 4.2, 'W', 43, 'WNW', 'WNW', 22, 24, 90, 42, 1024.9, 1020.4, 8, 3, 13.0, 17.2, 'Yes', 'Yes'), ('7/27/2014', 9.4, 21.0, 4.2, 1.8, 10.2, 'W', 31, 'W', 'ESE', 20, 15, 65, 38, 1024.6, 1021.5, 1, 1, 11.9, 18.7, 'Yes', 'No'), ('7/28/2014', 8.8, 18.5, 0.0, 3.2, 6.7, 'WSW', 46, 'W', 'WNW', 15, 15, 62, 41, 1021.3, 1018.1, 7, 6, 11.9, 17.4, 'No', 'No'), ('7/29/2014', 11.8, 23.3, 0.0, 4.0, 5.1, 'NNW', 44, 'WNW', 'NNE', 22, 20, 49, 27, 1018.0, 1013.2, 7, 1, 14.9, 22.9, 'No', 'No'), ('7/30/2014', 13.0, 24.0, 0.0, 6.2, 10.2, 'NW', 41, 'WNW', 'WNW', 13, 22, 44, 31, 1018.0, 1014.5, 6, 1, 17.3, 23.3, 'No', 'No'), ('7/31/2014', 13.9, 25.0, 0.0, 6.6, 10.1, 'NNW', 61, 'NNW', 'NW', 24, 35, 40, 21, 1014.2, 1007.3, 1, 0, 17.7, 24.5, 'No', 'No'), ('8/1/2014', 15.9, 18.2, 0.0, 8.4, 10.0, 'W', 72, 'WNW', 'W', 22, 28, 41, 23, 1007.2, 1008.7, 1, 1, 16.8, 16.7, 'No', 'No'), ('8/2/2014', 7.2, 16.1, 0.0, 6.4, 10.0, 'W', 46, 'W', 'S', 28, 28, 45, 36, 1024.6, 1026.8, 1, 1, 9.6, 15.0, 'No', 'No'), ('8/3/2014', 5.5, 17.6, 0.0, 3.8, 9.5, 'W', 28, 'W', 'ESE', 20, 15, 60, 45, 1034.1, 1032.2, 1, 1, 8.4, 16.5, 'No', 'No'), ('8/4/2014', 6.4, 17.2, 0.0, 2.6, 10.1, 'E', 26, 'WNW', 'E', 17, 20, 69, 58, 1034.4, 1030.4, 3, 4, 9.9, 16.0, 'No', 'No'), ('8/5/2014', 7.9, 20.6, 0.0, 1.6, 10.2, 'SSE', 33, 'W', 'SSE', 17, 17, 75, 40, 1032.0, 1030.1, 0, 1, 10.0, 17.5, 'No', 'No'), ('8/6/2014', 6.5, 22.4, 0.0, 2.6, 10.1, 'W', 35, 'W', 'NE', 20, 11, 64, 43, 1032.6, 1026.2, 1, 1, 9.7, 20.1, 'No', 'No'), ('8/7/2014', 9.6, 20.4, 0.0, 4.6, 6.8, 'W', 41, 'W', 'SE', 28, 13, 53, 36, 1029.6, 1027.5, 6, 1, 11.4, 18.8, 'No', 'No'), ('8/8/2014', 9.1, 18.1, 0.0, 2.6, 4.0, 'WNW', 24, 'W', 'ESE', 17, 15, 76, 64, 1032.1, 1029.6, 7, 3, 10.9, 16.9, 'No', 'No'), ('8/9/2014', 8.9, 19.2, 0.0, 1.8, 6.8, 'NE', 26, 'W', 'NE', 13, 15, 94, 62, 1029.9, 1024.7, 8, 3, 10.2, 18.6, 'No', 'No'), ('8/10/2014', 9.9, 23.2, 0.0, 3.0, 3.5, 'SW', 31, 'W', 'WNW', 9, 9, 46, 27, 1022.4, 1017.6, 6, 1, 12.7, 22.7, 'No', 'No'), ('8/11/2014', 8.1, 14.4, 0.0, 3.4, 4.5, 'SSE', 48, 'W', 'S', 15, 24, 62, 45, 1025.4, 1025.1, 7, 5, 10.3, 13.7, 'No', 'Yes'), ('8/12/2014', 6.3, 15.4, 21.4, 5.6, 3.9, 'S', 44, 'W', 'SW', 17, 11, 84, 78, 1030.0, 1028.2, 7, 7, 8.9, 12.3, 'Yes', 'Yes'), ('8/13/2014', 7.9, 17.0, 19.4, 3.6, 10.1, 'SSW', 37, 'W', 'SSE', 19, 20, 77, 46, 1033.3, 1031.9, 2, 2, 10.5, 16.2, 'Yes', 'No'), ('8/14/2014', 6.4, 19.3, 0.2, 2.8, 10.3, 'SSE', 30, 'W', 'SE', 20, 22, 64, 49, 1035.0, 1032.5, 1, 2, 9.5, 18.1, 'No', 'No'), ('8/15/2014', 7.9, 19.0, 0.0, 3.4, 9.3, 'WNW', 28, 'W', 'ESE', 17, 17, 81, 53, 1031.6, 1026.5, 1, 1, 10.5, 17.8, 'No', 'No'), ('8/16/2014', 8.7, 16.8, 0.0, 1.2, 0.3, 'ESE', 26, 'W', 'ESE', 13, 13, 86, 70, 1023.8, 1019.0, 7, 7, 10.3, 16.4, 'No', 'Yes'), ('8/17/2014', 10.3, 17.5, 28.6, 4.8, 2.2, 'ESE', 46, 'E', 'WNW', 28, 22, 90, 74, 1010.3, 1004.2, 8, 7, 14.4, 17.0, 'Yes', 'Yes'), ('8/18/2014', 11.0, 15.7, 21.8, 4.8, 0.0, 'SSE', 63, 'SSE', 'SSW', 31, 28, 94, 90, 1001.8, 1005.0, 8, 8, 13.8, 13.3, 'Yes', 'Yes'), ('8/19/2014', 12.8, 17.7, 38.4, 4.4, 3.0, 'SSE', 78, 'S', 'SW', 28, 26, 69, 80, 1015.3, 1016.6, 7, 7, 15.5, 14.5, 'Yes', 'Yes'), ('8/20/2014', 9.5, 17.1, 8.2, 4.6, 5.0, 'SW', 44, 'W', 'S', 22, 22, 68, 54, 1024.7, 1024.5, 7, 6, 12.5, 15.7, 'Yes', 'Yes'), ('8/21/2014', 9.4, 18.1, 10.8, 2.0, 7.1, 'SE', 43, 'WNW', 'S', 19, 22, 86, 65, 1029.2, 1027.0, 7, 3, 11.7, 17.1, 'Yes', 'Yes'), ('8/22/2014', 11.2, 19.6, 10.2, 2.4, 10.1, 'SSE', 28, 'W', 'SSE', 17, 17, 88, 61, 1031.8, 1029.0, 6, 3, 13.2, 18.5, 'Yes', 'Yes'), ('8/23/2014', 9.9, 19.3, 3.2, 3.2, 2.9, 'ESE', 31, 'NW', 'E', 4, 20, 92, 85, 1031.6, 1029.3, 5, 7, 11.8, 14.8, 'Yes', 'Yes'), ('8/24/2014', 11.1, 19.4, 3.8, 0.2, 7.3, 'W', 22, 'WNW', 'E', 17, 11, 88, 64, 1029.7, 1026.4, 4, 2, 13.0, 18.4, 'Yes', 'No'), ('8/25/2014', 10.5, 19.3, 0.0, 3.2, 8.9, 'ESE', 44, 'W', 'ESE', 13, 19, 81, 61, 1025.7, 1022.4, 0, 2, 13.7, 18.8, 'No', 'Yes'), ('8/26/2014', 11.6, 15.6, 12.6, 4.6, 0.0, 'ESE', 52, 'SSW', 'SSW', 2, 9, 93, 87, 1024.3, 1022.7, 8, 7, 13.6, 14.9, 'Yes', 'Yes'), ('8/27/2014', 13.4, 19.8, 13.2, 3.2, 5.3, 'SSE', 56, 'S', 'SE', 19, 28, 80, 54, 1025.3, 1023.9, 7, 5, 15.3, 18.7, 'Yes', 'Yes'), ('8/28/2014', 12.3, 19.7, 15.2, 6.6, 8.8, 'SSE', 48, 'SSE', 'SSE', 20, 26, 81, 51, 1026.8, 1025.9, 2, 4, 15.3, 17.8, 'Yes', 'Yes'), ('8/29/2014', 9.4, 18.0, 2.0, 3.8, 5.4, 'SSW', 50, 'W', 'SSW', 17, 24, 85, 65, 1026.7, 1024.0, 7, 4, 12.1, 15.8, 'Yes', 'Yes'), ('8/30/2014', 12.0, 16.1, 3.2, 3.8, 2.7, 'SSW', 52, 'SW', 'SW', 20, 22, 89, 84, 1023.9, 1021.7, 8, 7, 12.5, 14.9, 'Yes', 'Yes'), ('8/31/2014', 11.7, 20.8, 3.0, 1.0, 9.5, 'W', 37, 'W', 'ESE', 20, 15, 67, 55, 1021.1, 1017.2, 1, 1, 14.8, 20.5, 'Yes', 'No'), ('9/1/2014', 10.7, 23.6, 0.0, 3.2, 8.7, 'NE', 31, 'WNW', 'ENE', 13, 13, 77, 51, 1016.9, 1010.9, 4, 7, 14.6, 20.7, 'No', 'No'), ('9/2/2014', 14.1, 18.4, 0.2, 5.2, 1.5, 'W', 59, 'W', 'S', 7, 22, 59, 66, 1009.1, 1007.9, 5, 7, 15.8, 13.7, 'No', 'Yes'), ('9/3/2014', 8.9, 16.7, 5.0, 4.2, 7.7, 'SW', 76, 'SW', 'SSW', 28, 30, 52, 45, 1013.3, 1012.3, 6, 5, 13.1, 16.2, 'Yes', 'No'), ('9/4/2014', 9.8, 17.6, 0.2, 3.0, 8.3, 'S', 61, 'SSW', 'SSW', 24, 31, 53, 52, 1015.9, 1015.1, 3, 6, 13.4, 14.7, 'No', 'Yes'), ('9/5/2014', 8.8, 18.2, 4.4, 3.6, 8.7, 'SSW', 52, 'W', 'S', 17, 26, 72, 57, 1021.8, 1021.7, 3, 2, 13.2, 16.7, 'Yes', 'Yes'), ('9/6/2014', 10.3, 19.1, 11.0, 3.2, 2.3, 'ESE', 43, 'NW', 'SE', 7, 24, 92, 73, 1029.7, 1028.5, 7, 7, 12.3, 15.7, 'Yes', 'Yes'), ('9/7/2014', 11.2, 19.0, 18.4, 3.6, 6.9, 'ESE', 31, 'W', 'SE', 15, 17, 90, 65, 1032.0, 1028.2, 7, 2, 12.5, 17.7, 'Yes', 'No'), ('9/8/2014', 10.9, 19.5, 1.0, 2.4, 10.5, 'NE', 35, 'WNW', 'NE', 17, 24, 93, 60, 1029.5, 1024.2, 1, 2, 12.2, 18.2, 'No', 'No'), ('9/9/2014', 12.2, 23.1, 0.0, 5.0, 10.3, 'NNE', 41, 'NNW', 'NE', 17, 22, 56, 56, 1019.4, 1012.8, 1, 4, 19.3, 20.6, 'No', 'Yes'), ('9/10/2014', 14.0, 24.4, 5.0, 6.8, 8.3, 'W', 59, 'W', 'WSW', 9, 28, 84, 28, 1008.2, 1008.9, 7, 3, 14.8, 23.2, 'Yes', 'No'), ('9/11/2014', 12.1, 25.8, 0.2, 5.2, 10.9, 'SSW', 50, 'WNW', 'E', 13, 17, 36, 32, 1016.7, 1013.7, 1, 1, 18.1, 23.7, 'No', 'No'), ('9/12/2014', 13.9, 18.4, 0.2, 6.8, 1.8, 'S', 41, 'SSW', 'SE', 13, 15, 67, 52, 1025.7, 1024.1, 7, 4, 14.7, 16.9, 'No', 'No'), ('9/13/2014', 12.9, 17.6, 0.8, 2.4, 3.8, 'E', 28, 'WNW', 'E', 9, 17, 80, 72, 1026.9, 1023.5, 7, 4, 14.4, 16.8, 'No', 'No'), ('9/14/2014', 12.9, 22.6, 0.4, 2.8, 9.5, 'SSE', 35, 'WNW', 'E', 11, 17, 69, 66, 1020.6, 1016.0, 0, 1, 17.3, 20.5, 'No', 'No'), ('9/15/2014', 13.1, 20.1, 0.0, 3.8, 10.1, 'ENE', 30, 'WNW', 'ENE', 11, 22, 68, 55, 1018.6, 1015.1, 1, 5, 17.7, 19.2, 'No', 'No'), ('9/18/2014', 12.2, 20.5, 0.0, 7.0, 10.8, 'WSW', 44, 'WSW', 'SE', 28, 24, 33, 31, 1018.6, 1017.1, 1, 3, 15.6, 18.4, 'No', 'No'), ('9/19/2014', 9.2, 22.2, 0.0, 5.4, 9.7, 'ESE', 31, 'W', 'E', 19, 26, 50, 33, 1022.3, 1018.5, 7, 7, 14.7, 18.2, 'No', 'No'), ('9/20/2014', 9.1, 20.3, 0.0, 4.2, 11.0, 'S', 41, 'WNW', 'SSE', 13, 22, 50, 41, 1024.5, 1023.7, 1, 1, 15.4, 19.4, 'No', 'No'), ('9/21/2014', 10.9, 20.9, 1.0, 3.6, 8.0, 'ESE', 30, 'WNW', 'ESE', 15, 15, 71, 49, 1030.5, 1027.3, 6, 2, 15.4, 18.3, 'No', 'No'), ('9/22/2014', 12.3, 20.2, 0.2, 4.8, 10.6, 'E', 26, 'WNW', 'E', 6, 17, 55, 51, 1032.1, 1028.9, 4, 1, 16.9, 18.9, 'No', 'No'), ('9/23/2014', 10.9, 21.2, 0.0, 4.0, 10.9, 'NE', 37, 'W', 'NE', 11, 20, 58, 53, 1030.2, 1026.2, 0, 0, 17.2, 19.6, 'No', 'No'), ('9/24/2014', 11.7, 22.2, 0.0, 5.4, 10.7, 'NNE', 37, 'WNW', 'NE', 6, 17, 66, 66, 1022.7, 1016.6, 0, 3, 18.5, 20.8, 'No', 'No'), ('9/25/2014', 17.4, 24.6, 0.0, 6.2, 1.2, 'WSW', 61, 'W', 'SSE', 6, 17, 60, 65, 1011.9, 1009.8, 7, 7, 20.0, 20.2, 'No', 'Yes'), ('9/26/2014', 14.3, 21.7, 2.0, 3.0, 8.3, 'SSE', 41, 'SSW', 'SE', 22, 19, 59, 51, 1017.9, 1015.9, 5, 5, 18.8, 20.1, 'Yes', 'No'), ('9/27/2014', 13.0, 22.8, 0.2, 5.0, 11.1, 'ESE', 35, 'SSW', 'SE', 15, 20, 53, 45, 1021.1, 1019.3, 5, 1, 18.8, 20.2, 'No', 'No'), ('9/28/2014', 11.6, 25.4, 0.2, 5.4, 11.2, 'NNE', 50, 'NNW', 'NE', 19, 24, 54, 50, 1021.9, 1016.2, 0, 0, 20.4, 21.2, 'No', 'No'), ('9/29/2014', 16.5, 32.9, 0.0, 8.0, 10.6, 'NNW', 37, 'N', 'WNW', 17, 15, 29, 17, 1014.6, 1011.2, 2, 0, 25.2, 32.3, 'No', 'No'), ('9/30/2014', 16.6, 33.5, 0.0, 8.0, 6.8, 'NW', 52, 'SE', 'NW', 2, 26, 42, 16, 1013.7, 1007.2, 4, 5, 23.7, 32.7, 'No', 'No'), ('10/1/2014', 15.6, 22.1, 0.0, 12.0, 11.3, 'WSW', 61, 'W', 'SE', 28, 24, 19, 28, 1017.7, 1018.5, 1, 1, 18.2, 19.6, 'No', 'No'), ('10/2/2014', 10.4, 24.9, 0.0, 7.2, 11.1, 'WNW', 30, 'W', 'NE', 11, 13, 45, 45, 1022.1, 1017.2, 1, 0, 17.6, 21.3, 'No', 'No'), ('10/3/2014', 12.8, 21.1, 0.0, 5.8, 6.3, 'ESE', 31, 'W', 'E', 6, 17, 63, 58, 1021.1, 1019.6, 4, 7, 19.0, 19.1, 'No', 'No'), ('10/4/2014', 16.4, 21.9, 0.0, 3.0, 8.5, 'ENE', 39, 'NE', 'NE', 19, 24, 73, 68, 1020.2, 1015.5, 7, 1, 19.2, 21.5, 'No', 'No'), ('10/5/2014', 14.0, 33.8, 0.0, 4.4, 10.6, 'SSW', 63, 'W', 'E', 11, 17, 65, 23, 1016.0, 1012.9, 1, 1, 18.4, 30.8, 'No', 'No'), ('10/6/2014', 17.3, 26.0, 0.0, 8.8, 8.3, 'NE', 46, 'WNW', 'ENE', 9, 19, 67, 64, 1019.2, 1012.4, 7, 2, 19.7, 21.8, 'No', 'No'), ('10/7/2014', 19.7, 27.9, 0.0, 8.0, 7.7, 'NW', 61, 'WSW', 'ESE', 28, 20, 44, 30, 1007.8, 1008.3, 7, 1, 24.1, 25.2, 'No', 'Yes'), ('10/8/2014', 15.1, 21.1, 5.4, 4.6, 3.7, 'SSW', 35, 'SSE', 'ESE', 20, 19, 80, 54, 1018.7, 1018.0, 7, 2, 16.7, 18.8, 'Yes', 'No'), ('10/9/2014', 14.4, 21.2, 0.0, 4.8, 8.5, 'ENE', 37, 'WNW', 'ENE', 7, 22, 61, 49, 1023.2, 1020.2, 1, 1, 18.6, 21.0, 'No', 'No'), ('10/10/2014', 14.0, 22.8, 0.2, 4.8, 7.9, 'NE', 35, 'NNW', 'ENE', 13, 22, 53, 58, 1019.5, 1015.5, 6, 6, 20.2, 21.9, 'No', 'No'), ('10/11/2014', 14.4, 26.8, 0.0, 5.4, 11.1, 'NNE', 41, 'WNW', 'E', 13, 19, 61, 61, 1016.8, 1014.2, 1, 1, 19.9, 23.6, 'No', 'No'), ('10/12/2014', 17.0, 24.7, 0.0, 7.8, 11.2, 'NNE', 52, 'W', 'NE', 9, 26, 66, 61, 1017.5, 1013.4, 0, 1, 20.3, 23.3, 'No', 'No'), ('10/13/2014', 17.9, 26.2, 0.0, 8.8, 5.0, 'WNW', 57, 'ESE', 'ENE', 11, 13, 60, 69, 1007.6, 1005.7, 7, 8, 22.5, 21.5, 'No', 'Yes'), ('10/14/2014', 13.2, 17.6, 9.4, 5.8, 3.0, 'S', 76, 'W', 'WSW', 26, 20, 49, 42, 1008.5, 1008.5, 6, 7, 14.9, 17.1, 'Yes', 'Yes'), ('10/15/2014', 10.6, 16.0, 70.8, 4.8, 0.1, 'SW', 78, 'SW', 'SSW', 28, 26, 79, 52, 1011.7, 1013.4, 8, 7, 11.6, 15.1, 'Yes', 'No'), ('10/16/2014', 9.0, 23.4, 0.2, 4.0, 11.7, 'ENE', 30, 'W', 'E', 11, 24, 61, 43, 1018.4, 1015.8, 2, 6, 14.3, 20.1, 'No', 'No'), ('10/17/2014', 12.2, 20.8, 0.0, 4.0, 8.8, 'SSE', 50, 'SSE', 'S', 20, 31, 75, 45, 1024.6, 1024.9, 7, 3, 15.2, 19.9, 'No', 'No'), ('10/18/2014', 12.9, 20.4, 0.0, 7.6, 6.2, 'ENE', 26, 'W', 'E', 15, 17, 66, 46, 1029.8, 1027.4, 7, 1, 15.3, 19.6, 'No', 'No'), ('10/19/2014', 12.4, 23.9, 0.0, 2.6, 12.0, 'NNE', 41, 'W', 'NE', 9, 19, 57, 49, 1027.5, 1022.6, 1, 1, 18.6, 23.1, 'No', 'No'), ('10/20/2014', 15.8, 20.8, 0.0, 10.6, 4.0, 'SSE', 69, 'S', 'S', 33, 22, 59, 74, 1028.7, 1029.8, 7, 8, 19.8, 17.0, 'No', 'No'), ('10/21/2014', 15.0, 18.7, 0.4, 2.6, 0.0, 'ENE', 31, 'ESE', 'E', 19, 19, 50, 49, 1032.5, 1030.7, 8, 7, 17.4, 18.5, 'No', 'No'), ('10/22/2014', 15.0, 21.3, 0.0, 5.0, 9.2, 'NNE', 46, 'NNW', 'NE', 4, 28, 54, 54, 1027.1, 1022.0, 7, 1, 17.8, 20.4, 'No', 'No'), ('10/23/2014', 14.5, 28.0, 0.0, 6.0, 10.7, 'E', 28, 'W', 'E', 6, 20, 64, 56, 1018.0, 1015.9, 3, 2, 19.7, 25.1, 'No', 'No'), ('10/24/2014', 18.6, 26.4, 0.0, 5.8, 7.1, 'NNE', 48, 'NNW', 'ENE', 13, 30, 78, 70, 1020.1, 1014.9, 6, 5, 22.0, 23.1, 'No', 'No'), ('10/25/2014', 18.5, 29.9, 0.2, 6.0, 8.4, 'SSE', 39, 'WNW', 'SSE', 19, 19, 81, 59, 1015.3, 1013.6, 1, 6, 21.0, 25.9, 'No', 'No'), ('10/26/2014', 18.5, 32.5, 0.0, 5.0, 11.2, 'S', 44, 'W', 'SSE', 11, 24, 64, 55, 1010.2, 1007.9, 0, 5, 23.5, 25.8, 'No', 'No'), ('10/27/2014', 19.4, 31.6, 0.0, 6.6, 8.9, 'WNW', 70, 'NNE', 'W', 13, 41, 60, 26, 1007.8, 1002.7, 5, 7, 23.2, 29.6, 'No', 'No'), ('10/28/2014', 15.9, 28.9, 0.0, 7.8, 10.4, 'W', 43, 'W', 'W', 17, 22, 36, 18, 1012.2, 1008.3, 2, 1, 21.7, 28.0, 'No', 'No'), ('10/29/2014', 16.6, 24.6, 0.0, 7.2, 11.4, 'ENE', 37, 'SSW', 'E', 7, 26, 35, 63, 1017.2, 1015.8, 1, 2, 22.6, 21.8, 'No', 'No'), ('10/30/2014', 15.5, 30.8, 0.0, 5.8, 12.6, 'E', 28, 'W', 'ENE', 13, 17, 61, 32, 1015.6, 1011.6, 2, 3, 21.1, 28.4, 'No', 'No'), ('11/2/2014', 13.7, 23.5, 2.4, 15.0, 12.9, 'W', 56, 'W', 'ESE', 28, 22, 26, 23, 1017.9, 1017.9, 1, 1, 16.8, 21.8, 'Yes', 'No'), ('11/3/2014', 13.8, 21.5, 0.2, 7.8, 6.8, 'ESE', 37, 'WNW', 'ESE', 11, 26, 52, 57, 1025.4, 1023.7, 3, 4, 17.0, 19.5, 'No', 'No'), ('11/4/2014', 16.1, 21.8, 0.0, 6.6, 8.8, 'ENE', 46, 'NNE', 'ENE', 13, 31, 60, 64, 1024.0, 1019.4, 7, 2, 20.4, 21.0, 'No', 'No'), ('11/5/2014', 17.7, 23.5, 0.0, 6.0, 3.8, 'NNE', 67, 'ESE', 'NE', 15, 30, 67, 75, 1017.1, 1012.6, 7, 7, 20.7, 21.0, 'No', 'Yes'), ('11/6/2014', 15.5, 23.2, 2.0, 5.6, 9.5, 'SSW', 50, 'SSW', 'SE', 24, 28, 64, 57, 1014.8, 1013.9, 6, 6, 20.1, 20.9, 'Yes', 'No'), ('11/7/2014', 16.5, 22.1, 0.0, 6.2, 11.9, 'E', 30, 'E', 'E', 9, 22, 54, 56, 1019.4, 1019.5, 4, 5, 20.6, 21.8, 'No', 'No'), ('11/8/2014', 14.4, 23.1, 0.0, 6.4, 12.3, 'ENE', 41, 'E', 'NE', 9, 22, 61, 60, 1022.4, 1018.9, 2, 0, 21.4, 21.9, 'No', 'No'), ('11/9/2014', 16.5, 26.2, 0.0, 6.8, 10.9, 'S', 54, 'S', 'SSE', 22, 24, 60, 53, 1018.8, 1017.6, 1, 6, 23.1, 25.2, 'No', 'No'), ('11/10/2014', 18.7, 23.6, 0.0, 8.0, 3.2, 'ESE', 37, 'S', 'SE', 13, 20, 73, 61, 1018.2, 1016.8, 8, 6, 20.7, 22.2, 'No', 'No'), ('11/11/2014', 16.6, 23.2, 0.0, 4.2, 5.1, 'ESE', 35, 'ESE', 'SE', 7, 20, 51, 66, 1020.1, 1019.6, 6, 8, 21.3, 19.0, 'No', 'No'), ('11/12/2014', 16.4, 22.2, 0.0, 4.6, 6.1, 'ENE', 33, 'WNW', 'E', 6, 20, 66, 51, 1019.7, 1016.0, 6, 1, 18.8, 21.6, 'No', 'No'), ('11/13/2014', 18.5, 23.5, 0.0, 6.8, 6.6, 'NE', 39, 'ENE', 'ENE', 15, 22, 64, 68, 1019.2, 1015.7, 7, 7, 20.0, 22.1, 'No', 'No'), ('11/14/2014', 17.7, 32.2, 0.0, 4.8, 11.2, 'SSW', 72, 'SSW', 'ESE', 2, 13, 69, 39, 1011.8, 1006.7, 3, 7, 23.3, 31.7, 'No', 'No'), ('11/15/2014', 18.9, 24.1, 0.0, 12.8, 2.3, 'SE', 39, 'S', 'SSE', 7, 24, 60, 50, 1009.9, 1010.0, 8, 8, 20.1, 22.6, 'No', 'Yes'), ('11/16/2014', 18.1, 28.5, 5.6, 5.0, 7.3, 'W', 74, 'NW', 'W', 22, 44, 87, 27, 1005.6, 1001.5, 8, 2, 18.2, 28.1, 'Yes', 'No'), ('11/17/2014', 15.2, 25.5, 0.4, 7.0, 12.6, 'E', 35, 'W', 'E', 15, 24, 38, 48, 1013.8, 1011.8, 2, 3, 21.3, 22.9, 'No', 'No'), ('11/18/2014', 18.6, 26.7, 0.0, 8.0, 11.7, 'SSE', 43, 'W', 'SSE', 20, 24, 60, 45, 1016.7, 1016.4, 3, 1, 22.3, 25.2, 'No', 'No'), ('11/19/2014', 18.1, 24.9, 0.0, 8.0, 10.1, 'ENE', 41, 'ENE', 'E', 11, 28, 65, 59, 1021.8, 1018.6, 7, 5, 21.9, 22.7, 'No', 'No'), ('11/20/2014', 18.8, 31.1, 0.0, 6.8, 10.6, 'ENE', 41, 'NE', 'ENE', 6, 24, 56, 57, 1014.3, 1008.7, 7, 6, 24.8, 26.0, 'No', 'No'), ('11/21/2014', 22.1, 33.9, 0.0, 8.4, 11.0, 'SSE', 63, 'SSE', 'E', 7, 22, 36, 46, 1007.4, 1004.6, 2, 2, 31.0, 30.3, 'No', 'No'), ('11/22/2014', 19.1, 26.3, 0.0, 10.0, 9.3, 'SSE', 37, 'SE', 'E', 9, 19, 50, 60, 1015.9, 1011.5, 4, 7, 23.6, 23.4, 'No', 'No'), ('11/23/2014', 19.6, 30.1, 0.0, 6.0, 10.6, 'SE', 44, 'E', 'E', 4, 22, 62, 54, 1011.5, 1007.4, 3, 3, 24.9, 28.9, 'No', 'No'), ('11/24/2014', 21.1, 30.2, 0.0, 7.2, 6.4, 'E', 33, 'SSW', 'E', 6, 28, 71, 76, 1015.0, 1007.4, 6, 6, 23.5, 23.6, 'No', 'Yes'), ('11/25/2014', 21.8, 24.7, 5.0, 6.6, 5.6, 'SW', 52, 'SSW', 'ESE', 13, 24, 65, 56, 1013.0, 1016.4, 7, 5, 24.0, 21.6, 'Yes', 'No'), ('11/26/2014', 19.3, 23.3, 0.0, 7.4, 7.3, 'ENE', 41, 'ENE', 'ENE', 17, 26, 58, 66, 1019.7, 1016.6, 6, 7, 21.5, 21.9, 'No', 'No'), ('11/30/2014', 19.1, 26.8, 0.0, 8.0, 8.4, 'NNE', 44, 'ENE', 'NE', 11, 26, 64, 63, 1014.2, 1011.2, 2, 4, 23.8, 24.6, 'No', 'Yes'), ('12/1/2014', 19.6, 26.8, 3.2, 9.8, 8.0, 'NNE', 46, 'E', 'NE', 6, 20, 59, 69, 1011.0, 1007.9, 6, 7, 25.1, 23.6, 'Yes', 'Yes'), ('12/2/2014', 19.0, 28.9, 8.2, 8.6, 10.7, 'SE', 61, 'WNW', 'NNE', 15, 20, 71, 56, 1011.9, 1008.8, 6, 2, 23.7, 27.8, 'Yes', 'No'), ('12/3/2014', 21.6, 29.3, 1.0, 8.4, 7.6, 'S', 59, 'E', 'ENE', 4, 17, 68, 55, 1013.2, 1009.4, 4, 7, 26.2, 28.4, 'No', 'Yes'), ('12/4/2014', 20.0, 26.9, 23.8, 8.0, 0.0, 'W', 61, 'ENE', 'ENE', 9, 22, 80, 74, 1012.5, 1009.4, 7, 7, 22.7, 25.3, 'Yes', 'Yes'), ('12/5/2014', 19.6, 27.2, 6.2, 11.0, 6.9, 'WNW', 52, 'N', 'NE', 9, 17, 64, 59, 1008.3, 1005.6, 7, 5, 24.3, 26.3, 'Yes', 'Yes'), ('12/6/2014', 20.5, 26.7, 1.8, 5.6, 6.6, 'ENE', 30, 'NE', 'E', 17, 17, 70, 61, 1007.7, 1004.1, 6, 7, 23.4, 25.5, 'Yes', 'Yes'), ('12/7/2014', 18.7, 27.2, 5.4, 7.8, 8.9, 'WNW', 50, 'ENE', 'E', 11, 22, 68, 81, 1006.0, 1003.9, 2, 4, 24.5, 23.6, 'Yes', 'Yes'), ('12/8/2014', 18.9, 32.0, 15.8, 8.6, 7.5, 'W', 70, 'ESE', 'WSW', 2, 17, 81, 42, 1006.8, 1006.3, 6, 7, 22.0, 29.2, 'Yes', 'No'), ('12/9/2014', 21.1, 23.8, 0.4, 7.4, 2.1, 'S', 31, 'ESE', 'ESE', 19, 22, 71, 70, 1015.0, 1014.3, 7, 6, 22.5, 23.0, 'No', 'No'), ('12/10/2014', 20.4, 25.3, 0.0, 5.0, 2.6, 'E', 33, 'E', 'E', 17, 22, 73, 69, 1014.8, 1011.4, 6, 7, 22.5, 24.7, 'No', 'Yes'), ('12/11/2014', 20.7, 22.0, 9.8, 3.4, 0.7, 'SSW', 65, 'W', 'SSW', 19, 26, 92, 85, 1005.5, 1008.8, 7, 7, 21.7, 18.6, 'Yes', 'Yes'), ('12/13/2014', 16.7, 24.1, 0.0, 8.4, 9.7, 'ESE', 44, 'SE', 'ESE', 19, 28, 53, 54, 1018.6, 1016.9, 5, 4, 20.6, 21.2, 'No', 'No'), ('12/14/2014', 15.3, 24.4, 0.0, 8.0, 10.8, 'NNE', 39, 'WNW', 'ENE', 7, 24, 69, 48, 1014.4, 1010.7, 5, 1, 20.0, 23.2, 'No', 'No'), ('12/15/2014', 17.8, 25.9, 0.0, 8.0, 13.0, 'NE', 41, 'ENE', 'ENE', 6, 24, 54, 48, 1012.2, 1010.8, 1, 1, 24.3, 24.6, 'No', 'No'), ('12/16/2014', 20.0, 25.0, 0.0, 11.4, 8.7, 'NE', 65, 'NNE', 'NE', 13, 39, 60, 67, 1007.9, 999.6, 7, 3, 22.1, 24.3, 'No', 'No'), ('12/17/2014', 19.2, 23.8, 0.0, 7.6, 5.8, 'W', 41, 'SSE', 'SE', 33, 22, 61, 51, 1006.3, 1007.8, 2, 7, 21.2, 22.3, 'No', 'No'), ('12/18/2014', 18.3, 25.3, 0.0, 6.8, 5.6, 'E', 31, 'WNW', 'E', 11, 20, 80, 70, 1010.3, 1005.5, 8, 6, 19.1, 24.4, 'No', 'No'), ('12/19/2014', 18.2, 24.1, 0.0, 6.6, 10.8, 'SSW', 56, 'SSE', 'SE', 31, 22, 53, 44, 1012.4, 1013.0, 1, 1, 21.2, 23.2, 'No', 'No'), ('12/20/2014', 18.0, 23.1, 0.0, 8.4, 9.5, 'ENE', 31, 'ESE', 'E', 9, 20, 51, 50, 1018.5, 1016.6, 5, 1, 20.7, 22.2, 'No', 'No'), ('12/21/2014', 16.8, 25.7, 0.0, 7.0, 12.6, 'ENE', 46, 'W', 'E', 6, 31, 65, 61, 1018.6, 1016.0, 1, 1, 22.5, 24.1, 'No', 'No'), ('12/22/2014', 20.5, 26.4, 0.0, 9.2, 8.8, 'NE', 57, 'ENE', 'NE', 15, 33, 63, 69, 1016.9, 1014.8, 3, 5, 24.8, 25.1, 'No', 'No'), ('12/23/2014', 20.7, 26.1, 0.0, 8.2, 4.6, 'NE', 41, 'NW', 'NNE', 11, 13, 84, 81, 1015.4, 1012.8, 7, 8, 21.1, 23.8, 'No', 'Yes'), ('12/24/2014', 21.0, 24.3, 1.6, 5.0, 3.3, 'SSW', 54, 'S', 'S', 17, 28, 82, 71, 1013.7, 1013.9, 7, 7, 22.4, 22.7, 'Yes', 'No'), ('12/25/2014', 19.8, 26.8, 0.0, 5.8, 5.3, 'WSW', 59, 'N', 'NE', 9, 22, 77, 71, 1011.5, 1005.7, 7, 7, 23.2, 25.6, 'No', 'Yes'), ('12/26/2014', 19.9, 30.4, 28.6, 4.0, 8.9, 'SSE', 57, 'WSW', 'SE', 19, 37, 67, 66, 1007.8, 1011.3, 3, 6, 24.1, 22.7, 'Yes', 'No'), ('12/27/2014', 18.8, 21.7, 0.0, 10.6, 0.0, 'ENE', 31, 'ESE', 'ESE', 11, 15, 50, 53, 1021.0, 1020.6, 7, 7, 20.6, 20.7, 'No', 'No'), ('12/28/2014', 18.9, 24.2, 0.0, 4.0, 2.0, 'ENE', 30, 'S', 'E', 2, 13, 75, 61, 1019.2, 1015.9, 7, 7, 20.2, 23.5, 'No', 'No'), ('12/29/2014', 17.7, 27.3, 0.0, 5.4, 12.6, 'NNE', 46, 'NNW', 'NE', 13, 24, 62, 66, 1009.7, 1004.1, 1, 1, 23.6, 25.4, 'No', 'No'), ('12/30/2014', 19.4, 28.1, 0.0, 8.0, 12.7, 'SSW', 54, 'S', 'E', 13, 17, 59, 50, 1007.4, 1004.0, 0, 0, 23.4, 26.9, 'No', 'No'), ('12/31/2014', 19.3, 25.2, 0.0, 9.6, 8.0, 'SSW', 46, 'E', 'E', 17, 24, 64, 57, 1015.6, 1014.4, 5, 2, 22.2, 23.9, 'No', 'No'), ('1/1/2015', 21.4, 28.4, 0.0, 6.8, 11.0, 'ENE', 43, 'NE', 'NE', 15, 24, 68, 69, 1014.5, 1011.4, 1, 3, 25.2, 27.5, 'No', 'No'), ('1/2/2015', 21.2, 28.5, 0.0, 9.2, 3.6, 'S', 37, 'S', 'ESE', 17, 17, 78, 76, 1018.8, 1017.7, 7, 7, 23.2, 26.3, 'No', 'No'), ('1/3/2015', 22.0, 28.8, 0.0, 4.0, 12.0, 'NE', 48, 'E', 'NE', 15, 22, 76, 70, 1020.2, 1017.5, 3, 1, 26.3, 27.7, 'No', 'No'), ('1/4/2015', 22.4, 30.4, 0.0, 10.2, 8.9, 'SSW', 52, 'E', 'NE', 11, 15, 69, 66, 1015.9, 1012.8, 1, 7, 26.9, 27.1, 'No', 'No'), ('1/5/2015', 20.5, 26.3, 0.2, 10.0, 3.4, 'S', 35, 'SSW', 'ESE', 9, 15, 82, 66, 1019.4, 1018.7, 7, 7, 21.8, 25.9, 'No', 'No'), ('1/6/2015', 21.3, 28.2, 0.2, 4.0, 11.8, 'E', 26, 'SSE', 'E', 11, 17, 80, 64, 1020.7, 1019.9, 5, 3, 24.4, 26.8, 'No', 'No'), ('1/7/2015', 22.8, 29.3, 0.0, 6.6, 12.4, 'NNE', 44, 'E', 'NE', 17, 22, 64, 50, 1020.6, 1018.3, 3, 1, 27.1, 27.9, 'No', 'No'), ('1/8/2015', 21.2, 28.0, 0.0, 9.2, 13.0, 'W', 41, 'N', 'NE', 6, 31, 55, 55, 1016.1, 1011.7, 1, 1, 25.8, 27.4, 'No', 'No'), ('1/9/2015', 21.8, 29.9, 0.0, 13.6, 8.7, 'NE', 48, 'E', 'ENE', 13, 31, 72, 64, 1010.6, 1007.8, 1, 2, 25.7, 26.9, 'No', 'No'), ('1/10/2015', 22.0, 28.7, 0.0, 7.4, 1.0, 'W', 41, 'ESE', 'ENE', 2, 13, 81, 78, 1010.8, 1009.1, 7, 8, 24.3, 25.2, 'No', 'Yes'), ('1/11/2015', 20.6, 22.9, 21.0, 7.4, 0.0, 'S', 33, 'ESE', 'S', 19, 13, 96, 92, 1013.6, 1012.6, 8, 8, 21.1, 21.1, 'Yes', 'Yes'), ('1/12/2015', 20.4, 24.4, 9.6, 4.8, 3.3, 'S', 56, 'SSE', 'S', 22, 30, 76, 78, 1014.7, 1013.3, 7, 7, 22.9, 22.9, 'Yes', 'Yes'), ('1/13/2015', 18.9, 28.8, 4.8, 5.4, 7.5, 'NNE', 43, 'WSW', 'ENE', 6, 20, 94, 77, 1010.2, 1005.6, 6, 5, 21.2, 24.5, 'Yes', 'No'), ('1/14/2015', 21.1, 34.2, 0.0, 6.2, 12.7, 'WSW', 54, 'WNW', 'WNW', 6, 28, 55, 32, 999.1, 997.2, 1, 2, 28.6, 33.4, 'No', 'No'), ('1/15/2015', 22.0, 29.0, 0.0, 11.0, 11.7, 'W', 35, 'WSW', 'ESE', 11, 24, 45, 57, 1004.0, 1004.2, 2, 1, 26.1, 24.8, 'No', 'No'), ('1/16/2015', 21.2, 27.6, 0.0, 8.2, 12.9, 'ENE', 33, 'WSW', 'E', 6, 22, 67, 63, 1008.6, 1005.8, 3, 2, 24.7, 26.6, 'No', 'No'), ('1/17/2015', 20.7, 35.7, 0.0, 3.2, 13.4, 'WNW', 39, 'W', 'E', 7, 24, 35, 23, 1008.0, 1005.2, 0, 1, 27.0, 33.5, 'No', 'No'), ('1/18/2015', 20.7, 29.1, 0.0, 10.2, 11.8, 'ESE', 39, 'SSW', 'ESE', 13, 20, 73, 43, 1011.7, 1010.0, 5, 6, 24.5, 28.6, 'No', 'No'), ('1/19/2015', 20.9, 22.7, 0.0, 10.4, 0.1, 'SE', 44, 'SSE', 'SE', 28, 24, 66, 61, 1014.9, 1015.2, 8, 8, 21.7, 21.7, 'No', 'Yes'), ('1/20/2015', 18.1, 24.8, 6.2, 3.4, 7.3, 'ENE', 48, 'ENE', 'NE', 20, 26, 88, 64, 1014.3, 1011.9, 8, 5, 20.3, 23.9, 'Yes', 'Yes'), ('1/21/2015', 19.7, 28.0, 18.0, 7.4, 10.5, 'E', 59, 'SSE', 'E', 2, 20, 78, 61, 1011.0, 1010.6, 5, 3, 24.4, 27.1, 'Yes', 'No'), ('1/22/2015', 22.5, 28.3, 0.2, 8.4, 11.7, 'ENE', 37, 'ESE', 'E', 9, 19, 68, 58, 1014.5, 1012.1, 5, 1, 26.4, 27.5, 'No', 'No'), ('1/23/2015', 22.4, 29.1, 0.0, 8.0, 10.5, 'NNE', 52, 'NE', 'NE', 11, 30, 74, 61, 1010.1, 1007.0, 7, 2, 25.8, 28.7, 'No', 'No'), ('1/24/2015', 22.7, 29.1, 0.0, 9.2, 9.8, 'NE', 43, 'E', 'NE', 15, 24, 69, 54, 1008.1, 1004.9, 1, 1, 26.7, 28.3, 'No', 'No'), ('1/25/2015', 21.6, 34.4, 1.0, 8.0, 11.2, 'S', 59, 'W', 'E', 6, 19, 77, 44, 1003.1, 1001.6, 2, 5, 25.0, 31.2, 'No', 'No'), ('1/26/2015', 20.2, 20.4, 0.6, 10.6, 0.0, 'SSE', 35, 'SSE', 'S', 20, 17, 84, 88, 1013.2, 1013.3, 8, 8, 20.4, 19.7, 'No', 'Yes'), ('1/27/2015', 18.9, 20.4, 33.0, 5.4, 0.0, 'ESE', 37, 'ESE', 'E', 20, 13, 96, 93, 1013.3, 1012.5, 8, 8, 19.2, 20.2, 'Yes', 'Yes'), ('1/28/2015', 17.3, 20.5, 57.0, 7.2, 2.3, 'S', 43, 'SSE', 'SSW', 17, 6, 95, 92, 1013.3, 1013.5, 8, 7, 17.9, 18.2, 'Yes', 'Yes'), ('1/29/2015', 14.6, 24.3, 14.0, 2.8, 12.2, 'S', 57, 'SSW', 'S', 17, 35, 54, 47, 1012.9, 1011.0, 3, 3, 19.0, 22.1, 'Yes', 'No'), ('1/30/2015', 15.2, 27.3, 0.0, 8.8, 11.2, 'WSW', 48, 'WSW', 'WSW', 20, 17, 43, 28, 1009.4, 1005.4, 1, 3, 19.6, 26.8, 'No', 'No'), ('1/31/2015', 17.0, 26.1, 0.0, 5.8, 11.7, 'ESE', 26, 'WNW', 'ESE', 9, 19, 59, 42, 1008.1, 1005.8, 2, 2, 21.4, 24.2, 'No', 'No'), ('2/1/2015', 19.3, 26.6, 0.0, 9.4, 7.0, 'SE', 37, 'SSW', 'ESE', 9, 19, 75, 55, 1009.5, 1009.3, 7, 6, 22.0, 24.2, 'No', 'Yes'), ('2/2/2015', 18.0, 25.0, 3.4, 6.6, 8.7, 'SSE', 61, 'SSW', 'S', 19, 35, 81, 59, 1015.5, 1015.9, 7, 2, 19.6, 23.4, 'Yes', 'No'), ('2/3/2015', 18.5, 26.5, 1.0, 8.6, 9.8, 'SSE', 43, 'SW', 'SE', 17, 24, 72, 45, 1020.1, 1017.5, 5, 2, 20.1, 25.7, 'No', 'Yes'), ('2/4/2015', 17.3, 25.6, 1.2, 6.4, 6.6, 'SSE', 43, 'W', 'SSE', 15, 30, 70, 58, 1015.7, 1015.7, 7, 6, 20.1, 22.9, 'Yes', 'Yes'), ('2/5/2015', 18.6, 24.3, 7.4, 7.2, 0.5, 'ESE', 46, 'ESE', 'ESE', 20, 13, 59, 54, 1023.2, 1024.1, 7, 7, 21.9, 22.5, 'Yes', 'No'), ('2/6/2015', 17.6, 25.6, 0.2, 4.2, 7.8, 'ESE', 31, 'W', 'ESE', 9, 15, 80, 53, 1027.7, 1026.2, 7, 7, 20.5, 23.6, 'No', 'No'), ('2/7/2015', 18.8, 26.5, 0.0, 5.4, 6.9, 'ENE', 35, 'WNW', 'ENE', 9, 22, 77, 50, 1025.2, 1021.8, 8, 4, 20.3, 26.0, 'No', 'No'), ('2/8/2015', 18.9, 32.1, 0.0, 5.6, 12.2, 'E', 26, 'W', 'E', 9, 22, 71, 58, 1018.9, 1017.0, 0, 1, 23.3, 28.3, 'No', 'No'), ('2/9/2015', 22.7, 25.9, 0.0, 8.0, 1.2, 'S', 46, 'S', 'SE', 20, 20, 76, 66, 1023.8, 1023.9, 7, 7, 23.7, 25.3, 'No', 'No'), ('2/10/2015', 21.5, 28.2, 0.0, 5.8, 7.7, 'ENE', 33, 'WNW', 'E', 6, 19, 82, 65, 1024.6, 1023.1, 5, 3, 24.0, 27.7, 'No', 'No'), ('2/11/2015', 22.8, 28.6, 0.2, 5.8, 11.3, 'ENE', 41, 'ENE', 'E', 17, 28, 72, 59, 1023.6, 1021.0, 6, 2, 25.8, 27.1, 'No', 'No'), ('2/12/2015', 21.0, 28.8, 0.0, 8.0, 10.0, 'ESE', 37, 'SE', 'ESE', 4, 26, 62, 61, 1021.8, 1021.0, 1, 5, 26.1, 27.6, 'No', 'Yes'), ('2/13/2015', 20.4, 28.1, 6.8, 7.8, 4.6, 'ENE', 31, 'WNW', 'ESE', 7, 19, 94, 61, 1024.2, 1023.3, 7, 5, 22.1, 25.1, 'Yes', 'Yes'), ('2/14/2015', 20.4, 27.2, 4.4, 5.0, 6.7, 'ENE', 39, 'W', 'NE', 7, 17, 82, 55, 1023.1, 1019.9, 2, 7, 23.1, 26.9, 'Yes', 'No'), ('2/15/2015', 20.3, 29.4, 0.6, 5.6, 8.8, 'NE', 37, 'N', 'ENE', 4, 20, 85, 59, 1017.0, 1014.8, 7, 3, 22.4, 26.4, 'No', 'No'), ('2/16/2015', 22.1, 28.0, 0.0, 8.0, 11.1, 'NE', 46, 'NE', 'NE', 19, 28, 62, 57, 1016.9, 1015.7, 3, 7, 25.4, 26.8, 'No', 'No'), ('2/17/2015', 21.9, 27.8, 0.0, 8.4, 12.2, 'NE', 48, 'NNE', 'ENE', 19, 31, 59, 56, 1019.0, 1017.6, 3, 2, 25.7, 26.1, 'No', 'No'), ('2/18/2015', 22.2, 27.6, 0.0, 10.4, 12.2, 'E', 41, 'NE', 'E', 9, 28, 59, 60, 1019.9, 1019.0, 2, 2, 26.4, 26.7, 'No', 'No'), ('2/19/2015', 22.2, 27.6, 0.2, 9.6, 5.1, 'ENE', 39, 'ENE', 'E', 11, 17, 88, 63, 1021.8, 1019.4, 7, 5, 23.0, 25.8, 'No', 'No'), ('2/20/2015', 21.7, 26.8, 0.0, 5.0, 1.8, 'NE', 43, 'W', 'E', 6, 9, 82, 67, 1018.0, 1016.2, 7, 7, 23.8, 25.6, 'No', 'No'), ('2/21/2015', 20.5, 25.6, 1.0, 2.8, 0.0, 'ENE', 37, 'SSE', 'ESE', 6, 15, 88, 74, 1017.1, 1016.0, 8, 8, 22.9, 24.5, 'No', 'Yes'), ('2/22/2015', 20.7, 27.4, 1.2, 3.4, 10.7, 'E', 31, 'ESE', 'E', 4, 20, 82, 62, 1017.7, 1016.9, 3, 6, 23.8, 26.8, 'Yes', 'No'), ('2/23/2015', 22.4, 27.6, 0.0, 6.6, 5.5, 'ENE', 31, 'NNE', 'E', 15, 17, 76, 63, 1016.9, 1014.6, 5, 4, 24.1, 26.9, 'No', 'No'), ('2/24/2015', 22.2, 25.6, 0.2, 5.2, 6.2, 'SSE', 61, 'NNW', 'S', 4, 33, 89, 66, 1014.8, 1015.1, 7, 6, 23.3, 24.8, 'No', 'No'), ('2/25/2015', 20.1, 23.8, 0.0, 6.6, 9.1, 'SE', 44, 'WSW', 'SSE', 6, 30, 76, 77, 1015.6, 1015.2, 7, 7, 22.2, 22.9, 'No', 'Yes'), ('2/26/2015', 19.9, 25.8, 4.2, 2.2, 4.7, 'E', 20, 'WNW', 'E', 15, 17, 86, 72, 1010.9, 1007.2, 7, 7, 21.5, 24.9, 'Yes', 'Yes'), ('2/27/2015', 20.0, 27.5, 26.8, 4.6, 8.4, 'SE', 28, 'S', 'ESE', 11, 17, 97, 60, 1010.8, 1009.5, 6, 2, 21.1, 26.4, 'Yes', 'No'), ('2/28/2015', 20.1, 27.0, 0.2, 5.6, 6.0, 'NNE', 43, 'ENE', 'NE', 9, 22, 78, 62, 1010.8, 1008.5, 7, 7, 23.3, 26.5, 'No', 'No'), ('3/1/2015', 22.0, 36.4, 0.0, 6.0, 7.0, 'SSE', 91, 'E', 'E', 6, 20, 69, 57, 1005.9, 1002.9, 1, 7, 26.2, 29.3, 'No', 'Yes'), ('3/2/2015', 18.2, 24.6, 11.4, 10.6, 3.3, 'SSE', 48, 'SSW', 'SE', 20, 15, 70, 57, 1018.7, 1017.3, 6, 7, 20.1, 23.7, 'Yes', 'No'), ('3/3/2015', 16.8, 27.7, 0.2, 5.0, 8.0, 'ENE', 33, 'WNW', 'E', 9, 28, 60, 54, 1015.9, 1013.1, 1, 2, 22.5, 25.8, 'No', 'No'), ('3/4/2015', 21.5, 27.9, 0.0, 6.6, 7.4, 'SSW', 26, 'S', 'E', 7, 13, 79, 63, 1013.4, 1010.2, 5, 3, 23.7, 26.9, 'No', 'No'), ('3/5/2015', 20.4, 28.6, 0.0, 4.8, 9.8, 'SSE', 59, 'SW', 'SSE', 15, 35, 28, 56, 1005.9, 1008.5, 4, 4, 25.2, 23.1, 'No', 'No'), ('3/6/2015', 16.2, 30.9, 0.0, 8.8, 11.3, 'WSW', 44, 'WNW', 'W', 15, 24, 44, 22, 1007.6, 1003.7, 5, 1, 21.1, 29.6, 'No', 'No'), ('3/7/2015', 19.3, 25.4, 0.0, 8.0, 7.3, 'ENE', 43, 'E', 'ENE', 2, 24, 89, 57, 1012.8, 1009.9, 4, 2, 19.8, 24.6, 'No', 'No'), ('3/8/2015', 19.6, 27.6, 0.0, 5.8, 6.7, 'SSE', 35, 'WNW', 'SSE', 11, 22, 87, 62, 1011.1, 1009.5, 7, 7, 21.0, 25.6, 'No', 'No'), ('3/9/2015', 20.3, 31.2, 0.0, 4.0, 11.0, 'ENE', 31, 'WNW', 'E', 11, 24, 75, 57, 1011.9, 1009.9, 0, 1, 23.7, 27.7, 'No', 'No'), ('3/10/2015', 21.1, 24.5, 0.0, 7.2, 0.9, 'SSW', 35, 'SSW', 'E', 17, 20, 79, 79, 1017.7, 1016.5, 7, 7, 22.8, 24.0, 'No', 'No'), ('3/11/2015', 21.3, 27.9, 0.0, 1.2, 7.6, 'WNW', 52, 'WNW', 'E', 11, 26, 85, 65, 1016.9, 1013.3, 6, 1, 22.5, 27.0, 'No', 'No'), ('3/12/2015', 20.0, 28.7, 0.2, 6.2, 9.8, 'SE', 41, 'SSE', 'SE', 22, 22, 76, 52, 1014.9, 1013.3, 5, 6, 25.0, 27.3, 'No', 'No'), ('3/13/2015', 20.1, 21.9, 0.6, 6.2, 0.3, 'SSE', 44, 'SSE', 'S', 22, 17, 70, 65, 1019.9, 1019.5, 7, 7, 20.8, 21.4, 'No', 'Yes'), ('3/14/2015', 15.8, 24.5, 1.2, 3.4, 8.9, 'NE', 31, 'WNW', 'E', 9, 19, 73, 49, 1018.7, 1014.6, 1, 2, 20.1, 23.7, 'Yes', 'No'), ('3/15/2015', 17.7, 24.9, 0.0, 5.6, 5.1, 'SSE', 70, 'SSW', 'S', 26, 33, 75, 51, 1010.0, 1012.5, 6, 6, 21.8, 23.0, 'No', 'Yes'), ('3/16/2015', 16.3, 23.6, 8.8, 7.4, 6.1, 'SSE', 37, 'WNW', 'E', 13, 13, 77, 45, 1017.2, 1015.7, 7, 5, 17.9, 23.4, 'Yes', 'No'), ('3/17/2015', 15.3, 24.4, 0.0, 4.8, 3.9, 'N', 31, 'WNW', 'NE', 11, 17, 63, 55, 1015.9, 1012.0, 3, 7, 20.4, 22.5, 'No', 'No'), ('3/18/2015', 19.7, 29.9, 0.0, 5.8, 7.8, 'SSE', 28, 'NNE', 'ESE', 9, 17, 76, 49, 1007.2, 1003.7, 7, 2, 22.5, 27.2, 'No', 'No'), ('3/19/2015', 19.6, 28.9, 0.2, 3.0, 10.5, 'SSW', 35, 'W', 'ESE', 20, 19, 72, 54, 1011.5, 1010.5, 2, 1, 22.8, 27.2, 'No', 'No'), ('3/20/2015', 20.0, 31.4, 0.0, 5.2, 8.0, 'SSE', 72, 'W', 'S', 13, 39, 75, 65, 1010.5, 1012.0, 1, 5, 23.8, 24.9, 'No', 'Yes'), ('3/21/2015', 18.3, 23.1, 2.0, 7.6, 0.9, 'SSE', 44, 'SE', 'SE', 22, 22, 75, 55, 1024.7, 1025.3, 7, 6, 19.6, 21.7, 'Yes', 'Yes'), ('3/22/2015', 18.6, 24.4, 2.2, 5.4, 1.6, 'ESE', 44, 'E', 'E', 24, 22, 71, 59, 1024.4, 1022.0, 7, 7, 22.2, 24.1, 'Yes', 'Yes'), ('3/23/2015', 18.4, 26.5, 1.4, 3.4, 8.7, 'NNE', 41, 'N', 'NE', 9, 22, 81, 64, 1018.9, 1013.6, 1, 6, 22.8, 26.4, 'Yes', 'No'), ('3/24/2015', 20.6, 27.6, 0.2, 6.8, 2.2, 'SW', 31, 'SW', 'SE', 2, 9, 86, 93, 1012.1, 1010.4, 7, 8, 22.2, 22.5, 'No', 'Yes'), ('3/25/2015', 15.0, 24.8, 22.4, 3.4, 9.7, 'SSW', 37, 'W', 'SSE', 19, 20, 72, 53, 1017.2, 1016.5, 1, 3, 18.0, 24.2, 'Yes', 'No'), ('3/26/2015', 16.9, 28.7, 0.2, 5.8, 10.4, 'WSW', 41, 'W', 'WNW', 19, 17, 70, 24, 1017.8, 1015.1, 1, 1, 20.4, 27.8, 'No', 'No'), ('3/27/2015', 14.7, 27.6, 0.0, 7.0, 11.2, 'WSW', 52, 'W', 'W', 15, 22, 34, 20, 1020.5, 1017.1, 1, 0, 17.2, 26.4, 'No', 'No'), ('3/28/2015', 14.7, 24.5, 0.0, 7.0, 10.9, 'W', 37, 'W', 'ESE', 24, 20, 39, 45, 1023.4, 1021.9, 1, 2, 18.5, 22.2, 'No', 'No'), ('3/29/2015', 15.2, 24.7, 0.0, 5.0, 6.4, 'ENE', 31, 'WNW', 'ENE', 11, 20, 78, 59, 1023.4, 1021.1, 7, 6, 17.3, 23.2, 'No', 'No'), ('3/30/2015', 17.3, 23.9, 0.0, 4.8, 2.7, 'NW', 28, 'W', 'ENE', 19, 19, 84, 64, 1024.3, 1022.9, 8, 5, 19.1, 23.1, 'No', 'Yes'), ('3/31/2015', 17.3, 24.1, 14.2, 3.0, 3.8, 'ESE', 31, 'W', 'E', 6, 13, 93, 58, 1026.2, 1024.8, 7, 6, 19.7, 22.7, 'Yes', 'Yes'), ('4/1/2015', 17.8, 25.3, 6.0, 4.2, 9.9, 'NNE', 39, 'W', 'ENE', 13, 17, 95, 72, 1025.0, 1021.0, 1, 5, 18.8, 23.6, 'Yes', 'No'), ('4/2/2015', 18.5, 27.9, 0.0, 4.2, 3.9, 'S', 48, 'N', 'E', 7, 11, 86, 57, 1018.9, 1016.3, 7, 7, 20.3, 27.1, 'No', 'No'), ('4/3/2015', 17.9, 19.0, 0.6, 6.4, 0.0, 'S', 48, 'SSE', 'SSW', 13, 13, 91, 89, 1023.9, 1022.9, 8, 8, 18.1, 18.5, 'No', 'Yes'), ('4/4/2015', 17.7, 20.1, 24.0, 5.4, 0.0, 'ESE', 52, 'ESE', 'SE', 33, 26, 95, 93, 1020.3, 1017.4, 8, 8, 18.0, 17.4, 'Yes', 'Yes'), ('4/5/2015', 15.5, 25.9, 21.4, 2.2, 9.7, 'W', 31, 'W', 'ESE', 13, 19, 76, 54, 1010.5, 1005.7, 4, 4, 19.9, 25.6, 'Yes', 'No'), ('4/6/2015', 15.8, 24.9, 0.0, 4.0, 5.1, 'N', 35, 'WNW', 'NW', 7, 15, 81, 62, 1008.0, 1006.6, 1, 8, 19.9, 20.2, 'No', 'No'), ('4/7/2015', 15.1, 23.0, 0.4, 3.2, 9.8, 'NW', 70, 'WNW', 'WNW', 15, 22, 67, 42, 1007.9, 1007.2, 6, 2, 20.0, 21.2, 'No', 'Yes'), ('4/8/2015', 14.2, 22.3, 5.8, 5.6, 4.6, 'WSW', 63, 'WSW', 'WSW', 30, 30, 43, 39, 1010.7, 1013.1, 3, 6, 18.3, 21.0, 'Yes', 'No'), ('4/9/2015', 15.3, 22.2, 0.2, 6.6, 6.1, 'S', 54, 'WSW', 'S', 13, 31, 49, 42, 1020.6, 1020.2, 3, 3, 18.6, 21.2, 'No', 'No'), ('4/10/2015', 14.7, 22.4, 0.4, 5.2, 6.0, 'S', 35, 'SSW', 'S', 13, 20, 82, 58, 1024.8, 1022.8, 7, 3, 16.8, 21.7, 'No', 'Yes'), ('4/11/2015', 15.6, 22.7, 7.8, 1.8, 4.6, 'W', 22, 'W', 'E', 13, 13, 94, 69, 1023.3, 1019.6, 7, 5, 17.5, 20.4, 'Yes', 'No'), ('4/12/2015', 14.8, 23.5, 0.2, 2.0, 8.8, 'SSW', 44, 'WNW', 'SSE', 17, 28, 80, 63, 1018.7, 1018.0, 5, 7, 18.7, 21.4, 'No', 'No'), ('4/13/2015', 14.8, 22.2, 0.0, 4.0, 10.2, 'SSE', 35, 'SW', 'SSE', 13, 19, 65, 50, 1023.7, 1021.3, 3, 3, 19.1, 22.2, 'No', 'No'), ('4/14/2015', 14.5, 22.4, 0.0, 4.2, 8.5, 'ENE', 24, 'WNW', 'ENE', 13, 17, 63, 54, 1023.9, 1021.4, 5, 3, 18.2, 20.8, 'No', 'No'), ('4/15/2015', 15.0, 24.2, 0.0, 5.0, 8.7, 'W', 46, 'W', 'ENE', 15, 19, 72, 66, 1025.1, 1021.6, 7, 2, 18.6, 23.2, 'No', 'No'), ('4/16/2015', 17.7, 31.7, 0.6, 3.2, 10.4, 'SSE', 41, 'WNW', 'ENE', 4, 15, 67, 44, 1022.4, 1019.3, 6, 7, 21.6, 29.2, 'No', 'Yes'), ('4/17/2015', 19.9, 23.7, 1.6, 4.0, 0.0, 'SSE', 20, 'E', 'E', 17, 13, 86, 89, 1024.6, 1021.3, 7, 8, 21.0, 21.0, 'Yes', 'No'), ('4/18/2015', 19.7, 28.6, 0.4, 2.0, 5.0, 'NW', 54, 'N', 'N', 19, 26, 71, 51, 1017.8, 1013.9, 7, 8, 23.7, 26.1, 'No', 'Yes'), ('4/19/2015', 18.0, 22.5, 2.4, 6.6, 6.6, 'S', 61, 'WSW', 'SSE', 22, 35, 50, 69, 1018.5, 1019.6, 6, 7, 19.4, 20.0, 'Yes', 'Yes'), ('4/20/2015', 13.6, 17.2, 13.2, 3.2, 0.0, 'SSE', 83, 'S', 'SSE', 24, 46, 96, 94, 1023.6, 1020.7, 8, 8, 15.0, 17.1, 'Yes', 'Yes'), ('4/21/2015', 14.5, 17.7, 119.4, 4.8, 0.0, 'SSE', 87, 'SSE', 'S', 54, 46, 87, 96, 1019.6, 1016.8, 8, 8, 14.9, 14.6, 'Yes', 'Yes'), ('4/22/2015', 14.1, 17.9, 105.8, 4.8, 0.6, 'S', 72, 'SSW', 'SSW', 20, 22, 98, 94, 1013.4, 1010.5, 8, 7, 16.1, 17.2, 'Yes', 'Yes'), ('4/23/2015', 14.3, 23.8, 29.0, 4.8, 8.6, 'SSE', 26, 'WNW', 'SE', 13, 7, 98, 56, 1012.3, 1009.6, 4, 4, 16.4, 23.1, 'Yes', 'No'), ('4/24/2015', 15.0, 25.1, 0.0, 2.2, 8.5, 'W', 19, 'WNW', 'E', 11, 13, 89, 59, 1008.0, 1004.4, 4, 4, 17.3, 23.9, 'No', 'No'), ('4/25/2015', 14.4, 25.9, 0.2, 4.4, 8.1, 'SSE', 57, 'W', 'ENE', 17, 19, 78, 49, 1008.8, 1004.7, 3, 3, 17.2, 22.5, 'No', 'Yes'), ('4/26/2015', 12.7, 17.1, 13.0, 4.0, 1.3, 'SW', 48, 'W', 'SW', 19, 19, 81, 81, 1008.0, 1010.4, 6, 6, 13.8, 16.2, 'Yes', 'Yes'), ('4/27/2015', 12.5, 20.9, 4.0, 0.4, 10.5, 'S', 35, 'W', 'SSE', 19, 17, 59, 41, 1018.9, 1019.0, 1, 1, 15.3, 20.7, 'Yes', 'No'), ('4/28/2015', 10.3, 20.9, 0.2, 5.6, 10.4, 'SSE', 39, 'WNW', 'S', 20, 22, 63, 50, 1026.1, 1024.5, 1, 1, 14.0, 20.1, 'No', 'No'), ('4/29/2015', 10.6, 18.9, 0.0, 4.0, 0.9, 'SSE', 37, 'WNW', 'SE', 20, 17, 81, 77, 1030.6, 1028.9, 6, 7, 14.0, 17.5, 'No', 'Yes'), ('4/30/2015', 14.0, 20.9, 10.2, 3.8, 3.0, 'SSE', 33, 'SSE', 'SE', 17, 17, 92, 65, 1031.3, 1028.4, 8, 6, 16.0, 20.4, 'Yes', 'Yes'), ('5/1/2015', 14.1, 21.7, 28.4, 2.2, 1.0, 'E', 41, 'SSW', 'ESE', 17, 15, 98, 83, 1028.2, 1024.5, 8, 7, 16.7, 19.8, 'Yes', 'Yes'), ('5/2/2015', 16.6, 23.0, 8.6, 2.6, 2.3, 'ESE', 52, 'ESE', 'NE', 20, 17, 79, 95, 1020.6, 1016.5, 7, 7, 21.7, 19.0, 'Yes', 'Yes'), ('5/3/2015', 18.9, 20.9, 31.6, 1.2, 0.4, 'SSW', 50, 'SSW', 'S', 15, 22, 98, 86, 1014.8, 1012.8, 8, 6, 19.0, 20.8, 'Yes', 'No'), ('5/4/2015', 17.3, 21.8, 0.4, 1.8, 0.3, 'S', 28, 'W', 'SSE', 17, 7, 83, 66, 1016.0, 1013.2, 7, 6, 18.3, 21.6, 'No', 'No'), ('5/5/2015', 14.7, 27.5, 0.0, 1.6, 9.8, 'W', 41, 'NNW', 'NNW', 20, 26, 84, 33, 1008.3, 1003.9, 4, 1, 19.0, 27.0, 'No', 'No'), ('5/6/2015', 13.4, 21.0, 0.2, 6.4, 10.0, 'W', 46, 'W', 'WSW', 28, 26, 41, 29, 1014.0, 1012.5, 0, 0, 15.3, 20.4, 'No', 'No'), ('5/7/2015', 11.5, 20.3, 0.0, 6.6, 10.3, 'W', 56, 'W', 'WSW', 19, 30, 51, 31, 1018.2, 1015.4, 1, 1, 15.1, 19.8, 'No', 'No'), ('5/8/2015', 11.1, 21.0, 0.0, 5.2, 10.3, 'W', 35, 'W', 'WNW', 22, 11, 51, 31, 1019.4, 1016.1, 1, 0, 13.8, 20.5, 'No', 'No'), ('5/9/2015', 11.4, 21.0, 0.0, 2.8, 10.3, 'WNW', 35, 'W', 'NW', 19, 19, 52, 36, 1017.1, 1013.9, 1, 1, 14.5, 20.7, 'No', 'No'), ('5/10/2015', 11.3, 21.2, 0.0, 4.8, 7.8, 'NW', 52, 'N', 'WNW', 20, 26, 49, 33, 1011.3, 1006.0, 1, 5, 15.4, 20.8, 'No', 'No'), ('5/11/2015', 15.4, 21.9, 0.0, 5.0, 10.2, 'WNW', 70, 'WNW', 'WSW', 17, 39, 48, 35, 1010.2, 1009.6, 1, 1, 16.8, 21.1, 'No', 'No'), ('5/12/2015', 12.2, 22.5, 0.0, 6.6, 10.3, 'W', 52, 'NW', 'W', 11, 30, 56, 34, 1014.3, 1010.2, 0, 1, 16.2, 21.9, 'No', 'No'), ('5/13/2015', 13.2, 17.3, 0.0, 4.6, 7.7, 'W', 59, 'W', 'SW', 33, 13, 42, 32, 1015.3, 1016.3, 1, 6, 13.9, 16.4, 'No', 'Yes'), ('5/14/2015', 7.9, 19.3, 2.2, 4.0, 10.1, 'W', 46, 'W', 'W', 28, 20, 49, 34, 1024.7, 1024.2, 1, 2, 11.3, 18.4, 'Yes', 'No'), ('5/15/2015', 10.2, 20.0, 0.2, 4.4, 7.8, 'S', 48, 'W', 'SSW', 22, 24, 59, 61, 1031.4, 1031.1, 1, 5, 14.2, 17.8, 'No', 'No'), ('5/16/2015', 13.0, 20.8, 0.8, 2.8, 9.3, 'S', 41, 'SW', 'S', 19, 20, 87, 50, 1035.4, 1033.7, 3, 3, 15.1, 19.6, 'No', 'No'), ('5/17/2015', 11.1, 20.5, 0.6, 3.0, 3.0, 'W', 24, 'W', 'ESE', 17, 17, 89, 66, 1035.5, 1032.2, 3, 6, 13.0, 18.4, 'No', 'No'), ('5/18/2015', 11.5, 19.3, 0.0, 2.0, 0.5, 'W', 20, 'W', 'SE', 15, 2, 91, 84, 1031.8, 1027.3, 7, 8, 13.8, 18.2, 'No', 'No'), ('5/19/2015', 13.8, 21.5, 0.2, 0.4, 1.8, 'NNW', 28, 'NNE', 'NE', 2, 7, 84, 66, 1020.6, 1015.5, 8, 6, 16.9, 20.9, 'No', 'No'), ('5/20/2015', 16.2, 25.4, 0.4, 1.4, 5.8, 'NW', 31, 'NW', 'ENE', 17, 19, 79, 58, 1015.9, 1013.4, 7, 7, 17.4, 21.6, 'No', 'No'), ('5/21/2015', 14.5, 21.8, 0.2, 4.0, 5.8, 'S', 41, 'W', 'S', 20, 19, 67, 58, 1018.6, 1016.9, 1, 5, 16.5, 19.2, 'No', 'Yes'), ('5/22/2015', 13.0, 17.7, 11.2, 3.4, 1.4, 'S', 72, 'S', 'S', 31, 30, 94, 56, 1016.9, 1020.4, 8, 6, 15.2, 16.9, 'Yes', 'Yes'), ('5/23/2015', 10.2, 19.0, 24.4, 5.6, 8.6, 'SSW', 44, 'W', 'S', 26, 22, 69, 50, 1029.1, 1028.1, 3, 3, 11.8, 17.9, 'Yes', 'No'), ('5/24/2015', 8.3, 20.3, 0.2, 2.8, 8.1, 'W', 35, 'W', 'ESE', 19, 6, 87, 44, 1032.3, 1030.7, 3, 2, 10.1, 18.9, 'No', 'No'), ('5/25/2015', 9.4, 19.5, 0.0, 2.6, 6.0, 'W', 26, 'WNW', 'NNW', 11, 7, 84, 52, 1032.2, 1028.5, 7, 7, 11.4, 18.2, 'No', 'No'), ('5/26/2015', 8.5, 19.0, 0.0, 2.0, 5.9, 'WNW', 30, 'W', 'SSE', 24, 9, 77, 55, 1030.0, 1026.6, 3, 7, 10.4, 17.9, 'No', 'No'), ('5/27/2015', 10.4, 21.6, 0.0, 3.2, 8.3, 'W', 26, 'W', 'WNW', 15, 9, 69, 40, 1025.4, 1021.6, 6, 6, 13.1, 20.5, 'No', 'No'), ('5/28/2015', 11.7, 21.0, 0.0, 1.4, 7.6, 'NNW', 24, 'WNW', 'ENE', 11, 4, 82, 60, 1023.6, 1020.2, 1, 5, 13.6, 20.3, 'No', 'No'), ('5/29/2015', 13.6, 19.2, 0.0, 2.0, 0.6, 'NW', 26, 'W', 'WNW', 9, 7, 79, 65, 1020.6, 1020.1, 8, 6, 17.3, 18.7, 'No', 'No'), ('5/30/2015', 11.1, 18.3, 0.2, 2.4, 1.1, 'W', 28, 'WNW', 'WNW', 11, 9, 84, 52, 1022.0, 1017.8, 7, 7, 13.1, 17.0, 'No', 'No'), ('5/31/2015', 11.5, 15.0, 0.0, 3.4, 0.0, 'W', 30, 'WNW', 'NW', 11, 13, 78, 59, 1016.5, 1012.3, 8, 7, 12.1, 14.5, 'No', 'No'), ('6/1/2015', 10.1, 15.9, 0.0, 0.4, 8.6, 'WSW', 63, 'WSW', 'SW', 28, 26, 47, 25, 1014.7, 1016.7, 5, 2, 13.4, 14.8, 'No', 'No'), ('6/2/2015', 6.1, 16.6, 0.2, 4.6, 9.1, 'WSW', 50, 'WSW', 'S', 31, 20, 47, 41, 1023.8, 1022.4, 1, 1, 9.5, 15.6, 'No', 'No'), ('6/3/2015', 6.1, 18.4, 0.0, 3.2, 8.8, 'W', 35, 'W', 'SSW', 22, 11, 64, 56, 1023.2, 1020.7, 1, 6, 8.8, 15.6, 'No', 'No'), ('6/4/2015', 7.4, 19.0, 0.0, 1.2, 9.0, 'W', 33, 'WNW', 'ENE', 17, 9, 82, 53, 1022.0, 1017.8, 3, 2, 8.9, 17.5, 'No', 'No'), ('6/5/2015', 8.9, 17.7, 0.0, 4.0, 6.9, 'W', 33, 'WSW', 'SSW', 19, 7, 69, 42, 1019.3, 1019.3, 7, 1, 10.2, 16.8, 'No', 'No'), ('6/6/2015', 10.1, 21.0, 1.0, 1.8, 6.1, 'W', 28, 'W', 'W', 20, 4, 66, 45, 1028.3, 1027.0, 2, 1, 11.9, 20.6, 'No', 'No'), ('6/7/2015', 9.3, 22.6, 0.0, 2.2, 9.5, 'NW', 24, 'W', 'N', 17, 15, 89, 43, 1029.0, 1024.1, 1, 5, 10.8, 21.3, 'No', 'No'), ('6/8/2015', 10.8, 22.9, 0.0, 2.8, 8.1, 'WNW', 52, 'WNW', 'WNW', 15, 19, 67, 36, 1024.5, 1019.5, 5, 1, 14.8, 22.5, 'No', 'No'), ('6/9/2015', 13.6, 22.6, 0.0, 4.0, 6.5, 'NNW', 30, 'WNW', 'WSW', 13, 19, 57, 29, 1020.7, 1019.5, 6, 5, 17.1, 21.9, 'No', 'Yes'), ('6/10/2015', 12.8, 14.6, 2.0, 3.0, 0.0, 'SSE', 31, 'W', 'SSW', 11, 9, 94, 92, 1031.1, 1031.2, 7, 7, 12.9, 14.2, 'Yes', 'Yes'), ('6/11/2015', 11.7, 16.1, 6.6, 0.6, 0.2, 'W', 24, 'W', 'N', 9, 4, 83, 69, 1036.8, 1034.4, 7, 7, 13.3, 15.9, 'Yes', 'No'), ('6/12/2015', 12.6, 19.4, 0.4, 1.4, 0.7, 'W', 24, 'W', 'NNW', 13, 4, 88, 57, 1034.6, 1031.5, 7, 6, 13.5, 19.2, 'No', 'No'), ('6/13/2015', 13.1, 19.7, 0.0, 2.4, 4.5, 'NNW', 33, 'W', 'NNW', 17, 11, 85, 46, 1031.3, 1027.1, 7, 7, 13.8, 19.0, 'No', 'No'), ('6/14/2015', 9.5, 19.9, 0.0, 2.0, 8.3, 'WSW', 24, 'W', 'E', 19, 6, 88, 52, 1028.5, 1025.7, 4, 3, 11.2, 18.6, 'No', 'No'), ('6/15/2015', 10.9, 16.9, 0.2, 4.0, 0.6, 'NE', 39, 'WNW', 'W', 13, 9, 85, 79, 1027.8, 1025.2, 7, 7, 12.9, 16.4, 'No', 'Yes'), ('6/16/2015', 12.9, 17.9, 2.6, 4.8, 0.3, 'WNW', 24, 'N', 'NNE', 9, 7, 85, 94, 1022.8, 1018.3, 7, 7, 16.5, 15.8, 'Yes', 'Yes'), ('6/17/2015', 14.7, 17.6, 10.8, 0.6, 0.0, 'NW', 30, 'N', 'W', 9, 7, 95, 92, 1012.5, 1009.1, 8, 8, 16.0, 16.4, 'Yes', 'Yes'), ('6/18/2015', 11.4, 17.4, 2.2, 1.0, 0.8, 'W', 39, 'W', 'SSW', 17, 13, 80, 84, 1014.4, 1013.6, 7, 7, 13.5, 15.8, 'Yes', 'Yes'), ('6/19/2015', 9.6, 14.5, 67.0, 4.8, 2.5, 'W', 41, 'W', 'SSW', 24, 20, 98, 88, 1017.2, 1017.5, 7, 7, 9.9, 12.5, 'Yes', 'Yes'), ('6/20/2015', 8.3, 16.6, 7.2, 2.2, 8.6, 'W', 41, 'W', 'SSW', 15, 13, 76, 59, 1024.1, 1023.4, 2, 7, 9.8, 14.1, 'Yes', 'Yes'), ('6/21/2015', 8.5, 14.1, 1.2, 2.2, 0.0, 'W', 33, 'W', 'SSW', 20, 11, 90, 88, 1028.7, 1027.6, 7, 7, 9.1, 13.7, 'Yes', 'Yes'), ('6/22/2015', 8.0, 19.2, 3.0, 0.6, 7.7, 'W', 22, 'WNW', 'NNE', 13, 7, 94, 45, 1029.6, 1026.1, 1, 7, 9.3, 17.5, 'Yes', 'No'), ('6/23/2015', 8.0, 20.3, 0.0, 2.0, 8.1, 'NNW', 26, 'W', 'NNE', 13, 9, 85, 47, 1026.5, 1023.3, 1, 4, 10.2, 18.7, 'No', 'No'), ('6/24/2015', 10.2, 21.3, 0.0, 3.0, 6.5, 'W', 24, 'W', 'ESE', 11, 6, 82, 41, 1023.2, 1019.9, 5, 7, 13.2, 20.0, 'No', 'No'), ('6/25/2015', 12.7, 19.4, 0.0, 2.4, 4.2, 'SSE', 37, 'W', 'SSE', 19, 20, 77, 74, 1023.3, 1023.5, 6, 7, 15.2, 17.6, 'No', 'Yes'), ('6/26/2015', 10.1, 19.2, 6.2, 2.0, 7.2, 'W', 26, 'WNW', 'NNE', 19, 2, 85, 40, 1032.9, 1031.1, 1, 3, 11.7, 18.7, 'Yes', 'No'), ('6/27/2015', 8.3, 19.4, 0.0, 1.8, 9.7, 'W', 26, 'WNW', 'W', 15, 11, 87, 44, 1032.6, 1029.2, 0, 1, 9.7, 19.0, 'No', 'No'), ('6/28/2015', 7.4, 19.6, 0.0, 2.6, 9.5, 'W', 28, 'W', 'ESE', 20, 9, 73, 53, 1032.9, 1030.9, 0, 1, 9.3, 18.5, 'No', 'No'), ('6/29/2015', 9.3, 19.5, 0.0, 1.0, 5.1, 'W', 22, 'W', 'E', 19, 9, 84, 54, 1033.4, 1030.0, 7, 6, 11.0, 17.8, 'No', 'No'), ('6/30/2015', 9.0, 19.1, 0.0, 1.2, 4.3, 'W', 28, 'W', 'ENE', 22, 7, 94, 56, 1029.4, 1025.0, 7, 5, 10.7, 17.9, 'No', 'No'), ('7/1/2015', 10.7, 17.5, 1.0, 0.6, 8.7, 'W', 33, 'W', 'NW', 19, 9, 85, 37, 1026.2, 1022.6, 5, 1, 12.0, 17.4, 'No', 'No'), ('7/2/2015', 7.0, 16.4, 0.0, 3.0, 8.1, 'WSW', 65, 'W', 'WSW', 22, 33, 70, 40, 1020.0, 1016.8, 7, 1, 8.4, 16.1, 'No', 'No'), ('7/3/2015', 6.2, 16.2, 0.0, 4.0, 9.3, 'W', 44, 'W', 'SSE', 26, 15, 55, 46, 1026.5, 1024.6, 1, 1, 8.1, 15.9, 'No', 'No'), ('7/4/2015', 5.8, 16.1, 0.0, 0.2, 6.8, 'W', 31, 'WNW', 'WNW', 13, 11, 82, 31, 1022.7, 1020.3, 6, 2, 7.6, 15.5, 'No', 'No'), ('7/5/2015', 6.0, 18.6, 0.0, 1.6, 9.3, 'W', 30, 'W', 'ESE', 20, 4, 66, 35, 1022.2, 1018.0, 1, 1, 7.7, 16.6, 'No', 'No'), ('7/6/2015', 6.0, 17.3, 0.0, 3.2, 9.5, 'W', 37, 'WNW', 'W', 17, 22, 58, 34, 1016.3, 1013.3, 1, 1, 8.6, 17.1, 'No', 'No'), ('7/7/2015', 7.8, 14.7, 0.0, 3.2, 2.7, 'SSW', 43, 'W', 'SSW', 24, 11, 58, 85, 1019.8, 1021.7, 5, 8, 11.2, 11.8, 'No', 'Yes'), ('7/8/2015', 7.9, 16.5, 5.6, 0.6, 6.3, 'SSE', 31, 'W', 'SSE', 22, 17, 86, 64, 1028.7, 1027.6, 6, 4, 8.4, 13.7, 'Yes', 'No'), ('7/9/2015', 6.6, 17.6, 0.0, 2.0, 9.6, 'W', 24, 'WNW', 'E', 19, 7, 92, 46, 1030.8, 1026.9, 1, 1, 8.3, 16.4, 'No', 'No'), ('7/10/2015', 7.3, 16.9, 0.0, 1.2, 3.2, 'W', 43, 'W', 'WNW', 13, 13, 92, 61, 1022.6, 1019.0, 4, 7, 9.4, 16.0, 'No', 'No'), ('7/11/2015', 6.6, 19.9, 0.8, 1.4, 9.3, 'WNW', 61, 'W', 'NNW', 20, 17, 100, 48, 1015.4, 1009.4, 0, 1, 7.2, 19.2, 'No', 'Yes'), ('7/12/2015', 7.1, 15.1, 2.2, 2.8, 4.0, 'WNW', 57, 'WNW', 'WNW', 22, 33, 60, 42, 1003.6, 1001.5, 7, 2, 9.8, 13.1, 'Yes', 'Yes'), ('7/13/2015', 8.1, 16.9, 4.8, 4.8, 5.5, 'WSW', 76, 'W', 'WSW', 15, 39, 96, 41, 1000.9, 1002.9, 7, 1, 8.6, 16.5, 'Yes', 'No'), ('7/14/2015', 8.6, 17.6, 0.6, 2.0, 8.3, 'WSW', 44, 'W', 'W', 13, 17, 62, 31, 1011.5, 1010.4, 1, 4, 11.5, 17.6, 'No', 'No'), ('7/15/2015', 6.2, 16.8, 0.2, 3.4, 9.6, 'WNW', 24, 'W', 'ENE', 9, 13, 62, 42, 1018.1, 1016.1, 1, 3, 8.7, 14.9, 'No', 'No'), ('7/16/2015', 8.3, 13.4, 0.2, 3.4, 2.6, 'NW', 43, 'SSW', 'W', 13, 13, 91, 68, 1016.8, 1013.7, 7, 6, 10.3, 12.9, 'No', 'Yes'), ('7/17/2015', 6.2, 14.3, 17.2, 0.0, 1.7, 'SSW', 57, 'W', 'SW', 26, 26, 95, 51, 1010.1, 1012.9, 8, 7, 6.7, 13.5, 'Yes', 'Yes'), ('7/18/2015', 6.6, 14.6, 9.0, 3.0, 4.3, 'SSW', 48, 'WNW', 'SSW', 19, 28, 58, 78, 1025.6, 1027.2, 3, 7, 10.4, 11.8, 'Yes', 'No'), ('7/19/2015', 7.8, 16.7, 0.6, 2.0, 9.0, 'W', 33, 'W', 'S', 17, 17, 84, 55, 1032.6, 1031.1, 3, 2, 10.3, 15.8, 'No', 'No'), ('7/20/2015', 7.8, 17.9, 0.0, 1.6, 4.2, 'W', 26, 'W', 'SE', 20, 15, 84, 64, 1034.6, 1032.1, 3, 6, 10.0, 15.9, 'No', 'Yes'), ('7/21/2015', 8.2, 19.3, 3.0, 0.8, 9.9, 'NNE', 33, 'WNW', 'NE', 17, 15, 93, 54, 1033.1, 1029.3, 1, 1, 9.9, 18.3, 'Yes', 'No'), ('7/22/2015', 9.9, 16.9, 0.0, 4.0, 0.9, 'N', 28, 'SE', 'NNW', 2, 17, 71, 57, 1027.4, 1025.0, 7, 7, 13.4, 16.5, 'No', 'Yes'), ('7/23/2015', 11.2, 19.1, 1.8, 0.8, 2.2, 'W', 28, 'W', 'ESE', 24, 9, 96, 70, 1026.1, 1023.4, 8, 7, 12.0, 16.4, 'Yes', 'No'), ('7/24/2015', 11.6, 20.0, 0.0, 2.0, 3.7, 'NNW', 33, 'W', 'E', 13, 9, 95, 58, 1020.0, 1014.5, 7, 7, 12.9, 18.6, 'No', 'No'), ('7/25/2015', 10.8, 20.8, 0.0, 2.6, 10.1, 'NNW', 31, 'NNW', 'WNW', 11, 15, 50, 29, 1017.5, 1015.8, 1, 1, 14.3, 20.5, 'No', 'No'), ('7/26/2015', 11.0, 20.2, 0.0, 4.6, 9.3, 'NW', 59, 'N', 'WNW', 9, 35, 53, 31, 1017.0, 1012.4, 6, 1, 13.8, 19.5, 'No', 'No'), ('7/27/2015', 7.3, 15.7, 0.0, 5.0, 10.1, 'W', 63, 'W', 'WSW', 20, 26, 41, 28, 1025.0, 1024.5, 1, 1, 10.2, 15.2, 'No', 'No'), ('7/28/2015', 6.4, 17.3, 0.0, 4.8, 9.6, 'W', 41, 'WNW', 'S', 24, 19, 56, 40, 1032.9, 1030.8, 1, 2, 9.6, 16.6, 'No', 'No'), ('7/29/2015', 8.1, 18.4, 0.0, 4.8, 8.5, 'W', 41, 'W', 'ESE', 20, 11, 70, 50, 1035.0, 1030.2, 3, 1, 9.3, 16.4, 'No', 'No'), ('7/30/2015', 8.2, 20.5, 0.0, 1.0, 7.6, 'W', 41, 'W', 'E', 11, 19, 80, 30, 1026.3, 1020.1, 5, 5, 10.7, 19.2, 'No', 'No'), ('7/31/2015', 10.7, 21.0, 0.0, 4.8, 9.5, 'W', 41, 'N', 'WNW', 6, 9, 49, 31, 1021.4, 1019.5, 2, 1, 14.7, 20.4, 'No', 'No'), ('8/1/2015', 9.4, 22.3, 0.0, 3.4, 9.2, 'WNW', 61, 'NW', 'NW', 15, 28, 54, 28, 1018.6, 1015.6, 6, 6, 14.3, 20.7, 'No', 'No'), ('8/2/2015', 14.3, 24.7, 0.0, 5.4, 7.8, 'WNW', 43, 'WNW', 'NW', 9, 20, 51, 30, 1015.1, 1010.4, 5, 5, 16.9, 23.8, 'No', 'No'), ('8/3/2015', 8.4, 19.4, 0.0, 5.4, 10.1, 'WSW', 57, 'WNW', 'WSW', 20, 17, 48, 29, 1015.2, 1013.7, 1, 1, 11.7, 19.0, 'No', 'No'), ('8/4/2015', 8.3, 15.1, 0.0, 3.8, 4.6, 'WSW', 33, 'W', 'SSE', 19, 2, 57, 42, 1023.0, 1018.9, 7, 4, 8.9, 14.4, 'No', 'No'), ('8/5/2015', 5.0, 14.2, 0.0, 0.6, 4.8, 'W', 48, 'WNW', 'WNW', 20, 19, 46, 46, 1014.5, 1010.3, 6, 6, 9.4, 13.0, 'No', 'No'), ('8/6/2015', 6.8, 16.4, 0.0, 3.8, 8.5, 'WSW', 37, 'WNW', 'S', 22, 11, 53, 39, 1016.5, 1016.7, 3, 7, 9.5, 14.3, 'No', 'No'), ('8/7/2015', 6.7, 18.5, 0.0, 2.8, 10.1, 'WNW', 33, 'W', 'SSE', 26, 17, 60, 40, 1024.0, 1021.0, 1, 2, 10.0, 16.1, 'No', 'No'), ('8/8/2015', 7.9, 17.5, 0.0, 2.6, 8.9, 'SSW', 33, 'WNW', 'SSE', 19, 24, 63, 44, 1024.7, 1022.5, 5, 1, 11.0, 16.3, 'No', 'No'), ('8/9/2015', 6.2, 17.6, 0.0, 1.8, 9.5, 'W', 30, 'W', 'E', 20, 13, 68, 56, 1024.8, 1019.6, 1, 1, 9.1, 16.3, 'No', 'No'), ('8/10/2015', 8.6, 20.6, 0.0, 2.6, 10.2, 'NNE', 33, 'W', 'E', 13, 20, 66, 41, 1017.7, 1012.9, 1, 1, 11.8, 18.8, 'No', 'No'), ('8/11/2015', 9.8, 21.0, 0.0, 5.0, 10.5, 'W', 30, 'W', 'WNW', 17, 9, 52, 27, 1014.6, 1011.1, 1, 1, 13.3, 20.4, 'No', 'No'), ('8/12/2015', 8.4, 17.5, 0.0, 3.8, 8.7, 'NW', 74, 'W', 'WNW', 19, 28, 54, 37, 1007.9, 1004.0, 1, 1, 11.1, 16.2, 'No', 'No'), ('8/13/2015', 9.4, 19.8, 0.0, 4.8, 10.5, 'WSW', 48, 'WSW', 'SW', 28, 17, 50, 23, 1014.9, 1014.7, 1, 1, 12.3, 19.3, 'No', 'No'), ('8/14/2015', 7.9, 20.4, 0.0, 4.0, 10.5, 'WSW', 30, 'W', 'E', 15, 19, 55, 38, 1025.1, 1023.4, 1, 1, 11.8, 18.0, 'No', 'No'), ('8/15/2015', 8.2, 18.1, 0.0, 3.0, 7.3, 'W', 30, 'WNW', 'SSE', 20, 19, 63, 61, 1030.5, 1028.8, 3, 5, 12.4, 17.0, 'No', 'No'), ('8/16/2015', 10.5, 19.8, 0.0, 3.0, 9.2, 'NW', 28, 'W', 'NE', 13, 15, 70, 63, 1027.4, 1021.4, 5, 4, 14.0, 17.4, 'No', 'Yes'), ('8/17/2015', 9.3, 20.5, 5.6, 2.8, 10.4, 'WSW', 46, 'W', 'NW', 13, 13, 53, 29, 1017.1, 1013.3, 3, 1, 13.4, 20.4, 'Yes', 'No'), ('8/18/2015', 10.9, 16.2, 0.0, 4.4, 10.4, 'SW', 39, 'WSW', 'SSE', 20, 19, 40, 46, 1020.8, 1021.0, 1, 2, 12.6, 14.7, 'No', 'No'), ('8/19/2015', 9.0, 17.0, 0.0, 3.6, 6.6, 'WNW', 24, 'W', 'E', 17, 13, 58, 54, 1027.2, 1025.0, 3, 6, 12.5, 16.4, 'No', 'No'), ('8/20/2015', 8.2, 18.9, 0.0, 2.6, 9.8, 'NE', 31, 'WNW', 'NE', 11, 20, 71, 59, 1028.3, 1025.0, 1, 1, 12.1, 18.7, 'No', 'No'), ('8/21/2015', 9.4, 21.0, 0.0, 3.8, 9.4, 'NNE', 31, 'WNW', 'NE', 13, 15, 73, 63, 1025.8, 1021.2, 0, 7, 13.0, 19.8, 'No', 'No'), ('8/22/2015', 12.9, 28.3, 0.0, 4.2, 9.4, 'NNW', 33, 'N', 'N', 19, 11, 45, 32, 1021.0, 1016.2, 2, 5, 19.8, 26.9, 'No', 'Yes'), ('8/23/2015', 15.4, 18.5, 2.4, 6.4, 0.2, 'NNW', 22, 'N', 'NNW', 7, 7, 85, 73, 1021.8, 1018.4, 7, 7, 15.6, 17.9, 'Yes', 'Yes'), ('8/24/2015', 15.1, 17.4, 4.2, 1.8, 0.6, 'E', 59, 'S', 'SSE', 17, 9, 90, 95, 1018.4, 1015.0, 8, 7, 16.3, 16.4, 'Yes', 'Yes'), ('8/25/2015', 12.5, 19.9, 54.4, 5.0, 4.4, 'NW', 56, 'WNW', 'W', 22, 20, 66, 53, 1013.4, 1012.8, 7, 7, 16.1, 18.7, 'Yes', 'Yes'), ('8/26/2015', 12.3, 20.2, 5.2, 2.8, 6.3, 'SSW', 28, 'SSE', 'S', 13, 13, 80, 59, 1018.1, 1017.8, 7, 7, 16.3, 18.9, 'Yes', 'No'), ('8/27/2015', 11.6, 20.5, 0.0, 3.0, 4.3, 'W', 52, 'W', 'NW', 9, 17, 87, 44, 1019.7, 1015.1, 7, 6, 15.1, 20.1, 'No', 'No'), ('8/28/2015', 10.6, 20.8, 0.0, 2.8, 9.2, 'WSW', 48, 'W', 'S', 22, 20, 48, 43, 1019.8, 1018.9, 3, 5, 14.6, 18.5, 'No', 'No'), ('8/29/2015', 9.0, 20.3, 0.0, 4.2, 10.8, 'WSW', 30, 'W', 'WNW', 13, 15, 60, 31, 1022.7, 1017.9, 1, 2, 13.0, 20.1, 'No', 'No'), ('8/30/2015', 8.3, 18.7, 0.0, 3.6, 10.8, 'SSW', 39, 'WNW', 'S', 20, 22, 52, 44, 1020.3, 1017.5, 1, 3, 12.1, 18.1, 'No', 'No'), ('8/31/2015', 9.6, 19.7, 0.0, 4.8, 10.9, 'SSE', 35, 'WSW', 'SSE', 15, 22, 48, 39, 1017.3, 1013.8, 1, 2, 13.9, 18.4, 'No', 'No'), ('9/1/2015', 9.0, 19.7, 0.0, 3.2, 10.8, 'W', 31, 'W', 'ESE', 17, 13, 50, 39, 1015.8, 1013.3, 1, 1, 12.7, 17.0, 'No', 'No'), ('9/2/2015', 8.0, 18.8, 0.0, 4.0, 10.4, 'WNW', 31, 'W', 'ENE', 11, 19, 61, 46, 1018.0, 1012.0, 5, 1, 11.9, 18.6, 'No', 'Yes'), ('9/3/2015', 11.2, 20.8, 2.8, 5.6, 8.0, 'SW', 52, 'WNW', 'WSW', 20, 24, 69, 28, 1006.0, 1005.6, 3, 6, 14.4, 20.6, 'Yes', 'Yes'), ('9/4/2015', 12.5, 19.5, 20.4, 4.0, 5.7, 'S', 48, 'SSW', 'S', 19, 20, 92, 54, 1021.5, 1020.5, 7, 2, 13.7, 18.3, 'Yes', 'No'), ('9/5/2015', 11.5, 21.7, 0.0, 2.8, 9.3, 'ESE', 37, 'WNW', 'SE', 17, 24, 68, 53, 1022.3, 1019.6, 1, 5, 15.2, 18.7, 'No', 'No'), ('9/6/2015', 12.7, 17.5, 0.4, 5.4, 1.0, 'ENE', 24, 'NNE', 'ENE', 11, 6, 84, 68, 1024.9, 1021.9, 7, 7, 14.6, 16.0, 'No', 'No'), ('9/7/2015', 11.1, 24.9, 0.2, 0.6, 9.3, 'W', 54, 'W', 'W', 9, 15, 62, 32, 1018.3, 1013.3, 2, 4, 17.4, 22.7, 'No', 'No'), ('9/8/2015', 10.0, 20.0, 0.0, 6.8, 11.0, 'W', 52, 'WSW', 'W', 30, 24, 42, 32, 1018.8, 1015.7, 1, 2, 13.3, 19.7, 'No', 'No'), ('9/9/2015', 9.8, 20.2, 0.0, 5.0, 10.9, 'W', 41, 'W', 'SSE', 20, 17, 48, 39, 1023.1, 1022.0, 1, 1, 15.4, 18.9, 'No', 'No'), ('9/10/2015', 11.3, 19.6, 0.0, 4.8, 6.5, 'SSW', 37, 'WNW', 'SSE', 13, 15, 59, 41, 1030.9, 1029.8, 1, 7, 15.5, 18.9, 'No', 'No'), ('9/11/2015', 14.0, 21.3, 0.0, 4.0, 9.1, 'NNE', 39, 'WNW', 'NE', 11, 24, 56, 44, 1032.1, 1027.6, 1, 0, 17.6, 20.5, 'No', 'No'), ('9/12/2015', 10.9, 25.4, 0.0, 7.4, 10.4, 'ENE', 24, 'W', 'E', 11, 19, 61, 51, 1028.5, 1024.7, 1, 5, 17.2, 21.3, 'No', 'No'), ('9/13/2015', 12.4, 22.3, 0.0, 3.8, 10.6, 'NNE', 30, 'WNW', 'E', 11, 20, 61, 60, 1028.5, 1025.0, 1, 1, 18.3, 21.4, 'No', 'No'), ('9/14/2015', 15.3, 23.6, 0.0, 5.0, 10.7, 'NE', 43, 'NNE', 'NE', 17, 24, 58, 59, 1025.9, 1020.5, 1, 1, 20.7, 21.4, 'No', 'No'), ('9/15/2015', 15.8, 29.8, 0.0, 6.4, 11.0, 'W', 41, 'NNE', 'NNW', 9, 35, 33, 25, 1015.4, 1009.0, 1, 3, 23.5, 29.2, 'No', 'No'), ('9/16/2015', 12.4, 21.1, 0.0, 10.2, 10.2, 'ESE', 37, 'W', 'ESE', 19, 26, 42, 60, 1017.7, 1015.0, 2, 3, 17.2, 19.3, 'No', 'No'), ('9/17/2015', 12.2, 19.9, 0.0, 4.2, 8.2, 'S', 43, 'WNW', 'SE', 9, 28, 53, 57, 1018.4, 1018.3, 3, 7, 18.0, 17.7, 'No', 'Yes'), ('9/18/2015', 13.6, 20.0, 2.2, 6.4, 7.7, 'S', 52, 'S', 'S', 20, 26, 65, 44, 1026.2, 1025.5, 5, 2, 15.8, 18.9, 'Yes', 'Yes'), ('9/19/2015', 12.5, 19.5, 10.8, 5.4, 7.3, 'E', 33, 'W', 'ESE', 17, 24, 88, 54, 1026.5, 1023.9, 7, 6, 14.7, 18.1, 'Yes', 'No'), ('9/20/2015', 12.5, 18.6, 0.4, 4.0, 3.4, 'ENE', 37, 'W', 'E', 11, 13, 62, 72, 1024.5, 1021.7, 5, 7, 16.6, 17.4, 'No', 'No'), ('9/21/2015', 12.4, 22.5, 0.2, 1.6, 10.4, 'SSW', 35, 'W', 'NE', 15, 15, 74, 60, 1019.9, 1015.2, 1, 2, 16.3, 21.3, 'No', 'No'), ('9/22/2015', 14.6, 19.5, 0.2, 6.2, 9.2, 'SSW', 59, 'SW', 'S', 24, 37, 36, 47, 1016.8, 1017.5, 3, 2, 18.7, 17.8, 'No', 'No'), ('9/23/2015', 10.0, 16.2, 0.2, 8.8, 6.5, 'S', 69, 'SSW', 'SSW', 31, 35, 55, 74, 1025.5, 1025.4, 3, 7, 13.3, 11.7, 'No', 'Yes'), ('9/24/2015', 8.3, 16.3, 3.2, 4.0, 6.1, 'S', 65, 'SSW', 'SSW', 22, 28, 63, 62, 1025.6, 1024.6, 7, 7, 13.0, 13.6, 'Yes', 'Yes'), ('9/25/2015', 10.1, 16.4, 31.8, 2.8, 4.3, 'S', 54, 'S', 'SSE', 13, 26, 91, 63, 1029.3, 1027.8, 7, 7, 13.4, 15.9, 'Yes', 'Yes'), ('9/26/2015', 11.1, 20.1, 3.4, 4.4, 7.7, 'S', 43, 'W', 'SSE', 22, 24, 86, 48, 1028.5, 1025.4, 6, 3, 14.4, 18.4, 'Yes', 'Yes'), ('9/27/2015', 12.3, 19.2, 3.6, 3.8, 6.2, 'SW', 46, 'SW', 'S', 20, 20, 70, 51, 1023.7, 1021.1, 7, 7, 15.3, 18.3, 'Yes', 'No'), ('9/28/2015', 10.9, 20.8, 0.2, 4.2, 11.0, 'W', 28, 'W', 'ESE', 15, 17, 56, 49, 1021.1, 1017.8, 1, 1, 17.3, 19.1, 'No', 'No'), ('9/29/2015', 11.9, 23.4, 0.0, 5.8, 3.4, 'NW', 50, 'N', 'NE', 15, 17, 58, 55, 1019.5, 1015.8, 0, 1, 19.1, 21.7, 'No', 'No'), ('9/30/2015', 16.7, 21.4, 0.0, 5.6, 6.4, 'SSE', 33, 'SSE', 'ESE', 17, 20, 57, 62, 1022.1, 1021.4, 7, 7, 21.0, 18.7, 'No', 'No'), ('10/1/2015', 16.8, 22.9, 0.0, 5.6, 9.6, 'ENE', 33, 'W', 'E', 6, 24, 68, 65, 1026.4, 1022.8, 4, 1, 19.9, 21.7, 'No', 'No'), ('10/2/2015', 16.5, 23.0, 0.0, 4.8, 10.5, 'SSE', 33, 'NNW', 'ENE', 4, 24, 57, 57, 1033.4, 1031.8, 1, 1, 21.3, 21.1, 'No', 'No'), ('10/3/2015', 14.2, 27.5, 0.0, 7.2, 11.1, 'E', 22, 'W', 'E', 13, 11, 62, 47, 1030.6, 1024.7, 0, 1, 21.5, 27.3, 'No', 'No'), ('10/4/2015', 19.8, 33.8, 0.0, 8.0, 8.2, 'WSW', 46, 'W', 'W', 4, 28, 28, 13, 1023.4, 1021.8, 7, 7, 26.4, 32.6, 'No', 'No'), ('10/5/2015', 16.1, 37.0, 0.0, 11.0, 11.4, 'S', 20, 'WNW', 'E', 11, 11, 42, 16, 1024.0, 1021.1, 1, 7, 21.1, 35.6, 'No', 'No'), ('10/6/2015', 20.3, 32.3, 0.0, 8.6, 11.4, 'NNE', 43, 'WNW', 'ENE', 15, 17, 37, 26, 1023.2, 1019.7, 1, 1, 23.8, 30.6, 'No', 'No'), ('10/7/2015', 19.7, 21.5, 0.0, 13.2, 1.3, 'SSW', 67, 'SSE', 'SE', 39, 26, 61, 56, 1029.6, 1033.6, 5, 7, 20.3, 19.0, 'No', 'No'), ('10/8/2015', 17.0, 21.1, 0.0, 6.6, 2.2, 'ENE', 35, 'ESE', 'E', 13, 20, 53, 57, 1038.8, 1036.0, 7, 7, 18.5, 19.9, 'No', 'No'), ('10/9/2015', 16.8, 22.7, 0.0, 5.4, 8.7, 'ENE', 43, 'N', 'NE', 15, 24, 51, 51, 1034.4, 1029.7, 7, 5, 20.1, 22.0, 'No', 'No'), ('10/10/2015', 15.7, 24.3, 0.0, 6.8, 9.5, 'E', 24, 'SE', 'E', 2, 17, 62, 60, 1028.9, 1025.8, 1, 4, 21.2, 22.3, 'No', 'No'), ('10/11/2015', 15.0, 24.3, 0.0, 5.6, 6.4, 'W', 41, 'WNW', 'ENE', 9, 11, 77, 65, 1022.7, 1018.6, 6, 7, 18.7, 21.4, 'No', 'Yes'), ('10/12/2015', 16.5, 29.5, 3.6, 5.0, 9.6, 'SSE', 43, 'WSW', 'NE', 11, 19, 50, 55, 1016.7, 1012.4, 1, 6, 22.7, 23.4, 'Yes', 'Yes'), ('10/13/2015', 17.5, 20.4, 1.6, 7.8, 0.8, 'SSW', 37, 'S', 'ESE', 20, 20, 82, 77, 1022.3, 1022.3, 4, 8, 18.3, 19.8, 'Yes', 'Yes'), ('10/14/2015', 16.9, 23.3, 3.4, 1.4, 8.3, 'NE', 37, 'W', 'NE', 6, 20, 75, 60, 1026.8, 1025.2, 7, 1, 20.1, 22.7, 'Yes', 'No'), ('10/15/2015', 16.3, 24.0, 0.0, 7.0, 12.0, 'NE', 44, 'NNE', 'ENE', 13, 30, 65, 63, 1026.2, 1022.0, 1, 0, 21.6, 23.1, 'No', 'No'), ('10/16/2015', 17.3, 27.5, 0.0, 6.8, 11.9, 'NNE', 43, 'ESE', 'E', 6, 20, 60, 52, 1021.7, 1018.7, 0, 1, 23.3, 27.3, 'No', 'No'), ('10/17/2015', 19.1, 26.0, 0.0, 9.8, 9.7, 'SSE', 31, 'SSE', 'ESE', 17, 15, 66, 64, 1023.1, 1021.4, 1, 4, 21.5, 23.0, 'No', 'Yes'), ('10/18/2015', 18.8, 23.2, 1.4, 7.2, 3.8, 'SSE', 35, 'SE', 'E', 17, 15, 69, 56, 1029.2, 1027.9, 8, 7, 19.5, 22.1, 'Yes', 'No'), ('10/19/2015', 19.4, 24.6, 0.2, 4.2, 8.2, 'NE', 39, 'N', 'ENE', 11, 24, 81, 54, 1026.6, 1022.4, 7, 4, 21.8, 24.4, 'No', 'No'), ('10/20/2015', 18.7, 26.8, 0.4, 6.8, 7.7, 'W', 35, 'SE', 'ENE', 6, 15, 60, 55, 1020.6, 1016.3, 2, 2, 23.7, 26.0, 'No', 'No'), ('10/21/2015', 19.7, 27.9, 1.0, 7.6, 3.4, 'NNE', 31, 'WNW', 'W', 2, 9, 58, 43, 1013.8, 1011.5, 4, 7, 24.5, 26.3, 'No', 'Yes'), ('10/22/2015', 18.6, 20.5, 8.4, 5.0, 0.7, 'S', 61, 'S', 'SSW', 11, 31, 89, 74, 1011.4, 1010.3, 7, 7, 19.6, 20.1, 'Yes', 'Yes'), ('10/23/2015', 14.5, 21.4, 14.8, 2.8, 3.4, 'SSW', 41, 'SSW', 'SSW', 19, 17, 70, 55, 1022.1, 1021.6, 7, 7, 16.6, 19.4, 'Yes', 'No'), ('10/24/2015', 12.9, 22.3, 0.2, 4.6, 12.0, 'ENE', 39, 'WNW', 'ENE', 13, 26, 62, 54, 1024.4, 1020.9, 5, 1, 17.8, 20.7, 'No', 'No'), ('10/25/2015', 15.2, 24.9, 0.0, 7.4, 10.2, 'NE', 43, 'E', 'NE', 7, 19, 62, 59, 1022.1, 1017.8, 2, 3, 21.1, 22.3, 'No', 'No'), ('10/26/2015', 17.5, 29.4, 0.0, 7.0, 5.2, 'WSW', 69, 'ESE', 'WSW', 9, 13, 54, 53, 1014.4, 1015.1, 3, 7, 24.6, 22.2, 'No', 'Yes'), ('10/27/2015', 15.5, 19.6, 7.6, 7.8, 2.0, 'S', 54, 'S', 'SSE', 19, 30, 65, 47, 1025.8, 1025.8, 8, 7, 16.5, 19.3, 'Yes', 'No'), ('10/28/2015', 13.4, 21.2, 0.4, 3.8, 8.2, 'SSE', 31, 'W', 'E', 9, 20, 70, 45, 1025.3, 1022.5, 7, 5, 16.4, 20.6, 'No', 'No'), ('10/29/2015', 15.7, 23.0, 0.0, 5.4, 11.4, 'E', 31, 'WNW', 'E', 7, 22, 55, 40, 1023.6, 1022.1, 5, 1, 18.2, 21.9, 'No', 'No'), ('10/30/2015', 14.1, 23.1, 0.0, 8.0, 9.3, 'ENE', 39, 'W', 'NE', 7, 24, 59, 48, 1023.8, 1020.8, 1, 7, 19.0, 21.8, 'No', 'No'), ('10/31/2015', 17.1, 24.2, 0.0, 8.0, 5.7, 'NE', 48, 'NE', 'NE', 19, 28, 59, 61, 1021.8, 1018.6, 7, 8, 22.2, 22.5, 'No', 'No'), ('11/1/2015', 17.5, 26.8, 0.0, 7.8, 9.0, 'NE', 44, 'E', 'NE', 15, 17, 67, 59, 1015.2, 1010.6, 1, 3, 21.9, 25.4, 'No', 'Yes'), ('11/2/2015', 18.2, 30.7, 26.0, 6.6, 9.1, 'WSW', 46, 'NW', 'E', 13, 15, 75, 53, 1011.2, 1009.0, 5, 5, 21.6, 26.4, 'Yes', 'Yes'), ('11/3/2015', 18.6, 20.0, 1.4, 6.8, 0.0, 'S', 35, 'SSE', 'SE', 19, 17, 91, 89, 1017.0, 1016.5, 8, 8, 19.0, 19.2, 'Yes', 'Yes'), ('11/4/2015', 17.1, 19.6, 3.8, 1.4, 0.0, 'E', 56, 'ESE', 'E', 24, 31, 91, 83, 1017.6, 1016.3, 8, 8, 19.5, 19.4, 'Yes', 'Yes'), ('11/5/2015', 16.0, 23.4, 13.0, 0.0, 0.7, 'ENE', 50, 'NE', 'NE', 30, 26, 94, 80, 1014.8, 1010.5, 8, 8, 18.2, 20.5, 'Yes', 'Yes'), ('11/6/2015', 18.2, 28.3, 11.6, 3.2, 5.2, 'S', 33, 'W', 'NE', 9, 13, 77, 87, 1007.7, 1006.3, 4, 7, 23.3, 20.5, 'Yes', 'Yes'), ('11/7/2015', 18.4, 24.6, 10.0, 5.6, 5.3, 'SSE', 46, 'ESE', 'ESE', 9, 28, 69, 69, 1012.3, 1012.3, 3, 7, 22.5, 21.8, 'Yes', 'No'), ('11/8/2015', 16.2, 21.7, 0.4, 7.2, 4.6, 'SSW', 46, 'SSW', 'SSE', 17, 26, 67, 65, 1020.7, 1020.0, 7, 6, 18.0, 20.4, 'No', 'No'), ('11/9/2015', 13.7, 23.3, 0.0, 6.4, 12.3, 'E', 30, 'W', 'E', 11, 17, 59, 48, 1021.3, 1017.5, 5, 1, 19.5, 21.8, 'No', 'No'), ('11/10/2015', 15.2, 25.6, 0.0, 6.0, 11.3, 'ENE', 30, 'S', 'ENE', 2, 19, 61, 45, 1016.0, 1013.5, 3, 7, 20.6, 24.8, 'No', 'No'), ('11/11/2015', 18.9, 23.9, 0.0, 8.6, 0.0, 'SSW', 31, 'S', 'ESE', 13, 11, 82, 66, 1020.3, 1020.3, 7, 7, 20.0, 22.1, 'No', 'Yes'), ('11/12/2015', 18.3, 25.5, 2.4, 4.8, 4.2, 'NNE', 43, 'NNE', 'ENE', 17, 17, 53, 69, 1020.4, 1018.0, 7, 8, 23.5, 22.2, 'Yes', 'No'), ('11/13/2015', 18.0, 28.8, 0.4, 8.4, 7.4, 'SSW', 48, 'W', 'NE', 7, 6, 63, 60, 1013.1, 1009.8, 1, 7, 22.7, 23.3, 'No', 'Yes'), ('11/14/2015', 17.7, 20.1, 18.2, 9.0, 0.0, 'SSE', 33, 'S', 'ESE', 15, 19, 81, 70, 1014.4, 1013.4, 8, 8, 18.7, 18.9, 'Yes', 'Yes'), ('11/15/2015', 14.9, 20.9, 29.6, 2.2, 0.8, 'SSW', 46, 'SSE', 'S', 24, 19, 64, 70, 1017.7, 1017.4, 7, 7, 18.2, 18.5, 'Yes', 'Yes'), ('11/16/2015', 14.3, 22.6, 5.0, 4.4, 13.0, 'ESE', 31, 'SSE', 'ESE', 17, 20, 56, 43, 1020.0, 1018.0, 5, 1, 19.1, 21.7, 'Yes', 'No'), ('11/17/2015', 14.4, 25.1, 0.0, 8.0, 12.6, 'NNE', 44, 'W', 'NE', 6, 22, 55, 46, 1019.1, 1016.0, 0, 2, 20.2, 23.7, 'No', 'No'), ('11/18/2015', 17.4, 36.5, 0.0, 11.0, 13.0, 'SSW', 57, 'W', 'W', 11, 22, 45, 17, 1013.6, 1009.7, 5, 1, 25.1, 35.6, 'No', 'No'), ('11/19/2015', 18.8, 31.2, 0.0, 10.4, 12.5, 'SSW', 28, 'W', 'E', 9, 17, 62, 54, 1015.0, 1011.7, 1, 4, 23.1, 28.6, 'No', 'No'), ('11/20/2015', 21.4, 40.9, 0.0, 8.8, 12.4, 'W', 54, 'SW', 'WNW', 2, 28, 63, 13, 1012.5, 1006.3, 1, 1, 25.2, 40.7, 'No', 'No'), ('11/21/2015', 20.3, 22.1, 0.0, 14.6, 0.3, 'S', 54, 'SE', 'SE', 13, 24, 65, 56, 1015.6, 1017.3, 7, 7, 20.8, 20.7, 'No', 'No'), ('11/22/2015', 19.0, 22.4, 0.0, 6.2, 2.7, 'NNE', 33, 'E', 'ENE', 17, 17, 59, 58, 1019.7, 1016.7, 7, 8, 19.8, 20.8, 'No', 'No'), ('11/23/2015', 17.1, 26.5, 0.0, 3.8, 11.5, 'SSE', 52, 'WNW', 'SE', 11, 30, 60, 52, 1011.9, 1010.8, 1, 2, 22.4, 25.4, 'No', 'No'), ('11/24/2015', 18.7, 25.2, 0.0, 8.0, 11.4, 'NE', 52, 'ENE', 'NE', 13, 28, 57, 55, 1017.4, 1014.1, 4, 1, 23.6, 23.0, 'No', 'No'), ('11/26/2015', 22.4, 37.8, 0.0, 12.6, 9.6, 'W', 74, 'NNW', 'W', 28, 35, 31, 14, 999.8, 1000.0, 1, 2, 32.4, 36.0, 'No', 'No'), ('11/27/2015', 16.5, 22.6, 0.6, 14.6, 7.1, 'ENE', 37, 'SE', 'ESE', 4, 22, 54, 60, 1016.1, 1013.8, 7, 4, 21.1, 21.6, 'No', 'No'), ('11/28/2015', 19.1, 23.8, 0.0, 7.4, 0.3, 'ENE', 37, 'ENE', 'NE', 20, 17, 69, 55, 1016.7, 1016.0, 8, 8, 21.5, 22.5, 'No', 'No'), ('11/29/2015', 19.9, 26.0, 0.0, 6.4, 7.1, 'ENE', 43, 'NNE', 'NE', 17, 22, 80, 65, 1013.7, 1009.7, 7, 2, 21.1, 25.1, 'No', 'No'), ('11/30/2015', 18.2, 26.3, 0.2, 7.4, 11.1, 'S', 48, 'WSW', 'E', 7, 22, 65, 65, 1012.4, 1008.7, 4, 1, 21.1, 23.8, 'No', 'No'), ('12/1/2015', 19.0, 33.3, 0.0, 8.0, 10.4, 'S', 63, 'ESE', 'NE', 9, 31, 58, 34, 1010.3, 1006.7, 1, 5, 26.3, 32.0, 'No', 'No'), ('12/2/2015', 19.2, 22.8, 0.0, 14.2, 5.3, 'SSE', 61, 'S', 'S', 22, 35, 66, 59, 1015.1, 1017.0, 7, 7, 21.0, 19.4, 'No', 'No'), ('12/3/2015', 17.1, 21.7, 0.0, 9.2, 8.1, 'ESE', 31, 'ESE', 'ESE', 11, 20, 52, 49, 1027.1, 1026.0, 7, 5, 19.4, 20.3, 'No', 'No'), ('12/4/2015', 14.6, 23.6, 0.0, 6.4, 9.3, 'E', 28, 'WNW', 'E', 6, 19, 53, 44, 1026.3, 1024.1, 4, 3, 20.3, 22.8, 'No', 'No'), ('12/6/2015', 16.6, 25.8, 0.0, 9.0, 12.7, 'ENE', 35, 'SE', 'ENE', 7, 24, 58, 46, 1020.5, 1017.8, 3, 5, 23.0, 24.9, 'No', 'No'), ('12/7/2015', 18.8, 25.5, 0.0, 9.2, 7.9, 'E', 39, 'ESE', 'E', 9, 22, 61, 57, 1021.4, 1019.9, 7, 7, 23.2, 24.1, 'No', 'No'), ('12/8/2015', 20.9, 25.0, 0.0, 7.6, 0.3, 'NE', 43, 'NE', 'ENE', 11, 17, 68, 64, 1018.6, 1015.8, 7, 7, 22.7, 24.4, 'No', 'No'), ('12/9/2015', 21.3, 33.3, 0.8, 4.6, 8.6, 'S', 61, 'NNE', 'ENE', 7, 17, 70, 58, 1014.2, 1012.1, 5, 3, 24.6, 27.5, 'No', 'Yes'), ('12/10/2015', 20.2, 25.5, 15.2, 10.0, 6.4, 'SSW', 44, 'S', 'E', 7, 19, 80, 63, 1015.9, 1011.7, 7, 3, 21.3, 25.0, 'Yes', 'No'), ('12/11/2015', 21.2, 35.3, 0.2, 6.4, 8.8, 'W', 59, 'W', 'WNW', 17, 30, 66, 13, 1005.8, 1001.1, 3, 7, 24.4, 34.7, 'No', 'No'), ('12/12/2015', 18.4, 22.6, 0.0, 12.2, 5.8, 'ESE', 39, 'E', 'ESE', 15, 28, 57, 50, 1014.7, 1015.1, 3, 4, 20.8, 21.4, 'No', 'No'), ('12/13/2015', 18.2, 24.4, 0.0, 7.6, 6.5, 'NE', 48, 'NE', 'NE', 19, 30, 58, 56, 1019.3, 1016.1, 5, 7, 21.4, 23.2, 'No', 'No'), ('12/14/2015', 18.3, 29.6, 0.0, 8.0, 13.1, 'ENE', 28, 'WNW', 'E', 9, 19, 63, 59, 1015.4, 1013.4, 3, 3, 23.4, 25.5, 'No', 'No'), ('12/15/2015', 20.6, 26.9, 0.0, 10.0, 5.7, 'ENE', 43, 'ENE', 'ENE', 11, 22, 72, 65, 1015.3, 1012.5, 6, 8, 23.1, 25.0, 'No', 'No'), ('12/16/2015', 21.1, 23.4, 0.6, 5.4, 1.8, 'SSE', 80, 'NE', 'N', 22, 13, 87, 82, 1014.8, 1016.7, 7, 8, 22.9, 18.2, 'No', 'Yes'), ('12/17/2015', 16.6, 26.1, 9.8, 4.8, 12.0, 'E', 37, 'WNW', 'E', 9, 24, 70, 60, 1018.5, 1016.9, 4, 1, 21.6, 24.6, 'Yes', 'No'), ('12/18/2015', 19.0, 27.5, 0.0, 13.6, 12.3, 'NNE', 46, 'E', 'ENE', 15, 30, 58, 53, 1016.8, 1014.0, 0, 1, 24.5, 27.1, 'No', 'No'), ('12/19/2015', 20.3, 29.0, 0.0, 9.4, 13.2, 'NE', 52, 'ESE', 'NE', 9, 20, 59, 53, 1014.6, 1012.8, 1, 1, 26.3, 27.5, 'No', 'No'), ('12/21/2015', 23.6, 29.1, 0.0, 14.0, 3.6, 'SSE', 50, 'ENE', 'S', 7, 22, 56, 79, 1014.8, 1017.2, 6, 8, 27.1, 21.5, 'No', 'Yes'), ('12/22/2015', 17.7, 21.8, 29.8, 4.4, 0.0, 'ESE', 44, 'SSW', 'NE', 19, 2, 89, 90, 1023.2, 1021.5, 8, 8, 17.8, 17.7, 'Yes', 'Yes'), ('12/23/2015', 17.3, 23.0, 34.0, 3.6, 4.5, 'ESE', 31, 'SE', 'ESE', 13, 22, 65, 59, 1019.4, 1017.7, 7, 7, 21.8, 22.0, 'Yes', 'No'), ('12/24/2015', 16.9, 24.6, 1.0, 5.0, 9.5, 'E', 37, 'ESE', 'ESE', 20, 20, 60, 52, 1019.9, 1018.7, 4, 2, 21.6, 23.9, 'No', 'No'), ('12/25/2015', 17.5, 25.2, 0.0, 7.0, 9.6, 'ENE', 35, 'ENE', 'E', 4, 20, 55, 48, 1018.7, 1015.4, 5, 4, 21.8, 24.5, 'No', 'No'), ('12/26/2015', 18.8, 26.1, 0.6, 7.4, 6.1, 'NE', 39, 'N', 'NE', 17, 17, 74, 77, 1009.7, 1006.0, 5, 7, 22.7, 23.4, 'No', 'Yes'), ('12/27/2015', 17.1, 23.0, 1.8, 8.8, 5.7, 'S', 59, 'SSE', 'S', 22, 28, 74, 47, 1016.7, 1018.4, 8, 1, 17.1, 22.3, 'Yes', 'Yes'), ('12/28/2015', 15.3, 22.6, 2.6, 5.8, 4.8, 'SSW', 44, 'SW', 'SSE', 20, 24, 78, 50, 1023.7, 1023.0, 7, 7, 16.7, 21.6, 'Yes', 'No'), ('12/29/2015', 15.4, 24.9, 0.2, 7.4, 12.5, 'SSE', 35, 'SE', 'ESE', 20, 22, 51, 38, 1022.4, 1020.7, 6, 1, 21.2, 24.1, 'No', 'No'), ('12/30/2015', 15.0, 25.6, 0.0, 7.4, 13.1, 'ESE', 26, 'NW', 'E', 6, 19, 60, 50, 1019.9, 1018.7, 0, 1, 20.2, 23.7, 'No', 'No'), ('12/31/2015', 17.4, 26.7, 0.0, 8.0, 12.7, 'W', 41, 'WNW', 'E', 9, 24, 62, 52, 1019.4, 1016.8, 1, 5, 21.3, 24.2, 'No', 'No'), ('1/1/2016', 17.9, 25.6, 0.0, 11.0, 12.3, 'E', 35, 'SSW', 'E', 2, 28, 57, 52, 1016.4, 1013.7, 6, 4, 22.9, 24.2, 'No', 'No'), ('1/2/2016', 18.0, 25.4, 0.0, 6.8, 3.3, 'ESE', 28, 'W', 'ESE', 0, 19, 60, 51, 1013.4, 1012.3, 7, 7, 22.3, 23.5, 'No', 'No'), ('1/3/2016', 20.2, 24.6, 0.0, 8.0, 0.0, 'SE', 44, 'SSE', 'SE', 20, 22, 63, 84, 1015.2, 1014.7, 8, 8, 22.2, 19.9, 'No', 'Yes'), ('1/4/2016', 18.6, 23.6, 15.0, 6.4, 0.7, 'ESE', 46, 'ESE', 'ESE', 6, 7, 86, 89, 1016.8, 1016.3, 8, 8, 18.8, 19.1, 'Yes', 'Yes'), ('1/5/2016', 17.8, 20.3, 34.2, 0.0, 0.0, 'ESE', 54, 'SE', 'SE', 26, 26, 87, 87, 1016.5, 1014.6, 8, 8, 19.1, 19.5, 'Yes', 'Yes'), ('1/6/2016', 17.4, 18.6, 51.4, 8.0, 0.0, 'SE', 48, 'SE', 'SSE', 19, 20, 92, 91, 1012.3, 1011.6, 8, 8, 18.2, 17.9, 'Yes', 'Yes'), ('1/7/2016', 16.5, 24.4, 41.4, 2.0, 7.6, 'W', 41, 'SSW', 'SSW', 22, 24, 91, 66, 1014.0, 1015.8, 7, 7, 18.1, 21.0, 'Yes', 'No'), ('1/8/2016', 15.5, 25.4, 0.4, 6.6, 12.1, 'W', 41, 'NW', 'E', 4, 19, 58, 53, 1020.1, 1019.0, 5, 1, 20.6, 24.1, 'No', 'No'), ('1/9/2016', 18.5, 25.5, 0.0, 7.0, 8.6, 'ENE', 31, 'N', 'E', 2, 22, 71, 52, 1021.9, 1018.8, 5, 6, 21.2, 24.5, 'No', 'No'), ('1/10/2016', 18.5, 27.1, 0.0, 8.0, 12.2, 'ENE', 41, 'W', 'ENE', 9, 26, 67, 53, 1020.4, 1017.5, 3, 1, 22.9, 26.2, 'No', 'No'), ('1/11/2016', 20.5, 31.6, 0.0, 9.0, 12.1, 'E', 28, 'ESE', 'E', 7, 15, 69, 52, 1013.3, 1009.1, 1, 1, 24.5, 31.1, 'No', 'No'), ('1/12/2016', 23.5, 34.0, 0.0, 10.6, 4.4, 'S', 52, 'W', 'SSE', 2, 24, 56, 70, 1010.4, 1012.1, 6, 7, 26.5, 25.9, 'No', 'No'), ('1/13/2016', 21.3, 31.0, 0.0, 6.0, 11.0, 'NE', 37, 'NNE', 'E', 4, 28, 69, 59, 1019.7, 1016.2, 3, 1, 23.2, 26.7, 'No', 'No'), ('1/15/2016', 14.3, 21.7, 34.0, 12.2, 2.7, 'S', 54, 'W', 'S', 19, 22, 92, 71, 1024.4, 1024.0, 8, 7, 14.5, 19.4, 'Yes', 'Yes'), ('1/16/2016', 14.3, 23.8, 5.4, 6.0, 7.2, 'SE', 43, 'SSE', 'SSE', 20, 20, 66, 45, 1026.9, 1026.1, 7, 5, 19.7, 22.8, 'Yes', 'No'), ('1/17/2016', 16.0, 26.1, 0.0, 5.6, 11.8, 'SE', 33, 'SSE', 'ESE', 13, 22, 71, 49, 1025.1, 1022.6, 6, 4, 20.4, 25.1, 'No', 'No'), ('1/18/2016', 16.7, 27.0, 0.0, 7.0, 13.5, 'NNE', 35, 'WNW', 'E', 6, 20, 64, 55, 1020.6, 1017.7, 2, 2, 22.1, 25.1, 'No', 'No'), ('1/19/2016', 19.2, 30.2, 0.0, 8.0, 13.0, 'NNE', 41, 'N', 'ENE', 6, 13, 60, 54, 1017.4, 1013.3, 3, 3, 24.2, 29.2, 'No', 'No'), ('1/20/2016', 21.9, 37.5, 0.0, 11.8, 10.0, 'NNE', 39, 'ESE', 'E', 4, 9, 39, 39, 1012.6, 1009.8, 1, 6, 27.9, 32.1, 'No', 'No'), ('1/21/2016', 23.6, 33.5, 0.0, 11.6, 6.9, 'SW', 61, 'SW', 'ENE', 4, 20, 66, 48, 1010.5, 1007.4, 5, 4, 26.2, 32.3, 'No', 'Yes'), ('1/22/2016', 22.8, 29.2, 30.6, 10.4, 1.4, 'NE', 30, 'SSW', 'E', 7, 13, 85, 76, 1011.0, 1006.4, 7, 7, 24.9, 25.7, 'Yes', 'Yes'), ('1/23/2016', 22.3, 26.0, 13.0, 3.4, 9.5, 'W', 41, 'S', 'S', 17, 33, 60, 59, 1006.7, 1008.6, 3, 6, 25.6, 25.5, 'Yes', 'No'), ('1/24/2016', 20.8, 25.0, 0.0, 6.6, 0.6, 'SSE', 31, 'SSW', 'ESE', 11, 15, 73, 62, 1013.4, 1012.1, 8, 7, 21.9, 24.1, 'No', 'No'), ('1/25/2016', 21.6, 25.2, 0.0, 4.6, 0.0, 'W', 41, 'E', 'E', 13, 13, 73, 64, 1014.5, 1013.3, 8, 8, 23.2, 24.7, 'No', 'No'), ('1/26/2016', 21.6, 27.8, 0.0, 2.4, 8.7, 'W', 41, 'E', 'ENE', 11, 19, 73, 54, 1017.7, 1017.3, 8, 4, 22.9, 26.4, 'No', 'Yes'), ('1/27/2016', 20.8, 24.9, 2.2, 9.8, 0.5, 'NE', 48, 'NE', 'NE', 17, 15, 66, 63, 1016.2, 1014.0, 6, 8, 24.0, 24.3, 'Yes', 'No'), ('1/28/2016', 21.4, 27.6, 0.4, 5.6, 6.7, 'NNE', 39, 'N', 'ENE', 17, 15, 74, 64, 1008.2, 1004.7, 7, 7, 23.5, 27.2, 'No', 'No'), ('1/29/2016', 22.4, 28.1, 0.0, 5.0, 8.2, 'NW', 65, 'NNE', 'ESE', 11, 6, 72, 86, 1003.3, 1001.9, 3, 7, 26.3, 23.2, 'No', 'Yes'), ('1/30/2016', 19.5, 28.7, 9.0, 3.0, 3.0, 'ESE', 70, 'W', 'ESE', 17, 17, 84, 62, 1004.9, 1002.7, 8, 7, 22.4, 28.1, 'Yes', 'Yes'), ('1/31/2016', 19.7, 31.1, 12.8, 5.8, 10.0, 'WNW', 48, 'W', 'WNW', 15, 26, 83, 26, 1004.4, 1003.3, 1, 5, 22.6, 31.0, 'Yes', 'No'), ('2/1/2016', 21.8, 26.5, 0.2, 8.0, 7.4, 'SSE', 43, 'NNW', 'SE', 2, 15, 42, 52, 1004.2, 1001.1, 5, 4, 26.0, 25.5, 'No', 'Yes'), ('2/2/2016', 17.0, 27.9, 2.0, 5.0, 12.9, 'SE', 33, 'WNW', 'ESE', 17, 24, 62, 45, 1006.3, 1004.0, 2, 3, 20.9, 26.6, 'Yes', 'No'), ('2/3/2016', 19.3, 28.3, 0.0, 7.6, 10.7, 'SSE', 43, 'W', 'E', 4, 26, 67, 59, 1003.6, 1002.2, 5, 4, 23.4, 27.7, 'No', 'Yes'), ('2/4/2016', 19.1, 24.8, 10.8, 7.6, 0.8, 'S', 59, 'SSW', 'S', 24, 33, 87, 55, 1012.0, 1012.8, 8, 7, 19.7, 23.5, 'Yes', 'Yes'), ('2/5/2016', 19.6, 26.1, 3.6, 9.6, 6.8, 'SSE', 56, 'S', 'SSE', 31, 39, 59, 56, 1017.4, 1017.6, 6, 5, 22.0, 23.9, 'Yes', 'Yes'), ('2/6/2016', 19.9, 27.0, 1.8, 8.8, 8.1, 'SSE', 37, 'SE', 'ESE', 20, 20, 75, 49, 1018.0, 1016.9, 7, 3, 22.8, 26.4, 'Yes', 'No'), ('2/7/2016', 19.1, 27.4, 0.0, 7.2, 10.1, 'ESE', 30, 'WNW', 'ESE', 9, 17, 76, 54, 1018.0, 1016.6, 5, 3, 22.5, 25.7, 'No', 'No'), ('2/8/2016', 19.0, 28.0, 0.0, 4.6, 12.6, 'E', 24, 'WNW', 'ESE', 11, 17, 68, 54, 1019.1, 1017.9, 2, 1, 23.0, 27.0, 'No', 'No'), ('2/9/2016', 21.0, 27.7, 0.0, 9.8, 10.3, 'SSE', 39, 'SSE', 'SE', 26, 19, 70, 47, 1020.7, 1019.6, 6, 1, 25.0, 27.3, 'No', 'No'), ('2/10/2016', 19.6, 28.5, 0.2, 7.6, 12.7, 'NE', 43, 'W', 'ENE', 11, 22, 68, 46, 1016.7, 1012.9, 2, 1, 23.2, 27.6, 'No', 'No'), ('2/11/2016', 20.7, 28.4, 0.0, 10.4, 9.6, 'E', 26, 'WSW', 'E', 6, 20, 65, 58, 1015.8, 1014.2, 3, 7, 24.6, 26.7, 'No', 'No'), ('2/12/2016', 21.5, 28.8, 0.0, 6.4, 12.0, 'ENE', 33, 'W', 'E', 7, 22, 63, 58, 1017.0, 1015.1, 2, 1, 25.4, 27.5, 'No', 'No'), ('2/13/2016', 20.7, 28.9, 0.0, 8.8, 12.1, 'NNE', 46, 'N', 'NE', 9, 24, 60, 54, 1014.6, 1011.5, 1, 1, 25.3, 27.7, 'No', 'No'), ('2/14/2016', 21.1, 32.5, 0.0, 9.6, 10.4, 'SSE', 48, 'NE', 'SSE', 2, 4, 58, 53, 1008.4, 1005.3, 1, 5, 26.2, 31.5, 'No', 'No'), ('2/15/2016', 22.3, 29.3, 0.0, 8.0, 6.9, 'SW', 31, 'W', 'ESE', 15, 20, 75, 62, 1011.8, 1007.7, 7, 3, 24.1, 27.4, 'No', 'No'), ('2/16/2016', 21.5, 27.9, 0.0, 7.0, 10.8, 'SSE', 48, 'SSW', 'SE', 17, 31, 36, 51, 1009.1, 1008.8, 1, 2, 25.3, 25.6, 'No', 'No'), ('2/17/2016', 19.5, 26.0, 0.0, 8.8, 10.4, 'SSE', 39, 'SSW', 'ESE', 22, 22, 57, 34, 1011.4, 1008.4, 3, 1, 20.5, 25.5, 'No', 'No'), ('2/18/2016', 18.3, 26.4, 0.0, 8.0, 11.7, 'E', 30, 'SSW', 'ESE', 11, 19, 59, 47, 1009.8, 1008.7, 3, 1, 22.9, 26.1, 'No', 'No'), ('2/19/2016', 20.5, 29.4, 0.0, 8.0, 11.1, 'ENE', 35, 'NW', 'ENE', 9, 20, 70, 60, 1012.4, 1009.8, 4, 1, 23.7, 28.6, 'No', 'No'), ('2/20/2016', 23.1, 29.3, 0.0, 9.4, 5.9, 'S', 52, 'SSW', 'S', 24, 26, 75, 52, 1017.7, 1018.2, 7, 5, 24.6, 28.8, 'No', 'Yes'), ('2/21/2016', 21.4, 27.0, 6.0, 8.2, 4.8, 'E', 37, 'S', 'ESE', 9, 13, 89, 67, 1025.4, 1024.6, 6, 4, 21.9, 26.6, 'Yes', 'Yes'), ('2/22/2016', 20.8, 28.8, 1.2, 3.8, 11.6, 'ENE', 39, 'W', 'ENE', 11, 24, 71, 59, 1025.4, 1022.0, 1, 6, 24.3, 28.0, 'Yes', 'No'), ('2/23/2016', 21.8, 29.7, 0.0, 9.4, 12.4, 'NNE', 43, 'N', 'ENE', 9, 22, 62, 51, 1021.3, 1017.7, 1, 1, 25.4, 28.2, 'No', 'No'), ('2/24/2016', 20.9, 29.5, 0.0, 11.0, 12.3, 'NNE', 46, 'NNE', 'ENE', 11, 26, 60, 58, 1016.1, 1012.9, 0, 1, 26.1, 28.4, 'No', 'No'), ('2/25/2016', 21.9, 32.8, 0.0, 8.4, 12.2, 'NNE', 44, 'NE', 'E', 7, 17, 62, 45, 1012.4, 1009.3, 0, 0, 26.1, 32.2, 'No', 'No'), ('2/26/2016', 23.2, 27.8, 0.0, 12.2, 5.2, 'S', 63, 'SSW', 'SE', 28, 22, 67, 60, 1014.9, 1015.5, 1, 7, 25.4, 26.7, 'No', 'No'), ('2/27/2016', 22.5, 27.5, 0.0, 6.0, 10.0, 'ESE', 33, 'ESE', 'ESE', 17, 22, 60, 55, 1019.3, 1019.0, 7, 5, 26.0, 25.2, 'No', 'No'), ('2/28/2016', 20.7, 28.1, 0.0, 8.0, 10.1, 'E', 28, 'W', 'E', 11, 17, 62, 53, 1018.8, 1017.2, 1, 1, 23.7, 26.3, 'No', 'No'), ('2/29/2016', 20.5, 27.7, 0.0, 11.2, 5.7, 'ESE', 31, 'W', 'SE', 9, 20, 73, 60, 1021.2, 1020.4, 7, 5, 23.0, 27.5, 'No', 'No'), ('3/1/2016', 21.3, 28.2, 0.0, 4.2, 7.7, 'ENE', 33, 'E', 'ENE', 4, 26, 72, 47, 1022.0, 1019.9, 4, 1, 23.6, 27.6, 'No', 'No'), ('3/2/2016', 20.3, 28.8, 0.0, 7.8, 10.7, 'NNE', 50, 'NNE', 'ENE', 13, 30, 59, 52, 1021.1, 1018.9, 7, 7, 25.1, 28.1, 'No', 'No'), ('3/3/2016', 22.2, 28.7, 0.0, 8.2, 10.2, 'NE', 46, 'NNE', 'NE', 4, 26, 71, 58, 1021.3, 1019.4, 3, 4, 25.2, 28.4, 'No', 'No'), ('3/4/2016', 22.8, 28.3, 0.0, 9.6, 10.1, 'NE', 39, 'N', 'NE', 20, 24, 70, 53, 1022.0, 1020.1, 7, 2, 24.9, 26.9, 'No', 'No'), ('3/5/2016', 20.6, 27.6, 0.0, 9.2, 10.6, 'NE', 41, 'NNE', 'NE', 11, 24, 64, 55, 1021.7, 1019.4, 1, 1, 24.6, 27.2, 'No', 'No'), ('3/6/2016', 20.8, 27.9, 0.0, 9.8, 10.5, 'NE', 46, 'N', 'NE', 4, 20, 64, 59, 1022.9, 1021.2, 2, 1, 24.9, 26.3, 'No', 'No'), ('3/7/2016', 21.0, 28.3, 0.0, 8.0, 11.8, 'ENE', 44, 'E', 'NE', 7, 26, 71, 57, 1021.6, 1018.8, 2, 1, 24.5, 26.8, 'No', 'No'), ('3/8/2016', 22.4, 28.1, 0.0, 8.8, 10.8, 'ENE', 33, 'NE', 'ENE', 7, 20, 61, 57, 1023.4, 1022.6, 1, 3, 26.2, 27.0, 'No', 'No'), ('3/9/2016', 22.9, 29.3, 0.0, 9.2, 10.1, 'NNE', 43, 'N', 'NE', 13, 24, 71, 55, 1021.6, 1017.9, 4, 4, 24.8, 29.1, 'No', 'No'), ('3/10/2016', 22.0, 30.6, 0.0, 8.0, 6.5, 'SE', 31, 'SSE', 'SSE', 2, 24, 84, 59, 1019.7, 1018.9, 7, 7, 24.0, 28.5, 'No', 'No'), ('3/11/2016', 22.8, 27.8, 0.0, 5.8, 2.3, 'ENE', 37, 'ENE', 'ENE', 6, 19, 79, 66, 1020.1, 1017.9, 8, 7, 23.8, 26.8, 'No', 'No'), ('3/12/2016', 21.8, 28.7, 0.0, 4.6, 10.7, 'NE', 43, 'WNW', 'E', 9, 24, 73, 60, 1019.6, 1018.0, 1, 2, 24.6, 27.6, 'No', 'No'), ('3/13/2016', 22.6, 27.7, 0.0, 9.0, 7.7, 'ENE', 30, 'NE', 'ENE', 11, 20, 63, 63, 1020.5, 1017.9, 4, 7, 25.8, 26.2, 'No', 'No'), ('3/14/2016', 21.8, 30.7, 0.0, 7.2, 4.9, 'SSW', 41, 'WNW', 'SE', 9, 20, 84, 54, 1016.3, 1014.3, 7, 6, 22.9, 29.9, 'No', 'Yes'), ('3/15/2016', 19.9, 25.6, 16.8, 7.0, 4.5, 'SSW', 44, 'SW', 'S', 11, 26, 89, 66, 1019.5, 1018.6, 7, 6, 20.2, 24.3, 'Yes', 'Yes'), ('3/16/2016', 19.7, 26.2, 23.0, 6.0, 7.6, 'ESE', 39, 'S', 'SSW', 9, 20, 88, 58, 1019.7, 1018.0, 8, 4, 20.7, 25.4, 'Yes', 'Yes'), ('3/17/2016', 19.0, 26.1, 13.6, 5.2, 7.5, 'W', 41, 'NW', 'E', 4, 15, 92, 59, 1017.0, 1012.9, 7, 4, 19.6, 25.5, 'Yes', 'Yes'), ('3/18/2016', 19.6, 28.2, 3.4, 5.6, 4.4, 'SSW', 52, 'NNE', 'NNE', 11, 13, 71, 67, 1003.6, 997.6, 7, 7, 23.4, 26.4, 'Yes', 'Yes'), ('3/19/2016', 16.2, 24.4, 4.8, 5.4, 11.0, 'W', 44, 'WSW', 'SE', 20, 22, 43, 36, 1010.9, 1011.2, 1, 1, 18.4, 23.8, 'Yes', 'No'), ('3/20/2016', 17.4, 22.0, 0.2, 7.8, 3.4, 'S', 52, 'SSW', 'S', 15, 20, 63, 81, 1017.5, 1016.8, 7, 8, 18.6, 18.1, 'No', 'Yes'), ('3/21/2016', 15.4, 21.2, 61.2, 5.8, 2.7, 'S', 43, 'WSW', 'SSW', 19, 24, 91, 65, 1018.8, 1016.5, 8, 7, 15.6, 20.7, 'Yes', 'Yes'), ('3/22/2016', 14.3, 23.8, 25.4, 2.8, 6.9, 'S', 50, 'W', 'S', 20, 19, 74, 63, 1017.5, 1015.5, 3, 7, 17.1, 21.5, 'Yes', 'Yes'), ('3/23/2016', 14.9, 25.3, 1.6, 4.2, 9.5, 'W', 33, 'W', 'ESE', 20, 15, 66, 51, 1018.2, 1016.9, 1, 3, 18.3, 23.9, 'Yes', 'No'), ('3/24/2016', 16.5, 27.4, 0.0, 5.2, 9.3, 'ENE', 31, 'W', 'E', 11, 24, 73, 51, 1020.7, 1019.0, 6, 3, 19.4, 25.8, 'No', 'No'), ('3/25/2016', 19.3, 25.2, 0.0, 6.8, 0.3, 'S', 24, 'WNW', 'WNW', 11, 9, 78, 62, 1018.9, 1016.3, 7, 7, 20.4, 22.9, 'No', 'No'), ('3/26/2016', 17.1, 26.0, 0.0, 3.0, 10.2, 'ENE', 28, 'WNW', 'ENE', 17, 17, 71, 59, 1018.6, 1016.0, 2, 2, 20.0, 24.5, 'No', 'No'), ('3/27/2016', 19.3, 24.2, 0.2, 4.0, 5.7, 'ESE', 41, 'S', 'E', 9, 20, 83, 63, 1018.2, 1017.0, 5, 6, 22.2, 23.0, 'No', 'Yes'), ('3/28/2016', 19.4, 26.0, 34.8, 5.8, 4.1, 'SSW', 26, 'S', 'ESE', 15, 20, 88, 64, 1018.7, 1015.7, 6, 6, 20.6, 26.0, 'Yes', 'No'), ('3/29/2016', 20.6, 23.3, 0.0, 4.0, 0.0, 'SSW', 37, 'SSW', 'SSW', 13, 19, 84, 84, 1017.5, 1016.0, 7, 8, 21.2, 21.1, 'No', 'Yes'), ('3/30/2016', 19.0, 28.7, 7.0, 1.4, 7.5, 'WNW', 30, 'W', 'NW', 17, 7, 81, 31, 1015.0, 1012.0, 1, 6, 20.5, 26.8, 'Yes', 'Yes'), ('3/31/2016', 16.5, 25.6, 1.2, 6.8, 10.6, 'SSE', 39, 'W', 'SSE', 20, 20, 51, 42, 1017.1, 1016.2, 1, 2, 19.9, 24.7, 'Yes', 'No'), ('4/1/2016', 16.6, 25.6, 0.0, 5.4, 10.2, 'NE', 37, 'W', 'ENE', 15, 28, 69, 58, 1019.1, 1015.1, 3, 1, 20.2, 24.9, 'No', 'No'), ('4/2/2016', 18.3, 31.2, 0.0, 6.8, 10.3, 'SSE', 35, 'W', 'SW', 19, 9, 63, 19, 1016.4, 1014.6, 7, 3, 19.9, 29.7, 'No', 'No'), ('4/3/2016', 19.5, 25.2, 0.0, 6.8, 6.7, 'SSE', 35, 'SSW', 'ESE', 17, 19, 74, 64, 1024.6, 1022.1, 6, 2, 21.2, 23.3, 'No', 'Yes'), ('4/4/2016', 18.7, 23.5, 94.4, 3.4, 0.8, 'ENE', 33, 'SE', 'ESE', 6, 17, 91, 71, 1023.2, 1019.6, 8, 7, 19.5, 23.3, 'Yes', 'Yes'), ('4/5/2016', 18.6, 26.2, 6.4, 3.0, 10.4, 'W', 41, 'NNE', 'NNE', 9, 24, 64, 58, 1020.1, 1015.2, 1, 3, 23.5, 25.6, 'Yes', 'No'), ('4/6/2016', 19.9, 34.2, 0.0, 6.8, 10.6, 'NE', 43, 'ESE', 'NNE', 7, 26, 54, 46, 1015.9, 1011.6, 1, 1, 25.0, 29.3, 'No', 'No'), ('4/7/2016', 19.9, 20.5, 0.2, 8.4, 0.0, 'SSE', 43, 'SSE', 'SSE', 26, 19, 59, 54, 1023.2, 1022.3, 8, 7, 20.1, 19.9, 'No', 'No'), ('4/8/2016', 17.7, 20.6, 0.0, 4.0, 0.0, 'ENE', 31, 'W', 'E', 13, 2, 71, 70, 1023.5, 1021.2, 8, 8, 18.8, 20.5, 'No', 'No'), ('4/9/2016', 16.0, 25.0, 0.4, 1.2, 9.5, 'ESE', 26, 'WNW', 'SE', 17, 15, 65, 57, 1022.0, 1018.8, 2, 7, 19.3, 24.0, 'No', 'No'), ('4/10/2016', 16.1, 27.3, 0.0, 3.8, 9.6, 'W', 41, 'WNW', 'E', 19, 19, 70, 51, 1019.8, 1015.5, 5, 3, 19.3, 23.7, 'No', 'No'), ('4/11/2016', 16.1, 26.5, 0.0, 6.4, 9.4, 'WSW', 31, 'WNW', 'SE', 15, 19, 51, 46, 1017.5, 1016.4, 3, 6, 19.6, 24.1, 'No', 'Yes'), ('4/12/2016', 17.4, 22.9, 8.2, 5.6, 5.7, 'S', 35, 'SE', 'SSE', 7, 22, 85, 68, 1023.1, 1021.8, 7, 5, 18.3, 20.5, 'Yes', 'No'), ('4/13/2016', 15.5, 24.2, 0.6, 4.2, 8.3, 'ESE', 28, 'WNW', 'ESE', 11, 19, 72, 57, 1027.4, 1026.3, 6, 2, 19.7, 22.5, 'No', 'No'), ('4/14/2016', 15.7, 22.9, 0.6, 3.4, 2.4, 'ENE', 33, 'S', 'NE', 6, 15, 88, 62, 1030.2, 1027.5, 7, 7, 18.6, 22.3, 'No', 'No'), ('4/15/2016', 16.5, 24.6, 1.0, 3.4, 9.9, 'NE', 33, 'W', 'NE', 2, 19, 66, 51, 1026.4, 1021.8, 6, 5, 21.3, 24.2, 'No', 'No'), ('4/16/2016', 16.6, 25.5, 0.0, 5.0, 9.3, 'SSE', 28, 'W', 'ENE', 7, 11, 69, 49, 1021.2, 1017.8, 6, 7, 19.8, 24.7, 'No', 'No'), ('4/17/2016', 19.1, 23.2, 0.0, 4.6, 3.2, 'SSW', 43, 'SSW', 'SSE', 15, 17, 73, 77, 1022.1, 1020.4, 7, 7, 20.1, 20.5, 'No', 'Yes'), ('4/18/2016', 15.1, 24.2, 2.0, 3.0, 7.6, 'SSE', 37, 'W', 'SSE', 17, 17, 75, 68, 1021.8, 1019.2, 6, 7, 18.9, 21.2, 'Yes', 'Yes'), ('4/19/2016', 16.9, 23.9, 15.0, 5.0, 6.9, 'W', 24, 'W', 'ESE', 13, 17, 83, 68, 1021.7, 1020.1, 3, 7, 19.5, 22.2, 'Yes', 'Yes'), ('4/20/2016', 16.7, 25.5, 15.8, 3.4, 10.3, 'E', 22, 'W', 'E', 15, 13, 82, 66, 1024.6, 1022.0, 3, 2, 19.3, 23.2, 'Yes', 'No'), ('4/21/2016', 17.3, 24.5, 0.0, 3.4, 10.5, 'ENE', 30, 'W', 'NE', 9, 13, 79, 69, 1023.1, 1019.1, 2, 5, 20.2, 24.1, 'No', 'No'), ('4/22/2016', 17.1, 25.9, 0.0, 4.0, 7.1, 'SSW', 44, 'WNW', 'S', 13, 24, 70, 69, 1020.1, 1019.1, 1, 7, 20.2, 21.8, 'No', 'Yes'), ('4/23/2016', 16.2, 20.2, 6.6, 3.4, 1.3, 'SSW', 52, 'SSW', 'SSW', 22, 17, 83, 85, 1024.2, 1024.5, 7, 6, 16.8, 16.5, 'Yes', 'Yes'), ('4/24/2016', 15.3, 23.1, 3.8, 2.6, 9.9, 'SSE', 43, 'ESE', 'ESE', 22, 20, 61, 49, 1029.8, 1029.3, 5, 3, 20.1, 21.5, 'Yes', 'No'), ('4/25/2016', 13.1, 22.8, 0.0, 4.8, 10.4, 'W', 20, 'WNW', 'ESE', 13, 15, 76, 53, 1032.0, 1029.4, 1, 1, 16.3, 21.7, 'No', 'No'), ('4/26/2016', 14.2, 23.7, 0.0, 2.8, 9.6, 'W', 22, 'WNW', 'E', 13, 13, 75, 56, 1030.9, 1027.6, 3, 3, 17.2, 22.2, 'No', 'No'), ('4/27/2016', 15.3, 23.7, 0.0, 2.8, 10.7, 'NE', 35, 'WNW', 'NE', 15, 19, 78, 54, 1028.1, 1023.7, 1, 2, 17.8, 23.0, 'No', 'No'), ('4/28/2016', 15.7, 25.1, 0.0, 5.2, 7.7, 'E', 24, 'W', 'E', 11, 20, 84, 61, 1024.9, 1021.5, 7, 1, 18.4, 23.7, 'No', 'No'), ('4/29/2016', 16.0, 24.2, 0.0, 4.8, 4.6, 'NE', 26, 'W', 'NE', 13, 11, 75, 65, 1022.8, 1018.5, 4, 8, 18.8, 23.3, 'No', 'No'), ('4/30/2016', 18.8, 26.5, 0.0, 3.4, 4.5, 'N', 33, 'NE', 'WNW', 4, 9, 74, 54, 1018.7, 1015.6, 8, 6, 20.5, 26.0, 'No', 'Yes'), ('5/1/2016', 18.1, 26.1, 2.8, 3.4, 4.7, 'NNW', 44, 'N', 'N', 19, 20, 86, 55, 1013.6, 1009.6, 7, 5, 19.4, 25.4, 'Yes', 'No'), ('5/2/2016', 13.9, 21.3, 0.0, 4.8, 6.1, 'W', 41, 'NW', 'NE', 7, 9, 56, 60, 1017.3, 1012.2, 0, 7, 16.3, 21.2, 'No', 'No'), ('5/3/2016', 12.8, 26.4, 0.0, 3.4, 10.4, 'NW', 33, 'W', 'WNW', 11, 20, 61, 27, 1012.6, 1006.4, 1, 0, 16.0, 25.8, 'No', 'No'), ('5/4/2016', 16.0, 26.2, 0.0, 8.0, 10.2, 'NNW', 26, 'W', 'E', 17, 15, 49, 41, 1015.2, 1014.2, 1, 2, 19.1, 23.1, 'No', 'No'), ('5/5/2016', 13.5, 22.4, 0.0, 4.0, 10.1, 'W', 28, 'WNW', 'E', 13, 20, 55, 54, 1020.7, 1016.9, 1, 1, 16.2, 21.3, 'No', 'No'), ('5/6/2016', 14.0, 26.7, 0.0, 3.4, 9.9, 'W', 41, 'W', 'ESE', 19, 13, 69, 42, 1019.6, 1017.2, 4, 1, 16.4, 23.2, 'No', 'No'), ('5/7/2016', 12.4, 22.9, 0.0, 5.6, 8.7, 'W', 24, 'W', 'ENE', 13, 13, 75, 60, 1021.3, 1018.4, 0, 6, 15.4, 21.6, 'No', 'No'), ('5/8/2016', 15.3, 20.8, 0.0, 1.4, 0.0, 'WNW', 22, 'W', 'E', 11, 9, 86, 74, 1018.5, 1013.8, 7, 7, 18.2, 20.5, 'No', 'Yes'), ('5/9/2016', 18.0, 22.2, 1.6, 1.0, 0.0, 'NW', 43, 'NNE', 'NNE', 11, 17, 76, 72, 1008.8, 1003.7, 7, 7, 20.1, 21.8, 'Yes', 'No'), ('5/10/2016', 17.3, 24.6, 0.0, 4.4, 9.7, 'NW', 72, 'NW', 'WNW', 20, 35, 51, 35, 1006.5, 1004.3, 1, 1, 19.8, 23.8, 'No', 'No'), ('5/11/2016', 12.6, 23.1, 0.0, 8.0, 7.5, 'W', 43, 'WSW', 'WSW', 9, 17, 51, 21, 1015.5, 1012.2, 1, 6, 15.3, 21.3, 'No', 'No'), ('5/12/2016', 13.7, 24.5, 0.0, 6.0, 9.1, 'W', 46, 'NNW', 'WNW', 15, 22, 52, 35, 1014.7, 1013.9, 2, 6, 17.5, 23.3, 'No', 'No'), ('5/13/2016', 13.9, 25.9, 0.0, 4.0, 10.0, 'WSW', 30, 'WNW', 'WNW', 13, 11, 60, 32, 1021.8, 1019.6, 1, 1, 17.3, 25.6, 'No', 'No'), ('5/14/2016', 12.4, 26.6, 0.0, 7.2, 10.2, 'W', 28, 'WNW', 'ENE', 19, 15, 62, 50, 1023.7, 1019.9, 0, 0, 14.7, 22.3, 'No', 'No'), ('5/15/2016', 13.2, 24.4, 0.0, 2.2, 5.2, 'W', 30, 'W', 'N', 20, 9, 42, 41, 1017.4, 1013.7, 6, 5, 17.8, 22.4, 'No', 'No'), ('5/16/2016', 13.6, 22.9, 0.0, 3.2, 9.1, 'ENE', 28, 'W', 'NE', 17, 15, 66, 59, 1021.4, 1017.7, 1, 1, 16.4, 22.4, 'No', 'No'), ('5/17/2016', 16.3, 28.2, 0.0, 4.8, 8.9, 'WSW', 31, 'WNW', 'WNW', 7, 15, 55, 26, 1017.0, 1014.3, 2, 1, 18.3, 27.7, 'No', 'No'), ('5/18/2016', 12.7, 21.9, 0.0, 6.6, 3.0, 'WSW', 39, 'W', 'N', 17, 11, 49, 34, 1018.8, 1015.2, 7, 7, 14.6, 21.4, 'No', 'No'), ('5/19/2016', 11.9, 23.2, 0.0, 4.0, 9.9, 'W', 37, 'WNW', 'WNW', 9, 17, 54, 29, 1017.9, 1013.4, 0, 1, 14.5, 23.0, 'No', 'No'), ('5/20/2016', 12.8, 24.9, 0.0, 4.0, 9.2, 'W', 41, 'WSW', 'SE', 19, 17, 53, 51, 1020.3, 1019.3, 0, 1, 17.3, 22.2, 'No', 'No'), ('5/21/2016', 13.6, 21.5, 0.0, 3.4, 4.4, 'W', 24, 'W', 'E', 13, 9, 72, 56, 1027.3, 1024.0, 6, 7, 15.5, 20.8, 'No', 'No'), ('5/22/2016', 14.5, 22.0, 0.0, 2.0, 9.1, 'NNE', 24, 'W', 'E', 13, 9, 82, 66, 1024.4, 1020.2, 1, 4, 16.0, 21.8, 'No', 'No'), ('5/23/2016', 15.2, 26.8, 0.0, 4.0, 9.2, 'WSW', 61, 'NW', 'SSW', 9, 22, 53, 32, 1013.9, 1012.4, 3, 1, 21.5, 23.8, 'No', 'No'), ('5/24/2016', 12.1, 22.3, 0.0, 7.6, 9.9, 'W', 44, 'W', 'WSW', 17, 19, 50, 21, 1018.1, 1013.6, 1, 2, 14.1, 20.8, 'No', 'No'), ('5/25/2016', 10.4, 21.2, 0.0, 3.2, 8.7, 'W', 33, 'W', 'E', 22, 6, 54, 29, 1017.8, 1013.5, 4, 7, 12.9, 20.8, 'No', 'No'), ('5/26/2016', 12.9, 20.2, 0.2, 4.6, 4.8, 'NW', 48, 'NNW', 'NW', 22, 24, 52, 48, 1006.9, 1000.4, 7, 2, 15.0, 19.9, 'No', 'No'), ('5/27/2016', 12.8, 18.6, 0.2, 4.0, 9.9, 'W', 61, 'W', 'W', 17, 37, 42, 27, 1003.5, 1001.7, 1, 1, 14.0, 17.9, 'No', 'No'), ('5/28/2016', 9.8, 14.8, 0.0, 5.6, 2.1, 'W', 39, 'NNW', 'W', 9, 13, 63, 70, 1007.2, 1006.0, 6, 6, 12.9, 14.3, 'No', 'Yes'), ('5/29/2016', 9.2, 19.3, 2.2, 1.6, 9.8, 'W', 37, 'W', 'W', 17, 15, 59, 29, 1017.2, 1016.5, 1, 1, 11.0, 18.7, 'Yes', 'No'), ('5/30/2016', 7.3, 19.9, 0.2, 2.6, 9.5, 'W', 39, 'W', 'WSW', 24, 9, 62, 30, 1025.5, 1024.1, 1, 1, 9.5, 19.1, 'No', 'No'), ('5/31/2016', 8.7, 17.5, 0.0, 2.2, 1.7, 'SE', 35, 'W', 'SE', 17, 6, 76, 87, 1029.6, 1027.2, 7, 7, 11.0, 15.8, 'No', 'Yes'), ('6/1/2016', 10.9, 17.9, 29.4, 0.6, 1.4, 'W', 24, 'W', 'ENE', 15, 7, 89, 74, 1029.1, 1026.6, 7, 7, 13.1, 16.0, 'Yes', 'No'), ('6/2/2016', 11.1, 19.1, 1.0, 2.4, 8.7, 'W', 41, 'W', 'SSE', 19, 15, 85, 60, 1027.0, 1024.3, 2, 7, 12.3, 18.6, 'No', 'No'), ('6/3/2016', 11.7, 18.3, 0.2, 2.4, 1.3, 'WSW', 28, 'WNW', 'S', 11, 11, 78, 73, 1025.4, 1021.6, 7, 7, 13.3, 18.3, 'No', 'Yes'), ('6/4/2016', 13.3, 21.1, 64.4, 4.8, 0.0, 'ENE', 89, 'NNE', 'NE', 13, 30, 91, 82, 1015.4, 1009.5, 8, 8, 17.0, 18.8, 'Yes', 'Yes'), ('6/5/2016', 16.3, 19.7, 93.8, 4.8, 0.0, 'ENE', 96, 'NE', 'ENE', 31, 57, 89, 85, 1002.5, 995.9, 8, 8, 18.8, 19.7, 'Yes', 'Yes'), ('6/6/2016', 13.7, 18.4, 68.4, 12.6, 2.2, 'W', 59, 'W', 'WSW', 28, 28, 59, 43, 999.8, 998.4, 7, 7, 14.9, 17.9, 'Yes', 'No'), ('6/7/2016', 11.3, 19.9, 0.0, 5.2, 3.6, 'WNW', 44, 'NNW', 'WNW', 20, 20, 59, 40, 1004.1, 1002.7, 4, 7, 13.8, 17.9, 'No', 'No'), ('6/8/2016', 10.9, 20.7, 0.0, 1.8, 9.3, 'WNW', 31, 'WNW', 'WNW', 15, 15, 65, 40, 1011.4, 1009.2, 1, 1, 13.8, 20.2, 'No', 'No'), ('6/9/2016', 13.8, 22.0, 0.2, 4.8, 6.0, 'NW', 59, 'NNW', 'WNW', 31, 17, 62, 32, 1006.8, 1005.9, 7, 1, 17.4, 21.6, 'No', 'No'), ('6/10/2016', 13.1, 21.4, 0.2, 6.2, 9.1, 'W', 35, 'WNW', 'WNW', 15, 7, 64, 41, 1017.4, 1016.8, 1, 1, 15.3, 20.8, 'No', 'No'), ('6/11/2016', 10.1, 19.8, 0.0, 3.2, 8.7, 'WSW', 54, 'W', 'W', 24, 19, 53, 34, 1022.5, 1020.7, 1, 5, 13.4, 19.3, 'No', 'No'), ('6/12/2016', 7.9, 18.1, 0.0, 5.4, 8.3, 'SW', 33, 'W', 'S', 22, 7, 62, 34, 1036.2, 1034.9, 4, 1, 9.4, 17.6, 'No', 'No'), ('6/13/2016', 8.5, 20.3, 0.0, 1.0, 6.5, 'W', 30, 'W', 'E', 20, 9, 65, 51, 1039.0, 1035.5, 5, 1, 10.3, 17.7, 'No', 'No'), ('6/14/2016', 9.9, 21.2, 0.0, 2.2, 9.6, 'W', 41, 'W', 'WNW', 15, 6, 80, 42, 1035.8, 1031.6, 1, 4, 11.6, 20.9, 'No', 'No'), ('6/15/2016', 9.1, 20.5, 0.0, 3.4, 8.2, 'WNW', 26, 'WNW', 'E', 17, 9, 72, 45, 1033.4, 1029.8, 5, 3, 10.6, 19.2, 'No', 'No'), ('6/16/2016', 10.2, 22.2, 0.0, 2.2, 9.6, 'NNW', 30, 'W', 'N', 13, 11, 81, 42, 1025.5, 1019.3, 1, 1, 12.9, 21.2, 'No', 'No'), ('6/17/2016', 12.7, 19.3, 0.0, 3.6, 1.4, 'NNW', 30, 'NNW', 'N', 20, 17, 53, 60, 1017.7, 1014.6, 6, 7, 17.4, 18.7, 'No', 'Yes'), ('6/18/2016', 14.7, 21.1, 5.0, 3.6, 3.4, 'SSW', 31, 'E', 'ESE', 6, 4, 90, 64, 1017.4, 1015.4, 7, 6, 15.4, 20.7, 'Yes', 'No'), ('6/19/2016', 14.5, 19.5, 0.4, 0.8, 0.0, 'NNE', 52, 'W', 'ESE', 13, 20, 81, 89, 1017.2, 1010.4, 7, 8, 15.2, 16.7, 'No', 'Yes'), ('6/20/2016', 15.0, 20.4, 38.8, 2.2, 3.5, 'NNW', 52, 'NNW', 'NW', 9, 22, 76, 52, 999.5, 994.2, 6, 6, 16.2, 17.9, 'Yes', 'No'), ('6/21/2016', 14.9, 18.4, 0.0, 6.0, 5.5, 'NW', 59, 'NW', 'WNW', 22, 28, 56, 38, 1003.3, 1002.0, 7, 4, 15.8, 17.8, 'No', 'No'), ('6/22/2016', 12.8, 19.7, 0.0, 4.4, 9.0, 'W', 50, 'NW', 'W', 17, 28, 60, 34, 1004.8, 1005.0, 2, 1, 15.0, 19.3, 'No', 'No'), ('6/23/2016', 9.4, 18.5, 0.0, 5.0, 8.2, 'NNW', 35, 'NNW', 'NNW', 7, 24, 58, 43, 1012.6, 1007.4, 7, 4, 12.8, 17.4, 'No', 'No'), ('6/24/2016', 12.7, 16.3, 0.0, 3.8, 6.5, 'W', 69, 'WNW', 'W', 13, 43, 52, 33, 1003.8, 1003.2, 5, 3, 15.8, 14.4, 'No', 'No'), ('6/25/2016', 7.3, 15.1, 0.6, 5.4, 9.6, 'W', 54, 'W', 'S', 28, 17, 49, 31, 1018.1, 1018.1, 1, 1, 8.4, 14.3, 'No', 'No'), ('6/26/2016', 5.6, 15.3, 0.0, 3.6, 5.2, 'W', 39, 'W', 'W', 20, 7, 61, 45, 1021.1, 1017.0, 6, 7, 7.4, 13.7, 'No', 'No'), ('6/27/2016', 7.4, 11.7, 0.0, 2.2, 0.0, 'W', 46, 'W', 'SW', 26, 9, 74, 74, 1015.3, 1013.6, 8, 8, 9.3, 11.0, 'No', 'Yes'), ('6/28/2016', 7.7, 17.3, 2.4, 1.4, 8.9, 'WSW', 46, 'W', 'SSW', 31, 13, 57, 36, 1022.9, 1023.1, 1, 1, 9.6, 16.9, 'Yes', 'No'), ('6/29/2016', 6.7, 18.8, 0.2, 4.0, 9.6, 'W', 31, 'W', 'N', 22, 4, 66, 33, 1028.4, 1025.4, 1, 1, 8.8, 18.6, 'No', 'No'), ('7/2/2016', 8.2, 18.2, 0.0, 2.8, 9.5, 'W', 37, 'W', 'W', 24, 17, 62, 36, 1025.5, 1023.2, 1, 1, 10.1, 17.8, 'No', 'No'), ('7/3/2016', 6.5, 18.1, 0.0, 3.6, 9.5, 'W', 24, 'W', 'ENE', 17, 13, 72, 42, 1026.6, 1022.6, 1, 0, 9.2, 16.5, 'No', 'No'), ('7/4/2016', 6.4, 15.6, 0.0, 3.4, 7.5, 'W', 22, 'WNW', 'SE', 13, 6, 77, 58, 1020.8, 1016.2, 5, 7, 7.6, 14.4, 'No', 'Yes'), ('7/5/2016', 7.5, 18.8, 4.8, 0.6, 5.8, 'NW', 46, 'W', 'NW', 11, 17, 90, 55, 1011.9, 1006.1, 8, 2, 9.6, 17.7, 'Yes', 'No'), ('7/6/2016', 9.5, 17.7, 0.2, 4.4, 4.8, 'W', 61, 'WNW', 'WSW', 22, 31, 54, 47, 1004.0, 1003.0, 6, 6, 12.9, 15.9, 'No', 'Yes'), ('7/7/2016', 12.9, 17.2, 29.4, 6.4, 1.6, 'S', 50, 'S', 'WSW', 19, 22, 85, 86, 1015.4, 1016.5, 7, 7, 14.9, 14.6, 'Yes', 'Yes'), ('7/8/2016', 12.4, 15.6, 22.4, 4.8, 0.0, 'W', 28, 'W', 'SSW', 17, 7, 92, 80, 1019.8, 1018.4, 8, 8, 12.7, 15.5, 'Yes', 'Yes'), ('7/9/2016', 8.7, 18.0, 2.2, 0.6, 5.2, 'SW', 30, 'WNW', 'S', 20, 13, 88, 64, 1023.5, 1022.4, 3, 5, 10.5, 16.4, 'Yes', 'No'), ('7/10/2016', 10.5, 17.9, 1.0, 1.8, 7.3, 'W', 30, 'WNW', 'E', 13, 15, 90, 69, 1025.1, 1021.3, 3, 3, 11.9, 16.7, 'No', 'No'), ('7/11/2016', 11.8, 18.6, 0.0, 3.2, 0.3, 'NW', 69, 'N', 'N', 20, 39, 63, 54, 1015.2, 1009.7, 7, 7, 15.5, 18.3, 'No', 'No'), ('7/12/2016', 14.8, 20.2, 0.2, 1.2, 7.8, 'NW', 54, 'WNW', 'NW', 15, 33, 41, 26, 1010.3, 1007.1, 6, 7, 16.6, 18.7, 'No', 'No'), ('7/13/2016', 9.6, 14.0, 0.0, 8.0, 9.8, 'W', 72, 'WNW', 'WSW', 37, 37, 40, 26, 1017.3, 1019.8, 3, 7, 10.5, 13.3, 'No', 'No'), ('7/14/2016', 6.7, 17.0, 0.0, 5.2, 9.6, 'WSW', 50, 'W', 'W', 30, 20, 54, 27, 1029.4, 1025.9, 7, 2, 8.6, 16.4, 'No', 'No'), ('7/15/2016', 6.4, 17.7, 0.0, 3.0, 9.5, 'W', 31, 'W', 'E', 22, 4, 60, 35, 1030.3, 1027.3, 1, 2, 8.8, 16.9, 'No', 'No'), ('7/16/2016', 6.9, 18.9, 0.0, 1.8, 4.7, 'W', 28, 'W', 'SSE', 19, 15, 71, 65, 1033.3, 1030.2, 2, 7, 9.3, 17.1, 'No', 'No'), ('7/17/2016', 9.2, 18.8, 0.8, 1.8, 3.2, 'WNW', 24, 'W', 'ESE', 13, 2, 91, 73, 1031.2, 1027.1, 7, 7, 13.3, 17.8, 'No', 'No'), ('7/18/2016', 11.0, 24.2, 0.0, 1.2, 8.9, 'WNW', 30, 'W', 'WNW', 9, 15, 92, 45, 1024.6, 1019.8, 1, 0, 11.5, 23.9, 'No', 'No'), ('7/19/2016', 11.4, 24.9, 0.2, 3.2, 6.2, 'NW', 20, 'W', 'NE', 0, 6, 71, 58, 1021.7, 1019.1, 7, 5, 18.0, 23.0, 'No', 'Yes'), ('7/20/2016', 16.5, 16.9, 17.0, 2.4, 0.0, 'SW', 35, 'S', 'WSW', 9, 13, 91, 90, 1019.7, 1018.4, 8, 8, 16.7, 16.2, 'Yes', 'Yes'), ('7/21/2016', 13.9, 19.3, 20.4, 1.8, 2.6, 'W', 31, 'W', 'NW', 15, 2, 92, 79, 1019.9, 1016.1, 7, 5, 14.6, 17.6, 'Yes', 'No'), ('7/22/2016', 13.1, 25.7, 0.0, 0.2, 7.4, 'NNW', 52, 'NNW', 'NW', 30, 30, 66, 44, 1009.1, 1001.0, 6, 4, 19.3, 25.1, 'No', 'Yes'), ('7/23/2016', 14.5, 17.4, 6.0, 7.6, 10.0, 'WNW', 69, 'WNW', 'W', 44, 43, 35, 31, 1004.3, 1003.8, 1, 1, 14.5, 17.0, 'Yes', 'No'), ('7/24/2016', 7.8, 14.3, 0.0, 4.0, 5.4, 'WSW', 46, 'W', 'NW', 22, 15, 50, 39, 1015.8, 1012.1, 7, 2, 8.7, 13.6, 'No', 'No'), ('7/25/2016', 8.4, 17.9, 0.0, 4.0, 9.9, 'W', 44, 'NNW', 'WNW', 19, 24, 50, 31, 1012.7, 1011.3, 1, 1, 12.2, 17.1, 'No', 'No'), ('7/26/2016', 10.2, 17.9, 0.0, 4.8, 9.9, 'WNW', 39, 'N', 'E', 6, 9, 52, 47, 1014.7, 1012.8, 1, 1, 14.0, 17.7, 'No', 'No'), ('7/27/2016', 10.8, 18.6, 0.0, 5.4, 10.1, 'W', 63, 'NW', 'WSW', 19, 26, 53, 32, 1012.2, 1013.3, 2, 3, 14.7, 18.5, 'No', 'No'), ('7/28/2016', 8.8, 19.4, 0.0, 4.0, 10.1, 'WSW', 48, 'W', 'WNW', 19, 11, 57, 34, 1024.3, 1020.5, 1, 0, 11.1, 19.0, 'No', 'No'), ('7/29/2016', 7.3, 18.5, 0.0, 4.0, 10.1, 'WSW', 50, 'W', 'WNW', 24, 11, 61, 34, 1023.0, 1018.0, 1, 2, 9.8, 17.6, 'No', 'No'), ('7/30/2016', 8.7, 19.8, 0.0, 4.2, 10.0, 'W', 33, 'W', 'ESE', 26, 9, 63, 50, 1023.3, 1020.2, 1, 3, 10.4, 17.9, 'No', 'No'), ('7/31/2016', 10.4, 20.9, 0.0, 2.8, 3.2, 'W', 24, 'W', 'WNW', 15, 7, 75, 37, 1018.0, 1015.3, 7, 2, 11.9, 20.5, 'No', 'No'), ('8/1/2016', 10.9, 18.4, 0.0, 2.2, 0.7, 'W', 22, 'WNW', 'W', 6, 6, 66, 54, 1017.2, 1013.0, 6, 8, 13.3, 17.0, 'No', 'No'), ('8/2/2016', 11.5, 15.8, 0.4, 1.0, 0.9, 'SE', 54, 'W', 'S', 15, 24, 76, 77, 1013.7, 1013.9, 7, 8, 12.8, 13.2, 'No', 'Yes'), ('8/3/2016', 10.7, 14.6, 24.8, 2.6, 0.2, 'S', 63, 'SE', 'SSE', 31, 24, 77, 89, 1018.0, 1017.7, 8, 8, 13.6, 12.6, 'Yes', 'Yes'), ('8/5/2016', 9.7, 16.2, 4.0, 3.2, 2.7, 'SW', 35, 'W', 'SSW', 20, 17, 90, 67, 1030.4, 1028.3, 6, 6, 11.2, 14.7, 'Yes', 'Yes'), ('8/6/2016', 9.2, 15.5, 1.8, 2.6, 2.2, 'SSE', 31, 'W', 'SE', 17, 7, 78, 71, 1029.0, 1026.8, 7, 7, 10.8, 14.7, 'Yes', 'No'), ('8/7/2016', 10.3, 16.4, 0.6, 0.6, 2.6, 'W', 33, 'W', 'ESE', 15, 7, 80, 64, 1027.4, 1024.7, 7, 6, 12.4, 15.9, 'No', 'No'), ('8/8/2016', 8.7, 19.7, 0.0, 2.6, 10.8, 'W', 28, 'WNW', 'E', 22, 11, 75, 52, 1026.4, 1022.9, 1, 1, 11.0, 17.9, 'No', 'No'), ('8/9/2016', 8.1, 19.1, 0.0, 2.0, 6.9, 'NNE', 28, 'W', 'NE', 17, 11, 73, 52, 1023.1, 1017.9, 5, 7, 11.0, 18.8, 'No', 'No'), ('8/10/2016', 10.9, 25.2, 0.0, 4.8, 9.2, 'NW', 44, 'NNW', 'NNW', 17, 24, 52, 33, 1015.6, 1011.4, 3, 3, 17.6, 24.6, 'No', 'No'), ('8/11/2016', 11.2, 20.3, 0.0, 6.2, 10.6, 'W', 46, 'W', 'WSW', 17, 22, 48, 30, 1018.4, 1017.0, 1, 1, 14.0, 19.6, 'No', 'No'), ('8/12/2016', 7.1, 19.4, 0.0, 6.4, 8.6, 'NW', 41, 'WNW', 'E', 20, 13, 56, 37, 1024.4, 1019.8, 0, 7, 9.7, 17.3, 'No', 'No'), ('8/13/2016', 8.3, 20.3, 0.0, 3.2, 10.6, 'W', 41, 'W', 'WSW', 24, 19, 49, 31, 1022.5, 1020.2, 1, 2, 12.4, 19.8, 'No', 'No'), ('8/14/2016', 9.5, 20.0, 0.0, 5.4, 10.5, 'W', 28, 'W', 'SE', 20, 13, 52, 46, 1027.7, 1027.2, 1, 1, 14.2, 17.6, 'No', 'No'), ('8/15/2016', 8.9, 19.6, 0.0, 3.2, 10.1, 'NE', 30, 'WNW', 'NE', 17, 17, 72, 54, 1032.7, 1029.7, 1, 1, 12.0, 19.2, 'No', 'No'), ('8/16/2016', 9.8, 20.3, 0.0, 4.0, 10.5, 'ENE', 24, 'W', 'ENE', 13, 19, 75, 59, 1031.0, 1025.8, 0, 0, 12.8, 19.6, 'No', 'No'), ('8/17/2016', 10.6, 24.2, 0.0, 3.8, 10.2, 'ENE', 24, 'W', 'ENE', 15, 11, 63, 35, 1026.3, 1022.1, 1, 6, 14.2, 22.7, 'No', 'No'), ('8/18/2016', 11.6, 22.9, 0.0, 4.6, 10.5, 'N', 31, 'W', 'ENE', 15, 19, 62, 40, 1024.5, 1020.7, 1, 1, 14.2, 20.7, 'No', 'No'), ('8/19/2016', 11.2, 24.3, 0.0, 4.8, 10.0, 'NNE', 48, 'W', 'NNW', 11, 24, 66, 37, 1020.1, 1013.9, 0, 6, 14.2, 22.4, 'No', 'No'), ('8/20/2016', 11.0, 17.9, 0.4, 6.6, 10.7, 'WSW', 59, 'W', 'WSW', 19, 22, 51, 35, 1015.3, 1013.8, 1, 3, 13.2, 15.7, 'No', 'No'), ('8/21/2016', 8.2, 20.4, 0.0, 5.2, 10.7, 'W', 39, 'W', 'WNW', 24, 9, 48, 32, 1019.8, 1016.4, 1, 1, 12.5, 19.9, 'No', 'No'), ('8/22/2016', 9.5, 13.8, 0.0, 3.0, 0.2, 'W', 35, 'WNW', 'W', 15, 24, 66, 67, 1016.8, 1015.0, 7, 7, 11.4, 12.2, 'No', 'Yes'), ('8/23/2016', 8.5, 18.4, 1.8, 0.6, 6.8, 'SSE', 37, 'WNW', 'SSW', 19, 20, 69, 57, 1014.4, 1013.5, 1, 7, 11.9, 15.4, 'Yes', 'Yes'), ('8/24/2016', 11.8, 14.7, 2.4, 3.2, 0.0, 'S', 43, 'SSE', 'ESE', 11, 9, 79, 90, 1013.3, 1007.5, 8, 8, 13.4, 13.7, 'Yes', 'Yes'), ('8/25/2016', 9.0, 17.3, 52.8, 5.2, 6.7, 'W', 48, 'SW', 'S', 22, 15, 67, 48, 1010.2, 1010.6, 7, 3, 11.4, 15.7, 'Yes', 'No'), ('8/26/2016', 7.3, 17.3, 0.0, 4.6, 7.8, 'W', 43, 'W', 'S', 20, 20, 57, 50, 1018.7, 1017.6, 7, 7, 10.4, 16.4, 'No', 'Yes'), ('8/27/2016', 7.4, 19.9, 1.4, 2.8, 10.7, 'W', 33, 'W', 'ENE', 24, 15, 57, 45, 1023.6, 1020.3, 1, 1, 11.3, 17.7, 'Yes', 'No'), ('8/28/2016', 8.4, 20.5, 0.0, 3.8, 10.7, 'W', 33, 'W', 'ESE', 22, 17, 50, 36, 1022.9, 1020.9, 1, 2, 12.2, 18.0, 'No', 'No'), ('8/29/2016', 8.4, 19.6, 0.0, 4.0, 6.1, 'W', 22, 'W', 'W', 17, 9, 57, 38, 1027.4, 1025.0, 7, 7, 12.9, 18.1, 'No', 'No'), ('8/30/2016', 10.7, 19.9, 0.0, 3.2, 4.4, 'NNE', 31, 'W', 'ENE', 17, 15, 71, 62, 1026.9, 1023.1, 7, 6, 13.8, 19.6, 'No', 'No'), ('8/31/2016', 13.6, 23.6, 0.0, 4.8, 2.3, 'NNW', 54, 'N', 'NNW', 20, 39, 61, 53, 1018.7, 1013.9, 7, 7, 18.8, 21.2, 'No', 'No'), ('9/1/2016', 12.1, 22.5, 0.0, 4.6, 9.2, 'NE', 28, 'W', 'NE', 11, 15, 63, 46, 1020.3, 1015.3, 2, 3, 16.9, 20.7, 'No', 'Yes'), ('9/2/2016', 14.5, 18.0, 14.4, 6.2, 0.0, 'NE', 31, 'SSE', 'SSE', 6, 9, 90, 91, 1011.6, 1006.0, 8, 8, 15.7, 15.9, 'Yes', 'Yes'), ('9/3/2016', 15.4, 20.5, 23.4, 2.2, 9.1, 'WNW', 65, 'WNW', 'WNW', 33, 30, 50, 39, 998.3, 1004.3, 4, 5, 17.6, 20.1, 'Yes', 'No'), ('9/4/2016', 10.1, 21.3, 0.0, 5.6, 10.9, 'WSW', 39, 'WNW', 'ESE', 11, 15, 48, 33, 1021.6, 1022.0, 1, 1, 15.5, 19.2, 'No', 'No'), ('9/5/2016', 10.0, 21.2, 0.0, 3.4, 11.1, 'ENE', 26, 'W', 'ENE', 20, 19, 55, 54, 1030.4, 1027.1, 0, 0, 14.1, 19.0, 'No', 'No'), ('9/6/2016', 10.0, 20.5, 0.0, 5.0, 10.8, 'E', 24, 'WNW', 'ENE', 13, 19, 66, 58, 1030.4, 1026.3, 0, 0, 15.0, 20.2, 'No', 'No'), ('9/7/2016', 12.2, 22.0, 0.0, 3.2, 8.2, 'NE', 30, 'WNW', 'E', 13, 17, 82, 55, 1031.7, 1029.3, 6, 3, 16.0, 21.0, 'No', 'No'), ('9/8/2016', 15.4, 21.2, 0.0, 3.8, 7.1, 'NE', 41, 'N', 'NE', 9, 24, 69, 67, 1029.7, 1024.8, 7, 5, 18.7, 20.1, 'No', 'No'), ('9/9/2016', 14.7, 22.7, 0.0, 5.0, 8.9, 'NNE', 52, 'ENE', 'NE', 6, 22, 61, 60, 1021.9, 1015.9, 6, 4, 19.5, 21.2, 'No', 'Yes'), ('9/10/2016', 14.1, 22.7, 1.2, 7.4, 9.3, 'NNE', 57, 'NNW', 'W', 26, 31, 54, 31, 1012.7, 1010.9, 2, 7, 17.9, 21.8, 'Yes', 'No'), ('9/11/2016', 13.0, 21.0, 0.0, 6.2, 8.7, 'W', 33, 'WSW', 'ESE', 17, 17, 44, 53, 1019.0, 1017.1, 1, 6, 16.8, 17.6, 'No', 'No'), ('9/12/2016', 12.4, 20.9, 0.0, 4.2, 9.7, 'W', 28, 'W', 'E', 20, 19, 47, 53, 1021.5, 1018.5, 3, 3, 16.6, 18.3, 'No', 'No'), ('9/13/2016', 16.0, 20.2, 0.0, 5.6, 1.5, 'SSW', 30, 'SSW', 'S', 15, 9, 73, 69, 1021.4, 1017.8, 8, 7, 17.5, 18.9, 'No', 'Yes'), ('9/14/2016', 16.0, 24.6, 5.8, 1.8, 3.9, 'NNW', 37, 'NNW', 'N', 6, 19, 86, 55, 1014.1, 1008.4, 8, 7, 17.4, 23.1, 'Yes', 'No'), ('9/15/2016', 14.1, 22.1, 0.0, 6.6, 8.1, 'W', 41, 'NW', 'WNW', 41, 35, 35, 31, 1009.8, 1007.5, 1, 7, 17.4, 20.9, 'No', 'No'), ('9/16/2016', 13.5, 22.5, 0.0, 6.8, 8.5, 'W', 43, 'W', 'W', 19, 28, 55, 29, 1016.5, 1015.5, 6, 3, 16.9, 21.7, 'No', 'No'), ('9/17/2016', 10.7, 22.4, 0.0, 5.4, 8.8, 'NNE', 37, 'W', 'NE', 6, 19, 52, 44, 1022.0, 1018.0, 1, 7, 17.5, 19.2, 'No', 'No'), ('9/18/2016', 14.2, 17.8, 0.0, 6.6, 0.0, 'WSW', 30, 'W', 'W', 17, 6, 66, 79, 1012.6, 1005.7, 8, 8, 14.9, 15.1, 'No', 'Yes'), ('9/19/2016', 13.1, 21.4, 13.4, 1.0, 10.1, 'W', 59, 'W', 'W', 30, 28, 53, 38, 1008.5, 1008.7, 1, 1, 17.7, 20.6, 'Yes', 'No'), ('9/20/2016', 10.0, 20.6, 0.0, 6.4, 8.7, 'WSW', 28, 'WNW', 'NE', 17, 17, 48, 47, 1018.9, 1016.0, 7, 7, 15.1, 18.5, 'No', 'No'), ('9/21/2016', 14.0, 21.2, 0.0, 4.8, 2.9, 'N', 31, 'W', 'NE', 9, 15, 61, 78, 1012.5, 1007.5, 7, 8, 16.0, 16.8, 'No', 'Yes'), ('9/22/2016', 13.5, 20.1, 2.0, 4.0, 4.1, 'WSW', 56, 'W', 'W', 20, 24, 54, 63, 1006.9, 1005.9, 3, 7, 18.4, 17.0, 'Yes', 'No'), ('9/23/2016', 15.2, 22.0, 0.6, 3.0, 8.2, 'SSW', 61, 'WSW', 'SSW', 17, 24, 55, 48, 1011.7, 1010.7, 6, 2, 17.3, 21.5, 'No', 'No'), ('9/24/2016', 12.5, 22.3, 0.0, 4.8, 10.1, 'W', 30, 'WNW', 'ESE', 13, 17, 55, 63, 1012.6, 1007.9, 1, 1, 18.4, 20.6, 'No', 'Yes'), ('9/25/2016', 13.6, 22.1, 3.4, 5.2, 2.1, 'WSW', 41, 'W', 'SE', 15, 15, 74, 75, 1006.7, 1006.1, 7, 7, 15.5, 16.3, 'Yes', 'Yes'), ('9/26/2016', 12.0, 21.8, 4.0, 4.2, 10.1, 'WSW', 41, 'WSW', 'E', 20, 19, 41, 44, 1013.0, 1009.0, 1, 1, 16.5, 18.9, 'Yes', 'No'), ('9/27/2016', 10.9, 23.2, 0.0, 6.2, 9.7, 'WSW', 61, 'N', 'WSW', 20, 26, 37, 22, 1009.7, 1006.8, 2, 2, 18.6, 20.6, 'No', 'No'), ('9/28/2016', 10.2, 21.3, 0.0, 7.2, 11.4, 'W', 35, 'WNW', 'E', 17, 17, 46, 42, 1014.7, 1011.3, 1, 1, 16.2, 19.6, 'No', 'Yes'), ('9/29/2016', 14.2, 22.8, 1.4, 5.4, 4.2, 'NW', 56, 'NNE', 'N', 11, 22, 76, 50, 1000.5, 994.0, 8, 2, 14.8, 22.3, 'Yes', 'No'), ('9/30/2016', 12.3, 20.1, 0.4, 7.2, 8.6, 'NNW', 67, 'NNW', 'NW', 28, 39, 42, 40, 999.1, 998.3, 6, 3, 16.1, 17.3, 'No', 'No'), ('10/1/2016', 12.4, 22.1, 0.0, 7.4, 10.4, 'W', 41, 'WNW', 'W', 35, 39, 40, 34, 1005.0, 1005.5, 3, 3, 19.5, 20.2, 'No', 'No'), ('10/2/2016', 12.5, 24.7, 0.0, 8.0, 11.1, 'NE', 41, 'NW', 'ENE', 7, 20, 44, 45, 1012.9, 1008.3, 0, 0, 18.4, 22.7, 'No', 'No'), ('10/3/2016', 18.4, 25.6, 0.0, 9.0, 8.3, 'WSW', 72, 'NNE', 'WNW', 15, 31, 41, 14, 999.4, 997.8, 7, 7, 21.5, 22.9, 'No', 'No'), ('10/4/2016', 12.7, 23.4, 0.0, 10.2, 11.1, 'W', 70, 'NW', 'W', 17, 43, 34, 25, 1007.8, 1003.7, 1, 1, 17.5, 23.0, 'No', 'No'), ('10/5/2016', 11.7, 23.7, 0.0, 11.0, 11.0, 'SW', 57, 'W', 'WSW', 30, 26, 34, 16, 1016.4, 1013.2, 0, 1, 14.7, 22.9, 'No', 'No'), ('10/6/2016', 13.0, 27.8, 0.0, 7.6, 11.1, 'WSW', 48, 'W', 'WSW', 7, 30, 34, 20, 1019.1, 1017.0, 4, 8, 19.9, 27.2, 'No', 'No'), ('10/7/2016', 16.0, 31.0, 0.0, 8.6, 9.3, 'WNW', 37, 'W', 'W', 9, 22, 40, 16, 1021.0, 1015.6, 7, 5, 22.5, 30.8, 'No', 'No'), ('10/8/2016', 20.1, 22.2, 0.2, 10.0, 7.4, 'SSE', 54, 'S', 'SSE', 28, 30, 63, 50, 1016.3, 1017.6, 6, 5, 21.0, 20.1, 'No', 'No'), ('10/9/2016', 13.8, 25.5, 0.0, 7.4, 8.4, 'NE', 52, 'W', 'NE', 11, 24, 51, 40, 1022.9, 1018.1, 7, 7, 17.5, 20.3, 'No', 'No'), ('10/10/2016', 16.8, 33.6, 0.0, 8.4, 6.6, 'W', 41, 'NE', 'WSW', 9, 28, 37, 24, 1007.7, 1004.1, 6, 7, 25.3, 31.8, 'No', 'Yes'), ('10/11/2016', 12.3, 21.3, 3.8, 10.2, 11.4, 'WSW', 61, 'WSW', 'SE', 35, 9, 33, 26, 1013.2, 1012.9, 1, 3, 14.9, 20.1, 'Yes', 'No'), ('10/12/2016', 10.7, 23.6, 0.0, 6.6, 9.3, 'WSW', 39, 'W', 'E', 26, 24, 45, 32, 1016.5, 1012.5, 1, 5, 14.3, 20.7, 'No', 'Yes'), ('10/13/2016', 11.8, 18.3, 4.4, 7.4, 7.9, 'SSW', 57, 'SSW', 'S', 26, 24, 56, 57, 1021.2, 1022.4, 2, 7, 15.9, 15.6, 'Yes', 'No'), ('10/14/2016', 9.0, 21.3, 0.2, 8.2, 11.6, 'W', 30, 'WNW', 'E', 17, 19, 50, 37, 1025.9, 1023.2, 1, 1, 15.1, 19.4, 'No', 'No'), ('10/15/2016', 11.1, 23.9, 0.0, 5.6, 12.2, 'NNE', 50, 'W', 'NE', 11, 26, 57, 36, 1023.1, 1017.5, 0, 0, 15.9, 23.0, 'No', 'No'), ('10/16/2016', 15.9, 29.0, 0.0, 10.0, 11.0, 'NNE', 56, 'N', 'NE', 22, 28, 31, 37, 1014.9, 1008.7, 0, 1, 23.1, 25.4, 'No', 'No'), ('10/17/2016', 21.7, 22.4, 0.0, 11.8, 2.4, 'W', 41, 'WNW', 'NNW', 28, 15, 43, 78, 1005.8, 1008.3, 7, 7, 22.4, 14.5, 'No', 'Yes'), ('10/18/2016', 11.5, 25.8, 3.0, 3.0, 12.2, 'W', 48, 'NNW', 'WNW', 19, 26, 39, 23, 1014.5, 1010.8, 1, 3, 18.3, 25.5, 'Yes', 'No'), ('10/19/2016', 16.2, 24.5, 0.2, 11.0, 11.1, 'W', 50, 'WSW', 'NW', 24, 6, 30, 20, 1017.9, 1017.0, 3, 2, 19.1, 22.9, 'No', 'No'), ('10/20/2016', 16.4, 21.6, 0.0, 8.0, 10.3, 'NNE', 44, 'ENE', 'NE', 19, 26, 47, 47, 1024.4, 1021.4, 6, 5, 19.0, 20.4, 'No', 'No'), ('10/21/2016', 15.3, 25.2, 0.0, 7.4, 8.4, 'NNE', 46, 'NNW', 'NE', 20, 26, 55, 55, 1018.9, 1012.8, 5, 7, 21.5, 23.3, 'No', 'Yes'), ('10/22/2016', 16.1, 18.0, 11.8, 8.4, 4.1, 'WSW', 57, 'SE', 'S', 15, 22, 84, 69, 1010.0, 1010.1, 7, 7, 17.0, 16.4, 'Yes', 'No'), ('10/23/2016', 10.2, 19.8, 0.6, 4.8, 10.4, 'SSW', 59, 'W', 'S', 22, 28, 53, 42, 1018.3, 1017.7, 7, 2, 13.1, 17.5, 'No', 'No'), ('10/24/2016', 10.2, 21.5, 0.8, 5.8, 12.4, 'ESE', 37, 'W', 'SSE', 15, 22, 45, 33, 1019.6, 1016.7, 1, 1, 15.0, 19.8, 'No', 'No'), ('10/25/2016', 11.4, 23.3, 0.0, 6.8, 12.3, 'ENE', 37, 'W', 'NE', 13, 22, 56, 46, 1018.9, 1014.4, 7, 1, 17.6, 22.8, 'No', 'No'), ('10/26/2016', 14.3, 27.0, 0.0, 7.8, 8.5, 'ENE', 26, 'W', 'E', 11, 20, 52, 34, 1016.6, 1013.0, 7, 7, 18.7, 25.8, 'No', 'No'), ('10/27/2016', 18.4, 21.7, 0.0, 8.0, 6.2, 'SE', 41, 'SSE', 'SSE', 20, 26, 65, 63, 1015.9, 1015.7, 4, 7, 20.8, 19.9, 'No', 'Yes'), ('10/28/2016', 14.7, 19.6, 1.4, 4.6, 0.5, 'SSE', 30, 'W', 'ESE', 19, 7, 73, 57, 1020.6, 1018.5, 8, 8, 15.4, 19.1, 'Yes', 'Yes'), ('10/29/2016', 15.3, 24.3, 3.2, 1.6, 7.9, 'NE', 41, 'W', 'NE', 13, 20, 86, 66, 1020.1, 1017.7, 6, 5, 18.3, 22.0, 'Yes', 'No'), ('10/30/2016', 18.2, 25.5, 0.2, 7.0, 4.6, 'NW', 50, 'NE', 'ENE', 9, 11, 65, 61, 1013.7, 1006.5, 7, 8, 23.0, 25.3, 'No', 'Yes'), ('10/31/2016', 16.1, 23.3, 1.6, 6.6, 12.9, 'NNW', 52, 'SSW', 'E', 28, 20, 24, 28, 1011.0, 1010.8, 1, 1, 18.3, 21.7, 'Yes', 'No'), ('11/1/2016', 12.1, 24.5, 0.0, 10.6, 12.1, 'W', 33, 'W', 'E', 17, 20, 31, 37, 1014.4, 1010.0, 4, 1, 16.8, 20.9, 'No', 'No'), ('11/2/2016', 13.0, 24.1, 0.0, 7.2, 12.8, 'W', 39, 'WSW', 'E', 20, 20, 34, 32, 1014.6, 1013.0, 1, 1, 19.1, 21.6, 'No', 'No'), ('11/3/2016', 13.6, 25.2, 0.0, 7.4, 12.2, 'E', 37, 'WNW', 'ENE', 11, 26, 57, 50, 1018.9, 1014.8, 1, 1, 19.7, 23.7, 'No', 'No'), ('11/4/2016', 15.3, 30.6, 0.0, 8.4, 12.8, 'NE', 35, 'W', 'NE', 11, 20, 58, 33, 1014.8, 1009.2, 2, 1, 21.0, 27.1, 'No', 'No'), ('11/5/2016', 21.0, 25.7, 0.0, 13.4, 12.4, 'W', 76, 'SW', 'WSW', 20, 28, 21, 16, 1002.9, 1006.2, 1, 1, 25.7, 24.9, 'No', 'No'), ('11/6/2016', 15.7, 26.0, 0.0, 14.4, 12.3, 'W', 57, 'WSW', 'ESE', 22, 26, 25, 27, 1009.1, 1007.8, 1, 7, 19.6, 23.2, 'No', 'No'), ('11/7/2016', 14.8, 28.1, 0.0, 7.6, 12.4, 'NE', 44, 'W', 'NE', 13, 24, 34, 46, 1011.1, 1006.4, 2, 1, 22.6, 25.5, 'No', 'No'), ('11/8/2016', 21.2, 28.3, 0.0, 11.0, 4.1, 'S', 54, 'SE', 'SSE', 6, 24, 25, 57, 1007.3, 1007.1, 7, 7, 26.8, 24.7, 'No', 'Yes'), ('11/9/2016', 17.8, 22.7, 2.0, 5.2, 2.5, 'SSW', 37, 'S', 'SSE', 13, 19, 72, 67, 1013.3, 1009.8, 7, 7, 20.1, 21.3, 'Yes', 'Yes'), ('11/10/2016', 16.9, 24.6, 10.2, 2.8, 10.7, 'E', 28, 'W', 'E', 7, 19, 71, 62, 1009.4, 1007.0, 6, 2, 20.0, 23.4, 'Yes', 'No'), ('11/11/2016', 17.8, 24.3, 0.0, 7.0, 11.1, 'E', 33, 'SSW', 'ESE', 9, 20, 68, 59, 1012.9, 1009.9, 5, 1, 20.2, 22.6, 'No', 'Yes'), ('11/12/2016', 18.4, 32.5, 9.0, 7.6, 9.1, 'N', 48, 'NNW', 'E', 15, 22, 72, 59, 1002.5, 996.9, 7, 3, 22.1, 26.4, 'Yes', 'No'), ('11/13/2016', 18.9, 30.3, 0.0, 8.0, 13.0, 'W', 72, 'NNW', 'W', 4, 41, 29, 21, 998.6, 995.4, 1, 1, 24.9, 28.0, 'No', 'No'), ('11/14/2016', 17.4, 24.4, 0.0, 15.8, 7.0, 'WSW', 56, 'W', 'SSE', 33, 28, 40, 52, 1002.0, 1004.5, 3, 7, 20.5, 20.3, 'No', 'No'), ('11/15/2016', 15.4, 23.2, 0.6, 5.8, 9.4, 'S', 39, 'S', 'ESE', 13, 19, 61, 45, 1016.1, 1015.0, 7, 3, 17.9, 20.5, 'No', 'No'), ('11/16/2016', 14.3, 25.2, 0.0, 5.2, 12.7, 'ESE', 39, 'WNW', 'ESE', 13, 22, 54, 52, 1020.0, 1021.3, 0, 3, 19.9, 22.0, 'No', 'No'), ('11/17/2016', 17.3, 23.9, 0.0, 7.4, 12.8, 'NNE', 43, 'ESE', 'E', 4, 28, 57, 53, 1025.6, 1021.9, 4, 1, 21.1, 23.1, 'No', 'No'), ('11/18/2016', 16.4, 31.4, 0.0, 9.2, 12.1, 'NNE', 37, 'W', 'NE', 13, 11, 52, 36, 1017.4, 1013.5, 1, 2, 23.0, 30.0, 'No', 'No'), ('11/19/2016', 19.3, 24.8, 0.0, 8.6, 3.7, 'SSE', 44, 'SSE', 'SE', 30, 20, 67, 58, 1018.3, 1018.4, 7, 7, 21.7, 22.1, 'No', 'No'), ('11/20/2016', 19.1, 25.1, 0.0, 6.0, 8.5, 'E', 33, 'E', 'E', 13, 26, 58, 55, 1021.3, 1018.2, 4, 7, 22.3, 23.2, 'No', 'No'), ('11/21/2016', 19.7, 28.4, 0.0, 7.4, 6.0, 'E', 35, 'E', 'ENE', 11, 17, 67, 64, 1018.4, 1015.1, 6, 5, 24.6, 25.5, 'No', 'No'), ('11/22/2016', 21.0, 31.0, 0.0, 8.0, 9.7, 'NE', 46, 'E', 'ENE', 15, 24, 51, 54, 1014.8, 1012.1, 1, 3, 26.6, 26.2, 'No', 'No'), ('11/24/2016', 13.5, 23.4, 5.4, 6.6, 13.1, 'SSE', 52, 'WSW', 'SE', 22, 26, 42, 39, 1013.0, 1011.8, 1, 1, 18.3, 21.8, 'Yes', 'No'), ('11/25/2016', 14.7, 25.5, 0.0, 8.8, 13.1, 'ESE', 37, 'W', 'ESE', 20, 22, 33, 46, 1012.8, 1012.5, 4, 2, 20.6, 23.4, 'No', 'No'), ('11/26/2016', 18.1, 24.4, 0.0, 8.0, 12.3, 'NE', 46, 'ENE', 'NE', 7, 24, 55, 53, 1017.4, 1013.7, 3, 1, 22.3, 23.9, 'No', 'No'), ('11/27/2016', 19.6, 23.5, 0.0, 9.8, 1.7, 'SE', 35, 'SE', 'ESE', 19, 22, 71, 66, 1017.8, 1016.9, 7, 7, 20.5, 21.6, 'No', 'No'), ('11/28/2016', 20.3, 26.1, 0.0, 6.0, 8.1, 'NE', 37, 'NE', 'E', 15, 28, 71, 63, 1015.0, 1010.4, 6, 1, 22.8, 25.5, 'No', 'No'), ('11/29/2016', 19.3, 25.3, 0.0, 7.8, 7.0, 'SE', 44, 'S', 'SE', 22, 20, 65, 57, 1011.8, 1010.8, 7, 6, 22.4, 24.1, 'No', 'No'), ('11/30/2016', 18.2, 25.2, 0.0, 6.4, 4.4, 'NE', 50, 'ESE', 'E', 6, 31, 61, 57, 1012.4, 1008.8, 7, 2, 22.4, 24.2, 'No', 'No'), ('12/1/2016', 18.1, 28.5, 0.0, 7.4, 8.1, 'ENE', 37, 'W', 'ENE', 9, 19, 68, 51, 1008.0, 1005.3, 7, 7, 21.2, 25.4, 'No', 'No'), ('12/2/2016', 18.7, 35.7, 0.2, 6.0, 9.8, 'SSW', 57, 'WNW', 'ESE', 13, 17, 44, 24, 1008.4, 1007.7, 3, 5, 25.6, 30.9, 'No', 'No'), ('12/3/2016', 21.0, 26.8, 0.0, 11.2, 9.7, 'S', 41, 'SSE', 'ESE', 11, 19, 64, 55, 1016.0, 1015.0, 7, 5, 22.6, 23.8, 'No', 'No'), ('12/4/2016', 19.7, 26.9, 0.0, 8.0, 9.3, 'NE', 39, 'E', 'E', 6, 26, 64, 60, 1016.0, 1013.1, 7, 7, 23.0, 25.1, 'No', 'No'), ('12/5/2016', 22.1, 29.9, 0.4, 7.6, 2.9, 'SSW', 59, 'NE', 'E', 13, 17, 71, 65, 1009.6, 1005.9, 7, 7, 26.1, 27.1, 'No', 'Yes'), ('12/6/2016', 20.4, 23.6, 3.2, 7.0, 0.0, 'S', 33, 'W', 'NE', 15, 7, 86, 83, 1012.4, 1010.6, 8, 8, 20.6, 22.2, 'Yes', 'Yes'), ('12/7/2016', 18.6, 25.1, 7.8, 1.4, 9.3, 'SSW', 37, 'SE', 'E', 15, 24, 86, 56, 1015.2, 1014.4, 5, 4, 20.7, 24.4, 'Yes', 'No'), ('12/8/2016', 20.2, 27.9, 0.2, 8.0, 12.2, 'NNE', 56, 'NNE', 'NE', 9, 26, 60, 61, 1008.7, 999.4, 1, 2, 24.6, 26.9, 'No', 'No'), ('12/9/2016', 18.1, 27.8, 0.4, 13.6, 13.4, 'W', 72, 'W', 'WSW', 44, 31, 35, 14, 1007.9, 1009.9, 1, 1, 20.2, 26.4, 'No', 'No'), ('12/10/2016', 16.9, 23.7, 0.0, 9.0, 9.8, 'E', 39, 'SSE', 'ENE', 11, 26, 54, 52, 1022.5, 1020.5, 3, 2, 20.8, 22.1, 'No', 'No'), ('12/11/2016', 20.0, 26.3, 0.0, 9.0, 11.4, 'E', 41, 'NE', 'E', 13, 28, 57, 56, 1022.2, 1020.4, 3, 1, 23.6, 24.3, 'No', 'No'), ('12/12/2016', 20.9, 27.6, 0.0, 10.6, 12.4, 'NE', 52, 'NE', 'ENE', 15, 19, 59, 53, 1022.6, 1018.1, 6, 1, 23.8, 25.5, 'No', 'No'), ('12/13/2016', 20.7, 37.8, 0.0, 10.2, 11.4, 'NNE', 44, 'ESE', 'NE', 9, 15, 49, 36, 1015.5, 1011.1, 3, 5, 27.5, 31.1, 'No', 'No'), ('12/14/2016', 27.1, 37.2, 0.0, 13.4, 2.5, 'WSW', 57, 'NW', 'WSW', 24, 33, 23, 16, 1008.5, 1007.0, 7, 7, 32.4, 34.1, 'No', 'Yes'), ('12/15/2016', 17.4, 19.1, 8.2, 8.8, 0.0, 'SSE', 46, 'SE', 'SSE', 17, 15, 88, 81, 1017.2, 1017.4, 8, 8, 17.7, 17.7, 'Yes', 'Yes'), ('12/16/2016', 17.2, 25.4, 32.6, 1.0, 0.0, 'ESE', 30, 'SSE', 'ESE', 17, 4, 89, 86, 1013.3, 1009.3, 8, 8, 18.8, 20.2, 'Yes', 'Yes'), ('12/17/2016', 18.5, 33.7, 10.4, 1.4, 12.7, 'S', 70, 'NW', 'WNW', 2, 19, 67, 27, 1007.4, 1005.2, 3, 4, 25.4, 32.4, 'Yes', 'No'), ('12/18/2016', 18.3, 21.3, 0.0, 10.0, 0.7, 'SSE', 57, 'SE', 'SE', 15, 22, 61, 55, 1018.8, 1020.0, 8, 8, 19.8, 19.9, 'No', 'No'), ('12/19/2016', 17.7, 22.9, 0.0, 7.8, 7.1, 'NE', 44, 'ENE', 'NE', 13, 24, 49, 47, 1021.0, 1017.5, 6, 3, 20.8, 21.4, 'No', 'No'), ('12/20/2016', 16.7, 27.1, 0.0, 7.0, 12.0, 'SSW', 48, 'E', 'ESE', 4, 20, 52, 52, 1010.4, 1005.3, 2, 3, 22.8, 26.9, 'No', 'No'), ('12/21/2016', 18.6, 26.7, 0.0, 10.0, 10.4, 'S', 52, 'S', 'ESE', 15, 28, 64, 50, 1012.3, 1012.2, 3, 2, 22.8, 25.0, 'No', 'No'), ('12/22/2016', 20.3, 24.3, 0.0, 9.2, 3.7, 'ENE', 35, 'E', 'ENE', 17, 20, 60, 52, 1019.4, 1018.1, 8, 5, 21.1, 23.0, 'No', 'No'), ('12/23/2016', 20.8, 24.4, 0.0, 7.6, 7.9, 'ENE', 48, 'NE', 'NE', 20, 28, 56, 56, 1019.3, 1016.6, 5, 2, 23.0, 23.8, 'No', 'No'), ('12/24/2016', 19.8, 27.2, 0.0, 9.4, 4.3, 'NNW', 44, 'WNW', 'ENE', 9, 20, 66, 55, 1015.7, 1013.8, 7, 7, 23.2, 26.3, 'No', 'Yes'), ('12/25/2016', 19.1, 27.4, 1.6, 4.6, 12.8, 'NE', 48, 'ESE', 'NE', 4, 26, 64, 55, 1017.1, 1015.5, 3, 3, 23.9, 26.8, 'Yes', 'No'), ('12/26/2016', 20.9, 29.3, 0.0, 11.2, 10.9, 'NE', 52, 'E', 'NE', 13, 30, 59, 51, 1014.7, 1011.4, 1, 1, 25.8, 27.9, 'No', 'No'), ('12/27/2016', 21.8, 29.6, 0.0, 11.2, 6.0, 'NE', 43, 'S', 'ESE', 17, 19, 66, 60, 1014.5, 1013.3, 7, 7, 25.7, 27.5, 'No', 'No'), ('12/28/2016', 21.1, 28.9, 0.0, 7.8, 9.4, 'NNE', 61, 'E', 'NNE', 15, 24, 63, 48, 1013.0, 1009.7, 6, 6, 24.9, 27.5, 'No', 'No'), ('12/29/2016', 22.6, 36.6, 0.0, 10.4, 4.8, 'E', 28, 'W', 'ENE', 15, 22, 49, 30, 1007.2, 1004.4, 7, 6, 28.1, 31.8, 'No', 'No'), ('12/30/2016', 23.9, 33.3, 0.0, 9.2, 0.5, 'NNE', 30, 'W', 'ENE', 9, 20, 58, 34, 1003.6, 1001.7, 8, 7, 27.3, 32.1, 'No', 'No'), ('12/31/2016', 24.1, 30.0, 0.0, 8.2, 4.8, 'SE', 37, 'SSE', 'SE', 17, 24, 57, 62, 1003.7, 1003.4, 6, 7, 27.7, 26.4, 'No', 'No'), ('1/1/2017', 22.7, 26.6, 0.0, 6.8, 0.0, 'E', 24, 'E', 'E', 9, 19, 70, 70, 1007.4, 1005.5, 7, 8, 24.6, 24.9, 'No', 'No'), ('1/2/2017', 21.2, 26.3, 0.4, 3.4, 3.5, 'S', 56, 'SSW', 'SSE', 26, 28, 71, 54, 1009.9, 1011.8, 7, 5, 22.1, 24.8, 'No', 'Yes'), ('1/3/2017', 18.5, 26.6, 2.6, 6.2, 8.8, 'SSE', 48, 'S', 'SSE', 19, 19, 66, 60, 1018.5, 1018.3, 7, 7, 21.9, 25.4, 'Yes', 'Yes'), ('1/4/2017', 20.1, 25.9, 1.2, 7.8, 5.6, 'ESE', 31, 'ESE', 'ESE', 22, 22, 53, 45, 1021.4, 1020.0, 7, 7, 24.0, 23.7, 'Yes', 'Yes'), ('1/5/2017', 19.6, 24.3, 5.0, 6.0, 0.5, 'ENE', 30, 'NNE', 'E', 7, 20, 89, 69, 1019.0, 1017.2, 8, 7, 20.5, 22.6, 'Yes', 'Yes'), ('1/6/2017', 19.9, 26.5, 8.8, 3.8, 4.8, 'E', 35, 'ESE', 'E', 15, 22, 86, 57, 1018.3, 1017.5, 7, 6, 20.0, 25.3, 'Yes', 'Yes'), ('1/7/2017', 19.2, 26.8, 4.4, 6.6, 11.5, 'NE', 43, 'S', 'NE', 2, 28, 61, 57, 1018.4, 1015.0, 3, 3, 24.8, 25.2, 'Yes', 'No'), ('1/8/2017', 19.7, 28.5, 0.0, 10.4, 11.7, 'NE', 54, 'N', 'ENE', 11, 20, 52, 52, 1013.5, 1010.0, 2, 6, 25.1, 27.5, 'No', 'No'), ('1/9/2017', 21.3, 29.9, 0.0, 9.6, 9.2, 'ENE', 31, 'ESE', 'E', 9, 20, 57, 57, 1011.5, 1009.2, 2, 2, 27.0, 26.7, 'No', 'No'), ('1/10/2017', 22.6, 31.3, 0.4, 8.2, 8.8, 'E', 31, 'W', 'E', 9, 17, 73, 49, 1012.0, 1008.1, 7, 4, 24.8, 30.5, 'No', 'No'), ('1/11/2017', 24.0, 37.7, 0.0, 7.4, 10.9, 'SSE', 63, 'W', 'ESE', 9, 20, 53, 47, 1007.6, 1003.4, 4, 7, 29.2, 31.4, 'No', 'No'), ('1/12/2017', 22.3, 28.4, 0.0, 9.4, 7.2, 'E', 31, 'SSE', 'E', 7, 20, 68, 52, 1012.4, 1010.7, 7, 2, 24.7, 26.8, 'No', 'No'), ('1/13/2017', 23.0, 30.5, 0.0, 8.6, 8.9, 'SSW', 52, 'N', 'NE', 15, 30, 68, 57, 1008.9, 1001.3, 8, 1, 24.6, 29.0, 'No', 'No'), ('1/14/2017', 24.6, 32.5, 0.0, 10.6, 7.1, 'ESE', 35, 'NNW', 'ESE', 2, 22, 59, 52, 1003.4, 1003.2, 8, 1, 28.7, 29.2, 'No', 'No'), ('1/15/2017', 22.8, 27.0, 0.0, 8.0, 6.9, 'ESE', 33, 'E', 'E', 20, 22, 56, 57, 1015.1, 1015.7, 6, 7, 25.6, 25.5, 'No', 'No'), ('1/16/2017', 21.7, 27.2, 0.0, 7.2, 12.1, 'NE', 52, 'NNE', 'NE', 22, 28, 55, 57, 1017.1, 1013.9, 3, 0, 26.2, 26.3, 'No', 'No'), ('1/17/2017', 20.8, 36.6, 0.0, 10.4, 11.9, 'NNE', 50, 'ESE', 'ENE', 6, 11, 64, 44, 1013.6, 1008.3, 5, 2, 25.3, 32.6, 'No', 'No'), ('1/18/2017', 25.1, 38.1, 0.0, 13.8, 11.1, 'SSE', 59, 'WNW', 'SSE', 20, 31, 26, 52, 1005.4, 1006.8, 1, 2, 36.5, 30.1, 'No', 'No'), ('1/19/2017', 20.1, 24.5, 0.0, 12.6, 0.0, 'ENE', 41, 'ESE', 'ENE', 20, 19, 61, 53, 1015.3, 1013.7, 8, 8, 21.5, 22.7, 'No', 'No'), ('1/20/2017', 19.0, 29.2, 0.0, 5.8, 2.6, 'SSW', 65, 'NNE', 'NNW', 22, 28, 62, 68, 1001.1, 994.3, 7, 7, 24.1, 28.3, 'No', 'Yes'), ('1/21/2017', 20.8, 27.4, 7.8, 6.2, 9.7, 'SSE', 48, 'SSE', 'SE', 22, 20, 49, 42, 1010.5, 1012.2, 7, 1, 22.2, 26.6, 'Yes', 'No'), ('1/22/2017', 20.4, 26.5, 0.0, 9.1, 10.7, 'ENE', 39, 'NE', 'E', 4, 22, 50, 50, 1017.9, 1015.8, 1, 4, 23.8, 26.0, 'No', 'No'), ('1/23/2017', 21.5, 32.6, 0.0, 9.6, 12.1, 'NE', 56, 'NNW', 'NE', 17, 20, 60, 51, 1014.9, 1010.1, 3, 1, 25.5, 28.6, 'No', 'No'), ('1/24/2017', 24.5, 37.0, 0.0, 12.0, 2.6, 'SSW', 69, 'NW', 'W', 11, 20, 34, 33, 1007.4, 1008.4, 6, 7, 32.6, 35.0, 'No', 'Yes'), ('1/25/2017', 20.6, 24.3, 17.8, 10.2, 0.3, 'SSE', 35, 'S', 'S', 13, 11, 68, 62, 1020.5, 1018.0, 7, 8, 21.7, 23.3, 'Yes', 'No'), ('1/26/2017', 20.7, 25.5, 0.0, 2.8, 0.4, 'SSE', 31, 'SSW', 'SSE', 11, 13, 70, 64, 1015.9, 1014.9, 8, 6, 22.6, 24.9, 'No', 'No'), ('1/27/2017', 20.4, 27.1, 0.0, 4.2, 6.0, 'S', 31, 'SSW', 'ESE', 13, 15, 67, 57, 1018.5, 1016.9, 7, 4, 21.7, 25.7, 'No', 'No'), ('1/28/2017', 20.4, 29.7, 0.0, 5.4, 12.2, 'NE', 48, 'NE', 'ENE', 2, 17, 63, 59, 1015.9, 1012.2, 1, 1, 26.4, 28.1, 'No', 'No'), ('1/29/2017', 22.3, 30.2, 0.0, 11.4, 6.8, 'S', 31, 'SSW', 'SSE', 13, 19, 74, 56, 1016.8, 1015.4, 7, 6, 24.5, 28.9, 'No', 'No'), ('1/30/2017', 23.1, 34.3, 0.0, 6.0, 12.0, 'NNE', 56, 'E', 'NE', 13, 17, 67, 54, 1012.5, 1008.0, 1, 3, 27.9, 30.3, 'No', 'No'), ('1/31/2017', 25.4, 39.4, 0.0, 11.8, 4.8, 'SSE', 57, 'ESE', 'SSE', 7, 33, 36, 58, 1008.1, 1009.7, 7, 7, 33.2, 29.2, 'No', 'Yes'), ('2/1/2017', 20.3, 23.6, 1.2, 9.2, 0.0, 'SSW', 33, 'SSW', 'SSE', 6, 9, 83, 79, 1016.1, 1012.7, 8, 8, 21.1, 22.4, 'Yes', 'Yes'), ('2/2/2017', 20.8, 27.1, 4.4, 0.0, 6.0, 'S', 50, 'S', 'SE', 30, 22, 70, 56, 1013.2, 1013.9, 7, 7, 23.1, 25.4, 'Yes', 'No'), ('2/3/2017', 22.3, 26.4, 0.0, 6.6, 0.1, 'NNE', 24, 'NNE', 'NE', 11, 17, 79, 63, 1015.5, 1013.5, 8, 8, 22.8, 26.1, 'No', 'No'), ('2/4/2017', 22.7, 30.4, 0.0, 4.4, 7.2, 'NNE', 35, 'ESE', 'E', 4, 17, 78, 65, 1013.9, 1010.4, 8, 5, 26.0, 28.1, 'No', 'No'), ('2/5/2017', 25.8, 34.9, 0.0, 9.6, 7.0, 'NW', 41, 'E', 'ENE', 4, 6, 50, 41, 1010.4, 1007.3, 7, 7, 29.5, 34.1, 'No', 'No'), ('2/6/2017', 26.2, 34.7, 0.0, 11.8, 10.9, 'S', 48, 'S', 'SE', 19, 19, 55, 44, 1011.3, 1009.3, 1, 1, 29.6, 33.9, 'No', 'Yes'), ('2/7/2017', 22.1, 24.9, 6.4, 8.2, 1.3, 'W', 41, 'S', 'S', 24, 19, 88, 89, 1017.6, 1018.7, 8, 7, 22.2, 21.0, 'Yes', 'Yes'), ('2/8/2017', 20.7, 27.0, 85.0, 3.4, 5.9, 'ESE', 46, 'ESE', 'E', 37, 19, 79, 85, 1022.1, 1021.8, 7, 7, 24.6, 23.1, 'Yes', 'Yes'), ('2/9/2017', 22.5, 30.9, 5.4, 5.2, 11.8, 'NNE', 54, 'NNW', 'NE', 17, 20, 72, 55, 1018.6, 1013.0, 3, 1, 25.7, 29.7, 'Yes', 'No'), ('2/10/2017', 23.7, 37.5, 0.0, 10.0, 12.0, 'SSE', 44, 'NW', 'ENE', 7, 17, 61, 35, 1010.4, 1006.4, 6, 2, 27.4, 36.2, 'No', 'No'), ('2/11/2017', 23.9, 36.2, 0.0, 11.0, 11.4, 'SSW', 63, 'W', 'E', 9, 19, 72, 51, 1007.8, 1002.7, 5, 3, 26.4, 33.1, 'No', 'No'), ('2/12/2017', 24.5, 31.9, 0.0, 10.4, 7.8, 'SSE', 59, 'S', 'SSE', 2, 33, 67, 59, 1000.5, 998.0, 1, 7, 28.1, 28.1, 'No', 'No'), ('2/13/2017', 17.8, 27.3, 0.0, 7.0, 12.8, 'SW', 37, 'SSW', 'ESE', 19, 22, 29, 32, 1008.1, 1007.3, 1, 1, 21.9, 26.9, 'No', 'No'), ('2/14/2017', 21.6, 24.0, 0.0, 9.0, 1.9, 'SSE', 44, 'E', 'SSE', 17, 24, 68, 73, 1015.0, 1015.9, 5, 6, 22.3, 21.2, 'No', 'Yes'), ('2/15/2017', 18.0, 26.1, 25.6, 1.2, 10.1, 'ENE', 37, 'WSW', 'E', 7, 17, 66, 52, 1017.4, 1013.6, 4, 2, 21.3, 26.1, 'Yes', 'No'), ('2/16/2017', 19.5, 30.0, 0.0, 8.0, 11.1, 'NNE', 54, 'W', 'ENE', 6, 24, 63, 51, 1012.1, 1009.0, 1, 1, 23.4, 28.8, 'No', 'No'), ('2/17/2017', 22.6, 29.9, 0.0, 11.2, 6.6, 'N', 70, 'NE', 'NE', 9, 9, 66, 59, 1009.8, 1005.7, 4, 7, 26.6, 26.8, 'No', 'Yes'), ('2/18/2017', 21.8, 29.4, 8.0, 5.4, 7.0, 'SE', 41, 'S', 'ESE', 17, 20, 79, 58, 1007.1, 1004.9, 3, 2, 22.9, 28.8, 'Yes', 'Yes'), ('2/19/2017', 18.6, 26.1, 3.2, 6.4, 7.9, 'S', 48, 'W', 'ESE', 17, 19, 69, 48, 1008.7, 1006.1, 5, 2, 19.7, 25.0, 'Yes', 'No'), ('2/20/2017', 17.5, 28.3, 0.6, 8.0, 12.5, 'WSW', 63, 'W', 'WNW', 35, 19, 32, 18, 1010.5, 1009.6, 0, 0, 19.9, 27.5, 'No', 'No'), ('2/21/2017', 16.9, 27.6, 0.0, 10.4, 11.7, 'NNE', 33, 'WNW', 'ESE', 17, 19, 41, 36, 1019.7, 1018.5, 6, 2, 19.4, 26.3, 'No', 'No'), ('2/22/2017', 19.3, 27.7, 0.0, 7.0, 12.2, 'NE', 48, 'NNE', 'NE', 15, 22, 50, 47, 1021.6, 1018.5, 2, 1, 25.8, 26.2, 'No', 'No'), ('2/23/2017', 21.6, 28.1, 0.0, 11.6, 11.5, 'NNE', 46, 'N', 'ENE', 17, 22, 55, 52, 1019.8, 1017.2, 1, 1, 25.4, 27.3, 'No', 'No'), ('2/24/2017', 21.8, 28.0, 0.0, 10.6, 5.7, 'S', 31, 'SE', 'ESE', 7, 15, 69, 56, 1020.8, 1018.6, 8, 7, 24.5, 27.3, 'No', 'Yes'), ('2/25/2017', 18.6, 20.8, 7.8, 4.4, 0.0, 'SSW', 44, 'S', 'SSW', 19, 19, 89, 87, 1020.5, 1020.1, 8, 8, 18.7, 19.0, 'Yes', 'Yes'), ('2/26/2017', 18.3, 25.5, 28.6, 5.8, 5.3, 'S', 48, 'SSE', 'SSW', 15, 24, 67, 54, 1021.8, 1021.8, 6, 3, 20.7, 24.3, 'Yes', 'Yes'), ('2/27/2017', 18.7, 26.6, 26.4, 7.6, 7.5, 'ESE', 44, 'SE', 'SE', 19, 24, 60, 47, 1024.0, 1022.8, 7, 3, 23.3, 25.6, 'Yes', 'Yes'), ('2/28/2017', 20.7, 26.7, 2.6, 5.6, 9.2, 'ESE', 48, 'ESE', 'E', 19, 17, 63, 61, 1022.7, 1021.4, 6, 6, 25.1, 26.4, 'Yes', 'Yes'), ('3/1/2017', 20.6, 27.2, 26.4, 7.2, 2.2, 'E', 43, 'SE', 'ESE', 9, 22, 87, 67, 1021.0, 1019.4, 6, 7, 21.4, 25.0, 'Yes', 'Yes'), ('3/2/2017', 20.5, 26.3, 3.2, 3.6, 7.6, 'E', 26, 'WNW', 'E', 13, 15, 81, 69, 1018.1, 1016.0, 3, 5, 23.0, 25.0, 'Yes', 'Yes'), ('3/3/2017', 20.7, 24.8, 37.8, 5.2, 1.4, 'SE', 63, 'S', 'SE', 6, 17, 89, 85, 1016.9, 1016.0, 7, 8, 21.7, 22.2, 'Yes', 'Yes'), ('3/4/2017', 19.9, 23.3, 27.6, 4.0, 0.2, 'SSE', 54, 'SE', 'S', 19, 20, 87, 86, 1015.2, 1013.1, 7, 7, 21.5, 20.9, 'Yes', 'Yes'), ('3/5/2017', 20.1, 23.0, 7.6, 2.4, 0.0, 'SW', 56, 'W', 'SW', 20, 24, 78, 76, 1010.2, 1009.6, 7, 7, 20.4, 22.1, 'Yes', 'Yes'), ('3/6/2017', 19.6, 25.7, 2.4, 4.0, 7.7, 'SSW', 65, 'WSW', 'SSW', 19, 33, 63, 49, 1012.8, 1013.2, 5, 3, 20.5, 25.5, 'Yes', 'No'), ('3/7/2017', 18.8, 23.2, 0.0, 9.4, 3.6, 'SSE', 54, 'SW', 'SSW', 13, 30, 73, 62, 1017.6, 1017.7, 7, 7, 19.3, 21.7, 'No', 'Yes'), ('3/8/2017', 16.9, 23.5, 5.0, 8.8, 1.4, 'SE', 46, 'ESE', 'SE', 17, 20, 67, 56, 1018.5, 1017.4, 8, 8, 19.9, 22.0, 'Yes', 'No'), ('3/9/2017', 17.9, 25.1, 1.0, 5.4, 2.7, 'SSE', 43, 'SE', 'SSE', 15, 31, 69, 54, 1017.0, 1016.0, 7, 7, 20.3, 23.3, 'No', 'No'), ('3/10/2017', 17.3, 25.8, 0.6, 5.4, 7.4, 'SSE', 44, 'W', 'S', 17, 24, 73, 51, 1015.1, 1014.0, 3, 3, 19.3, 25.1, 'No', 'No'), ('3/11/2017', 16.9, 26.1, 0.2, 5.0, 10.7, 'SSE', 31, 'WNW', 'ESE', 17, 20, 61, 47, 1014.2, 1012.3, 5, 2, 20.1, 25.5, 'No', 'No'), ('3/12/2017', 17.4, 26.4, 0.0, 7.2, 10.6, 'NNE', 46, 'NNE', 'ENE', 9, 28, 62, 50, 1010.6, 1007.7, 1, 1, 22.3, 26.0, 'No', 'No'), ('3/13/2017', 22.2, 27.4, 0.0, 7.2, 6.2, 'E', 56, 'NNE', 'E', 7, 19, 68, 63, 1011.1, 1012.4, 6, 6, 23.7, 27.0, 'No', 'No'), ('3/14/2017', 22.6, 25.9, 0.4, 7.6, 0.5, 'E', 44, 'ESE', 'ENE', 20, 24, 71, 67, 1019.2, 1020.2, 7, 8, 23.9, 21.4, 'No', 'Yes'), ('3/15/2017', 19.8, 25.9, 38.0, 4.8, 5.5, 'E', 54, 'E', 'E', 30, 31, 76, 67, 1020.6, 1018.7, 7, 6, 22.9, 24.8, 'Yes', 'Yes'), ('3/16/2017', 21.9, 24.9, 2.6, 7.6, 1.0, 'ENE', 56, 'ENE', 'NE', 26, 24, 84, 85, 1013.2, 1009.0, 8, 7, 23.1, 24.5, 'Yes', 'Yes'), ('3/17/2017', 20.0, 22.7, 20.0, 3.0, 1.3, 'S', 59, 'SSW', 'S', 26, 35, 83, 81, 1018.4, 1020.6, 8, 8, 20.3, 20.5, 'Yes', 'Yes'), ('3/18/2017', 19.3, 25.8, 45.8, 2.8, 3.6, 'SSE', 65, 'SE', 'ESE', 24, 22, 88, 79, 1022.9, 1022.2, 8, 7, 21.8, 24.1, 'Yes', 'Yes'), ('3/19/2017', 21.6, 26.2, 4.2, 4.8, 5.5, 'ESE', 57, 'E', 'ENE', 28, 24, 86, 76, 1020.3, 1017.9, 7, 7, 23.7, 25.3, 'Yes', 'No'), ('3/20/2017', 23.7, 27.9, 0.2, 8.4, 4.4, 'NNE', 39, 'NE', 'NE', 11, 20, 74, 66, 1018.5, 1015.6, 7, 7, 25.8, 26.9, 'No', 'No'), ('3/21/2017', 23.3, 27.1, 0.0, 5.2, 1.5, 'NNE', 30, 'NNE', 'E', 11, 17, 77, 72, 1015.7, 1012.6, 7, 6, 24.5, 26.0, 'No', 'Yes'), ('3/22/2017', 22.3, 31.9, 25.6, 6.0, 4.4, 'WSW', 63, 'SE', 'E', 4, 19, 82, 57, 1012.6, 1010.7, 7, 6, 23.9, 29.8, 'Yes', 'Yes'), ('3/23/2017', 20.7, 23.3, 18.2, 4.8, 0.2, 'SSW', 41, 'SSW', 'SSW', 19, 20, 72, 71, 1018.5, 1017.4, 7, 8, 21.5, 22.2, 'Yes', 'Yes'), ('3/24/2017', 18.5, 24.1, 10.2, 7.8, 5.5, 'S', 41, 'W', 'SSW', 13, 20, 85, 70, 1019.9, 1019.1, 2, 7, 20.4, 21.7, 'Yes', 'Yes'), ('3/25/2017', 19.2, 24.5, 4.8, 3.2, 4.9, 'ENE', 26, 'WNW', 'NE', 11, 13, 81, 58, 1017.8, 1014.1, 6, 7, 20.2, 24.2, 'Yes', 'No'), ('3/26/2017', 18.9, 26.5, 0.0, 3.0, 11.0, 'ENE', 28, 'WNW', 'E', 13, 19, 74, 66, 1015.9, 1014.7, 1, 2, 21.3, 26.0, 'No', 'No'), ('3/27/2017', 19.2, 27.0, 0.0, 5.8, 11.0, 'NNE', 41, 'W', 'NE', 11, 22, 76, 62, 1017.1, 1012.3, 1, 1, 21.8, 26.0, 'No', 'No'), ('3/28/2017', 21.2, 23.8, 0.0, 7.4, 0.0, 'SSW', 54, 'SSW', 'S', 19, 11, 76, 69, 1013.9, 1012.4, 7, 8, 21.8, 23.6, 'No', 'No'), ('3/29/2017', 21.4, 28.8, 0.0, 2.4, 8.4, 'E', 30, 'E', 'E', 2, 22, 84, 71, 1012.3, 1007.4, 8, 1, 22.5, 27.0, 'No', 'Yes'), ('3/30/2017', 22.5, 26.0, 2.4, 7.4, 0.0, 'SSW', 69, 'NNE', 'SSW', 19, 28, 70, 88, 1007.0, 1007.7, 8, 8, 25.2, 19.2, 'Yes', 'Yes'), ('3/31/2017', 15.3, 22.6, 42.4, 4.8, 9.9, 'SW', 54, 'W', 'S', 20, 28, 56, 53, 1016.4, 1015.6, 4, 2, 16.9, 21.6, 'Yes', 'No'), ('4/1/2017', 14.5, 25.6, 0.0, 4.8, 10.7, 'SSE', 35, 'W', 'ESE', 17, 17, 63, 48, 1018.2, 1016.6, 1, 2, 17.1, 22.5, 'No', 'No'), ('4/2/2017', 17.0, 22.0, 0.0, 4.8, 5.8, 'SSE', 50, 'SSW', 'SSE', 15, 22, 66, 59, 1025.1, 1024.7, 6, 6, 19.8, 20.1, 'No', 'Yes'), ('4/3/2017', 14.8, 22.0, 33.8, 4.2, 1.5, 'SSE', 50, 'W', 'ESE', 19, 24, 90, 49, 1028.4, 1026.3, 8, 7, 15.7, 21.8, 'Yes', 'Yes'), ('4/4/2017', 14.9, 22.8, 7.8, 0.4, 6.4, 'SE', 41, 'WNW', 'SSE', 15, 20, 78, 60, 1028.1, 1026.3, 3, 6, 17.9, 20.7, 'Yes', 'No'), ('4/5/2017', 14.1, 23.3, 0.4, 5.4, 10.2, 'ESE', 37, 'W', 'ESE', 9, 22, 72, 45, 1026.1, 1023.3, 3, 3, 18.1, 22.9, 'No', 'No'), ('4/6/2017', 13.2, 23.4, 0.2, 6.0, 8.7, 'ESE', 24, 'W', 'ENE', 17, 15, 69, 42, 1026.2, 1023.9, 2, 3, 17.1, 23.2, 'No', 'No'), ('4/7/2017', 14.1, 23.8, 0.0, 3.4, 10.6, 'ENE', 28, 'WNW', 'E', 11, 13, 69, 41, 1028.4, 1025.7, 2, 2, 18.7, 23.7, 'No', 'No'), ('4/8/2017', 14.9, 24.9, 0.0, 5.0, 9.8, 'ENE', 37, 'WNW', 'NE', 13, 20, 68, 49, 1026.2, 1021.4, 4, 4, 18.4, 23.1, 'No', 'No'), ('4/9/2017', 15.5, 28.7, 0.0, 7.0, 9.6, 'WNW', 67, 'NW', 'NNE', 7, 20, 62, 35, 1015.3, 1007.1, 1, 4, 20.1, 27.9, 'No', 'Yes'), ('4/10/2017', 11.7, 17.9, 8.8, 7.8, 6.1, 'W', 54, 'WNW', 'W', 26, 26, 51, 56, 1009.3, 1008.5, 7, 7, 13.9, 15.7, 'Yes', 'No'), ('4/11/2017', 13.8, 23.0, 0.0, 3.6, 2.1, 'SSW', 54, 'W', 'SSW', 22, 26, 56, 48, 1017.2, 1017.3, 7, 7, 17.9, 22.2, 'No', 'Yes'), ('4/12/2017', 15.0, 22.7, 9.4, 4.2, 2.8, 'SSW', 43, 'W', 'SSW', 19, 17, 71, 75, 1023.7, 1022.2, 7, 7, 17.4, 20.2, 'Yes', 'Yes'), ('4/13/2017', 15.3, 23.6, 19.8, 2.4, 9.2, 'SSE', 31, 'W', 'SSE', 17, 20, 80, 51, 1023.8, 1020.9, 4, 3, 17.3, 22.6, 'Yes', 'No'), ('4/14/2017', 13.9, 24.7, 0.0, 4.0, 10.8, 'W', 26, 'WNW', 'SE', 11, 15, 69, 41, 1022.1, 1019.3, 1, 1, 17.2, 23.5, 'No', 'No'), ('4/15/2017', 13.2, 23.8, 0.0, 5.2, 9.8, 'W', 26, 'W', 'ESE', 13, 17, 72, 55, 1021.0, 1018.7, 1, 4, 16.5, 22.0, 'No', 'No'), ('4/16/2017', 15.2, 26.9, 0.0, 4.4, 8.1, 'WSW', 39, 'W', 'WSW', 13, 9, 75, 30, 1020.0, 1017.4, 3, 5, 18.2, 26.2, 'No', 'No'), ('4/17/2017', 14.2, 24.1, 0.0, 3.0, 8.9, 'W', 24, 'WNW', 'ESE', 15, 13, 68, 55, 1024.4, 1022.1, 2, 2, 17.4, 22.3, 'No', 'No'), ('4/18/2017', 16.0, 24.3, 0.0, 4.0, 9.3, 'ESE', 24, 'W', 'E', 15, 17, 73, 55, 1027.0, 1025.3, 1, 1, 19.2, 23.0, 'No', 'No'), ('4/19/2017', 15.2, 24.9, 0.0, 4.6, 6.1, 'SE', 30, 'W', 'SE', 17, 15, 72, 63, 1030.6, 1028.1, 3, 6, 17.7, 22.3, 'No', 'No'), ('4/20/2017', 16.2, 24.0, 0.2, 3.8, 9.9, 'E', 30, 'WNW', 'ENE', 9, 20, 83, 48, 1030.3, 1027.5, 4, 2, 19.0, 23.0, 'No', 'No'), ('4/21/2017', 14.4, 23.9, 0.0, 4.0, 7.2, 'ENE', 26, 'WNW', 'E', 15, 17, 68, 58, 1028.4, 1024.8, 5, 6, 17.9, 22.4, 'No', 'No'), ('4/22/2017', 17.7, 24.1, 0.0, 4.2, 3.5, 'N', 19, 'NNE', 'ENE', 2, 15, 68, 60, 1025.9, 1022.2, 7, 5, 19.9, 22.5, 'No', 'No'), ('4/23/2017', 15.9, 26.7, 0.0, 3.6, 9.5, 'E', 22, 'WNW', 'ESE', 11, 17, 74, 58, 1024.1, 1020.9, 1, 2, 18.5, 23.6, 'No', 'No'), ('4/24/2017', 15.7, 23.9, 0.0, 3.0, 10.0, 'NNE', 24, 'W', 'E', 15, 17, 74, 61, 1022.7, 1018.4, 1, 3, 18.2, 22.7, 'No', 'No'), ('4/25/2017', 18.2, 26.7, 0.0, 4.4, 3.0, 'NW', 39, 'E', 'NW', 4, 22, 69, 65, 1014.0, 1008.8, 7, 7, 20.6, 21.9, 'No', 'Yes'), ('4/27/2017', 12.1, 20.0, 0.4, 7.0, 8.2, 'S', 46, 'W', 'S', 22, 24, 46, 45, 1015.8, 1015.2, 2, 4, 13.1, 18.5, 'No', 'No'), ('4/28/2017', 10.2, 21.8, 0.0, 5.0, 10.4, 'SW', 44, 'W', 'S', 22, 13, 51, 39, 1022.7, 1020.3, 1, 5, 13.5, 20.1, 'No', 'No'), ('4/29/2017', 10.8, 22.7, 0.0, 3.6, 10.5, 'W', 31, 'W', 'ESE', 24, 13, 60, 51, 1020.8, 1018.2, 1, 3, 14.0, 21.2, 'No', 'No'), ('4/30/2017', 14.0, 22.6, 0.0, 3.0, 7.8, 'SSE', 28, 'WNW', 'SE', 15, 13, 66, 59, 1023.0, 1020.9, 7, 4, 17.2, 20.5, 'No', 'No'), ('5/1/2017', 13.2, 25.6, 0.0, 4.0, 9.5, 'NNW', 30, 'W', 'N', 11, 19, 78, 40, 1019.5, 1014.9, 5, 5, 15.9, 24.2, 'No', 'No'), ('5/2/2017', 14.6, 23.9, 0.0, 5.0, 8.4, 'SSW', 39, 'W', 'SSW', 17, 15, 65, 33, 1017.5, 1016.0, 3, 6, 17.2, 23.2, 'No', 'Yes'), ('5/3/2017', 14.9, 18.4, 1.4, 5.0, 3.4, 'S', 43, 'S', 'SSE', 17, 15, 61, 67, 1027.0, 1027.3, 6, 8, 16.9, 16.3, 'Yes', 'Yes'), ('5/4/2017', 11.8, 20.0, 3.8, 3.8, 3.3, 'W', 24, 'WNW', 'ESE', 13, 13, 78, 45, 1031.6, 1029.4, 6, 7, 14.7, 19.5, 'Yes', 'No'), ('5/5/2017', 12.7, 21.6, 0.4, 2.4, 8.5, 'E', 26, 'WNW', 'ENE', 15, 20, 74, 54, 1031.2, 1027.8, 1, 1, 15.1, 20.5, 'No', 'No'), ('5/6/2017', 12.7, 26.2, 0.0, 4.0, 8.4, 'NNW', 43, 'W', 'N', 11, 13, 77, 39, 1025.9, 1021.1, 7, 6, 14.8, 25.2, 'No', 'No'), ('5/7/2017', 14.6, 22.2, 0.2, 4.0, 10.0, 'W', 50, 'W', 'ESE', 22, 13, 47, 25, 1023.6, 1023.2, 1, 1, 17.2, 21.1, 'No', 'No'), ('5/8/2017', 10.2, 20.1, 0.0, 4.8, 9.9, 'SSW', 33, 'W', 'SE', 22, 20, 49, 41, 1027.9, 1025.1, 2, 1, 12.2, 18.9, 'No', 'No'), ('5/9/2017', 10.7, 21.0, 0.0, 9.6, 7.5, 'SSE', 31, 'W', 'S', 19, 13, 67, 45, 1026.9, 1024.0, 5, 1, 13.3, 19.8, 'No', 'No'), ('5/10/2017', 10.5, 21.7, 0.0, 3.4, 10.0, 'W', 37, 'W', 'SE', 20, 13, 70, 52, 1025.1, 1021.9, 1, 1, 13.3, 20.3, 'No', 'No'), ('5/11/2017', 10.9, 22.1, 0.0, 2.0, 8.5, 'W', 30, 'W', 'SSE', 24, 19, 73, 56, 1024.7, 1022.9, 1, 7, 13.4, 19.7, 'No', 'No'), ('5/12/2017', 12.5, 19.6, 0.4, 2.6, 1.7, 'WNW', 26, 'W', 'ESE', 19, 17, 78, 71, 1027.0, 1024.5, 7, 7, 14.1, 18.5, 'No', 'Yes'), ('5/13/2017', 14.0, 21.3, 3.2, 0.6, 7.3, 'ENE', 28, 'WNW', 'NE', 11, 17, 86, 67, 1024.9, 1021.7, 1, 7, 15.8, 20.1, 'Yes', 'No'), ('5/14/2017', 14.7, 18.7, 0.0, 4.0, 0.3, 'ESE', 26, 'SW', 'SE', 7, 9, 89, 74, 1021.9, 1019.2, 7, 7, 16.3, 18.1, 'No', 'Yes'), ('5/15/2017', 13.1, 20.8, 5.2, 1.6, 5.5, 'SSW', 43, 'W', 'SSW', 20, 20, 75, 49, 1017.1, 1014.0, 7, 1, 14.6, 20.2, 'Yes', 'No'), ('5/16/2017', 11.1, 21.9, 0.0, 3.0, 9.9, 'W', 33, 'W', 'SSE', 19, 11, 59, 39, 1017.9, 1016.5, 1, 1, 14.4, 20.3, 'No', 'No'), ('5/17/2017', 9.8, 20.2, 0.0, 3.4, 9.5, 'W', 28, 'W', 'E', 17, 17, 72, 52, 1023.4, 1021.3, 1, 2, 12.7, 19.6, 'No', 'No'), ('5/18/2017', 12.6, 21.5, 0.0, 3.6, 6.4, 'E', 33, 'WNW', 'E', 15, 22, 79, 62, 1027.0, 1024.7, 7, 4, 14.8, 20.2, 'No', 'No'), ('5/19/2017', 14.8, 20.4, 0.0, 1.4, 0.5, 'NNE', 43, 'NE', 'NNE', 11, 17, 78, 72, 1025.3, 1020.9, 7, 7, 19.5, 20.2, 'No', 'Yes'), ('5/20/2017', 16.7, 23.2, 14.6, 1.0, 5.4, 'NE', 35, 'NW', 'WNW', 11, 9, 86, 58, 1017.9, 1015.4, 8, 3, 17.5, 22.8, 'Yes', 'No'), ('5/21/2017', 13.8, 23.5, 0.0, 4.0, 9.2, 'W', 30, 'W', 'ESE', 22, 17, 69, 49, 1021.0, 1019.3, 2, 1, 15.7, 21.9, 'No', 'No'), ('5/22/2017', 13.0, 21.0, 0.0, 1.0, 6.9, 'W', 22, 'W', 'E', 17, 11, 84, 65, 1024.7, 1021.9, 2, 4, 14.7, 20.1, 'No', 'No'), ('5/23/2017', 14.7, 22.6, 0.0, 2.4, 8.8, 'ENE', 24, 'WNW', 'ENE', 11, 17, 82, 65, 1022.1, 1017.2, 1, 2, 16.6, 22.4, 'No', 'No'), ('5/24/2017', 14.8, 22.7, 0.8, 3.4, 9.0, 'WSW', 54, 'NNW', 'WSW', 7, 22, 77, 31, 1014.7, 1012.7, 5, 1, 16.7, 22.5, 'No', 'No'), ('5/25/2017', 11.6, 21.4, 0.0, 5.6, 9.6, 'WSW', 33, 'W', 'E', 22, 11, 60, 43, 1021.3, 1018.9, 1, 0, 14.0, 19.7, 'No', 'No'), ('5/26/2017', 10.6, 20.8, 0.0, 1.8, 9.8, 'W', 30, 'W', 'S', 19, 13, 58, 56, 1021.7, 1019.7, 2, 3, 14.0, 19.6, 'No', 'No'), ('5/27/2017', 12.6, 20.6, 0.0, 2.8, 7.0, 'W', 24, 'W', 'ENE', 19, 15, 77, 65, 1021.8, 1017.6, 3, 3, 14.2, 19.4, 'No', 'No'), ('5/28/2017', 11.9, 23.7, 0.0, 2.4, 8.4, 'NNW', 48, 'W', 'NW', 13, 24, 83, 37, 1013.2, 1009.0, 1, 6, 13.3, 23.2, 'No', 'No'), ('5/29/2017', 11.4, 18.3, 0.0, 5.2, 9.4, 'W', 56, 'SW', 'WSW', 15, 19, 44, 30, 1017.8, 1018.6, 1, 1, 13.5, 17.5, 'No', 'No'), ('5/30/2017', 7.1, 17.1, 0.0, 3.4, 9.7, 'WSW', 39, 'W', 'WNW', 17, 17, 60, 37, 1023.1, 1020.1, 1, 6, 9.7, 16.7, 'No', 'No'), ('5/31/2017', 9.7, 16.3, 0.0, 3.4, 7.8, 'SSW', 52, 'SSW', 'SSW', 20, 28, 58, 43, 1025.4, 1026.0, 6, 4, 13.4, 15.9, 'No', 'No'), ('6/1/2017', 8.0, 18.3, 0.0, 4.8, 9.7, 'WSW', 43, 'W', 'SSW', 28, 26, 54, 39, 1032.8, 1031.2, 1, 1, 10.3, 17.8, 'No', 'No'), ('6/2/2017', 8.5, 18.1, 0.0, 3.2, 4.8, 'SSW', 41, 'W', 'SSW', 24, 20, 61, 50, 1032.7, 1030.8, 1, 4, 10.7, 16.4, 'No', 'No'), ('6/3/2017', 10.7, 17.4, 0.0, 3.4, 2.1, 'S', 41, 'W', 'S', 20, 22, 64, 66, 1031.1, 1028.8, 4, 7, 13.4, 16.4, 'No', 'Yes'), ('6/4/2017', 10.5, 19.7, 1.4, 0.6, 6.8, 'W', 28, 'W', 'SSE', 20, 17, 77, 57, 1028.3, 1024.5, 1, 2, 12.2, 19.0, 'Yes', 'No'), ('6/5/2017', 9.4, 19.6, 0.0, 2.8, 9.4, 'W', 28, 'W', 'WSW', 20, 7, 78, 41, 1025.0, 1021.5, 3, 5, 11.5, 19.2, 'No', 'No'), ('6/6/2017', 9.1, 17.9, 0.0, 2.2, 7.2, 'WSW', 59, 'W', 'S', 19, 15, 58, 43, 1019.7, 1017.7, 2, 2, 11.2, 14.7, 'No', 'Yes'), ('6/7/2017', 8.8, 15.5, 54.6, 2.6, 0.0, 'SSW', 56, 'SSW', 'S', 24, 17, 82, 85, 1020.2, 1019.6, 8, 8, 13.3, 14.2, 'Yes', 'Yes'), ('6/8/2017', 12.4, 18.1, 61.0, 1.8, 1.3, 'SE', 44, 'W', 'S', 17, 15, 91, 84, 1024.2, 1023.4, 5, 6, 13.3, 16.9, 'Yes', 'Yes'), ('6/9/2017', 10.4, 18.9, 3.4, 1.6, 4.8, 'ESE', 52, 'W', 'SSE', 19, 28, 90, 64, 1027.6, 1026.7, 6, 7, 12.5, 18.2, 'Yes', 'Yes'), ('6/10/2017', 12.5, 18.1, 38.8, 3.6, 0.2, 'SSE', 50, 'SE', 'SSE', 17, 15, 85, 70, 1031.9, 1030.2, 7, 7, 15.8, 17.5, 'Yes', 'Yes'), ('6/11/2017', 12.5, 17.2, 2.8, 1.6, 0.2, 'WNW', 20, 'W', 'W', 15, 6, 90, 85, 1029.2, 1025.9, 5, 6, 13.1, 16.0, 'Yes', 'Yes'), ('6/12/2017', 11.3, 20.4, 1.2, 0.8, 7.5, 'SSE', 26, 'WNW', 'SSE', 15, 15, 92, 59, 1025.0, 1024.0, 2, 3, 11.6, 19.1, 'Yes', 'No'), ('6/13/2017', 9.5, 18.7, 0.0, 2.2, 9.1, 'SSE', 37, 'W', 'SSE', 20, 22, 82, 62, 1030.0, 1029.1, 2, 3, 11.2, 18.2, 'No', 'Yes'), ('6/14/2017', 11.1, 17.8, 2.6, 1.8, 2.9, 'WNW', 24, 'WNW', 'ENE', 13, 9, 82, 78, 1031.3, 1028.4, 3, 7, 13.3, 17.4, 'Yes', 'No'), ('6/15/2017', 10.7, 20.1, 0.6, 1.2, 6.4, 'W', 22, 'W', 'ENE', 13, 15, 89, 69, 1027.9, 1024.4, 2, 6, 11.9, 18.7, 'No', 'No'), ('6/16/2017', 11.9, 17.3, 0.0, 1.6, 0.2, 'WNW', 26, 'W', 'WSW', 19, 7, 79, 69, 1026.2, 1023.5, 7, 7, 13.3, 17.2, 'No', 'No'), ('6/17/2017', 13.2, 19.1, 0.0, 1.0, 0.2, 'SSW', 26, 'WNW', 'SSW', 9, 13, 81, 67, 1024.3, 1021.8, 7, 7, 14.6, 17.4, 'No', 'Yes'), ('6/18/2017', 11.3, 18.0, 1.8, 2.0, 6.3, 'S', 52, 'SW', 'SSW', 13, 28, 83, 62, 1025.7, 1025.8, 3, 5, 12.9, 17.6, 'Yes', 'No'), ('6/19/2017', 11.2, 18.3, 0.4, 2.2, 1.9, 'SSW', 37, 'W', 'S', 17, 19, 79, 69, 1030.4, 1028.4, 6, 7, 12.7, 17.2, 'No', 'Yes'), ('6/20/2017', 11.3, 20.0, 4.4, 2.2, 5.8, 'W', 26, 'W', 'SSW', 19, 9, 88, 60, 1028.7, 1025.2, 6, 1, 11.9, 19.7, 'Yes', 'No'), ('6/21/2017', 8.6, 19.6, 0.0, 2.0, 7.8, 'SSE', 37, 'W', 'SSE', 22, 20, 73, 52, 1025.9, 1025.3, 2, 2, 10.5, 17.9, 'No', 'No'), ('6/22/2017', 9.3, 19.2, 0.0, 2.0, 9.2, 'W', 30, 'W', 'ESE', 20, 7, 78, 53, 1028.5, 1024.6, 2, 2, 11.0, 18.7, 'No', 'No'), ('6/23/2017', 9.4, 17.7, 0.0, 2.4, 2.7, 'W', 24, 'WNW', 'N', 15, 13, 85, 56, 1020.8, 1015.0, 6, 6, 10.2, 17.3, 'No', 'No'), ('6/24/2017', 10.1, 19.3, 0.0, 1.4, 9.3, 'W', 43, 'W', 'W', 17, 19, 56, 35, 1017.3, 1015.1, 5, 2, 12.4, 19.0, 'No', 'No'), ('6/25/2017', 7.6, 19.3, 0.0, 3.4, 9.4, 'W', 35, 'W', 'W', 13, 13, 73, 32, 1018.6, 1015.4, 1, 1, 9.4, 18.8, 'No', 'No')]
df=pd.DataFrame(tupledata)
df

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
3267,6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
3268,6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
3269,6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No